### ISSUE TITLE
Filter example is broken: Report "no data to warp"

### ISSUE THREAD

**Issue by jcfr** [Kitware/vtk-js#1]
Go to http://kitware.github.io/vtk-js/examples/Filter/index.html

Open the developer console

Move the slider

![screenshot from 2016-06-02 02-45-24](https://cloud.githubusercontent.com/assets/219043/15736199/183354fc-286c-11e6-8b83-a9f468947c4a.png)

**Comment by jcfr** [comment]
Cc: @scottwittenburg

**Comment by jourdain** [comment]
Hi Jc,

it was WIP before Scott left for vacations. 
I'm sure he'll finish it when he come back.

Seb

**Comment by jcfr** [comment]
Good to know. Thanks for the note.
Jc

On Thu, Jun 2, 2016 at 12:43 PM, Sebastien Jourdain <
notifications@github.com> wrote:

> Hi Jc,
>
> it was WIP before Scott left for vacations.
> I'm sure he'll finish it when he come back.
>
> Seb
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kitware/vtk-js/issues/1#issuecomment-223350229>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AANXo_pc4Vj29ZQcSakgrMzHP9uaQy-eks5qHwgvgaJpZM4IsQEX>
> .
>



-- 
+1 919 869 8849
