### ISSUE TITLE
vtk-js documentation error

### ISSUE THREAD

**Issue by fraser29** [Kitware/vtk-js#1006]
Hello, 
I believe that there is a typo/error in the ES6 usage documentation fro VTK.js at:
https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

The information regarding importing extra loaders says:

```
// Optional if you want to load *.css and *.module.css files
var cssRules = require('vtk.js/Utilities/config/dependency.js').webpack.css.rules;
```

But should read:

```
// Optional if you want to load *.css and *.module.css files
var cssRules = require('vtk.js/Utilities/config/dependency.js').webpack.css;
```

Regards

**Comment by thewtex** [comment]
@fraser29 have you tested this with the latest version of vtk.js? This is how it is used in a tested context:

  https://github.com/Kitware/itk-vtk-viewer/blob/3649d28fcf51626a335cecc5d6fc4f2fc1580338/webpack.config.js#L14

**Comment by fraser29** [comment]
Ah correct - vtk.js/Utilities/config/dependency.js is updated. 
Sorry. 

Thanks
