### ISSUE TITLE
OpenGL RenderWindow: Make background image optional?

### ISSUE THREAD

**Issue by swederik** [Kitware/vtk-js#1007]
Hello!

I've been using the GenericRenderWindow while integrating vtk-js for image display in the OHIF Viewer. It seems to be working fine, but I noticed it is creating an `<img>` element which spans the whole page and ends up interfering with our drag/drop implementation.

It looks like it's being created here:

https://github.com/Kitware/vtk-js/blob/5ceb2af2bf9e3b98c241d6cfc33497a32f524cd7/Sources/Rendering/OpenGL/RenderWindow/index.js#L1079

and it seems like it's meant to display an optional background image. (or is there some other use for it?)

Would you accept a PR to make the addition of this HTML element to the DOM optional? i.e. if `setBackgroundImage` is never called, bgImage is never created.

Thanks!

**Comment by jourdain** [comment]
Sure, that image background is to allow the use of vtk.js with a server to enable remote rendering while keeping the camera handling local.

**Comment by bernland** [comment]
In https://kitware.github.io/vtk-js/examples/ImageStream.html, the background image is updated AFTER dragging and then clicking on the foreground wireframe cone.

On the other hand, the background image in https://kitware.github.io/vtk-js/examples/RemoteView.html is updated continuously.

Is this the way it is supposed to be or can continuous updates also be configured using ImageStream objects?

**Comment by jourdain** [comment]
RemoteView use ImageStream under the cover. So the continuous update is expected. I'm not sure why you only get the end of interaction update. Maybe the RemoteView does a better (/updated) initialization that the example does not do?

**Comment by jourdain** [comment]
I think it might be linked to the fact that we send camera rather than mouse. But the example should be fixed to reflect the RemoteView approach.
