### ISSUE TITLE
PointData Arrays not loaded

### ISSUE THREAD

**Issue by bilke** [Kitware/vtk-js#101]
I have converted  [this unstructured grid file](https://github.com/Kitware/vtk-js/files/735320/square_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu.zip) with `vtkDataConverter` (passing the `-e` option) to the following vtk-js format file

https://github.com/bilke/vtk-js-test/tree/master/dist/data/square_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu

I then try to read it:

```javascript
const reader = vtkHttpDataSetReader.newInstance({ enableArray: true, fetchGzip: true });
reader.setUrl(`./data/square_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu`).then((reader, dataset) => {
  console.log('Metadata loaded with the geometry', dataset);

  reader.loadData().then((reader, dataset) =>{
    reader.getArrays().forEach(array => {
      console.log('-', array.name, array.location, ':', array.enable);
    });
  });
});
```

But unfortunately there are no point arrays defined (no console output and I also cannot map scalars to colors with one of the arrays). The [index.json](https://github.com/bilke/vtk-js-test/blob/master/dist/data/square_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu/index.json) looks valid. Do you have any ideas what's wrong here?

Also `reader.listArrays` as [stated in docs](https://kitware.github.io/vtk-js/api/HttpDataSetReader.html) seems not to be a valid variable or function.

**Comment by jourdain** [comment]
Thanks for reporting the issue. Looking at the index.json, it seems that we forgot to update the script when we update the DataAttribute class which has change some of the structure.

If you can't wait for us to fix it, you can probably edit manually that json file so it has a structure similar to what is described here: https://kitware.github.io/vtk-js/docs/structures_PolyData.html

**Comment by bilke** [comment]
Thanks for pointing me to the current structure.

Is ` reader.getArrays().forEach(array => {` the correct way to iterate over the arrays?

**Comment by jourdain** [comment]
I need to look at the reader and make sure it does understand the `new` structure. I may have to fix some stuff on the reader anyway.

**Comment by jourdain** [comment]
<img width="1457" alt="screen shot 2017-01-27 at 9 35 53 am" src="https://cloud.githubusercontent.com/assets/294518/22378889/7019620a-e474-11e6-90da-15920c205e74.png">

Just pushed a fix for the generator

**Comment by jourdain** [comment]
You can see the change here: https://github.com/Kitware/vtk-js/pull/102/files

**Comment by jourdain** [comment]
Then you may want to do `mapper.setInterpolateScalarsBeforeMapping(true)`

to get

<img width="854" alt="screen shot 2017-01-27 at 9 54 49 am" src="https://cloud.githubusercontent.com/assets/294518/22379464/af39a984-e476-11e6-911c-3ec3fb172088.png">
