### ISSUE TITLE
Unable to change color of object with actor.getProperty().setColor

### ISSUE THREAD

**Issue by longhuy322000** [Kitware/vtk-js#1011]
I am unable to change the color of the object with actor.getProperty().setColor. It only works with pure red, blue or green, but not with the combination of red, green and blue. I tried to set scalarVisibility in mapper to False as well, but it still didn't work. Could you please tell me what I did wrong?

**Comment by jourdain** [comment]
I'm guessing that you figure it out?

**Comment by longhuyn** [comment]
Yeah I got it. Thank you! I have two questions, but not related to this problem though.
1. Does VTK js have an API that draws a string in the render window?
2. Does VTK support time? For example, I want to move an object from one coordinate to another coordinate respects to time. Does VTK have any mechanism to do this?
Thank you again!

**Comment by jourdain** [comment]
1. Not yet but you can do that in plain HTML easily.
2. Not really but time can be handled at the application level.

**Comment by longhuyn** [comment]
1. I agree. But if I move the object around, the label of the object doesn't move with the object at the same time

**Comment by jourdain** [comment]
We have a mapper that will give you callback with (x,y) of a given point in 3D. 

https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html

Something is broken with the example, but that's the idea.

**Comment by SSPollock** [comment]
If you figured it out, do share.

**Comment by a3VonG** [comment]
In case it's useful for other people that run into the issue:
 I solved it by setting the [scalarVisibility](url) to false on the mapper.
