### ISSUE TITLE
Its possible Moving Camera without rotating on actor?

### ISSUE THREAD

**Issue by aneeshikmat** [Kitware/vtk-js#1020]
Hi, Its possible Moving Camera without rotating on actor?

My Case: I have an actor, and this actor most be move with camera, but current behavior its rotate on item like this example [VR Example](https://kitware.github.io/vtk-js/examples/VR.html).

Its possible to change this behavior for some actor only, and keep volume render with rotate track behavior? 

Note: Actor Position & Orientation is work fine. but last issue is on view direction from camera 

Thanks

**Comment by jourdain** [comment]
I'm not sure to see what you mean. But you can have some other renderer in the scene with their own camera. In which case those won't be affected by the camera of the main view.

**Comment by aneeshikmat** [comment]
Yes jourdain, Thats true, I make a new camera...but maybe I think my issue is when I need to get orientation direction. Look at this image

<img src="https://imgur.com/Qx3qxvf" />

For manual or test case To fix issue. I need to rotate direction for actor, so that if I can stop change look position for camera for actor, issue will be resolved, or I need to find way to calculate rotate degree value to set in rotate method.

**Comment by aneeshikmat** [comment]
I resolve this issue by doing one of these trick:

1) first one: not optimal but its good to got one of rotate vector, pitch, yaw, or roll like this:
```
var q = {};
    q.x = controllersGamePad[0].pose.orientation[0];
    q.y = controllersGamePad[0].pose.orientation[1];
    q.z = controllersGamePad[0].pose.orientation[2];
    q.w = controllersGamePad[0].pose.orientation[3];
    var yaw = Math.atan2(2.0*(q.y*q.z + q.w*q.x), q.w*q.w - q.x*q.x - q.y*q.y + q.z*q.z);
    var pitch = Math.asin(-2.0*(q.x*q.z - q.w*q.y));
    var roll = Math.atan2(2.0*(q.x*q.y + q.w*q.z), q.w*q.w + q.x*q.x - q.y*q.y - q.z*q.z);
    actor.rotateX(radians_to_degrees(yaw));
    actor.rotateY(radians_to_degrees(pitch));
    actor.rotateZ(radians_to_degrees(roll));
```

2) Second one its work perfect and smoothly, and its work by calculate degree from w Quaternion, and then we get Axis-Angle, for example: 
```
var Θ = Math.acos(controllersGamePad[0].pose.orientation[3])*2;
    var x1 = controllersGamePad[0].pose.orientation[0] / Math.sin(Math.acos(controllersGamePad[0].pose.orientation[3]));
    var y1 = controllersGamePad[0].pose.orientation[1] / Math.sin(Math.acos(controllersGamePad[0].pose.orientation[3]));
    var z1 = controllersGamePad[0].pose.orientation[2] / Math.sin(Math.acos(controllersGamePad[0].pose.orientation[3]));

actor.rotateWXYZ(radians_to_degrees(Θ), x1, y1, z1);
```
