### ISSUE TITLE
Add ability to remove WidgetManager from attached View

### ISSUE THREAD

**Issue by matthewma7** [Kitware/vtk-js#1022]
Currently, it is possible to remove a widget from WidgetManger with`widgetManager.removeWidget(widget);` but not possible to remove `WidgetManger` from the attached `View`. 
Would like to ask such feature with this feature request.

**Comment by jourdain** [comment]
What would be the usage?

**Comment by matthewma7** [comment]
For my use case. I am using ImageCroppingWidget to annotation a region of the Views. The functionality would add and remove the annotation on views dynamically. 
This is feature request is based on an assumption that the WidgetManger should be removed from Views to release certain resources.

**Comment by jourdain** [comment]
Yes but a widgetManager is supposed to go with it's view. So in some way, if you have a view, you should have a widgetManager. When you trash your view, you trash the widgetManager.

I agree that it would be good to have a way to detach a widgetManager from its view, but practically there is no need for it.

**Comment by matthewma7** [comment]
Ah, I see. It's more or less just keeping things clean mentally.
