### ISSUE TITLE
problems installing vtk.js

### ISSUE THREAD

**Issue by johannesdd** [Kitware/vtk-js#1023]
Hi,
I have to use vtk.js as a library for a standard web project. I tried to install it under windows 10 and 7 and Ubuntu. It seems to always deliver the same issues and frankly I dont know where to start. I followed the instruction given in the getting started guide.
1) npm init
2) npm install vtk.js --save
and at this stage the mistakes starts to pop up:
<pre><font color="#8AE234"><b>imm@imm-ThinkPad-T500</b></font>:<font color="#729FCF"><b>~/Documents/Projects/Work/Trockenuebung/vtkjs07</b></font>$ npm install vtk.js --save
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#3465A4">notice</font></span> created a lockfile as package-lock.json. You should commit this file.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> vtk.js@8.3.15 requires a peer of wslink@^0.1.8 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> vtk.js@8.3.15 requires a peer of shader-loader@^1.3.1 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> vtk.js@8.3.15 requires a peer of worker-loader@^2.0.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> vtkjs07@1.0.0 No description
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> vtkjs07@1.0.0 No repository field.
+ vtk.js@8.3.15
added 603 packages from 773 contributors and audited 4711 packages in 12.752s
found <font color="#EF2929">16</font> vulnerabilities (2 <b>low</b>, 7 <font color="#FCE94F">moderate</font>, 7 <font color="#EF2929">high</font>)
  run `npm audit fix` to fix them, or `npm audit` for details</pre>

and the issues are : 
<pre><font color="#555753">                                                                                </font>
<font color="#555753"> </font>                      === npm audit security report ===                       <font color="#555753"> </font>
<font color="#555753">                                                                                </font>
<font color="#555753">┌──────────────────────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font>                                Manual Review                                 <font color="#555753">│</font>
<font color="#555753">│</font>            Some vulnerabilities require your attention to resolve            <font color="#555753">│</font>
<font color="#555753">│</font>                                                                              <font color="#555753">│</font>
<font color="#555753">│</font>         Visit https://go.npm.me/audit-guide for additional guidance          <font color="#555753">│</font>
<font color="#555753">└──────────────────────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Insufficient Entropy</b>                                         <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=3.1.3 &lt;4.0.0 || &gt;=4.1.2                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>libcipm<font color="#555753"> &gt; </font>npm-lifecycle<font color="#555753"> &gt;</font>         <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> node-gyp<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>hawk<font color="#555753"> &gt; </font>cryptiles                        <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/720                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Insufficient Entropy</b>                                         <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=3.1.3 &lt;4.0.0 || &gt;=4.1.2                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>node-gyp<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>hawk<font color="#555753"> &gt;</font>       <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/720                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Insufficient Entropy</b>                                         <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=3.1.3 &lt;4.0.0 || &gt;=4.1.2                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-lifecycle<font color="#555753"> &gt; </font>node-gyp<font color="#555753"> &gt;</font>        <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> request<font color="#555753"> &gt; </font>hawk<font color="#555753"> &gt; </font>cryptiles                                   <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/720                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Insufficient Entropy</b>                                         <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=3.1.3 &lt;4.0.0 || &gt;=4.1.2                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-registry-client<font color="#555753"> &gt; </font>request<font color="#555753"> &gt;</font>   <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> hawk<font color="#555753"> &gt; </font>cryptiles                                             <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/720                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Insufficient Entropy</b>                                         <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> cryptiles                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=3.1.3 &lt;4.0.0 || &gt;=4.1.2                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>hawk<font color="#555753"> &gt; </font>cryptiles        <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/720                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Out-of-bounds Read</b>                                           <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=0.0.6                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>libcipm<font color="#555753"> &gt; </font>npm-lifecycle<font color="#555753"> &gt;</font>         <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> node-gyp<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>stringstream                            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/664                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Out-of-bounds Read</b>                                           <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=0.0.6                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>node-gyp<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>stringstream <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/664                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Out-of-bounds Read</b>                                           <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=0.0.6                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-lifecycle<font color="#555753"> &gt; </font>node-gyp<font color="#555753"> &gt;</font>        <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> request<font color="#555753"> &gt; </font>stringstream                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/664                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Out-of-bounds Read</b>                                           <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=0.0.6                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-registry-client<font color="#555753"> &gt; </font>request<font color="#555753"> &gt;</font>   <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/664                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Out-of-bounds Read</b>                                           <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> stringstream                                                 <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=0.0.6                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>request<font color="#555753"> &gt; </font>stringstream            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/664                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Prototype Pollution</b>                                          <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=4.17.11                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>cli-table2<font color="#555753"> &gt; </font>lodash               <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/782                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#FCE94F"><b>Moderate</b></font>      <font color="#555753">│</font> <b>Prototype Pollution</b>                                          <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=4.17.11                                                    <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-audit-report<font color="#555753"> &gt; </font>cli-table2<font color="#555753"> &gt;</font>   <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/782                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <b>Low</b>           <font color="#555753">│</font> <b>Prototype Pollution</b>                                          <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=4.17.5                                                     <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>cli-table2<font color="#555753"> &gt; </font>lodash               <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/577                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <b>Low</b>           <font color="#555753">│</font> <b>Prototype Pollution</b>                                          <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=4.17.5                                                     <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-audit-report<font color="#555753"> &gt; </font>cli-table2<font color="#555753"> &gt;</font>   <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> lodash                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/577                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Denial of Service</b>                                            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> http-proxy-agent                                             <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=2.1.0                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-profile<font color="#555753"> &gt; </font>make-fetch-happen<font color="#555753"> &gt;</font> <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> http-proxy-agent                                             <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/607                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
<font color="#555753">┌───────────────┬──────────────────────────────────────────────────────────────┐</font>
<font color="#555753">│</font> <font color="#EF2929"><b>High</b></font>          <font color="#555753">│</font> <b>Denial of Service</b>                                            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Package       <font color="#555753">│</font> https-proxy-agent                                            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Patched in    <font color="#555753">│</font> &gt;=2.2.0                                                      <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Dependency of <font color="#555753">│</font> vtk.js                                                       <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> Path          <font color="#555753">│</font> vtk.js<font color="#555753"> &gt; </font>gl-matrix<font color="#555753"> &gt; </font>npm<font color="#555753"> &gt; </font>npm-profile<font color="#555753"> &gt; </font>make-fetch-happen<font color="#555753"> &gt;</font> <font color="#555753">│</font>
<font color="#555753">│</font>               <font color="#555753">│</font> https-proxy-agent                                            <font color="#555753">│</font>
<font color="#555753">├───────────────┼──────────────────────────────────────────────────────────────┤</font>
<font color="#555753">│</font> More info     <font color="#555753">│</font> https://npmjs.com/advisories/593                             <font color="#555753">│</font>
<font color="#555753">└───────────────┴──────────────────────────────────────────────────────────────┘</font>
found <font color="#EF2929">16</font> vulnerabilities (2 <b>low</b>, 7 <font color="#FCE94F">moderate</font>, 7 <font color="#EF2929">high</font>) in 4711 scanned packages
</pre>

npm audit fix does not help at all:

Did I forgot to install a library or made a mistake while installing nodejs or npm. I have got it to work once in a VM, but shortly after I had to abandon the project and dont know how what I did different back then. Nodejs is at version 11.10.1 and npm at 6.7.0

**Comment by floryst** [comment]
Looks like you successfully installed vtk.js just fine.

The `npm WARN` messages are unmet peer dependencies. Basically, if you want to use vtk.js in your app, you should install those packages (shader-loader and worker-loader are a must, while wslink is optional unless you use remote rendering). 

The audit security report is okay and does not affect apps built on vtk.js. It is due to vtk.js depending on an older version of gl-matrix, which depends on an older version of npm, which is the root cause of all of those security reports. However, those security reports do not affect vtk.js at all, and as such you can continue to use vtk.js despite those vulnerability warnings.
