### ISSUE TITLE
vtkCaptionWidget in vtk.js

### ISSUE THREAD

**Issue by qlj062127** [Kitware/vtk-js#1027]
Hello,
  I want to use the vtkCaptionWidget, but I can't find it in vtk.js. Is there an alternative?

Thanks

**Comment by jourdain** [comment]
That class is not available in vtk.js but a mix of [vtkPixelSpaceCallbackMapper](https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html) and plain HTML should be able to do the trick.

**Comment by qlj062127** [comment]
I'll try. Thank you very much
