### ISSUE TITLE
webvr-polyfill bloats vtkOpenGLRenderWindow when built

### ISSUE THREAD

**Issue by brianhelba** [Kitware/vtk-js#1037]
The `webvr-polyfill` added by https://github.com/Kitware/vtk-js/commit/7678429c6c1c3f48ff2df16fd2eb1b834d14893e is always imported by and depended upon by `vtkOpenGLRenderWindow`, even when no VR functionality is used or needed. For a basic volume rendering application, the built `webvr-polyfill` library is actually larger than `vtk.js` (once tree-shaking happens).

The import and reference of `webvr-polyfill` needs to be moved to only occur within a module that's exclusive to VR rendering. Alternatively, `webvr-polyfill` needs to be removed entirely, and made the responsibility of users to include.

**Comment by jourdain** [comment]
Look at the way we build vtk.js-lite. You should do the same.
