### ISSUE TITLE
Add interaction without re-defining everything?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1044]
Hello,

I would like to add a simple callback function when according to camera moving.

Is there a way that I can simply add operation from the default interaction?

The example using "InteractorStyleManipulator" seems I have to re-define every default action from the beginning

Thank you

**Comment by floryst** [comment]
`camera.onModified(callback)` will call your callback whenever camera properties are modified, i.e. when the camera is moved via interaction or programmatically.

If you just want hooks into interaction events, then the InteractorStyleManipulator will emit StartInteractionEvent, InteractionEvent, and EndInteractionEvent. These can be hooked via `.onStartInteractionEvent(callback)`, `.onInteractionEvent(callback)`, and `.onEndInteractionEvent(callback)`.

**Comment by EJShim** [comment]
Thank you for your perfect solution that I needed
