### ISSUE TITLE
slicing on Scene Explorer

### ISSUE THREAD

**Issue by pramila16** [Kitware/vtk-js#1045]
I am trying to slice .vtkjs file using Scene Explorer web application,referred MultiSliceImageMapper example.

const imageActorK = vtkImageSlice.newInstance();
const data = sceneImporter.getScene()[0].source.getOutputData()
const imageMapperK = vtkImageMapper.newInstance();
imageMapperK.setInputData(data);
imageMapperK.setKSlice(30);
imageActorK.setMapper(imageMapperK);

1)For 'imageActorK.setMapper(imageMapperK)' i am getting error i.e 'i.getExtent is not a is function. Is getExtent() releted to vtkHttpDataSetReader library? As,  in sceneExplorer, file reading done vtkHttpSceneLoader library.
2)what mapper , actor should be used on sceneExplorer for slicing.

**Comment by jourdain** [comment]
The slicing in that case is expecting a vtkImageData while you are actually loading vtkPolyData with the scene loader. That [filter](https://kitware.github.io/vtk-js/examples/Cutter.html) could possibly cut/slice your data but they will appear as lines not as a surface cut. To do those kind of dynamic processing an approach based on ParaViewWeb (like [ParaViewLite](https://kitware.github.io/paraview-lite/) or [ParaViewVisualizer](https://kitware.github.io/visualizer/)) would be better.

**Comment by pramila16** [comment]
Thanks for your prompt response Jourdain.
So, not at all slicing is possible on scene loader?
I have implemented other functionality in vtkjs, will it be possible to combine ParaViewWeb with vtkjs?

**Comment by jourdain** [comment]
What I'm saying is that you can do slicing with vtk.js but I believe that you will get a result than does not match your expectation.

Otherwise, yes you can use ParaViewWeb with vtk.js. Visualizer has a local rendering mode that is using vtk.js while leaving all the data processing on the server side.

**Comment by pramila16** [comment]
Thanks Jourdain
I will try to implement using ParaViewWeb.

**Comment by jourdain** [comment]
You can look at the following links to see how we handle dynamic synchronization of a render window between a client (vtk.js) and a server (VTK/ParaView)
https://github.com/Kitware/VTK/blob/master/Web/Python/vtkmodules/web/render_window_serializer.py
https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/Misc/SynchronizableRenderWindow
https://github.com/Kitware/paraviewweb/blob/master/src/React/Renderers/VtkGeometryRenderer/index.js
