### ISSUE TITLE
set / get Orientation of Prop3D not working

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1050]
I am trying to make a plane actor that is always positioned same as camera's focal point,

and plane normal parallel to camera's direction of projection.

setting position worked fine by using actor.setPosition( focal[0], focal[1], focal[2] ); function,

but I am having problem with setting orientation of this actor.

first of all, actor.getOrientation() returns [undefined], that is different from the documentation which says the default orientation value is [0, 0, 0].

actor.setOrientation(X, Y, Z) or actor.setOrientation([X,Y,Z]) returns error  saying
"macro.js:602 Uncaught TypeError: Cannot read property 'forEach' of undefined"

I also tried to change values of actor.getMatrix(), that resulted rendering of nothing,
and actor.setUserMatrix(matrix) also resulted unexpected change of actor.getMatrix().

is there a way I can properly change (setting) orientation of prop3D?

Thank you

**Comment by EJShim** [comment]
I solved my problem by using setUserMatrix() method, the matrix need to be transposed.

**Comment by shanebenlolo** [comment]
> I solved my problem by using setUserMatrix() method, the matrix need to be transposed.

Do you still have the code you used to accomplish this? I am using setUserMatrix() to rotate an object as well. I've got the object rotating very similarly to your instance, but cannot figure out how to set the pivot point which the object will rotate around. 

I thought I could use setOrigin(actor.getCenter()), but that doesn't seem to do it.
