### ISSUE TITLE
dynamically update vertice position?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1052]
I am trying to make a simple 3D contour using planeSource.

I want to change planeSource's vertex position and render dynamically,

I can see that I can refer to pointdata by using 

planeSource.getOutputData().getPoints().

But modifying this does not change anything rendering plane.

How can I dynamically modify polydata's vertices position and render?

**Comment by EJShim** [comment]
I changed point data by using polydata.getPoints().setPoint(idx, ...[x,y,z]); but it never changes rendering actor. I tried polydata.getPoints().modified(), polydata.modified(), mapper.modified(), or update() functions, none of them worked.. please helpp

**Comment by jourdain** [comment]
The best way to do that is

```
const typedArray = polydata.getPoints().getData();
typedArray[0] = x0;
typedArray[1] = y0;
typedArray[2] = z0;
[...]

polydata.getPoints().modified();
```
And that should do it assuming your pipeline connection is correct. But you will have to share that part with us.

**Comment by EJShim** [comment]
@jourdain That did not work for me.. I solved it by
```

**polydata.getPoints().modified();**
const typedArray = polydata.getPoints().getData();
typedArray[0] = x0;
typedArray[1] = y0;
typedArray[2] = z0;
[...]
```
modified() 

Thank you for your answer
