### ISSUE TITLE
Is there a way I can apply transform to polyData?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1054]
I remember there was a polydata transform module function in C++ version of vtk.

is there a similar operation in vtk.js?

or do I have to manually apply transform for every points in polydata?

**Comment by jourdain** [comment]
You can create a filter an use the matrix builder for that. Like we do [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Sources/ConeSource/index.js#L64-L69)
