### ISSUE TITLE
Boundary extracting from DICOM slice

### ISSUE THREAD

**Issue by truongleit** [Kitware/vtk-js#1057]
Hi, my problem is I need to extract the boundary of each DICOM slice in a set of DICOM. Is there any function or example in VTK.js that can help me solve this issue? @jourdain @thewtex

**Comment by jourdain** [comment]
@thewtex @agirault

**Comment by agirault** [comment]
You can call [`vtkImageMapper.getBoundsForSlice`](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ImageMapper/index.js#L273) but it will only work if you are doing IJK slicing or if your dataset is axis-aligned with the world coordinates.
