### ISSUE TITLE
vtk.js distancewidget property

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1058]
Hello!

I applied the distancewidget to the vti viewer. 

However, there is no property for distancewidget in vtk.js. I want to use distancewidget more specifically. Can you tell me the properties for distancewidget?

The only property I know is the following:

`distanceWidget.setEnabled(1);`

**Comment by finetjul** [comment]
Have  you considered the [distance representation](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/DistanceRepresentation/index.js) properties ?

**Comment by rjsgml5698** [comment]
Thanks for the reply! I am not familiar with vtk.js yet.

Can you tell me the properties of the distance representation?
