### ISSUE TITLE
How to Identify the Brain Only (I implemented volume rendering)

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1062]
Hello. 

I implemented volume rendering as follows. 

But what I want is the brain. I'd like to see a specific brain. 

I work hard, but it is difficult to specify the brain. I am using the Gaussian filter now.

I'm a beginner who is not yet familiar with vtk. I would really appreciate it if you let me know.

![1](https://user-images.githubusercontent.com/40594949/56722822-c8930b00-6782-11e9-8272-46680f59bf1e.PNG)

Thank you!!

**Comment by thewtex** [comment]
@rjsgml5698 this requires "skull stripping", i.e. segmentation of the brain. We are considering the creation of an example that uses vtk.js with itk.js and tensorflow.js or similar. 

C: @martinken @aylward

**Comment by rjsgml5698** [comment]
Thanks for the answer. (+I am not good at English. I'll ask for your understanding in advance.)

I think it would be really helpful if you made that example. 

I have two questions :

1. Is "skull stripping" available in itk.js? Not in vtk.js? (Actually, I'm having trouble setting up the webpack for itk.js.)

2. I'm having trouble setting up the itk.js webpack with create-react-app. Do you have any information on this?
