### ISSUE TITLE
Help to use SynchronizableRenderWindow

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1063]
Hello I open this issue because I need help to use SynchronizableRenderWindow
The aim is to improve a previous work here https://github.com/pyviz/panel/pull/312 using this code https://github.com/Kitware/VTK/tree/db5b6e4d69292c0b7e9bbd4260b2e2f45a1d37d4/Web/Python/vtkmodules/web
I succeed to serialiaze python vtkRenderWindow but I'm stuck to reconstruct the render window on the javascript side.
This is the code I used to serialize on the python side
```python
import vtk

import panel.pane.vtk_render_serializer as rws

cone = vtk.vtkConeSource()

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)

ren.ResetCamera()
renWin.OffScreenRenderingOn()
renWin.Render()

rws.initializeSerializers()
context = rws.SynchronizationContext()

state = rws.serializeInstance(None, renWin, rws.getReferenceId(renWin), context, 0)
state['parent'] = None
state['mtime'] = 0
data = {sha : context.getCachedDataArray(sha, binary=False) for sha in context.dataArrayCache.keys()}
```
From the state and data variables I create json string and I made a small html file to reconstruct it on the webbrowser :
```html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
</head>

<body>

<script src='https://unpkg.com/vtk.js@8.4.5/dist/vtk.js'></script>

<script>
	var state = JSON.parse('{"parent": null, "id": "1570426183496", "type": "vtkWin32OpenGLRenderWindow", "properties": {"numberOfLayers": 1}, "dependencies": [{"parent": "1570426183496", "id": "1570426183400", "type": "vtkOpenGLRenderer", "properties": {"background": [0.0, 0.0, 0.0], "background2": [0.2, 0.2, 0.2], "viewport": [0.0, 0.0, 1.0, 1.0], "twoSidedLighting": 1, "lightFollowCamera": 1, "layer": 0, "preserveColorBuffer": 0, "preserveDepthBuffer": 0, "nearClippingPlaneTolerance": 0.001, "clippingRangeExpansion": 0.5, "useShadows": 0, "useDepthPeeling": 0, "occlusionRatio": 0.0, "maximumNumberOfPeels": 4}, "dependencies": [{"parent": "1570426183400", "id": "1570426286152", "type": "vtkOpenGLCamera", "properties": {"focalPoint": [0.0, 0.0, 0.0], "position": [0.0, 0.0, 3.2036135254332487], "viewUp": [0.0, 1.0, 0.0]}}, {"parent": "1570426183400", "id": "1570426183304", "type": "vtkOpenGLActor", "properties": {"visibility": 1, "pickable": 1, "dragable": 1, "useBounds": true, "origin": [0.0, 0.0, 0.0], "position": [0.0, 0.0, 0.0], "scale": [1.0, 1.0, 1.0], "forceOpaque": false, "forceTranslucent": false}, "calls": [["setMapper", ["instance:${1570426183208}"]], ["setProperty", ["instance:${1570426286728}"]]], "dependencies": [{"parent": "1570426183304", "id": "1570426183208", "type": "vtkOpenGLPolyDataMapper", "properties": {"scalarRange": [0.0, 1.0], "useLookupTableScalarRange": false, "scalarVisibility": 1, "colorByArrayName": -1, "colorMode": 0, "scalarMode": 0, "interpolateScalarsBeforeMapping": false}, "calls": [["setInputData", ["instance:${1570426183208-dataset}"]], ["setLookupTable", ["instance:${1570426286728}"]]], "dependencies": [{"parent": "1570426183208", "id": "1570426183208-dataset", "type": "vtkPolyData", "properties": {"points": {"hash": "iIko5uYglKcynRRhjzS3mg_21f", "vtkClass": "vtkPoints", "name": "Points", "dataType": "Float32Array", "numberOfComponents": 3, "size": 21, "ranges": [{"min": -0.5, "max": 0.5, "component": null}, {"min": -0.5, "max": 0.5, "component": null}, {"min": -0.4330126941204071, "max": 0.4330126941204071, "component": null}, {"min": 0.5, "max": 0.7071067811865476, "component": null}]}, "polys": {"hash": "0QwX+rYGGYv9l9M84N+Xaw_31L", "vtkClass": "vtkCellArray", "name": null, "dataType": "Uint32Array", "numberOfComponents": 1, "size": 31, "ranges": [{"min": 0.0, "max": 6.0, "component": null}]}, "fields": []}}, {"parent": "1570426183208", "id": "1570426286728", "type": "vtkLookupTable", "properties": {"numberOfColors": 256, "valueRange": [0.0, 1.0], "hueRange": [0.5, 0], "saturationRange": [1.0, 1.0], "nanColor": [0.5, 0.0, 0.0, 1.0], "belowRangeColor": [0.0, 0.0, 0.0, 1.0], "aboveRangeColor": [1.0, 1.0, 1.0, 1.0], "useAboveRangeColor": false, "useBelowRangeColor": false, "alpha": 1.0, "vectorSize": -1, "vectorComponent": 0, "vectorMode": 1, "indexedLookup": 0}}]}, {"parent": "1570426183304", "id": "1570426286728", "type": "vtkOpenGLProperty", "properties": {"representation": 2, "diffuseColor": [1.0, 1.0, 1.0], "color": [1.0, 1.0, 1.0], "ambientColor": [1.0, 1.0, 1.0], "specularColor": [1.0, 1.0, 1.0], "edgeColor": [0.0, 0.0, 0.0], "ambient": 0.0, "diffuse": 1.0, "specular": 0.0, "specularPower": 1.0, "opacity": 1.0, "interpolation": 1, "edgeVisibility": false, "backfaceCulling": false, "frontfaceCulling": false, "pointSize": 1.0, "lineWidth": 1.0, "lighting": true}}]}, {"parent": "1570426183400", "id": "1570426286344", "type": "vtkOpenGLLight", "properties": {"switch": 1, "intensity": 1.0, "color": [1.0, 1.0, 1.0], "position": [0.0, 0.0, 3.2036135254332487], "focalPoint": [0.0, 0.0, 0.0], "positional": 0, "exponent": 1.0, "coneAngle": 30.0, "attenuationValues": [1.0, 0.0, 0.0], "lightType": "HeadLight", "shadowAttenuation": 1.0}}], "calls": [["setActiveCamera", ["instance:${1570426286152}"]], ["addViewProp", ["instance:${1570426183304}"]], ["addLight", ["instance:${1570426286344}"]]]}], "calls": [["addRenderer", ["instance:${1570426183400}"]]], "mtime": 0}')
	var arrays = JSON.parse('{"iIko5uYglKcynRRhjzS3mg_21f": "AAAAPwAAAAAAAAAAAAAAvwAAAD8AAAAAAAAAvwAAgD7Xs90+AAAAvwAAgL7Xs90+AAAAvwAAAL8yMY0kAAAAvwAAgL7Xs92+AAAAvwAAgD7Xs92+", "0QwX+rYGGYv9l9M84N+Xaw_31L": "BgAAAAYAAAAFAAAABAAAAAMAAAACAAAAAQAAAAMAAAAAAAAAAQAAAAIAAAADAAAAAAAAAAIAAAADAAAAAwAAAAAAAAADAAAABAAAAAMAAAAAAAAABAAAAAUAAAADAAAAAAAAAAUAAAAGAAAAAwAAAAAAAAAGAAAAAQAAAA=="}')
	

	var model = {}
	model.rootContainer = document.querySelector('body')
	model.container = document.createElement('div')
	model.rootContainer.appendChild(model.container)

    model.synchCtx = vtk.Rendering.Misc.vtkSynchronizableRenderWindow.getSynchronizerContext()
    model.synchCtx.setFetchArrayFunction((sha) => Promise.resolve(arrays[sha]))
    
    //  // VTK renderWindow
    const initialValues = {
      viewId: "1",
    }
    model.renderWindow = vtk.Rendering.Misc.vtkSynchronizableRenderWindow.newInstance(initialValues)

    // OpenGlRenderWindow
    model.openGLRenderWindow = vtk.Rendering.OpenGL.vtkRenderWindow.newInstance()
    model.openGLRenderWindow.setContainer(model.container)
    model.renderWindow.addView(model.openGLRenderWindow)

    // Interactor
    model.interactor = vtk.Rendering.Core.vtkRenderWindowInteractor.newInstance()
    model.interactor.setInteractorStyle(
      vtk.Interaction.Style.vtkInteractorStyleTrackballCamera.newInstance()
    )
    model.interactor.setView(model.openGLRenderWindow)
    model.interactor.initialize()
    model.renderWindow.synchronize(state)
    model.renderWindow.render()
</script>
</body>
</html>
```

However I get this error: `No builder for vtkOpenGLPolyDataMapper`
So I looked at https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/SynchronizableRenderWindow/vtkObjectManager.js#L384-L433 and I replaced vtkOpenGLPolyDataMapper by vtkCompositePolyDataMapper2 but now I get several warnings and an error
![image](https://user-images.githubusercontent.com/18531147/56752309-3b52b500-6788-11e9-94df-d639c019a60e.png)

I don't know if I'm totally wrong on the serialisation or on the use of the SynchronizableRenderWindow but I'm stuck

**Comment by jourdain** [comment]
I'm pretty busy but I want to help. So if you don't hear back from me in the coming days. Feel free to ping me again on that issue so it does not fall off my radar. Thx!

**Comment by scottwittenburg** [comment]
For one thing, I think you should duplicate the entry for `vtkOpenGLPolyDataMapper`, and giving the key 'vtkCompositePolyDataMapper2', instead of replacing it, because the subsequent error you saw was about that builder missing.  Maybe you can report back here when you get the results of that?

**Comment by scottwittenburg** [comment]
Or looking back, maybe I misunderstood your description of what you did.  If you replaced one of those entries in the `DEFAULT_MAPPING`, you probably want to duplicate the one you replaced instead.  That could be done via the `setTypeMapping` method as well, so you don't need to change the `vtk.js` source code, but achieve a similar result from your application.

**Comment by xavArtley** [comment]
I just use the cdn of vtk.js and setTypeMapping of vtkObjectManager is not exposed

**Comment by scottwittenburg** [comment]
It looks like it is exposed, [here](https://github.com/Kitware/vtk-js/blob/c2b2d3e3405adb586a8b7e5e15a1534c8af6518c/Sources/Rendering/Misc/SynchronizableRenderWindow/vtkObjectManager.js#L459), were you not able to call that method?

But any rate, it sounds like you did change the `vtk.js` source code, so you could still try my previous suggestion as a starting point.

**Comment by xavArtley** [comment]
I have not change the code of vtk.js. I use the cdn from https://unpkg.com/vtk.js@8.4.5/dist/vtk.js
And it's vtkObjectManager that is not exposed.
But my concern is not really about the fist issue but rather about the second one and the fact that paraviewweb works. 
So I suppose there is something wrong with my code.

**Comment by scottwittenburg** [comment]
Oh, it looks like you changed the json representation of the exported render window.  Sorry I didn't get what you were doing at first, but I think I do now.  So I notice we don't support for that particular type yet, and I also noticed your JSON file has a `vtkWin32OpenGLRenderWindow` which we don't have in the object manager yet either.  

I *think* we can add those easily enough by doing what I said earlier, and since you've got the cdn version you're right that you can't just test it out for me.  Before I can submit a patch though, I'll just want to test that your JSON works with my changes, so I'll have to make a little example, which I'll get to as soon as I can.

**Comment by xavArtley** [comment]
Oh I didn't thought I changed that much the json.
I just merged 
https://github.com/Kitware/VTK/blob/master/Web/Python/vtkmodules/web/__init__.py
https://github.com/Kitware/VTK/blob/master/Web/Python/vtkmodules/web/render_window_serializer.py

and change the function:
```
def getReferenceId(ref):
  return vtkWebApplication.GetObjectId(ref)
```
by 
```
def getReferenceId(ref):
  return str(id(ref))
```
as I have not access to `from vtk.vtkWebCore import vtkWebApplication`

Then I inspired my example code from 
https://github.com/Kitware/VTK/blob/master/Web/Python/Testing/Python/TestSerializeRenderWindow.py
