### ISSUE TITLE
Setting {binary} option for stl reader automatically?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1064]
Hello

I would like to import stl files. some of them are encoded binary, and some are not.

in case of none-binary stl file, I need to add {binary:false} option to the stlLoader.

Is there a way this option can be outomatically set before load STL file?

**Comment by jourdain** [comment]
If you call `parse` and the arg is a string, it will naturally call `parseAsText` and `parseAsArrayBuffer`.
Otherwise if you provide a URL, you need to know if you should fetch and parse it as a binary or text.

I'm not sure I understand your question.

**Comment by EJShim** [comment]
Sorry for my poor English and thank you for your kind answer. 

I am trying to load stl files providing URLs using

`stlReader.setURL({URL}, {binary:true})` operation.

You mean in this case, do I have to know if the stl file I am trying to load is binary or text?


I tried to resolve it using Promise.catch(error) option as below:

`new Promise((resolve, reject)=>{            
            stlReader.setUrl(`${serverAddress}/api/meshFile/${meshId}`)
            .then(data=>{
                
                resolve(data);
                
            }).catch(error=>{            
                stlReader.setUrl(`${serverAddress}/api/meshFile/${meshId}`, {binary:false})
                .then(data=>{
                    resolve(data)
                })
            });
        }); `

I thought this code will catch error when I try to load non-binary (text) STL file, and  load the file with 

{binary : false} option.

But instead of ` .catch(error)` calling, it just goes to `.then(data)` and occurs error.

Do you have any solution for my problem?

Thank you.
