### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'getRange' of null

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1066]
hello.

I extracted the vti from the dicom file series using the following Python code:
````
def vtkImageToNumPy(image, pixelDims):
    imageData = reader.GetOutput()
    pointData = image.GetPointData()
    arrayData = pointData.GetArray(0)
    ArrayDicom = numpy_support.vtk_to_numpy(arrayData)
    ArrayDicom = ArrayDicom.reshape(pixelDims, order='F')

    return ArrayDicom

dicomFolder = "./lung_imgs"
reader = vtk.vtkDICOMImageReader()
reader.SetDirectoryName(dicomFolder)
reader.Update()

# Load dimensions using `GetDataExtent`
my_extent = reader.GetDataExtent()
ConstPixelDims = [my_extent[1]-my_extent[0]+1, my_extent[3]-my_extent[2]+1, my_extent[5]-my_extent[4]+1]

# Load spacing values
ConstPixelSpacing = reader.GetPixelSpacing()

dicom_array = vtkImageToNumPy(reader.GetOutput(), ConstPixelDims)

from pyevtk.hl import imageToVTK

imageToVTK("./lungResult",cellData={"ArrayDicom" : dicom_array})
````

So I tried to implement volume rendering. However, the following error occurred:

![image](https://user-images.githubusercontent.com/40594949/56888936-32c3ec80-6ab0-11e9-85e8-63e2c075e3cd.png)

So I tried to compare the implemented vti file with the unimplemented vti file through the para view. There were the following differences:

> [unimplemented]

![image](https://user-images.githubusercontent.com/40594949/56889254-d7dec500-6ab0-11e9-9141-377bd88299f9.png)

> [implemented]

![image](https://user-images.githubusercontent.com/40594949/56889281-eb8a2b80-6ab0-11e9-838b-230529773f65.png)

I want to find the difference and solution between the above pictures. I would like to implement volume rendering using ArrayDicom.

I would really appreciate your reply.

**Comment by jourdain** [comment]
Replace `imageToVTK("./lungResult",cellData={"ArrayDicom" : dicom_array})` by `imageToVTK("./lungResult",pointData={"ArrayDicom" : dicom_array})`

**Comment by rjsgml5698** [comment]
I have received great support for your answer.

I changed it to pointData according to your answer and it comes out as arraydicom.

I used the following reader:

> vtkHttpDataSetReader
![image](https://user-images.githubusercontent.com/40594949/56935674-8fb1b800-6b2d-11e9-81ef-252d250f7736.png)

> vtkXMLImageDataReader
![image](https://user-images.githubusercontent.com/40594949/56935635-55e0b180-6b2d-11e9-8ada-5ba62c5f2cbf.png)

Both had problems rendering.

Do you know what is the correct reader in vtk.js for the dicom array?

Thank you again for your kind answers despite my lack of knowledge.

**Comment by jourdain** [comment]
Did you managed to write a vti file? That you can load in ParaView?
If yes, then the `vtkXMLImageDataReader` is the reader to use. The `vtkHttpDataSetReader` is for something different.

**Comment by rjsgml5698** [comment]
Thank you for your quick reply.

I used vtk.js. And I have experienced volume rendering using vti files.

I originally uploaded the dicom series to the paraview and extracted the vti file. However, I want to automate by creating dicom2vti using Python.

The result of directing the dicom series to paraview is as follows:

> Volume rendering succeed
![image](https://user-images.githubusercontent.com/40594949/56936889-db1b9480-6b34-11e9-8ab1-33c4f8f8d5b6.png)

> Volume rendering failed
![image](https://user-images.githubusercontent.com/40594949/56936921-fededa80-6b34-11e9-81a5-55d4c86c3491.png)

I used `vtkXMLImageDataReader`. However, when I applied a dicom array, an error occurred.

This code is part of the code to implement volume rendering. This is similar to the example in vtk.js. Instead, it was developed as react.

```
import VTKViewport from 'react-vtkjs-viewport';
import vtkHttpDataSetReader from 'vtk.js/Sources/IO/Core/HttpDataSetReader';
import vtkXMLImageDataReader from 'vtk.js/Sources/IO/XML/XMLImageDataReader';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkVolume from 'vtk.js/Sources/Rendering/Core/Volume';
import vtkVolumeMapper from 'vtk.js/Sources/Rendering/Core/VolumeMapper';
import vtkDistanceWidget from 'vtk.js/Sources/Interaction/Widgets/DistanceWidget';
import vtkColorMaps from 'vtk.js/Sources/Rendering/Core/ColorTransferFunction/ColorMaps';
import vtkPiecewiseGaussianWidget from 'vtk.js/Sources/Interaction/Widgets/PiecewiseGaussianWidget';
import vtkColorTransferFunction from 'vtk.js/Sources/Rendering/Core/ColorTransferFunction';
import vtkPiecewiseFunction from 'vtk.js/Sources/Common/DataModel/PiecewiseFunction';
```

```
const importLoad = 'lungResult(dicomarray).vti';

    const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({
      background: [0, 0, 0],
      gaussianContainer : this.gaussianContainer,
      containerStyle : []
    });
    const defaultRenderer = fullScreenRenderer.getRenderer();
    const renderer = fullScreenRenderer.getRenderer();
    const renderWindow = fullScreenRenderer.getRenderWindow();

    renderWindow.getInteractor().setDesiredUpdateRate(15.0);
```

```
const vtiReader  = vtkXMLImageDataReader.newInstance({fetchGzip: true});

vtiReader.setUrl(importLoad).then(() => {
      vtiReader.loadData().then(() => {

        const imageData = vtiReader1.getOutputData();
        const dataArray = imageData.getPointData().getScalars();
        const dataRange = dataArray.getRange(); <= error occured
        globalDataRange[0] = dataRange[0];
        globalDataRange[1] = dataRange[1];

        // Update Lookup table
        changePreset();

        // Automatic switch to next preset every 5s
        // if (!this.gaussianContainer) {
        //   intervalID = setInterval(changePreset, 10000);
        // }

        this.gaussianWidget.setDataArray(dataArray.getData());
        this.gaussianWidget.applyOpacity(piecewiseFunction);
        this.gaussianWidget.setColorTransferFunction(lookupTable);

        lookupTable.onModified(() => {
          this.gaussianWidget.render();
          renderWindow.render();
        });

        renderer.addVolume(volumeActor);
        renderer.resetCamera();
        renderer.getActiveCamera().elevation(70);
        renderWindow.render();

        this.setState({
          renderWindow
        });
      });
    })
```

**Is there a way to fix the 'getRange' problem in the above code?**

Thank you!

**Comment by jourdain** [comment]
Probably because you don't have Scalars (active array).
You can try `imageData.getPointData().getArray(0)` instead of `getScalars()`.

**Comment by rjsgml5698** [comment]
Thank you for your reply. Thanks a little bit I'm moving forward.

Can I ask you one last question?

I entered getArray (0) instead of getscalars (). However, the following error occurred.

![image](https://user-images.githubusercontent.com/40594949/57050339-10e88680-6cb7-11e9-8167-49d3c23e1662.png)


**Can I get a solution for this?**

**Comment by jourdain** [comment]
What do you get as typed array?
```
console.log(imageData.getPointData().getArray(0).getData())
```

**Comment by rjsgml5698** [comment]
Thanks for the quick answer.

The result of the console is as follows :

![image](https://user-images.githubusercontent.com/40594949/57050877-a4bb5200-6cb9-11e9-9947-dd1af36f52c2.png)

Thank you!

**Comment by jourdain** [comment]
I thing VolumeRendering expect Scalars unless you specify which array you want to look at.

Anyway a way to fix that is to locally set that array as scalars

```
const pd = imageData.getPointData();
pd.setScalars(pd.getArray(0));
```

**Comment by rjsgml5698** [comment]
Thanks to your help, I solved the problem.

I was never able to solve it by myself.

Thank you so much!

**Comment by jourdain** [comment]
So the all problem is related to the way you generate your vtkImageData before you write it as vti file. If the data array was set as scalars, everything would have worked out of the box.

**Comment by rjsgml5698** [comment]
I understood your words. If it is set to scalars in volume rendering, it will be implemented without problems. 

Thank you again for your teaching. I can move on to the next step.

And I am looking for a way to apply the skull stripping algorithm.

Thanks!
