### ISSUE TITLE
vtkPolyData with custom storage

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1069]
I am very interested about the PolyData and its mapper. However, I am wondering if there is a way to customize its storage, without loosing all the work you already done. In the VTK C++, there is a class (vtkMappedUnstructuredGrid) which allow this customization.

Do you think it is possible to benefit from your work and having a custom storage? Or a least a way to override the PolyData API to go look into another storage.

Thanks!

**Comment by jourdain** [comment]
We don't have a mapping class per-say like in c++ but as long as you have TypedArray for the fields/points/cells... You can easily create your own source that will link them together inside a vtkPolyData without memory duplication.

**Comment by BotellaA** [comment]
I am not sure to see how it can be done. For example, if I have an Array of Objects reprensenting the points. How can the remaining vtk.js code can work ?

**Comment by jourdain** [comment]
Array of Objects are not TypedArray which means you will need to convert them. But in general what I said remain true, meaning that you could have a source/filter that will take your data structure as input and output a polydata.

**Comment by BotellaA** [comment]
Ok but I was looking at a way to avoid memory duplication. The output of a source will be a new polydata. At least that is what I understood (because of the data conversion).

**Comment by jourdain** [comment]
I mean if your data is far off like an "array of object" vs "typed array", there is nothing we can do. The GPU is expecting buffer of data so conversion needs to happen no matter what.

The overhead of a polydata when you already have all those memory buffer is nothing.
