### ISSUE TITLE
Problem adding colors to LookupTable

### ISSUE THREAD

**Issue by vicriv** [Kitware/vtk-js#1070]
Hello,
I am working in a vtk.js project that have a PolydataReader which read a .vtp file with scalars. These scalars can be 0, 1 or 2, only. So, I am trying to create a LookupTable with three colors only (white, green and red), but I do not get a representation.
I have a c++ code with vtk, which is similar and runs perfectly. Is possible that the commands that I am using are not included in vtk.js yet? I attach my code:

Thanks in advance.

import 'vtk.js/Sources/favicon';

import vtkActor from 'vtk.js/Sources/Rendering/Core/Actor';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkMapper from 'vtk.js/Sources/Rendering/Core/Mapper';

import vtkXMLPolyDataReader from 'vtk.js/Sources/IO/XML/XMLPolyDataReader';

import vtkLookupTable from 'vtk.js/Sources/Common/Core/LookupTable';

const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({background: [1, 1, 1],});
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();
const resetCamera = renderer.resetCamera;
const render = renderWindow.render;

const reader = vtkXMLPolyDataReader.newInstance();

const mapper = vtkMapper.newInstance({ interpolateScalarsBeforeMapping: true, scalarVisibility: true, scalarRange: [0, 2], }); 
const actor = vtkActor.newInstance();

reader.setUrl(`mesh.vtp`).then(() => {

    mapper.setInputConnection(reader.getOutputPort()); 

    const lut = vtkLookupTable.newInstance();
    lut.setNumberOfTableValues(3);
    lut.setTableValue(0, 1.0, 0.0, 0.0, 1.0); //red
    lut.setTableValue(1, 1.0, 1.0, 1.0, 1.0); //white
    lut.setTableValue(2, 0.0, 1.0, 0.0, 1.0); //green
    lut.build();
    mapper.setLookupTable(lut);
    mapper.setColorModeToMapScalars(); 
    mapper.setScalarModeToUsePointData();

    actor.setMapper(mapper);
    renderer.addActor(actor);
    resetCamera();
    render();
});

global.reader = reader;
global.polydata = polydata;
global.fullScreenRenderer = fullScreenRenderer;
global.lut = lut;
global.mapper = mapper;
global.actor = actor;
global.renderer = renderer;
global.renderWindow = renderWindow;

**Comment by jourdain** [comment]
Try using that [LookupTable](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/index.js) instead using the `addRGBPoint(x, r, g, b)` method.

It is possible that the current LookupTable implementation is not complete or slightly different than the C++ version.

**Comment by vicriv** [comment]
Thanks @jourdain for your answer. 
I tried your method, but I get the same result, i.e, I do not get to visualize the representation. I saw that the ColorTransferFunction looks like LookupTable in some examples so I wrote the code in a similar way. Maybe, am I writting anything wrong? Is possible that I need anything else?
I attach my code with the change below again:

import 'vtk.js/Sources/favicon';

import vtkActor from 'vtk.js/Sources/Rendering/Core/Actor';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkMapper from 'vtk.js/Sources/Rendering/Core/Mapper';
import vtkXMLPolyDataReader from 'vtk.js/Sources/IO/XML/XMLPolyDataReader';
import vtkColorTransferFunction from 'vtk.js/Sources/Rendering/Core/ColorTransferFunction';

const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({background: [1, 1, 1],});
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();
const resetCamera = renderer.resetCamera;
const render = renderWindow.render;
const reader = vtkXMLPolyDataReader.newInstance();
const mapper = vtkMapper.newInstance({ interpolateScalarsBeforeMapping: true, scalarVisibility: true, scalarRange: [0, 2], });
const actor = vtkActor.newInstance();

reader.setUrl(mesh.vtp).then(() => {
mapper.setInputConnection(reader.getOutputPort()); 

const ctfun = vtkColorTransferFunction.newInstance();
ctfun.addRGBPoint(0, 1.0, 0.0, 0.0);  //red
ctfun.addRGBPoint(1, 1.0, 1.0, 1.0); //white
ctfun.addRGBPoint(2, 0.0, 1.0, 0.0); //green
ctfun.build();

mapper.setColorTransferFunction(ctfun);

mapper.setColorModeToMapScalars(); 
mapper.setScalarModeToUsePointData();

actor.setMapper(mapper);
renderer.addActor(actor);
resetCamera();
render();
});

global.reader = reader;
global.polydata = polydata;
global.fullScreenRenderer = fullScreenRenderer;
global.ctfun = ctfun;
global.mapper = mapper;
global.actor = actor;
global.renderer = renderer;
global.renderWindow = renderWindow;

**Comment by jourdain** [comment]
I don't seems to find where you choose which [array you want to color by](https://github.com/Kitware/vtk-js/blob/master/Examples/Applications/GeometryViewer/index.js#L324).

**Comment by vicriv** [comment]
I think that I have solve the problem using:
mapper.setLookupTable(ctfun);   instead of   mapper.setColorTransferFunction(ctfun); 
With this command the program seems to work perfectly. It reads the scalars and paints these with the correct color. Is possible that the command setColorTransferFunction() does not exist?

**Comment by jourdain** [comment]
I don't think `setColorTransferFunction` exist.

**Comment by vicriv** [comment]
What could be the reason then? Maybe it takes ColorTransferFunction as a LookupTable or something like that?

**Comment by jourdain** [comment]
Both vtkLookupTable and vtkColorTransferFunction are vtkScalarsToColors. The mapper just needs a vtkScalarsToColors using the setLookupTable() API.

**Comment by aylward** [comment]
More information is needed to resolve.   Will close this issue.   Please re-open if the problem/question persists.
