### ISSUE TITLE
How to preserve lungs and eliminate the rest

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1072]
I am looking for a way to preserve the lungs and remove the rest for the pictures below. I can use a guassian filter to make it look like the picture below. I do not know how to look at lungs alone.

I know I can control the guassian filte using PiecewiseFunction and ColorTransferFunction.

Can you help me with this?

![image](https://user-images.githubusercontent.com/40594949/57274438-3b32ad80-70d6-11e9-875e-a826e306a1e1.png)

**Comment by llangholz89** [comment]
A quick and dirty way, without doing any sort of segmentation, would be to try running your dataset through an image crop filter ([example shown here](https://kitware.github.io/vtk-js/examples/ImageCropFilter.html)).  That may or may not get rid of everything you don't want though, but it should be an easy start

**Comment by rjsgml5698** [comment]
@llangholz89 

Thanks for the answer. I got a good idea. 

**Can I give transparency to only one part of the yellow mark (I want to make the lung more visible)**

There is a way I already know.

1. I make a dicom image as a binary file that consists of 1 (desired part) and 0 (not necessary part).

2. Give transparency and color value using piecewise function and colortransferfunction.

Is this the only way?

Thank you!!

![image](https://user-images.githubusercontent.com/40594949/57341389-37099d00-7175-11e9-9b89-f05954fb2c47.png)
