### ISSUE TITLE
Load /GeometryViewer/index.js in HTML file

### ISSUE THREAD

**Issue by simwes** [Kitware/vtk-js#1080]
Hello Everyone!

I am sorry if the question is a bit silly, but I am new to this kind of scripting.
I am trying to develop and run  a HTML script for a VTK viewer including this file Examples/Applications/GeometryViewer/index.js. However, I am having problem to load the file correctly. I am trying to load the /GeometryViewer/index.js file in my html with the following

`<script src="https://raw.githubusercontent.com/Kitware/vtk-js/master/Examples/Applications/GeometryViewer/index.js">
`
However, I get the error message from my browser:

`The resource from “https://raw.githubusercontent.com/Kitware/vtk-js/master/Examples/Applications/GeometryViewer/index.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).[Learn More]`

Perhaps, do you have a working example of HTML file I can run on my computer including the GeometryViewer javascript  file (index.js)?

Thank you very much!

**Comment by jourdain** [comment]
That file needs to be transpiled. An HTML file bundle can be found here:
https://kitware.github.io/vtk-js/examples/GeometryViewer/GeometryViewer.html

Which was taken from the live example here: https://kitware.github.io/vtk-js/examples/GeometryViewer.html

To learn how to create a project from an example, you can follow that [guide](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html)

**Comment by simwes** [comment]
Sebastien,

Thank you very much for your help. I will follow the instructions carefully.
Regards

Simone
