### ISSUE TITLE
Object.assign({}, actor, {userData: (...somedata) })  results disableing actor remove from renderer

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1082]
Hello, I added some custom user property to vtkActor  by using
```
let actor = vtkActor.newInstance();
let userData = {
   ...some data
}

actor = Object.assign({}, actor, {userData:userData});

renderer.addActor(actor); //it works

renderer.removeActor(actor); //not working
```

This actor works fine as ordinary vtkActor s. but problem occurs when I try to remove actor from renderer. It is not removed from the renderer.

Do you have any idea that causes this bug? 

If the way I tried to add custom property to the vtkActor is the problem, is there any recommended way to to do so?

**Comment by jourdain** [comment]
You can extend the actor class by following that [guide](https://kitware.github.io/vtk-js/docs/develop_class.html).

**Comment by EJShim** [comment]
@jourdain  Thanks, but is this class extends only available under vtk.js/ directory in node_modules/ ?

**Comment by jourdain** [comment]
No, you can create your own class inside your project.
