### ISSUE TITLE
When ImageReslice can support InterpolationMode.CUBIC ?

### ISSUE THREAD

**Issue by tanxu1120** [Kitware/vtk-js#1083]
InterpolationMode.NEAREST shows that the result is too bad.

![15584071518763](https://user-images.githubusercontent.com/37609756/58065017-d9367580-7bb6-11e9-9347-48f5cc325d10.jpg)

**Comment by finetjul** [comment]
@tanxu1120, if by ImageReslice you mean Imaging/Core/ImageReslice, I have currently no plan on adding cubic interpolation. You are always welcomed to contribute. It should be fairly easy because you can take example on the corresponding vtkImageReslice.cxx in VTK C++
I am happy to help if needed.
