### ISSUE TITLE
Integrate VTK in Django frame work

### ISSUE THREAD

**Issue by simwes** [Kitware/vtk-js#1086]
Hello,

I am trying to integrate VTK app into Django so in my html template I have the following:
` <script src="{% static 'js/MyWebApp.js' %}" type="text/javascript"></script>` 

However, I get the following error messages:
`The script from “http://127.0.0.1:8000/static/js/MyWebApp.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`
`Loading failed for the <script> with source “http://127.0.0.1:8000/static/js/MyWebApp.js`
And nothing appears on my browser. Do you have any suggestion ?
Thank you very much !

**Comment by jourdain** [comment]
Django is serving the js file as `text/html` instead of `text/javascript` ?

**Comment by simwes** [comment]
I have replaced `text/javascript` with `text/html`, the error messages disappear but the browser is still empty.  Also from the back end there is not error message !

**Comment by jourdain** [comment]
That's not what I said. `text/javascript` is required. Any console error or debug info.
Is your application working by itself? What does it do?

**Comment by simwes** [comment]
Sorry for the misunderstanding. Apart from  the above-mentioned errors  from the back-end I also received the following: `GET /static/js/MyWebApp.js HTTP/1.1" 404 1666`
This Django app is simply trying to load the test case from VTK [example](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) into html front-end script.

**Comment by jourdain** [comment]
I can't really help you as it is a pure Django and file serving issue.

**Comment by cemlyn007** [comment]
Sorry to be a pain but @simwes did you figure out the solution? I believe I'm in the same position as you. I can locally (& without Django) can view OBJ examples from a data folder. But if I integrate this into my Django framework, & place the data folder in my static folder, I get the same 404 error when the MyWebApp.js tries to locate them. 

I hope you get my message! Best wishes dudes

**Comment by jourdain** [comment]
404 means not found == url given is not valid to get to the file

**Comment by floryst** [comment]
If this is still an issue, please re-open.
