### ISSUE TITLE
Input format for vtkImageMarchingCubes

### ISSUE THREAD

**Issue by arshamg** [Kitware/vtk-js#1091]
I am stuck trying to understand the input data format for vtkImageMarchingCubes.

Currently we create `scalars` from a 1D array:

```
            var scalars = vtkDataArray.newInstance({
                values: arr, // 1D array data
                numberOfComponents: 1, // number of channels (grayscale)
                dataType: vtkDataArray.VtkDataTypes.INT8, // values encoding
                name: 'scalars'
            });
```
Then we create `imageData` setting the extent etc.
```
            var imageData = vtkImageData.newInstance();

            imageData.setOrigin(0, 0, 0);
            imageData.setSpacing(x_spacing, y_spacing, z_spacing);
            imageData.setExtent(0, x_extent, 0, y_extent, 0, z_extent);
            imageData.getPointData().setScalars(scalars);
```
Finally we pass this to vtkImageMarchingCubes and render.

```
        const mCubes = vtkImageMarchingCubes.newInstance({
            contourValue: 0.5,
            computeNormals: true,
            mergePoints: true,
        });

            mCubes.setInputData(imageData);
            mapper.setInputConnection(mCubes.getOutputPort());
// ... more code not shown
```
I don't receive any errors however nothing renders. Am I passing the correct data format to vtkImageMarchingCubes? Any help would be greatly appreciated.

**Comment by jourdain** [comment]
Everything seems right. 

In the first section you don't need to provide `dataType` as it will be deduced from `arr` that should be a `Uint8Array` or `Int8Array` depending on what your data really needs. 

I'm assuming the `arr.lenght == (x_extent  + 1) * (y_extent  + 1) * (z_extent  + 1)`.

**Comment by arshamg** [comment]
Thanks for the quick reply, I did not know the dataType is not required. I have found the issue with the code (unrelated to what was posted here) so will close the issue 👌

**Comment by jourdain** [comment]
Also `numberOfComponents` default to 1 when not provided. `name` and `values` are the 2 mandatory attributes. Although `values` can be skipped if your provide `empty: true`.

Then later on you can call `scalars.setData(arr, 1)`. The second arg is optional and represent the numberOfComponents.
