### ISSUE TITLE
iso-surface smoothing filters

### ISSUE THREAD

**Issue by kabhari** [Kitware/vtk-js#1094]
Do we have a JS implementation of `vtkSmoothPolyDataFilter` or `vtkWindowedSincPolyDataFilter` by any chance? There is no reference to these filters in the [API docs](https://kitware.github.io/vtk-js/api/).

Thanks guys!

**Comment by jourdain** [comment]
No we don't but if you feel like it you might be able to contribute them by looking at the C++ implementation.

**Comment by finetjul** [comment]
Hi, there is some WIP here https://github.com/Kitware/vtk-js/pull/1031
