### ISSUE TITLE
Is it possible to render pvti files in vtk.js in parallel?

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1097]
Hello.

I have a question.

Is it possible to render pvti files in vtk.js in parallel?

Thank you!

**Comment by jourdain** [comment]
What do you mean by "in parallel"? Are you envisioning browser with MPI? Or just multi-volume rendering. If it is the later, it will be available soonish.

**Comment by rjsgml5698** [comment]
Thanks for the quick reply! 

I don’t know if I understand your answer correctly. Already I implemented volume rendering by overlaying two of them at the same time. However, the two are overlapping at the same time, slower than one volume rendering. I want to improve this problem. 

So I think that if I use the pvti file format, it will get faster with the help of the GPU. I wonder if it can be implemented in vtk.js. 

Thank you!!

**Comment by jourdain** [comment]
The multi-volume rendering is to have proper blending of the volume.
The speed will happen at the GPU level or by down-sampling when interacting not by parallelizing like you are thinking.

**Comment by rjsgml5698** [comment]
Thank you very much!
