### ISSUE TITLE
Problems that are not clear: depth?

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1098]
Hi

I think this is due to depth. Is there a way to solve this?

The same problem occurs when I enter the renderwindow module and change the depth setting from true to false.

![image](https://user-images.githubusercontent.com/40594949/58931350-61617100-879a-11e9-8d1d-0ebff613fb5a.png)

Thank you!

**Comment by jourdain** [comment]
Are we looking at volume rendering or a contour with transparency?

**Comment by jourdain** [comment]
Ant idea @martinken ?

**Comment by martinken** [comment]
Guessing it is a transparent surface and would require depth peeling which we do not support yet

**Comment by rjsgml5698** [comment]
Thank you for your reply. 

It represents the result of rendering the vtp file, not volume rendering. I use setOpacity () to give a little bit of transparency. Is that a problem that can not be solved yet?

**Comment by martinken** [comment]
Transparent surfaces can have rendering artifacts.  See http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/ for some background. There are solutions but they are not in vtk.js yet.

**Comment by rjsgml5698** [comment]
Thank you!!
