### ISSUE TITLE
ViewProxy: extensible orientation axis

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1101]
Could it be possible to add a custom orientation axis actor in the ViewProxy? https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/ViewProxy/index.js#L113

It seems to be impossible at the moment but would be a simple nice feature.

**Comment by jourdain** [comment]
Feel free to submit a PR with the following set of methods to allow a dynamic list of orientation axis:

```
registerOrientationAxis(name, actor)
unregisterOrientationAxis(name)
listOrientationAxis()
```

thx
