### ISSUE TITLE
Texture upload performances

### ISSUE THREAD

**Issue by mcmigliore** [Kitware/vtk-js#1104]
There is currently a workaround in `vtkOpenGLTexture` for a Chrome 69 bug.  
Is this still needed? It slows down the function.

@manthey @laurennlam 

https://github.com/Kitware/vtk-js/blob/08091fbf41d939023f8d9d31cda82730c1b44c16/Sources/Rendering/OpenGL/Texture/index.js#L913

**Comment by manthey** [comment]
This appears to only have been a problem with Chrome 69.  Assuming we don't care about Chrome 69, it can be removed.

**Comment by mcmigliore** [comment]
I'll remove it, thanks!
