### ISSUE TITLE
error in documentation for AppendPolyData ?

### ISSUE THREAD

**Issue by PBrockmann** [Kitware/vtk-js#1111]
At https://kitware.github.io/vtk-js/api/Filters_General_AppendPolyData.html

I read:
![image](https://user-images.githubusercontent.com/5402758/59521762-5c549e00-8ecd-11e9-850b-ff353dca57ca.png)

I think vtkAppendFilter should be replaced by vtkAppendPolyData as:

```
const appendPolyData = vtkAppendPolyData.newInstance();
appendPolyData.setInputConnection(cone.getOutputPort());
appendPolyData.addInputConnection(cylinder.getOutputPort());

const appendedPolyData= appendPolyData.getOutputData();
```

**Comment by jourdain** [comment]
Yes you are correct.
