### ISSUE TITLE
Centering camera on a given point

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1114]
I would like to center the camera on a given point. I see the ViewProxy.resetCamera computes a new center from the bounds. 

Could it be possible to change this center without modifying the bounds? Are you interested by such feature?

**Comment by jourdain** [comment]
You can do what you are looking for without changing the API.
You just need to call:

```
view.getInteractorStyle3D().setCenterOfRotation(x, y, z);
```

**Comment by BotellaA** [comment]
Yes, that is what I did. I also used `camera.setFocalPoint(x, y, z);`. I was wondering if `camera.setPhysicalTranslation(-x, -y, -z);` was needed?

**Comment by jourdain** [comment]
The `PhysicalXXX` stuff are used for VR only.

BTW, feel free to submit a PR if you want to add new useful methods.

**Comment by BotellaA** [comment]
Thanks for your answer.
I will submit PR if that is really usefull for everyboby. Not sure in this case.

**Comment by jourdain** [comment]
Up to you but because we use closure in our function definition, your method could be written like that:

```
focusTo = macro.chain(camera.setFocalPoint, view.getInteractorStyle3D().setCenterOfRotation);
```

Maybe not worth a PR.
