### ISSUE TITLE
vtk.js marching cube with GUP

### ISSUE THREAD

**Issue by qqsea** [Kitware/vtk-js#1115]
Hi, i am trying to visualize a set of 2D dicom file into 3D model by using vtkImageMarchingCubes, follow the example https://kitware.github.io/vtk-js/examples/VolumeContour.html, we can render the whole 3D model by using our own data set(512x512x219). But there is a problem, when we change the iso value, it will take a long time to get the new 3D model showed in the browser.  
Whether of not when changing the iso value, and the calculation of iso surface can be put into GPU? Or any other way that can help to improve the efficiency of calculation?

Another one is except the vtkImageMarchingCubes, when use vtk.js, how to enable GPU for huge calculation?

Thanks

**Comment by jourdain** [comment]
If you do volume rendering you can achieve what you want by adjusting the transfer function.

**Comment by qqsea** [comment]
Thanks, I have already tried the volume rendering algorithm, the performance is good even by using CPU. 
I want to know the common procedure for using vtk.js with GPU, could you give some suggestions?

If GPU is not ready for all the vtk.js algorithm, the only way I can try is back to use webGL for re-implementation some algorithm within vtk.js

**Comment by jourdain** [comment]
I have a hard time understanding what you are talking about as vtk.js is using WebGL and therefore the GPU for its rendering.

**Comment by qqsea** [comment]
Yes, you are right that the VTK.js is based on webgl, but it does not mean that all the calculations of VTK.js are made within GPU, such as the code within marching cube algorithm is executed within CPU, and then the result will be sent to GPU for render.
As we have some experience on calculation of marching cube within GPU by using openGL, the code calculation of march cube is transferred into shader, and then send the shader to GPU for render.
So any such mechanism under VTK.js exist?
