### ISSUE TITLE
vtk.js  Change color

### ISSUE THREAD

**Issue by QearlGril** [Kitware/vtk-js#1116]
Hi @thewtex @jourda ，in the VolumeContour example,how can i change the 3D object's colors by vtkLookupTable? I tried and it didn't work.

**Comment by jourdain** [comment]
The marching cube does not compute or generate the scalar. But you can easily add it to your dataset and use the resulting polydata with the proper lookup table. Since it is an iso value, you just need to find how many points you have to create your scalar and call the Fill function on the Typed array.

**Comment by QearlGril** [comment]
Thank you for your reply，I'm a beginner. I don't quite understand what you mean. Can you give me an example to learn? Thank you again for your guidance.

**Comment by QearlGril** [comment]
const lookupTable = vtk.Common.Core.vtkLookupTable.newInstance({ hueRange: [0.666,0 ] });
	const mapper = vtk.Rendering.Core.vtkMapper.newInstance();
	var dataset = vtk.Common.DataModel.vtkDataSet.newInstance();
	dataset.setPointData(marchingCube.getOutputPort());
	mapper.setInputConnection(dataset.getPointData());
	mapper.setLookupTable(lookupTable);
	mapper.setUseLookupTableScalarRange(lookupTable);
	actor.setMapper(mapper);
----------------------
This is my code. Is it right?

**Comment by jourdain** [comment]
Kind of, but the data does have any scalar.

**Comment by QearlGril** [comment]
const lookupTable = vtk.Common.Core.vtkLookupTable.newInstance({ hueRange: [0.666,0 ] });
const mapper = vtk.Rendering.Core.vtkMapper.newInstance();
var dataset = vtk.Common.DataModel.vtkDataSet.newInstance();
dataset.setPointData(marchingCube.getOutputPort());
mapper.setInputConnection(dataset.getPointData());
mapper.setLookupTable(lookupTable);
mapper.setUseLookupTableScalarRange(lookupTable);
actor.setMapper(mapper);

function init() {
	  var width = 50, height = 50, depth = 50;
	  var size = width * height * depth;
	  var values = [];
	  for (var i = 0; i < size; i++) {
		values[i] = Math.random();
		}

	var scalars =  vtk.Common.Core.vtkDataArray.newInstance({
		values: values,
		numberOfComponents: 1, // number of channels (grayscale)
		dataType: vtk.Common.Core.vtkDataArray.VtkDataTypes.FLOAT, // values encoding
		name: 'scalars'
	});
	var imageData = vtk.Common.DataModel.vtkImageData.newInstance();
	imageData.setOrigin(0, 0, 0);
	imageData.setSpacing(1, 1, 1);
	imageData.setDimensions( width, height,depth)
	imageData.setExtent(0, width - 1, 0, height - 1, 0, depth - 1);
	imageData.getPointData().setScalars(scalars);

	marchingCube.setInputData(imageData);
	const dataRange = imageData
	  .getPointData()
	  .getScalars()
	  .getRange();
	const firstIsoValue = (dataRange[0] + dataRange[1]) /5;
	 marchingCube.setContourValue(firstIsoValue);
	renderer.addActor(actor);
	renderer.getActiveCamera().set({ position: [1, 1, 0], viewUp: [0, 0, -1] });
	renderer.resetCamera();
	renderWindow.render();
	}

-------------------
i push imageData in marchingCube，Is it right?
