### ISSUE TITLE
vtk.js vtkVolume setScale

### ISSUE THREAD

**Issue by QearlGril** [Kitware/vtk-js#1117]
Hi @jourda ，how can i change the Scale of vtkVolume ？I tried setScale()，but It's just move position.look forward to your reply,thanks

**Comment by QearlGril** [comment]
i found only“actor.getProperty().setScalarOpacity(1, ofun);” setScale() can change the Scale ，I don't quite understand.

**Comment by jourdain** [comment]
Since I don't understand what you try to do, I'll close the issue. BTW, who is @jourda?

**Comment by QearlGril** [comment]
sorry ,jourdain, i want to chang the the Scale of vtkVolume,But in the volumeMapper example ,only setScalarOpacity() 's param (index) will set “1”，the Scale of vtkVolume can only  changed.

**Comment by jourdain** [comment]
What is the scale of a volume? Its size on the screen?

**Comment by QearlGril** [comment]
const mapper = vtk.Rendering.Core.vtkVolumeMapper.newInstance();
mapper.setSampleDistance(1.1);
actor.setMapper(mapper);
actor.setScale(1,1,10);   
....
actor.getProperty().setScalarOpacity(1, ofun);

-------------
 this is volumeMapper example ,i only change "actor.getProperty().setScalarOpacity(0, ofun);" to "actor.getProperty().setScalarOpacity(1, ofun);" setScale() can changed 3D object's size.

**Comment by QearlGril** [comment]
const mapper = vtk.Rendering.Core.vtkVolumeMapper.newInstance();
mapper.setSampleDistance(1.1);
actor.setMapper(mapper);
actor.setScale(1,1,10);
....
actor.getProperty().setScalarOpacity(0, ofun);
-----------------------
setScale()  only changed 3D object's position.

**Comment by realcjames** [comment]
I have a similar issue, when I called actor.setScale(1, 1, 10), not only the scaleZ of the object changed, but also it moved alongside z-axis.
However, actor.getPosition() was still [0, 0, 0].
Don't know where went wrong and how to fix this...

#### code: 
```
setScale(sourceName, fieldValue = [1, 1, 10]) {
  const myRepresentations = this.$proxyManager
	.getRepresentations()
	.filter((r) => r.getInput().getName() === sourceName);
  for (let i = 0; i < myRepresentations.length; i++) {
	const actors = myRepresentations[i].getActors();
	if (actors && actors.length > 0) {
	  actors[0].setScale(fieldValue);
	}
  }
},
```

#### before setScale:
![20200602173451](https://user-images.githubusercontent.com/33344624/83504784-7ed53200-a4f7-11ea-85c7-d8fc1bccd2ab.png)

#### after setScale:
![20200602173521](https://user-images.githubusercontent.com/33344624/83504793-809ef580-a4f7-11ea-9b9c-37d770f83197.png)

@jourdain look forward to your reply, thanks, I am totally new to vtk.js...

**Comment by jourdain** [comment]
Let's pretend your object has the following set of bounds with no actor offset (position: 0, 0, 0) so the actor bound correspond to the actual data bounds without any translation:

```
bounds = [
   -1, 1, // minX, maxX
   -1, 1, // minY, maxY
    2, 3 // minZ, maxZ
]
scale = [1, 1, 10];

expectedNewBounds = [
  -1, 1,
  -1, 1,
   20, 30
]
```

So it makes total sense that it is moving up like it does on the picture.

**Comment by realcjames** [comment]
@jourdain Thanks, I got your point.
So I just need to setPosition after setScale right?
```
const minZBefore = actor.getZRange()[0];
actor.setScale([1, 1, 10])
const minZAfter = actor.getZRange()[0];
actor.setPosition([0, 0, minZBefore - minZAfter])
```

seems to me the problem was solved:

![20200603103429](https://user-images.githubusercontent.com/33344624/83589275-e2a63c00-a585-11ea-8956-e87bf23c4ce1.png)

**Comment by jourdain** [comment]
Yes that can be a way to do it.
