### ISSUE TITLE
ImageCropFilter.setCroppingPlanes(...planes) BUG

### ISSUE THREAD

**Issue by tanxu1120** [Kitware/vtk-js#1118]
Examples -> Filters/General -> ImageCropFilter

Dragging K range results in an error.

![15609155588763](https://user-images.githubusercontent.com/37609756/59735146-e6628500-9286-11e9-9984-19b4a8e67693.png)

**Comment by floryst** [comment]
I cannot seem to reproduce this even when closely matching your screenshot. (Tested on Firefox and Chrome.) Can you provide reproduction steps?

**Comment by tanxu1120** [comment]
step 1 : Open https://kitware.github.io/vtk-js/ in the Chrome browser.
![1](https://user-images.githubusercontent.com/37609756/59815359-e2983680-934a-11e9-8efc-72c7c638e295.png)
step 2 : Click on Examples.
![2](https://user-images.githubusercontent.com/37609756/59815503-53d7e980-934b-11e9-8d78-4d68320b3dc3.png)
step 3 : Click on ImageCropFilter.
![3](https://user-images.githubusercontent.com/37609756/59816148-9b5f7500-934d-11e9-85df-835fc3d8ebce.png)
step 4 : Rotate image to coronal position and zoom in.
![4](https://user-images.githubusercontent.com/37609756/59816325-407a4d80-934e-11e9-8d2b-ad318234629a.png)
step 5 : Drag K range, the image shows a problem.
![5](https://user-images.githubusercontent.com/37609756/59816432-a9fa5c00-934e-11e9-9408-bbc61e8cdced.png)

**Comment by floryst** [comment]
Hm, okay I cannot seem to reproduce the error. What browser are you using and what version? Does this behavior occur for other axes?

**Comment by tanxu1120** [comment]
GPU : NVIDIA GeForce GT 730M
vtk.js version : 8.8.0
Browser : Google Chrome 75.0.3770.100
OS : win7 64bit service pack 1

No problems with other axes.

**Comment by tanxu1120** [comment]
I tried it with a Mac, it works.

**Comment by aronhelser** [comment]
Repro on Win10, chrome, nvidia graphics. The volume seems to compress along the K axis, and leave double images. Crops properly along I, J axes.

**Comment by floryst** [comment]
@martinken
