### ISSUE TITLE
Point representation always render as black

### ISSUE THREAD

**Issue by hevo66** [Kitware/vtk-js#1120]
When rendering using point repsentation, the color does is not respected. The points are always rendered as black.

This can be reproduced in the GeoemtryViewer online example:

1. Open the diskout.vtp
2. Change representation to 'Points'
3. All points are black 
4. Change the solid color to any of the colors
5. Points are still Black

This issue seems to be introduced in v8.5.9.

**Comment by danmindru** [comment]
I can reproduce that as well on the latest Chrome and Firefox.

**Comment by martinken** [comment]
Should be an easy fix, I'll take a look this week

**Comment by danmindru** [comment]
Great, thanks! Just let me know if I can help somehow.

**Comment by hevo66** [comment]
Thank you for fixing this so quick :)

**Comment by martinken** [comment]
Very welcome :-)
