### ISSUE TITLE
cellPicker randomly picks backfaces with cubeSource

### ISSUE THREAD

**Issue by carpemonf** [Kitware/vtk-js#1122]
Hi,

I'm trying to use `cellPicker` with other shapes using the [cone example](https://kitware.github.io/vtk-js/examples/CellPicker.html). When using a `cubeSource` the picker randomly picks the backface instead of the frontface. I can't find any option for returning the first surface the ray hits.

### Step to reproduce it

- Copy the [code example for cellPicker](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/CellPicker/example/index.js).
- Replace `Cone` by `Cube`.
- Build and try to pick multiple faces in a cube face.

Thanks,
Carlos.

**Comment by gaston-perret** [comment]
> Hi,
> 
> I'm trying to use `cellPicker` with other shapes using the [cone example](https://kitware.github.io/vtk-js/examples/CellPicker.html). When using a `cubeSource` the picker randomly picks the backface instead of the frontface. I can't find any option for returning the first surface the ray hits.
> ### Step to reproduce it
> 
>     * Copy the [code example for cellPicker](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/CellPicker/example/index.js).
> 
>     * Replace `Cone` by `Cube`.
> 
>     * Build and try to pick multiple faces in a cube face.
> 
> 
> Thanks,
> Carlos.

Hello Carlos. Did you found any insight on this? I'm having the same problem.

**Comment by carpemonf** [comment]
Hi @gaston-perret,

I noticed that picking up front or back faces was not totally random. For instance with a 2D view (image attached), cells are selected on the front face on one side of the diagonal of the cube and on the other side for the back one. There might be something wrong on `node_modules/@kitware/vtk.js/Rendering/Core/CellPicker.js`.

![pick_cube](https://user-images.githubusercontent.com/4426168/127305341-ae2005a0-d592-40a0-b94f-cdc1b2f1ec09.png)

Best,
Carlos.

**Comment by finetjul** [comment]
vtkCellPicker only supports polydata with [triangles](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/CellPicker/index.js#L272), and not quads as in vtkCubeSource.
Would you mind adding vtkQuad to vtk.js ? The idea is to translate the [C++ vtkQuad](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Common/DataModel/vtkQuad.cxx) into Javascript. This is precisely what has been done for [vtkTriangle](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/Triangle/index.js).

**Comment by carpemonf** [comment]
Thanks @finetjul. I have made a quick test based on your comments by triangulating the quads from vtkCubeSource, and  then use that output in the cellPicker. This worked well and picked the right faces. I'm adding below the piece of code for the cube version of cellPicker with triangulation:

```
const cube = vtkCubeSource.newInstance();
const triangleFilter = vtkTriangleFilter.newInstance();
triangleFilter.setInputConnection(cube.getOutputPort());
const mapper = vtkMapper.newInstance();
mapper.setInputData(triangleFilter.getOutputData());
```

I guess this solution might work for some other cases where intersecting a quad is not strictly necessary.

**Comment by finetjul** [comment]
Yes, triangulating the quads will work.
The proper fix is still to create a vtkQuad class to handle it.
Anyone's welcomed to contribute it.
