### ISSUE TITLE
Picker: get wrong center in intersectWithLine

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1123]
I am trying to use the `vtkPicker` and get the picked actors. In the `intersectWithLine` function, I have an issue with the `center` which is alway an empty array: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Picker/index.js#L44

It seems to work by changing this line to
```
    const center = mapper.getCenter();
```
But there is maybe a bug somewhere, maybe in `getCenter`...?
Why to you splice the `model.center` instead of always returning it?

**Comment by floryst** [comment]
Good catch! I'm pretty sure that should be `model.center.slice(0)` (to copy the array), not a call to `splice`. That is a bug with the [AbstractMapper3D](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/AbstractMapper3D/index.js#L25).

**Comment by floryst** [comment]
After looking at this, I don't know why the AbstractMapper3D implements getCenter in that fashion. Anyways, there is a fix incoming.
