### ISSUE TITLE
Add jitter options for volume rendering

### ISSUE THREAD

**Issue by pieper** [Kitware/vtk-js#1129]
Currently jittering in volume rendering can add noise on the front clipping plane.

This is visible in the images in this comment: https://github.com/Kitware/vtk-js/pull/1093#issuecomment-501339753

It would be good if there were an option to turn off jittering, like there is in VTK-c++.

This pull request gives the option of disabling jitter: https://github.com/Kitware/vtk-js/pull/1109

@martinken suggested there's a jitter-related bug that should also be fixed: https://github.com/Kitware/vtk-js/pull/1109#issuecomment-501371362

**Comment by aylward** [comment]
Appears remaining issue is duplicate with #1109
