### ISSUE TITLE
Open VTK file using vtkPolyDataReader

### ISSUE THREAD

**Issue by emccourt** [Kitware/vtk-js#1133]
So I'm trying to get this (https://kitware.github.io/vtk-js/examples/PolyDataReader.html) example to run locally. 

I followed the directions here (https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) exactly for building, only changing the source code of the js file to be exactly the same as the example. 

I originally tried putting the sphere file in /dist/data/sphere.vtk and setting the url to that, but that didn't render (just gave me the purple background window), so then I tried changing the url to point directly to "https://github.com/Kitware/vtk-js/blob/master/Data/legacy/sphere.vtk", which should be the exact same file that the hosted example is opening, yet it still doesn't open it. 

Is there something I'm missing in the local implementation as far as file IO goes?

**UPDATE:** I've also tried building the STL reader example (https://kitware.github.io/vtk-js/examples/STLReader.html) as-is, opening the local html file, and selecting a local .stl file to open, still nothing. I've had no problems with creating geometries from ConeSource and such, so maybe there's a problem with how the readers work locally?

**Comment by jourdain** [comment]
The reader should be fine. I'm not sure to know what you are doing. Maybe it is just a cross-origin issue?

You can try to download the pre-compiled example here https://kitware.github.io/vtk-js/examples/PolyDataReader/PolyDataReader.html.

Then you can look at the url requested for fetching the VTK file in the network tab.

**Comment by emccourt** [comment]
Hi, thanks for responding.

While I did never figure out PolyDataReader or the STL reader, I was eventually able to run the Geometry Viewer example and load the Earth.vtp file locally, so maybe there was just an issue with some of the other file formats I was trying to open before. 

Either way, things work now so I'll close the issue. Thanks again for getting back to me, though.
