### ISSUE TITLE
WebApp Integration

### ISSUE THREAD

**Issue by TheMegaMatt** [Kitware/vtk-js#1137]
Hello, 
I would like to integrate the OBJViewer from this library in a ASP.net MVC Application,  but all the samples dont seem to point to a clear guide on how to integrate with a standard web page.

How can i do so? I'd be more than fine with the code of https://kitware.github.io/vtk-js/examples/OBJViewer/OBJViewer.html not obfuscated or some guidelines on how to reach that point

**Comment by aronhelser** [comment]
Have you found the example source? https://github.com/Kitware/vtk-js/tree/master/Examples/Applications/OBJViewer
The html page is generated by webpack - I'm not finding the rule right now, but basically everything is done with the js code in the source. If you want to use it as-is, you just need to provide a container, I think.

**Comment by TheMegaMatt** [comment]
@aronhelser would you be able to show me how to configure Webpack?

**Comment by jourdain** [comment]
Just follow that [guide](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) and use the application example as base for the code rather than the simple cone.

**Comment by TheMegaMatt** [comment]
@jourdain i did as you suggested but i have a problem with webpack, after compiling an including the code in my app, none of the function is accessible. what are the required configuration on webpack?

**Comment by floryst** [comment]
Are you trying to include the compiled code into your project and using some global name to access methods in the OBJViewer, or are you trying to import the source code into your project (e.g. something like `import { load } from './OBJViewer.js'`?

If you're trying to access functions like `load()` when you've included the compiled code into your project (effectively using OBJViewer as a library), you'll need to set the webpack `output.library` config to some global variable name, like "OBJViewer". See [this for more info](https://webpack.js.org/configuration/output/#outputlibrary).
