### ISSUE TITLE
Using multiple RenderWindows (more than 16)

### ISSUE THREAD

**Issue by johannesdd** [Kitware/vtk-js#1138]
Hey,
My project is about reading in a *.vtp file and displaying it with an offline *.html file. One of the requirements was that multiple 3d renderWindows, one for each scalar and vector information, can be viewed statically; so theoretically only one needs to be rendered at a time and it can quit rendering when the mouse courser exits the allocated window. Unfortunately, the number of windows exceeds 16, so there will be a WebGL issue and the oldest one not used will be deleted. So I end up with 16 working instances and (in for my test file) 8 disabled windows. Is there a way to get around this, for example disabling a renderWindow when it is not in use? 

Thank you in advance

**Comment by jourdain** [comment]
Did you try to create a single RenderWindow with 16 renderer?

**Comment by johannesdd** [comment]
Unfortunately not. I need to put them into different Containers so they can be easily maneuvered around to the place the user desires. Or is there a way to put different Renderers of the same RenderWindow into different Containers?

**Comment by jourdain** [comment]
Not really but if they all belong to a single big container, then yes. You could possibly drag a renderer from left to right...

**Comment by johannesdd** [comment]
The problem is I need the different containers since the objective was to display every output (be it 3d Content or tables) on A4 sized pages (similar to Letter size) so we see what a printed result would look like before outputting it into a .pdf file.  So I can not put it all into one single container.

Since there will probably be no other way, I will have to delete the RenderWindow every time, replace it with an image and then set a new RenderWindow, when I want to interact with that window again?

Now I don't know how far to go. Is the genericRenderWindow that can not exceed 16 or is it the renderWindow I get with .getRenderWindow() that makes the problem. The console only says that I exceed 16 live WebGL contexts.

**Comment by jourdain** [comment]
The 16 limitation comes from WebGL, but if I were you I would use only one RenderWindow that I will change its container based on which view in my A4 page I'm editing and then fill those containers with a static image.
