### ISSUE TITLE
Opacity with lookup table

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#1140]
I have an issue with a simple lookup table code.
I'm using vtk.js 8.9.1 and here is the code I have:
`
const lut = mapper.getLookupTable();
lut.setNumberOfColors(10);
lut.setAlphaRange(0.0, 1.0);
`
This lookup table is associated to a mesh which has only an array in pointData which contains values between 0 and 9.
My concern is that the polydata doesn't appear.
What I want is to display a polydata with some points hidden and some points displayed.
This code worked with a very old version of vtk.js (2.24.8).
I think something happens in the OpenGLMapper. 
@martinken @jourdain Do you have any idea ? Unfortunately it's quite urgent. Thanks for your help.

**Comment by jourdain** [comment]
@martinken changed something when we have rgba data that was broken before. It might be related to that change.

**Comment by laurennlam** [comment]
Do you have any clue on how I can use opacity ?

**Comment by thewtex** [comment]
For what it is worth, I observe possibly related behavior using recent vtk.js. The PolyData does not have PointData and I cannot see the points. I only recently created the code, though, so I do not know if it worked before.

xref https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/152

**Comment by martinken** [comment]
Do you have a simple test case you can send me, or can you create one?

**Comment by laurennlam** [comment]
I'll try to do it quick and share it with you.

**Comment by laurennlam** [comment]
I just tried a little example with the last version and it seems to work...
I also tried to update my vtk.js version on my project and it doesn't work.
So my conclusion is that the issue comes from my project. Sorry for the inconvenience guys. Thanks.
