### ISSUE TITLE
ResliceCursor interaction

### ISSUE THREAD

**Issue by qqsea** [Kitware/vtk-js#1143]
Current demo of ResliceCursor display the function of MPR slice and the operation for any center and any angle adjustment. But usually, user will not 'move mouse ' on the center point (x,y,z) directly, user just move the reference line. If user want to adjust the center, he/she will  move only one of these three reference lines (axial, saggital, saggital)  at a time, which means the coordinate of the center point will be updated only one direction. As to the angle adjustment, it is the same with demo of ResliceCursor. The center point keep static, and only rotate reference line.

So could you provide such snip codes for my questions or give me some idea on how to implementation it?

Thank you very much!

**Comment by mix3d** [comment]
I actually found I wished I could click where I wanted the reference line crosspoint to be, rather than click and drag the center (which has a very small hitbox)

**Comment by floryst** [comment]
I'm not familiar with the ResliceCursor (I think @finetjul knows more about the implementation), but in both cases I think the ResliceCursorLineRepresentation contains the relevant code. Specifically, [this block of code](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/ResliceCursor/ResliceCursorLineRepresentation/index.js#L219) is the logic for moving the cursor if the center is selected. You will probably need to add some flag to the ResliceCursorWidget that controls whether the reference lines rotate or simply move the center.

As for clicking where the reference lines should be, I'd check to see if you can set the center coordinate on the reslice cursor widget directly. That way you can just take click events and set the reslice cursor widget's position accordingly.

**Comment by aylward** [comment]
@finetjul  - perhaps this can be closed - assuming it has been addressed by changes to ResliceCursor since July 2019?

**Comment by finetjul** [comment]
ResliceCursorWidget went through a lot of changes recently.  Expected rotation behavior has notably been implemented.

Simple click to place the cursor center is not available in the example but the widget API lets you do it.
