### ISSUE TITLE
Jitter-related artifact in thin-slice volume renderings

### ISSUE THREAD

**Issue by swederik** [Kitware/vtk-js#1146]
Hi all,

There is a noticable artifact when using the thin-camera-clipping-range MPR approach. It looks like a bit of fuzziness. I suppose the artifact is also there in generic volume rendering but it's less obvious. If you disable jitter you can resolve it, but that doesn't seem like the final solution.

I'd like to take a stab at solving this problem so I figured it made sense to create a new issue to track it.

You can see the artifact here: https://kitware.github.io/vtk-js/examples/InteractorStyleMPRSlice.html

![Screenshot 2019-07-18 14 10 47](https://user-images.githubusercontent.com/607793/61456366-24c29100-a966-11e9-89ff-0e69c496a480.png)

Here is @martinken's description:

> And finally I *think* the issue with the thin slice is that the jitter residual is only handled on the end, but there is also a jitter residual at the start. Normally that makes little difference as the edges of the volume are transparent, but in this case, with such a thin slab, the missing jitter value from the beginning I think makes a difference. The fix will be to do a start residual, loop, then end residual. Right now we just have loop and end residual.

_Originally posted by @martinken in https://github.com/Kitware/vtk-js/pull/1093#issuecomment-501375681_

Thanks!

Relevant code:

https://github.com/Kitware/vtk-js/blob/c9fa0ceb23390af7b9059056b18024ffa96fa9c5/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L758

https://github.com/Kitware/vtk-js/blob/c9fa0ceb23390af7b9059056b18024ffa96fa9c5/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L553

**Comment by martinken** [comment]
I think the fix is just to handle the start jitter as well. Basically do the same gist and the end residual but for start residual. Should be a fairly easy fix

**Comment by swederik** [comment]
Oh you weren't kidding, that was a lot easier than I expected. I'll send the PR shortly!

**Comment by mix3d** [comment]
will that Jitter fix also fix the case where you get weird artifacts when at the max volume range?

![image](https://user-images.githubusercontent.com/1474137/61478951-a656f680-a947-11e9-8358-0776449474bc.png)

**Comment by swederik** [comment]
Weird, I don't see that artifact even before the changes. Which browser? I do see flickering at max volume range here though: https://kitware.github.io/vtk-js/examples/InteractorStyleMPRSlice.html

**Comment by mix3d** [comment]
Chrome, both windows and Mac

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, Jul 18, 2019 at 10:46 AM -0700, "Erik Ziegler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Weird, I don't see that artifact even before the changes. Which browser? I do see flickering at max volume range here though: https://kitware.github.io/vtk-js/examples/InteractorStyleMPRSlice.html

**Comment by aylward** [comment]
Duplicate with #1152

**Comment by aylward** [comment]
Min/Max slice issue cannot be replicated (see #1150)  - perhaps old GPU precision bug.

Jitter fixed in PR
