### ISSUE TITLE
Max File Size?

### ISSUE THREAD

**Issue by emccourt** [Kitware/vtk-js#1147]
Hi all. I have a series of slices that I've converted into a .vti file using [this](http://vtk.1045678.n5.nabble.com/Convert-a-series-of-DICOM-files-into-a-VTI-File-td5748876.html#a5748879) method to visualize them in the VolumeViewer app. When I have set the sampling rate >= 2 to reduce the file size, everything works fine. However, if I set the spacing to 1 to retain details (creating a .vti file at around 2 GB) the viewer fails to load it. I've successfully loaded images up to 800 MB, so I'm wondering if there's a set limit on how big files can be, or if the problem is in my encoding (which would be strange, since the method is the same save for the spacing).

Checking the console in f12, there are two errors: "Invalid data type null expecting ImageData", and "Uncaught TypeError: Cannot read property 'getPointData' of undefined"

It seems like the image isn't being parsed correctly because of the size. Is this on vtk-js's side, or the html input limiting the upload size? Thanks in advance!

**Comment by jourdain** [comment]
What browser on what platform?
What is the format for the vti?
- ascii/binary/appended?
- compressed: zlib?

All of that can be defined using the writer you use.
I haven't done much testing but I tend to prefer the appended+zlib compression.

Then, I'm guessing the limitation is on the browser side when the data get decoded based on the error you are getting.

**Comment by jourdain** [comment]
BTW, you can easily use ParaView to re-write the vti files using various encoding to try out.

**Comment by emccourt** [comment]
Latest version of Chrome on Windows 10 Pro.
When I write the vti exactly the same as the link does (changing nothing but the spacing) the format is "appended" and the compressor is listed as "vtkZLibDataCompressor".

And thanks for the suggestion, I'll go try and see if converting the files with ParaView makes any difference.

**Comment by emccourt** [comment]
I've loaded the image stack in ParaView and saved it as an appended encoded .vti compressed with Zlib (at compression rates 6, 3, and 1) and none of the files load. They did get farther than my original .vti file, but seem to crash upon creating the VolumeController (all that renders in the scene is the controller with the histogram but no Gaussian curve) 

Below is the debug when I ran the code locally:
![Capture](https://user-images.githubusercontent.com/25906998/61561272-763d4f80-aa3c-11e9-8bbd-0291d4449fcd.PNG)

What method do you use to convert DICOM/Tiff stacks to .vti files? I'm not adding any filter layers in the ParaView pipeline, just loading in the stack and saving it.

**Comment by jourdain** [comment]
The issue still seems to be related to allocation of the TypedArray inside the browser. Just our of curiosity, what is the dimension of the image x,y,z?

**Comment by emccourt** [comment]
1024, 1024, 928 (pixels)

**Comment by jourdain** [comment]
And the type of the field (Uint16...) ?

**Comment by emccourt** [comment]
DataArray type = UInt16, RangeMin = 0, RangeMax = 63900

**Comment by jourdain** [comment]
```
data = new Uint16Array(1024*1024*928)
=> ok
data = new Float32Array(1024*1024*928)
=> error same as yours
```

@martinken do we create a float32 array for the GPU of the size of the image data? If so that is indeed the limit.

**Comment by martinken** [comment]
u16 is promoted for float for volume rendering, probably image rendering as well. I believe the issue is that U16 is not filterable by webgl (no linear interpolation in hardware) so we promote it.
