### ISSUE TITLE
 HttpDataAccessHelper.js fails to load .vti file on Firefox

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1149]
Firefox v68 (Mac) and v67 (Windows) are failing to load .vti files with HttpDataAccessHelper, with the following message:

```
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer HttpDataAccessHelper.js:84
    onreadystatechange HttpDataAccessHelper.js:84
```

The same files work fine on Chrome, Safari, and Edge.

Example: https://vue-vtkjs-viewport.netlify.com/#/example/basic

**Comment by jourdain** [comment]
I think it is related to byte alignment when decoding and how vue on Typed array are managed across the browser. My guess is that we need to do something like [that](https://stackoverflow.com/questions/7372124/why-is-creating-a-float32array-with-an-offset-that-isnt-a-multiple-of-the-eleme)

**Comment by mix3d** [comment]
Interesting that it is indeed vue specific... since the other examples work fine. Hmm!

**Comment by jourdain** [comment]
By Vue, I don't mean vue.js but a view of a TypedArray like

```
const bytes = new Uint8Array(...);
const float = new Float32Array(bytes, 3, 10); // <-- this is a vue of the data
```

**Comment by floryst** [comment]
I think this is a case of the received arraybuffer length not being a mutiple of your dataset datatype (which I see is Uint16). Can you make sure your dataset size is a multiple of 2?

**Comment by mix3d** [comment]
It works on other browsers though. It even fails on the same volume used on all the vtk.js examples (https://github.com/Kitware/vtk-js/tree/master/Data/volume/headsq.vti)

**Comment by floryst** [comment]
This might be a bug in Firefox. The netlify server is sending `Content-Encoding: gzip`, but firefox isn't decoding the data as it should be doing. If you pop into the debugger and check out the data, firefox is giving you the gzipped version of "0edblahblahblah.gz" (so two gzip layers). I think this is the relevant bug report for firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1269101

**Comment by mix3d** [comment]
What a bummer of an issue. Not VTK though, so we can close the bug.
