### ISSUE TITLE
How to render polyline and solid

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1156]
I would like to render all mesh types (point set, polyline, polygonal surface, polyhedral solid). I understand I have to use the PolyData object to render each surface or each point set.

However, I am not sure how to use it for polyline ans solid? What would be your advises?

Thanks a lot for your help !

**Comment by jourdain** [comment]
VTK is using the vtkExtractSurface filter to do such conversion which requires some knowledge on the cells which are not implemented in vtk.js, hence the issue. 

Polyline is fine for polydata, the issue is just the solid cells as you have to find and render only the "outside surface".

**Comment by BotellaA** [comment]
Thanks for your quick answer ! 

Ok, I can find the outside surface and add it to the PolyData. This step is only for performance issue? 

For the polyline, I have to add only the vertices? How do you know the path of the line to draw?

**Comment by jourdain** [comment]
```
const lineCellArray = polydata.getLines();

lineCellArray.setData(Uint16Array.from([
  nbPointsInPolyLine, pointIdx0, pointIdx1, pointIdx..., pointIdxN,
  nbPointsInPolyLine, pointIdx0, pointIdx1, pointIdx..., pointIdxN,
  nbPointsInPolyLine, pointIdx0, pointIdx1, pointIdx..., pointIdxN,
  nbPointsInPolyLine, pointIdx0, pointIdx1, pointIdx..., pointIdxN,
 ...
]));


```

**Comment by BotellaA** [comment]
Great ! Thanks !
