### ISSUE TITLE
Take screenshot from canvas?

### ISSUE THREAD

**Issue by truongleit** [Kitware/vtk-js#1159]
Hi, I would like to take a screenshot from the rendered canvas but when I tried to apply to `toDataURL()` to get the `base64`, the result is completely blank. In addition, I already took a look at the ParaView Glance's source code covering the screenshot feature but I am still very confused at the part `img.addEventListener('load', () => {}`. Here is my source code, hope to reiceve the answer from you. Thanks. @jourdain 

```
function convertCanvasToImage(canvas) {
    var image = new Image();
    image.src = canvas.toDataURL("image/png");
    return image;
}
base64 = convertCanvasToImage($('#3d canvas').get(0)).src;
```

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/RenderWindow/index.js#L582

**Comment by truongleit** [comment]
It didn't work out, I tried `console.log(openglRenderWindow.captureNextImage());` but just received a message  `Promise {<pending>}` in browser's console. @jourdain

**Comment by jourdain** [comment]
Great, that is what you are suppose to get...

**Comment by jourdain** [comment]
The promise content will have the data you are looking for.

**Comment by jourdain** [comment]
The just trigger a render() to allow the promise to resolve.

**Comment by truongleit** [comment]
Thanks for the assistance! I truly appreciate your patience 😃 @jourdain
