### ISSUE TITLE
ResliceCursor: Strange rotation issues / strange behaviors with actual volumes

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1161]
The example for using the ResliceWidget uses a code-generated volume, so it is hard to tell if it is working correctly. 

I re-implemented with a real volume, but am noticing strange behaviors.

![reslice widget](https://user-images.githubusercontent.com/1474137/61972708-12180f80-af97-11e9-9ba9-d2219ab54b4a.gif)
https://vue-vtkjs-viewport.netlify.com/#/example/reslice

**Comment by mix3d** [comment]
it's worth noting that the center of the volume is not world coordinate center, but the Reslice Widget does seem to rotate from world center, as it also defaults to world 0,0,0 for the intersection of all 3 planes.

**Comment by mix3d** [comment]
I can re-capture with the mouse included.

**Comment by finetjul** [comment]
There might be a bug indeed. 
One thing that can help to debug is to reproduce the example in VTK (C++) and see if (where) there is a different behavior.

**Comment by mix3d** [comment]
I'm mostly a JS / web guy though :/

**Comment by ematvey** [comment]
Any news regarding this issue?

**Comment by finetjul** [comment]
No, no news on this. PR are welcomed :-)

**Comment by mix3d** [comment]
I abandoned this tool and wrote my own; webgl's lack of line thickness alone was a no go.

**Comment by ematvey** [comment]
@mix3d Did you abandon ResliceWidget or VTK.js? I can hardly imagine how this can be done on client without webgl.
Any plans to open source your implementation?

**Comment by mix3d** [comment]
@ematvey just the reslice widget. I built an svg based overlay system with a position translator, because the current state of svg widgets in vtk doesn't meet our needs either. Interacting with my custom slice axis widget overlay adjusts the camera view, while panning/zooming updates the location of the center of the axis representation. It's a very application specific implementation though.

**Comment by ematvey** [comment]
@mix3d Actually this sounds pretty close to what I'm thinking of building: pretty standard MPR tool with an option of oblique slices. ResliceWidget is close, but has rotation bugs, and panning/rotating UX needs some work.
Is you application available online? I'd love to play with it.

**Comment by mix3d** [comment]
@ematvey here's an old version from when I had tried to make it a standalone project /component, but integration required pulling the source code directly into our app so this is a bit abandoned.

https://vue-vtkjs-viewport.netlify.com/#/example/mpr-manager

**Comment by ematvey** [comment]
@mix3d perfect, this looks like pretty complete MPR example for vtk.js, thank you for open-sourcing it.

**Comment by mix3d** [comment]
ResliceCursor has been reworked recently, but I'm going to just close this issue for now.
