### ISSUE TITLE
Callback on render to update the FPS?

### ISSUE THREAD

**Issue by victornguyen18** [Kitware/vtk-js#1163]
Hi, I have a small problem in integrating [FPSMeter](http://darsa.in/fpsmeter/) into my app. In fact, I checked this [example ](https://kitware.github.io/vtk-js/examples/Cone.html) showing the usage of VTK's FPS Monitor and found out the way it refreshes the monitor is calling `fullScreenRenderer.setResizeCallback(fpsMonitor.update);`. However, I am using 3 classes, which are `RenderWindow`, `Renderer` and `RenderWindow` (OpenGL) for the rendering process. Certainly I tried` console.log(renderWindow)`, `console.log(openglRenderWindow);` but found nothing having same functionality as `setResizeCallback` to place the fps-updating call of FPSMeter. Can you guys give me some assistance? Thanks.

**Comment by jourdain** [comment]
First of all the FPSMeter that you plan to use is not the one highlighted in the vtk.js example.
Based on the documentation of the FPSMeter linked above, you need to call the tick() function after each render which can be done with the following code snippet.

```
rw.getInteractor(). onAnimation(() => {
  meter.tick();
});
```

For the vtk.js meter the key part is `fpsMonitor.setRenderWindow(renderWindow);` not the update call. In fact you can see the same logic happening in the vtk.js fps meter [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/UI/FPSMonitor/index.js#L152-L162).

**Comment by victornguyen18** [comment]
Thanks so much
