### ISSUE TITLE
Surface + Edges + Points representation

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1166]
How should I use vtk.js to render a `PolyData` with its edges and points? There is no such representation in the `GeometryRepresentationProxy`. Is it difficult to add this feature?

**Comment by finetjul** [comment]
Have you tried to setVerts() on the polydata ? it should render them.

**Comment by BotellaA** [comment]
Thanks for your very quick response!!
No, I did not try this. What is the difference between `setVerts` and `setPoints`? Should I do both?

**Comment by finetjul** [comment]
`setPoints` sets points (xyz coordinates), `setVerts` sets vertices (cells made of 1 point ID)

**Comment by BotellaA** [comment]
Thanks! `setVerts` works like you said. :smiley:
