### ISSUE TITLE
How to update color of point in polydata?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1167]
For example in vtk python,

it is possible to update point color using
``
polydata.GetPointData().GetScalars().SetTuple(pointId, [color])
``

is there any similar operation for vtk.js?

**Comment by jourdain** [comment]
```
const scalars = polydata.getPointData().getScalars();
scalars.getData()[pointId * 3] = red;
scalars.getData()[pointId * 3 + 1] = green;
scalars.getData()[pointId * 3 + 2] = blue;
scalars.modified();
```

**Comment by EJShim** [comment]
@jourdain  Thanks, but I get error when I call `` scalars.getData() ``

saying

``
Unhandled Rejection (TypeError): Cannot read property 'getData' of null
``

Do I have to do something before I use this method?

**Comment by jourdain** [comment]
That just mean that you don’t have scalars.
Do you at least have one array?

**Comment by EJShim** [comment]
@jourdain I did not have arrays actually, So I made one and set scalar as below : 

``
         const polyData = stlReader.getOutputData();
        
        const colorData = vtkDataArray.newInstance({
            name: 'Colors',
            values: new Float32Array(polyData.getPoints().getNumberOfTuples() * 3),
            numberOfComponents: 3,
        });


        for(let index = 0 ; index < colorData.getNumberOfTuples() ; index++){            
            colorData.setTuple(index, [Math.random(), 0.0, 0.0])
        }       
        colorData.modified();

        polyData.getPointData().setScalars(colorData);        
        polyData.getPointData().setActiveScalars('Colors');
        polyData.getPointData().modified();

``

With this, I get different colors of each vertex. but the "tuple" of each point is not RGB array.

Only the first element of each tuple affects vertex color, and I do not know what the other two elements doing.

for the first element, if the value is 0.0 the vertex color gets red, 0.5 makes green, 1.0 makes blue.


is there any way that I can set RGB Color to this data array?

**Comment by EJShim** [comment]
I resolved it by setting        ``  .setColorModeToDirectScalars();  `` in mapper.

Thank you for your kind response
