### ISSUE TITLE
How to update pointData color dynamically after renWin.render() ??

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1171]
Hello

I would like to update point color of polydata dynamically.

It works when I assign color BEFORE renderWindow.render() (refresh renderer).

but once I call renderWindow.render(), same code changes nothing.

`
const colors = polyData.getPointData().getScalars();

colors.setTuple(index, [color])

polyData.getPointData().modified()

**renderWindow.render()**;
`
it works
but

``  **renderWindow.render()**; 

const colors = polyData.getPointData().getScalars();

colors.setTuple(index, [color])

polyData.getPointData().modified()

**renderWindow.render()**;  ``

it does not work.

I tried `polyData.getPointData().getScalars().modified()`

or ``mapper.update()``, none of them worked

**Comment by jourdain** [comment]
The only `modified()` call that should be needed is on the `colors` vtkDataArray. 

What is your mapper configuration for `ColorMode`, `ScalarVisibility`, `InterpolateScalarsBeforeMapping`, `ScalarMode`?

@martinken might be another mtime issue?

**Comment by EJShim** [comment]
I set ``ColorMode`` to RGB, and ``ScalarVisibility`` True.

Actually, I resolved this issue by calling ``polyData.modified()``

``colors.modified`` and ``polyData.getPointData().modified()`` did not work.
