### ISSUE TITLE
Base64 encoding broken in 9.4.0

### ISSUE THREAD

**Issue by euandekock** [Kitware/vtk-js#1173]
The 9.4.0 version of vtk has implemented an internal version of the base64 encoder. This appears to break how it handles base64 encoding/decoding.
The error below is what I am seeing, it looks like it is caused by trying to call charCodeAt on an object that is not a string type.

This occurs on line 46 of Sources/Common/Core/Base64/index.js in the isValidChar function.

> Uncaught TypeError: e.charCodeAt is not a function
>     at o (unpkg.com/vtk.js@9.4.0/dist/vtk.js:14)
>     at s (unpkg.com/vtk.js@9.4.0/dist/vtk.js:14)
>     at Object.toArrayBuffer (unpkg.com/vtk.js@9.4.0/dist/vtk.js:14)
>     at Object.e.parseAsArrayBuffer (unpkg.com/vtk.js@9.4.0/dist/vtk.js:282)
>     at eval (eval at <anonymous> (cdnjs.cloudflare.com…2.4/jquery.min.js:2), <anonymous>:265:15)
>     at eval (<anonymous>)
>     at cdnjs.cloudflare.com…2.4/jquery.min.js:2
>     at Function.globalEval (cdnjs.cloudflare.com…2.4/jquery.min.js:2)
>     at Ha (cdnjs.cloudflare.com…2.4/jquery.min.js:3)
>     at n.fn.init.append (cdnjs.cloudflare.com…2.4/jquery.min.js:3)

**Comment by floryst** [comment]
Thanks for the report. I'll look at it.

**Comment by euandekock** [comment]
Many Thanks. Confirmed all working now.
