### ISSUE TITLE
Integration itkjs/vtkjs

### ISSUE THREAD

**Issue by RemiCecchinato** [Kitware/vtk-js#1176]
I need to use some functionalities of itk-js with vtk-js. I have not found any way to convert a labelMap from vtk-js format to itk-js format.
Are there some utilities to interface between itk-js and vtk-js for that purpose ? Are there some examples somewhere I can check out ?

**Comment by finetjul** [comment]
@thewtex should a convenient function convertVtkToItkImage (similar to convertItkToVtkImage) be written? Or is there something already existing?

**Comment by thewtex** [comment]
> @thewtex should a convenient function convertVtkToItkImage (similar to convertItkToVtkImage) be written?

@finetjul @RemiCecchinato yes, that will do the trick!
