### ISSUE TITLE
Label widget example offset on windows 10

### ISSUE THREAD

**Issue by aronhelser** [Kitware/vtk-js#1179]
Here's what it looks like on win10 chrome, offset off the upper right corner:
![image](https://user-images.githubusercontent.com/19917213/63177928-f42e4f80-c016-11e9-8bce-660787f2f734.png)

**Comment by finetjul** [comment]
@RemiCecchinato @luciemac

**Comment by RemiCecchinato** [comment]
@aronhelser I wasn't able to reproduce this, do you have more specific informations ?

**Comment by aronhelser** [comment]
Oops, sorry, should have tried my second screen. It only repros on my 15" laptop with a high-DPI screen (3840 x 2160). If I move my window to my attached montior, not high-dpi (34", 2460 x 1600), the label is in the center. 

For the high-dpi screen, in the Display control panel, the "Scale and layout - Change the size" is 200% - I'm sure that's the issue.

**Comment by mix3d** [comment]
This is an issue with canvas pixels vs high dpi screens. 

I have this code in one of my widgets,`x: this.point[0] / window.devicePixelRatio` with an accompanying one for `y`, to accommodate the canvas pixels vs screen pixels disparity.

**Comment by vibraphone** [comment]
I see this on macos with a retina display as well.

**Comment by jourdain** [comment]
Fixed in 17.5
