### ISSUE TITLE
Wireframe representation shader compilation error

### ISSUE THREAD

**Issue by bilke** [Kitware/vtk-js#119]
I have a [simple visualization](https://dev.opengeosys.org/docs/benchmarks/elliptic/groundwater-flow-neumann/#results-and-evaluation). When switching to wireframe representation it renders one image but when I e.g. rotate the view the object  disappears. Looking at the Java Script console I can see that the `vtkPolyDataFS.glsl` shader can not be compiled with the following error:

```
': ERROR: 0:101: 'texture1' : undeclared identifier 
ERROR: 0:101: 'tcoordVCVSOutput' : undeclared identifier 
ERROR: 0:101: 'st' :  field selection requires structure or vector on left hand side 
ERROR: 0:101: 'texture2D' : no matching overloaded function found 
ERROR: 0:101: '=' :  cannot convert from 'const float' to 'highp 4-component vector of float'
```

Do you have an idea what's wrong here? You can find the source of the visualization [here](https://github.com/bilke/ogs/blob/web-hugo/web/src/js/vis/index.js). Thanks!

**Comment by martinken** [comment]
I'll take a look.

**Comment by jourdain** [comment]
Despite the error you are running into, this is awesome! 
So cool to see some vtk.js usage outside Kitware.

**Comment by martinken** [comment]
Could  you try this small patch and see if that fixes the issue?

diff --git a/Sources/Rendering/OpenGL/PolyDataMapper/index.js b/Sources/Rendering/OpenGL/PolyDataMapper/index.js
index d32ec60..413f4e4 100644
--- a/Sources/Rendering/OpenGL/PolyDataMapper/index.js
+++ b/Sources/Rendering/OpenGL/PolyDataMapper/index.js
@@ -1302,8 +1302,12 @@ export function vtkOpenGLPolyDataMapper(publicAPI, model) {
       options.cellOffset += model.primitives[primTypes.TriStrips].getCABO()
         .createVBO(poly.getStrips(), 'strips', representation, options);

+      const drawSurfaceWithEdges =
+        (actor.getProperty().getEdgeVisibility() &&
+          representation === Representation.SURFACE);
+
       // if we have edge visibility build the edge VBOs
-      if (actor.getProperty().getEdgeVisibility()) {
+      if (drawSurfaceWithEdges) {
         model.primitives[primTypes.TrisEdges].getCABO()
           .createVBO(poly.getPolys(), 'polys', Representation.WIREFRAME,
           {

**Comment by bilke** [comment]
@martinken Yes, your patch fixes it!

**Comment by martinken** [comment]
Fantastic!  I have merged the change into master. Thanks for letting us know about it.
