### ISSUE TITLE
Displaying the same ViewProxy in several locations

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1193]
I would like a way to display the same view in several DOM elements. Currently, I need to use the `setContainer` to only one element. Is it possible to clone the view or something like that?

Thanks for your advise

**Comment by jourdain** [comment]
If you want several view, you need to make a new instance everywhere you need that view to be.
If it is to just have the same exact image, you can make some "live capture" that will produce images that you can then place in various places of your web page.

HTH

**Comment by BotellaA** [comment]
Thanks, I will probably create more views.
