### ISSUE TITLE
Get picked actor

### ISSUE THREAD

**Issue by micheleivani** [Kitware/vtk-js#1196]
I'm testing the VTK js version. I already made some apps in C# with the regular VTK library.
My goal is to left-click on the `renderer` in which there are some STL files loaded and then get the selected actor references.

In c# I use the `vtkActor actor = NewPicker.GetViewProp() as vtkActor;`
In .js after calling the ` this.picker.pick(point, renderer);` the picker contains several actors and I'm not able to select the clicked one.

Can you help me? Thank you.

**Comment by jourdain** [comment]
Regular picker I think do a lot of Math with might not be optimum in JS. 

You may want to use the hardware selector similar to what is done in that [test](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelector.js)

**Comment by micheleivani** [comment]
Thank you for feedback. I have tried to implement the hardware selector, but I have some doubts when I have to call the `selector.setArea(...)` method. What are the values I need to insert?

Here is an extract of my code:
The init code
```
init3D() {
  // const background = this.colorToDouble();
  const background = this.colorToDouble(245, 247, 250);
  this.renderWindow = vtkRenderWindow.newInstance();
  this.renderer = vtkRenderer.newInstance({ background: background });
  this.renderWindow.addRenderer(this.renderer);

  const openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
  this.renderWindow.addView(openglRenderWindow);

  let container = this.$refs.vtk;
  openglRenderWindow.setContainer(container);
  openglRenderWindow.traverseAllPasses();
  const { width, height } = container.getBoundingClientRect();
  openglRenderWindow.setSize(width, height);

  const interactor = vtkRenderWindowInteractor.newInstance();
  interactor.setView(openglRenderWindow);
  interactor.initialize();
  interactor.bindEvents(container);
  interactor.setInteractorStyle(
    vtkInteractorStyleTrackballCamera.newInstance()
  );

  this.picker = vtkOpenGLHardwareSelector.newInstance();
  this.picker.setFieldAssociation(
    FieldAssociations.FIELD_ASSOCIATION_POINTS
  );
  this.picker.attach(openglRenderWindow, this.renderer);

  this.renderWindow.getInteractor().onLeftButtonPress(this.handleLeftPress);
},
```

The onLeftButtonPress callback
```
handleLeftPress(callData) {
  if (this.renderer !== callData.pokedRenderer) {
    return;
  }

  const pos = callData.position;
  this.picker.setArea(pos.x, pos.y, 0, 0);

  const res = this.picker.select();
  console.log(res); // return empty array
}
```

I have added some actors in the render.

Any tips? Thank you some much

**Comment by jourdain** [comment]
I guess the test is not a good example of its usage.

In case you plan to do many lookup while not changing the camera, you can set the area to the full size like we do [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L186-L189) and then do the lookup like we do [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L340).

Then from the selection object you can extract the prop/actor like we do [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L361).
