### ISSUE TITLE
Does vti (vtkImageData) only support 1channel?

### ISSUE THREAD

**Issue by rjsgml5698** [Kitware/vtk-js#1198]
Hello.
I have something curious.

Does vti (vtkImageData) only support 1channel?

**Comment by jourdain** [comment]
No, you can have as many array (temperature, pressure, velocity) as you want and/or as many components (velocity(x,y,z)) as you want.

**Comment by rjsgml5698** [comment]
Thank you for your reply.

I want to stack pngs into vti. Can I store the rgb value of png in vti?

Thank you!

**Comment by jourdain** [comment]
Yes

**Comment by rjsgml5698** [comment]
Thank you
