### ISSUE TITLE
How to use ImageReslice.resliceTransform?

### ISSUE THREAD

**Issue by Josieee** [Kitware/vtk-js#1199]

**Comment by Josieee** [comment]
How to use both the resliceAxes and the resliceTransform at the same time? I can not find setResliceTransfrom in vtkImageReslice. I want to rotate, scale, and translate the imageReslice to a fixed position

**Comment by finetjul** [comment]
It should be the same way as in C++:
  https://vtk.org/doc/nightly/html/classvtkImageReslice.html#a1f0b56a40d5b335abe8712aa582583ec

**Comment by Josieee** [comment]
I want to show a cutting face at any angle in a cube. But the InteractorStyleMPRSlice is to use camera clipping planes to show only one plane, I want to show the specific position of this plane in the cube, so I want to use ImageReslice to get a slices from an image volume and move it to the position of the cut in the cube to show it. But now I don't know how to translate the imageReslice to the cut position

**Comment by finetjul** [comment]
In [C++](https://gitlab.kitware.com/vtk/vtk/blob/master/Imaging/Core/vtkImageReslice.cxx), there are some convenient methods (e.g. 
`SetResliceAxesOrigin`) to help you configure `resliceAxes`. Maybe you could add them in ImageReslice and make a pull request ?

`resliceTransform` has not been implemented yet. You can do so by looking at how it works in [C++](https://gitlab.kitware.com/vtk/vtk/blob/master/Imaging/Core/vtkImageReslice.cxx)

Hth

**Comment by Josieee** [comment]
Thanks
