### ISSUE TITLE
DepthPeeling support

### ISSUE THREAD

**Issue by Josieee** [Kitware/vtk-js#1202]
The API of vtkRenderer says the render window must have alpha bits (i.e., call SetAlphaBitPlanes(1)) and no multisample buffer (i.e. call SetMultiSamples(0)) to support depth peeling.
I can not find SetAlphaBitPlanes and SetMultiSamples in vtkRenderWindow

**Comment by Josieee** [comment]
Has the DepthPeeling been supported?

**Comment by jourdain** [comment]
Not yet

**Comment by Josieee** [comment]
Thank you for your reply
