### ISSUE TITLE
Best way to modify interaction event using mouse information?

### ISSUE THREAD

**Issue by EJShim** [Kitware/vtk-js#1208]
Hello

I want to modify trackballcamera interaction that will rotate specific vtkActor, not camera.

For that, firstly, I have to disable default event dispatching ,

and then, get information for actor rotation (pan, pitching, something like that..)

and apply them to actor.

What is the best way to do this?

I tried to get some mouse event information using interactor.onAnimation(e), interactorstyle.onInteractorStyleEvent(e), but none of them provided information I needed

**Comment by jourdain** [comment]
It seems that you want to create your interactor.

You can look at the [manipulator interactor](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Style/InteractorStyleManipulator/index.js) that intercept mouse events and then forward those events to custom handlers that will manipulate the camera. In your case, either create your manipulator that will affect the actor or just create a new interactor.

Then you can see its initialization and usage in this [example](https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html).
