### ISSUE TITLE
vtkCutter with geometry

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1214]
Hello,

I was wondering if the vtkCutter can be used with geometries.

I'm using the cdn of vtk.js and here is an example of what I'm doing

https://xavartley.github.io/panel/vtk_examples/dev_panel_vtkcutter.html

when cliking on cutter this is the code performed (I put a debbuger statement on purpose, one can stop the execution with dev tools open):
```javascript
(function anonymous(args,properties,source,target,cb_obj,cb_data,require,exports
) {

debugger

const renderer = target.renderer_el.getRenderer()
const renderWindow = target.renderer_el.getRenderWindow()

const vtkPlane = vtk.Common.DataModel.vtkPlane
const vtkCutter = vtk.Filters.Core.vtkCutter
const vtkMapper = vtk.Rendering.Core.vtkMapper
const vtkActor = vtk.Rendering.Core.vtkActor

if(source.active){
    
    if(!target.save_actor){
        target.save_actor = renderer.getActors()[0]
    }
    
    target.save_actor.getProperty().setOpacity(0)
    
    const plane = vtkPlane.newInstance()
    plane.setOrigin(150, 100, 20);
    plane.setNormal(0, 0, 1);
    const cutter = vtkCutter.newInstance()
    cutter.setCutFunction(plane)
    cutter.setInputData(target.save_actor.getMapper().getInputData())
    cutter.update()
    
    console.log('cutter points:', cutter.getOutputData().getPoints().getData())
    console.log('cutter cells:', cutter.getOutputData().getCells())
    console.log('cutter pointData Arrays :', cutter.getOutputData().getPointData().getArrays())
    
    const cutMapper = vtkMapper.newInstance()
    cutMapper.setInputData(cutter.getOutputData())
    const cutActor = vtkActor.newInstance()
    cutActor.getProperty().setLighting(false);
    cutActor.getProperty().setColor(0, 1, 0);
    cutActor.setMapper(cutMapper)
    target.save_cut_actor = cutActor
    renderer.addActor(cutActor)
    
}else{
    target.save_actor.getProperty().setOpacity(1)
    if(target.save_cut_actor){
        renderer.removeActor(target.save_cut_actor)
        target.save_cut_actor = null
    }
    
    
}
renderer.resetCamera()
renderWindow.render()
target.properties.camera.change.emit()
})
```

I'd like to get the poinData scalars associated to the cut represented inside the plane

For comparison this is the python of what I try to do
![image](https://user-images.githubusercontent.com/18531147/65323914-f0a85e00-dbaa-11e9-9c4c-71444a75c4d4.png)

**Comment by jourdain** [comment]
vtk.js is not currently supporting volumetric cells unless it is for volume rendering using vtkImageData which can also be sliced the way you want. In your case, you've extracted the surface of your dataset so you can render it inside vtk.js. But now that you only have the surface, cutting it will result with just lines.

A current way to enable data processing and rendering is to use VTK/ParaView Web for either doing the data processing and rendering or just the data processing.

We are hoping to offer at some point some WebAssembly component of VTK so it could be used along with vtk.js. But unfortunately we are not fully there yet.

**Comment by xavArtley** [comment]
As my geometry is an uniformgrid should it be possible to transform it in vtkVolume?
I tried something like this:
```javascript
target.save_actor.getProperty().setOpacity(0.1)
const actor_bounds = target.save_actor.getBounds()
const poly = target.save_actor.getMapper().getInputData()
    
    //Create image data from geometry
    
    
    const imageData = vtkImageData.newInstance();
    
    imageData.setExtent(actor_bounds[0], actor_bounds[1],
                        actor_bounds[2], actor_bounds[3],
                        actor_bounds[4], actor_bounds[5])
    
    imageData.setOrigin(actor_bounds[0],
                        actor_bounds[2],
                        actor_bounds[4])
    
    const da = vtkDataArray.newInstance({
      numberOfComponents: 1,
      values: poly.getPointData().getArray(0).getData(),
    });
da.setName('scalars')
imageData.getPointData().setScalars(da)
    
volumeActor = vtkVolume.newInstance()
volumeMapper = vtkVolumeMapper.newInstance()
    
volumeMapper.setInputData(imageData)
volumeActor.setMapper(volumeMapper)
```

but the position of the volume is wrong. I suppose I don't use correctly Extent and Origin
And the dataset as not the good colormap but I don't know how to apply the LookUpTable to the volume

**Comment by jourdain** [comment]
In your case, you will have to save a vti file, that way you will capture the scalars inside your volume.

Then you can use [this example](https://kitware.github.io/vtk-js/examples/ResliceCursor.html) to cut through your volume.

The extent is ijk based not xyz. You can also just set the dimensions of your volume which underneath will set the extent. Also, there is no way you can get the data from your polydata and put it in an image data since a polydata is just a surface mesh.

**Comment by xavArtley** [comment]
Ok it makes sense now.
