### ISSUE TITLE
Visualization precision issues with datasets that have 'large coordinates'

### ISSUE THREAD

**Issue by danmindru** [Kitware/vtk-js#1217]
Hi there,

When trying to visualize a vtp with value ranges from 6200475.180468361 to 6200562.503912979, I've noticed that the visualization does not accurately represent the data.

For example, the vtp (see attached zip) is rendered in the vtk.js GeometryViewer example as:
![vtkjs-geometry-viewer](https://user-images.githubusercontent.com/1515742/65590564-4a35d180-df8b-11e9-840f-57d1ac9b4d1a.png)

Paraview renders it similarly: 
![paraview](https://user-images.githubusercontent.com/1515742/65590605-5d48a180-df8b-11e9-9b18-ec1ec29ac58f.png)

However, by visualizing the same data in i.e. QGIS, one can see that the bottom border is not accurately represented in either vtk.js or Paraview:
![qgis](https://user-images.githubusercontent.com/1515742/65590706-85380500-df8b-11e9-84dd-78ee3188ed2c.png)

[Used Data.zip](https://github.com/Kitware/vtk-js/files/3651799/Data.zip)

Are there any ways to increase the accuracy of the visualization that come to mind?
Thanks for the help,
Dan

-------------------------

About the data:
The data represents geographical coordinates in a given projection. The precision is necessary because the data is sometimes shown on top of a map. Any transform to this coordinate with either misrepresent the geographical data or effectively reproject the data.

**Comment by jourdain** [comment]
Using ParaView 5.6 or 5.7, I can not reproduce the precision issue while I agree that on vtk.js the precision issue arises and you can see the geometry jumping around.

@martinken can we do similar things on vtk.js to properly handle double precision coordinates like it is done in VTK or ParaView without manually shifting the coordinates?

**Comment by martinken** [comment]
Yes we can

**Comment by martinken** [comment]
To be clear that is a "we could code the same technique", right now it isn't implemented though

**Comment by martinken** [comment]
Latest PV should handle those coordinates fine (as you are seeing Seb)

**Comment by danmindru** [comment]
Thanks for getting back so quickly. It sounds promising!
To clarify, would you prefer that this is pushed / funded by a customer?
(that's fine, just want to make sure that is the case 😊)

**Comment by danmindru** [comment]
Hi @boucaud @finetjul,
Upon updating to v11.9.0 seems to improve the original issue, however I'm seeing new scaling issues when visualizing i.e. 2+ actors that have shifted coordinates.

`Example #1`:
![comparison-between-v11-8-0-and-v11-9-0](https://user-images.githubusercontent.com/1515742/68682336-44a94080-0565-11ea-9968-3c62bb4f8109.png)

(zoomed)
![comparison-between-v11-8-0-and-v11-9-0-zoomed](https://user-images.githubusercontent.com/1515742/68682335-4410aa00-0565-11ea-991d-47c9fd39bed2.png)


It seems like there is a proportional relation between the issue and the difference in size between the actors. In the following example, you can see what I mean.

`Example #2`
![comparison-between-v11-8-0-and-v11-9-0-smaller-example](https://user-images.githubusercontent.com/1515742/68682522-8df99000-0565-11ea-9279-8100207977a4.png)

Again, rendering just one actor at a time does not present any problems. They seem to be scaled correctly / precisely. The problem occurs with 2+ actors.
I've also attached the input vtps.

I am not sure if the fix in #1251 will also take care of this, but it might.

Thanks for the good work,
Dan

[11.9.0 sample data.zip](https://github.com/Kitware/vtk-js/files/3836737/11.9.0.sample.data.zip)

**Comment by boucaud** [comment]
Hello @danmindru,
#1251 should indeed fix these scaling issues (the issue being that view matrices are not properly updated for multiple actors.

**Comment by danmindru** [comment]
thanks @boucaud, seems that you are one step ahead 👍 
Looking good then, let's keep this one closed.

All the best,
Dan
