### ISSUE TITLE
What is limit of the number of polygons in a polydata model ?

### ISSUE THREAD

**Issue by PBrockmann** [Kitware/vtk-js#1218]
I have encountered a problem when I refine resolution of the polydata model I create.
Beyond a 2^14 (16384) polygons, the polygons are not drawn.

Here is a simple test from https://jsfiddle.net/PBrockmann/e8hdfs40
Change resolution to 1 (dx = dy = 1;) you get a partial representation of the structure:

![image](https://user-images.githubusercontent.com/5402758/65707738-6f126d80-e08d-11e9-98a1-d8dd9f5bb800.png)
whereas you have it complete with a coarse resolution (dx = dy = 2;)

![image](https://user-images.githubusercontent.com/5402758/65707852-a08b3900-e08d-11e9-8e95-c1543e48a895.png)
 
My real code has pointed me the hard limit of 2^14.
Why such a limit ? Is there a way to increase it ?

Thks

**Comment by jourdain** [comment]
This is strange as I've loaded datasets with more than 5 millions cells. 

Maybe you are using WebGL1 and not WebGL2 that is available on a modern browser.
Editing the code in your example just work on my side using chrome.

**Comment by jourdain** [comment]
I bet the issue is related to the limit of JS using []. If you allocate the correct size of TypedArray, you will be good.

**Comment by PBrockmann** [comment]
Tested with google-chrome Version 75 and not working.

In my understanding and testing,
define array with "new Array(N) and fill without shortening" is the most efficient.

<pre>
var a = new Array(N);
for (var i = 0; i < N; ++i) {
 a[i] = "foo";
}
</pre>

from https://jsperf.com/preallocating-array/9

**Comment by jourdain** [comment]
Array or [] is the same thing and will have the same size limitation which is not true with Uint16Array or Float32Array.

**Comment by PBrockmann** [comment]
OK I will adapt my code to this recommendation.
Thanks

**Comment by PBrockmann** [comment]
I have now allocated all arrays as TypedArrays but the same limitation occurs

See
https://jsfiddle.net/PBrockmann/z0kvepmq/
adapted from https://jsfiddle.net/PBrockmann/e8hdfs40

**Comment by PBrockmann** [comment]
Any news on this issue... thks

**Comment by floryst** [comment]
Your polysArray is Uint16, so you're overflowing since your vertexArray has way more vertices than 2^16-1. You should be good using a Uint32Array.

**Comment by PBrockmann** [comment]
YES ! 
Of course, I would say. 
No error messages so not so easy to detect the overflowing. But logic.

Many thanks @floryst !

**Comment by PBrockmann** [comment]
Euhh..

No yet because I reach a new limitation with  `360*180*4*3 / dx` with dx = 0.5

![image](https://user-images.githubusercontent.com/5402758/65887535-5f04d180-e39e-11e9-915d-369b2ee2d873.png)

**Comment by jourdain** [comment]
Polys needs to be index, so they can not be floats.

**Comment by PBrockmann** [comment]
Ok that is what I have tried first.

![image](https://user-images.githubusercontent.com/5402758/65896503-a2b30780-e3ad-11e9-842a-d8dd20fcff17.png)

without success...

**Comment by aronhelser** [comment]
Take a look at BigUInt64Array - but you have to do some additional changes
so the values you feed it aren't just ints....

**Comment by jourdain** [comment]
BigUInt64Array is not the way to go.

**Comment by PBrockmann** [comment]
With the `var polysArray = new Uint16Array(360*180*5 / dx);`
I can define 2^32-1 items so larger than `360*180*5 / dx` when dx = 0.5
But only half of the globe is displayed...

**Comment by floryst** [comment]
I played with your example, and it looks like you're not allocating enough space for your vertices, since you're not getting enough vertices to cover your entire sphere. Typed arrays will silently fail if you try to assign out-of-bounds, so when your code keeps setting vertices beyond the vertexArray length, nothing will complain.

**Comment by PBrockmann** [comment]
@floryst: Really, I would be curious to see this because from my test increasing `vertexArray = new Float64Array(360*180*4*3*40);` for example has no repercussion.

**Comment by floryst** [comment]
Oh I haven't tried seeing the polys. I just converted your example to just show vertices, and saw that your vertices only covered half of the sphere. I'll check it out later.

**Comment by PBrockmann** [comment]
Let me know, I hope not to have made a stupid error.

**Comment by floryst** [comment]
Ah, you need to bump up all of the array sizes: vertex, polys, and values array.

**Comment by PBrockmann** [comment]
Gloups... Yes indeed !

I think this issue can be closed now. Definition from typed arrays was a the thing to do.
Many thank to both of you for having inspected my test code and help me.

![image](https://user-images.githubusercontent.com/5402758/65998867-7de98d80-e49c-11e9-8a5a-161933edb68a.png)
