### ISSUE TITLE
CellArrayBufferObject with point data in 2D

### ISSUE THREAD

**Issue by panquez** [Kitware/vtk-js#1221]
I try to show 2D PolyData in a 3D camera. The result is wrong: the points are not located on a plane. 

In CellArrayBufferObject, the number of components of point data is never used: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/CellArrayBufferObject/index.js#L34

Should I give a 3D PolyData or can the CABO handle 2D points?

cc @BotellaA

**Comment by panquez** [comment]
@martinken Any news on this point?

**Comment by martinken** [comment]
Polydata assumes 3 coordinates for points in a few places probably, You would need to add a dummy z value for each point I believe.
