### ISSUE TITLE
Support for <Array> & <Array type="string"> in XMLReader 

### ISSUE THREAD

**Issue by danmindru** [Kitware/vtk-js#1229]
Hi there,

Working with the attached data, I've noticed that:
1. `<Array>` under `<CellData>` is not being processed ([only `<DataArray>`  is](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/XML/XMLReader/index.js#L228))
I wonder why? 
It might also be a lack of knowledge of the format on my end, but it seems like both should be supported.

2. Even if `<Array>` was processed, the `string` type would [not be supported](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/XML/XMLReader/index.js#L31).  
Is that deliberate? 

Again, it might be a hole in my knowledge regarding the format. Perhaps there is another mechanism to read `<Array type="String">` that I am not aware of. 

Do you have any hints / suggestions?
Thanks for the help,
Dan

[example-vtp.zip](https://github.com/Kitware/vtk-js/files/3733520/string-array.zip)

**Comment by danmindru** [comment]
No worries :)
Numerical data display is more common in most cases I suppose, so that makes sense.

Do you have any plans to support string arrays in the near future?
Thanks,
Dan

**Comment by jourdain** [comment]
We sure want to support them. But only when we will need them that we will put the effort to integrate them. This could come from a customer request unless it get contributed by someone from the community. As of today, I don't have anyone (except you) that requested it. ;-)

**Comment by danmindru** [comment]
Absolutely.
As it is, it's not the most important thing on my list, so I'm on the same page. If it becomes more important, we'd be happy to contribute one way or another :)

**Comment by aminechir** [comment]
Hi,

I am facing the same problem for reading a vtp file containing a String Array in the <CellData> section.  How did you resolve your problem temporarly @danmindru  ?

In my case , I have just some few words to assign to each cell, So I can use a integer array for the cells and add a field data which gives the association between the id and the string I wanted to assign

**Comment by jourdain** [comment]
The latest version of Glance and vtk.js does properly skip the string arrays.

**Comment by aminechir** [comment]
Okay I will try this,
Thanks

**Comment by devngc** [comment]
HI @jourdain,
Has there been any update on this? I am too interested in loading string-based arrays in Paraview Glance.

**Comment by floryst** [comment]
This is available in v28.3.0 (https://github.com/Kitware/vtk-js/pull/2864).
