### ISSUE TITLE
Parallel Projection is still incorrect for the VolumeMapper.

### ISSUE THREAD

**Issue by JamesAPetts** [Kitware/vtk-js#1233]
So in #1230 we fixed the vertex shader bounds of the VolumeMapper so that _something_ is rendered in parallel projection. It looked different so we were happy, but we weren't looking at a reasonable dataset to properly check the result.

The fragment shader for parallel projection is likely broken, I've tested this by sticking a slab(cube) on top of the volume:

<img width="725" alt="Screenshot 2019-10-24 at 12 00 05" src="https://user-images.githubusercontent.com/25818497/67479879-eb7d7980-f656-11e9-8b40-cfb063f5c1d6.png">
<img width="631" alt="Screenshot 2019-10-24 at 12 00 22" src="https://user-images.githubusercontent.com/25818497/67479900-ef110080-f656-11e9-940b-59521c4d60c1.png">

The volume rendered with the volume mapper becomes skewed and jumps away from the cube.

More context here, by comparing a 1% FOV perspective camera to the "parallel projection": https://github.com/OHIF/react-vtkjs-viewport/issues/66

I'll try and look into this, but any insight would be greatly appreciated.

**Comment by JamesAPetts** [comment]
Fixed in #1234 .

**Comment by mix3d** [comment]
dont forget to close this now that the fix has been merged
