### ISSUE TITLE
Rendering cellData

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1250]
This might be a very simple question but I cannot find how to do it..

I have a ProxyManager with a PolyData. I also have a Float32Array (going from 0 to 1500) of size the number of polygons in the PolyData. I tried to add my arry using `getCellData().setScalars(data);` or `getCellData().addArray(data);` and then setting the `setColorModeToMapScalars()` to the Mapper but I does not seems to be enough.

What are the right steps to do to display an array on the polygons?

Thanks a lot for your help

**Comment by jourdain** [comment]
If you use the ProxyManager, you should use a Representation. If so, calling `repInstance. setColorBy(arrayName, 'cellData')`

**Comment by BotellaA** [comment]
Thanks for your quick answer. I tried this method but still have a dark image.
![Capture d’écran de 2019-11-07 11-48-53](https://user-images.githubusercontent.com/3213882/68382735-9b251200-0154-11ea-9f3c-949cd0709922.png)

Here is the code:
```
 const data = vtkDataArray.newInstance({ name: value, numberOfComponents: 1, values: scalars });
 polyData.getCellData().addArray(data);
 proxyManager
     .getRepresentations()
     .filter(r => r.getInput() === this.item.source)
     .forEach(r => {
          r.setColorBy(value, 'cellData');
      });
```
The range of the lookupTable is ok (from 0 to 1449). I did not set a custom lookupTable.

**Comment by BotellaA** [comment]
@jourdain I am progressing in the debug.

I had a bad default ColorMap preset that came from a dummy copy of paraview-glance config. Changing this give me this picture.
![Capture d’écran de 2019-11-12 11-08-39](https://user-images.githubusercontent.com/3213882/68662993-3136af00-053e-11ea-84ce-4824d364af10.png)

This shift in the color display come from the computation of the [`colorIdx`](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/CellArrayBufferObject/index.js#L317) and the `options.cellOffset`. This offset is equal to the number of vertices + number line vertices (according https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/PolyDataMapper/index.js#L1879).

What I do not understand is why I have to give an array of size vertices + polys here
```
polyData.getCellData().addArray(data);
```
What is the expected size of `data`? I would like to only give polygon values.

**Comment by jourdain** [comment]
The expected size is the number of cells that you have. If you just defined just the polys, that should just be the number of polys.

**Comment by BotellaA** [comment]
Ok, thanks for your answer.
