### ISSUE TITLE
vtkImageReslice class do not have setBackgroundLeveal api?

### ISSUE THREAD

**Issue by RexingRui** [Kitware/vtk-js#1258]
Hi!
We are working on mpr render. When I want use imageReslice.setBackgroundLeveal(-1024), there was a error that says imageReslice.setBackgroundLevel is not a function. Then I read the source code and it   does not have this api.  
In thet future,  Can vtk.js provide this api

**Comment by finetjul** [comment]
Hi @RexingRui , only setBackgroundColor has been implemented. 

However contributions are welcomed :-) 
Feel free to look at how it is done in C++ and do the same in JS.

**Comment by RexingRui** [comment]
Hi @finetjul 
Thanks
