### ISSUE TITLE
ColorMaps with sparse data

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1261]
I have a data array attach to the PolyData cells. However, these data are sparsed, I mean some of the cells do not have data. Currently I set this "no data value" to a given constant.

I would like to render this data without taking into account the "no data" constant. Do you thing this rendering could be possible?

**Comment by jourdain** [comment]
You can either threshold your dataset to remove cells with that magic value or assign a specific color to it.

**Comment by BotellaA** [comment]
Very interesting! How to do these two choices?

1. The thresholding should be done while setting the data array or later?

1. How to assign a color to that value while still using the ColorMap at the right range?

**Comment by jourdain** [comment]
1. That will be later via a filter
2. You can use NaN or a number outside of the color range.

**Comment by BotellaA** [comment]
Thanks!
