### ISSUE TITLE
How to load metaimage file from Slicer in vtk.js?

### ISSUE THREAD

**Issue by tmxklzp** [Kitware/vtk-js#1267]
In Python, I could read metaimage file(.mha) from a medical software Slicer via **vtkMetaImageReader**. while I want to load this file in Javascript, I can't find an implemented reader API to load this .mha file from my server. I tried **XMLImageDataReader**, **vtkITKImageReader** and so on.

Is there any existing reader API that I can use to load the .mha file? Otherwise is there any parser that transform the data below(read from uncompress .mha file) to a volume object? Or I must implement this parser by myself? 
![image](https://user-images.githubusercontent.com/20590535/70026111-e0b0ef80-15d9-11ea-82bf-60443c48cf1e.png)

**Comment by tmxklzp** [comment]
I used **vtkJSONImageWriter** in Python to transform this .mha file to JSON, such as below:
![image](https://user-images.githubusercontent.com/20590535/70029885-07bfef00-15e3-11ea-9129-7454a35caecd.png)

But when I tried **vtkHttpDataSetReader** to load this JSON file, it also failed:
![image](https://user-images.githubusercontent.com/20590535/70030160-946aad00-15e3-11ea-9215-73bc6a80a42c.png)

So how should I load this JSON file to vtk.js as a volume?

**Comment by jourdain** [comment]
itk-js can load your mha file like we do with [ParaView Glance](https://kitware.github.io/paraview-glance/).

For the JSON one, you can write your own reader with something like that.

```
const jsonData = ...;
const dataset = vtkImageData.newInstance();
dataset.setOrigin(jsonData.origin);
dataset.setSpacing(jsonData.spacing);
dataset.getPointData().setScalars(vtkDataArray.newInstance({
   name: 'scalars',
   values: Float32Array.from(jsonData.MetaImage),
}));
```

Float32Array should be replaced by the actual data type Uint16Array or else...

**Comment by jourdain** [comment]
@thewtex @floryst

**Comment by tmxklzp** [comment]
@jourdain thanks! I'll try it later.

**Comment by jourdain** [comment]
vti could be a better format if you are looking for a native and size efficient format. (Appended + Zlib)

**Comment by tmxklzp** [comment]
@jourdain Yeah I think vti would be better, how can I convert my mha file to vti file?


And I tried your code above that feed the json data to vtkImageData instance and set this image data to volume mapper. The code didn't report error, but the window rendered nothing and 
 got WebGL warning that the texture bound is non-power-of-2.
![image](https://user-images.githubusercontent.com/20590535/70057184-acf4ba80-1617-11ea-9802-d66e018ef5e5.png)

My code:
![image](https://user-images.githubusercontent.com/20590535/70057302-de6d8600-1617-11ea-8a8d-794d678d888f.png)

**Comment by jourdain** [comment]
You are missing the dimensions.

**Comment by jourdain** [comment]
I think you can use ParaView to load and convert your file. Or if you are in vtk, just use vtkXMLImageDataWriter.

**Comment by tmxklzp** [comment]
@jourdain Yes I add the line:
`img.setDimensions(jsonData.dimensions)`
And it works! Thank you very much!!!

And in later, I'll try ParaView and vtkXMLImageDataWriter to convert my file to vti. Really appreciate your help!

**Comment by jourdain** [comment]
Based on your mha header file, I think you can use Uint8Array.

**Comment by tmxklzp** [comment]
@jourdain  Yes I think so. Thanks for your reminding me.

**Comment by thewtex** [comment]
To support more automated MetaImage conversion, e.g. compressed MetaImage files, itk.js and vtk.js could be of use -- the relevant examples / docs are:

- https://glitch.com/~itk-js-umd-example
- [convertItkToVtkImage](https://kitware.github.io/vtk-js/api/Common_DataModel_ITKHelper.html)
