### ISSUE TITLE
Why doesn't the manipulator's onMouseUp have position?

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1269]
Looking at the `vtkInteractorStyleManipulator` and associated mouse manipulators, why was the API designed to not have position for MouseUp? JS events for mouseUp do have position.

This seems like an oversight, but fortunately one that would result in only a minor revision change since the API for manipulators is `publicAPI.onButtonUp = (interactor) => {};`, leaving space for 2 more params, renderer and position.

Additionally, the old API documentation at compositeCamera manipulator, (which really should be compositeMouse manipulator), says it should be `onButtonUp(eventX, eventY, vtkRenderer, vtkRenderWindowInteractor)`, which references what I'm assuming an API prior to refactoring to a position object.

**Comment by jourdain** [comment]
Probably because the `move` and `down` give it so if you need it, you can capture those info.

**Comment by jourdain** [comment]
Also the up could be outside of the RenderWindow.

**Comment by jourdain** [comment]
Anyhow, we can surely add the same args as the one we provide for any mouse manipulator especially if we have them. `.onMouseXXX(model.interactor, callData.pokedRenderer, callData.position)`

**Comment by mix3d** [comment]
So TLDR; no REAL reason, and you'd accept a PR to add them in?

**Comment by jourdain** [comment]
yes ;-)
