### ISSUE TITLE
Live example datasets fail to load

### ISSUE THREAD

**Issue by jcfr** [Kitware/vtk-js#1270]
On page like this one: https://kitware.github.io/vtk-js/examples/OBJViewer.html#OBJ-Viewer

Clicking on any of these links:

![image](https://user-images.githubusercontent.com/219043/70173289-8890f080-16a0-11ea-9ea9-2f93de818d92.png)

Report error like the following:

![image](https://user-images.githubusercontent.com/219043/70173266-7e6ef200-16a0-11ea-8b67-aecc48702bfc.png)

This was observed using Firefox 70.0.1 (64-bit)

**Comment by floryst** [comment]
I clicked on Ferrari and it loaded for me on Firefox. Might have been a transient network-related issue?

**Comment by jcfr** [comment]
It turns out that the issue was caused by the PrivacyBadger extension:

![image](https://user-images.githubusercontent.com/219043/70243824-597e8b80-1741-11ea-8f15-eec06907e83d.png)
