### ISSUE TITLE
Should I use ResliceCursorWidget or vtkImageMapper?

### ISSUE THREAD

**Issue by hubtub2** [Kitware/vtk-js#1276]
I am trying to create a MPR view of a CT Volume with the capability to add a 2D-Rectangle-Widget in each view.

I found two examples that are close:
- ResliceCursor Example: using vtkResliceCursorWidget 
- PaintWidget Example: using vtkImageMapper

Which method of display is easiest to combine with a rectangleWidget?

The widet should:
- be draggable and should 
- appear/dissappear while scrolling throught the slices
- be visible in all three views/renderers

Note: I do not need the arbitrary slicing of vtkResliceCursorWidget, axial, coronal and sagittal is enough.

**Comment by finetjul** [comment]
The reslice cursor widget is a bit complicated, so if you do not need the arbitrary slicing you can use simply vtkImageMapper.
