### ISSUE TITLE
vtkWidgetmanager blocks mouse input to multiple renderes

### ISSUE THREAD

**Issue by hubtub2** [Kitware/vtk-js#1277]
I am adding just the following lines to the ResliceCursor example:
```
import vtkWidgetManager from 'vtk.js/Sources/Widgets/Core/WidgetManager';
let widgetManager = vtkWidgetManager.newInstance();
widgetManager.setRenderer(renderers[0]);   
```
Now, mouse input from the whole browser window is routed to the first render window
, the other two render windows do not react anymore.

Is there anything I have to do to make the WidgetManager works with multiple render windows, or is this a bug?

**Comment by jourdain** [comment]
Widget Manager definitely works with multiple render windows. My guess is that you are not using it right. Could you provide more context? I don't even see one renderWindow in your code.

**Comment by hubtub2** [comment]
Hi, 

to reproduce this, use the unmodified ResliceCursor-Example (https://kitware.github.io/vtk-js/examples/ResliceCursor.html).

Add the following two lines after the for-loops that creates the renderers:
```
let widgetManager = vtkWidgetManager.newInstance();
widgetManager.setRenderer(renderers[0]);   
```

> Widget Manager definitely works with multiple render windows. 
There is no example in the official examples of vtk.js ...

**Comment by jourdain** [comment]
ParaViewGlance which use vtk.js make use of the WidgetManager across several views.  
But I'm not saying that ResliceCursor works with the WidgetManager as I don't know what is done inside ResliceCursor. @floryst and @finetjul  may have some idea.

**Comment by hubtub2** [comment]
Note: I found the same behaviour after I converted the PaintWidget-Example 
( https://kitware.github.io/vtk-js/examples/PaintWidget.html ) from vtkFullScreenRenderWindow to vtkRenderWindow/vtkOpenGLRenderWindow and setting a <div> tag as container:
The whole website does not accept mouse input anymore...

**Comment by floryst** [comment]
This is an issue with the SVG layer being too large . I'll take a look.
