### ISSUE TITLE
Does setUrl of STLReader only support local host url?

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1282]
I am trying to load stl files from anther server. I was wondering the method setUrl should be working.
However, I found when I pass the url, it always result in adding localhost address before my passing url.

For example, if I pass www.MyDomain.net/test.stl to setUrl, the the argument resulted in **"http://localhost:8081/www.MyDomain.net/test.stl"** 

How can I set the correct url, or it only support local host url?

**Comment by jourdain** [comment]
Did you provided `http://www.MyDomain.net/test.stl` or just `www.MyDomain.net/test.stl`?

**Comment by lihouxing-sjtu** [comment]
Thanks, that's my mistake. After add the http protocol, I succeded to emit the GET request , But I got another error below,
**

> Failed to load http://www.MyDomain.net/test.stl: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.

**
 I guess this might not be the problem of vtk.js ........... but what should I do to get it work?

> Did you provid `http://www.MyDomain.net/test.stl` or just `www.MyDomain.net/test.stl`?
> 
> Not providing a protocol then would assume the same host...

**Comment by jourdain** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
