### ISSUE TITLE
how can I load the VTK model file？

### ISSUE THREAD

**Issue by JerryGit1** [Kitware/vtk-js#1283]
Hi, can I load the VTK suffix model file?
For example:
liver.vtk

**Comment by jourdain** [comment]
Itk.js has the full support of the legacy format, but inside vtk.js in plain JS, we only support (currently) vtkPolyData in ASCII format without any data field. 

vtp would be a preferred format.

**Comment by JerryGit1** [comment]
> Itk.js完全支持传统格式，但是在纯JS的vtk.js内部，我们（当前）仅支持ASCII格式的vtkPolyData，而没有任何数据字段。
> 
> vtp将是首选格式。

VTK文件Thank you for your reply. I just read other examples：

https://kitware.github.io/vtk-js/examples/PolyDataReader/PolyDataReader.html
It can load VTK files

Thank you
