### ISSUE TITLE
MatrixBuilder.rotateFromDirections() returns a 0 matrix in one scenario

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1286]
I think the math is wrong for this one scenario:

```
transform = vtkMatrixBuilder
	.buildFromDegree()
	.identity()
	.rotateFromDirections([-1, 0, 0], [1, 0, 0])
```
returns a matrix filled with 0's
I would expect the transform to flip points along the x axis (or maybe mirror?), but that's not happening.

**Comment by mix3d** [comment]
One possible solution to guarantee a perpendicular vector to rotate around would be to do something like the following:

```JS
const eulerUnits = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
for (let i = 0; vec3.length(tmp) < EPSILON; i++) {
	vec3.cross(tmp, src, eulerUnits[i])
}
```
Since it's guaranteed the source vector won't be parallel to all 3.

**Comment by floryst** [comment]
Yup, we only need to check two axes when picking a perpendicular vector.
