### ISSUE TITLE
Add PolyData clipping plane from widget 

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1287]
I would like to add a widget to control a clipping plane on a PolyData.
I can see my plane and update the clipping plane in the mapper but the PolyData is not clipped in the camera.

```
    clipper = vtkImplicitPlaneWidget.newInstance();
    clipper.getWidgetState().setNormal(0, 0, 1);
    clipper.placeWidget([-1,1,-1,1,-1,1]); // these bounds are ok for my test
    clipper.setPlaceFactor(3);
    const widgetManager = view.getReferenceByName("widgetManager");
    widgetManager.addWidget(clipper);
    widgetManager.enablePicking();
    clipper.onWidgetChange((state) =>{
        proxyManager
          .getRepresentations()
          .forEach(r => {
            const mapper = r.getMapper()
    mapper.removeAllClippingPlanes();
    mapper.addClippingPlane(vtkPlane.newInstance({origin: state.getOrigin(), normal: state.getNormal()}));
            console.log("mapper", mapper.getNumberOfClippingPlanes())
            console.log("mapper", mapper.getClippingPlanes()[0].getNormal())
          }) ;
   }) ;
```

What did I miss? 
Thanks for your help

**Comment by BotellaA** [comment]
Just forgot to call `mapper.modified()`... :man_facepalming:

**Comment by erentrk01** [comment]
@BotellaA   Can you share your repo,please ?  We have been trying to clipping polydata with Implicit Plane Widget. But it gives us an error because of get interactor s null value. maybe there might be problem in our code mapper.setInputConnection(reader.getOutputPort())
