### ISSUE TITLE
Same reference when getting points from two differents vtkPoints

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#129]
Hello,

I'm using two differents vtkPoints and I had to get points one by one from each. But when I get the point i on the first vtkPoints and then get a point on the second vtkPoints, then my first getting point has the same values as the second one. But the two vtkPoints are two differents objects.
For example :
data1 contains point (0, 0, 0)
data 2 contains point (1, 1, 1)

let p1 = data1.getPoint(0);
console.log(p1) will display (0, 0, 0)
let p2 = data2.getPoint(0);
console.log(p2) will display (1, 1, 1)
console.log(p1) will display (1, 1, 1)

The trick to do this is to make a deep copy of the output of getPoint() function but it's heavy.
Am I doing anything wrong or is it a bug ?

**Comment by jourdain** [comment]
That is the expected behavior. The getPoint(idx) is only provided as a helper and we do not allocate new memory for each point coordinate, we reuse the same holder. We could put that holder within the instance instead of the module.

**Comment by laurennlam** [comment]
Thanks for the explanation. 
I think it's confusing to have this behavior inside the module. I spent much time to understand what happens...
For me it's not intuitive because I'm thinking like in VTK, but I'm a beginner on javascript so maybe it's a normal behaviour.

**Comment by jourdain** [comment]
I didn't wanted to implement a getPoint(idx) initially as he lead to bad memory management.
I wanted to force users to use the native API on arrays.

But we made it so you could provide the tuple container.

So in you could write your code like that:

const p1 = [0,0,0];
const p2 = [0,0,0];

data1.getPoint(0, p1);
data2.getPoint(0, p2);

**Comment by jourdain** [comment]
Like in VTK

**Comment by laurennlam** [comment]
Yes, thanks a lot @jourdain !
