### ISSUE TITLE
v13 Initialize error: Uncaught TypeError: Cannot read property 'blendFuncSeparate' of null

### ISSUE THREAD

**Issue by euandekock** [Kitware/vtk-js#1292]
The v13 release of vtk.js is failing on my application.

During startup I get the following error:

```
index.js:127 Uncaught TypeError: Cannot read property 'blendFuncSeparate' of null
    at Object.e.initialize (index.js:127)
    at e.buildPass (index.js:112)
    at Object.e.apply (index.js:44)
    at Object.e.traverse (index.js:32)
    at Object.e.traverse (index.js:25)
    at Object.e.traverseAllPasses (index.js:1046)
    at l (index.js:331)
    at Object.e.render (index.js:718)
    at Object.e.initialize (index.js:129)
    at index.js:35
```

Looking at the code this appears to be occurring here:
```

  publicAPI.initialize = () => {
    if (!model.initialized) {
      model.context = publicAPI.get3DContext();
      model.textureUnitManager = vtkOpenGLTextureUnitManager.newInstance();
      model.textureUnitManager.setContext(model.context);
      model.shaderCache.setContext(model.context);
      // initialize blending for transparency
      const gl = model.context;
----->  gl.blendFuncSeparate(
        gl.SRC_ALPHA,
        gl.ONE_MINUS_SRC_ALPHA,
        gl.ONE,
        gl.ONE_MINUS_SRC_ALPHA
      );
      gl.depthFunc(gl.LEQUAL);
      gl.enable(gl.BLEND);
      model.initialized = true;
    }
  };
```
My code appears to work fine with v12 and earlier.

I am running the code on Linux/Chrome
Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by jourdain** [comment]
Are you using an eGPU? I've ran into this before when my browser was initialized with a wring gpu. Restarting the browser tend to solve the issue.

Are the live examples online failing as well for you?

**Comment by euandekock** [comment]
Hi Jourdain,

I am not using any GPU's, just running on a basic laptop. The online examples seem to work OK, I'll dig deeper and see if I can isolate where/when it's failing.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.

When running into those kind of errors, it was usually related to my browser being unable to create GL context.
