### ISSUE TITLE
Wrong Widget bounding box computation

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1296]
According https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/StateBuilder/boundsMixin.js#L19 and https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/StateBuilder/boundsMixin.js#L31,   `bounds` are multiplied by `placeFactor`. 

This is true only when the bounding box center is at the origin (0, 0, 0).

**Comment by jourdain** [comment]
Oups... ;-)

**Comment by floryst** [comment]
Let me know if that works for you, @BotellaA.
