### ISSUE TITLE
How I can merge imageData objects?

### ISSUE THREAD

**Issue by aneeshikmat** [Kitware/vtk-js#1309]
Hello,

I Have an imageData1, imageData2, imageData3 which its generated from `vtkITKHelper.convertItkToVtkImage`, these imageData contains a series of  dicom image, but every one of them has different count of image, for example imageData1 have dicom from 0 to 10, and imageData2 from 11 to 50, imageData3 from 51 to 200....

now how I can merge these data to be in a new vtkImageData instance(imageData4) to can be assign it to imageMapper?

**Comment by floryst** [comment]
Right now vtk.js does not have anything similar to [vtkImageAppend](https://vtk.org/doc/nightly/html/classvtkImageAppend.html), but shouldn't be too difficult to write. For your case, you should be able to create an imagedata with the final size, and then combine the data arrays from your smaller image data objects.

**Comment by aneeshikmat** [comment]
Thank you @floryst
