### ISSUE TITLE
why after using HardwareSelector the render window results in black background

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1311]
I am trying to pick actors while mouse moving, and hardWareSelector works fine only that the render window's background turns out to be black after the select.

I go through the source code of hardWareSelector and find the block blow:
`
/ Initialize renderer for selection.
    // change the renderer's background to black, which will indicate a miss
    model.originalBackground = model.renderer.getBackgroundByReference();
    model.renderer.setBackground(0.0, 0.0, 0.0);
`
but I don't know why it doesn't restore the original backGround color.
Here is my code block :
     `
 if (hardwareSelector.captureBuffers()) {
             hardwareSelector.generateSelection(pos.x,
                pos.y,
                pos.x,
                pos.y);
            hardwareSelector.releasePixBuffers();
        }
`

**Comment by jourdain** [comment]
How do you setup your background color on the view?

**Comment by lihouxing-sjtu** [comment]
Hi，thanks for your reply. I solved the problem by call renderwindow.render() after generateSelection.
Is it possible to call render() by hardwareSelector? I think it would be more convinient
