### ISSUE TITLE
Angular 8 + vtk.js

### ISSUE THREAD

**Issue by aminechir** [Kitware/vtk-js#1313]
Hi,

I am using vtkjs in Angular web projects. 

In the old versions of Angular, we had access to the webpack.config.js file to edit it and I could then add the rules of vtk.js.

The problem is that in the latest versions, Angular encapsulates webpack in its code (through the angular.json file) and it is now very difficult to edit the webpack of an Angular project.

So I can't do npm install vtk.js.

For the moment to work around the problem, I import the vtk.js library precompiled in app.module.ts. Thus, I can't use 'import ... from vtk.js ...' and I have to update the vtk.js versions by downloading the new release each time

Have people here already been confronted with this problem?
Thanks

**Comment by dannyrb** [comment]
I was under the impression that this was an issue with Angular 7, but not Angular 8. Are you able to use [angular-builders](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)?

**Comment by aminechir** [comment]
I will try later with the new version of the angular builders.

**Comment by doczoidberg** [comment]
@aminechir did you have succes? what did you do?

**Comment by aminechir** [comment]
Hi,

With the new approach for using vtk.js, with @kitware/vtk.js, we can easily use vtk.js into an angular app. I can close this issue 

Thanks you
