### ISSUE TITLE
How to load remote .vtp files including unstructured grid? 

### ISSUE THREAD

**Issue by khasanovsm** [Kitware/vtk-js#1315]
Hello! 

I am totally new to vtk.js and web visualisation, so my question could be really basic to figure out.

I have this file to visualise: https://github.com/BinWang0213/PyGRDECL/blob/master/Results/dome.vtp

It consists of geometry description as well as other data arrays such as  DataArray type="Float32" Name="PORO" format="appended" RangeMin="0.10163647681". How do I load this into js via vtk.js?

**Comment by jourdain** [comment]
That [example](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) allow you to load your file.

Here is a [link](https://kitware.github.io/vtk-js/examples/GeometryViewer/GeometryViewer.html?fileURL=https://raw.githubusercontent.com/BinWang0213/PyGRDECL/master/Results/dome.vtp) that use this example with your data.
