### ISSUE TITLE
Is there any function like Three.group() in vtkJs?

### ISSUE THREAD

**Issue by buptwny** [Kitware/vtk-js#1318]
I want to define a group to restore something in order to control the assemble show, In threejs, I can use THREE().group(), so how to do that in vtkjs?
Thanks a lot!

**Comment by jourdain** [comment]
We don't have a class that does that per-say, but depending what you are looking for, you can either implement it simply (extend vtkProp with only an addActor method) or you can create functions that could help you out.

**Comment by buptwny** [comment]
> We don't have a class that does that per-say, but depending what you are looking for, you can either implement it simply (extend vtkProp with only an addActor method) or you can create functions that could help you out.

Thank you ! Now I just push the actors to an array, also works.
