### ISSUE TITLE
Is there a vtkPropAssembly class we can use in vtkjs?

### ISSUE THREAD

**Issue by buptwny** [Kitware/vtk-js#1319]
I found that In vtk c++，we can use vtkPropAssembly to build a view container to restore vtkProp3D vtkActor,vtkAssembly and so on.Then we can use renderer.addProp to add props. But in vtkjs I can't find that, How can I get a assembly like that in vtkjs, before this I extended vtkProp to do that, add a addActor function, but that dosen't work.I feel it's a little difficult for me.
Thanks a lot!!

**Comment by jourdain** [comment]
Can you share your implementation? Because that is the way to go...

**Comment by buptwny** [comment]
> Can you share your implementation? Because that is the way to go...

I define a vtkAssembly in the dir "vtk.js/Sources/Rendering/Core/Assembly", extend vtkProp:
![image](https://user-images.githubusercontent.com/19993890/72721009-0f991a00-3bb6-11ea-8802-4cb0ec5dd190.png)
![image](https://user-images.githubusercontent.com/19993890/72721156-5be45a00-3bb6-11ea-9296-69df06030ca4.png)
Then, If I have something to add to the assembly, I use assembly.addProp(), even the prop is another assembly. Finally, when it's time to render, I can use a recursion to get every actor in the assembly, then use renderer.addAcotr() to render:
![image](https://user-images.githubusercontent.com/19993890/72721381-de6d1980-3bb6-11ea-882d-98831c804b89.png) 
Although It works,But my target is to use renderer.addViewProp(assembly) to render the assembly.I want the assembly just like an actor, a view element, the renderer can add it directly to render. 
Thanks for your timely reply!!

**Comment by jourdain** [comment]
Indeed that's not what I was suggesting and like you said it is bad design. I'll try to find the time to write you what I meant which would follow that usage:

```
const assembly = vtkAssembly.newInstance();
assembly.addActor(actor1);
assembly.addActor(actor2);
assembly.addActor(actor3);

renderer.addActor(assembly);
```

**Comment by jourdain** [comment]
That's what I was thinking.

```
function vtkAssembly(publicAPI, model) {
  model.classHierarchy.push('vtkAssembly');
  model.actors = [];

  publicAPI.getNestedProps = () => {
    return model.actors;
  };

  publicAPI.addActor = (a) => {
    model.actors.push(a);
  };
}

export function extend(publicAPI, model, initialValues = {}) {
  Object.assign(model, initialValues);
  vtkProp3D.extend(publicAPI, model, initialValues);
  vtkAssembly(publicAPI, model);
}

// ----------------------------------------------------------------------------

export const newInstance = macro.newInstance(extend, 'vtkAssembly');

// ----------------------------------------------------------------------------

export default { newInstance, extend };
```

**Comment by buptwny** [comment]
> That's what I was thinking.
> 
> ```
> function vtkAssembly(publicAPI, model) {
>   model.classHierarchy.push('vtkAssembly');
>   model.actors = [];
> 
>   publicAPI.getNestedProps = () => {
>     return model.actors;
>   };
> 
>   publicAPI.addActor = (a) => {
>     model.actors.push(a);
>   };
> }
> 
> export function extend(publicAPI, model, initialValues = {}) {
>   Object.assign(model, initialValues);
>   vtkProp3D.extend(publicAPI, model, initialValues);
>   vtkAssembly(publicAPI, model);
> }
> 
> // ----------------------------------------------------------------------------
> 
> export const newInstance = macro.newInstance(extend, 'vtkAssembly');
> 
> // ----------------------------------------------------------------------------
> 
> export default { newInstance, extend };
> ```

wow！It's  awesome， I have tried that, perfectly works, thanks so much, I will try  to figure out how it works detail, thank you very much ! very appriciate!!

**Comment by sedghi** [comment]
I'm interested in combining AnnotationCubeActor and Axes Actor together; I following the code in the [vtk examples website](https://lorensen.github.io/VTKExamples/site/Python/VisualizationAlgorithms/AnatomicalOrientation/) which uses `vtk.vtkPropAssembly()`, but instead based on the above discussion I'm using the proposed implementation of vtkAssembly

```
function makeAxesActor() {
    const axes = vtkAxesActor.newInstance();
    return axes
}

function makeAnnotatedCubeActor() {
    const cube = vtkAnnotatedCubeActor.newInstance();
    cube.setDefaultStyle({
        text: '+X',
        fontStyle: 'bold',
        fontFamily: 'Arial',
        fontColor: 'black',
        fontSizeScale: (res) => res / 2,
        faceColor: '#0000ff',
        faceRotation: 0,
        edgeThickness: 0.1,
        edgeColor: 'black',
        resolution: 400,
    });
    // cube.setXPlusFaceProperty({ text: '+X' });
    cube.setXMinusFaceProperty({
        text: '-X',
        faceColor: '#ffff00',
        faceRotation: 90,
        fontStyle: 'italic',
    });
    cube.setYPlusFaceProperty({
        text: '+Y',
        faceColor: '#00ff00',
        fontSizeScale: (res) => res / 4,
    });
    cube.setYMinusFaceProperty({
        text: '-Y',
        faceColor: '#00ffff',
        fontColor: 'white',
    });
    cube.setZPlusFaceProperty({
        text: '+Z',
        edgeColor: 'yellow',
    });
    cube.setZMinusFaceProperty({ text: '-Z', faceRotation: 45, edgeThickness: 0 });
    return cube
}


const cube = makeAnnotatedCubeActor()
const axes = makeAxesActor()

const assembly = vtkAssembly.newInstance();
assembly.addActor(axes);
assembly.addActor(cube);

const orientationWidget = vtkOrientationMarkerWidget.newInstance({
        actor: assembly,
        interactor: volumeRenderWindow.getInteractor(),
    });
orientationWidget.setEnabled(true);
orientationWidget.setViewportCorner(
  vtkOrientationMarkerWidget.Corners.BOTTOM_LEFT
);
orientationWidget.setViewportSize(0.15);
orientationWidget.setMinPixelSize(100);
orientationWidget.setMaxPixelSize(300);

```

 I get the following giant cube, without any axes, and when I start interacting, it disappears

![image](https://user-images.githubusercontent.com/7490180/110557091-dd29e380-810d-11eb-9001-243738532f89.png)

I also tried the `vtkAppendPolyData` to add inputData; but for some reason the cube's color and text is not appearing and everything becomes white. 

Any comment is appreciated.

**Comment by jourdain** [comment]
Can you create a codepen so we can play live with it and see what is going on?

**Comment by sedghi** [comment]
@jourdain I created two codesandboxes

1. Using ConeSource: https://codesandbox.io/s/vtk-js-annotatedcube-cone-elz8i
2. Using headsq.vtk: https://codesandbox.io/s/vtk-js-annotatedcube-mip-v1ogk

Summary:
- For the ConeSource It is working fine, and both cube and axes are "assembled" together; however, for the volume rendering, the assembled doesn't show anything, but each alone works inside the vtkOrientationMarkerWidget (if you replace the actor with each alone)

My use case above also is 3D rendering with MIP. Since the vtkOrientationMarkerWidget gets the interactor, is it something related to my interactor?

Also, vtkAxesActor in Python supports X,Y,Z axis labels as well, Can you kindly guide me of how to start implementing that?

**Comment by jourdain** [comment]
@martinken it seems that volume rendering mess something up vs geometry rendering. When I played with the background color and I turn it fully transparent, the full volume rendering is disappearing. 

You may want to investigate what could be going on...

**Comment by jourdain** [comment]
Thanks @sedghi for those live examples as they speed up our investigation.

**Comment by jourdain** [comment]
Actually, it seems that there is a zooming issue in the viewport of the orientation axis which could lead to the issue you are seeing. When @floryst come back from his trip, he should be able to look into it as the orientation axis should not follow the camera (zoom) of the main renderer...

**Comment by jourdain** [comment]
I guess I found the issue... The vtkAssembly is missing a `getBounds()` method or something so the reset camera can actually work.

**Comment by sedghi** [comment]
thanks @jourdain , I'll take a look into adding a `getBounds()` to the assembler. 
I was wondering if you have any suggestion for the axis labels. I went ahead and tried the example of [SpheresAndLabels](https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html) for implementation, however, that make sense for when we are adding text to the main renderer
