### ISSUE TITLE
what is window?

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1325]
This might be a silly question, but what is 'window'? I couldn't find any definition of window , below is a piece of code from [line source](http://kitware.github.io/vtk-js/api/Filters_Sources_LineSource.html).
``` 
    // Points
    const points = new window[pointDataType](numPts * 3);
    pd.getPoints().setData(points, 3);
```

**Comment by jourdain** [comment]
[Global variable window](https://developer.mozilla.org/en-US/docs/Web/API/Window)
