### ISSUE TITLE
How to use GPU render?

### ISSUE THREAD

**Issue by Turtleted21** [Kitware/vtk-js#1327]
Hello
How to use GPU render?

actually I do this : 
` const actor = vtk.Rendering.Core.vtkVolume.newInstance();`
` const mapper = vtk.Rendering.Core.vtkVolumeMapper.newInstance();`
`actor.setMapper(mapper);`
it work

so for use GPU render I try to do this : 
` const actor = vtk.Rendering.OpenGL.vtkVolume.newInstance();`
` const mapper = vtk.Rendering.OpenGL.vtkVolumeMapper.newInstance();`
`actor.setMapper(mapper);`

but I don't see my model
i have a nvidia 1080 ti

**Comment by jourdain** [comment]
Your first case is actually using the GPU when you bind the OpenGL RenderWindow to the vtkRenderWindow, you tell the system to use OpenGL (WebGL) for the mapping.
