### ISSUE TITLE
How to use vtkLookupTable?

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1328]
hi! How to use vtkLookupTable? There are no examples in the official documentation

**Comment by jourdain** [comment]
vtkLookupTable can be found in the [VTK Textbook](https://www.kitware.com/products/books/VTKTextbook.pdf) page 76, 129, 212-213, 221, 459, 492, 526.

**Comment by WebHero0544** [comment]
Well, thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sebastien Jourdain"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 下午4:48
收件人:&nbsp;"Kitware/vtk-js"<vtk-js@noreply.github.com&gt;;
抄送:&nbsp;"@独来独往@"<1073317235@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kitware/vtk-js] How to use vtkLookupTable? (#1328)




vtkLookupTable can be found in the VTK Textbook page 76, 129, 212-213, 221, 459, 492, 526.
