### ISSUE TITLE
How to load local .vti file?

### ISSUE THREAD

**Issue by Neplight** [Kitware/vtk-js#1329]
I try to use HttpDataSetReader to load local .vti file but failed. It requires a json file, so I am a little confused. Is there other api I can use to load local .vti file, or I use HttpDataSetReader wrong?

**Comment by Neplight** [comment]
And here is my code
    
    const reader = vtkHttpDataSetReader.newInstance({ fetchGzip: true });
    marchingCube.setInputConnection(reader.getOutputPort());
    reader
        .setUrl(`./data/head-ascii.vit`, { loadData: true })
        .then(() => {
            const data = reader.getOutputData();
            const dataRange = data
                .getPointData()
                .getScalars()
                .getRange();
            const firstIsoValue = (dataRange[0] + dataRange[1]) / 3;

            const el = document.querySelector('.isoValue');
            el.setAttribute('min', dataRange[0]);
            el.setAttribute('max', dataRange[1]);
            el.setAttribute('value', firstIsoValue);
            el.addEventListener('input', updateIsoValue);

            marchingCube.setContourValue(firstIsoValue);
            renderer.addActor(actor);
            renderer.getActiveCamera().set({ position: [1, 1, 0], viewUp: [0, 0, -1] });
            renderer.resetCamera();
            renderWindow.render();
        });

**Comment by jourdain** [comment]
The `HttpDataSet` example is stating 

> Caution: The example is not actually loading a vtp file but a data structrure that was coming from a vtp file. For more details please read the vtkHttpDataSetReader API;

VTI is a format that encode vtkImageData into an XML format and the proper reader is vtkXMLImageDataReader which is used in [that example](https://kitware.github.io/vtk-js/examples/VolumeViewer.html).

Also do you understand that a WebBrowser is not allowed to access your local file system for security reason?

On top of that  `./data/head-ascii.vit` does not seems to be a `vti` file but a `vit` file.

**Comment by Neplight** [comment]
@jourdain Typo is really embarrassing. 
Anyway, thanks a lot. I will try to use vtkXMLImageDataReader.

**Comment by jourdain** [comment]
No worries, but it could have been the source of your issue too.
