### ISSUE TITLE
How do I get any shear plane in volume

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1331]
Hi, in VTK, how do you get an arbitrary shear plane in volume instead of a shear plane that is perpendicular and parallel to a certain axis

**Comment by floryst** [comment]
You can either check out [ResliceCursor](https://kitware.github.io/vtk-js/examples/ResliceCursor.html) or the [InteractorStyleMPRSlice](https://kitware.github.io/vtk-js/examples/InteractorStyleMPRSlice.html) (this one is visual only).

**Comment by WebHero0544** [comment]
Hello!My current requirement is to click two points on the screen to form a plane perpendicular to the xz plane, and then use this plane to cut the volume, which is similar to the vtkImageSlice. When using the setISlice method of vtkImageMapper, the volume can only be perpendicular to the xz plane and parallel to the yz plane, and the length of the resulting section can't be controlled. I wonder whether vtkImageMapper can be extended.Make it support two input points to form a plane perpendicular to the xz plane or perpendicular to the yz plane or perpendicular to the xy plane to cut the volume. Here is the demo I refer to, I don't know how to extend this piece.Perhaps VTK itself provides such methods or classes that I haven't found.

https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html

**Comment by floryst** [comment]
Right now vtkImageMapper (vtkOpenGLImageMapper contains the actual slicing logic) only supports IJK/XYZ aligned slicing. But, you should be able to build your desired functionality using [vtkImageReslice](https://github.com/Kitware/vtk-js/blob/master/Sources/Imaging/Core/ImageReslice/api.md) (which is what ResliceCursor uses), which can perform arbitray plane slicing. The interactivity portion (clicking two points) will have to come from your application logic.

**Comment by WebHero0544** [comment]
Well, thank you very much. Let me see how do I use ImageReslice

**Comment by agirault** [comment]
Closing this issue. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
