### ISSUE TITLE
Can I draw folds in VTK?

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1333]
Hello!VtkLineSource can draw a definite line with two points, but I found no classes with polylines

**Comment by jourdain** [comment]
We don't have a source that build a vtkPolyData like you want but that should be easy to write. You can look at how `vtkLineSource` is written and create cells that are composed of several segments of lines.
Or you can also create several cells composed of one segment.

**Comment by WebHero0544** [comment]
Well, thank you. I'll try

**Comment by WebHero0544** [comment]
@jourdain Thank you again. Problem solved
