### ISSUE TITLE
Mosaic-like points appear using ImageCropFilter

### ISSUE THREAD

**Issue by knight0905** [Kitware/vtk-js#1334]
When the vti file is loaded, using ImageCropFilter, I want to be able to view arbitrary slices and surfaces. I specified vtkColorTransferFunction and vtkPiecewiseFunction. I want to make the part of the 3D data less than 10 completely transparent, as follows:
piecewiseFunction.addPoint (0.0, 0.0);
piecewiseFunction.addPoint (10, 1.0);
However, on the surface of the object, mosaic-like points appear, and the surface does not look smooth. Why is this and what should i do

![捕获](https://user-images.githubusercontent.com/59352943/74916217-6e91bf00-5400-11ea-8e3b-57838f3d9c3c.PNG)

**Comment by floryst** [comment]
Try reducing the volume rendering sample distance to a small value (<1) to see if that smooths out the rendering. (`vtkVolumeMapper.setSampleDistance(value)`)

**Comment by agirault** [comment]
Closing this issue. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
