### ISSUE TITLE
ClosedPolyLineToSurfaceFilter usage

### ISSUE THREAD

**Issue by bastiends** [Kitware/vtk-js#1338]
Hello,

I have a set of points and I would like to get a closed polyline based on those points.
I found the ClosedPolyLineToSurfaceFilter which seems to be the class to do that but I don't really understand how I'm suppose to set my points and retrieve my polyline

Can anyone help me with that ?

Thanks !

**Comment by jourdain** [comment]
ClosedPolyLineToSurfaceFilter aim to create a surface from a closed line. 
To provide the closed lines, you need to feel a vtkPolyData with line cells. 

To read more on VTK, you can look at the PDF book available freely available [here](https://vtk.org/vtk-textbook/)

**Comment by bastiends** [comment]
Hi Jourdain

Thanks for your information !

I've looked at the pdf but I cannot find a reference to the ClosedPolyLineToSurfaceFilter, could you help me find the documentation of this function ?

**Comment by jourdain** [comment]
What you are looking for is creating a `vtkPolyData with cells that define lines.`

Then you will use that polydata as input of the vtkClosedPolyLineToSurfaceFilter.

**Comment by bastiends** [comment]
I've created a Polydata, but I don't know how to pass it to a vtkClosedPolyLineToSurfaceFilter

```
let closedPolyline = vtkClosedPolyLineToSurfaceFilter.newInstance();

closedPolyline.setInputData(linePolydata, 0);
closedPolyline.addInputData(meshPolydata);
closedPolyline.update();

let closedPolylineMapper = vtkMapper.newInstance();
closedPolylineMapper.setInputData(closedPolyline.getOutputData());

let closedPolylineActor = vtkActor.newInstance();

myRenderer.addActor(closedPolylineActor);
myRenderer.resetCamera();
```

But when the scene is rerendered I got the following error : 
`TypeError: model.oglmapper is undefined`

Am I configuring using the vtkClosedPolyLineToSurfaceFilter correctly?

**Comment by jourdain** [comment]
Can you provide the full code?
What is `meshPolydata`? 
Why didn't you connect the mapper to the actor? (the reason of the current issue)

In general it seems that you don't have much understanding of the VTK pipeline. 
It might be worth going through more code examples to understand the core concepts.

**Comment by bastiends** [comment]
Oh yeah your were right I forgot to connect the mapper.

This is working now, but vtkClosedPolyLineToSurfaceFilter is finally not what I'm looking for.

I'm looking for a way to extract a surface from a polydata based on a closed line (like vtkSelectPolyData do in python) do I have a way to do that in vtk js ?

**Comment by jourdain** [comment]
Do you want to keep all the cells (polys) that have their points enclosed in a polygonal selection loop?

I don't think we have anything like that out of the box. But with hardware selection of points and polygonal enclosure testing you might be able to do it yourself.

**Comment by bastiends** [comment]
Ok, I'll see what I can do !

Thank for your help
