### ISSUE TITLE
vtkOrientationMarkerWidget on a vtkRemoteView

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1339]
I would like to add a `vtkOrientationMarkerWidget` on a `vtkRemoteView`. 

```
    this.view = vtkRemoteView.newInstance();
    this.view.setContainer(this.$refs.vtkView);
    this.orientationWidget = vtkOrientationMarkerWidget.newInstance({
      actor: vtkAxesActor.newInstance(),
      interactor: this.view.getInteractor()
    });
    this.orientationWidget.setEnabled(true);
    this.orientationWidget.setViewportSize(0.1);
```

I get this error 
```
Error in mounted hook: "TypeError: model.interactor.findPokedRenderer(...).getRenderWindow is not a function"
```

If I understand the issue, it does not seem to work because the view associated to the interactor is a `CanvasView` and does  not have the required method for this [call](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/OrientationMarkerWidget/index.js#L118)

Is there a way to make it works?

Thanks

**Comment by jourdain** [comment]
To make it work, you need to create a regular vtkRenderWindow with the openGL backend while binding the ImageStream. You can look at what [ParaView Lite](https://github.com/Kitware/paraview-lite/blob/master/src/components/core/View/script.js) is doing.

**Comment by BotellaA** [comment]
Ok, it seems a lot just for a Marker. 

Is it working to put the Marker on the VTK remote? I see some "fixme" https://github.com/Kitware/VTK/blob/master/Web/Python/vtkmodules/web/protocols.py#L165

**Comment by jourdain** [comment]
On the JS side vtkRemoteView is a strip down version of the vtkOpenGLRenderWindow without any local 3D rendering or WebGL. 

If you want local 3D rendering, you need to have a local vtk.js RenderWindow.

If you don't want local rendering, you can indeed adjust the content of the RenderWindow on the server side to have an orientation axis.

The fixme that you see is related to the API expected by ParaView that is not by default available on a vtkRenderWindow. So we just expose the same API while doing nothing with that call.

**Comment by BotellaA** [comment]
Do you have an example with the Marker on the server side? I added the marker following classic example but in python:
```
            renderer = vtk.vtkRenderer()
            renderWindow = vtk.vtkRenderWindow()
            renderWindow.AddRenderer(renderer)

            renderWindowInteractor = vtk.vtkRenderWindowInteractor()
            renderWindowInteractor.SetRenderWindow(renderWindow)
            renderWindowInteractor.GetInteractorStyle().SetCurrentStyleToTrackballCamera()
        
            axes = vtk.vtkAxesActor()
            widget = vtk.vtkOrientationMarkerWidget()
            widget.SetOrientationMarker(axes)
            widget.SetInteractor(renderWindowInteractor)
            widget.SetViewport( 0.0, 0.0, 0.2, 0.2 )
            widget.EnabledOn()
            widget.InteractiveOn()


            renderer.ResetCamera()
            renderWindow.Render()
```

It works when python server starts but the marker disappears when the first image get pushed on the local side.

**Comment by jourdain** [comment]
I'm not sure but it should work.

**Comment by BotellaA** [comment]
I updated my minimal example with the Marker. I got the same behavior, the marker is gone after the first image/resize.

https://github.com/BotellaA/test-vtk-web

**Comment by BotellaA** [comment]
I am still trying but nothing new.. Any advise on where should I look to debug this ?

**Comment by BotellaA** [comment]
Solve the issue. The marker was getting deleted by python.. 😕
