### ISSUE TITLE
Is there a way in VTK to tell if the actor is in the camera?

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1342]
Hi! Is there a way in VTK to tell if the actor is in the camera?(The actor is in the visual region)

**Comment by floryst** [comment]
There might be a better way, but one possible solution is to render a color picking buffer with [vtkOpenGLHardwareSelector](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/HardwareSelector/index.js), and then scanning for non-empty pixels. Not performant, but should work.

**Comment by WebHero0544** [comment]
Well, thank you. Let me see

**Comment by WebHero0544** [comment]
Well, the question should have been, how can I tell by the coordinates of the points, the lines, the planes whether they are in the vertebral body(in the camera)?

**Comment by floryst** [comment]
If you have actors in your scene and you want to know if they are visible on the display, then I would use the HardwareSelector mentioned above. Are you trying to determine if all actors (including occluded ones) are in the viewport? If so, then that might be more complicated. You could use the camera transform matrices to see if your coordinates end up in in clip space (from -1 to 1 I think).

**Comment by WebHero0544** [comment]
Well, thank you very much. The second answer is what I want to know

**Comment by agirault** [comment]
Closing this issue. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
