### ISSUE TITLE
ImageOutlineFilter is not in vtk.js

### ISSUE THREAD

**Issue by QearlGril** [Kitware/vtk-js#1350]
hi @jourdain  ImageOutlineFilter is not in vtk.js？

**Comment by jourdain** [comment]
No, but it would be trivial to add it. Feel free to submit a MR.

**Comment by QearlGril** [comment]
Thank you，wait new version

**Comment by jourdain** [comment]
Actually it is implemented but not registered in our available binary.

@floryst if you push anything on vtk.js could you update [this](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/General/index.js)?
