### ISSUE TITLE
Trouble with Read Local Json

### ISSUE THREAD

**Issue by fying-snow** [Kitware/vtk-js#1351]
Hello, I'm trying to develop the MPR demo in my own project. I just put the files and data source from the following directions to my own place.

> vtk-js-master\Sources\Interaction\Style\InteractorStyleMPRSlice\example
> vtk-js-master\Data\volume\headsq.vti`

The code for loading the local json is pasted below and I figured out "__BASE_PATH__ equires '' ".

`reader.setUrl(`${__BASE_PATH__}/data/volume/headsq.vti`, { loadData: true })`

So, I just changed the url to **'/data/volume/headsq.vti'.**

However, I had a trouble with loading the json file.
![image](https://user-images.githubusercontent.com/10750319/76062006-b51a1880-5fbf-11ea-87b9-eba3c2a6160c.png)

But if I just run the source from github, it works well.
![image](https://user-images.githubusercontent.com/10750319/76062401-923c3400-5fc0-11ea-9270-3766c319e685.png)

I'm very confusing with this problem. Hope you can help me figure it out. Thanks a lot!

**Comment by jourdain** [comment]
My bet is that you did not create a rule to serve your data directory like we have in vtk-js repo.

- [Example runner](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L64-L71)
- [github.io deployed](https://github.com/Kitware/vtk-js/blob/master/Documentation/config.js#L87)

**Comment by fying-snow** [comment]
> My bet is that you did not create a rule to serve your data directory like we have in vtk-js repo.
> 
> * [Example runner](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L64-L71)
> * [github.io deployed](https://github.com/Kitware/vtk-js/blob/master/Documentation/config.js#L87)

Oh yes, you are right, I did't create the rule. But do I need to add both the rules from the two files? It didn't work when I only added the proxy rule to my webpack.config.js.

I'm not sure how to use the following rule:
`copy: [{ src: '../Data/*', dest: './build-tmp/public/data' }],`

Thank you again for such quick response!

**Comment by jourdain** [comment]
Sorry, I was just trying to give you a hint on what was happening not really giving you a complete solution as I don't know your setup. The second "rule" is not a rule, it was just to show you that I had to copy the data for the static web site generation so the data could actually be available online.

If you are using webpack and you have a similar setup as vtk.js here are the two relevant part.
- [serve data](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L54)
- [proxy](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L64-L71)

But please, now that you know the problem, take the time to search on the web the solution.
The dev team of vtk.js can't help you answer general questions such as: `how to serve static files with webpack?` 

HTH,

Seb

**Comment by fying-snow** [comment]
> Sorry, I was just trying to give you a hint on what was happening not really giving you a complete solution as I don't know your setup. The second "rule" is not a rule, it was just to show you that I had to copy the data for the static web site generation so the data could actually be available online.
> 
> If you are using webpack and you have a similar setup as vtk.js here are the two relevant part.
> 
> * [serve data](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L54)
> * [proxy](https://github.com/Kitware/vtk-js/blob/master/Utilities/ExampleRunner/template-config.js#L64-L71)
> 
> But please, now that you know the problem, take the time to search on the web the solution.
> The dev team of vtk.js can't help you answer general questions such as: `how to serve static files with webpack?`
> 
> HTH,
> 
> Seb

Yes, you are right. I'm sorry to bother you with such a general question. I was too confused.
Thank you for your patience and I'll close this issue.

**Comment by jourdain** [comment]
No worries, we are happy to help...
