### ISSUE TITLE
CroppingWidget for draco objects

### ISSUE THREAD

**Issue by zac92** [Kitware/vtk-js#1352]
I need to implement a cropping widget for draco objects.
Is there already any solution for doing it?

I had tried it with the ImageCroppingWidget example but i saw that it is just working with imagedata.
Is it possible to modify the widget to use it with draco objects?

Thank you

**Comment by agirault** [comment]
Hi @zac92. Sorry that took a while, we're working through issues now: are you still interested in this?

**Comment by agirault** [comment]
Hi @zac92. Sorry for the late answer, we’re working through issues now. If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
