### ISSUE TITLE
How to load local parallel vtk data file？

### ISSUE THREAD

**Issue by shaolun-Ryan** [Kitware/vtk-js#1353]
Hi jourdain！

I wonder if i can load my local vtk data such as .pvti  .pvts  .pvtu etc. and how？Is there any proper data renderer exists to load these data montioned above？

Thx for ur help！

**Comment by jourdain** [comment]
You will need to load all the *.vti or your .pvti by creating a new mapper/actor for each file.
vts and vtu are not currently supported but we hope to have a better integration with WebAssembly to better integrate the VTK/C++ code into the web environment.

**Comment by shaolun-Ryan** [comment]
Thanks for ur suggestions Jourdain!

Is there any other parallel data format except .pvti data?

And what renderer can i use to load .vti and .pvti data? Will `XMLImageDataReader` work?

Have a nice day!

**Comment by jourdain** [comment]
If I'm not mistaken, a pvti contains a directory of vti files. Each vti file can be loaded by the `XMLImageDataReader`. If you render them directly, they will be volume rendered. If you are looking for geometry rendering, you will have to process them to extract a polydata.

**Comment by shaolun-Ryan** [comment]
Sure，I will go ahead based on ur suggestions!
Thx a lot!

**Comment by agirault** [comment]
Regarding missing IO: vtk.js mostly focuses on rendering and therefore all 3d cell processing is not supported unless you involve WebAssembly like VTK/C++ or ITK.js as of today. We might support it in the future. Closing for now. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
