### ISSUE TITLE
how to draw  series coordinates which are perpendicular to the tube ?

### ISSUE THREAD

**Issue by buptwny** [Kitware/vtk-js#1357]
I used the tubeFilter to create a tube, then I want to draw some lines which are perpendicular to the cube so I can get the distribution about some define value. 
Just like the colorful lines which perpendicular to the white tube in the picture:
![image](https://user-images.githubusercontent.com/19993890/76344340-5f859900-633c-11ea-8459-913dd07dc152.png)
Is there any tools or filters already in the vtkjs I can use?
Thanks a lot!

**Comment by jourdain** [comment]
I would create a custom filter that will create a given polydata that will be flat and only represent the `well log`. Then by providing the camera information, you could update the transform of the actor to make it normal to the camera.

**Comment by agirault** [comment]
Closing this issue. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
