### ISSUE TITLE
Texture as image doesn't work anymore

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#136]
I don't know which commit does that but adding a texture (as an image) to an actor doesn't work anymore as we can see in the elevation example : https://kitware.github.io/vtk-js/examples/ElevationReader.html

**Comment by martinken** [comment]
Yes :_) Thanks. We are working on it. Should have a fix soon. We are in the middle of updating it to support async loading of images and it is in a broken state.

**Comment by laurennlam** [comment]
Okay cool ! Thanks !
