### ISSUE TITLE
how can i read binary vtp file using vtk.js

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1362]
Hi,
I managed to read asicii format vtp file by using vtkPolyDataReader, however, I want to read binary vtp file, as it's size is much smaller than the one in asicii format. Is there a way to do that? Thanks

**Comment by jourdain** [comment]
vtp can be read by [vtkXMLPolyDataReader](https://github.com/Kitware/vtk-js/tree/master/Sources/IO/XML/XMLPolyDataReader) with the format [appended+zlib].
