### ISSUE TITLE
Do not allow the actor to scale

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1364]
Hello, how do I stop the specified actor from zooming when I'm interacting with the mouse wheel?

**Comment by jourdain** [comment]
What is your actor displaying?

**Comment by WebHero0544** [comment]
I wanted to paste the textured text image onto the actor, but the texture would blur when zooming in, so I wanted to keep the actor from zooming in, but the interaction would rotate and pan

**Comment by jourdain** [comment]
It seems that you just don't want to zoom. Use the style manipulator without registering the zoom one.

**Comment by WebHero0544** [comment]
Well, no, I want the specified actor not to scale, but the other actors can still scale.Is there a way to render the specified actor without using the scaling matrix?

**Comment by jourdain** [comment]
Not really. If they belong to the same scene. Eventually you could use separate renderer to dissociate the camera like we do with the orientation axes.

**Comment by WebHero0544** [comment]
Is there no other way than to use separate renderers?

**Comment by jourdain** [comment]
Unless it is a 2D actor? But with the specification of your problem it is hard to tell.

**Comment by WebHero0544** [comment]
Well, thank you. I'll try the way you just said, and I'll ask you if that doesn't work

**Comment by WebHero0544** [comment]
I may not have been clear about yesterday's question, but instead, the question should be this: is it possible to scale without changing the width and height of the vtkPlaneSource?I need it to be that big all the time, but it does scale.I wonder if VTK has a way to implement this function.

**Comment by WebHero0544** [comment]
![error](https://user-images.githubusercontent.com/17270753/76816147-7ba4a100-683a-11ea-8ac9-31fbbe05e002.png)
One more problem: I called the getState method on vtkActor to report an error that was caused by the guidance of the scalarRange attribute, but I don't know what the problem is, so it is normal to call the getState method on the vtkCamera.

**Comment by agirault** [comment]
Hi @WebHero0544. Sorry for the late answer, we’re working through issues now. If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
