### ISSUE TITLE
how to display massive number of actors and improve interaction speed?

### ISSUE THREAD

**Issue by Joun-lee** [Kitware/vtk-js#1365]
Hi, dear exports,
I have about 20,000 actors and composited with 40,000,000 cells. Is it possible with any methods that I can display the actors and interact with the scene smoothly?  Thanks!

**Comment by jourdain** [comment]
How does ParaView behave with such scene? Also could you provide more information regarding the type of data and rendering that you are looking for?

Is it an unstructured grid or an actual surface mesh such as a point cloud?

**Comment by Joun-lee** [comment]
Thanks for your reply! I haven't tried Paraview, as the file type is customed. I parsed the file and use vtk.js to converted my data into vtkPolyData. It's not surface mesh but just polylines.

**Comment by jourdain** [comment]
I see, and you have 40,000,000 polylines split among 20K actors?

Can you reduce the number of actors by merging the datasource? What kind of GPU do you have? 

What are the current fps that you are getting?

**Comment by Joun-lee** [comment]
My GUP is Quadro RTX 3000, I don't know how to test the fps, but I can hardly rotate the view with the mouse. Sure I can merge the data source, but I wan to separately control the color and visibility of the polylines. So split every polyline to be a single actor seems to the only option I've got.

**Comment by jourdain** [comment]
Actors are indeed convenient, but it is not your only options. You can tag each line with a given Id and control their color and opacity in a fast manner as well.

**Comment by Joun-lee** [comment]
Really! That would be great! Is there any example I can reference?

**Comment by jourdain** [comment]
Try first to see how fast it is to have all those lines. Also are you only making cells with 2 points or are you making bigger cells that provide complex lines? (better to use less cells assuming the split correspond to the amount of control you want to have)

**Comment by Joun-lee** [comment]
every polyline is tree-structure like, so it is a complex polyline. I will first try to merge them together to see what it would be. 
`You can tag each line with a given Id and control their color and opacity in a fast manner as well.`
Here the id means the cell id? And how can I control the cell's color or opacity?

**Comment by jourdain** [comment]
Add one or more fields to `cellData` of your vtkPolyData.  Then you could name that new field 'Id' if you like, but you don't have to.

**Comment by Joun-lee** [comment]
Ok, I see. Thank you!. I know cellData can be used to color the vtkPolyData. So the opacity is controlled with the (r,g,b, a), where a is the opacity. Am I right?

**Comment by jourdain** [comment]
I'm not sure anymore, but I think you can control the opacity the same way you control color with a transfer function.

**Comment by Joun-lee** [comment]
Ok, I will look into that. Again, thank you very much for your help!
