### ISSUE TITLE
The image color generated by using the vtkImageSlice class when zooming is inconsistent

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1367]
Hello, when I used the vtkImageSlice class to generate the image, when the mouse zoomed-in, I found that the edge of the color contained the color I used to call renderer.setBackground(1, 1, 1) method, which in this case is white.I don't know what caused it.But I've found that this happens when the vtkImageSlice class is followed by multiple vtkPlaneSource classes (representation.wireframe) that are updated with the end of the zoom.

**Comment by jourdain** [comment]
Just set the background to fully transparent (`setBackground(0,0,0,0)`)and set the white in the HTML element.

**Comment by WebHero0544** [comment]
No, in the image, the colored edges become white again

**Comment by WebHero0544** [comment]
You said white should be set on the container, right?

**Comment by jourdain** [comment]
Can you provide a screenshot so we can make sure we properly understand what you mean by edge?

Yes, on the html CSS element while providing 4 values to setBackground(...).

**Comment by WebHero0544** [comment]
Ok, just a moment

**Comment by WebHero0544** [comment]
This graph is correct before scaling
![QQ截图20200321163345](https://user-images.githubusercontent.com/17270753/77222838-074b6400-6b92-11ea-85dd-712657d981c9.png)
After scaling, the color edges of the figure contain white
![QQ截图20200321163421](https://user-images.githubusercontent.com/17270753/77222851-15998000-6b92-11ea-95c0-07c3f7b0e424.png)


Current related Settings:
(1)this.renderer.setBackground(0, 0, 0, 0);
(2)this.container  //html element
.vtk-box {
  position: relative;
  height: 100%;
  background: #fff;
}

**Comment by WebHero0544** [comment]
It may be the influence of the tile diagram behind, remove the tile diagram is no problem, but there is still a problem, just no tile diagram can not be seen

**Comment by jourdain** [comment]
This is indeed strange and I'm not sure I understand what could be going on. Is the vtkRenderWindow just an overlay of your map? What happen if you try to set the css background to black?

@martinken do you have any idea of what could be going on?

**Comment by WebHero0544** [comment]
The vtkRenderWindow is not overwritten on the map and is implemented using the vtkTexture and vtkvtkPlaneSource

**Comment by WebHero0544** [comment]
It is estimated that there is a relationship with the asynchronous loading of the image. When the image is successfully loaded, it will be drawn to VTK one by one. Then, the color of the image generated by vtkImageSlice will be in trouble, that is, the color of the edge will be the same as the background color (renderer.setBackground(0, 0, 0, 0))

**Comment by WebHero0544** [comment]
When no tiles are loaded and the image is redrawn with vtkImageSlice, everything is fine

**Comment by jourdain** [comment]
As your image data is probably just 1D on the Z you might be able to use it as a texture on another plane source while using ScalarToRGBA filter to convert your numerical value into a transparent image.

**Comment by WebHero0544** [comment]
By "image data" do you mean the image generated using the vtkImageSlice class?

**Comment by WebHero0544** [comment]
Well, thank you very much. I see what you mean

**Comment by agirault** [comment]
Closing this issue. If you still need help, feel free to go ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
