### ISSUE TITLE
 How to get multiple slice image data through imageReslice

### ISSUE THREAD

**Issue by hu3402379** [Kitware/vtk-js#1368]
Hi:

I want to get the data of multiple slices through imageReslice, and then put it together into a piece of data to display in browser。

1）I see that there is  'slabNumberOfSlices' property in the source code that can specify how many layers to slice, but it looks no use。 
at ImageReslice/index.js  line 234， 
If I want 5 slices, I set 'slabNumberOfSlices' value is 5, the nsamples's value will return min value。
```    
// multiple samples for thick slabs
    const nsamples = Math.min(model.slabNumberOfSlices, 1);
```
So did this happen?

2）
The 'slabMode' attribute seems to implement the mip function, but at  line 827 of the /imageReslice/index.js, it returns a null.
```
publicAPI.getCompositeFunc = (slabMode, slabTrapezoidIntegration) => null;
```

So, if I want to use imageReslice to get multiple slices to do the mip function, what better way to achieve this is to take multiple slices one layer at a time?

Thank a lot。

**Comment by agirault** [comment]
Hi @hu3402379. Sorry for the late answer, we’re working through issues now. If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
