### ISSUE TITLE
How to do loop rendering

### ISSUE THREAD

**Issue by knight0905** [Kitware/vtk-js#1369]
There are multiple model files. As follows

const vtiUrls = [
  `${__BASE_PATH__}/data/volume/headsq1.vti`,
  `${__BASE_PATH__}/data/volume/headsq2.vti`,
];
// Render the first file
reader.setUrl(vtiUrls[0]).then(() => {
  reader.loadData().then(() => {
    renderer.addVolume(actor);
    const data = reader.getOutputData();
    cropFilter.setCroppingPlanes(...data.getExtent());

    setupControlPanel(data, cropFilter);

    const interactor = renderWindow.getInteractor();
    interactor.setDesiredUpdateRate(5.0);
    renderer.resetCamera();
    renderWindow.render();
  });
});

How to read the model file through the timer and then render it dynamically

**Comment by jourdain** [comment]
I'm not sure to understand the question. What is the thing you call `timer`?
Call `renderWindow.render();` when you want to trigger a render.
Another approach could be to request an animation.

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
