### ISSUE TITLE
The vtkImageMarchingCubes class is slow

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1370]
Hello, when using vtkImageMarchingCubes, how to solve the problem that the page UI card is dead due to the large amount of computation?

**Comment by jourdain** [comment]
You can run it in a WebWorker and just publish the polydata for rendering.

**Comment by WebHero0544** [comment]
I've tried, but vtk.js(script from: https://unpkg.com/vtk.js) is running in the background to report an error

**Comment by WebHero0544** [comment]
I don't know how to build js running in the background

**Comment by jourdain** [comment]
Look at online tutorials on WebWorkers.

**Comment by WebHero0544** [comment]
I know about webworkers, but VTK doesn't work in webworkers, and there are many browser environments in the code, such as window objects

**Comment by jourdain** [comment]
I'm just talking about executing 1 filter into a webworker not performing the rendering in a WebWorker. A filter by definition is executing a function. You just need to create the infrastructure to pass typed array around. To me that's the perfect fit.

**Comment by WebHero0544** [comment]
I know, but I don't know how to reference useful classes separately in webworkers, such as the vtkImageMarchingCubes class, which now all references all VTK code to report an error.Here you can download the source code and then directly reference the script as needed

**Comment by WebHero0544** [comment]
But it doesn't seem to work. The code hasn't been compiled yet

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
