### ISSUE TITLE
export-scene-macro.py crashes on latest pvpython

### ISSUE THREAD

**Issue by benoitpaillard** [Kitware/vtk-js#1372]
Hi all, 

[export-scene-macro.py](https://github.com/Kitware/vtk-js/blob/master/Utilities/ParaView/export-scene-macro.py) is not functional with pvpython 5.8 python 3.7

I started digging into it but there are a bunch of issues I just do not understand.

Thank you for your help.

**Comment by jourdain** [comment]
You should use the UI now for doing the export. The macro was initially created before we could do a proper integration inside ParaView. I did not removed the macro as it could be used as ref but does not aim to be used anymore.

**Comment by jourdain** [comment]
My guess is a bunch of import path that changed in PV 5.8. Feel free to post the errors here.

**Comment by benoitpaillard** [comment]
Ha neat, I had not noticed that new export feature. That's going to simplify many things on my side, stoked !

Thanks

**Comment by jourdain** [comment]
FYI https://blog.kitware.com/exporting-paraview-scenes-to-paraview-glance/
