### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by simwes** [Kitware/vtk-js#1373]
Hi,

I am trying to run the standalone vtk web loader shown in the [website](https://kitware.github.io/vtk-js/examples/HttpDataSetReader.html). However, when I run the html script on my Firefox browser I get this error:
Cross-Origin Request Blocked: _The Same Origin Policy disallows reading the remote resource at file: file:///home/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow. (Reason: CORS request not http)_

I am still new to this kind of scripts. Can anyone suggest a solution?
Thank you very much for your help!

**Comment by jourdain** [comment]
A browser is not allowed to read your local drive for security reason unless you tell it to. If you do a couple of google search on CORS you will find good documents that explain that part.

Moreover, that specific example is for HTTP:// not FILE://. I think you are looking for something more like [ParaView Glance](https://kitware.github.io/paraview-glance/) or some other example that let you click a button to let you load local files inside the browser.
