### ISSUE TITLE
Provide HttpHeaders (Authorization) for XMLPolyDataReader.setUrl()

### ISSUE THREAD

**Issue by goflo** [Kitware/vtk-js#1375]
Hi,

I'm using XMLPolyDataReader to read a PolyData XML file from a API. That works fine when the API method is accessible without authorization.
But we need to provide a access token for the API by setting the Authorization field in the HTTP header.

Is that possible?

At the moment I use the XmlPolyDataReader like this:

```
  public addModelFromUrl(url: string) {
    const reader = this.vtkXMLPolyDataReader.newInstance();
    reader.setUrl(url).then(() => {
      const modelPolyData = reader.getOutputData(0);
      ...
    });
  }
```

Thanks!

**Comment by jourdain** [comment]
Good point, I'm not sure, but I think that `setURL(url, options={})` can support a second optional argument. We should add a `header` (or something like that) and make sure we propagate it all the way to the actual network call. Feel free to submit a PR if you want.

**Comment by goflo** [comment]
@jourdain thanks for your reply!

I now load the data from the API by my own service implementation. There I can of course provide the access token. I need to load some meta data too and therefore it's easier to do that by my own. 

From the new API endpoint I get a Base64 string for the content of the vtp file. I convert that Base64 string to a ArrayBuffer and use the `parseAsArrayBuffer()` function of the `vtkXMLPolyDataReader` to read the data. That seems to be working - at least I don't see any errors in the console.
But I'm struggle to get the PolyData from the reader. Using the `setUrl()` function I done it like this:

````
    const reader = this.vtkXMLPolyDataReader.newInstance();
    reader.setUrl('http://example.com/api/mesh/4711').then(() => {
      const modelPolyData = reader.getOutputData(0);
    });
````

But using the `parseAsArrayBuffer()` function this doesn't work:
````
      const buffer = this.base64ToArrayBuffer(modelData.vtkPolyData);
      const reader = this.vtkXMLPolyDataReader.newInstance();
      reader.parseAsArrayBuffer(buffer);    // <--- seems not to return a promise :-/
      reader.getOutputPort(0);    // <--- this is undefined!
````

**Comment by goflo** [comment]
I solved the problem. Encoding of the Base64 was wrong. I used now ASCII Encoding and it works now 😊

**Comment by mikesuttie** [comment]
Could you post up full solution please ? I am also having this issue.

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper.js#L17-L21

**Comment by mikesuttie** [comment]
> https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper.js#L17-L21

That's great, thank you!
