### ISSUE TITLE
Local rendering + vtkWeb server

### ISSUE THREAD

**Issue by esalehim** [Kitware/vtk-js#1376]
Hi,

I'm trying to use vtkWeb as a data processing server but do the actual rendering on client side with  [SynchronizableRenderWindow](https://kitware.github.io/vtk-js/api/Rendering_Misc_SynchronizableRenderWindow.html). 

I'm aware that `SynchronizableRenderWindow` could work with ParaView backend (via `ParaViewWebLocalRendering` Protocol), but similar api is missing in vtkweb. Is there a way to make it work? I'd like to stick with vtkWeb since I have my code in pure vtk

Thanks

**Comment by jourdain** [comment]
You "just" need to provide the missing server side RPC which should be fairly easy to do if you use the ParaView version as reference.
https://github.com/Kitware/ParaView/blob/master/Web/Python/paraview/web/protocols.py#L908-L1001

**Comment by esalehim** [comment]
Thanks for your reply @jourdain!

That's what I actually did. With some minor changes I've managed to replicate the missing api in vtkweb. Now I'm able to deliver the geometry (points+lines) but for some reason scalar arrays are not delivered! I'll do some more troubleshooting and will let you know.

But I was also curious to know:
1) What is the motivation for `vtkWebViewPortGeometryDelivery` class then?! Is there any client side (vtk.js) component that matches this?

2) Is it possible to use geometry delivery in mpi parallel mode? using either paraview or vtkweb backend? I tried that with **pvbatch** and I get a crash at `pushGeometry`

3) In general is there any other benefit for choosing paraviewweb over vtkweb server?

**Comment by jourdain** [comment]
1. It is the legacy one that we don't use anymore. But left for compatibility reason.
2. Yes, but you need to force "rendering" to happen on process 0 by tuning some rendering threshold.
3. ParaView provide a higher level API (easier to code on server side) and provide natural support for MPI.

**Comment by jourdain** [comment]
If your code is fairly limited and you already have "all" of it in VTK, it might be just fine to use the VTK approach.

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
