### ISSUE TITLE
Coincident topology and vtkImageMapper

### ISSUE THREAD

**Issue by boucaud** [Kitware/vtk-js#1377]
Hello,
We are having issues with coincident topology and the image mapper, and we would like to be able to use setRelativeCoincidentTopologyPolygonOffsetParameters with vtkImageMapper to fix those issues.

I tried to implement this in a simple way, and got it to work by essentially doing this:

1. Derive vtkImageMapper from vtkMapper instead of vtkAbstractMapper
2. Add shader replacements/set uniforms in vtkOpenGLImageMapper

My question is about this first step. I'm not sure whether it is to be avoided, and whether it has side effects that I didn't notice. An alternative would be to move the coincident topology methods up to vtkAbstractMapper, or to create an intermediary class.

What do you think ? Does this approach seem ok, or do you prefer one of the alternatives ? Did I miss something ?
Thanks,
Adrien

**Comment by finetjul** [comment]
@martinken @jourdain what do you think ?
