### ISSUE TITLE
GL framebuffer incomplete

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1381]
Hello,
it is not really an issue but more a question,

I noticed when loading the example InteractiveOrientationWidget:
https://kitware.github.io/vtk-js/examples/InteractiveOrientationWidget.html

There are several warnings trace in the js console:
![Capture d’écran de 2020-04-03 10-03-23](https://user-images.githubusercontent.com/18531147/78338084-6b0e5d80-7592-11ea-9d69-9c41a2899b91.png)

I was wondering if someone know where it comes from and if it's really harmeless

**Comment by jourdain** [comment]
I'm thinking that we might be calling stuff that should be delayed until the GLContext is properly created. That's just a wild guess as everything is fine once the app is ready and running.

@martinken do you have any idea?

**Comment by martinken** [comment]
No idea, but it looks like a bug. Our framebuffer should be complete etc so something is up.

**Comment by xavArtley** [comment]
Don't know if it's help for this issue but the warning appear only when the mouse cursor enter into the renderwindow
Moreover the marker widget size increase as well
![invalid_framebuffer](https://user-images.githubusercontent.com/18531147/94006327-f5948480-fd9f-11ea-88b1-deabeab40648.gif)

**Comment by jourdain** [comment]
@floryst

**Comment by floryst** [comment]
I can no longer reproduce this issue in vtk.js v19. If the warnings still show up, please re-open and let us know.
