### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#1382]
This happens in `WidgetManager`::`updateSvg()` promise, line `model.svgRoot.appendChild(node);`

This is because at the time the promise is ran, `WidgetManager` has already been destroyed. 

@floryst  Is the fix as simple as `return`ing if `model.deleted` is `true` ?

**Comment by floryst** [comment]
I agree, we should check for `model.deleted` there, or the existence of `model.svgRoot`.
