### ISSUE TITLE
Can I use the render function asynchronously

### ISSUE THREAD

**Issue by Tixxxon** [Kitware/vtk-js#1383]
I have a big one .vtk model that I upload over the network, read vtkPolydataReader and then fill in the polydata. I call the render() function, which runs for a few seconds, resulting in a window lock. Is there a way around this? Thanks. Sorry for my English :)

**Comment by thewtex** [comment]
Hi @Tixxxon ,

If the time in the main thread is being spent while reading the polydata, you can [use itk.js](https://insightsoftwareconsortium.github.io/itk-js/docs/polydata_formats.html) for reading, which will run in a background thread.

**Comment by Tixxxon** [comment]
Thanks for the answer, but the main time is spent on the render function()

Here is an example:

POINTS 44895 double
reader.parseAsText: 92.369140625ms
mapper.setInputData: 0.012939453125ms
renderer.render: 252.023193359375ms

**Comment by Tixxxon** [comment]
I have a model of 10 actors. I tried calling the render function both at the end of adding all actors and after adding each actor

**Comment by jourdain** [comment]
This is really strange. Your data is small. Can you share your data? What is the device spec that you are running that on?

**Comment by Tixxxon** [comment]
[https://yadi.sk/d/k2-0yLTRpWxyzg](yandex.disk)
3 GHz 4-core i5
8 Gb DDR4
Radeon Pro 555 2 Gb
OSX

**Comment by jourdain** [comment]
I see the first data generation for WebGL leads to a 180 ms time. 
While afterwords, any render is around 0.3 ms.

We currently don't have any infrastructure to generate the GL data inside a web worker.
It could be done but the effort might not be small...

**Comment by Tixxxon** [comment]
I understood. Thanks for the answer. I hope very much that this can happen in the future :)
