### ISSUE TITLE
How does ImageData modify the scalar value ? 

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1390]
How does ImageData modify the scalar value ? 

Just like   ------
int dims[3];
	reader->GetOutput()->GetDimensions(dims);   
	int nbofcomp;
	nbofcomp = reader->GetOutput()->GetNumberOfScalarComponents();
	for (int k = 0; k < dims[2];k++){
		for (int j = 0; j < dims[1]; j++){
			for (int i = 0; i < dims[0]; i++){
				if (i < 79 && i>31 && j>14 && j < 50){
					unsigned char *pixel = (unsigned char*)(reader->GetOutput()->GetScalarPointer(i, j, k));
					*pixel = 255 - *pixel;  //将选择的区域设置成反色
					*(pixel + 1) = 255 - *(pixel + 1);
					*(pixel + 2) = 255 - *(pixel + 2);
				}
		   }
		}
	}

**Comment by jourdain** [comment]
```
const imagedata = reader.getOutputData();
const dimensions = imagedata.getDimensions();
const scalars = imagedata.getPointData().getScalars();
const nbOfComp = scalars.getNumberOfComponents();
const typedArray = scalars.getData();

for (let k = 0; k < dimensions[2]; k++) {
  for (let j = 0; j < dimensions[1]; j++) {
    for (let i = 0; i < dimensions[0]; i++) {
       const idx = (i + j * dimensions[0] + k * dimensions[0] * dimensions[1]) * nbOfComp;
       for (let c = 0; c < nbOfComp; c++) {
         typedArray[idx + c] = 255 - typedArray[idx + c];
       }
    }
  }
}
scalars.modified();
imagedata.modified();
```

**Comment by huatianyu** [comment]
> ```
> const imagedata = reader.getOutputData();
> const dimensions = imagedata.getDimensions();
> const scalars = imagedata.getPointData().getScalars();
> const nbOfComp = scalars.getNumberOfComponents();
> const typedArray = scalars.getData();
> 
> for (let k = 0; k < dimensions[2]; k++) {
>   for (let j = 0; j < dimensions[1]; j++) {
>     for (let i = 0; i < dimensions[0]; i++) {
>        const idx = (i + j * dimensions[0] + k * dimensions[0] * dimensions[1]) * nbOfComp;
>        for (let c = 0; c < nbOfComp; c++) {
>          typedArray[idx + c] = 255 - typedArray[idx + c];
>        }
>     }
>   }
> }
> scalars.modified();
> imagedata.modified();
> ```



> ```
> const imagedata = reader.getOutputData();
> const dimensions = imagedata.getDimensions();
> const scalars = imagedata.getPointData().getScalars();
> const nbOfComp = scalars.getNumberOfComponents();
> const typedArray = scalars.getData();
> 
> for (let k = 0; k < dimensions[2]; k++) {
>   for (let j = 0; j < dimensions[1]; j++) {
>     for (let i = 0; i < dimensions[0]; i++) {
>        const idx = (i + j * dimensions[0] + k * dimensions[0] * dimensions[1]) * nbOfComp;
>        for (let c = 0; c < nbOfComp; c++) {
>          typedArray[idx + c] = 255 - typedArray[idx + c];
>        }
>     }
>   }
> }
> scalars.modified();
> imagedata.modified();
> ```

I wanted to get the level surface by setting the scalar, but that didn't show up. How do I get the isosurface from the ImageData?
