### ISSUE TITLE
How to handle CONTEXT_LOST_WEBGL errors gracefully?

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1391]
Is there a place in VTK that I can listen for these errors? I am getting them with extremely large DICOM volumes, _sometimes_. No easily reproduceable steps, but would love to be able to catch the error and show a dialog to the user. 

Thanks!

**Comment by floryst** [comment]
You can get the canvas through your openglRenderWindow object and add a listener for the event "webglcontextlost".
