### ISSUE TITLE
I wanted to get the level surface by setting the scalar, but that didn't show up. How do I get the isosurface from the ImageData?

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1393]
const imagedata = reader.getOutputData();
const dimensions = imagedata.getDimensions();
const scalars = imagedata.getPointData().getScalars();
const nbOfComp = scalars.getNumberOfComponents();
const typedArray = scalars.getData();

for (let k = 0; k < dimensions[2]; k++) {
  for (let j = 0; j < dimensions[1]; j++) {
    for (let i = 0; i < dimensions[0]; i++) {
       const idx = (i + j * dimensions[0] + k * dimensions[0] * dimensions[1]) * nbOfComp;
       for (let c = 0; c < nbOfComp; c++) {
         typedArray[idx + c] = 255 - typedArray[idx + c];
       }
    }
  }
}
scalars.modified();
imagedata.modified();

**Comment by jourdain** [comment]
https://kitware.github.io/vtk-js/examples/VolumeContour.html

**Comment by huatianyu** [comment]
I used the vtkVolumeMapper class. VtkImageMarchingCubes cannot be used here. Could you tell me how to draw isosurface with vtkVolume

**Comment by jourdain** [comment]
Change the piecewise function to make a specific value opaque.

Yet you can still use that example as your data is the same type as the given example.

**Comment by huatianyu** [comment]
The instance:
const actor = vtkActor.newInstance();
const mapper = vtkMapper.newInstance();
const marchingCube = vtkImageMarchingCubes.newInstance({
  contourValue: 0.0,
  computeNormals: true,
  mergePoints: true,
});

actor.setMapper(mapper);
mapper.setInputConnection(marchingCube.getOutputPort());

My project:
   const volumeActor = vtkVolume.newInstance();
   const volumeMapper = vtkVolumeMapper.newInstance();
   ........
    volumeActor.getProperty().setRGBTransferFunction(0, lookupTable);
    volumeActor.getProperty().setScalarOpacity(1, piecewiseFun);
------------------------------------------------------------------------------------------------------------


/ / volumeMapper setInputConnection (marchingCube getOutputPort ());
     
    Do you mean you can use the volumeMapper like this?

**Comment by jourdain** [comment]
Just run the example with your data. The filter convert your vtkImageData into a vtkPolyData which can be rendered using geometry rendering and not volume rendering.

If you want to highlight contour in Volume rendering, you need to play with the piecewise transfer function.
