### ISSUE TITLE
Set orientation of AxesActor

### ISSUE THREAD

**Issue by goflo** [Kitware/vtk-js#1394]
Hi,

I need to add multiple AxesActors to represent the local coordinate cystems of elements. For each element I have a coordinate system which is defined by three direction vectors (vx, vy, vz) and an origin point (x, y, z). Set the position of the AxesActor is easy using the setPostionFrom() function and providing the x, y, z tuple.

But how can I rotate the AxesActor so that the x axis is align in direction of vx, y axis in direction of vy and z axis in direction of vz?

I have tried to calculated the angles between the global coordinate system and the three axes and then rotate the AxesActor using rotateX, rotateY and rotateZ. But that isn't working properly.

Thanks!

**Comment by floryst** [comment]
You can use `actor.setOrientation(x,y,z)` (in deg I think) to orient your actor.

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
