### ISSUE TITLE
How do I get an index based on world coordinates?Is that right

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1395]
let coordinates = ["0.63", "-24.72", "-82.5"];
        let x = coordinates[0]
        let y = coordinates[1]
        let z = coordinates[2]
        //     Gets an index based on world coordinates
        vtkImageData.worldToIndex([parseFloat(x), parseFloat(y), parseFloat(z)], outArr)
        let q = Math.round(outArr[0])
        let w = Math.round(outArr[1])
        let e = Math.round(outArr[2])
        const idx = (q + w * dimensions[0] + e * dimensions[0] * dimensions[1]) * nbOfComp;

**Comment by jourdain** [comment]
seems like it. Could do that too:
```
const imageData = vtkImageData.newInstance();
[...]
const coordinates = ["0.63", "-24.72", "-82.5"];
const  [i,j,k] = imageData.worldToIndex(coordinates.map(Number)).map(Math.round);
const idx = (i + j * dimensions[0] + k * dimensions[0] * dimensions[1]) * nbOfComp;
```

**Comment by jourdain** [comment]
Please use https://discourse.vtk.org/ for question rather than the bug tracker.
