### ISSUE TITLE
ImageMapper rendering issues 

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#1396]
Since v13.12.0, there are some broken behavior. Please find below 2 issues I found:
 - the [ImageOutlineFilter ](https://kitware.github.io/vtk-js/examples/ImageOutlineFilter.html) example renders all black.
 - Global plane opacity on vtkImageSlice property no longer works:
```
const actor = vtkImageSlice.newInstance();
...
actor.getProperty().setOpacity(0.5);
```

**Comment by scottwittenburg** [comment]
Thanks @finetjul I'll take a look.

**Comment by scottwittenburg** [comment]
@finetjul I was able to reproduce and fix the issue you reported with the ImageOutlineFilter example.  I cannot reproduce the opacity issue.  To test the problem, I just ran:

```
npm run example -- MouseRangeManipulator
```

and then used the console and objects attached to the global scope to try it out.  See the video below:

![opacity_repro](https://user-images.githubusercontent.com/6527504/78958559-9b2f9200-7aa5-11ea-8b1a-2d8a115e080a.gif)

**Comment by finetjul** [comment]
@scottwittenburg, indeed opacity works. It behaves strangely though.
I used to set it at 0.65 and now I have to set it around 0.005 to have the same translucency.

**Comment by scottwittenburg** [comment]
Thanks @finetjul I'll give that a try and see if I can get to the bottom of it.

**Comment by scottwittenburg** [comment]
@finetjul I was able to reproduce that behavior you described, and I have pushed one more commit to my current PR (#1397) which fixes it.
