### ISSUE TITLE
How do I set colors for scalars correctly?

### ISSUE THREAD

**Issue by Tixxxon** [Kitware/vtk-js#1401]
How do I set colors for scalars? I didn't find any examples. For some reason, I get them the other way around. I set setScalarRange([550, 570]) and the cells with the value 550 are red, and the cells 570 are blue, and it should be the other way around. Thanks

**Comment by jourdain** [comment]
That is expected due to the default HueRange of the lookup table.

[That example](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) use and allow the user to interactively apply presets to the vtkColorTransferFunction.

**Comment by Tixxxon** [comment]
Thanks! :)
