### ISSUE TITLE
How do you make any slice on the left see only one outline?

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1402]
I used volume drawing to change the grayscale of each Dicom slice to display the contour lines.But after the actual reconstruction, see the blue circle.There are other contours in the height range of one contour in the picture on the right, resulting in multiple contours on the left.Why is there overlap on the right? How to make only one contour visible in the picture on the left?

Is it set here？how do i do？

    volumeActor.getProperty().setScalarOpacityUnitDistance(0, 0.1);
    volumeActor.getProperty().setUseGradientOpacity(0, false);
    volumeActor.getProperty().setRGBTransferFunction(0, lookupTable);
    volumeActor.getProperty().setScalarOpacity(0, piecewiseFun);
    volumeActor.getProperty().setGradientOpacityMinimumValue(0, 15);
     volumeActor.getProperty().setGradientOpacityMinimumOpacity(0, 0.0);
     volumeActor.getProperty().setGradientOpacityMaximumValue(0, 100);
     volumeActor.getProperty().setGradientOpacityMaximumOpacity(0, 1.0);
     volumeActor.getProperty().setShade(true);
     volumeActor.getProperty().setAmbient(0.2);
     volumeActor.getProperty().setDiffuse(0.7);
     volumeActor.getProperty().setSpecular(0.3);
     volumeActor.getProperty().setSpecularPower(8.0);

![image](https://user-images.githubusercontent.com/24466497/79202070-9daa3700-7e6b-11ea-8d38-14eac2506c22.png)

**Comment by agirault** [comment]
Hi @huatianyu. Sorry for the late answer, we’re working through issues now. If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
