### ISSUE TITLE
WRONG OFFSET (Uint32Array should be a multiple of 4)

### ISSUE THREAD

**Issue by lorifranke** [Kitware/vtk-js#1404]
Hi there,

I am experiencing the following error:
```
RangeError: start offset of Uint32Array should be a multiple of 4
    at new Uint32Array (<anonymous>)
    at Object.Zf [as processDataArray] (index.js:186)
    at index.js:23
    at u (index.js:81)
    at Object.e.parseXML (index.js:75)
    at Jf.e.parseAsArrayBuffer (index.js:504)
```

Code in my application:
``` 
...
const reader = window.vtk.IO.XML.vtkXMLPolyDataReader.newInstance();
reader.setUrl('/data/cluster_00050.vtp')).then(() => {
    const polydata = reader.getOutputData();
    ...
```

Expected offset 591128 as given in file:
![Screen Shot 2020-04-14 at 1 05 12 PM](https://user-images.githubusercontent.com/38534852/79253943-fa005d00-7e51-11ea-9a4f-060484802b2a.png)

Actual offset 699382 when debugging into `reader.setUrl`:
![Screen Shot 2020-04-14 at 1 00 28 PM](https://user-images.githubusercontent.com/38534852/79254042-24eab100-7e52-11ea-95a7-f4019992750a.png)

Observation:
For some of my vtp-files loading works. In other cases (e.g. the one above) it appears the offset is not read correctly, while surprisingly other attributes look correct. I wonder if I have to specify any options when loading with vtkXMLPolyDataReader. 

Please help (paper deadline approaching)!

**Comment by jourdain** [comment]
This is a JS limitation implementation. The offset is correct but trigger an issue in your browser. The solution for you would be to convert the file inside ParaView to a binary+encoding format rather than appended+zlib.

Appended+zlib is the preferred format in general though...

**Comment by lorifranke** [comment]
Thank you @jourdain for the quick response!
Do you have more insights as to what exactly is the JS limitation? I would like to better understand how this can happen.

In parallel, I tried to load with VTK in Python - where it worked:
<img width="627" alt="Screen Shot 2020-04-14 at 1 48 00 PM" src="https://user-images.githubusercontent.com/38534852/79256808-a5131580-7e56-11ea-9e01-4f560e548942.png">

I know this is VTK.js, but do you happen to know the magic lines of code to save this into binary+encoding in Python?

**Comment by jourdain** [comment]
```
SetDataModeToBinary()
```

I guess the encoded part is automatic on Binary. 

The issue is that with appended you have a big byte array like follow

```
Temp_Float32(n), Flag_Uint8(n), ..., Pressure_Float32(n)
```
And in JS when you do
```
const pressure = new Float32(offset, nbFloat);
```
When offset is not a multiple of 4 bytes (32 bits) it complains.

**Comment by lorifranke** [comment]
Thanks for your help! The suggestion with SetDataModeToBinary() worked well. I was able to transform the file to binary with the following Python code:

```
import vtk
file = "cluster_00050.vtp"
reader = vtk.vtkXMLPolyDataReader()
reader.SetFileName(file)
writer = vtk.vtkXMLPolyDataWriter()
writer.SetFileName('cluster_00050_bin.vtp')
writer.SetInputConnection(reader.GetOutputPort())
writer.SetDataModeToBinary()
writer.Write()
```

Now the file can be loaded in JS without getting the error :)
