### ISSUE TITLE
vtkCutter's Output's point type is Array  and cannot be appended?

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1405]
Hi,
I am trying to append the output of vtkCutter, but it raised an error at the line below, says "pointData.set is not a function".
`pointData.set(ds.getPoints().getData(), numPts * 3); //vtkAppendPolyData line 157`

I then go to look up vtkCutter source code, and find that  the point type of it's output is Array instead of Float32Array, which don't have the function of 'set'.
Am i right, or is there other problem?

**Comment by jourdain** [comment]
You are right, the vtkCutter is not converting its internal JS arrays into typed array when updating its output dataset. 

FYI @agirault @laurennlam

**Comment by lihouxing-sjtu** [comment]
For whom may encounter the same issue, I use the code below temporary to make the output of vtkCutter as a safe input for vtkAppendPolydata
```
    let outData = cutter.getOutputData();
        let numOfPoints = outData.getPoints().getNumberOfPoints();
        if (numOfPoints == 0) {
          return;
        }
        let points = vtkPoints.newInstance();
        points .setNumberOfPoints(numOfPoints);
        points .getData().set(outData.getPoints().getData());
        outData.setPoints(points );
```
