### ISSUE TITLE
Using vtkWebGLObject binary data in vtk.js

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#1406]
I have a VTKWeb application and I would like to send the geometry from the server side to the client side. I looked at `vtkWebGLObject` which can output a binary array but I do not understand how to use this output in vtk.js.

Is there a documentation or example on how to use this binary output on the client side?

Thanks for your help

**Comment by jourdain** [comment]
https://github.com/Kitware/visualizer/blob/master/server/pvw-visualizer.py#L199
https://github.com/Kitware/visualizer/blob/master/src/MainView.js#L5

Should give you the starting point of what you should look at.

**Comment by BotellaA** [comment]
Thanks for your quick answer. 
You seem to point out to the `SynchronizableRenderWindow`. It might look too complexe for my goal. I am creating a polydata on the server side from several data, and I would like to display this polydata on the client side. However, it will never be displayed on the server side and should be destroyed once send to client.

**Comment by jourdain** [comment]
Then if you have a somewhat simpler path, you should serialize (in memory) your vtkPolyData into a compressed vtp files and send them over as attachement (binary) and let the client decode them using vtk.js vtkXMLPolyDataReader.parseAsByteArray using your own endpoint or pub/sub listener.

**Comment by BotellaA** [comment]
If I want to sync the camera interactions but with two different data (one on the client and one on the server), is `SynchronizableRenderWindow` the best way to go ? Or would it be better to go for a `ViewProxy` and try to apply the mouse interactions on both sides? Or something else?

**Comment by jourdain** [comment]
SynchronizableRenderWindow mostly focus on rendering content not the camera. So it would be better to handle the synchronization yourself. Like on mouse release if that make sense for your use case.

**Comment by BotellaA** [comment]
I made it works with `vtkXMLPolyDataReader` and synchronization en mouse release and end wheel event. Thanks!
