### ISSUE TITLE
How do I set transparency for scalars correctly?

### ISSUE THREAD

**Issue by QearlGril** [Kitware/vtk-js#1408]
@jourdain  , How do I set transparency for scalars correctly in the GeometryViewer？I know piecewiseFunction can be set in th volume，scalars have a similar one？thankyou

**Comment by agirault** [comment]
Hi @QearlGril. Sorry for the late answer, we’re working through issues now. If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
