### ISSUE TITLE
renderer geometry to a 3D array

### ISSUE THREAD

**Issue by mastrogiorgis** [Kitware/vtk-js#1412]
Hi,

I'm trying to access the content of the renderer that has several actors and save the 3D geometry to a 3D array. 
Can anyone please provide some guidance on how to do this?

Many thanks,

**Comment by floryst** [comment]
Can you explain what you mean by saving the geometry to a 3D array? Do you want to rasterize the 3D scene into some arbitrarily-sized 3D array, or do you mean something else?

**Comment by mastrogiorgis** [comment]
Hi @floryst and thanks for the reply.
What I'm effectively trying to do is to store the cube actors used to draw the attached scene into a 3D array or any other form of an array. Is there a way that I can access the renderer and get the coordinates of the cubes?

![walls](https://user-images.githubusercontent.com/23278410/82437850-08b0e400-9a90-11ea-8544-548f8fd53524.jpg)

Many thanks,

**Comment by floryst** [comment]
If you're generating your scene with many different cubes/actors, then you should have access to the source PolyData object for each of your cubes. You can obtain the vertices of your cubes via `cubePolyData.getPoints().getData()`, which will give you the vertices of the cube as a single array. (The `i`th vertex is at position `i*3`.)

**Comment by mastrogiorgis** [comment]
Yes, the scene is generated using cubes (vtkCubeSource) but not vtkPolyData. Do you think there is a way to draw this information from the renderer rather than trying to access all cube actors individually?
Many thanks,

**Comment by floryst** [comment]
You're better off getting the information from your CubeSources. Something like the following will get you your vertices:
```
const cubeSources = [ ... your list of vtkCubeSource objects ];
cubeSources.forEach((source) => {
  const cubePolyData = source.getOutputData();
  const vertices = cubePolyData.getPoints().getData();
});
```

**Comment by mastrogiorgis** [comment]
Thanks for that, but I cannot reproduce the same in python.

`for cube in cube_list:
    print(cube)
    cubePolyData = cube.getOutputData()
    print(cubePolyData)
    vertices = cubePolyData.getPoints().getData()`
AttributeError: 'vtkFiltersSourcesPython.vtkCubeSource' object has no attribute 'getOutputData'

**Comment by jourdain** [comment]
`cube.getOutputData() [JS] <=> [Python] cube.getOutput()`

**Comment by jourdain** [comment]
`getData()` only exist in JS and allow to access the underlying TypedArray.
In Python, you directly have the `vtkDataArray` no need to get to a native type that does not exist in C++.

**Comment by mastrogiorgis** [comment]
Thanks for that but I still get a similar error:
AttributeError: 'vtkFiltersSourcesPython.vtkCubeSource' object has no attribute 'getOutput'

**Comment by jourdain** [comment]
Could you provide the full Python?

```
from vtk import vtkCubeSource

cube = vtkCubeSource()
cube.Update()
cube.GetOutput()
```

**Comment by mastrogiorgis** [comment]
Sure and thank you for looking into this @jourdain 

```
import vtk

cube_list = []

def cube_from_source(x,y,z):

    cube_source = vtk.vtkCubeSource()

    cube_source.SetXLength(x)
    cube_source.SetYLength(y)
    cube_source.SetZLength(z)
    cube_source.Update()

    #kolos = cube_source.getOutput()
    mapper = vtk.vtkPolyDataMapper()
    mapper.SetInputConnection(cube_source.GetOutputPort())
    mapper.Update()

    cube_list.append(cube_source)

    actor = vtk.vtkActor()
    actor.SetMapper(mapper)

    render = vtk.vtkRenderer()
    render.AddActor(actor)

    renWin = vtk.vtkRenderWindow()
    renWin.AddRenderer(render)

    renWinIn = vtk.vtkRenderWindowInteractor()
    renWinIn.SetRenderWindow(renWin)

    renWinIn.Start()



cube_from_source(10,10,10)

#cubeSources = cube_list;
for cube in cube_list:
    print(cube)
    cubePolyData = cube.getOutput()
    print(cubePolyData)
    vertices = cubePolyData.getPoints().getData()
```

**Comment by jourdain** [comment]
C++ methods starts with Capital letter, hence the issue.

[See](https://vtk.org/doc/nightly/html/classvtkPolyDataAlgorithm.html#ae2047a60e7e61d213dfd6ec6dc6bbecf)

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
