### ISSUE TITLE
Expose Reslice Cursors in vtk.js release

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1413]
Hello,

Is it possible to expose the different class used in https://kitware.github.io/vtk-js/examples/ResliceCursor/index.html in the compiled bundle?

Thanks

**Comment by jourdain** [comment]
Sure feel free to submit an MR with all the sub directory added in [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/index.js) with a commit message like `fix(Widgets): Expose missing classes`
