### ISSUE TITLE
how to use vtk-js in angular ?

### ISSUE THREAD

**Issue by TarrahArshad** [Kitware/vtk-js#1415]
i need use vtk-js to angular cli app

**Comment by jourdain** [comment]
You can use the CDN version of vtk.js or if you plan to build it from source within your angular app, you will just need to add specific rules for webpack to properly handle vtk.js dependencies.

See some example [here](https://github.com/Kitware/vtk-js/blob/master/Utilities/config/dependency.js) or [here](https://github.com/Kitware/vtk-js/blob/master/Utilities/config/chainWebpack.js) for reference.

**Comment by TarrahArshad** [comment]
you have sample angular code ?

**Comment by TarrahArshad** [comment]
i added CDN how to i can call from my angular typescript code?

**Comment by jourdain** [comment]
https://kitware.github.io/vtk-js/docs/intro_vtk_as_external_script.html

**Comment by cavramescu** [comment]
Is there any demo of how to include vtk.js in an angular 8+ project?

**Comment by cavramescu** [comment]
@TarrahArshad  Could you make it work? I'm also trying to integrate it in angular 8, but i have no success.

**Comment by jourdain** [comment]
Can someone provide a base angular project with some dummy vtk.js render window?
I can look into it and see how to fix it to make it work.

**Comment by TarrahArshad** [comment]
i can do it

**Comment by dolremi** [comment]
@TarrahArshad could you provide some example codes to make it work in angular? Thank you very much.

**Comment by floryst** [comment]
I made a quick & minimal working example of vtk.js in Angular 10 default template: https://github.com/floryst/vtk-js-angular-10

You can read the README.md for a general overview, and the second commit in the repo is the changeset from the default angular 10 template.

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
