### ISSUE TITLE
Tolerance on widget

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#1417]
HI All,
I'm actually working on the vtkResliceCursorWidget (from old to new widget structure).
I'd like to know if there is a way to set the tolerance for the picking ? Because I'm using line and it's quite difficult to pick it.

Thanks.

**Comment by jourdain** [comment]
The way we deal with tolerance is that we render something different on the back buffer for the picking part.
A line is a bit tricky was we don't have lineWidth. But maybe with a glyph+cylinder you could create some thickness.

**Comment by laurennlam** [comment]
Thanks @jourdain !
