### ISSUE TITLE
How to use vtk.js to reconstruct DICOM file

### ISSUE THREAD

**Issue by lsy1998** [Kitware/vtk-js#1437]
I hope to reconstruct the DICOM sequence in three dimensions through vtk.js, but I don't know how to start. What should I do

**Comment by jourdain** [comment]
It might be interesting to look into itk-js for the decoding and its integration with vtk.js. 

FYI: @thewtex

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
