### ISSUE TITLE
Draw spline curve

### ISSUE THREAD

**Issue by materdd** [Kitware/vtk-js#1439]
Thanks for your work.
I would like to draw a spline curve in vtk.js as same as the below link. How can I do the same in vtk.js?

https://vtk.org/Wiki/VTK/Examples/Cxx/PolyData/ParametricSpline

Best regards

**Comment by floryst** [comment]
Check out [SplineContextRepresentation](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Representations/SplineContextRepresentation/index.js#L85) for an example of what you can do to render your spline.

**Comment by floryst** [comment]
If this is still an issue, please re-open or ask on our [Discourse](https://discourse.vtk.org/c/web/9)
