### ISSUE TITLE
How can i  cut a 3D image with an abitrary slice plane and draw the results on the screen?

### ISSUE THREAD

**Issue by lihouxing-sjtu** [Kitware/vtk-js#1444]
Hi,
Do we have any class like vtkImageResliceMapper in c++? I tried vtkReliceImage, but didn't work out. The result image slice is not at right postion. If there is no such vtkImageResliceMapper class, how to set the parameters for vtkResliceImage to get the desired result?

**Comment by floryst** [comment]
@luciemac @finetjul

**Comment by finetjul** [comment]
Hi it is indeed `vtkImageReslice` that you can use. It is a literal translation of the C++ code. I have been notified that some bugs may exist.

You can see usage [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Imaging/Core/ImageReslice/test/testImageReslice.js) in the associated test  

There is the pending Python code to test the same action with C++ implementation.

**Comment by lihouxing-sjtu** [comment]
I went through the C++ code, and found there may be some diffences as to the js version. As the pictures below shows, are the indexes correct in the js version? 
![Snipaste_2020-05-15_09-43-27](https://user-images.githubusercontent.com/18169068/82002524-90fa4800-9690-11ea-9711-a3bd2b74d986.png)
![Snipaste_2020-05-15_09-42-56](https://user-images.githubusercontent.com/18169068/82002526-935ca200-9690-11ea-834d-bc5544c7ce56.png)

**Comment by finetjul** [comment]
I think it is fine especially if it is the same inversion all over the file.

But have you tried to invert those and see if that fixes your problem ?

**Comment by lihouxing-sjtu** [comment]
I tried to swich the 'i' and 'j' here, but it didn't fix my problem. May be there are other parts that should be changed.  The mat4 in js stores every item along the row, so is the matrix in c++, am I right? If they are the same way to define row and col, the order here may be wrong.

**Comment by floryst** [comment]
Closing due to age, but if vtkImageReslice is not sufficient then the [VolumeMapper clip planes](https://kitware.github.io/vtk-js/examples/VolumeClipPlane.html) can be used for slab slicing.
