### ISSUE TITLE
setSampleDistance doesn't seem to work, how do you make it work

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1447]
I want to use 
"labelMap. Actor. GetProperty () setInterpolationTypeToNearest ();
LabelMap. Mapper. SetSampleDistance (0.1);"
Interpolation,

 but setSampleDistance doesn't seem to work, how do you make it work

**Comment by floryst** [comment]
Just to make sure: are you calling `renderWindow.render()` after setting your sample distance?

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
