### ISSUE TITLE
Launcher to run example is broken

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#1448]
The examples cannot be ran anymore from the command line.
It seems that it's caused by this commit : 62071c7339a3a30e6ca8c151a2d0e2779075eb2d

Line 4 of file vtk-js/Utilities/ExampleRunner/example-runner-cli.js 
`var { program } = require('commander');`

@floryst

**Comment by floryst** [comment]
Running examples on master seems to work for me. Might be worth to make sure your node_modules isn't out of date. If that's not the issue, then let me know what examples are not running and I'll look into it.

**Comment by laurennlam** [comment]
that's correct, it's been a long time since I didn't update the node_module. I'll let you know !

**Comment by laurennlam** [comment]
@floryst Thanks for your advice. Indeed, I didn't update the node_module since a long time and it fix every thing.
