### ISSUE TITLE
getCellPoints output not making sense for some files

### ISSUE THREAD

**Issue by nsab1n** [Kitware/vtk-js#1455]
I'm having trouble using `getCellPoints` for a vtp file read using `vtkXMLPolyDataReader`. The data I'm using isn't public, but my issue seems to be reproducible using the GeometryViewer example.

From [this data](https://data.kitware.com/#collection/586fef9f8d777f05f44a5c86/folder/59de9dd58d777f31ac641dc3), if I use `diskout.vtp` and put a breakpoint in the console after the data is parsed in the array buffer, using `getCellPoints` matches what I see opening the same vtp file in ParaView:
![image](https://user-images.githubusercontent.com/65524604/82177550-5b619300-990c-11ea-815c-07f2540ce9a9.png)
![image](https://user-images.githubusercontent.com/65524604/82177572-6d433600-990c-11ea-852a-029c75053851.png)

However, if i use `diskout-stream-ascii.vtp`, the output from `getCellPoints` is unusable:
![image](https://user-images.githubusercontent.com/65524604/82177654-c27f4780-990c-11ea-8861-ed356e5dc73a.png)
Paraview finds the cell and its points:
![image](https://user-images.githubusercontent.com/65524604/82177688-de82e900-990c-11ea-9e74-d3809fe8e470.png)

I'm aware these files are completely different, and I've chosen arbitrary cell IDs here just for illustration, but this is the same issue I'm having with my own data. Interestingly, `getOutputData(0).getPolys().getCellSizes()` on `diskout-stream-ascii.vtp` returns an array of the correct length and suggests every poly is a quad, which I think is correct (and none of the cell sizes are in the 000s). Is there a way to get the point IDs associated with a specific cell in this case?

**Comment by jourdain** [comment]
It seems we are off by one as we can see the value 4 which should be the number of points of the cell. Which means we wrongly interpreted the point id as a cell size.

@finetjul

**Comment by finetjul** [comment]
If you change 0 to 1 [line 69](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/PolyData/index.js#L69).

Would it fix the issue ?

If so, the `publicAPI.buildCells()` logic should be tweaked/fixed.

**Comment by nsab1n** [comment]
Thanks for your quick replies and pointing me in the right direction! I think `buildCells` itself is fine and it wasn't an off-by-one problem, the issue (I believe) is that the cell location passed to `cells.getCell()` [at line 196](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/PolyData/index.js#L196) is relative to the start of the cell array for all cells, whereas `cells.getCell()` expects a location relative to the start of its array (polys/lines etc). I guess the reason `diskout.vtp` worked is that it doesn't have any lines?

Using my dataset, this is the cellpoints I expect for cell id 53691, from ParaView:
![image](https://user-images.githubusercontent.com/65524604/82278502-f3b75080-99bc-11ea-8e1b-593d2adf07ef.png)
I did some investigation in the console to confirm (note `this.polydata = reader.getOutputData(0)`):
![image](https://user-images.githubusercontent.com/65524604/82279016-19912500-99be-11ea-9b2a-17833dcfe401.png)
In my project I've worked around this by building the cell IDs myself, I did also check this using a hacky change to `publicAPI.getCellPoints`:
```javascript
  publicAPI.getCellPoints = (cellId) => {
    const cellType = model.cells.getCellType(cellId);
    let cells = null;
    let locOffset = 0;
    switch (cellType) {
      case CellType.VTK_VERTEX:
      case CellType.VTK_POLY_VERTEX:
        cells = model.verts;
        break;

      case CellType.VTK_LINE:
      case CellType.VTK_POLY_LINE:
        locOffset = model.verts.get().values.length;
        cells = model.lines;
        break;

      case CellType.VTK_TRIANGLE:
      case CellType.VTK_QUAD:
      case CellType.VTK_POLYGON:
        locOffset = model.verts.get().values.length + 
          model.lines.get().values.length;
        cells = model.polys;
        break;

      case CellType.VTK_TRIANGLE_STRIP:
        locOffset = model.verts.get().values.length + 
          model.lines.get().values.length +
          model.polys.get().values.length;
        cells = model.strips;
        break;

      default:
        cells = null;
        return { type: 0, cellPointIds: null };
    }
    const loc = model.cells.getCellLocation(cellId);
    const cellPointIds = cells.getCell(loc - locOffset);
    return { cellType, cellPointIds };
  };
```
Which worked for my dataset but is pretty ugly - I guess you guys have a more canonical way to implement this.

Thanks for the quick replies and your work on the library! Sorry if this was a bit verbose - haven't raised issues on public github projects before.

**Comment by finetjul** [comment]
Can you please test my MR and tell me if it fixes your issue or not.

**Comment by nsab1n** [comment]
Yes - that worked for my dataset. Thanks a lot :)
