### ISSUE TITLE
How to convert vtkimagedata of vtk.js to opencv.js Mat 

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1456]
Like C++:
// vtkImageData==>Mat
cv::Mat vtkImage2Mat(vtkImageData *image)
{
    int dim[3];
    image->GetDimensions(dim);
    int imgType=CV_8UC1;
    if(image->GetNumberOfScalarComponents()==1)
        imgType=CV_8UC1;
    if(image->GetNumberOfScalarComponents()==3)
        imgType=CV_8UC3;
 
    cv::Mat matSrc(dim[1],dim[0],imgType,image->GetScalarPointer());
 
    return matSrc;
}

**Comment by jourdain** [comment]
You can get the corresponding TypedArray from a vtkImageData like that: `imageData.getPointData().getScalars()`

HTH
