### ISSUE TITLE
How does vtk.js create a  polygonal Dataset  

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1460]
like this:
![ae733f1569862426b85590a553042cb](https://user-images.githubusercontent.com/24466497/82425964-d1572d00-9ab9-11ea-82ac-880463147b72.png)

**Comment by jourdain** [comment]
?

**Comment by huatianyu** [comment]
> ?

Can't you see the picture?

**Comment by huatianyu** [comment]
> ?
   this is my data       
 data: [
            ['0.63', '-24.72', '-82.5'],
            ['1.88', '-25.09', '-82.5'],
            ['3.13', '-25.36', '-82.5'],
            ['4.38', '-25.54', '-82.5'],
            ['5.63', '-25.6', '-82.5'],
            ['6.88', '-25.54', '-82.5'],
            ['8.13', '-25.42', '-82.5'],
            ['9.38', '-25.18', '-82.5'],
            ['10.63', '-24.78', '-82.5'],
            ['11.64', '-24.38', '-82.5'],
            ['11.88', '-24.28', '-82.5'],
            ['13.13', '-23.65', '-82.5'],
            ['13.98', '-23.13', '-82.5'],
            ['14.38', '-22.88', '-82.5'],
            ['15.63', '-21.98', '-82.5'],
            ['15.76', '-21.88', '-82.5'],
            ['16.88', '-20.9', '-82.5'],
            ['17.17', '-20.63', '-82.5'],
            ['18.13', '-19.73', '-82.5'],
            ['18.48', '-19.38', '-82.5'],
            ['19.38', '-18.48', '-82.5'],
            ['19.71', '-18.13', '-82.5'],
            ['20.63', '-17.08', '-82.5'],
            ['20.81', '-16.88', '-82.5'],
            ['21.88', '-15.67', '-82.5'],
            ['21.91', '-15.63', '-82.5'],
            ['23.02', '-14.38', '-82.5'],
            ['23.13', '-14.25', '-82.5'],
            ['24.12', '-13.13', '-82.5'],
            ['24.38', '-12.83', '-82.5'],
            ['25.22', '-11.88', '-82.5'],
            ['25.63', '-11.42', '-82.5'],
            ['26.37', '-10.63', '-82.5'],
            ['26.88', '-10.08', '-82.5'],
            ['27.54', '-9.38', '-82.5'],
            ['28.13', '-8.79', '-82.5'],
            ['28.79', '-8.13', '-82.5'],
            ['29.38', '-7.54', '-82.5'],
            ['30.04', '-6.88', '-82.5'],
            ['30.63', '-6.29', '-82.5'],
            ['31.33', '-5.63', '-82.5'],
            ['31.88', '-5.12', '-82.5'],
            ['32.67', '-4.38', '-82.5'],
            ['33.13', '-3.97', '-82.5'],
            ['34.08', '-3.13', '-82.5'],
            ['34.38', '-2.87', '-82.5'],
            ['35.5', '-1.88', '-82.5'],
            ['35.63', '-1.76', '-82.5'],
            ['36.88', '-0.66', '-82.5'],
            ['36.92', '-0.63', '-82.5'],
            ['38.13', '0.37', '-82.5'],
            ['38.42', '0.63', '-82.5'],
            ['39.38', '1.47', '-82.5'],
            ['39.81', '1.88', '-82.5'],
            ['40.63', '2.65', '-82.5'],
            ['41.13', '3.13', '-82.5'],
            ['41.88', '3.82', '-82.5'],
            ['42.46', '4.38', '-82.5'],
            ['43.13', '5.04', '-82.5'],
            ['43.71', '5.63', '-82.5'],
            ['44.38', '6.25', '-82.5'],
            ['45.0', '6.88', '-82.5'],
            ['45.63', '7.5', '-82.5'],
            ['46.29', '8.13', '-82.5'],
            ['46.88', '8.71', '-82.5'],
            ['47.54', '9.38', '-82.5'],
            ['48.13', '9.96', '-82.5'],
            ['48.79', '10.63', '-82.5'],
            ['49.38', '11.21', '-82.5'],
            ['50.04', '11.88', '-82.5'],
            ['50.63', '12.46', '-82.5'],
            ['51.29', '13.13', '-82.5'],
            ['51.88', '13.75', '-82.5'],
            ['52.46', '14.38', '-82.5'],
            ['53.13', '15.04', '-82.5'],
            ['53.68', '15.63', '-82.5'],
            ['54.38', '16.42', '-82.5'],
            ['54.78', '16.88', '-82.5'],
            ['55.63', '17.9', '-82.5'],
            ['55.8', '18.13', '-82.5'],
            ['56.7', '19.38', '-82.5'],
            ['56.88', '19.64', '-82.5'],
            ['57.5', '20.63', '-82.5'],
            ['58.13', '21.81', '-82.5'],
            ['58.16', '21.88', '-82.5'],
            ['58.63', '23.13', '-82.5'],
            ['59.05', '24.38', '-82.5'],
            ['59.35', '25.63', '-82.5'],
            ['59.38', '25.78', '-82.5'],
            ['59.57', '26.88', '-82.5'],
            ['59.74', '28.13', '-82.5'],
            ['59.84', '29.38', '-82.5'],
            ['59.89', '30.63', '-82.5'],
            ['59.95', '31.88', '-82.5'],
            ['59.95', '33.13', '-82.5'],
            ['59.95', '34.38', '-82.5'],
            ['59.95', '35.63', '-82.5'],
            ['60.0', '36.88', '-82.5'],
            ['60.0', '38.13', '-82.5'],
            ['60.05', '39.38', '-82.5'],
            ['60.11', '40.63', '-82.5'],
            ['60.16', '41.88', '-82.5'],
            ['60.27', '43.13', '-82.5'],
            ['60.38', '44.38', '-82.5'],
            ['60.49', '45.63', '-82.5'],
            ['60.6', '46.88', '-82.5'],
            ['60.63', '47.19', '-82.5'],
            ['60.71', '48.13', '-82.5'],
            ['60.82', '49.38', '-82.5'],
            ['60.92', '50.63', '-82.5'],
            ['60.98', '51.88', '-82.5'],
            ['60.98', '53.13', '-82.5'],
            ['60.98', '54.38', '-82.5'],
            ['60.92', '55.63', '-82.5'],
            ['60.82', '56.88', '-82.5'],
            ['60.71', '58.13', '-82.5'],
            ['60.63', '59.06', '-82.5'],
            ['60.6', '59.38', '-82.5'],
            ['60.43', '60.63', '-82.5'],
            ['60.2', '61.88', '-82.5'],
            ['59.97', '63.13', '-82.5'],
            ['59.69', '64.38', '-82.5'],
            ['59.38', '65.52', '-82.5'],
            ['59.35', '65.63', '-82.5'],
            ['58.99', '66.88', '-82.5'],
            ['58.51', '68.13', '-82.5'],
            ['58.13', '69.03', '-82.5'],
            ['57.98', '69.38', '-82.5'],
            ['57.37', '70.63', '-82.5'],
            ['56.88', '71.48', '-82.5'],
            ['56.65', '71.88', '-82.5'],
            ['55.86', '73.13', '-82.5'],
            ['55.63', '73.46', '-82.5'],
            ['54.97', '74.38', '-82.5'],
            ['54.38', '75.13', '-82.5'],
            ['53.97', '75.63', '-82.5'],
            ['53.13', '76.65', '-82.5'],
            ['52.93', '76.88', '-82.5'],
            ['51.88', '78.0', '-82.5'],
            ['51.76', '78.13', '-82.5'],
            ['50.63', '79.26', '-82.5'],
            ['50.51', '79.38', '-82.5'],
            ['49.38', '80.51', '-82.5'],
            ['49.26', '80.63', '-82.5'],
            ['48.13', '81.76', '-82.5'],
            ['48.01', '81.88', '-82.5'],
            ['46.88', '83.01', '-82.5'],
            ['46.76', '83.13', '-82.5'],
          ]
How do I create a polydata from these world coordinates

**Comment by jourdain** [comment]
```
const coords = new Float32Array(data.length * 3);
let index = 0;
data.forEach(([x,y,z]) => {
   coords[index++] = x;
   coords[index++] = y;
   coords[index++] = z;
});

const pointIndex = new Uint16Array(6 * 4 + 6);
index = 0;
pts.forEach((pointIndexArray) => {
  pointIndex[index++] = pointIndexArray.length;
  for (let i = 0; i < pointIndexArray.length; i++) {
      pointIndex[index++] = pointIndexArray[i];
  }
});

const scalars = new Float64Array(data.length);

const polydata = vtkPolyData.newInstance();
polydata.getPoints().setData(coords, 3);
polydata.getPolys().setData(pointIndex);
polydata.getPointData().setScalars(
    vtkDataArray.newInstance({ name: 'scalars', values: scalars })
);

```

**Comment by jourdain** [comment]
You can see the same thing happening [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Sources/ConeSource/index.js#L71-L73).
