### ISSUE TITLE
VR example not working properly?!

### ISSUE THREAD

**Issue by tomrobin-teschner** [Kitware/vtk-js#1462]
The VR example on the vtk.js homepage (https://kitware.github.io/vtk-js/examples/VR.html) does not seem to work for mobile devices. I am able to see the Cone on screen (not in VR mode), but when I click "send to VR", I get a split screen and pretty much empty space. There is some artefact that shows up (see picture attached) but it is certainly not the cone. Also, the back arrow and settings cog don't seem to work.
I have tried chrome, firefox and the native Android browser on a Samsung S10, as well as chrome on the Samsung S9 and iPhone 7 with the same result (nothing visible and unresponsive back arrow / settings cog).
Any ideas what could be the issue?

![Screenshot_20200520-204238_Chrome](https://user-images.githubusercontent.com/37083588/82497212-cdd99b00-9ae5-11ea-8952-cb280ba0e386.jpg)

**Comment by jourdain** [comment]
On phone we use a VR Polyfill which do that split eye view. But I'm not sure how well we set the physical space position and so on. If you have WebVR enabled via an HTC Vive or else, then you get "real" VR. 

Thanks for reporting the issue.

**Comment by tomrobin-teschner** [comment]
That was my first thought as well (positioning in space could be the problem). Maybe the camera just needs repositioning? I will try with my HTC vive headset once I have access to my workstation again, thanks for pointing that out.

**Comment by floryst** [comment]
If this is still an issue, please re-open.

**Comment by Sebas20oo** [comment]
https://github.com/Kitware/vtk-js/issues/3124
