### ISSUE TITLE
use InteractorStyleManipulator to create a manipulator for rotate volume render

### ISSUE THREAD

**Issue by RexingRui** [Kitware/vtk-js#1463]
Hi, I create InteractorStyleManipulator like this:
```
const iStyle = vtkInteractorStyleManipulator.newInstance();
const manipulator =  vtkMouseCameraTrackballRotateManipulator.newIntance();
manipulator.setButton(1);
iStyle.addMouseManipulator(manipulator);
iStyle.addGestureManipulator(vtkGestureCameraManipulator.newInstance());
```
Then, I rotate the volume, the action is not like exmple http://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html and also not like InteractorStyleTrackballCamera's action。it does not follow mouse. why,  should I set some camera parameters ?

**Comment by jourdain** [comment]
Could you describe the issue rather than saying it is different?

Is it possible that the center of rotation is not properly set and the rotation looks weird because it rotates around the volume corner?

**Comment by RexingRui** [comment]
@jourdain 
when I load data, 
![1](https://user-images.githubusercontent.com/35950219/82543588-5f004e80-9b86-11ea-8f0a-85eef9e28d2b.PNG)
then I rotate volume renderer
![2](https://user-images.githubusercontent.com/35950219/82543645-77706900-9b86-11ea-8528-416ed94041a6.PNG)
it offset the center, what I want to get  like this:
![3](https://user-images.githubusercontent.com/35950219/82543730-9969eb80-9b86-11ea-86b7-cf82a30b9386.PNG)

**Comment by jourdain** [comment]
Yes, my assumption was right, you need to set the center of rotation on your `iStyle` to be the center of your volume bounds. One way to do that is to call `resetCamera()` and use the `camera.getFocalPoint()` like that ` iStyle.setCenterOfRotation(focalPoint)`.

**Comment by RexingRui** [comment]
thanks @jourdain , I use you method to try and it is normal;
