### ISSUE TITLE
How to set vtk.js so that the image is not true after zooming in?

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1464]
![2](https://user-images.githubusercontent.com/24466497/82544517-cf5b9f80-9b87-11ea-9f9b-088eeb60e2c0.png)
![1](https://user-images.githubusercontent.com/24466497/82544519-cff43600-9b87-11ea-9a92-4b2dfa070ebc.png)

I built a solid with many faces, but when I zoom in, I see many faces. How can I make the image as clear as a small one when I zoom in? think you 

this is my code:
  const surfaceMapper = vtkMapper.newInstance();
  const surfaceActor = vtkActor.newInstance();
  surfaceMapper.setInputData(contours);
  surfaceActor.setMapper(surfaceMapper);
  surfaceActor.getProperty().setColor(...color);
  surfaceActor.getProperty().setAmbient(1);
  surfaceActor.getProperty().setDiffuse(0);
  surfaceActor.getProperty().setRepresentation(2);
  surfaceActor.getProperty().setOpacity(0.05);
  surfaceActor.setScale(...spacing);

**Comment by jourdain** [comment]
It seems that your polydata is using lines rather than polys (triangles/quad/...)

**Comment by huatianyu** [comment]
> It seems that your polydata is using lines rather than polys (triangles/quad/...)

sorry ，this is polydata,but it's still not clear enough
![3](https://user-images.githubusercontent.com/24466497/82546094-2ebaaf00-9b8a-11ea-8915-8e305f27a04a.png)

**Comment by jourdain** [comment]
If you remove the opacity change so it appear fully opaque?

**Comment by huatianyu** [comment]
It doesn't seem to be a transparency issue, I don't want t
![d8878bdcf777dc080dc9cb316285574](https://user-images.githubusercontent.com/24466497/82546714-21ea8b00-9b8b-11ea-8ce2-6493cd6c8d09.png)
o see a straight face spacing

**Comment by jourdain** [comment]
I believe the issue is in your data. Try to load it in ParaView to see what your data looks like.

**Comment by huatianyu** [comment]
Yes, my data is just a lot of contour coordinates. How to use vtk.js to reconstruct from multiple two-dimensional contour lines? I see that C++ has this kind of similar implementation.(https://blog.csdn.net/u013339596/article/details/19167037)
This is tow of the Outlines
    data :{
 "line1": [
          [-9.37, 79.05, 61.5],
          [-8.12, 78.66, 61.5],
          [-6.87, 78.28, 61.5],
          [-5.62, 78.22, 61.5],
          [-4.37, 78.19, 61.5],
       ...........
        ]
 "line2":   [-11.87, 86.8, 64.5],
          [-10.62, 86.48, 64.5],
          [-9.37, 86.38, 64.5],
          [-8.12, 86.07, 64.5],
          [-6.87, 86.05, 64.5],
          [-5.62, 86.05, 64.5],
      .........
}

**Comment by jourdain** [comment]
If you know the ordering, you can stitch the contours together to create quad or triangles rather than line. Otherwise, vtk is just rendering the geometry you defined properly.

Not a bug.
