### ISSUE TITLE
I have seen this on the official website of vtk.js. Is this the coverage of the C++ version of VTK?

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1469]
![a64a57a1b9dd483d36701b9de5ee781](https://user-images.githubusercontent.com/24466497/82885102-42458b80-9f77-11ea-8c12-3a2f6372304f.png)

**Comment by jourdain** [comment]
No, this is the code coverage when running the tests. How much JS code is currently covered by our JS tests.
