### ISSUE TITLE
Setting Color

### ISSUE THREAD

**Issue by lokesh2909** [Kitware/vtk-js#1472]
What is the exact code to set color, opacity for an actor?

**Comment by jourdain** [comment]
```
actor.getProperty().setColor(1.0, 0.5, 0);
actor.getProperty().setOpacity(0.5);
```

Beware that vtk.js does not have a proper depth peeling implementation (at the moment) and artifacts can occur when having some transparent objects that are not volume rendered.

**Comment by lokesh2909** [comment]
When am i supposed to use setProperty and getProperty

**Comment by jourdain** [comment]
If you want several actors to share the exact same property objet.

```
const props = actor1.getProperty();

actor2.setProperty(props);
actor3.setProperty(props);
```

**Comment by lokesh2909** [comment]
Thanks
