### ISSUE TITLE
change Volume Render brightness

### ISSUE THREAD

**Issue by RexingRui** [Kitware/vtk-js#1474]
hi @jourdain , is any api that can change volume render birghtness, not opacity.

**Comment by jourdain** [comment]
I think if you increase the [ambient](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/VolumeProperty/index.js#L295) value of the VolumeProperty, that might do what you are looking for.

**Comment by RexingRui** [comment]
Thanks for you reply @jourdain . Sorry and maybe I do not descript issue clear. when I use MIP， I want to adjust intensity by change window width / level(I defined a manuiplator for this). just like setWindowLevel or setWindowWidth to change image data map.
![MIP](https://user-images.githubusercontent.com/35950219/83584288-437b4780-a579-11ea-824e-e81a454c3faf.gif)

**Comment by jourdain** [comment]
I see, then you just need to adjust the lookup table range so the white and the black values get defined for a different set of scalar values.

Maybe @thewtex or @agirault can provide an explanation that is more aligned with your "medical" expectation.

**Comment by agirault** [comment]
You'll want to adjust the `ScalarOpacity` on the `VolumeProperty`, using a `PieceWiseFunction` as shown [here](https://kitware.github.io/vtk-js/api/Rendering_Core_VolumeProperty.html).

Look [here in `itk-vtk-viewer`](https://github.com/Kitware/itk-vtk-viewer/blob/82aa01a4bd4de292da9d2f865571c9875df58e6a/src/UserInterface/Image/createTransferFunctionWidget.js#L251-L295) for an example of how the `PieceWiseFunction` (within the `PiecewiseGaussianWidget`) is defined using window width/level values. You can find a demo [here](https://kitware.github.io/itk-vtk-viewer/app/).

Hth

**Comment by RexingRui** [comment]
Last few days, I can not visit github website. So I did not reply immediately.  I will use your methods to try; Thanks @agirault and @jourdain .

**Comment by floryst** [comment]
If this is still an issue, please re-open.
