### ISSUE TITLE
Rotating a 3d model

### ISSUE THREAD

**Issue by lokesh2909** [Kitware/vtk-js#1476]
How am i supposed to rotate a 3d model. Is it using the prop3d api? If so am I supposed to map it with an actor. A little sample code would be of great help??

**Comment by floryst** [comment]
If you want to transform your vtkPolyData, you will need to transform your points (and any normals in your data). You can access your array of points via `polyData.getPoints().getData()`, and then you can use `vtkMatrixBuilder` to do the transforms. Something like this (untested):
```
vtkMatrixBuilder.buildFromRadian().rotateX(Math.PI/2).apply(polyData.getPoints().getData();
```

If your polydata has normals or other orientation-dependent data in `pd.getPointData()`, then you would probably want to transform those as well.

**Comment by lokesh2909** [comment]
Thanks one more question, What is the exact code to clip the polydata and render the remaining of the polydata to the scene. I am using a .vtp file

**Comment by floryst** [comment]
If you want to do a clipping/cropping, you'll have to write a filter for that (similar to vtkClipPolyData). Approach-wise, you will need to intersect your clipping plane with your model, generate your intersections, then discard all geometry on one side of the plane.

**Comment by lokesh2909** [comment]
I am using Django in the backend, and Vtk.js in the front end. I am using polydata reader and trying to read the polydata but it says no input instead of rendering. Can I know the exact code to render a polydata using vtkpolydata reader? Few Questions?

1. How am I supposed to send the polydata if I am not serving it as a file? Am I supposed to send it as a json response, xml or what?

2. What encoding should be used while sending data from backend? Though the vtk.js says it supports binary, ascii and another encoding in VtkXMLPolydataReader. It actually supported only ascii encoding

**Comment by jourdain** [comment]
Why don't you send it as a file?

**Comment by lokesh2909** [comment]
I tried but still ascii is working and not binary, May be i have made a mistake somewhere. But now I am stuck in rendering the polydata. Let's say I have polydata stored in a variable. what am i supposed to do? How to send it to the frontend which is vtk.js?

**Comment by jourdain** [comment]
Where is your code? That [example](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) is doing exactly that and it is working.

**Comment by lokesh2909** [comment]
Thanks
