### ISSUE TITLE
Interact with Models in the Scene

### ISSUE THREAD

**Issue by lokesh2909** [Kitware/vtk-js#1485]
How to interact with the objects in the scene. For example, how to place a small dot/ sphere on a object which already exists in the scene

**Comment by floryst** [comment]
You can use CellPicker to pick out surfaces in your scene. Check out the [CellPicker example](https://kitware.github.io/vtk-js/examples/CellPicker.html). Right click on the cone to place green spheres on the cone's surface.

**Comment by lokesh2909** [comment]
How to restrict the surface only to the object in the scene rather than empty space. For eg, in the cell picker example how to restrict the cells only to the surface of the cone and not in the empty grey area

**Comment by floryst** [comment]
In that example, the if block `if (picker.getActors().length === 0) {` is the case where no surface was picked. Just remove that block of code.

**Comment by lokesh2909** [comment]
Great. It worked, thanks. Is there any option to move the picked cells. Let's say I place a sphere on the object in the scene. Now When i click on it and drag, is there any function that's makes it move?

**Comment by floryst** [comment]
That can be a bit more complicated. One way is to turn this into a widget (check out the vtk.js widget examples). vtk.js currently does not have any default widget manipulators that keep a point on a model surface, but you can write one yourself; look at vtkPlaneManipulator for an example of keeping objects on the plane. In fact, most widgets use vtkPlaneManipulator to keep points on the view plane at the camera focal point.

**Comment by lokesh2909** [comment]
Thanks for the help let me try to use it and see.
