### ISSUE TITLE
Assign handle to a point in the scene

### ISSUE THREAD

**Issue by gaston-perret** [Kitware/vtk-js#1486]
This is a fantastic library thank you!

I have a script that picks vertices of a vtp mesh, modifies them and renders the result. I would like to make that modification dynamically with mouse interaction, not programmatically. I think the handle widgets could give me that functionality but I don't understand how I can add handle functionality to an actor in the scene. 
Is it possible to bind a handle to a vertex?

Also, the PointPicker tool I use to pick vertices has a big distance tolerance for picking, I can pick points from far away the mesh and I would like to make it more precise, can I modify that distance tolerance?

**Comment by floryst** [comment]
Yep, you should be able to use widgets for this. Check out [PolyLineWidget](https://kitware.github.io/vtk-js/examples/PolyLineWidget.html) for an example. Of course, you would want to pre-populate the points in the widget state for your mesh.

As for PointPicker, you can use `picker.setTolerance(value)`. The default is 0.025.

**Comment by eltopo22** [comment]
Hi. Sorry to reopen this. @floryst could you give me some info about "prepopulate the points in the widget state". I'm thinking of setting the origins of each handle like this:
```
publicAPI.createHandle = (origin) => {
     const newHandle = model.widgetState.addHandle();
    newHandle.setOrigin(...origin);
```

Where origin would be each point of my VTP source

```
const source = vtpReader.getOutputData(0);
actor.setMapper(mapper);
mapper.setInputData(source);
renderer.addActor(actor);
```
Then I would use the getMoveHandle() method to handle the movement of the widget
Is this the proper way? Would something like this link the source points to the handle widgets?
Thank you

**Comment by floryst** [comment]
At a high level, that looks like a good approach. This however will not link the source points to the handle widgets.

What you can do is sync the vertices and the handle positions. One way to do this is as follows:
- initial step: create handles located at each of your mesh's vertices
- listen to `widgetState.onModified(...)`
- When the state is updated, loop through the handle list (`getHandleList()` I think) and re-create the array that stores the vertices
- Update your mesh polydata with the new vertices array, and update your rendering
