### ISSUE TITLE
Overlay ViewPort Interaction

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1487]
Hello, I have a scene with 2 viewports:
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/18531147/84658239-e2a72400-af15-11ea-876c-8c215a198e72.gif)

However I'd like to be able to interact only with the upper left viewport when the mouse is on it.
Is it possible?

If needed, the link for the synchronizable scene is here :
https://drive.google.com/file/d/1SgWOJBR6qYVlU6AujDxPE3ZyVMIYqicF/view?usp=sharing

**Comment by jourdain** [comment]
It could be, but we need 2 camera (1 per renderer) and make sure the serializer don't make other assumptions.

**Comment by xavArtley** [comment]
In the example I presented there is already one camera by render:
![image](https://user-images.githubusercontent.com/18531147/84766825-b9e46480-afd1-11ea-973a-2fe06ea4cf68.png)

**Comment by jourdain** [comment]
Oh, that is good news. I thought it was related to missing interactor style. 

Maybe the issue could be solved by changing which renderer is in front of the other one when they overlap.

**Comment by xavArtley** [comment]
the upper left corner renderer is already above the full size one
If I invert the order of renderers the upper left renderer is hidden

**Comment by jourdain** [comment]
It should be related to the pokeRenderer logic I believe which shouldn't be too bad.

**Comment by martinken** [comment]
Have to get some other stuff done for a bit.

**Comment by jourdain** [comment]
@xavArtley if you want to take a stab at it, the relevant part is [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js#L677-L693)

**Comment by xavArtley** [comment]
Ok I'll try to look at it when I have more time

**Comment by xavArtley** [comment]
personally i would be tempted to add just a break after the first currentRenderer found [here](https://github.com/Kitware/vtk-js/blob/22afe9744888b9ec2366faf05936e51d9ad504cd/Sources/Rendering/Core/RenderWindowInteractor/index.js#L679)
