### ISSUE TITLE
How read vtkUnstructuredGrid (.vtu) without convert it in .vtp (and lost internal area) ?

### ISSUE THREAD

**Issue by felixMHub** [Kitware/vtk-js#1488]
HI, 
I’m developing a web app using vtkjs, but I need to work with vtkUnstructuredGrid data. I’ve already tried the readers available in vtkjs repo, but they seems don’t work. Can someone help me ?

**Comment by Timanu05** [comment]
I tried to do the same thing and you might want to look into itk.js for this feature.

**Comment by thewtex** [comment]
To generate the vtk.js PolyData for rendering:

```
import vtk from 'vtk.js/Sources/vtk'
// This is for File objects.  Use readPolyDataArrayBuffer for ArrayBuffer's
import readPolyDataFile from 'itk/readPolyDataFile'

[...]

const { polyData, webWorker } =  await readPolyDataFile(null, myFile)
webWorker.terminate()
const polyDataInstance = vtk(polyData)

// render polyDataInstance
```

**Comment by thewtex** [comment]
Example:

https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://data.kitware.com/api/v1/file/5a1c85318d777f7ddd99ab91/download/overlapping.vtu

**Comment by jourdain** [comment]
vtk.js mostly focus on rendering and therefore all 3d cell processing is not supported unless you involve WebAssembly of VTK/C++ or ITK.js. Closing for now.

**Comment by sridhar-mani** [comment]
> To generate the vtk.js PolyData for rendering:
> 
> ```
> import vtk from 'vtk.js/Sources/vtk'
> // This is for File objects.  Use readPolyDataArrayBuffer for ArrayBuffer's
> import readPolyDataFile from 'itk/readPolyDataFile'
> 
> [...]
> 
> const { polyData, webWorker } =  await readPolyDataFile(null, myFile)
> webWorker.terminate()
> const polyDataInstance = vtk(polyData)
> 
> // render polyDataInstance
> ```

can this read vtu file or only vtp file

**Comment by sridhar-mani** [comment]
i was trying to the VTK leagacy reader and got that its not a function.
