### ISSUE TITLE
[Feature Request] vtkFollower

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1491]
Hello, one of our [panel](https://github.com/holoviz/panel/issues/1412) user would like to use a `vtkFollower`, I think it can be an intersting feature for various `vtk.js` users so I open an issue here.
vtkFollower :
"vtkFollower is a subclass of vtkActor that always follows its specified camera. More specifically it will not change its position or scale, but it will continually update its orientation so that it is right side up and facing the camera."

**Comment by jourdain** [comment]
@martinken what do you think?

**Comment by martinken** [comment]
Yes, certainly a useful class.

**Comment by xavArtley** [comment]
Thx @martinken

**Comment by GilShoshan94** [comment]
Thank you so much ! @martinken  @jourdain  @xavArtley
