### ISSUE TITLE
handling Rescale Intercept / Slope / Type

### ISSUE THREAD

**Issue by GreyFoxRU** [Kitware/vtk-js#1494]
Hello, tell me please, is it possible to specify the values ​​of Rescale Intercept / Slope / Type for the correct rendering of a dicom image? 
I get the image data using the capabilities of cornerstone, then set the values ​​in vtk.js,  

```typescript
    volumeMapper.setInputData(data)
```

but the rendered image looks very bright, 
I thought that there simply wasn’t enough setting window level values, but when setting values ​​obtained from cornerstone (window width window center)

```typescript

        const window = 400; // cornerstone image.windowWidth = 400
        const center = 40; // cornerstone image.windowCenter = 40

        const mappingRangeLower = center - window / 2;
        const mappingRangeUpper = center + window / 2;

        volumeActor.getProperty()
          .getRGBTransferFunction(0)
          .setMappingRange(mappingRangeLower, mappingRangeUpper);

```

the picture is still not drawn correctly.  

I thought maybe the values ​​of Rescale Intercept / Slope / Type are not set or not taken into account, or maybe I'm missing something. Please help resolve the issue.
![vtk](https://user-images.githubusercontent.com/48510330/84760936-670aad00-afd1-11ea-8b83-f93f06835daf.PNG)

**Comment by thewtex** [comment]
If the DICOM is read with [itk.js](https://insightsoftwareconsortium.github.io/itk-js/docs/index.html), rescale / slope will be taken into account. Then convert with [`convertItkToVtkImage`](https://kitware.github.io/vtk-js/api/Common_DataModel_ITKHelper.html) for rendering.

**Comment by GreyFoxRU** [comment]
@thewtex Hello, and thanks for the answer, but unfortunately in my case the use of ITK is not yet possible, my task now is to use the capabilities of the already connected libraries to achieve the correct image.

I found that VTK.js has the ability to use a lookup table, and I think my problem will be solved if I use it.
I have values ​​for the Lookup Table - Rescale Slope and Rescale Intercept, is there a way to generate a lookup table using vtk.js using these values? If not, what data type is supported for the lookup table? 

I'm not yet experienced in using the vtk.js library, so I hope someone can tell me how to properly use the lookup table with vtk.js

**Comment by aylward** [comment]
This is perhaps a bug in whatever DICOM reader is being used, and it should be reported to that library.   We recommend using ITK.js as noted by @thewtex .  It properly converts recorded DICOM values into CT hounsfield units that are the recorded CT values.  Such conversions are independent of the window/level settings used for display.
