### ISSUE TITLE
OrientationMarkerWidget,  pkg example does not work on Mac OS/Safari

### ISSUE THREAD

**Issue by meihuisu** [Kitware/vtk-js#1496]
The example under vtk.js/Sources/Interaction/Widgets/OrientationMarkerWidget/example/index.js
does not work on Mac OS/Safari but ran with on Mac OS/Chrome and Mac OS/firefox.

**Comment by jourdain** [comment]
Based on the description, the issue seems to be related to WebGL1 (don't work) vs WebGL 2 (work)

@martinken any idea?

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
