### ISSUE TITLE
Why mouse events don't work

### ISSUE THREAD

**Issue by wmxj** [Kitware/vtk-js#1498]
const istyle = vtkInteractorStyleMPRSlice.newInstance();
renderWindow.getInteractor().setInteractorStyle(istyle);
.........other code

istyle.removeAllMouseManipulators();

const manipulator = Manipulators.vtkMouseRangeManipulator.newInstance({
 button: 1,
scrollEnabled: true,
});

istyle.addMouseManipulator(manipulator);
					
//Not implemented
istyle.handleMouseMove(v => {
	console.log(v);
});
					
//Not implemented
istyle.handleLeftButtonPress(v => {
	console.log(v);
});

**Comment by floryst** [comment]
In order for your range manipulator to work, you need to add listeners to it. Check out the [MouseRangeManipulator example](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Manipulators/MouseRangeManipulator/example/index.js)

**Comment by wmxj** [comment]
tks for your rply.i mean click or move event.not only vtkMouseRangeManipulator's,maybe  vtkMouseCameraTrackballZoomManipulator
