### ISSUE TITLE
Black areas on model with setDiscretize and picking value/color on click/hover

### ISSUE THREAD

**Issue by Delyrah** [Kitware/vtk-js#1499]
Hi,

we tried to vizualize the attached VTP model with a modified version of the geometry viewer example which works great, but there are some black parts, which is only happening if **lookupTable.setDiscretize** is set to **true**.

`
  lookupTable.setDiscretize(true);
  lookupTable.setNumberOfValues(20);
`

![image](https://user-images.githubusercontent.com/33599024/84883565-f5923380-b090-11ea-894d-1812f7567aa2.png)

Colors:
![image](https://user-images.githubusercontent.com/33599024/84885274-18254c00-b093-11ea-98e9-fad05cab1ca5.png)

When discretize is disabled:
![image](https://user-images.githubusercontent.com/33599024/84885865-e95ba580-b093-11ea-831a-b926aef9acd5.png)

We can ensure that the values of the black areas are somewhere inside the min/max scalar range. (0 to around 800 for this example)
We even tried to set the below and above range colors but the black parts stayed. When discretize is disabled everything works.

While I was searching for the reason for the black areas I tried to come up with another solution to pick the colors or scalar values below the mouse cursor (by click or hover), I was trying to accomplish that by the PointPicker class, but I was unsuccessful. Is this possible somehow? This would be great for the final project aswell.

Source code (index.js) and model (rotor.vtp) attached.
[rotor.zip](https://github.com/Kitware/vtk-js/files/4791705/rotor.zip)

**Comment by Delyrah** [comment]
![image](https://user-images.githubusercontent.com/33599024/84885111-dd231880-b092-11ea-9bed-b7f3bcc5eb91.png)

**Comment by Delyrah** [comment]
More investigation on this matter:

```
console.log(lookupTable.mapValue(-100));
console.log(lookupTable.mapValue(0.10));
console.log(lookupTable.mapValue(10));
console.log(lookupTable.mapValue(100));
console.log(lookupTable.mapValue(200));
console.log(lookupTable.mapValue(400));
console.log(lookupTable.mapValue(600));
console.log(lookupTable.mapValue(900));
```
`mapValue(0.10)` and `mapValue(10)` returns `NaN`.

This has to happen somewhere here:
https://github.com/Kitware/vtk-js/blob/b50fd091cb9b5b65981bc7c64af45e8f2472d7a1/Sources/Rendering/Core/ColorTransferFunction/index.js#L500-L517

**Comment by jourdain** [comment]
Thanks for reporting that discretize issue. 
Do you think you could provide a fix via a Pull Request?

**Comment by Delyrah** [comment]
I assume, yes, but I'm not very experienced with pull requests.

By any chance, do you maybe know an answer to my other issue, picking the color or scalar value below the cursor?

**Comment by jourdain** [comment]
@martinken can we render the floating points to a back buffer and query it afterward, like we do for hardware selection except that in this case we will do it for scalar values?

**Comment by martinken** [comment]
You mean like a value pass? e.g. render scalar values to a float buffer. We could add that but it might be a bit of work. In VTK more typically we would use regular picking to get the cell or point and then query that cell or point for it's values. vtk.js does not have cell/point picking yet but that might also work.

**Comment by jourdain** [comment]
Yes I was thinking of value pass. For picking we have some available for ImageMapper as that one if fairly easy but I'm not sure about plain polydata. I think one of the issue with JS is that if we have big loops (over cells/points), it tends to be slow to actually find the right point or cell that was picked. That was one of the issue with the widget taken from the C++ implementation that was relaying on picking for finding which handle was getting grabbed. 

Anyhow, I was mostly curious to know if a value pass could be done and how fast/easy it could be added to vtk.js. I don't have the need just yet.

Thanks @martinken

**Comment by Delyrah** [comment]
My first assumption was incorrect, the problem was some lines further below.

https://github.com/Kitware/vtk-js/blob/b50fd091cb9b5b65981bc7c64af45e8f2472d7a1/Sources/Rendering/Core/ColorTransferFunction/index.js#L520

If "x" coming out of the discretize part is 0, the area stay black. Even a really small number (0.0000001) will solve the issue.
When the while condition part checking x is changed from ">" to ">=" everything works well.

`idx < numNodes && x >= model.nodes[idx].x`

Can you confirm this is a suitable solution for you? I am not aware of any side effects this could cause.


Regarding value picking: So there is no way currently to do this? Thats unfortunate. 
I found the ShapeWidget on the examples page (https://kitware.github.io/vtk-js/examples/ShapeWidget.html) which does something similar, so my thought was this is something that would be easily possible.

**Comment by jourdain** [comment]
The example that you looked at is using the vtkImageMapper and yes, with that mapper you can do quick and reliable picking. I think you can also do it on the geometry but it could be slow depending on the size of your geometry.

**Comment by RP-101** [comment]
I am also having the same issue with a random set of NaN - when splitting the data into 3 discrete color groups for scalar values between 0 and 0.99. I expect the following:
0 to c.0.33 = blue color
c0.33 to c0.66 = blue/yellow color
c0.66 to 1.0 = yellow
...however what I get is a series of NaN and then, grey, then the yellow color I am after. I am not sure if I am missing anything here - any help /pointers much appreciated. Thanks

```
// Console log reported from the below script.
Range of lookup table: 0,0.99
0=0,0,255,255
0.1=NaN,NaN,NaN,255
0.2=NaN,NaN,NaN,255
0.3=NaN,NaN,NaN,255
0.4=128,128,128,255
0.5=128,128,128,255
0.6=128,128,128,255
0.7=255,255,0,255
0.8=255,255,0,255
0.9=255,255,0,255
```

```javascript
// Get the polydata
_polydata = writerReader.getOutputData()
arrayName = _polydata.getPointData().getArrayName(0);
activeArray = _polydata.getPointData().getArrays()[0];
dataRange = activeArray.getRange()
console.log(dataRange)

var preset = vtk.Rendering.Core.vtkColorTransferFunction.vtkColorMaps.getPresetByName('blue2yellow');
lookupTable = vtk.Rendering.Core.vtkColorTransferFunction.newInstance();
lookupTable.setNumberOfValues(3)
lookupTable.setDiscretize(true)

lookupTable.applyColorMap(preset);
lookupTable.setVectorModeToMagnitude();
lookupTable.setMappingRange(dataRange[0], dataRange[1]);
lookupTable.updateRange();

// Print the color values to the console
console.log(`Range of lookup table: ${lookupTable.getRange()}`)
for (i = 0; i < 10; i++) {
    var myVal = Math.round(i*0.1*10)/10
  console.log(`${myVal}=${lookupTable.mapValue(myVal)}`)
}

mapper.setLookupTable(lookupTable);
mapper.setColorModeToMapScalars();
mapper.setInterpolateScalarsBeforeMapping(true);
mapper.setScalarModeToUsePointData();
mapper.setScalarVisibility(true);
// Assume scalar range is between 0 and 1 for now. This will be set dynamically with more complex example.
mapper.setScalarRange(dataRange[0], dataRange[1]);

const actor = vtk.Rendering.Core.vtkActor.newInstance();
actor.setMapper(mapper);
```

**Comment by RP-101** [comment]
Apologies - this issue has been resolved with the following [https://github.com/Kitware/vtk-js/commit/011f86f55197d6acb90dffa4862bcdd70896f484](url)

**Comment by daker** [comment]
@RP-101 or @jourdain can you close the issue?
