### ISSUE TITLE
CenterOfRotation vs FocalPoint

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/vtk-js#15]
It does not seem possible currently to have separate focal point from center of rotation.  This might be nice to have eventually.

**Comment by martinken** [comment]
Have you tried translating the focal point using <shift> left mouse?  That may do what you are shooting for.

**Comment by jourdain** [comment]
Actually, the issue that we are facing is that in ParaView, when you zoom, we basically move forward the focalPoint and cameraPosition while the centerOfRotation (a property on the view) remain the same.

So when exporting a scene from ParaView, we keep the same focal point which end up being the center of rotation in VTK.js which will mess up any initial interaction. In fact, we would like to keep the same center of rotation as ParaView. So we were thinking that if we could specify it along with the focal point that could solve the problem. Specially if we change the center of rotation on purpose in ParaView to be off-center.

**Comment by martinken** [comment]
OK, maybe better discussed offline as I'm not sure why PV is doing it the way it is :-)

**Comment by jourdain** [comment]
Sure sounds good. But the idea is that the Focal Point should not necessary be the center of rotation.

**Comment by martinken** [comment]
Why are you moving the focal point on a dolly in PV? Why not just the position?

**Comment by jourdain** [comment]
I agree for that part, that should not be the case. But if we pick the center of rotation to be somewhere else than the current focal point, we should be able to define that in a vtk-js scene.

**Comment by martinken** [comment]
Is there any interactor style in VTK that does this?

**Comment by jourdain** [comment]
I have no idea, but that must be the case, since ParaView is based on VTK.

**Comment by martinken** [comment]
OK, well, just have to put the same logic in the interactor style in JS, so it should be easy.

**Comment by jourdain** [comment]
See https://kitware.github.io/vtk-js/examples/Manipulators.html
