### ISSUE TITLE
mouseleave event triggers handleMouseUp in vtkRenderWindowInteractor

### ISSUE THREAD

**Issue by manjebrinkhuis** [Kitware/vtk-js#1502]
I'm rendering svg elements on top of my vtkjs viewport, and sometimes an svg-element appears at my cursor position, triggering a mouseleave event in `vtkRenderWindowInteractor` and in turn the `publicAPI.handleMouseUp` event in, which in my use-case, is undesired. 

I created an interactor class where I thought I could super the handleMouseUp method and check for the event type, like so,

```
const superHandleMouseUp = publicAPI.handleMouseUp;
publicAPI.handleMouseUp = (event) => {
  // check event.type
  superHandleMouseUp()
}
```

to skip running it for mouseleave events, but handleMouseUp is not available through publicAPI as it isn't listed in the `handledEvents` array in `vtkRenderWindowInteractor`.

What would be a good way to check for the event type of handleMouseUp?

**Comment by manjebrinkhuis** [comment]
Right now, commenting out the mouseleave line resolves the issue. Should this be considered a bug? It was originally added because button up/down events are not received outside of the window (https://github.com/Kitware/vtk-js/pull/869). 

Also, I'm a bit puzzled by why a mouseleave event is triggered in the first place (probably something specific in my code). It looks more like mouseout behavior.

**Comment by floryst** [comment]
This should be fixable by using `pointer-events: none` on the svg layer, though I want to make sure that we really don't want any interaction with the svg layer.

Can you try adding the CSS `svg { pointer-events: none; }` to your page to see if that works? If so, then it might be worth adding that during svg creation.

**Comment by manjebrinkhuis** [comment]
Thanks for the answer! Sorry for the late reply. I'm a little busy now, but I will check this soon. Sounds like a good solution.

**Comment by floryst** [comment]
@manjebrinkhuis Any update on this on your side?

**Comment by manjebrinkhuis** [comment]
Very sorry for the late reply --  this has escaped my attention! Actually, looking into this again, with a newer branch of vtk.js this problem has disappeared, also without the `pointer-events: none` added. Not sure if that was intentional, but many thanks for the work!

**Comment by floryst** [comment]
No problem, glad the latest version worked for you! I think it was the fix related to simultaneous button presses, so I'm glad that fixed this as well.
