### ISSUE TITLE
stl viewer problem on mobile web browser.

### ISSUE THREAD

**Issue by hwkim0325** [Kitware/vtk-js#1508]
I'm trying to develop stl-viewer using vtk-js.
vtk-js worked well on my PC or another PC.
But whenever I try to test my app on mobile circumstance,
the web browser refreshed or not working.
Actually I tried to test that on several devices such as android, ios, or tablet.
But only I can have reasonable result is PC webbrowser.
Is there anything I missed?

**Comment by jourdain** [comment]
What do you mean by reasonable result?
- Download time?
- Load time?
- Frame rate?
- Rendering quality?
- ???

**Comment by hwkim0325** [comment]
While loading the STL files on my renderer, the app was refreshed.
In my case, I loaded 6 STL files, but only the 4 files were loaded successfully.
The size of the STL files was 350mb, so I assume the mobile device does not afford to the size of the files.
Is that right?

**Comment by jourdain** [comment]
I see, it is probably limited by the amount of memory available on those devices and crash.

**Comment by hwkim0325** [comment]
Thanks for the comment!.
