### ISSUE TITLE
labelWidget is not working!

### ISSUE THREAD

**Issue by hwkim0325** [Kitware/vtk-js#1509]
labelWidget is not working properly at example.

**Comment by jourdain** [comment]
Could you explain what is not working?

When I tried that [example](https://kitware.github.io/vtk-js/examples/LabelWidget.html), things seems to work fine for me.

**Comment by xavArtley** [comment]
On windows 10 at least if pixel ratio is not one I encounter some issues
[image: ezgif.com-video-to-gif.gif]

**Comment by jourdain** [comment]
@luciemac

**Comment by finetjul** [comment]
Existing [LabelWidget ](https://github.com/Kitware/vtk-js/tree/master/Sources/Interaction/Widgets/LabelWidget)is obsolete. The new [Widget framework](https://kitware.github.io/vtk-js/docs/develop_widget.html) should be used.

**Comment by floryst** [comment]
Check out the [vtkPolyLineWidget](https://kitware.github.io/vtk-js/examples/PolyLineWidget.html) for a label example. That one should handle device pixel ratio correctly.

**Comment by hwkim0325** [comment]
Thanks for commenting,
And please check the example on a mobile web browser.
In my case, there was nothing related to the label text on an android browser.

**Comment by hwkim0325** [comment]
renderWindow.getInteractor().onRightButtonPress((callData) => {

var colorValue = hexToRgb(colorInput.value);

const clientX = callData.position.x;
const clientY = callData.position.y;
  const [width, height] = openGLRenderWindow.getSize();
  //const x = Math.round((width * clientX) / window.innerWidth);
  //const y = Math.round(height * (clientY / window.innerHeight));
  const x = clientX; const y = clientY;


This code worked well. Please try this code.

**Comment by floryst** [comment]
I've tested the linked PR on my phone, and it works, so that should also resolve your mobile issues. Let me know if it doesn't.
