### ISSUE TITLE
edge support

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/vtk-js#151]
vtk-js does not work in ms edge

**Comment by jourdain** [comment]
You may need to load a polyfill? 
Is the following example [here](https://kitware.github.io/vtk-js/examples/Cone/index.html) working or not?

**Comment by martinken** [comment]
I just visited the example page on edge (Windows 10 x64) and it worked for me.  There was a bug that caused edge to not work that was fixed last week some time. Maybe that is hitting you? Failing that what platform are you on?

**Comment by doczoidberg** [comment]
also win 10 x64. the strange thing is with opened developer tools it works but not without the tools open.

**Comment by martinken** [comment]
I found the issue.  Ala

http://stackoverflow.com/questions/7742781/why-does-javascript-only-work-after-opening-developer-tools-in

Basically the console object does not exist unless the dev tools are open. So any calls to it crash. We need to make sure we do not use console if it doesn't exist.

**Comment by jourdain** [comment]
@martinken we should replace all our console.xxx() calls to our vtk[Debug|Info|Error|Warn]Macro and make sure we guard those methods accordingly.

I can try to get a stab at it but it may only happen during the weekend unless you want to do it sooner. ;-)

**Comment by jourdain** [comment]
Should be fixed now. Could you confirm and close the issue if that's the case?

**Comment by doczoidberg** [comment]
it is rendered now but I found 2 other issues now.

1. rendering ist not correct. there are some polys of the cone transparent.
2. touch does not manipulate view. (this works on android, but not on my surface)

**Comment by martinken** [comment]
The missing triangles is a different issue I believe, although probably edge specific.  It is on my near term list to look at. I think it is probably a quick fix.

**Comment by martinken** [comment]
The missing triangles should be fixed now in master.

**Comment by martinken** [comment]
Touch events have to be turned on in edge ala

for touch API, you have to activate a flag on Edge : in the address bar, enter about:flags and press enter. In the section Touch, you can enable touch events with the corresponding dropdown

I just tested them on my surface and them seem to be working so I'm closing this one.
