### ISSUE TITLE
[Question] VTK-js speed 

### ISSUE THREAD

**Issue by giwl-21** [Kitware/vtk-js#1517]
Hello,

I am on a 2017 macbook air, and am working with VTKjs.  

The face from this [example](https://kitware.github.io/vtk-js/examples/ZipHttpReader.html) is extremely slow on my laptop.  I know its computing power is rather low, but I am building an app designed to run on devices similar to this.  

Does anybody have any suggestions about efficiency when it comes to rendering DICOM (CT-scan) files this way?

Thanks!

**Comment by jourdain** [comment]
Are you using Safari? Did you try it on Chrome/Firefox?
Mostly the speed will be dependent on your GPU.

In case of Safari, WebGL1 is used which provide an even slower path than a WebGL2.

**Comment by jourdain** [comment]
Also, make sure your dedicated GPU is used rather than the CPU integrated one.

**Comment by giwl-21** [comment]
I had one of my colleagues use it, and it worked much faster on his PC.  Its probably this mac's GPU.  Thanks!
