### ISSUE TITLE
An Issue related to the color of the line when wheeling.

### ISSUE THREAD

**Issue by hwkim0325** [Kitware/vtk-js#1518]
1 - [Initial line Color]
![image](https://user-images.githubusercontent.com/40055222/86336978-76ede680-bc8b-11ea-9bd7-2f22b9b7028e.png)

2 - [When I wheel back]
![image](https://user-images.githubusercontent.com/40055222/86337036-8bca7a00-bc8b-11ea-8dc5-37dd975629f3.png)

3 - [When I wheel front again]
![image](https://user-images.githubusercontent.com/40055222/86337064-9422b500-bc8b-11ea-855d-d268e16a1d1c.png)

I am trying to attach a memo to my object and connect the point with my memo.
However, When I use wheel, the color of the line was changed to the black color.

Here is my code using coordinate inctance.

const coordinate = vtk.Rendering.Core.vtkCoordinate.newInstance();
coordinate.setCoordinateSystemToDisplay();

const clicked_x = 50 ;   // px
const clicked_y = 150 ;   // px

const assigned_x = clicked_x * ( vtk_x / web_x );
const assigned_y = vtk_y - ( clicked_y * ( vtk_y / web_y));

coordinate.setValue(assigned_x, assigned_y, 0);
var memoPosition = coordinate.getComputedWorldValue(renderer);

const lineSource = vtk.Filters.Sources.vtkLineSource.newInstance({ resolution: 10, point1: memoPosition, point2: pointPosition});

Why this happening?

**Comment by jourdain** [comment]
Because of shading happening on the lines. You can fix that by changing the following set of properties:

```
actor.getProperty().set({
  ambient: 1.0, 
  diffuse: 0.0,
});
```

**Comment by hwkim0325** [comment]
It worked!! thanks a lot!
