### ISSUE TITLE
vtk.js mobile panning problem

### ISSUE THREAD

**Issue by 5dh15** [Kitware/vtk-js#1519]
Hi!
I’m doing web 3D-model viewer project now.
And I added the GestureCameraManipulator on my InteractorStyleManipulator.
What I wanted to see was to implement rotate, zoom and panning functions on mobile environment.
The rotate and zoom function’s performance is good.
But I don’t know the gesture about how to panning on mobile.
(I tried many gestures what I  can try)
I saw that the panning function is exist in the GestureCameraManipulator’s index.js file.
Can anyone tell me how to figure it out?
Or should I add something on my code?

**Comment by jourdain** [comment]
Can you share your code? What is the issue? Could you provide more informations?

**Comment by 5dh15** [comment]
> Can you share your code? What is the issue? Could you provide more informations?

The iuuse is I don't know how to panning the actor on mobile environment.
I heared that vtk.js is not supporting the other gesture on mobile environment, such as 2 finger drag, etc.
Is there any other default gesture involved in vtk.js to panning the actor?

I can rotate the actor by 1 finger touch/drag and zoom the actor by pinch.


Here is my code:

const interactorStyle = vtk.Interaction.Style.vtkInteractorStyleManipulator.newInstance();
const GestureCameraManipulator = vtk.Interaction.Manipulators.vtkGestureCameraManipulator;
interactorStyle.addGestureManipulator(GestureCameraManipulator);

**Comment by hwkim0325** [comment]
![image](https://user-images.githubusercontent.com/40055222/86424380-5cfce400-bd1d-11ea-8f86-166b36ca4741.png)
![image](https://user-images.githubusercontent.com/40055222/86424454-96355400-bd1d-11ea-943a-bd508f6ddf01.png)
![image](https://user-images.githubusercontent.com/40055222/86424467-9df4f880-bd1d-11ea-9cd6-7c9b71bba734.png)
and did not  appeared "pan" alert.

**Comment by floryst** [comment]
Check out PR #1542. It should resolve the pan issues.
