### ISSUE TITLE
About lookup table

### ISSUE THREAD

**Issue by hwkim0325** [Kitware/vtk-js#1521]
Our project is about to finish
Thus, please help our problem.
We have been developing STL viewer, so we use STL reader in vtk.js library.
In our project, we want to load STL files having different colors.
Therefore, we selected 10 colors to apply to our object.
However, if we load the STL data through the STL reader, we could not change the color of the objects by using
Actor.getProperty().setColor();
After searching for information, we knew that the STL file should use Lookup table to change the color.
Unfortunately, since I've never used Lookup table before, I don't know how to approach this kind of API.
Please tell me how to use the lookup table if we have color arrays
such as [[0,0.2,0.4],[1,0.9,0.3], .... ,[0.4,0,0]]
Looking forward to release our product using your library.
Besides, apologize for bothering you many times.

**Comment by jourdain** [comment]
`Actor.getProperty().setColor(0.1, 0.4, 1.0);` should work and should be the way to do it with STLReader. STL does not have any field and therefore can not be used with a LookupTable.

How did you configure your mapper?

**Comment by hwkim0325** [comment]
I don't know why the colors of the objects show the right color, but it did work!.
However, a few days ago, what we saw is only red or blue color if we did not set the scalarVisivility option.

**Comment by jourdain** [comment]
can you share some code snippet?

**Comment by hwkim0325** [comment]
I think it was my fault.
I didn't realize the value was inserted from 0 to 1 value.
Actually I  roughly inserted into the parameter with values of 0~255.
Besides, your example of interactorStyleManipulator did not work well in mobile( the pan ).
https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html
please check,
https://github.com/Kitware/vtk-js/issues/1519
