### ISSUE TITLE
Question: Loading VTK/VTI files within in-app variables for display

### ISSUE THREAD

**Issue by giwl-21** [Kitware/vtk-js#1522]
Hello, 

I am trying to figure out how to load a vtk/vti file blob into the viewer.  Is there a good way to do this?
I saw JSON Nucleo Reader, although I have little understanding of its usage, it seems like a good option.

Thanks!

**Comment by jourdain** [comment]
Just use the vtkXMLImageDataReader to take care of the `*.vti` file format.
For `*.vtk`, I'm not sure we have a vtkImageDataReader inside Source/IO/Legacy/

**Comment by jourdain** [comment]
Otherwise itk.js should have all those readers using the C++ implementation as WebAssembly modules.

**Comment by giwl-21** [comment]
Sorry, I'm sort of new to vtk and have never worked with the C++ version.
I'm pretty sure this won't work:
`// JS
vtkLoad(vtikBlob){
    const reader = vtkXMLImageDataReader.newInstance();
    /*
    preliminary configuration
    */
    reader.setUrl(vtiBlob).then(() => {/*function*/});
}
`
Is there a method for the vtkXMLImageDataReader object to directly read the blob? Or I could be sorely misunderstanding this.

**Comment by jourdain** [comment]
Code taken from [example](https://kitware.github.io/vtk-js/examples/VolumeViewer.html)

```
blob.arrayBuffer().then((buffer) => {
  const vtiReader = vtkXMLImageDataReader.newInstance();
  vtiReader.parseAsArrayBuffer(buffer);
  // ...
});
```

**Comment by giwl-21** [comment]
Alright, I will try this.  Thanks!
