### ISSUE TITLE
Render 2d image

### ISSUE THREAD

**Issue by fivegrant** [Kitware/vtk-js#1525]
I used ImageHelper.imageToImageData function for the image I want to render, but I don't know how to include ImageData in the rendering pipeline (since it doesn't seem to be a source or filter). Should I use a texture on a plane instead?

**Comment by jourdain** [comment]
If that is supposed to be a texture, you should use it as such

```
texture = vtkTexture.newInstance();
texture.setImage(img);

source = vtkPlaneSource.newInstance();
mapper = vtkMapper.newInstance();
actor = vtkActor.newInstance();

actor.setMapper(mapper);
mapper.setInputData(source);

actor.setTexture(texture); // might be addTexture

// [...]
renderer.addActor(actor);
```

I guess my question would be what do you plan to do with your image?

You could possibly look at it with an vtkImageMapper.

**Comment by fivegrant** [comment]
That works, thanks. I plan on rendering a series of images obtained from a camera feed by updating the texture

**Comment by jourdain** [comment]
What would be the refresh rate that you would expect of that texture? As such pipeline may not scale well for having a video stream inside a 3D scene.

**Comment by fivegrant** [comment]
Greater than 15 frames per second. Preferably, I would have overlayed the rendering window over the html element streaming the feed, but modifying the style of VTK window (changing the opacity of the background, aligning two windows, etc) didn't seem like an option

**Comment by jourdain** [comment]
If it is a flat overlay, that could be done. For the background color you can pass a 4th component which could make it totally transparent. For the window alignment, you could use some place holder in 3d to get the corners of your video screen and have some callback to get the (x,y) position of those points so you could place your movie accordingly with maybe some css based distortion assuming you are not running into some occlusion problem due to 2 totally independent layers.

See [vtkPixelSpaceCallbackMapper](https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html) for 3d to 2d coordinate mapping.

**Comment by fivegrant** [comment]
Thanks for your help!

**Comment by bernland** [comment]
> If that is supposed to be a texture, you should use it as such
> 
> ```
> texture = vtkTexture.newInstance();
> texture.setImage(img);
> 
> source = vtkPlaneSource.newInstance();
> mapper = vtkMapper.newInstance();
> actor = vtkActor.newInstance();
> 
> actor.setMapper(mapper);
> mapper.setInputData(source);
> 
> actor.setTexture(texture); // might be addTexture
> 
> // [...]
> renderer.addActor(actor);
> ```
> 
> I guess my question would be what do you plan to do with your image?
> 
> You could possibly look at it with an vtkImageMapper.

This works with vtkCubeSource and vtkPlaneSource, however, not with vtkCircleSource, vtkSphereSource, and vtkConcentricCylinderSource. What's the logic behind this?

**Comment by jourdain** [comment]
The mesh generated by `vtkCircleSource`, `vtkSphereSource`, and `vtkConcentricCylinderSource` don't have texture coordinates. That is why the texture don't get map to those. 

I would have thought the `vtkSphereSource` would have defined the tcoord.
