### ISSUE TITLE
Using large volumes in Vtk.js

### ISSUE THREAD

**Issue by PieterJanVR** [Kitware/vtk-js#1526]
I would like to create large volumes in Vtk.js so I can request new slices in different directions. For smaller volumes (< 2k images) I got this working. For large volumes however, I've reached the ArrayBuffer length limit in the browser.

The implementation I currently use, creates a vtkVolume from a vtkDataArray. The vtkDataArray in vtk.js uses native arrays from the specified datatype (in my case Int32Array). This means that when I try to create a vtkDataArray a volume of more than 2048 slices of 512 x 512 pixels, vtk tries to create an Int32Array of +536870912 elements. This translates in an ArrayBuffer of 2147483648 (536870912 * 4) elements which reaches the upper limits of the ArrayBuffer length in the browser.

This is the current code I use to create my volume:
```javascript
const slices = []; //My array of 512x512px slices with a length > 2048
const joinedSlicesData = new Int32Array(slices[0].width * slices[0].height * slices.length);
const scalars = vtkDataArray.newInstance({
    values: joinedSlicesData,
    numberOfComponents: 1,
    dataType: "Int32Array",
    name: "scalars"
});
```

Is there a way to create a vtkDataArray with an 'unlimited' amount of slices?

**Comment by jourdain** [comment]
You might have to create several volumes to overcome the system limitation.

**Comment by PieterJanVR** [comment]
Thanks for the quick response.

How would you implement your suggestion of multiple volumes?

The thing I currently do is create a vtkDataArray of my slices and use that to create a vtkImageData object which represents my volume.
Then when I need to resolve a slice request, I create a vtkImageReslicer and get the output data which represents my slice.

I'm new to the API, but would you know if there's a way to construct a vtkImageData object out of multiple vtkDataArrays?

**Comment by jourdain** [comment]
Just create many vtkImageData(vtkDataArray()) when you properly define the origin so they end up in space next to each other and add all of them to your renderer.

You will also need to have several vtkImageReslicer. I'm not sure if everything will work as expected but it could be worth a try.

**Comment by PieterJanVR** [comment]
That might just work indeed. It would however take some overhead time to stitch the result of the vtkImageReslicers back together.
Once I find more time I'll give that solution a try.

FYI: I've also been testing with creating my own "UnlimitedInt32Array" which makes use of ES6 Proxy to overload the array indexer [] and split the big volume array up in multiple arrays. However as expected is the performance way too slow. 😣

**Comment by mix3d** [comment]
Running into this same problem. Did the Multiple Volumes work for you? Was there a noticeable seam in the rendered result at all?

**Comment by pvrobays** [comment]
@mix3d No, I haven't had the time to implement this. 
For our use case creating different volumes would've been too slow anyway.

**Comment by mix3d** [comment]
Did you solve it any other way or just give up and move on?

**Comment by pvrobays** [comment]
We moved on in the end. We did however made an optimization by using UInt16Arrays instead of Uint32Arrays which doubled the limit of the ArrayBuffer's size.

**Comment by mix3d** [comment]
Interesting that that worked for you. We ended up switching from Int16Arrays to Float32Arrays because we found VTK was converting them under the hood anyways.  (Sources/Rendering/OpenGL/Texture/index.js?5805)

**Comment by mix3d** [comment]
Int16 (signed) would be our preferred data type, and would easily let us load the largest datasets we have, but the internal conversion to Float32 is greatly hindering our ability to load a single volume.

**Comment by mix3d** [comment]
@jourdain is there a reason why so many data types are disabled internally?
![image](https://user-images.githubusercontent.com/1474137/94300909-85f8d380-ff1e-11ea-88eb-a2c204df1ef4.png)

**Comment by martinken** [comment]
Those data types are not filterable. Meaning that WebGL 2 doesn't guarantee that the hardware can perform linear interpolation on those types. See https://webgl2fundamentals.org/webgl/lessons/webgl-data-textures.html specifically the column labeled "texture filterable".

If we allow those types then we would need to perform binlinear (or trilinear) interpolation in the fragment shader since we couldn't rely on the hardware providing it.

**Comment by mix3d** [comment]
@martinken Is there any way to attempt or check if hardware lerp is available before just falling back to the common denominator? If there's been talk in the ES world of adopting a Float16Array specifically for WebGL GPU interop for years, (https://esdiscuss.org/topic/float16array), is that assumption of non-guaranteed lerp outdated?

**Comment by martinken** [comment]
Float16 lerp is an extension and is typically available.  I think it is required for WebGL2.

**Comment by martinken** [comment]
So there is the data type that we provide to opengl (in the code above the two options are UCHAR and FLOAT)

and then there is the datatype that we tell OpenGL to use to actually store that data which can be found here
https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/RenderWindow/index.js#L537 where you will see we tell OpenGL to use half float

**Comment by mix3d** [comment]
But `Texture` can only be unsigned char or float, and in the case of float, it uses Float32Array, right? (https://github.com/Kitware/vtk-js/blob/44e75d9bb9d24a3b8a4f45cc72366451892eb07e/Sources/Rendering/OpenGL/Texture/index.js#L1079)
Do you have any other suggestions on not using 2x the RAM to store 16bit data?

**Comment by martinken** [comment]
That is correct. So there are a couple improvements that could be done with some work. 

1) 16 bit single component data can be stuffed into a RG8 texture with some extra JS code and then with some extra shader logic to combine the R and G back into a single value. Good memory footprint and leverages hardware interp. I think RG8 is required in WebGL2 but not 100% sure.

2) Update the JS code to store the data as Float16 before passing it to OpenGL where it will also be stored as Float16. I don't think ES6 has a Float16 native type so would need to use a lib to do some of this conversion probably.

Both of those might give us the ability to handle up to 2x larger volumes at the price of some code complexity. I guess it depends on where the memory limit is happening as for OpenGL both would still be 16bpp. But in JS the footprint could be half the size.

**Comment by mix3d** [comment]
Option 1 is something I just suggested in a Slack channel looking for validity feedback. RG8 is Lerpable according to the table you provided.

Option 2 refers to the lack of native Float16 support as I mentioned earlier in my link to esdiscuss.org, and most JS implementations seem to suffer from incorrect rounding or other performance related issues.

**Comment by mix3d** [comment]
Update as we've considered options: Splitting the volume into adjacent parts would not work, as there is not, to my knowledge, inter-volume interpolation, which is very much required when doing Maximum/Minimum Intensity Projection for slices of a volume. An NAMIC project started that work, but was very much limited in scope and would not provide the needed intensity projection calculations. https://projectweek.na-mic.org/PW33_2020_GranCanaria/Projects/VTKjsMultiVolumeRendering/

**Comment by mix3d** [comment]
> ... where the memory limit is happening ...
It's happening in JS world; it cannot allocate a float32Array larger than `2^29+1024`, or an int16Array larger than `2^30+2048`, generating `RangeError: Array buffer allocation failed` when exceeded.
