### ISSUE TITLE
Paraview Docker

### ISSUE THREAD

**Issue by lokesh2909** [Kitware/vtk-js#1528]
How to pull the docker image from paraview I followed this link https://hub.docker.com/r/kitware/paraview and tried to pull but it says the following error

Using default tag: latest
Error response from daemon: manifest for kitware/paraview:latest not found: manifest unknown: manifest unknown

**Comment by jourdain** [comment]
There is no tag `latest`. You need to pick one that is listed here: https://hub.docker.com/r/kitware/paraview/tags

For example: `kitware/paraview:pv-master-egl-py3`

**Comment by lokesh2909** [comment]
Thank you it works

**Comment by lokesh2909** [comment]
How to download the osmesa py3 version for the same paraview
