### ISSUE TITLE
Manipulators

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/vtk-js#153]
running the example: https://kitware.github.io/vtk-js/examples/Manipulators.html#Source

When changing a setting I get:
```
ReferenceError: vtkDebugMacro is not defined
 /vtk-js/examples/Manipulators/Manipulators.js:1
```

How can I activate zoom via mousewheel?

**Comment by jourdain** [comment]
Need to fix the example to have vtkDebugMacro defined but otherwise the code works.

**Comment by jourdain** [comment]
Once travis finished to build that should be fixed.

https://github.com/Kitware/vtk-js/pull/156/files
