### ISSUE TITLE
 when zooming with the mouse wheel, can a graph (for example, vtkCircleSource) only change its position without changing its size?

### ISSUE THREAD

**Issue by WebHero0544** [Kitware/vtk-js#1531]
Hello!Is it possible to achieve this requirement in VTK: when zooming with the mouse wheel, can a graph (for example, vtkCircleSource) only change its position without changing its size?I looked at a lot of the code, but I couldn't find any configuration or methods.

**Comment by WebHero0544** [comment]
I wanted to use the inverse of the current scaling matrix to define the user matrix for actor, but the matrix doesn't know where to get it

**Comment by jourdain** [comment]
You could render the circles on an SVG element based on their 3D position. That way, their size is not correlated with the size in the 3d world.

https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html

**Comment by WebHero0544** [comment]
So can't meet the demand, SVG or canvas 2 d will be covered in the canvas webgl above, and I also want to make 3 d graphics can not change with the zoom own size, only to change its position, don't know the VTK can not achieve such a demand, I try to get the current scaling matrix and the matrix inverse matrix to do something, but I don't know where to get

**Comment by WebHero0544** [comment]
In WebGL, points don't get bigger or smaller with scaling, and it's not clear whether lines or triangles can do this

**Comment by jourdain** [comment]
The matrix are handled at the camera level.

**Comment by WebHero0544** [comment]
I read the code, but I didn't understand it very well. I saw the projection matrix and the view matrix set in it, but I didn't see the model matrix. My previous understanding of the model matrix was that it was the product of the displacement, rotation and scaling matrices.

**Comment by finetjul** [comment]
See https://github.com/Kitware/vtk-js/pull/1530

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
