### ISSUE TITLE
How to merge MultiSliceImageMapper with VolumeViewer

### ISSUE THREAD

**Issue by domac7111** [Kitware/vtk-js#1532]
Hello!

I am interested in how to add functionality of MultiSliceImageMapper to VolumeViewer example, but the key is to leave VolumeViewer interactive functionality.

When i add code :

```
mport controlPanel from './controlPanel.html';

const fullScreenRenderWindow = vtkFullScreenRenderWindow.newInstance({
  background: [0, 0, 0],
});

```
to VolumeViewer whole screen goes dark and i can not upload my picture from my local disc.

**Comment by floryst** [comment]
You don't need any of the render window stuff from that example, only the mappers and actors. You will need to add the image slice code and image mapper code, and add the actors to the scene. Copying the entirety of the MultiSliceImageMapper won't work, since it itself is a self-contained example.

The reason you are seeing a dark screen is because fullScreenRenderWindow automatically mounts the canvas to the body tag, and since your background is (0,0,0), you get a black screen.

**Comment by domac7111** [comment]
> You don't need any of the render window stuff from that example, only the mappers and actors. You will need to add the image slice code and image mapper code, and add the actors to the scene. Copying the entirety of the MultiSliceImageMapper won't work, since it itself is a self-contained example.
> 
> The reason you are seeing a dark screen is because fullScreenRenderWindow automatically mounts the canvas to the body tag, and since your background is (0,0,0), you get a black screen.

Thank you for your answer, but i do not quite follow you.

i put up my code here:

https://codesandbox.io/s/multisliceinvolumerendering-814cd?file=/src/index.js

basically it is VolumeViewer code at the start and i placed MultiSliceImageMapper, then i commented all the stuff i think that need to be commented from your directions.

Until i added MultiSliceImage code VolumeViewer worked normal.

My question is should i remove imports also when adding a new code like this, and why is my screen full white at localhost and i can not upload any vtk images after commenting those lines. 

I placed comment at the start of MultiImageSlice code and at the end. Can you write me directions on how to use those image slice and image mapper code in my example?

**Comment by floryst** [comment]
Check this example code out: https://gist.github.com/floryst/928a35477d36478e2974468dd9e2b1f2

The relevant added lines are two imports and the `setupMultiSlice` function. Of course, there are no controls bound since I didn't add them, but hopefully the above is enough to get you started.

**Comment by domac7111** [comment]
Hey! You helped me a lot with this and thank you so much! Now, I added the controlPanel using import and using

`fullScreenRenderer.addController(controlPanel);`

Now my question is why it is not working when i move slices on the bar of control panel? I think i need function _UpdateColorWindow_ but when i copy it from MultiSliceImageMapper and replace `renderWindow.render(); `with `fullScreenRenderer.render();` I get the picture showing but in console it says error:

Uncaught ReferenceError: imageActorK is not defined
    at HTMLInputElement.eval

I got this for all others actors also, can you tell me why and how to find solution?

**Comment by floryst** [comment]
That's because the MultiSliceImageMapper example assumes that `imageActorK` (and all of the other actors) are global. Note that I have them local to the function `setupMultiSlice`, so of course the image actor variable isn't defined in the global scope.

As for updating the slices from the UI, you'll need the code [here](https://github.com/Kitware/vtk-js/blob/master/Examples/Volume/MultiSliceImageMapper/index.js#L92). Of course, you'll need to be cognizant of where your variables are and such, but once you get the slices working then window/level should follow easily.

**Comment by domac7111** [comment]
Thank you for your answer it was really helpful, i did that but the new problem is that slices I and J are going only from 0% then to 50% and then to 100% in the bar and in the image, while slice K maximum range of motion is to the middle of the picture in 3D, no matter how many slices i write in

`imageMapperJ.setJSlice(90);`

for each, can you explain to me where is the problem?

**Comment by floryst** [comment]
It sounds like the ranges on your sliders are not correctly set. Check to make sure your slider min/max corresponds to the axis bounds for I, J, and K.

As for color level/window issues, what do you mean they are updated? Check to see that you didn't bind both slicing and color level/window to the same slider.

**Comment by domac7111** [comment]
For color level and window issues, the problem is that i can change those values on the moving bar, but the change apply on the image only after moving I and J slice bars. What do you think the problem could be?

**Comment by floryst** [comment]
In your code for updating color window/level, you have `fullScreenRenderer.render()`. That should be `renderWindow.render`.

You should use the image extent for setting your min/max. In effect, you should have the following code to set your ranges: https://github.com/Kitware/vtk-js/blob/master/Examples/Volume/MultiSliceImageMapper/index.js#L74

**Comment by domac7111** [comment]
Can you check my code now, because when i change  `fullScreenRenderer.render()` to `renderWindow.render` it will not show image i load at all. And for setting min/max should i use code from line 74 to 79 or from line 74 to the line 105? Because when i add the code to the line 105 it says Declaration or statement expected at the part 

`
    ['.colorLevel', '.colorWindow'].forEach((selector) => {
      document.querySelector(selector).setAttribute('max', dataRange[1]);
      document.querySelector(selector).setAttribute('value', dataRange[1]);
    });
    document
      .querySelector('.colorLevel')
      .setAttribute('value', (dataRange[0] + dataRange[1]) / 2);
    updateColorLevel();
    updateColorWindow();
  });`

https://codesandbox.io/s/objective-banach-3ksl6?file=/src/index.js

I believe is not at the right place, but i can not find effects part as you suggested in the code.

**Comment by floryst** [comment]
First, you have an extra `});` at the end of the code you just pasted that you need to get rid of. Second, I think it'll be useful for you to revisit how your code is structured. For one, you have references to `imageActorI/J/K` in `function createViewer() {...}`, but you don't create those until you are in `setupMultislice()`. I would move all of the `updateColorLevel/Window()` and `updateSlice()` functions to `setupMultislice()`, and setup UI bindings there. Codesandbox is giving me lots of "...is not defined" in the problems tab at the bottom.

It won't suffice to just copy-and-paste this code, so I would recommend that you take some time to understand what each chunk of code does and how you want them to work together. You have all of the parts you need, which is great, and now you need to make sure you integrate the parts correctly.

**Comment by domac7111** [comment]
I did all you suggested, and it worked! Now i have a few more questions, i added the code here:

https://codesandbox.io/s/working-gb9sh?file=/src/index.js

I still have some error in codesandbox after clicking on browser and trying to add .vti file it says: 

TypeError
Cannot read property 'addEventListener' of null

But there is no problem locally and i do not know why is that problem here?

My question would be about css for controllers. I see that vtkVolumeController is taken from vtk.js/Sources/Interaction/UI/VolumeController, but when i download it locally and set top and left borders to bigger then 5px, it stays 5px and i do not know why? 

And another problem is when i start it locally i get a big navigation bar on the bottom because of some random words that are like going out from VolumeViewer controller and it can be clicked on to open it and close it, can you tell me why is that? I tried to put everything in codesandbox to be more easier to find the problem.

**Comment by floryst** [comment]
Codesandbox isn't importing `controlPanel.html` correctly. That is, it's not importing it as HTML, since the import is an empty object. I think codesandbox has some transformer you can use (or you can tell codesandbox to use parcel-js).

How are you setting the top and left borders for the vtkVolumeController?

Can you send a screenshot for your last issue? I'm not seeing it happen in the codesandbox.

**Comment by domac7111** [comment]
I revived and change some stuff in my code and this part works for now, the problem is that for the final part I should add PaintWidget functions so i can do segmentation of some parts. I believe I can leave slices J,K and I to go trough the picture but the problem is that i have 3D image and view, but PaintWidget works from 2D camera setup, do you have any advises or ideas how to make those two to work together because i am stuck now on this problem?

**Comment by floryst** [comment]
Right now the PaintWidget is mostly restricted to the 2D view by design, since painting is usually done in a 2D scenario. Painting in 3D is possible, but we don't have any logic for that yet. In fact, it could be a simple extension off of the existing paint widget. The only 2D aspect of the widget is the paint cursor I believe, so not constraining that to the camera direction but rather the paint surface normal would be the most ideal scenario.

**Comment by domac7111** [comment]
After all i decided to try and add the image in paint widget, on the same way it is added in volume viewer, because i believe that will be the quickest and easiest solution to my problem, and i do not have enough knowledge to do what you suggested. 

But when i add new .vti image the screen stays black and i get errors:

Cannot read property 'addEventListener' of null
Cannot read property 'setAttribute' of null

Can you please check out this code and suggest me solution? I think the problem now is that values for loader are mixed but i am really lost in the code. I pasted both of them and commented what i thought it was not needed.

https://codesandbox.io/s/newest-problem-kw7sy?file=/src/index.js:0-25401

**Comment by floryst** [comment]
Sounds like you have some querySelector that is returning null. I'd check to make sure you have your HTML in-place before any code does querySelector. In fact, I only see `querySelector(...) is null` when I click on your link. I'm not sure why codesandbox has differing output compared to when I run it vs what you report, but if you can also supply line numbers in the meantime then that would useful in helping you debug this.

I think it's time to also clean up a bit of your code. One suggestion is to wrap more code in functions, so you are less likely to have globals that can make code confusing to follow.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
