### ISSUE TITLE
Volume rendering issue with Safari

### ISSUE THREAD

**Issue by jcbuisson** [Kitware/vtk-js#1534]
Hi there,

I build a 3D viewer for CT-scan images. Everything works fine with Chrome (83) and Firefox (78), but on Safari (13) the image appears shredded: the main volumes are there, but locally everything is messed up

Here is a CodeSandbox which illustrates this problem (it downloads a 240Mo CT-scan .vti file, you may need to be patient)

[https://codesandbox.io/s/vtkjs-volume-rendering-i5vxz](https://codesandbox.io/s/vtkjs-volume-rendering-i5vxz)

Any idea?

<img width="533" alt="Capture d’écran 2020-07-16 à 10 31 52" src="https://user-images.githubusercontent.com/20263717/87648787-35ac0b00-c750-11ea-834b-8486ae796617.png">
<img width="416" alt="Capture d’écran 2020-07-16 à 10 35 51" src="https://user-images.githubusercontent.com/20263717/87648839-39d82880-c750-11ea-9f91-cfed2273a023.png">

**Comment by floryst** [comment]
My first guess is this may be a webgl vs webgl2 issue? Safari 13 doesn't enable webgl2 by default. If you enable webgl2 under Safari's "experimental features" in the developer menu, will that fix the rendering?

**Comment by jcbuisson** [comment]
No, I activated "Experimental features -> WebGL 2.0" and now there is no image at all, and the JS console if full of errors : "WebGL: INVALID_ENUM: texParameter: invalid parameter name" in front of instruction "renderWindow.render()"

**Comment by floryst** [comment]
@martinken Can you take a look? I don't have macOS for testing.

**Comment by jcbuisson** [comment]
There is nothing to show, the image is empty, probably because of the failure of `renderWindow.render()`

**Comment by martinken** [comment]
Does it fail on 13.10.0 ?

**Comment by martinken** [comment]
Without the experimental WebGL2

**Comment by jcbuisson** [comment]
I'll tell you as soon as my system upgrade is over (it seems to be the only way to get the last version of Safari)

**Comment by jcbuisson** [comment]
I updated MacOS & Safari to their latest versions, but the situation is the same: a shredded image by default, and no image at all with lots of errors "WebGL: INVALID_ENUM: texParameter: invalid parameter name" when I activate the (experimental) feature "WebGL2"
Here is a sandbox which illustrates the problem: https://codesandbox.io/s/vtkjs-volume-rendering-i5vxz

vtk.js with its companion library itk.js are more and more used to visualize medical imagery, and the medical world uses a lot MacOS and Safari

**Comment by martinken** [comment]
Did you also test it with the Webgl2 off?

**Comment by jcbuisson** [comment]
Yes, it gives a shredded image (but no errors in console)

**Comment by martinken** [comment]
Thanks, should be fixed in master now.
