### ISSUE TITLE
Rendering sampled data points 

### ISSUE THREAD

**Issue by Aditi96** [Kitware/vtk-js#1538]
Hi,
I have been trying to render a 1% sampled data of the Isabel hurricane dataset however I am unable to do so. The sampled dataset is a vtp file and is a XMLPolyData. Is there a problem of rendering because there are missing data points?? Here is the snippet I wrote to render sampled data. 
Thank you

    var arrayName = polydata.getPointData().getArrayName(0)
    var activeArray = polydata.getPointData().getArrays()[0]
    var dataRange = activeArray.getRange()

    const lookupTable = vtk.Rendering.Core.vtkColorTransferFunction.newInstance();
    lookupTable.setVectorModeToMagnitude();
    lookupTable.applyColorMap(vtk.Rendering.Core.vtkColorTransferFunction.vtkColorMaps.getPresetByName('Cool to Warm'));
    lookupTable.setMappingRange(dataRange[0],dataRange[1]);
    lookupTable.updateRange();

    const mapper = vtk.Rendering.Core.vtkMapper.newInstance();
    mapper.setInputData(polydata);
    mapper.setLookupTable(lookupTable);
    mapper.setColorByArrayName(arrayName);
    mapper.setColorModeToMapScalars();
    mapper.setInterpolateScalarsBeforeMapping();
    mapper.setScalarModeToUsePointFieldData();
    mapper.setScalarVisibility(true);
    mapper.setScalarRange(dataRange[0],dataRange[1]);

    actor.getProperty().setEdgeVisibility(true)
    actor.getProperty().setPointSize(5);
    actor.setMapper(mapper);

    renderer.addActor(actor);
    renderer.resetCamera();
    renderWindow.render();

Any help would be much appreciated.

**Comment by jourdain** [comment]
First does your vtp load with that [example](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) ?

**Comment by Aditi96** [comment]
Thank you for replying. 
No..I guess so. I am loading my data using a vtkXMLPolyDataReader. Something like this. I am not using the above example to load my data. 
reader.setUrl('./Data/isabel_p_25_hist_grad_rand_pymp_0.01.vtp', { loadData: true }).then(())

**Comment by jourdain** [comment]
Sure, but does that example works or fail with your data?

Once I know that then I can look at your code. Even if that line below seems weird

`polydata.getPointData().getArrayName(0)`

**Comment by Aditi96** [comment]
No it doesn't. I might have made a mistake though but as much as I tried it didn't work out.

**Comment by Aditi96** [comment]
Yeah I tried doing it in my local system as well and the example provided again it did not work. Not sure why though.

**Comment by jourdain** [comment]
That probably means that the vtp if not properly read by vtk.js. You can try to regenerate it using "binary+zlib".

**Comment by Aditi96** [comment]
I tried the same using a binary+zlib format. This doesn't work either.

**Comment by jourdain** [comment]
Are we talking about the example or your code? Right now, I want to make sure your data is correct before looking at any code.

I mean if the example does not work, that means your data is wrong. Unless it has no cell which means no error but nothing should show up.

**Comment by Aditi96** [comment]
I am talking about the data. I used the data in binary+zlib format in the geometry viewer. But nothing shows up. And yes there is no error either.

**Comment by jourdain** [comment]
Ok then, I bet that's because you have no vertex defined.

You could do the following to fix the issue in your code

```
const polydata = [...];
const nbPoints = polydata.getPoints().getNumberOfPoints();
const vertexValues = new Uint16Array(nbPoint + 1);
vertexValues[0] = nbPoints;
for (let i = 0;i < nbPoints; i++) {
  vertexValues[i+1] = 1;
}
polydata.getVerts().setData(vertexValues);
```

**Comment by Aditi96** [comment]
Ohh great. Thank you so much. It worked. Really appreciate it. And thanks for replying so fast.
