### ISSUE TITLE
React Vs Anguar

### ISSUE THREAD

**Issue by lokesh2909** [Kitware/vtk-js#1541]
Is vtk.js easy to interact/ combine with react or angular? Any thoughts or suggestions please!

**Comment by jourdain** [comment]
vtk.js is framework agnostic and therefore should work with anything. But since it is not written using TypeScript it will be more difficult to deal with it inside an Angular project. 

In general at Kitware we tend to prefer Vue.js or React than Angular.

Hope that helps!

**Comment by lokesh2909** [comment]
Thanks a lot !
