### ISSUE TITLE
ImageStream not compatible to vtk

### ISSUE THREAD

**Issue by knopkem** [Kitware/vtk-js#1543]
This might not be a bug, but I wonder the reason why a  paraview server is needed when using the ImageStream component, at least the sample doesn't work for me when using VTK with the vtk_server.py as described here: https://kitware.github.io/paraviewweb/examples/RemoteRenderer.html

The reason I ask is, that it seems that both paraviewweb and vtk.js use the same technology behind (wslink) and the paraview remote renderer sample is pretty much identical to vtk.js ImageStream.

What works for me:
* paraviewweb with vtk or paraview backend
* vtk.js with paraview backend

What doesn't work:
* vtk.js with vtk backend

The errors I get are responses from the server (vtkpython) that rpc calls are not registered (however the same are used when running with paraviewweb and indeed protocol.py registeres the calls it complains about. E.g.:

`code: -32601
data: "viewport.image.push.observer.add"
message: "Unregistered method called"`

We have a fair amount of vtk code that we would like to reuse and are not familiar with paraview. (I read that one can create a paraview plugin that contains the vtk code but I would like to avoid this as it will take quite some time and prefer to use directly vtk).
Any infos about this are appreciated. Thanks

**Comment by jourdain** [comment]
vtk.js does work with VTK server, you can see an example [here](https://github.com/Kitware/web-project-templates/tree/master/vue-vtkjs-pvw-template/server/vtkpython)

**Comment by knopkem** [comment]
Thanks for pointing me in the right direction. Indeed it works now with vtk which is a big help. I still have a hard time to create a simple vanilla-js sample out of the project template though, need to study vue and the project a bit more.

**Comment by jourdain** [comment]
You can do vanilla-js if you want but at least that template should give you the key elements that are required to get something working. Vue.js is definitely not required. Hope you will figure it out.

**Comment by knopkem** [comment]
Got a working example extracted from the vue.js sample. Maybe a help for others (or better: an example on the webpage):

`import vtkWSLinkClient from "vtk.js/Sources/IO/Core/WSLinkClient";
import SmartConnect from "wslink/src/SmartConnect";
import vtkRemoteView from "vtk.js/Sources/Rendering/Misc/RemoteView";
import { connectImageStream } from "vtk.js/Sources/Rendering/Misc/RemoteView";

vtkWSLinkClient.setSmartConnectClass(SmartConnect);

document.body.style.padding = "0";
document.body.style.margin = "0";

const divRenderer = document.createElement("div");
document.body.appendChild(divRenderer);

divRenderer.style.position = "relative";
divRenderer.style.width = "100vw";
divRenderer.style.height = "100vh";
divRenderer.style.overflow = "hidden";

const view = vtkRemoteView.newInstance({
  rpcWheelEvent: "viewport.mouse.zoom.wheel",
});
view.setContainer(divRenderer);
view.setInteractiveRatio(0.7); // the scaled image compared to the clients view resolution
view.setInteractiveQuality(50); // jpeg quality

window.addEventListener("resize", view.resize);

const clientToConnect = vtkWSLinkClient.newInstance();

// Error
clientToConnect.onConnectionError((httpReq) => {
  const message =
    (httpReq && httpReq.response && httpReq.response.error) ||
    `Connection error`;
  console.error(message);
  console.log(httpReq);
});

// Close
clientToConnect.onConnectionClose((httpReq) => {
  const message =
    (httpReq && httpReq.response && httpReq.response.error) ||
    `Connection close`;
  console.error(message);
  console.log(httpReq);
});

// hint: if you use the launcher.py and ws-proxy just leave out sessionURL (it will be provided by the launcher)
const config = {
  application: "cone", sessionURL: 'ws://localhost:1234/ws',
};

// Connect
clientToConnect
  .connect(config)
  .then((validClient) => {
    connectImageStream(validClient.getConnection().getSession());

    const session = validClient.getConnection().getSession();
    view.setSession(session);
    view.setViewId(-1);
    view.render();
  })
  .catch((error) => {
    console.error(error);
  });
`

Thanks again, this is really great.

**Comment by jourdain** [comment]
I've just added your example [here](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/Misc/RemoteView/example) for reference.

Feel free to submit a PR if you want to add or edit anything. 

Thanks for your contribution!
