### ISSUE TITLE
how to convert the ct scan image into 3d model using vtk

### ISSUE THREAD

**Issue by Amit8445** [Kitware/vtk-js#1544]
Hi, I am  trying to convert the ct scan image into 3d model .I am using the vtk and c++. To convert it I am using marchingcubes algorithm.but after that I don't know that what process are required? So guys pleasse help me for this task.
Thannks.

**Comment by floryst** [comment]
You can check out vtk.js image marching cubes here: http://kitware.github.io/vtk-js/examples/ImageMarchingCubes.html

Are you trying to do this on-the-fly in the browser? Depending on your data size and your requirements, I would recommend using VTK-python, and then sending the generated model to the browser for viewing.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
