### ISSUE TITLE
How to set the backface color of the object

### ISSUE THREAD

**Issue by 5dh15** [Kitware/vtk-js#1545]
I'm tried to change the backface color of the corn object.

The purpose is for make the internal color of the object different from the external color of object.

The backface color is exist in the vtk.js but I don't know how to change it's value.

Here is my code: 
    <script>

        const fullScreenRenderer = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance({
            background: [0, 0, 0],
        });

        const renderer = fullScreenRenderer.getRenderer();
        const renderWindow = fullScreenRenderer.getRenderWindow();

        const cone = vtk.Filters.Sources.vtkConeSource.newInstance();
        const actor = vtk.Rendering.Core.vtkActor.newInstance({ pickable: false });
        const mapper = vtk.Rendering.Core.vtkMapper.newInstance();

        actor.BackfaceProperty = [0,0,0.5];

        actor.setMapper(mapper);
        mapper.setInputConnection(cone.getOutputPort()); 
        renderer.addActor(actor);

        renderer.resetCamera();
        renderWindow.render();

    </script>

**Comment by jourdain** [comment]
I'm not sure vtk can do a different backface coloring. @martinken ?

**Comment by martinken** [comment]
Not implemented yet in the mapper. Not hard to add, half the code is there but commented out, just not done yet.

**Comment by 5dh15** [comment]
Thank you!
@jourdain 
@martinken

**Comment by 5dh15** [comment]
@martinken Did you figured it out?

**Comment by daker** [comment]
@jourdain 
@martinken 
I have tried to complete the code, i still have one issue when using a texture(last screenshot), do you have an idea what is the cause?

![capture1](https://user-images.githubusercontent.com/878518/107128510-93f03500-68be-11eb-96b4-f17621d6d75d.JPG)

![Capture2](https://user-images.githubusercontent.com/878518/107128511-9488cb80-68be-11eb-898d-2431ecc9b336.JPG)

![Capture3](https://user-images.githubusercontent.com/878518/107128512-95216200-68be-11eb-81de-db3d47a80308.JPG)

**Comment by daker** [comment]
@martinken any clue?
