### ISSUE TITLE
Widget issue

### ISSUE THREAD

**Issue by 5dh15** [Kitware/vtk-js#1548]
I'm making web stl viewer, and it need to add some widget like Implicit Plane Widget, Interactive Orientation Widget.

But it seems there is some issue about to fix the widgets.

In mobile invironment, all of the widgets doesn't support to touch the widget to implement function.
Such as Interactive Orientation Widget case, it can click the box to re-positioning the object in PC.
But it doesn't support the same function in the mobile web browser.

And I think there is a not completed widget.
The Implicit Plane Widget need to set transparency zero of the object on one side of the plane.

**Comment by jourdain** [comment]
FYI @floryst

**Comment by floryst** [comment]
Right now, widgets don't have support for touch, but that might be a fairly simple target to support. I haven't gotten around to looking at it primarily because touch affords more complex and dynamic interactions than just a mouse and keyboard, but I do recognize its usefulness, especially on tablets and other larger touchscreens. I'll see if I can get something working towards this.

**Comment by 5dh15** [comment]
@floryst  Thank you for the reply.
I think those widget is nessessary to develop or fix.

And I just found that OrientationMarkerWidget can't add click to repositionning function.
I don't know why can't I add this function.

Here is my code:


        function majorAxis(vec3, idxA, idxB) {
            const axis = [0, 0, 0];
            const idx = Math.abs(vec3[idxA]) > Math.abs(vec3[idxB]) ? idxA : idxB;
            const value = vec3[idx] > 0 ? 1 : -1;
            axis[idx] = value;
            return axis;
        }

        const fullScreenRenderer = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance({
            background: [0.2, 0.2, 0.2],
        });

        const renderer = fullScreenRenderer.getRenderer();
        const renderWindow = fullScreenRenderer.getRenderWindow();
        const render = renderWindow.render;

        const cone = vtk.Filters.Sources.vtkConeSource.newInstance();
        const actor = vtk.Rendering.Core.vtkActor.newInstance({ pickable: false });
        const mapper = vtk.Rendering.Core.vtkMapper.newInstance();
        const camera = renderer.getActiveCamera();

        actor.setMapper(mapper);
        mapper.setInputConnection(cone.getOutputPort()); 
        renderer.addActor(actor);

        const axes = vtk.Rendering.Core.vtkAnnotatedCubeActor.newInstance();
        axes.setDefaultStyle({
            fontStyle: 'bold',
            fontFamily: 'Arial',
            fontColor: 'white',
            fontSizeScale: (res) => res / 2,
            faceRotation: 0,
            edgeThickness: 0.1,
            edgeColor: 'black',
            resolution: 400,
        });
        axes.setXPlusFaceProperty  ({ text: 'x+' , faceColor: 'red' });
        axes.setXMinusFaceProperty ({ text: 'x-' , faceColor: 'red' });
        axes.setYPlusFaceProperty  ({ text: 'y+' , faceColor: 'green' });
        axes.setYMinusFaceProperty ({ text: 'y-' , faceColor: 'green' });
        axes.setZPlusFaceProperty  ({ text: 'z+' , faceColor: 'blue' });
        axes.setZMinusFaceProperty ({ text: 'z-' , faceColor: 'blue' });

        const orientationWidget = vtk.Interaction.Widgets.vtkOrientationMarkerWidget.newInstance({
            actor: axes,
            interactor: renderWindow.getInteractor(),
        });
        orientationWidget.setEnabled(true);
        orientationWidget.setViewportCorner(
            vtk.Interaction.Widgets.vtkOrientationMarkerWidget.Corners.BOTTOM_RIGHT
        );
        orientationWidget.setViewportSize(0.15);
        orientationWidget.setMinPixelSize(100);
        orientationWidget.setMaxPixelSize(300);

        const widgetManager = vtk.Widgets.Core.vtkWidgetManager.newInstance();
        widgetManager.setRenderer(orientationWidget.getRenderer());

        const widget = vtk.Widgets.Widgets3D.vtkInteractiveOrientationWidget.newInstance();
        widget.placeWidget(axes.getBounds());
        widget.setBounds(axes.getBounds());
        widget.setPlaceFactor(1);

        const vw = widgetManager.addWidget(widget);

        vw.onOrientationChange(({ up, direction, action, event }) => {
            const focalPoint = camera.getFocalPoint();
            const position = camera.getPosition();
            const viewUp = camera.getViewUp();

            const distance = Math.sqrt(
                vtkMath.distance2BetweenPoints(position, focalPoint)
            );
            camera.setPosition(
                focalPoint[0] + direction[0] * distance,
                focalPoint[1] + direction[1] * distance,
                focalPoint[2] + direction[2] * distance
            );

            if (direction[0]) {
                camera.setViewUp(majorAxis(viewUp, 1, 2));
            }
            if (direction[1]) {
                camera.setViewUp(majorAxis(viewUp, 0, 2));
            }
            if (direction[2]) {
                camera.setViewUp(majorAxis(viewUp, 0, 1));
            }

            orientationWidget.updateMarkerOrientation();
            widgetManager.enablePicking();
            render();
        });

        renderer.resetCamera();
        widgetManager.enablePicking();
        render();

**Comment by 5dh15** [comment]
Also, I can't see the OrientationMarkerWidget in the mobile example page.

**Comment by floryst** [comment]
The OrientationMarkerWidget is on the page, but is hidden on Chrome (probably having to do with how Chrome on Android handles page height). For instance, if you open the same example on Firefox for Android, you can see the widget. I'll adjust the example CSS accordingly.

What do you mean you can't click to reposition? Are you wanting to reposition the orientation widget to a different corner?

**Comment by floryst** [comment]
Oh, I see. I was playing with the OrientationMarkerWidget, but you meant the InteractiveOrientationWidget, which allows you to click on the faces and move the camera to that direction. The primary issue right now is that widgets were written with mouse movement in mind, so we need to find a different way of handling touch vs mouse.

**Comment by floryst** [comment]
> Also, I can't see the OrientationMarkerWidget in the mobile example page.

This should be addressed in #1558

**Comment by 5dh15** [comment]
@floryst  Thank you!

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
