### ISSUE TITLE
Actor Rotation

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/vtk-js#155]
```
actor.RotateX(33)
VM6164:12 vtkProp3D::RotateX - NOT IMPLEMENTED

```
is there another way?

**Comment by martinken** [comment]
Right now the actor rotations (as opposed to camera) are not implemented. No other way currently to do it aside from implementing them or running your data through a calc filter and doing the rotation in there. The actor rotation code is not a lot of work, just finding time to get to it.

**Comment by martinken** [comment]
Implemented the basic rotate methods, merged to master.
