### ISSUE TITLE
Feature Request: PLY Reader

### ISSUE THREAD

**Issue by banesullivan** [Kitware/vtk-js#1554]
The [PLY format](https://en.wikipedia.org/wiki/PLY_(file_format)) is a ubiquitous format for 3D meshes. It'd be awesome to include a PLY file reader in vtk.js (to my knowledge, PLY is not currently supported?)

**Comment by smoothumut** [comment]
we also ask for this PLY file reader feature. It would be great!

**Comment by jourdain** [comment]
Contributions are welcome ;-)

**Comment by smoothumut** [comment]
> Contributions are welcome ;-)

 I really would love to contribute but I am very new to this and have not enough time : (

**Comment by jourdain** [comment]
No worries. We'll see what we can do, but we are also constraint with time.

**Comment by daker** [comment]
@jourdain i did made a pull request if by any chance you want to review it

**Comment by daker** [comment]
@jourdain is the PR included in v15.3.1?

**Comment by smoothumut** [comment]
WOW,  it looks great! Frankly I had no hope, But we are really impressed how you as a team take care of the project. You deserve a big hug : )

**Comment by jourdain** [comment]
v15.3.1 should have it. I was expecting semantic-release to write on the MR to mention that automatically. But maybe it was not able to write on it?

@smoothumut your hug should go to @daker. He did all the work! Thanks a LOT @daker... 
It is nice to have support from the community. Especially when we are stretch across our many projects and we don't have the time to do much on it.

**Comment by jourdain** [comment]
Should be in v15.3
