### ISSUE TITLE
Pick function toggles the values of the the camera's viewMatrix

### ISSUE THREAD

**Issue by fivegrant** [Kitware/vtk-js#1555]
I started setting the viewMatrix manually for the vtkCamera and it works. However, the vtkPicker is somehow broken whenever I set the view matrix manually. Instead of picking an actor, the `pick` function makes all of the values positive. If I run another `pick` the matrix is fixed. So instead of selecting the shape on screen, it flashes in and out on my screen. If I take out the cameraState function below, picking works, but as soon as it's included, it breaks.
``` 
...
...
function cameraState() {
   getCameraPose()
       .then((response) => {
         return response.json();
       }).then((data) => {
         renderer.getActiveCamera().setViewMatrix(data);
       });
}
cameraState();
...
...
const picker = vtkPicker.newInstance();  
picker.setPickFromList(false);  3  
const select = [click.position.x, click.position.y, 0];   
console.log(renderer.getActiveCamera().getViewMatrix()); // every pick, the values toggle between negative and positive
picker.pick(select, renderer);
console.log(picker.getActors().length) //returns 0
...
...
```

**Comment by jourdain** [comment]
@martinken
