### ISSUE TITLE
vtkImageReslice dose not support Safari(V13.1.2)

### ISSUE THREAD

**Issue by tewtermor** [Kitware/vtk-js#1557]
Hello,

I used vtkImageReslice to get image pixel for display in cornerstone canvas but I found an error of function vtkImageReslice.getOutputData().

this is an error "Unhandled Promise Rejection: TypeError: this dose not subclass a TypedArray constructor"

Tools: VueJS (v2.6.11), vtk.js (V14.15.2), Safari (V13.1.2), macOS Catalina (V10.15.6)

I tried to test change vtk.js version 8.3.9 to 14.15.2 in this project https://github.com/QSolutionsLLC/cornerstone-vtk-mpr. The result is this project can display images. So I change vtk.js in my project to 8.3.9. It can get output data from vtkImageReslice but I need to use some function of the latest version.

**Comment by floryst** [comment]
Is there a line number for this error? Without a line number, I can initially guess that it could be this line: https://github.com/Kitware/vtk-js/blob/master/Sources/Imaging/Core/ImageReslice/index.js#L322

Can you change that line to `const background = new window[inputScalarType](model.backgroundColor)` to see if that fixes the issue on latest vtk.js? Safari/webkit can be wonky when dealing with `.from()`.

**Comment by tewtermor** [comment]
> Is there a line number for this error? Without a line number, I can initially guess that it could be this line: https://github.com/Kitware/vtk-js/blob/master/Sources/Imaging/Core/ImageReslice/index.js#L322
> 
> Can you change that line to `const background = new window[inputScalarType](model.backgroundColor)` to see if that fixes the issue on latest vtk.js? Safari/webkit can be wonky when dealing with `.from()`.

Thank you for your solution. It is work but I have a question. Why does the project (https://github.com/QSolutionsLLC/cornerstone-vtk-mpr) that use latest vtk.js works on safari without change that line?

**Comment by floryst** [comment]
Great, thanks for the feedback. I will fix it in master.

That project doesn't use the latest version of vtk.js. It uses v8.3.9, which was before the regression occurred.
