### ISSUE TITLE
STL from solidworks not visualising.

### ISSUE THREAD

**Issue by EmileSonneveld** [Kitware/vtk-js#1559]
Hey!
When I load an STL from solidworks, nothing is shown in VTK.JS. While, if I open this STL in Blender, and re-export to STL, it does get shown.
Any way to work around / fix this? :)

STL I used here: [stl_solidworks.zip](https://github.com/Kitware/vtk-js/files/5090355/stl_solidworks.zip)
Tested on demo here: https://kitware.github.io/vtk-js/examples/STLReader.html (And tested locally with vtk.js version ^13.11.1)

**Comment by floryst** [comment]
It appears that SolidWorks exports binary STLs with the word "solid" in the header. According to Wikipedia, this is wrong, but SolidWorks persists nevertheless. We will have to modify the current heuristic or use some other heuristic to handle these files.

**Comment by EmileSonneveld** [comment]
That was super fast! And on top of that, it works when I apply the patch locally! 😄 
Thank you, both!!

**Comment by jourdain** [comment]
The live example should work now as well.
