### ISSUE TITLE
The brightness of actor is seperated when rotating

### ISSUE THREAD

**Issue by JasonYoo1995** [Kitware/vtk-js#1565]
![image](https://user-images.githubusercontent.com/66045861/91398613-62872e00-e877-11ea-944c-91ec6086259e.png)
![image](https://user-images.githubusercontent.com/66045861/91398621-69ae3c00-e877-11ea-834e-36dc971e8f25.png)
![image](https://user-images.githubusercontent.com/66045861/91398630-6f0b8680-e877-11ea-80c5-3267db05fffc.png)
![image](https://user-images.githubusercontent.com/66045861/91398641-7337a400-e877-11ea-815e-126732765a4b.png)

Like the pictures above, when I rotate the actor, its brightness is seperated by two — brighter one and darker one.
(This problem can be easily found when its transparency is between 20% and 80%)
How can I solve this problem? I want to show it with just one color.

**Comment by jourdain** [comment]
This is related to https://github.com/Kitware/vtk-js/issues/1202

**Comment by jourdain** [comment]
The origin is related to https://github.com/Kitware/vtk-js/issues/680 but should be solved when using WebGPU.
