### ISSUE TITLE
How does VTk. js free GPU memory?

### ISSUE THREAD

**Issue by huatianyu** [Kitware/vtk-js#1567]
![image](https://user-images.githubusercontent.com/24466497/91512499-bac03d80-e914-11ea-9047-56ad7555f918.png)
GPU memory is still occupied every time the window is closed

**Comment by floryst** [comment]
Do you have a minimal example of this occurring? If you unset the render window container (i.e. set it to null), it should clear up your GPU memory.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
