### ISSUE TITLE
Use ImageCropFilter without HttpDataSetReader

### ISSUE THREAD

**Issue by Seeker93** [Kitware/vtk-js#1569]
Hi everyone.

I am kinda new to this, so forgive me if I am missing something obvious.

I am rendering a float array using VTK.js and I'm using this code as a base https://stackoverflow.com/questions/47407199/how-to-render-a-float32array-cube-with-vtk-js.

I've done this successfully, but now I want to add the _ImageCropFilter_ widget on top of it. However, when I look at the example on how to implement it (https://kitware.github.io/vtk-js/examples/ImageCropFilter.html) it only shows how to achieve it when using _HttpDataSetReader_, but I am using the _ImageData_ object as my data source. How would I go about linking the _ImageCropFilter_ to my data cube?

Using the HttpDataSetReader it seems to be achieved using the following lines:

```
cropFilter.setInputConnection(reader.getOutputPort());
mapper.setInputConnection(cropFilter.getOutputPort());
```

But how would I do the equivalent using the _ImageData_ object?

**Comment by floryst** [comment]
You can do the following:
```
cropFilter.setInputData(myFloat32Array);
mapper.setInputData(cropFilter.getOutputData());
```

If you want to learn more about how vtk.js pipelines work, check out this tutorial video: <https://vimeo.com/375521810>. Filters and pipelines are discussed at 10:21.

**Comment by Seeker93** [comment]
Thank you! That worked and the video is very informative. Is the video linked anywhere in the docs btw? It's super useful but I must have missed it.

**Comment by floryst** [comment]
Yep! They are linked here: https://kitware.github.io/vtk-js/docs/tutorial.html
