### ISSUE TITLE
vtkXMLPolyDataReader cannot read specific vtp file

### ISSUE THREAD

**Issue by robbie-li** [Kitware/vtk-js#1570]
See my comment on commit:
https://github.com/Kitware/vtk-js/commit/76c307479b1181487dc7036b14b94e910658a24f#commitcomment-41964581

Sample vtp file is attached here:
[buccal.zip](https://github.com/Kitware/vtk-js/files/5160211/buccal.zip)

Main cause is offset in new UInt32Array(buffer, offset, length) is not multiple of 4.

**Comment by robbie-li** [comment]
The sample file is uploaded here:

[buccal.zip](https://github.com/Kitware/vtk-js/files/5160208/buccal.zip)

**Comment by floryst** [comment]
Ah, I commented about a dataset without seeing this post first. I'll check it out and get back to you with a fix.

**Comment by floryst** [comment]
The fix should now be in master. Let me know if there are any other problematic files that won't load!
