### ISSUE TITLE
Constrain the ImageCroppingRegionsWidget to certain bounds

### ISSUE THREAD

**Issue by Seeker93** [Kitware/vtk-js#1571]
Is there any way to constrain the ImageCroppingRegionsWidget (https://kitware.github.io/vtk-js/api/Interaction_Widgets_ImageCroppingRegionsWidget.html) to a set bounds?

 I would like to constrain it to the dimensions of my volume.

**Comment by floryst** [comment]
Yeah that's possible. For one, I'd recommend you check out the newer widget architecture that's under `Sources/Widgets`, as `Sources/Interaction/Widgets` are the old-style widgets and are not being actively developed. The [vtkImageCroppingWidget](https://kitware.github.io/vtk-js/examples/ImageCroppingWidget.html) is the cropping widget in the new-style widgets.

Note that the cropping widget doesn't actually perform the cropping; vtkImageCropFilter does. In the example linked above, the following lines perform the actual cropping:
```
    cropState.onModified(() => {
      cropFilter.setCroppingPlanes(cropState.getPlanes());
    });
```

All you need to do is to take the output of `cropState.getPlanes()`, constrain them to the bounds of your volume, and then pass that to `cropFilter.setCroppingPlanes(...)`.
