### ISSUE TITLE
how to load remote images by http request

### ISSUE THREAD

**Issue by laoniu2020** [Kitware/vtk-js#1575]
Hi all, 

How to load a remote series images (hundreds dicom images) by http to volumn render.

**Comment by jourdain** [comment]
@floryst I think you provided some input on that topic.

**Comment by floryst** [comment]
Check out [readImageDICOMFileSeries](http://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readImageDICOMFileSeries-fileList-singleSortedSeries-false-gt-image-webWorkerPool). You will need to use fetch() or XMLHttpRequest to download your images, and then pass the resulting File list to `readImageDICOMFileSeries`.

You might be interested in following this topic on the VTK discourse: https://discourse.vtk.org/t/request-hundreds-images-by-http/4154/5

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
