### ISSUE TITLE
Replace current volume with a new one

### ISSUE THREAD

**Issue by Seeker93** [Kitware/vtk-js#1578]
Hi guys. I am rendering a specific volume similar to the SimpleCone example (but in React) 

https://kitware.github.io/vtk-js/examples/SimpleCone.html

However, I want to replace the current volume with a slightly edited one on a button press. However, I can't seem to find the command to remove the current volume from the renderwindow. I assumed renderer.removeAllVolumes() would do the trick, but that doesn't seem to be the case. Is there a special command for this?

**Comment by jourdain** [comment]
That is because it is not a Volume (VolumeRendering), it is an Actor. You can see in the code `renderer.addActor(actor)`.
