### ISSUE TITLE
I hope to know some value means on actor.jon

### ISSUE THREAD

**Issue by AlexTerry1024** [Kitware/vtk-js#1579]
0.4945269525051117,
0.9051258563995361,
0.20178239047527313,
0.25008419156074524,
 0.6825500726699829,
0.6665751934051514,
0.6896824240684509,
0.3268996775150299,
0.88401859998703,
0.9641408920288086,
0.2844676077365875,
0.5107138752937317,
0.06342488527297974,
0.3234332501888275,
 0.711337685585022,
0.2414875477552414,
0.7309854030609131,
0.8149802088737488,
0.5051003694534302,
0.3436082899570465,
0.9637079834938049,
0.27523142099380493,
0.8384449481964111,
0.10200495272874832,
0.30800673365592957

**Comment by AlexTerry1024** [comment]
I hope to know how can I get these values for actor.json

**Comment by jourdain** [comment]
What is actor.json? It seems that you can just reduce your array to get the mean. I don't see what is the link with vtk.js.

**Comment by AlexTerry1024** [comment]
Thank you for repying

**Comment by AlexTerry1024** [comment]
I mean ActorSerialization example demo

**Comment by AlexTerry1024** [comment]
![image](https://user-images.githubusercontent.com/31697138/93119759-f15bcd80-f6f4-11ea-81d0-c0569d1aa132.png)

**Comment by AlexTerry1024** [comment]
{
  "allocatedRenderTime": 10,
  "bounds": [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5],
  "boundsMTime": {
    "classHierarchy": ["vtkObject"],
    "mtime": 561,
    "vtkClass": "vtkObject"
  },
  "classHierarchy": ["vtkObject", "vtkProp", "vtkProp3D", "vtkActor"],
  "dragable": true,
  "estimatedRenderTime": 0,
  "forceOpaque": false,
  "forceTranslucent": false,
  "isIdentity": true,
  "mapper": {
    "bounds": [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5],
    "center": [0, 0],
    "classHierarchy": ["vtkObject", "vtkMapper"],
    "colorMapColors": {
      "classHierarchy": ["vtkObject", "vtkDataArray"],
      "dataType": "Uint8Array",
      "mtime": 556,
      "name": "temp",
      "numberOfComponents": 4,
      "size": 100,
      "type": "vtkDataArray",
      "values": [6, 255, 0, 255, 0, 96, 255, 255, 255, 204, 0, 255, 254, 255, 0, 255, 0, 255, 186, 255, 0, 255, 170, 255, 0, 255, 194, 255, 178, 255, 0, 255, 0, 116, 255, 255, 0, 36, 255, 255, 222, 255, 0, 255, 0, 255, 10, 255, 255, 64, 0, 255, 182, 255, 0, 255, 0, 255, 218, 255, 255, 244, 0, 255, 0, 255, 238, 255, 0, 188, 255, 255, 0, 255, 6, 255, 162, 255, 0, 255, 0, 36, 255, 255, 230, 255, 0, 255, 0, 164, 255, 255, 255, 104, 0, 255, 198, 255, 0, 255],
      "vtkClass": "vtkDataArray"
    },
    "colorMode": 0,
    "fieldDataTupleId": -1,
    "forceCompileOnly": 0,
    "inputArrayToProcess": [],
    "inputConnection": [null],
    "inputData": [{
      "cellData": {
        "activeGlobalIds": -1,
        "activeNormals": -1,
        "activePedigreeIds": -1,
        "activeScalars": 0,
        "activeTCoords": -1,
        "activeTensors": -1,
        "activeVectors": -1,
        "arrays": [{
          "data": {
            "classHierarchy": ["vtkObject", "vtkDataArray"],
            "dataType": "Float32Array",
            "mtime": 553,
            "name": "temp",
            "numberOfComponents": 1,
            "size": 25,
            "values": [0.4945269525051117, 0.9051258563995361, 0.20178239047527313, 0.25008419156074524, 0.6825500726699829, 0.6665751934051514, 0.6896824240684509, 0.3268996775150299, 0.88401859998703, 0.9641408920288086, 0.2844676077365875, 0.5107138752937317, 0.06342488527297974, 0.3234332501888275, 0.711337685585022, 0.2414875477552414, 0.7309854030609131, 0.8149802088737488, 0.5051003694534302, 0.3436082899570465, 0.9637079834938049, 0.27523142099380493, 0.8384449481964111, 0.10200495272874832, 0.30800673365592957],
            "vtkClass": "vtkDataArray"
          }
        }],
        "classHierarchy": ["vtkObject", "vtkFieldData", "vtkDataSetAttributes"],
        "copyFieldFlags": [],
        "doCopyAllOff": false,
        "doCopyAllOn": true,
        "mtime": 556,
        "vtkClass": "vtkDataSetAttributes"
      },
      "classHierarchy": ["vtkObject", "vtkDataSet", "vtkPointSet", "vtkPolyData"],
      "fieldData": {
        "activeGlobalIds": -1,
        "activeNormals": -1,
        "activePedigreeIds": -1,
        "activeScalars": -1,
        "activeTCoords": -1,
        "activeTensors": -1,
        "activeVectors": -1,
        "arrays": [],
        "classHierarchy": ["vtkObject", "vtkFieldData", "vtkDataSetAttributes"],
        "copyFieldFlags": [],
        "doCopyAllOff": false,
        "doCopyAllOn": true,
        "mtime": 553,
        "vtkClass": "vtkDataSetAttributes"
      },
      "lines": {
        "classHierarchy": ["vtkObject", "vtkDataArray"],
        "dataType": "Float32Array",
        "empty": true,
        "mtime": 553,
        "numberOfComponents": 1,
        "values": [],
        "vtkClass": "vtkCellArray"
      },
      "mtime": 555,
      "pointData": {
        "activeGlobalIds": -1,
        "activeNormals": -1,
        "activePedigreeIds": -1,
        "activeScalars": -1,
        "activeTCoords": -1,
        "activeTensors": -1,
        "activeVectors": -1,
        "arrays": [],
        "classHierarchy": ["vtkObject", "vtkFieldData", "vtkDataSetAttributes"],
        "copyFieldFlags": [],
        "doCopyAllOff": false,
        "doCopyAllOn": true,
        "mtime": 553,
        "vtkClass": "vtkDataSetAttributes"
      },
      "points": {
        "dataType": "Float32Array",
        "numberOfComponents": 3,
        "size": 75,
        "values": [0.5, 0, 0, -0.5, 0.5, 0, -0.5, 0.4829629063606262, 0.129409521818161, -0.5, 0.4330126941204071, 0.25, -0.5, 0.3535533845424652, 0.3535533845424652, -0.5, 0.25, 0.4330126941204071, -0.5, 0.129409521818161, 0.4829629063606262, -0.5, 3.0616171314629196e-17, 0.5, -0.5, -0.129409521818161, 0.4829629063606262, -0.5, -0.25, 0.4330126941204071, -0.5, -0.3535533845424652, 0.3535533845424652, -0.5, -0.4330126941204071, 0.25, -0.5, -0.4829629063606262, 0.129409521818161, -0.5, -0.5, 6.123234262925839e-17, -0.5, -0.4829629063606262, -0.129409521818161, -0.5, -0.4330126941204071, -0.25, -0.5, -0.3535533845424652, -0.3535533845424652, -0.5, -0.25, -0.4330126941204071, -0.5, -0.129409521818161, -0.4829629063606262, -0.5, -9.184850732644269e-17, -0.5, -0.5, 0.129409521818161, -0.4829629063606262, -0.5, 0.25, -0.4330126941204071, -0.5, 0.3535533845424652, -0.3535533845424652, -0.5, 0.4330126941204071, -0.25, -0.5, 0.4829629063606262, -0.129409521818161],
        "vtkClass": "vtkPoints"
      },
      "polys": {
        "classHierarchy": ["vtkObject", "vtkDataArray"],
        "dataType": "Uint32Array",
        "empty": true,
        "mtime": 552,
        "numberOfComponents": 1,
        "size": 121,
        "values": [24, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 3, 0, 1, 2, 3, 0, 2, 3, 3, 0, 3, 4, 3, 0, 4, 5, 3, 0, 5, 6, 3, 0, 6, 7, 3, 0, 7, 8, 3, 0, 8, 9, 3, 0, 9, 10, 3, 0, 10, 11, 3, 0, 11, 12, 3, 0, 12, 13, 3, 0, 13, 14, 3, 0, 14, 15, 3, 0, 15, 16, 3, 0, 16, 17, 3, 0, 17, 18, 3, 0, 18, 19, 3, 0, 19, 20, 3, 0, 20, 21, 3, 0, 21, 22, 3, 0, 22, 23, 3, 0, 23, 24, 3, 0, 24, 1],
        "vtkClass": "vtkCellArray"
      },
      "strips": {
        "classHierarchy": ["vtkObject", "vtkDataArray"],
        "dataType": "Float32Array",
        "empty": true,
        "mtime": 553,
        "numberOfComponents": 1,
        "values": [],
        "vtkClass": "vtkCellArray"
      },
      "verts": {
        "classHierarchy": ["vtkObject", "vtkDataArray"],
        "dataType": "Float32Array",
        "empty": true,
        "mtime": 553,
        "numberOfComponents": 1,
        "values": [],
        "vtkClass": "vtkCellArray"
      },
      "vtkClass": "vtkPolyData"
    }],
    "interpolateScalarsBeforeMapping": false,
    "lookupTable": {
      "aboveRangeColor": [1, 1, 1, 1],
      "alpha": 1,
      "alphaRange": [1, 1],
      "belowRangeColor": [0, 0, 0, 1],
      "buildTime": {
        "classHierarchy": ["vtkObject"],
        "mtime": 61,
        "vtkClass": "vtkObject"
      },
      "classHierarchy": ["vtkObject", "vtkLookupTable"],
      "hueRange": [0, 0.66667],
      "mappingRange": [0, 1],
      "mtime": 60,
      "nanColor": [0.5, 0, 0, 1],
      "numberOfColors": 256,
      "opaqueFlagBuildTime": {
        "classHierarchy": ["vtkObject"],
        "mtime": 60,
        "vtkClass": "vtkObject"
      },
      "saturationRange": [1, 1],
      "table": [255.5, 0.5, 0.5, 255.5, 255.5, 4.50002, 0.5, 255.5, 255.5, 8.50004, 0.5, 255.5, 255.5, 12.50006, 0.5, 255.5, 255.5, 16.50008, 0.5, 255.5, 255.5, 20.5001, 0.5, 255.5, 255.5, 24.50012, 0.5, 255.5, 255.5, 28.500140000000002, 0.5, 255.5, 255.5, 32.50016, 0.5, 255.5, 255.5, 36.50018, 0.5, 255.5, 255.5, 40.5002, 0.5, 255.5, 255.5, 44.500220000000006, 0.5, 255.5, 255.5, 48.50024, 0.5, 255.5, 255.5, 52.500260000000004, 0.5, 255.5, 255.5, 56.500280000000004, 0.5, 255.5, 255.5, 60.5003, 0.5, 255.5, 255.5, 64.50032, 0.5, 255.5, 255.5, 68.50034000000001, 0.5, 255.5, 255.5, 72.50036, 0.5, 255.5, 255.5, 76.50038, 0.5, 255.5, 255.5, 80.5004, 0.5, 255.5, 255.5, 84.50042, 0.5, 255.5, 255.5, 88.50044000000001, 0.5, 255.5, 255.5, 92.50046000000002, 0.5, 255.5, 255.5, 96.50048, 0.5, 255.5, 255.5, 100.50049999999999, 0.5, 255.5, 255.5, 104.50052000000001, 0.5, 255.5, 255.5, 108.50054000000002, 0.5, 255.5, 255.5, 112.50056000000001, 0.5, 255.5, 255.5, 116.50057999999999, 0.5, 255.5, 255.5, 120.5006, 0.5, 255.5, 255.5, 124.50062000000001, 0.5, 255.5, 255.5, 128.50064, 0.5, 255.5, 255.5, 132.50066, 0.5, 255.5, 255.5, 136.50068000000002, 0.5, 255.5, 255.5, 140.50070000000002, 0.5, 255.5, 255.5, 144.50072, 0.5, 255.5, 255.5, 148.50073999999998, 0.5, 255.5, 255.5, 152.50076, 0.5, 255.5, 255.5, 156.50078000000002, 0.5, 255.5, 255.5, 160.5008, 0.5, 255.5, 255.5, 164.50082, 0.5, 255.5, 255.5, 168.50084, 0.5, 255.5, 255.5, 172.50086000000002, 0.5, 255.5, 255.5, 176.50088000000002, 0.5, 255.5, 255.5, 180.5009, 0.5, 255.5, 255.5, 184.50092000000004, 0.5, 255.5, 255.5, 188.50094, 0.5, 255.5, 255.5, 192.50096, 0.5, 255.5, 255.5, 196.50098, 0.5, 255.5, 255.5, 200.50099999999998, 0.5, 255.5, 255.5, 204.50102, 0.5, 255.5, 255.5, 208.50104000000002, 0.5, 255.5, 255.5, 212.50106, 0.5, 255.5, 255.5, 216.50108000000003, 0.5, 255.5, 255.5, 220.50110000000004, 0.5, 255.5, 255.5, 224.50112000000001, 0.5, 255.5, 255.5, 228.50114, 0.5, 255.5, 255.5, 232.50115999999997, 0.5, 255.5, 255.5, 236.50118, 0.5, 255.5, 255.5, 240.5012, 0.5, 255.5, 255.5, 244.50122, 0.5, 255.5, 255.5, 248.50124000000002, 0.5, 255.5, 255.5, 252.50126000000003, 0.5, 255.5, 254.49871999999996, 255.5, 0.5, 255.5, 250.49869999999999, 255.5, 0.5, 255.5, 246.49867999999998, 255.5, 0.5, 255.5, 242.49865999999997, 255.5, 0.5, 255.5, 238.49864, 255.5, 0.5, 255.5, 234.49862, 255.5, 0.5, 255.5, 230.49859999999995, 255.5, 0.5, 255.5, 226.49857999999998, 255.5, 0.5, 255.5, 222.49855999999997, 255.5, 0.5, 255.5, 218.49854, 255.5, 0.5, 255.5, 214.49851999999998, 255.5, 0.5, 255.5, 210.49849999999995, 255.5, 0.5, 255.5, 206.49847999999997, 255.5, 0.5, 255.5, 202.49845999999997, 255.5, 0.5, 255.5, 198.49843999999996, 255.5, 0.5, 255.5, 194.49841999999998, 255.5, 0.5, 255.5, 190.49839999999998, 255.5, 0.5, 255.5, 186.49838, 255.5, 0.5, 255.5, 182.49836, 255.5, 0.5, 255.5, 178.49833999999996, 255.5, 0.5, 255.5, 174.49831999999998, 255.5, 0.5, 255.5, 170.49829999999997, 255.5, 0.5, 255.5, 166.49827999999994, 255.5, 0.5, 255.5, 162.49825999999996, 255.5, 0.5, 255.5, 158.49823999999998, 255.5, 0.5, 255.5, 154.49822, 255.5, 0.5, 255.5, 150.4982, 255.5, 0.5, 255.5, 146.49817999999996, 255.5, 0.5, 255.5, 142.49815999999998, 255.5, 0.5, 255.5, 138.49813999999998, 255.5, 0.5, 255.5, 134.49811999999994, 255.5, 0.5, 255.5, 130.49809999999997, 255.5, 0.5, 255.5, 126.49807999999997, 255.5, 0.5, 255.5, 122.49805999999994, 255.5, 0.5, 255.5, 118.49803999999999, 255.5, 0.5, 255.5, 114.49801999999995, 255.5, 0.5, 255.5, 110.498, 255.5, 0.5, 255.5, 106.49797999999998, 255.5, 0.5, 255.5, 102.49795999999995, 255.5, 0.5, 255.5, 98.49794, 255.5, 0.5, 255.5, 94.49791999999997, 255.5, 0.5, 255.5, 90.49789999999993, 255.5, 0.5, 255.5, 86.49788, 255.5, 0.5, 255.5, 82.49785999999996, 255.5, 0.5, 255.5, 78.49783999999993, 255.5, 0.5, 255.5, 74.49781999999998, 255.5, 0.5, 255.5, 70.49779999999994, 255.5, 0.5, 255.5, 66.49778, 255.5, 0.5, 255.5, 62.49775999999997, 255.5, 0.5, 255.5, 58.497739999999936, 255.5, 0.5, 255.5, 54.49771999999999, 255.5, 0.5, 255.5, 50.49769999999996, 255.5, 0.5, 255.5, 46.49768000000001, 255.5, 0.5, 255.5, 42.497659999999975, 255.5, 0.5, 255.5, 38.49763999999995, 255.5, 0.5, 255.5, 34.49762, 255.5, 0.5, 255.5, 30.497599999999967, 255.5, 0.5, 255.5, 26.497579999999935, 255.5, 0.5, 255.5, 22.49755999999999, 255.5, 0.5, 255.5, 18.497539999999958, 255.5, 0.5, 255.5, 14.497519999999925, 255.5, 0.5, 255.5, 10.497499999999977, 255.5, 0.5, 255.5, 6.497479999999946, 255.5, 0.5, 255.5, 2.4974599999999993, 255.5, 0.5, 255.5, 0.5, 255.5, 2.5025600000000328, 255.5, 0.5, 255.5, 6.502580000000065, 255.5, 0.5, 255.5, 10.502600000000012, 255.5, 0.5, 255.5, 14.502620000000043, 255.5, 0.5, 255.5, 18.50263999999999, 255.5, 0.5, 255.5, 22.502660000000024, 255.5, 0.5, 255.5, 26.502680000000055, 255.5, 0.5, 255.5, 30.5027, 255.5, 0.5, 255.5, 34.50272000000003, 255.5, 0.5, 255.5, 38.50274000000007, 255.5, 0.5, 255.5, 42.50276000000001, 255.5, 0.5, 255.5, 46.502780000000044, 255.5, 0.5, 255.5, 50.50280000000008, 255.5, 0.5, 255.5, 54.50282000000002, 255.5, 0.5, 255.5, 58.502840000000056, 255.5, 0.5, 255.5, 62.50286, 255.5, 0.5, 255.5, 66.50288000000003, 255.5, 0.5, 255.5, 70.50290000000007, 255.5, 0.5, 255.5, 74.50292000000002, 255.5, 0.5, 255.5, 78.50294000000004, 255.5, 0.5, 255.5, 82.50295999999999, 255.5, 0.5, 255.5, 86.50298000000002, 255.5, 0.5, 255.5, 90.50300000000006, 255.5, 0.5, 255.5, 94.50302, 255.5, 0.5, 255.5, 98.50304000000003, 255.5, 0.5, 255.5, 102.50306000000006, 255.5, 0.5, 255.5, 106.50308000000001, 255.5, 0.5, 255.5, 110.50310000000005, 255.5, 0.5, 255.5, 114.50312000000008, 255.5, 0.5, 255.5, 118.50314000000002, 255.5, 0.5, 255.5, 122.50316000000005, 255.5, 0.5, 255.5, 126.50318, 255.5, 0.5, 255.5, 130.50320000000002, 255.5, 0.5, 255.5, 134.50322000000006, 255.5, 0.5, 255.5, 138.50324, 255.5, 0.5, 255.5, 142.50326000000004, 255.5, 0.5, 255.5, 146.50328, 255.5, 0.5, 255.5, 150.50330000000002, 255.5, 0.5, 255.5, 154.50332000000006, 255.5, 0.5, 255.5, 158.50334, 255.5, 0.5, 255.5, 162.50336000000004, 255.5, 0.5, 255.5, 166.50338000000008, 255.5, 0.5, 255.5, 170.5034, 255.5, 0.5, 255.5, 174.50342000000003, 255.5, 0.5, 255.5, 178.50344000000007, 255.5, 0.5, 255.5, 182.50346000000002, 255.5, 0.5, 255.5, 186.50348000000005, 255.5, 0.5, 255.5, 190.5035, 255.5, 0.5, 255.5, 194.50352000000004, 255.5, 0.5, 255.5, 198.50354000000007, 255.5, 0.5, 255.5, 202.50356000000002, 255.5, 0.5, 255.5, 206.50358000000006, 255.5, 0.5, 255.5, 210.5036, 255.5, 0.5, 255.5, 214.50362, 255.5, 0.5, 255.5, 218.50364000000005, 255.5, 0.5, 255.5, 222.50366, 255.5, 0.5, 255.5, 226.50368000000003, 255.5, 0.5, 255.5, 230.50370000000007, 255.5, 0.5, 255.5, 234.50372000000002, 255.5, 0.5, 255.5, 238.50374000000005, 255.5, 0.5, 255.5, 242.50376000000009, 255.5, 0.5, 255.5, 246.50378000000003, 255.5, 0.5, 255.5, 250.50380000000007, 255.5, 0.5, 255.5, 254.50382, 255.5, 0.5, 252.49615999999995, 255.5, 255.5, 0.5, 248.4961399999999, 255.5, 255.5, 0.5, 244.49611999999988, 255.5, 255.5, 0.5, 240.4961, 255.5, 255.5, 0.5, 236.49607999999998, 255.5, 255.5, 0.5, 232.49605999999994, 255.5, 255.5, 0.5, 228.4960399999999, 255.5, 255.5, 0.5, 224.49601999999987, 255.5, 255.5, 0.5, 220.496, 255.5, 255.5, 0.5, 216.49598, 255.5, 255.5, 0.5, 212.49595999999997, 255.5, 255.5, 0.5, 208.49593999999993, 255.5, 255.5, 0.5, 204.4959199999999, 255.5, 255.5, 0.5, 200.49589999999986, 255.5, 255.5, 0.5, 196.49588, 255.5, 255.5, 0.5, 192.49585999999996, 255.5, 255.5, 0.5, 188.49583999999993, 255.5, 255.5, 0.5, 184.4958199999999, 255.5, 255.5, 0.5, 180.49579999999986, 255.5, 255.5, 0.5, 176.49578000000002, 255.5, 255.5, 0.5, 172.49576, 255.5, 255.5, 0.5, 168.49573999999996, 255.5, 255.5, 0.5, 164.49571999999992, 255.5, 255.5, 0.5, 160.49569999999989, 255.5, 255.5, 0.5, 156.49567999999985, 255.5, 255.5, 0.5, 152.49566, 255.5, 255.5, 0.5, 148.49563999999995, 255.5, 255.5, 0.5, 144.49561999999992, 255.5, 255.5, 0.5, 140.49559999999988, 255.5, 255.5, 0.5, 136.49557999999985, 255.5, 255.5, 0.5, 132.49556, 255.5, 255.5, 0.5, 128.49553999999995, 255.5, 255.5, 0.5, 124.49551999999994, 255.5, 255.5, 0.5, 120.49549999999991, 255.5, 255.5, 0.5, 116.49547999999987, 255.5, 255.5, 0.5, 112.49546000000001, 255.5, 255.5, 0.5, 108.49543999999997, 255.5, 255.5, 0.5, 104.49541999999995, 255.5, 255.5, 0.5, 100.49539999999992, 255.5, 255.5, 0.5, 96.49537999999988, 255.5, 255.5, 0.5, 92.49536000000002, 255.5, 255.5, 0.5, 88.49533999999998, 255.5, 255.5, 0.5, 84.49531999999995, 255.5, 255.5, 0.5, 80.49529999999993, 255.5, 255.5, 0.5, 76.4952799999999, 255.5, 255.5, 0.5, 72.49525999999986, 255.5, 255.5, 0.5, 68.49524, 255.5, 255.5, 0.5, 64.49521999999996, 255.5, 255.5, 0.5, 60.49519999999993, 255.5, 255.5, 0.5, 56.495179999999905, 255.5, 255.5, 0.5, 52.49515999999987, 255.5, 255.5, 0.5, 48.495140000000006, 255.5, 255.5, 0.5, 44.49511999999998, 255.5, 255.5, 0.5, 40.495099999999944, 255.5, 255.5, 0.5, 36.495079999999916, 255.5, 255.5, 0.5, 32.49505999999988, 255.5, 255.5, 0.5, 28.49503999999985, 255.5, 255.5, 0.5, 24.49501999999999, 255.5, 255.5, 0.5, 20.494999999999955, 255.5, 255.5, 0.5, 16.494979999999924, 255.5, 255.5, 0.5, 12.494959999999892, 255.5, 255.5, 0.5, 8.494939999999861, 255.5, 255.5, 0.5, 4.494919999999999, 255.5, 255.5, 0.5051000000000334, 0.5, 255.5, 255.5, 255.5, 0.5, 0.5, 255.5, 0.5051000000000334, 0.5, 255.5, 255.5, 128, 0.5, 0.5, 255.5],
      "useAboveRangeColor": false,
      "useBelowRangeColor": false,
      "valueRange": [1, 1],
      "vectorComponent": 0,
      "vectorMode": 1,
      "vectorSize": -1,
      "vtkClass": "vtkLookupTable"
    },
    "mtime": 2,
    "output": [],
    "renderTime": 0,
    "resolveCoincidentTopology": false,
    "scalarMode": 0,
    "scalarRange": [0, 1],
    "scalarVisibility": true,
    "static": false,
    "topologyOffset": {
      "Polygon": {
        "factor": 0,
        "unit": 0
      },
      "Line": {
        "factor": 0,
        "unit": 0
      },
      "Point": {
        "factor": 0,
        "unit": 0
      }
    },
    "useInvertibleColors": false,
    "useLookupTableScalarRange": false,
    "vtkClass": "vtkMapper"
  },
  "mapperBounds": [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5],
  "matrix": {
    "0": 1,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 1,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 1
  },
  "matrixMTime": {
    "classHierarchy": ["vtkObject"],
    "mtime": 2,
    "vtkClass": "vtkObject"
  },
  "mtime": 3,
  "orientation": [0, 0, 0],
  "origin": [0, 0, 0],
  "pickable": true,
  "position": [0, 0, 0],
  "property": {
    "ambient": 0,
    "ambientColor": [1, 1, 1],
    "backfaceCulling": false,
    "classHierarchy": ["vtkObject", "vtkProperty"],
    "color": [1, 1, 1],
    "diffuse": 1,
    "diffuseColor": [1, 1, 1],
    "edgeColor": [0, 0, 0],
    "edgeVisibility": false,
    "frontfaceCulling": false,
    "interpolation": 1,
    "lighting": true,
    "lineWidth": 1,
    "mtime": 60,
    "opacity": 1,
    "pointSize": 1,
    "representation": 2,
    "shading": false,
    "specular": 0,
    "specularColor": [1, 1, 1],
    "specularPower": 1,
    "vtkClass": "vtkProperty"
  },
  "renderTimeMultiplier": 1,
  "savedEstimatedRenderTime": 0,
  "scale": [1, 1, 1],
  "textures": [],
  "useBounds": true,
  "visibility": true,
  "vtkClass": "vtkActor"
}

**Comment by jourdain** [comment]
Could you explain what you are trying to do? 
Why do you want to serialize an actor? 
Why do you want to process the serialized data?

**Comment by AlexTerry1024** [comment]
I am going to convert three.js to VTK.js
I have point data list and index data list and colors list.

So I think this sample is similar with the component what I want to build.

Thank you.

Regards.

**Comment by jourdain** [comment]
Just create a vtkPolyData from your mesh information. No need to deal with the serialization part.

```
const polydata = vtkPolyData.newInstance();
polydata.getPoints().setData(Float32Array.from(vertex), 3);

// ... create the cells for your trianges (nbPoints, pointIdx0, pointIdx1, pointIdx2, nbPoints, pointIdx0, pointIdx1, pointIdx2, [...])
// polydata.getPolys().setData(list);
```

**Comment by AlexTerry1024** [comment]
One more question.

There is any way to add color without using a scalar?

**Comment by jourdain** [comment]
yes

**Comment by AlexTerry1024** [comment]
Would you please provide sample code?

**Comment by jourdain** [comment]
https://discourse.vtk.org/t/rendering-a-2d-float-array/4216/2

**Comment by AlexTerry1024** [comment]
![image](https://user-images.githubusercontent.com/31697138/93197443-3841d580-f77e-11ea-8cc8-33b368b9b819.png)

**Comment by AlexTerry1024** [comment]
Would you please explain what is wrong?

Thank you.

Regards

**Comment by jourdain** [comment]
You must be messing up something in the connectivity of your mesh.
