### ISSUE TITLE
Focus on Actor in 3D view

### ISSUE THREAD

**Issue by thomas-beznik** [Kitware/vtk-js#1581]
Hello,

I would like to be able to "focus" the camera on a particular actor (a 3D STL) i.e. that the camera zooms on this actor and when rotating it, it goes around this actor. I have the coordinates of its center of mass.

Any tips on how this could be done, and on what I should use to achieve this? 

Also, some more information/ some links to better understand how the camera works and the meaning of its different properties would really be appreciated!

Thank you!

**Comment by jourdain** [comment]
You should be able to call reset camera using the bounds of the object you want. 
Also, depending on your interactor style, you may have to set the center of rotation.

**Comment by thomas-beznik** [comment]
How can I reset the camera using the bounds of the object? Thanks for your answer!

**Comment by jourdain** [comment]
You pass the bounds as arguments to the method.

https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Renderer/index.js#L369

**Comment by thomas-beznik** [comment]
Great, it indeed works! Another question: what should I set the center of rotation to? To the center of mass of the object? Because that doesn't seem to work

**Comment by thomas-beznik** [comment]
Nevermind, it works if I take the actor's center :)

**Comment by jourdain** [comment]
After a reset camera, you can use the `camera.getFocalPoint()`
