### ISSUE TITLE
Can't load vtk.js modules, VolumerMapper, GenericRenderWindow etc!

### ISSUE THREAD

**Issue by SohailButt** [Kitware/vtk-js#1582]
C:\dv-project\node_modules\vtk.js\dist>npm run build

> dv-project@1.0.0 build C:\dv-project\node_modules\vtk.js
> webpack --progress --colors --mode development

Hash: fe0f470c433a8381aa2d
Version: webpack 4.43.0
Time: 1770ms
Built at: 09/17/2020 1:46:26 PM
 Asset      Size  Chunks             Chunk Names
app.js  95.3 KiB    main  [emitted]  main
Entrypoint main = app.js
[../webpack/buildin/global.js] 472 bytes {main} [built]
[./Sources/Rendering/Core/Volume/index.js] 5.06 KiB {main} [built]
[./Sources/Rendering/Core/VolumeMapper/index.js] 2.99 KiB {main} [built]
[./Sources/Rendering/Misc/GenericRenderWindow/index.js] 4.94 KiB {main} [built]
[./Sources/macro.js] 54.9 KiB {main} [built]
[./Sources/vtk.js] 2.64 KiB {main} [built]
[./src/index.js] 1.14 KiB {main} [built]

ERROR in ./src/index.js
Module not found: Error: Can't resolve '../Source/IO/Core/HttpDataSetReader' in 'C:\dv-project\node_modules\vtk.js\src'
 @ ./src/index.js 6:0-71 21:19-39

ERROR in ./Sources/Rendering/Core/Volume/index.js
Module not found: Error: Can't resolve 'gl-matrix' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\Volume'
 @ ./Sources/Rendering/Core/Volume/index.js 1:0-39 68:18-22 68:59-63 68:100-104 68:141-145 68:182-186 68:223-227 68:264-268 68:305-309 70:17-21 71:6-10 73:15-19
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Common/Core/DataArray' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 21:0-46
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/VolumeMapper/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Common/Core/Math' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\VolumeMapper'
 @ ./Sources/Rendering/Core/VolumeMapper/index.js 2:0-59 16:21-54
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Common/Core/Points' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 20:0-43
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Common/DataModel/PolyData' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 22:0-50
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Interaction/Style/InteractorStyleTrackballCamera' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 18:0-112 39:38-71
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/Actor' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 23:0-45
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/Mapper' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 24:0-46
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/Volume/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/Prop3D' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\Volume'
 @ ./Sources/Rendering/Core/Volume/index.js 3:0-61 137:2-11
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/RenderWindow' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 16:0-73 31:23-38
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/RenderWindowInteractor' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 17:0-93 38:21-46
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/Renderer' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 15:0-65 32:19-30
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/VolumeMapper/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/VolumeMapper/Constants' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\VolumeMapper'
 @ ./Sources/Rendering/Core/VolumeMapper/index.js 3:0-77 4:16-25
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/Volume/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/Core/VolumeProperty' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\Volume'
 @ ./Sources/Rendering/Core/Volume/index.js 4:0-77 17:27-44
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/Rendering/OpenGL/RenderWindow' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 14:0-81 35:29-50
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/Volume/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/macro' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\Volume'
 @ ./Sources/Rendering/Core/Volume/index.js 2:0-41 5:20-25 140:2-7 142:2-7 143:2-7 144:2-7 149:25-30
 @ ./src/index.js

ERROR in ./Sources/Rendering/Core/VolumeMapper/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/macro' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Core\VolumeMapper'
 @ ./Sources/Rendering/Core/VolumeMapper/index.js 1:0-41 49:11-16 71:2-7 72:2-7 73:2-7 74:2-7 75:2-7 80:25-30
 @ ./src/index.js

ERROR in ./Sources/Rendering/Misc/genericRenderWindow/index.js
Module not found: Error: Can't resolve 'vtk.js/Sources/macro' in 'C:\dv-project\node_modules\vtk.js\Sources\Rendering\Misc\genericRenderWindow'
 @ ./Sources/Rendering/Misc/genericRenderWindow/index.js 13:0-41 73:24-29 95:2-7 96:2-7 97:2-7 102:25-30
 @ ./src/index.js

**Comment by jourdain** [comment]
You are not supposed to build vtk.js from its distribution directory. If you want to build it, you should download the sources from the repo.

**Comment by SohailButt** [comment]
> You are not supposed to build vtk.js from its distribution directory. If you want to build it, you should download the sources from the repo.

Thanks A lot sir! it worked! in fact I have already done that.

Much appreciated!
