### ISSUE TITLE
TypeError: image.getDimensions is not a function

### ISSUE THREAD

**Issue by AlexTerry1024** [Kitware/vtk-js#1583]
Hello, How are you today?

When I use VolumeMapper, I am getting this error
What is wrong from my code?

Thank you.

Regards.

Here is my code

import React, { useState, useRef } from "react";
var vtkFullScreenRenderWindow = require("vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow");
// import VtkLandAnalyzerStyle from "../../styles/VtkLandAnalyzer";
var vtkActor = require("vtk.js/Sources/Rendering/Core/Actor");
var vtkMapper = require("vtk.js/Sources/Rendering/Core/Mapper");
var vtkColorTransferFunction = require("vtk.js/Sources/Rendering/Core/ColorTransferFunction");

var vtkPolyData = require("vtk.js/Sources/Common/DataModel/PolyData");
var vtkDataArray = require("vtk.js/Sources/Common/Core/DataArray");
var vtkOpenGLRenderWindow = require("vtk.js/Sources/Rendering/OpenGL/RenderWindow");
var vtkRenderWindowInteractor = require("vtk.js/Sources/Rendering/Core/RenderWindowInteractor");
var vtkInteractorStyleTrackballCamera = require("vtk.js/Sources/Interaction/Style/InteractorStyleTrackballCamera");
var vtkRenderWindow = require("vtk.js/Sources/Rendering/Core/RenderWindow");
var vtkRenderer = require("vtk.js/Sources/Rendering/Core/Renderer");
var vtkVolume = require("vtk.js/Sources/Rendering/Core/Volume");
var vtkVolumeMapper = require("vtk.js/Sources/Rendering/Core/VolumeMapper");
var vtkPiecewiseFunction = require("vtk.js/Sources/Common/DataModel/PiecewiseFunction");

interface IProps { }

const VtkLandAnalyzer: React.FC<IProps> = ({ }: IProps) => {
  
  const [containerEl] = useState(document.createElement('div'));
  const [fullScreenRenderer] = useState(vtkFullScreenRenderWindow.newInstance());
  const [polydata] = useState(vtkPolyData.newInstance());
  const [actor] = useState(vtkVolume.newInstance());
  
  const [mapper] = useState(vtkVolumeMapper.newInstance());
  const [openglRenderWindow] = useState(vtkOpenGLRenderWindow.newInstance());
  const [renderWindow] = useState(fullScreenRenderer.getRenderWindow());
  
  mapper.setSampleDistance(1.1);

  actor.setMapper(mapper);

  const getColorFromIndex = (colors: any, index: any) => {
    return {
      r: colors[index * 3], g: colors[index * 3 + 1], b: colors[index * 3 + 2]
    }
  }

  containerEl.style.width = "100%";
  containerEl.style.height = "100%";

  const vertex: any = [...]
  const indexBuffer: any = [...]
  const colorBuffer: any = [...];

  var vertexArray = [];
  var polysArray = [];

  for (var i = 0; i < vertex.length; i = i + 4) {
    vertexArray.push(vertex[i], vertex[i + 1], vertex[i + 2], vertex[i + 3]);
  }

  for (var i = 0; i < indexBuffer.length; i = i + 4) {
    polysArray.push(4, indexBuffer[i], indexBuffer[i + 1], indexBuffer[i + 2], indexBuffer[i + 3]);
  }

  polydata.getPoints().setData(Float32Array.from(vertex), 3);
  polydata.getPolys().setData(Uint16Array.from(polysArray), 1);

  const colorData = vtkDataArray.newInstance({
    name: 'Colors',
    values: new Float32Array(polydata.getPoints().getNumberOfTuples() * 4),
    numberOfComponents: 4,
  });

  for (let index = 0; index < colorData.getNumberOfTuples(); index++) {
    let indexedColor = getColorFromIndex(colorBuffer, index);

    colorData.setTuple(index, [indexedColor.r, indexedColor.g, indexedColor.b, 1])
  }
  colorData.modified();

  polydata.getPointData().setScalars(colorData);
  polydata.getPointData().setActiveScalars('Colors');
  polydata.getPointData().modified();

  const ctfun = vtkColorTransferFunction.newInstance();
  ctfun.addRGBPoint(0, 85 / 255.0, 0, 0);
  ctfun.addRGBPoint(95, 1.0, 1.0, 1.0);
  ctfun.addRGBPoint(225, 0.66, 0.66, 0.5);
  ctfun.addRGBPoint(255, 0.3, 1.0, 0.5);
  const ofun = vtkPiecewiseFunction.newInstance();
  ofun.addPoint(0.0, 0.0);
  ofun.addPoint(255.0, 1.0);
  actor.getProperty().setRGBTransferFunction(0, ctfun);
  actor.getProperty().setScalarOpacity(0, ofun);
  actor.getProperty().setScalarOpacityUnitDistance(0, 3.0);
  actor.getProperty().setInterpolationTypeToLinear();
  actor.getProperty().setUseGradientOpacity(0, true);
  actor.getProperty().setGradientOpacityMinimumValue(0, 2);
  actor.getProperty().setGradientOpacityMinimumOpacity(0, 0.0);
  actor.getProperty().setGradientOpacityMaximumValue(0, 20);
  actor.getProperty().setGradientOpacityMaximumOpacity(0, 1.0);
  actor.getProperty().setShade(true);
  actor.getProperty().setAmbient(0.2);
  actor.getProperty().setDiffuse(0.7);
  actor.getProperty().setSpecular(0.3);
  actor.getProperty().setSpecularPower(8.0);

  mapper.setInputData(polydata);

  var renderer = fullScreenRenderer.getRenderer();
  renderer.addVolume(actor);
  renderer.resetCamera();

  renderer.getActiveCamera().zoom(1.5);
  renderer.getActiveCamera().elevation(70);
  renderWindow.render();

  return <div ref={(ref: any) => ref.appendChild(containerEl)}></div>;
}

export default VtkLandAnalyzer;

**Comment by jourdain** [comment]
vtk.js support 2 types of rendering "Geometry" and "Volume". The geometry one is for triangles type of surface mesh. Volume is for a 3D grid where we want to see through via some transfer function. 

In your case, you have a geometry which means you can not do Volume rendering but Geometry rendering. You can not use one rendering technic with the other data type.

**Comment by AlexTerry1024** [comment]
There is any way to convert from Geometry to Volume?
Thank you.

Regards.

**Comment by jourdain** [comment]
Could you explain what you are trying to do? If you have a 3d mesh with 3d cells you could resample it to a grid so you can do volume rendering. But it seems that you only have surface mesh and therefor, doing volume rendering does not make much sense. Hence my question. Maybe it is just calling something with another name that is getting you confused.

**Comment by AlexTerry1024** [comment]
const vertex: any = [
    0.5, 0.5, 95.1768,
    0.5, 0.5, 94.1558,
    0.5, 1.5, 95.0291,
    0.5, 1.5, 94.0119,
    1.5, 0.5, 95.1833,
    1.5, 0.5, 94.1621,
    1.5, 1.5, 95.0529,
    1.5, 1.5, 94.0351,
  ];
  const indexBuffer: any = [0, 1, 2, 3, 4, 5, 6, 7];
  const colorBuffer: any = [
    0.0,
    0.62352943,
    1.0,
    0.0,
    0.2509804,
    1.0,
    0.1254902,
    0.0,
    1.0,
    0.1254902,
    1.0,
    0.0,
    0.0,
    1.0,
    0.2509804,
    0.0,
    1.0,
    0.2509804,
    0.0,
    0.62352943,
    1.0,
    0.0,
    0.62352943,
    1.0,
  ];

  const customIndexBuffer: any = [3, 1, 0, 2, 7, 5, 4, 6,]
  const polysArray = [];

  for (var i = 0; i < customIndexBuffer.length; i = i + 8) {
    polysArray.push(12, customIndexBuffer[i], customIndexBuffer[i + 1], customIndexBuffer[i + 2], customIndexBuffer[i + 3], customIndexBuffer[i + 4], customIndexBuffer[i + 5], customIndexBuffer[i + 6], customIndexBuffer[i + 7]);
  }

  polydata.getPoints().setData(Float32Array.from(vertex), 3);
  polydata.getPolys().setData(Uint16Array.from(polysArray), 1);

  const colorData = vtkDataArray.newInstance({
    name: "Colors",
    values: new Float32Array(polydata.getPoints().getNumberOfTuples() * 1),
    numberOfComponents: 1,
  });

  for (let index = 0; index < colorData.getNumberOfTuples(); index++) {
    const indexedColor = getColorFromIndex(colorBuffer, index);

    colorData.setTuple(index, [indexedColor.r, indexedColor.g, indexedColor.b, 1]);
  }
  colorData.modified();

  polydata.getPointData().setScalars(colorData);
  polydata.getPointData().setActiveScalars("Colors");
  polydata.getPointData().modified();

  mapper.setInputData(polydata);

  actor.setMapper(mapper);

  // var renderer = fullScreenRenderer.getRenderer();
  renderer.addActor(actor);
  renderer.resetCamera();

  renderWindow.addView(openglRenderWindow);

**Comment by AlexTerry1024** [comment]
![Screenshot at Nov 10 00-19-37](https://user-images.githubusercontent.com/31697138/98567030-7117aa00-22ea-11eb-81ac-fec315a62569.png)
From this code, I wanted to get this model

**Comment by AlexTerry1024** [comment]
![image](https://user-images.githubusercontent.com/31697138/98567107-85f43d80-22ea-11eb-9c9f-d7335befeef5.png)
But Currently, I am getting this. What is wrong?

**Comment by jourdain** [comment]
You are using a 3D cell (hexahedron) that can only exist on unstructured grid. Here you have a polydata which only handles 2d cells (vertex, line, polys, triangle strips).

To create your cube, you needs to define 6 polys faces/cells.
