### ISSUE TITLE
Uncaught ReferenceError: vtkFullScreenRenderWindow is not defined. Please help!!

### ISSUE THREAD

**Issue by SohailButt** [Kitware/vtk-js#1584]
Uncaught ReferenceError: vtkFullScreenRenderWindow is not defined

**Comment by SohailButt** [comment]
> Uncaught ReferenceError: vtkFullScreenRenderWindow is not defined

I am using the same build you have suggested to me

**Comment by jourdain** [comment]
No relevant information to help understand the issue.

Please explain what you are doing so we can understand the origin of a possible problem.
So far, this looks like a user error. We can't fix users, but we can try to fix our software/documentation.

On the other hand we can not take the responsibility to provide a documentation on JS fundamentals or teach you how to code or use software/code from others. 

I hope you can understand.

Thanks,

Seb

**Comment by SohailButt** [comment]
Thanks for your reply. I am trying to execute this example.

https://kitware.github.io/vtk-js/examples/OBJReader.html

I am referencing all libraries like this.


import macro from '../Sources/macro';
console.log("loaded", macro);

import vtkFullScreenRenderWindow from '../Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkConeSource from '../Sources/Filters/Sources/ConeSource';
import vtkVolumeMapper from '../Sources/Rendering/Core/VolumeMapper';
import vtkActor from '../Sources/Rendering/Core/Actor';
import vtkMapper from '../Sources/Rendering/Core/Mapper';
import vtkMTLReader from '../Sources/IO/Misc/MTLReader';
import vtkOBJReader from '../Sources/IO/Misc/OBJReader';


vtk.js loads fine but other imports are not working.

**Comment by jourdain** [comment]
It looks like you import path may not be right or your build system is not correctly configured.

If you are inside vtk.js root directory you can run the following command to execute and run that example:

```
npm install
npm run example -- OBJReader
```

**Comment by SohailButt** [comment]
If the import path is wrong then why is the vtk.js file loaded? this is the
issue I am having and it's a really strange one.  Please see this
screenshot below.

[image: image.png]

**Comment by SohailButt** [comment]
I am following each and every single step mentioned on their site and yet
it's not working!

**Comment by jourdain** [comment]
Which step do you follow? If we have that info we could guide you?

Since you said, "the vtk.js file loaded" does that mean that you should follow that [guide](https://kitware.github.io/vtk-js/docs/intro_vtk_as_external_script.html)?

Otherwise, was it that [guide](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) that you used?

**Comment by SohailButt** [comment]
Ok here is the thing. I followed this guide.

https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

Then I also watched a tutorial video and went through these slides (both
are same)
https://docs.google.com/presentation/d/17TCS6EhFi6SWFIrcAJ-DFdFzFFL-WD9BBTv-owmMdDU/edit#slide=id.g5f40cc204f_0_164

I also managed to load that initial cone example successfully but put all
my imports in index.js file and code in index.html and both these files are
in dist folder. Complete path below.

dv-project/node_modules/vtk.js/dist

I again want to thank you for your keen interest as I am also keen and in
fact anxious to set this up on my laptop and start working on my project.
Actually I am a wordpress developer and learning vtk.js for a project.

Looking forward to hearing from you.

Many thanks!

**Comment by jourdain** [comment]
Oh so the issue is your import (Like I said).

You need to replace `from '../` by `from 'vtk.js/` like written in the documentation. 

Maybe you should re-read the guide without changing it.

**Comment by SohailButt** [comment]
Nothing worked for me sir, I  have gone through all the documentation again but no success so far. Its very very strange that with the same path vtk.js loads fine that is ../Source/marco
but fails to load other modules.

**Comment by jourdain** [comment]
I just followed the guide, step by step and it is working great. 

Please start again and try to follow each commands, file creation/edits listed in the document. Do not change anything just because you know better.

If you follow that guide correctly you should have the content of the attached zip + a `node_modules/` directory.
[MyWebProject.zip](https://github.com/Kitware/vtk-js/files/5250089/MyWebProject.zip)

If you want to run the zip I shared, you can do

```
cd MyWebProject
npm install
npm start
```

**Comment by SohailButt** [comment]
Hi there Sir,

Please accept my sincere apologies for the delayed response. I successfully
loaded all the modules and resolved loading issues after your guidance.

I just can't thank you enough.

Stay blessed.

Best Regards,
Sohail
