### ISSUE TITLE
How to resize actor

### ISSUE THREAD

**Issue by Seeker93** [Kitware/vtk-js#1589]
Hi guys. I have defined a vtkImageSlice like this:

```
        const renderWindow = vtkRenderWindow.newInstance(); //Now uses RenderWindow instead of Fullscreen render window
        var scalars = vtkDataArray.newInstance({
            values: rgbArray,
            numberOfComponents: 3, // number of channels
            dataType: VtkDataTypes.UNSIGNED_CHAR, // values encoding
            name: 'scalars'
        });

        var imageData = vtkImageData.newInstance();
        imageData.setOrigin(0, 0, 0);
        imageData.setSpacing(1.0, 1.0, 1.0);
        imageData.setExtent(0, width - 1, 0, height - 1, 0, depth - 1);
        imageData.getPointData().setScalars(scalars);

        var mapper = vtkImageMapper.newInstance();
        mapper.setInputData(imageData);

        var actor = vtkImageSlice.newInstance();
        actor.setMapper(mapper);

        var view3d = document.getElementById("view3d");

        const openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
        openglRenderWindow.setContainer(view3d)

        const dims = view3d.getBoundingClientRect();
        openglRenderWindow.setSize(dims.width, dims.height)

        renderWindow.addView(openglRenderWindow);

        const sliceRenderer = vtkRenderer.newInstance({
            background: [255, 255, 255]
        });

        sliceRenderer.addVolume(actor);
        renderWindow.addRenderer(sliceRenderer) 
        renderWindow.render();
```

I would like to resize this actor to fit my renderwindow.

However, I can't find any way to change it's actual size?

**Comment by jourdain** [comment]
That is the point of calling `renderer.resetCamera()`

**Comment by Seeker93** [comment]
I am calling resetCamera() in my current implementation, but I am still met with this: 
![Screenshot from 2020-09-23 16-22-15](https://user-images.githubusercontent.com/5177086/94025876-48c70100-fdb9-11ea-8012-68912ccd4a57.png) The black section is the render window. 

I need the height of the image slice to fit exactly in the renderWindow height. Is there a way to do this?

**Comment by jourdain** [comment]
That is expected but if you look at the implementation of the `resetCamera()` you will see that we have an overshoot on purpose. You can reproduce the code without that overshoot.

**Comment by wmxj** [comment]
try:
this.renderer.getActiveCamera().zoom(1.2);

**Comment by jourdain** [comment]
If this is still an issue, please re-open.

**Comment by gaston-perret** [comment]
> 
> 
> That is expected but if you look at the implementation of the `resetCamera()` you will see that we have an overshoot on purpose. You can reproduce the code without that overshoot.

Could provide me some guidance on this overshoot you are talking about. I looked at the resetCamera method and I can't find it in there.

**Comment by jourdain** [comment]
`renderer.resetCamera()`

**Comment by gaston-perret** [comment]
> 
> 
> `renderer.resetCamera()`

thank you for replying, thats the method I am looking at. But I don't see anything about an overshoot for the camera.

**Comment by jourdain** [comment]
Hum indeed... I thought there was a 1.1 scaling of some kind but I can't see it either. @martinken any idea?

**Comment by martinken** [comment]
It is the clippingRange and the ivar that controls it is 

model.clippingRangeExpansion

**Comment by martinken** [comment]
in resetCamera()

// default so that the bounding sphere fits within the view fustrum

The view is scaled so that a sphere encapsulating your data fits the view.
