### ISSUE TITLE
ImageSlice - setSlicing not working as in the example

### ISSUE THREAD

**Issue by AimalAzmi** [Kitware/vtk-js#1592]
I am trying to duplicate a scenario similar to Paraview glance, where we have 4 render windows, one contains the 3d image and the other three render windows contain the image slices. I am using the IMAGE_SLICING interaction mode as well on the slicing render windows and it works fine. 

I would like to use a similar mechanism where I can move the slices using the sliders we have in the left navbar similar to Paraview Glance but after several tries I am unable to update the slices using the api. I am following [MultiSliceImageMapper](https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html) for this part.

I have tried using `imageMapper.setISlice(Number($val));` but it does not work, similarly for the J and K slices.

**Slice creation code**
`const sliceActor = {};
const imageMapper = {};
const lookupTable = vtkColorTransferFunction.newInstance();
lookupTable.addRGBPoint(0, 85 / 255.0, 0, 0);
lookupTable.addRGBPoint(95, 1.0, 1.0, 1.0);
lookupTable.addRGBPoint(225, 0.66, 0.66, 0.5);
lookupTable.addRGBPoint(255, 0.3, 1.0, 0.5);
const piecewiseFunction = vtkPiecewiseFunction.newInstance();
piecewiseFunction.addPoint(0.0, 0.0);
piecewiseFunction.addPoint(255.0, 1.0);
		
['X', 'Y', 'Z'].map((axis) => {
	sliceActor[axis] = vtkImageSlice.newInstance();
	sliceActor[axis].getProperty().setRGBTransferFunction(0, lookupTable);
	sliceActor[axis].getProperty().setScalarOpacity(0, piecewiseFunction);
	sliceActor[axis].getProperty().setInterpolationTypeToLinear();
	imageMapper[axis] = vtkImageMapper.newInstance();
	sliceActor[axis].setMapper(imageMapper[axis]);
})
		
this.sliceActor = sliceActor;
this.sliceMapper = imageMapper;`

**Setting the slicing modes**

`
switch (this.props.slice) {
	case "X":
		imageMapper.setISlice(30);
		break;
	case "Y":
		imageMapper.setJSlice(30);
		break;
	case "Z":
	        imageMapper.setKSlice(30);
		break;
}
`

Also, since I am adding all the slices onto the 3d render view as well, I would like to move them as they are being done in Paraview glance when I either move the sliders or by moving the mouse wheel while being the slice window.

Thanks

**Comment by floryst** [comment]
Are you calling `renderWindow.render()` after every time you call `set[IJK]Slice(...)`?

**Comment by AimalAzmi** [comment]
> Are you calling `renderWindow.render()` after every time you call `set[IJK]Slice(...)`?

Yes, I am.

**Comment by AimalAzmi** [comment]
`const renderWindow = vtkRenderWindow.newInstance();
			const renderer = vtkRenderer.newInstance({
				background: [0, 0, 0],
			});
			
			const openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
			
			renderWindow.addRenderer(renderer);
			renderWindow.addView(openglRenderWindow);
			
			const {height, width} = this.container.current.getBoundingClientRect();
			openglRenderWindow.setContainer(container);
			openglRenderWindow.setSize(width, height);
			
			const interactor = vtkRenderWindowInteractor.newInstance();
			interactor.setView(openglRenderWindow);
			interactor.initialize();
			interactor.bindEvents(container);
			interactor.setInteractorStyle(
				vtkInteractorStyleTrackballCamera.newInstance()
			);
			renderer.addActor(sliceActor);
			
			const iStyle = vtkInteractorStyleImage.newInstance();
			iStyle.setInteractionMode("IMAGE_SLICING");
			imageMapper.setSliceAtFocalPoint(true);
			
			renderWindow.getInteractor().setInteractorStyle(iStyle);
			
			const camera = renderer.getActiveCamera();
			camera.setPosition(
				axis.cameraSettings.position[0],
				axis.cameraSettings.position[1],
				axis.cameraSettings.position[2],
			);
			camera.roll(axis.cameraSettings.roll);
			camera.setParallelProjection(true);
			
			renderer.resetCamera();`

**Comment by floryst** [comment]
Are those hardcoded `30` values present in your codebase? Or did you just type them in as a demonstration?

Your slice setup/creation code looks good to me. Can you post the relevant code where you bind your slider events to setting the slice?

**Comment by AimalAzmi** [comment]
Yes initially I hard code each slice to 30. 

Actually before binding that to the sliders, I wanted to try it out through the api from the web console. I have set the actor to a global scope so it is accessible through the chrome console and then I have been trying this code to set the slices but its not working.

`sliceActor.X.getMapper().setISlice($val);`
`renderWindow.render();`

So, if this api worked I would have hooked it with the slider onChange event but no luck so far. Neither the slice render window shows any change nor the 3d render window.

Thanks

**Comment by AimalAzmi** [comment]
Any updates regarding this would be very helpful!

Thanks

**Comment by floryst** [comment]
Oh, did you set `imageMapper.setSliceAtFocalPoint(true)`? That will cause the slices to be sliced at the camera focal point, rather than from your setSlice calls.

**Comment by AimalAzmi** [comment]
Yes, I am using that. But if I remove that the slices are not positioned properly then. What would be the workaround for this?

Thanks

**Comment by AimalAzmi** [comment]
> Oh, did you set `imageMapper.setSliceAtFocalPoint(true)`? That will cause the slices to be sliced at the camera focal point, rather than from your setSlice calls.

Yeah, that was the issue. Resolved.

Thanks a lot!

**Comment by AimalAzmi** [comment]
Setting the setSliceAtFocalPoint to false does make the setSlice method work but, if I set it to false the interaction manipulators that I have assigned to the render screen dont function anymore (I am guessing since the camera is not at the focal point maybe). Any workarounds this?

**Comment by floryst** [comment]
`vtkInteractorStyleImage` manipulates camera focus on scroll wheel slicing, so it's incompatible with `setSliceAtFocalPoint(false)`. Instead of using `vtkInteractorStyleImage`, check out [`vtkMouseRangeManipulator`](https://kitware.github.io/vtk-js/examples/MouseRangeManipulator.html). That should be compatible with using `setSlice`.

**Comment by AimalAzmi** [comment]
I am using `vtkInteractorStyleManipulator`, is it also not compatible? Following is a piece of code from my implementation that is working fine with `setSliceAtFocalPoint(false)` but not working without it.

`const interactorStyle = vtkInteractorStyleManipulator.newInstance();`

`const sliceManipulatorScroll = vtkMouseCameraSliceManipulator.newInstance();`
`sliceManipulatorScroll.setDragEnabled(false);`
`sliceManipulatorScroll.setScrollEnabled(true);`

`interactorStyle.addMouseManipulator(sliceManipulatorScroll);`

`renderWindow.getInteractor().setInteractorStyle(interactorStyle);`

**Comment by floryst** [comment]
You should be using the vtkMouseRangeManipulator, which calls setSlice. See the [vtkMouseRangeManipulator example](https://kitware.github.io/vtk-js/examples/MouseRangeManipulator.html) for a demonstration of this. The vtkMouseCameraSliceManipulator depends on `setSliceAtFocalPoint(true)`, as it only moves the camera's focal point.

**Comment by AimalAzmi** [comment]
Thank you very much for your help so far. It works very well now!
