### ISSUE TITLE
LineWidget wishlist 

### ISSUE THREAD

**Issue by ocrossi** [Kitware/vtk-js#1593]
**Coming upgrades for the Line Widget**
These are the next features to be developed on the Line Widget, ranked by priority
- [x] Rotate the 2D handles with the camera
- [x] Implement None Handle to match an invisible sphere
- [x] Add UI
- [x] implement Right to Left/ Left to Right behavior for SVG Layer
- [ ] implement pickable poly line to move the widget all in one drag
- [x] keep steady size during handle mouse over
- [x]  Add a Disk handle
- [x] Hide Poly Line behind the handle
- [x] add rotation feature to CircleHandle
- [x] resolve bug text doesn't move when there is a circle handle
- [ ] size of handles to fix when scaleInPixels is deactivated

**Comment by ocrossi** [comment]
@finetjul

**Comment by finetjul** [comment]
> - [ ]  keep steady size during handle mouse over

Size can increase on mouse over, however center of scaling should be in a way to not "move" the line extremity

> - [ ]   Rotate the 2D sources of the line with the camera
> - [ ]   add 2d positioning of handles to rotate the position of a handle with the camera

I do not understand the difference between those two points

- [ ] Add UI for example
