### ISSUE TITLE
ImageCroppingWidget not working properly

### ISSUE THREAD

**Issue by xavArtley** [Kitware/vtk-js#1594]
Hello I was trying the https://kitware.github.io/vtk-js/examples/ImageCroppingWidget/index.html example
However it appears not to work

![cropwidget](https://user-images.githubusercontent.com/18531147/94944337-67c04400-04d9-11eb-90b3-00c3dc61458b.gif)

**Comment by floryst** [comment]
Thanks for the report! It appears to only affect face cropping, so I'll take a look at that.
