### ISSUE TITLE
Incompatibility with latest worker-loader package

### ISSUE THREAD

**Issue by paologf** [Kitware/vtk-js#1596]
Hello, 
I have an issue creating a project with vuejs about the compatibility of `worker-loader` and `vtk.js` package.
Using the latest version of `vtk.js` and a version of `worker-loader` >= 3.0.0 I got the following error:
```
 error  in ./node_modules/vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker.js

Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'fallback'. These properties are valid:
   object { worker?, publicPath?, filename?, chunkFilename?, inline?, esModule? }
 - options.inline should be one of these:
   "no-fallback" | "fallback"
    at validate (./vtk-test/node_modules/schema-utils/dist/validate.js:98:11)
    at Object.pitch (./vtk-test/node_modules/worker-loader/dist/index.js:57:28)

```

, decreasing the worker-loader version to 2.0.0 everything works.

Do you have any idea if there is some configuration I'm missing?

[Here](https://github.com/paologf/vtk-test) you could find the sample project.

Thanks

Paolo

**Comment by jourdain** [comment]
Since it is a major version change, we could assume breaking changes. We will need to upgrade our code and dependency to handle it properly. @floryst do you want to take care of it at some point?

**Comment by floryst** [comment]
kw-web-suite is outdated, and needs a new major version bump. I'll create a PR there.

**Comment by finetjul** [comment]
talking about breaking changes, there is another pending commit (ac0a9e873b8b883d380257f40134ff7b445fc7ec) that has breaking changes. I can be extracted from the WIP - but soon to be finished (i.e. end of the week) - MR  if needed.

**Comment by floryst** [comment]
This is resolved with vtk.js v15, as we now use worker-loader >= 3.0.0.
