### ISSUE TITLE
Image Reslice with NodeJS

### ISSUE THREAD

**Issue by jcbuisson** [Kitware/vtk-js#1597]
Hi everyone,

I need to downsample CT scan images on the server side with NodeJS.

The following snippet works fine on the browser :
```
const imageReslice = vtkImageReslice.newInstance()
imageReslice.setInputData(vtkImage)
imageReslice.setOutputSpacing([2., 2., 4.])
vtkImage = imageReslice.getOutputData()
```

However on NodeJS, I get a: `ReferenceError: window is not defined`

Here is a complete NodeJS script to reproduce the error.\
Install `axios`, `vtk.js` and run it with `node -r esm`
```

import axios from 'axios'
import vtkXMLImageDataReader from 'vtk.js/Sources/IO/XML/XMLImageDataReader/index.js'
import vtkImageReslice from 'vtk.js/Sources/Imaging/Core/ImageReslice'

async function main() {
   try {
      const vtiReader = vtkXMLImageDataReader.newInstance();
      console.log("loading...")
      let response = await axios.get("https://appli.liveanatomy.fr/static/liveanatomy/uploads/LIDC2.vti")
      // console.log('response', response.data.substring(0, 500))
      console.log("loaded")

      vtiReader.parseAsArrayBuffer(response.data)
      let vtkImage = vtiReader.getOutputData(0)

      const imageReslice = vtkImageReslice.newInstance()
      imageReslice.setInputData(vtkImage)
      imageReslice.setOutputSpacing([2., 2., 4.])
      let reslicedVtkImage = imageReslice.getOutputData()
      console.log('reslicedVtkImage ok')

   } catch(err) {
      console.log(err.toString())
   }
}

main()
```

**Comment by jourdain** [comment]
@floryst if you can't investigate, I can try to find some time on it.

**Comment by floryst** [comment]
This issue stems from trying to use XML APIs that exist in the browser, but not in node.js. `vtkXMLImageDataReader` (and other parts of vtk.js) is dependent on browser APIs. (See: https://github.com/Kitware/vtk-js/blob/master/Sources/IO/XML/XMLReader/index.js#L14)

That being said, you still might be able to use vtk.js readers and filters in a node.js setting. The easiest way is to bring in [jsdom](https://github.com/jsdom/jsdom) into your environment, though I don't know whether jsdom provides the DOMParser API.

An easy application-side patch to get around this is to install [xmldom](https://www.npmjs.com/package/xmldom), and do the following at application startup:
```js
global.window = global;
global.DOMParser = require('xmldom').DOMParser;
```

I haven't tested this, but it should mostly work. Let me know if you run into more issues regarding the usage of the vtkXMLImageDataReader in node.js.

**Comment by jcbuisson** [comment]
Yes, it works with:
```
global.window = global;
global.DOMParser = require('xmldom').DOMParser;
```
Thank you for a quick answer! I'll let you know if I have other issues with using vtk.js in NodeJS on the server side. Keep the good work!
