### ISSUE TITLE
Export canvas as image #Question

### ISSUE THREAD

**Issue by billcxx** [Kitware/vtk-js#1598]
I'm using vtkjs with react and electron, everything works great, except I couldn't find a way to save the viewport as an image. I read through the doc and examples, but find nothing relevant. I have also tried the canvas.toDataURL() method, but it only gives me an empty image.

Does anybody have any experience with exporting images using vtkjs?

**Comment by xavArtley** [comment]
Suppose the variable `renwin` is your `vtkRenderWindow`

you can do this:
```javascript
renwin.getViews()[0].captureNextImage().then((image_data) => {
 //do what you want with your image data
})
renwin.render()
```

**Comment by jourdain** [comment]
Thanks @xavArtley

**Comment by billcxx** [comment]
Thank you so much! @xavArtley  captureNextImage is exactly what I need

**Comment by chen9uang** [comment]
when i use this api got warning " Unable to clone WebGL context as it has preserveDrawingBuffer=false" and failed ，do you know where to set this property, i didnt find it in this repo @xavArtley

**Comment by Moonsic** [comment]
Thank you so much! @xavArtley
