### ISSUE TITLE
obj-mtl-importer.py and large number of textures 

### ISSUE THREAD

**Issue by micrat** [Kitware/vtk-js#1600]
Hello,
I find that the obj-mtl-importer.py procedure becomes progressively slow during the meshMapping step (increasing the number of textures in the obj file). The following link is an example of obj with a large number of textures, that, after hours of processing is still unfinished: https://www41.zippyshare.com/v/IjcESx6l/file.html

Time for meshMapping texture number 1 is small, and the time progressively increase, to many seconds for texture number 2000. The meshMapping algorithm seem to have a complexity n^2 (where n is the number of textures).

May it could be possible to perform some optimiziation for this specific issue?
Thanks in advance

**Comment by jourdain** [comment]
Feel free to optimize the code, it was mostly given as an example on how this could be done.

**Comment by micrat** [comment]
Thanks, but as I have only two or three of these obj to convert, I will wait until finish the un-optimized conversion (the time to learn pvpython/vtk would be much larger than the time saved due to optimized code)...
Regards

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
