### ISSUE TITLE
rendering multiple volume by using vtkVolumeMapper

### ISSUE THREAD

**Issue by qqsea** [Kitware/vtk-js#1603]
Hi,
Here is the requirement: render multiple volumes in one renderwindow by using vtkVolumeMapper.  The dimentions and thickness for multiple 3d raw data are same. User make interaction on the renderwindow will have same effect on all the raw data.

Could you give me some suggestion on how to implement this requirement? Not only by using vtkVolumeMapper.
Further if the multiple raw data have their own color map and opacity. How to implement?

Thank you very much!

**Comment by floryst** [comment]
You can add multiple vtkVolumes to a renderer, and each can have their own colormap and opacity functions. If you check out the [vtkVolumeMapper example](https://kitware.github.io/vtk-js/examples/VolumeMapper.html), you get the pipeline for adding a single vtkMapper/vtkVolume pair to a renderer. You can create another mapper/volume pair with your other dataset and add it.

Note that right now, multiple volume rendering is not well supported in vtk.js (rendering issues), but it is on our roadmap.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
