### ISSUE TITLE
How to rescale PT, CT and Fusion series to look the same

### ISSUE THREAD

**Issue by laozhu** [Kitware/vtk-js#1609]
If I do nothing, set PT and CT scale equal 1.0, 

- The PT is smaller than CT
- The Fusion is smaller than CT
- The Fusion is the same with PT

```javascript
const camera = renderer.getActiveCamera();
camera.setParallelProjection(true);
renderer.resetCamera();
camera.zoom(1);
```
PT vs CT
![image](https://user-images.githubusercontent.com/1212457/97033025-4234d080-1595-11eb-9b6c-c4fe139643d9.png)

Fusion vs CT
![image](https://user-images.githubusercontent.com/1212457/97034964-3f87aa80-1598-11eb-8fe1-d366f73070a5.png)

PT vs Fusion
![image](https://user-images.githubusercontent.com/1212457/97035106-7067df80-1598-11eb-8576-5f7696993860.png)

If I  want to calculate scale factor of PT relative to CT, how can I make the CT, PT and Fusion looks the same. below is my image size and pixel spacing of PT and CT.

![image](https://user-images.githubusercontent.com/1212457/97034310-4c57ce80-1597-11eb-9ad0-f899a2e561bb.png)

Thank you for any help or infomation :)

**Comment by floryst** [comment]
You can try resampling one of your images to match the other, or you could transform the actor via `actor.setUserMatrix(<4x4 transform matrix>)`. (Using the user matrix will scale the pixel size, so pixels won't match from one image to another, I think.)

**Comment by laozhu** [comment]
Thank you for your reply and sorry for my later response.
I have resamped everty pixel value in PT series to SUV unit, can I transform the width and height at the same time?

**Comment by floryst** [comment]
You can use a resampling filter to get your PT and Fusion images into the same resolution as the CT image. If you can do this prior to loading the datasets into vtk.js, check out using itk-python and the [ResampleImgeFilter](https://itk.org/ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Documentation.html) to resample your images into a common resolution.

**Comment by laozhu** [comment]
Thank you for your suggestion, I will give itk-python a try.

**Comment by scumer** [comment]
hi 请问下你融合是怎么做的？用vtk做的融合？方便介绍下怎么实现的融合吗？谢谢

**Comment by jourdain** [comment]
In english you will have a better chance to get it answered.
