### ISSUE TITLE
How to use attributes of class' 'Constants' ?

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#161]
I tried to access constants used in LandmarkTransform but without success. (Shame on me, I coded this class...). But I don't how to use 'Mode'. For information, I used the generated vtkjs lib.

```
const transform = vtkLandmarkTransform.newInstance();
transform.setMode(Mode.RIGID_BODY);
transform.setSourceLandmark(sourceLandmarks);
transform.setTargetLandmark(targetLandmark);
transform.update();
```

**Comment by jourdain** [comment]
You will be able to do 

```
transform.setMode(vtkLandmarkTransform.Mode.RIGID_BODY);
```

if you expose the constants to the vtkLandmarkTransform module by doing something along 

```
import { Mode, xxx, yyy } from './Constants';
[...]
export default Object.assign({ newInstance, extend },  { Mode, xxx, yyy });
```

**Comment by laurennlam** [comment]
Thank you. It works well !
