### ISSUE TITLE
Extract image data for all slices 

### ISSUE THREAD

**Issue by rafitj** [Kitware/vtk-js#1613]
**I'm trying to figure out a way to slice an image volume on a certain axis and convert the output data into something I can render as images, preferably base64.**

I have looked into `ImageReslice`, `ImageSliceFilter` and a handful other tools but can't seem to figure out what exactly this UInt8 array I'm getting as the output really is and how to use it? It doesn't seem to convert into Base64 easily. **Is there a way to go from vtkDataArray or vtkImageData or vtkImageSlice to base64?**

For context my volume data is rendered correctly and read in as so:
```
const vtiReader = vtkXMLImageDataReader.newInstance();
vtiReader.parseAsArrayBuffer(data);
...
```

**Comment by jourdain** [comment]
yes but base64 is just a string encoding of binary data. If you want an image (jpeg/png), you will have to perform the conversion to a rgba buffer and compress it using the proper algo to finally encode it using base64. 
Canvas can be used to generate images and handle the data conversion and compression.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
