### ISSUE TITLE
Get pointId and Scalar Value for VTI files

### ISSUE THREAD

**Issue by eltopo22** [Kitware/vtk-js#1617]
Hi, I tried using the pointPicker to pick a point from a volume slice. The volume comes in a VTI file and I need to read the Scalar Value of a picked point. I did this with VTP files using pointPicker but now with a VTI file I always get a pointId = -1 when trying to pick.
What do you recommend to be able to pick a point and read its Scalar Value?
Thank you.

**Comment by jourdain** [comment]
from the world xyz, I think you can get the ijk/index of the corresponding point. Then you just need to do the lookup in your vtkDataArray.

**Comment by jourdain** [comment]
The part that I'm note sure is how you pick a point in 3D if you do volume rendering.

**Comment by stephanscheidl** [comment]
Hi, eltopo22, I would be interested in how you managed to do that with VTP files. Can you please post a code example? Thanks, Stephan

**Comment by jourdain** [comment]
On vtp you can look at the hardware selector test to find the point id and then lookup your fields.

**Comment by eltopo22** [comment]
> The part that I'm note sure is how you pick a point in 3D if you do volume rendering.

I did the picking with polydata objects in 3D and I was having trouble to do it in 2D slices of a volume but what you told me about the imageData was exactly what I needed. Thanks a lot

> Hi, eltopo22, I would be interested in how you managed to do that with VTP files. Can you please post a code example? Thanks, Stephan

I mainly used this example as reference and replaced the cone with the output of a polydata reader:
https://kitware.github.io/vtk-js/examples/PointPicker.html

If you have any trouble message me and I'll see if I can help

**Comment by dahuajiejie** [comment]
> > The part that I'm note sure is how you pick a point in 3D if you do volume rendering.
> 
> I did the picking with polydata objects in 3D and I was having trouble to do it in 2D slices of a volume but what you told me about the imageData was exactly what I needed. Thanks a lot
> 
> > Hi, eltopo22, I would be interested in how you managed to do that with VTP files. Can you please post a code example? Thanks, Stephan
> 
> I mainly used this example as reference and replaced the cone with the output of a polydata reader:
> https://kitware.github.io/vtk-js/examples/PointPicker.html
> 
> If you have any trouble message me and I'll see if I can help

hello,i have some proplems want to ask you , Do you have time about this.
