### ISSUE TITLE
Mapping specific point coordinates to SphereMapper with color

### ISSUE THREAD

**Issue by rafitj** [Kitware/vtk-js#1618]
Hi, I am trying to do something which I believe is fairly trivial but am somewhat new - apologies if this is the wrong place for questions.

I have a list of point coordinates `[x1,y1,z1,x2,y2,z2...] ` and also a colours array for each point. I want to use a `SphereMapper` (or something else that makes each point a sphere) and give each point its associated colour from the colours array. I would then want to filter by a colour range.

I have looked into the SphereMapper example. I have set up a `Calculator`, `PointSource` and `SphereMapper` but I can't seem to give my own data to ideally a PointSource (only radius and number of points). I then thought to use just a `DataArray` but that doesn't have an `OutputPort` so I can't connect with the SphereMapper. Is there a better way to be doing this?

For the second part, filtering by a colour range, is there a vtk way to filter or do I have to recreate the data and rerender each time? For instance, in the SphereMapper example is there a way I can efficiently filter by temperature range value?

Thanks so much!

**Comment by jourdain** [comment]
Just add a filter inside your pipeline that remove the cells that you want to hide before the sphere mapper.

**Comment by rafitj** [comment]
Thanks! And any tips for the first part - using a list of point coordinates as data for a point source or in general rendering a list of point coordinates?

**Comment by jourdain** [comment]
```
const coords = [x1, y1, ...];
const polydata = vtkPolyData.newInstance();
polydata.getPoints().setData(Float32Array.from(coords), 3);

const nbPoints = coords.length / 3;
const cells = new Uint16Array(nbPoints + 1);
for (let i = 0; i < nbPoints; i++) {
   cells[1+i] = i;
}
cells[0] = nbPoints;
polydata.getVerts().setData(cells);

const mapper = vtkSphereMapper.newInstance();
mapper.setInputData(polydata);
```

**Comment by jourdain** [comment]
The examples should give you all the rest in term of missing parts.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
