### ISSUE TITLE
How to render a color bar on the window?

### ISSUE THREAD

**Issue by pilifly** [Kitware/vtk-js#1621]
Hello,

Any idea about rendering a color bar with annotations on the window? In C++, I used vtkScalarBarActor, but it is not available in vtk.js.

[
![colorBar](https://user-images.githubusercontent.com/21962033/98492214-24a66e80-2205-11eb-98a8-a688bf09f7d7.PNG)
](url)

Thanks.

Best,
Fei

**Comment by jourdain** [comment]
We don't have such implementation in vtk.js but you can do it using SVG or plain HTML. You can extract an image from the lookup table. After that, it is up to you to put the labels the way you want.

**Comment by pilifly** [comment]
Hi Jourdain,

Thank you very much for the quick response and the suggestion. I will check that.
BTW, is that possible to render the color bar as a 2D actor in vtk.js?

Best,
Fei

**Comment by jourdain** [comment]
not as of today.

**Comment by jourdain** [comment]
Implemented in 17.14

**Comment by xiaoxiao5** [comment]
Hello, how to solve the problem of adding annotation circle on the window?

**Comment by xtecox** [comment]
> We don't have such implementation in vtk.js but you can do it using SVG or plain HTML. You can extract an image from the lookup table. After that, it is up to you to put the labels the way you want.

How can i extract an image from the lookup table?

**Comment by jourdain** [comment]
https://github.com/Kitware/glance/blob/master/src/components/controls/ColorBy/script.js#L26-L34
