### ISSUE TITLE
transparent spheres (opacity and alpha)

### ISSUE THREAD

**Issue by rafitj** [Kitware/vtk-js#1624]
I have 2 sphere mappers - one with multicolor small spheres and one with larger translucent spheres. **I want the larger sphere to be white and translucent so you can see the smaller colourful spheres "inside".** 

However, the translucency doesn't seem to work properly, the larger sphere has a solid background color and I can't see through it. An example is shown below

<img width="400" alt="Screen Shot 2020-11-10 at 11 46 07 PM" src="https://user-images.githubusercontent.com/35117970/98769954-12683400-23af-11eb-82b9-e6106f196fcc.png">

<img width="400" alt="Screen Shot 2020-11-10 at 11 46 15 PM" src="https://user-images.githubusercontent.com/35117970/98769953-11cf9d80-23af-11eb-8a0c-031d1ad8d096.png">

I have tried two things with identical results:

1. Have the color array in my filter have 4 components RGBA:
```
getArrays: (inputDataSets: any) => ({
        input: [{ location: FieldDataTypes.COORDINATE }],
        output: [
          {
            location: FieldDataTypes.POINT,
            name: 'color',
            dataType: 'Float32Array',
            attribute: AttributeTypes.SCALARS,
            numberOfComponents: 4,
          },
          ...
        ],
  }),
...
evaluate: (arraysIn: any, arraysOut: any) => {
        const [coords] = arraysIn.map((d: any) => d.getData());
        const [color] = arraysOut.map((d: any) => d.getData());
        for (let i = 0; i < (coords.length / 3)*4 ; i+=4) {
          color[i] = 1;
          color[i + 1] = 1;
          color[i + 2] = 1;
          color[i + 3] = 0.25; // desired alpha
        }
        arraysOut.forEach((x: any) => x.modified());
}
mapper.setColorByArrayName('color');
```

2. Change the actor property only (and use a 3 component RGB color array):
` mapper.getLookupTable().setAlpha(0.25)`

I'm not sure if I'm doing something wrong like not setting the correct colour mode or scalar mode or use a LUT? Or is this a general non-feature of multi-volume translucent rendering.

**Comment by jourdain** [comment]
Your RGBA should be Uint8 not Float32.
Also, you need to tell the mapper to not convert the color field to a color. It should use that field as-is without any use of a lookup table.

**Comment by rafitj** [comment]
Thanks for the response!

I tried the above - changing to Uint8 but it doesn't seem to work, still getting solid sphere.
```
getArrays: (inputDataSets: any) => ({
        input: [{ location: FieldDataTypes.COORDINATE }],
        output: [
          {
            location: FieldDataTypes.POINT,
            name: 'color',
            dataType: 'Uint8Array',
            attribute: AttributeTypes.SCALARS,
            numberOfComponents: 4,
          },
          ...
        ],
  }),
...
evaluate: (arraysIn: any, arraysOut: any) => {
        const [coords] = arraysIn.map((d: any) => d.getData());
        const [color] = arraysOut.map((d: any) => d.getData());
        for (let i = 0; i < (coords.length / 3)*4 ; i+=4) {
          color[i] = 255;
          color[i + 1] = 255;
          color[i + 2] = 255;
          color[i + 3] = 0.25*255; // desired alpha
        }
        arraysOut.forEach((x: any) => x.modified());
}
mapper.setColorByArrayName('color');
```

![Screen Shot 2020-11-11 at 4 21 30 PM](https://user-images.githubusercontent.com/35117970/98866098-6a984800-243a-11eb-9db4-3c962c62fbbe.png)
![Screen Shot 2020-11-11 at 4 21 34 PM](https://user-images.githubusercontent.com/35117970/98866101-6bc97500-243a-11eb-9dfd-941218b8b4a6.png)

Not sure what you mean by telling the mapper to not convert the color field since the documentation says the following: _"By
default (ColorModeToDefault), unsigned char scalars are treated as colors, and NOT mapped through the lookup table"_ and I'm already using default colorMode. I also tried playing with colorMode and scalarMode, but neither of the below.
```
mapper.setColorModeToDirectScalars();
mapper.setScalarModeToUsePointFieldData();
```

**Comment by jourdain** [comment]
`mapper.setColorModeToDirectScalars();` should have done the trick. 

But which mapper are you using? If it is the sphere one, it may not work with transparency.

**Comment by jourdain** [comment]
@martinken is the SphereMapper supposed to handle RGBA?

**Comment by martinken** [comment]
The code looks like case 2 should work, not case 1. Try actor.setForceTranslucent(true) and see if that gets what you are looking for.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
