### ISSUE TITLE
Turn off rotation linewidget in ImplicitPlaneWidget

### ISSUE THREAD

**Issue by AimalAzmi** [Kitware/vtk-js#1630]
Hi, I am using the [ImplicitPlaneWidget](https://kitware.github.io/vtk-js/examples/ImplicitPlaneWidget.html) as described in the example in my application and it works fine.

I would like to only turn off the Red LineWidget that is used for plane rotation. I have looked thoroughly at the available methods from the vtkImplicitPlaneWidget class but haven't been able to find a solution.

Is there a way to do it? **(Apologies in advance if I am missing something very basic)**

Thanks!

**Comment by jourdain** [comment]
We don't have it on our API but that is a good idea and that should be easy to add.

FYI @floryst

**Comment by AimalAzmi** [comment]
Thank you! Waiting on this feature then! 😃
