### ISSUE TITLE
Using vtk.js as an ES6 dependency

### ISSUE THREAD

**Issue by pierre441999** [Kitware/vtk-js#1632]
I have followed a tutorial ([https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html#Webpack-config]) to build an application vtk.js and I have created the project structure and the different packages. When I want to build the application with the command : 'npm run build' I have an error message that says 'Unexpected identifier'.

**Comment by jourdain** [comment]
See https://github.com/Kitware/vtk-js/issues/1584#issuecomment-695262557 for any differences.

Please post the full error as it is hard to understand what is going on with only 2 words and fairly limited context.

**Comment by pierre441999** [comment]
With the command 'npm run build'  : 

![Capture d’écran 2020-11-18 à 16 38 20](https://user-images.githubusercontent.com/728

With the command 'npm start' :  

![Capture d’écran 2020-11-18 à 16 38 49](https://user-images.githubusercontent.com/72804528/99551924-b740cd80-29bc-11eb-8756-ab452c28b868.png)
04528/99551903-b1e38300-29bc-11eb-8929-ace0942dbc73.png)

**Comment by jourdain** [comment]
Hum, I'm wondering if it is not related to https://github.com/Kitware/vtk-js/issues/1209#issuecomment-729768950 as well.

FYI @floryst

**Comment by pierre441999** [comment]
It's working with your attached zip MyWebProject.zip, thank you very much
