### ISSUE TITLE
Run STL reader example

### ISSUE THREAD

**Issue by HugoPrin** [Kitware/vtk-js#1637]
Hello everyone, 
I'm new to using vtk.js. I installed the all thing using the file 'MyWebProject.zip' provided by @jourdain  and followed several tutorials. But I don't know in what file do I need to put the code of the STL reader example. For now, I have a dist/index.html, dist/MyWebApp.js , src/controller.html and a src/index.js. My project is running at port:  http://localhost:8081/ and opening the index.html displays the cone example.

I'd really appreciated your help, Thank you

**Comment by jourdain** [comment]
The main file to edit is the one you find in any the example page. Which is inside ./src/index.js if you follow the ES6 tutorial.
