### ISSUE TITLE
Making widgets visible on axial view

### ISSUE THREAD

**Issue by juanlaCS** [Kitware/vtk-js#1647]
Hi! We are trying to make handle widgets work in axial views. Specifically we have rulers that are listed very much like kitware's paraview glance. 
We can successfully hide these handle widgets but when a ruler is clicked in the listed toolbar to move to that axial view position, the rulers aren't shown unless we hover with the mouse over the renderer.

Is this correct? Using setvisibility to true on a widget. Can we refresh somehow the renderer? Renderwindow.render doesnt seem to be doing the trick

Thanks in advance!

**Comment by floryst** [comment]
You might also need to call `widgetManager.renderWidgets()` for that renderer as well. Let me know if that works for you.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
