### ISSUE TITLE
setUseLabelOutline is not a function -- VolumeOutline example

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#1650]
I'm trying out the `VolumeOutline` [example](https://kitware.github.io/vtk-js/examples/VolumeOutline.html) on my local. However, I'm getting errors regarding these [two lines](https://github.com/Kitware/vtk-js/blob/92734a37388ac8e2559a0615769fc9830d08ed42/Examples/Volume/VolumeOutline/index.js#L81-L82)

```
labelMap.actor.getProperty().setUseLabelOutline(true);
labelMap.actor.getProperty().setLabelOutlineThickness(3);
```

Has there been any changes to the api?

the error is:
```
volume_outline.js:91 Uncaught (in promise) TypeError: labelMap.actor.getProperty(...).setUseLabelOutline is not a function
 createLabelPipeline (volume_outline.js:91)
 volume_outline.js:142
```
I'm able to run the example by commenting out those lines

![image](https://user-images.githubusercontent.com/7490180/101507006-1488c880-3944-11eb-9364-62f9ebc2a769.png)

I'm using `"vtk.js": "11.1.3"`

**Comment by floryst** [comment]
The earliest version of vtk.js that supports the label outline property is v11.14.0, so at minimum updating to that should fix things for you.

**Comment by sedghi** [comment]
@floryst thanks, indeed that was the solution
