### ISSUE TITLE
Cannot run the PiecewiseGaussianWidget example

### ISSUE THREAD

**Issue by laurentmalka** [Kitware/vtk-js#1653]
When running the PiecewiseGaussianWidget example locally by running the following command,
```
npm ci
npm run example -- PiecewiseGaussianWidget
```

I'm getting this error:

```
ERROR in ./Interaction/Widgets/PiecewiseGaussianWidget/ComputeHistogram.worker.js
Module build failed (from ../node_modules/worker-loader/dist/cjs.js):
ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema.
 - options.inline should be one of these:
   "no-fallback" | "fallback"
    at validate (/home/lmalka/dev/vtk-js/node_modules/worker-loader/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.pitch (/home/lmalka/dev/vtk-js/node_modules/worker-loader/dist/index.js:59:29)
 @ ./Interaction/Widgets/PiecewiseGaussianWidget/index.js 30:0-63 541:23-45
 @ ./Interaction/Widgets/PiecewiseGaussianWidget/example/index.js 6:0-100 82:13-51
```

With a git bisect, I found that this example was not working anymore since [this commit](https://github.com/Kitware/vtk-js/commit/da60598633e048144e31862114feba0e8211f610).

@floryst 
@finetjul @luciemac @boucaud

**Comment by wenge8n** [comment]
What is the solution?

**Comment by floryst** [comment]
Had a typo in the inline option. Will be merged soon.

**Comment by wenge8n** [comment]
Thank you very much.

**Comment by wenge8n** [comment]
ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'fallback'. These properties are valid:
   object { worker?, publicPath?, filename?, chunkFilename?, inline?, esModule? }
 - options.inline should be one of these:
   "no-fallback" | "fallback"

**Comment by wenge8n** [comment]
vtk.js/Sources/Interaction/UI/VolumeController

When I import this, the error occur, Please check and update me.

Thank you

**Comment by wenge8n** [comment]
After update vtk.js, It is still showing the error.

**Comment by wenge8n** [comment]
./node_modules/vtk.js/Sources/Interaction/Widgets/PiecewiseGaussianWidget/ComputeHistogram.worker.js
ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'fallback'. These properties are valid:
   object { worker?, publicPath?, filename?, chunkFilename?, inline?, esModule? }
 - options.inline should be one of these:
   "no-fallback" | "fallback"

**Comment by floryst** [comment]
I'm pretty sure I rewrote every instance of the old worker-loader config. Can you post your webpack config?
