### ISSUE TITLE
PostCSS loader error for Geometry Application

### ISSUE THREAD

**Issue by MHadavand** [Kitware/vtk-js#1657]
Tried to build Geometry viewer application and got this error:

ERROR in ./src/GeometryViewer.module.css (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/postcss-loader/dist/cjs.js??ref--11-2!./src/GeometryViewer.module.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
    at validate (D:\Projects\ParaviewVis\MyWebProject\node_modules\postcss-loader\node_modules\schema-utils\dist\validate.js:104:11)
    at Object.loader (D:\Projects\ParaviewVis\MyWebProject\node_modules\postcss-loader\dist\index.js:43:29)
 @ ./src/GeometryViewer.module.css 2:12-168 9:17-24 13:15-22
 @ ./src/index_geometry.js

Here is the webpack config
```
var path = require('path');
var webpack = require('webpack');
var vtkRules = require('vtk.js/Utilities/config/dependency.js').webpack.core.rules;
var cssRules = require('vtk.js/Utilities/config/dependency.js').webpack.css.rules;

// Optional if you want to load *.css and *.module.css files
// var cssRules = require('vtk.js/Utilities/config/dependency.js').webpack.css.rules;

var entry = path.join(__dirname, './src/index_geometry.js');
const sourcePath = path.join(__dirname, './src');
const outputPath = path.join(__dirname, './dist');

module.exports = {
    entry,
    output: {
        path: outputPath,
        filename: 'MyWebApp.js',
    },
    module: {
        rules: [
            { test: /\.html$/, loader: 'html-loader' },
            { test: /\.(png|jpg)$/, use: 'url-loader?limit=81920' },
            { test: /\.svg$/, use: [{ loader: 'raw-loader' }] },
        ].concat(vtkRules, cssRules),
    },
    resolve: {
        modules: [
            path.resolve(__dirname, 'node_modules'),
            sourcePath,
        ],
    },
};
```

**Comment by MHadavand** [comment]
This modification solves the build issue 

module: {
        rules: [
            { test: /\.html$/, loader: 'html-loader' },
            { test: /\.(png|jpg|ico)$/, use: 'url-loader?limit=81920' },
            { test: /\.svg$/, use: [{ loader: 'raw-loader' }] },
            { test: /\.css$/, use: ['style-loader', 'css-loader'] }
        ].concat(vtkRules),
    },

**Comment by floryst** [comment]
The linked PR should fix this issue, as it was an issue with the postcss-loader options changing after the upgrade.
