### ISSUE TITLE
RemoteView example not working

### ISSUE THREAD

**Issue by aronhelser** [Kitware/vtk-js#1681]
During ParaView 5.9 release process, a user reported the [RemoteView example](https://kitware.github.io/vtk-js/examples/RemoteView.html) was not working. An error printed by Twisted logging will be resolved by upgrading Twisted in a [paraview issue](https://gitlab.kitware.com/paraview/paraview/-/issues/20419). 

However, it appears there is still a mis-match between the registered protocols and the RPC calls made by the client, because after starting the example PV server, no image is displayed and the browser console prints many RPC errors similar to:
` "viewport.image.push.observer.add" message: "Unregistered method called"`
 and also for "viewport.image.push.original.size", "viewport.image.push" and several more.

**Comment by jourdain** [comment]
Let me know when you have pv binaries with the new twisted so I can check that issue.

**Comment by aronhelser** [comment]
You can grab binaries from the PV MR pipelines: https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/825
Linux is ready, and I just started mac.

**Comment by aronhelser** [comment]
mac is ready now

**Comment by jourdain** [comment]
Fixed in 

```
commit 0fbba5fcd49b679c8e5d5563f058eb7e44e55bf0 (HEAD -> master, origin/master, origin/HEAD)
Author: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Date:   Wed Jan 6 14:46:38 2021 -0700

    doc(RemoteView): Update example code
```
