### ISSUE TITLE
addClippingPlane normals inverted between vtkVolumeMapper and vtkMapper

### ISSUE THREAD

**Issue by PaulHax** [Kitware/vtk-js#1687]
Much thanks for #1677, just what I needed.  I'm using `mapper::addClippingPlane` on a scene mixing vtkVolumeMapper and vtkMapper with a shared plane object.  Seems that vtkVolumeMapper clips one direction, vtkMapper the other.  Might be nice to make this consistent?  Not sure what the proper fix would be besides negating these values: https://github.com/Kitware/vtk-js/pull/1677/files#diff-653a0c06ccb1ec727a15802ff1d90b9cb6599f82d58610b2522dcfe483ab7cf1R848-R851

See the volume clipped one way, the plane clipped on the other direction:
![image](https://user-images.githubusercontent.com/16823231/104356055-7acfb080-54d9-11eb-8bf0-75b088affcbb.png)

**Comment by gandis0713** [comment]
I think the conditions to set bounds of the volume by plane normal seem wrong.
So, I modified the conditions and created a PR. https://github.com/Kitware/vtk-js/pull/1715

**Comment by daker** [comment]
@jourdain Fixed in #1715, the issue can be closed
