### ISSUE TITLE
stlReader gives error

### ISSUE THREAD

**Issue by smoothumut** [Kitware/vtk-js#1688]
Hi everyone, first of all, thank you very much for all your effort. 
I have a small problem that prevents me to go forward

when adding 
import vtkSTLReader from 'vtk.js/Sources/IO/Geometry/STLReader';

to the js file to test stl reader function it give the error below
the error comes in terminal after calling npm run build

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vtpreader@1.0.0 build: `webpack --progress --mode=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vtpreader@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

this is the log

info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vtpreader@1.0.0~prebuild: vtpreader@1.0.0
6 info lifecycle vtpreader@1.0.0~build: vtpreader@1.0.0
7 verbose lifecycle vtpreader@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vtpreader@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\CikoBonBon\Documents\Projects\vtpReader_vtkjs\node_modules\.bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.2.1\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\CikoBonBon\AppData\Local\Microsoft\WindowsApps;;C:\Users\HelloBro\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\WhatTheHell\AppData\Roaming\npm
9 verbose lifecycle vtpreader@1.0.0~build: CWD: C:\Users\IHelloNinja\Documents\Projects\vtpReader_vtkjs
10 silly lifecycle vtpreader@1.0.0~build: Args: [ '/d /s /c', 'webpack --progress --mode=production' ]
11 silly lifecycle vtpreader@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle vtpreader@1.0.0~build: Failed to exec build script
13 verbose stack Error: vtpreader@1.0.0 build: `webpack --progress --mode=production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid vtpreader@1.0.0
15 verbose cwd C:\Users\CikoBonbon\Documents\Projects\vtpReader_vtkjs
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error vtpreader@1.0.0 build: `webpack --progress --mode=production`
22 error Exit status 1
23 error Failed at the vtpreader@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by smoothumut** [comment]
hi again, also 
import vtkXMLPolyDataReader from 'vtk.js/Sources/IO/XML/XMLPolyDataReader';
gives an error too

**Comment by jourdain** [comment]
I bet you are following the ES6 guide (Am I right?) with the latest vtk.js. That guide needs to be updated to align with the latest build infrastructure.  Otherwise you need vtk.js@15.6.0.

@floryst

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
