### ISSUE TITLE
this is a question about debugging in vscode

### ISSUE THREAD

**Issue by smoothumut** [Kitware/vtk-js#1690]
hello, first of all I am really new into vtk.js and also js. 
my question is  how can I debug an vtk.js file (ex: cone.js) in visual studio code ?? 
when "npm run build" command executed, app.js is created then debugging tools never enter into the js files like cone.js
I will be very grateful for any help, otherwise it will be very hard for me keep editin without debuging
regards

**Comment by jourdain** [comment]
This is what [I found](https://docs.microsoft.com/en-us/visualstudio/javascript/debug-nodejs?view=vs-2019) when I did a google search. HTH

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
