### ISSUE TITLE
Other examples of rendering point cloud data

### ISSUE THREAD

**Issue by leemerlas** [Kitware/vtk-js#1700]
I'm trying to learn how to render Lidar (point cloud data) by using vtk-js. 

Is there any other tutorial/example on how to render point cloud data? The `PointSource` example is pretty basic. Would prefer something like what three.js has.

**Comment by jourdain** [comment]
```
const polydata = vtkPolyData.newInstance();
polydata.getPoints().setData(Float32Array.from(__your_array_of_xyz__), 3);
const nbPoints = __your_array_of_xyz__.length / 3;
const vertex = new Uint16Array(nbPoints + 1);
vertex[0] = nbPoints;
for (let i = 0; i < nbPoints; i++) {
   vertex[i+1] = i;
}
polydata.getVerts().setData(vertex);

[... mapper/actor ..]
```

**Comment by jourdain** [comment]
You can find the same code inside `PointSource`.

- [Binding points + cells](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Sources/PointSource/index.js#L29-L35)
- [Filling the cells](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Sources/PointSource/index.js#L55-L58)

**Comment by leemerlas** [comment]
@jourdain thanks for this. on another note, is it possible to render lidar point clouds with vtk.js? possibly from a .pcd file? asking since most of the examples use xyz arrays

**Comment by jourdain** [comment]
We'll have to create a reader. But definitely possible. And if your `.pcd` is fairly basic, it should be strait forward to write in JS.

**Comment by leemerlas** [comment]
@jourdain I see, thanks for that info. I'll close this issue for now.
