### ISSUE TITLE
render text in 3D space

### ISSUE THREAD

**Issue by leemerlas** [Kitware/vtk-js#1702]
Is it possible to render text inside the 3D space? 

I would like to achieve something like this:

![image](https://user-images.githubusercontent.com/31193012/105655070-55d83600-5efa-11eb-8046-a1a786183413.png)

Maybe there is a widget for this?

**Comment by jourdain** [comment]
You definitely can do it, but you will have to leverage JS for that. We don't have a streamline way inside vtk.js.

But in general, you can create the following pipeline:

```
PlaneSource > Mapper > Actor
                         ^
                         |
draw-text-in-canvas > vtkTexture
                                
```

**Comment by leemerlas** [comment]
@jourdain Hmm, I'll try creating the pipeline you mentioned. Thanks
