### ISSUE TITLE
move actor in 3D space

### ISSUE THREAD

**Issue by leemerlas** [Kitware/vtk-js#1709]
Is it possible to move a point cloud in 3D space by clicking and dragging? Maybe by using the HardwareSelector? Or is there an easier and more efficient method?

**Comment by jourdain** [comment]
You should use a [widget](https://kitware.github.io/vtk-js/examples/HandleWidget.html) to capture the displacement you want to achieve. Then you can call `setPosition` (or origin / don't remember) on the actor itself.
