### ISSUE TITLE
Scene Explorer example not working

### ISSUE THREAD

**Issue by leemerlas** [Kitware/vtk-js#1710]
When trying out Scene Explorer example to load lidar.vtkjs, nothing is rendered:

![image](https://user-images.githubusercontent.com/31193012/106101420-d86e2900-6178-11eb-989e-189a43a5fd15.png)

Upon checking console, the following error can be observed: 

![image](https://user-images.githubusercontent.com/31193012/106101468-e754db80-6178-11eb-9265-e106311891df.png)

Is this a known bug with scene explorer?

**Comment by jourdain** [comment]
@boucaud
