### ISSUE TITLE
How to create colored pointclouds

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1722]
Hello,

First of all, Thank you for the awesome work! 

**- GOAL**
I'm trying to create a 3D visualization tool where it is needed to plot point clouds with known xyz coordinates. I also need to modify the color of each point depending on a specific value.

Going through the tutorial, the best I could find is the PointSource tutorial. However, I'm not sure if whether it's possible to plot points with known xyz coordinates with it
I also got to know that it's possible to do it with polydata type but couldn't manage so far. 
Any help would be much appreciated!

Cheers,
Zaid

**Comment by jourdain** [comment]
See https://github.com/Kitware/vtk-js/issues/1700

**Comment by zbouslikhin** [comment]
Thank you for the quick reaction!
I did try the following but it doesn't render anything:

```
const x = Array.from({length: 20}, () => Math.floor(Math.random() * 40));
  const y = Array.from({length: 20}, () => Math.floor(Math.random() * 40));
  const z = Array.from({length: 20}, () => Math.floor(Math.random() * 40));
  const xyz = [x, y, z];
  
  const polydata = vtkPolyData.newInstance();
  polydata.getPoints().setData(xyz, 3);
  const nbPoints = xyz.length / 3;
  const vertex = new Uint16Array(nbPoints + 1);
  vertex[0] = nbPoints;
  for (let i = 0; i < nbPoints; i++) {
    vertex[i+1] = i;
  }
  polydata.getVerts().setData(vertex);

  // ----------------------------------------------------------------------------
  // Actor/mapper setup
  // ----------------------------------------------------------------------------
  const actor = vtkActor.newInstance();
  const mapper = vtkMapper.newInstance();

  mapper.setInputData(polydata);
  actor.setMapper(mapper);
  renderer.addActor(actor);

  //render
  renderer.resetCamera();
  renderWindow.render();
```

**Comment by jourdain** [comment]
Your array needs to be [x0, y0, z0, x1, y1, z1, ...]

**Comment by jourdain** [comment]
Looking at the [code](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Sources/PointSource/index.js#L42-L51) should have helped you.

**Comment by zbouslikhin** [comment]
Sorry for the newbie question. I'm only starting using VTK in general. Thank you very much!
Is there any way to access and change the color of a specific pointcloud?

**Comment by jourdain** [comment]
You just update the field for a given point... Super easy, but you will need to start understanding VTK vtkPolyData/vtkPointData/vtkDataArray.

**Comment by zbouslikhin** [comment]
Surely, that's the way that I should have taken before diving in to practical stuff. Many thanks for your help. 
I'll close this for now

**Comment by jourdain** [comment]
```
const field = new Float32Array(20); // Based on the number of points you have
const array = vtkDataArray.newInstance({ name: 'data', values: field });
polydata.getPointData().setScalars(array);

// Changing 10th point field
field[10] = 1.56
array.modified()
```
