### ISSUE TITLE
PointPicker implementation doesn't work for certain lines

### ISSUE THREAD

**Issue by goflo** [Kitware/vtk-js#1738]
Hi,

I'm using the PointPicker as shown in the examples:
https://kitware.github.io/vtk-js/examples/PointPicker.html

I get the content of an XML file with VTKFile/PolyData from the API and render that on the client. For this simple case it's just a structure with 6 points which are connected by 3 lines.
What I want to do with the PointPicker is picking one of the six points, show the position and some meta data for the point.

But that works only in some cases. With the following the definition the PointPicker works as expected:
```xml
<VTKFile type="PolyData">
	<PolyData>
		<Piece NumberOfPoints="6" NumberOfLines="3" NumberOfPolys="0">
			<Points>
				<DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii">0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3</DataArray>
			</Points>
			<PointData>
				<DataArray type="Int32" Name="node_ids" NumberOfComponents="1" format="ascii">1 3 3 4 4 2</DataArray>
			</PointData>
			<CellData Scalars="element_type_cell_colors">
				<DataArray type="Int32" Name="element_ids" NumberOfComponents="1" format="ascii">1 2 3</DataArray>
				<DataArray type="UInt8" Name="element_type_cell_colors" NumberOfComponents="3" format="ascii">255 0 0 255 0 0 255 0 0</DataArray>
			</CellData>
			<Lines>
				<DataArray type="Int64" Name="connectivity" format="ascii">0 1 2 3 4 5</DataArray>
				<DataArray type="Int64" Name="offsets" format="ascii">2 4 6</DataArray>
			</Lines>
		</Piece>
	</PolyData>
</VTKFile>
```

But for these PolyData definitions the PointPicker doesn't work! The picker.getActors() function always returns an empty array!
```xml
<VTKFile type="PolyData">
	<PolyData>
		<Piece NumberOfPoints="6" NumberOfLines="3" NumberOfPolys="0">
			<Points>
				<DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii"> 0 1 1 1 1 1 1 1 1 2 1 1 2 1 1 3 1 1</DataArray>
			</Points>
			<PointData>
				<DataArray type="Int32" Name="node_ids" NumberOfComponents="1" format="ascii"> 1 3 3 4 4 2</DataArray>
			</PointData>
			<CellData Scalars="element_type_cell_colors">
				<DataArray type="Int32" Name="element_ids" NumberOfComponents="1" format="ascii">1 2 3</DataArray>
				<DataArray type="UInt8" Name="element_type_cell_colors" NumberOfComponents="3" format="ascii"> 255 0 0 255 0 0 255 0 0</DataArray>
			</CellData>
			<Lines>
				<DataArray type="Int64" Name="connectivity" format="ascii"> 0 1 2 3 4 5</DataArray>
				<DataArray type="Int64" Name="offsets" format="ascii"> 2 4 6</DataArray>
			</Lines>
		</Piece>
	</PolyData>
</VTKFile>
```

As you can see the difference between the two models is only in the coordinates of the points. I have tried several other coordinates. It's also not working with the following point sets:
```xml
                        <Points>
				<DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii"> 0 0 1 1 0 1 1 0 1 2 0 1 2 0 1 3 0 1</DataArray>
			</Points>
```

```xml
			<Points>
				<DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii"> 0 1 0 1 1 0 1 1 0 2 1 0 2 1 0 3 1 0</DataArray>
			</Points>
```

```xml
			<Points>
				<DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii"> 0 0 0 1 0 0 1 0 0 2 0 0 2 0 0 3 0 0</DataArray>
			</Points>
```

Is this a known issue? Are there some other possibilities to pick a point from a PolyData model?
I have already tried the HardwareSelector approach, but this is not working well.

Thanks and Best Regards,
Florian

**Comment by jourdain** [comment]
The coordinates should not matter. Could you illustrate better what you mean by working vs not working?

**Comment by goflo** [comment]
Hi @jourdain 
thanks for the quick reply.
Well "not working" means that the pointPicker.getActors() returns an empty array and pointPicker.getPointId() returns -1.

Working means that the pointPicker.getActors() returns an actor and using the pointPicker.getPointId() returns a valid pointId (> -1). With the pointId I can find the point which was selected and go on with the workflow (loading point information and meta data).

Here is a part of the code which should handle the point selection:
```javascript
  private initPicker() {
    // Pick on mouse right click
    this.renderWindow.getInteractor().onRightButtonPress((callData: any) => {
      if (this.renderer !== callData.pokedRenderer) {
        return;
      }

      const pos = callData.position;
      const point = [pos.x, pos.y, 0.0];

      if (this.pointPicker) {
        this.pickPoint(point);
      }     
      this.renderWindow.render();
    });
  }
  
  private pickPoint(point) {
    this.pointPicker.pick(point, this.renderer);
    
    if (this.pointPicker.getActors().length > 0) {
      const pickedPointId = this.pointPicker.getPointId();
      const pickedPointPosition = this.polyData.getPoints().getPoint(pickedPointId);
      
      if (pickedPointPosition) {
        this.replaceMarker(pickedPointPosition);
      }
      
      // emit event
      if (this.pointPicked) {
        this.pointPicked.emit(new NodePickedEventData(pickedPointId, pickedPointPosition));
      }
    } else {
      console.log("this.pointPicker.getActors() doesn't contain any actor...");
    }
  }
```

Hope now it's more understandable?

**Comment by jourdain** [comment]
And you click close to where the point is or just on the line right in middle of 2 points?

Also, are you using a hidpi screen? (Just wondering)

**Comment by goflo** [comment]
Yes, in both cases I click very close to the points (at the start or end of the line). I have also set the tolerance of the PointPicker higher than the default value (`pointPicker.setTolerance(1.0);`), but that doesn't solve the problem...

No, I'm using an normal screen with a resolution of 1920x1080px.

**Comment by jourdain** [comment]
Hum, on very basic geometry this should work pretty well. I'm not sure what is going on. I tend to use hardware selector, but none the less, your setup should work. Maybe @finetjul may know something as it was his team (I think) who did the initial work on it.

**Comment by jourdain** [comment]
FYI @floryst

**Comment by goflo** [comment]
Any idea how to go on with this issue? Can someone reproduce the issue?

In the meanwhile I have also tried to implement the required functionality using the HardwareSelector. I have now the following implemented instead of the PointPicker:

```javascript
  private initHardwareSelector() {
    this.hwSelector = this.vtkOpenGLHardwareSelector.newInstance();
    this.hwSelector.setFieldAssociation(this.fieldAssociations.FIELD_ASSOCIATION_POINTS);
    this.hwSelector.attach(this.renderWindow.getViews()[0], this.renderer);
    this.hwSelector.setCaptureZValues(true);

    // Pick on mouse right click
    this.renderWindow.getInteractor().onRightButtonPress((callData: any) => {
      const pos = callData.position;
      this.selectPointWithHadwareSelector(pos.x, pos.y);

      this.renderWindow.render();
    });
  }

  private selectPointWithHadwareSelector(mouseX: number, mouseY: number) {
    const clickRange = 20;  // half width of the selection box created around the mouse position
    this.hwSelector.setArea(mouseX - clickRange, mouseY - clickRange, mouseX + clickRange, mouseY + clickRange);
    const res = this.hwSelector.select();
    
    if (res && res.length > 0) {
      const result = res[0];
      const actor = result.getProperties().prop;
      // What to do now? How can I get the closes point?
    }
  }
```

The HardwareSelector returns a result and I can get the selected actor. But how to go on?
How can I get the closes point to the mous position?

**Comment by finetjul** [comment]
@boucaud an idea ?

**Comment by finetjul** [comment]
@goflo can you please create an MR that adds a failing test in [testPointPicker](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/PointPicker/test/testPointPicker.js) ?

**Comment by goflo** [comment]
@finetjul I can try to. But debugging tests like described in https://github.com/Kitware/vtk-js/blob/master/CONTRIBUTING.md with `npm test:debug` is not working. I can just run the tests with `npm test`.

**Comment by finetjul** [comment]
@goflo  it is `npm run test:debug`

**Comment by goflo** [comment]
@finetjul please check this PR: https://github.com/Kitware/vtk-js/pull/1764
There is an other issue adding the actor to the renderer.

**Comment by goflo** [comment]
@finetjul @jourdain I added now two test which are showing the problem. It seems not to be a problem with the PolyData itself. I have also added a test with a LineSource and there you can very good see what the problem is:
```js
  const lineSource = vtkLineSource.newInstance();
  lineSource.set({
    point0: [0, 0, 0],
    point1: [100, 0, 0],
    resolution: 10,
  });

  // adding mapper, actor...
  ...
  
  // Test picker
  const picker = vtkPointPicker.newInstance();
  picker.setPickFromList(1);
  picker.initializePickList();
  picker.addPickList(actor);
  picker.setTolerance(1.0);

  const pFirst = [380 + 0.5, 200, 0];
  picker.pick(pFirst, renderer);

  const actorsFirstPoint = picker.getActors();
  t.equal(actorsFirstPoint.length, 1);
  t.equal(actorsFirstPoint[0], actor);

  const idFirstPoint = picker.getPointId();
  t.equal(idFirstPoint, 0);

  // this will fail because the y position is not exactly like the position of the points (200)
  // when doing the pick with point [20, 200, 0] it's working fine!
  const pLast = [20, 200 + 0.5, 0];
  picker.pick(pLast, renderer);

  const actorsLastPoint = picker.getActors();
  t.equal(actorsLastPoint.length, 1);
  t.equal(actorsLastPoint[0], actor);

  const idLastPoint = picker.getPointId();
  t.equal(idLastPoint, 10);
```

When the y-component of the picked position is exactly like the position of the point the pick is working. If the y-component of the picked position is not equal then it's not working! For the x-component it doesn't matter.

That seems to be also the reason why one of my PolyData models is working and the other one is not working.

See PR: https://github.com/Kitware/vtk-js/pull/1764

**Comment by jourdain** [comment]
@finetjul I let you do the integration. Thanks @goflo for those tests.

BTW, you could write your lineSource setup that way too

```
const lineSource = vtkLineSource.newInstance({
    point0: [0, 0, 0],
    point1: [100, 0, 0],
    resolution: 10,
});
```
