### ISSUE TITLE
No effect after ClearAllActors

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1745]
Hello,

Using the function "removeAllActors()" from the RenderWindow class doesn't clear the scene. I'm using it this way:
```
var renderer = vtkRenderer.newInstance();
renderer.removeAllActors();
```
Is there something I am missing?

**Comment by jourdain** [comment]
A render call?

**Comment by zbouslikhin** [comment]
Sorry, I forgot to mention that I'm also rendering. Even with a render, it doesn't clear the scene.

**Comment by jourdain** [comment]
Are you doing Volume rendering? If so, those are not actors but volumes...

**Comment by zbouslikhin** [comment]
I'm not doing volume rendering. I'm rendering simple point clouds using vtkPolyData.

**Comment by jourdain** [comment]
[This](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Renderer/index.js#L154-L160) looks correct. You will need to provide more details in order for us to help you.

**Comment by jourdain** [comment]
Actually, that make sense that "does not work" since you remove the actors of a new instance that is obviously empty of actors and that is not used for the rendering...

**Comment by zbouslikhin** [comment]
I see.
However, when using `removeActor()` actor by actor, it works as predicted.

Here's some more context about `removeAllActors()`:
````
        this.renderer = vtkRenderer.newInstance();
        this.renderWindow = vtkRenderWindow.newInstance();
        this.renderWindow.addRenderer(this.renderer);

        // OpenGLRenderWindow
        this.openGLRenderWindow = vtkOpenGLRenderWindow.newInstance();
        this.openGLRenderWindow.setContainer(this.mount)
        this.openGLRenderWindow.setSize(width, height);
        this.renderWindow.addView(this.openGLRenderWindow);

        // Interactor
        this.interactor = vtkRenderWindowInteractor.newInstance();
        this.interactor.setInteractorStyle(
            vtkInteractorStyleTrackballCamera.newInstance()
        );
        this.interactor.setView(this.openGLRenderWindow);
        this.interactor.initialize()
        this.interactor.bindEvents(this.mount);

        const actor = vtkActor.newInstance();
        const mapper = vtkMapper.newInstance();
        
       //currentPolyData holds a list of point clounds

        mapper.setInputData(currentPolyData)
        mapper.setLookupTable(colorLookupTable);
        mapper.setColorModeToMapScalars();
        mapper.setInterpolateScalarsBeforeMapping();
        mapper.setScalarModeToUsePointData();
        mapper.setScalarVisibility(true);
        mapper.setScalarRange(scalarRange[0], scalarRange[1])

        actor.setMapper(mapper);
        this.renderer.addActor(actor)
        this.renderer.removeAllActors();
````

**Comment by jourdain** [comment]
Indeed, actors/volumes don't get updated on the add method. Only the viewProps seems to matter.

The following could do the trick
```
this.renderer.removeAllViewProps();
this.renderer.modified();
```

But you are right, we have a bug on actor handling...

**Comment by zbouslikhin** [comment]
Thank you very much for your help and quick reaction!

I'll leave this ticket open for now.

**Comment by JWock82** [comment]
I had the same issue. I found `.removeAllViewProps()` did the trick.
