### ISSUE TITLE
Polydata: hide a single point

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1761]
Hi,

I'm displaying a bunch of points colored according some scalars mapped using the `colortransferfunction`. I'm trying to hide some points without creating a copy of the data. 
The first solution that comes to my mind is to set the opacity of the desired point to 0. However, I'm not sure if it is possible to access and change the color of an individual point by index.
There may be another easier way to go that I'm ignoring. If so. any help would be much appreciated! 

Regards,
Zaid

**Comment by jourdain** [comment]
You can easily swap the vertex array to only select the points to show. Ideally you want to create a single typed array on which you provide a shrink view of it with just the list of points to see. Especially if the points you want to hide have no relationship with the color map that you want to apply to them. 

Or if you compute a rgba field on your dataset, you can just update the alpha part.

**Comment by jourdain** [comment]
Closing because solved
