### ISSUE TITLE
when use pointpicker to picker actor and setvisibility is False, then can't work.

### ISSUE THREAD

**Issue by WeiliJiang** [Kitware/vtk-js#1762]
hello, I want to use pointpicker to picker one actor and setvisibility is False or highlight. when i use poingpicker to picker, i use genericRenderWindow as renderer and rendererwindow. and code write as follows:
pickerfunction=()=>{
    const renderer = this.genericRenderWindow.getRenderer();
    const renderWindow = this.genericRenderWindow.getRenderWindow()
   const picker = vtkPointPicker.newInstance();
    picker.setPickFromList(1);
    picker.initializePickList();
    const mapper = vtkMapper.newInstance()
    const actor = vtkActor.newInstance()
    actor.setMapper(mapper)
    mapper.setInputData(this.props.actors)
    console.log('add actor',actor)
    picker.addPickList(this.props.actors);
    this.renderWindow.getInteractor().onRightButtonPress((callData) => {
      if (this.renderer !== callData.pokedRenderer) {
        return;
      }
      const pos = callData.position;
      const point = [pos.x, pos.y, 0.0];
      console.log(`Pick at: ${point}`);
      picker.pick(point, this.renderer);
      // picker.pick(point, callData.pokedRenderer);
      const actors = picker.getActors();
      console.log('picker actors',actors)
      const ijk = picker.getPointIJK()
      const worldPositions = picker.getPickPosition()
      console.log('picker ijk',ijk)
      console.log('picker worldPositions',worldPositions)
     renderWindow.render();
    });}
and in this code, this.props.actors.length is number and >0. and renderer.getActors() is the same. but when i try to addpicklist one of them, they will get error, and error is: prop.getMapper is not a function. but in my code, this.props.actor is do mapper.and code as follow:
 createPipeline = (fileContents, colorNum, opacity) => {
    const vtpReader = vtkXMLPolyDataReader.newInstance()
    vtpReader.parseAsArrayBuffer(fileContents)
    const source = vtpReader.getOutputData()
    const lookupTable = vtkColorTransferFunction.newInstance()
  lookupTable.applyColorMap(vtkColorMaps.getPresetByName('erdc_rainbow_bright'))
    const mapper = vtkMapper.newInstance({
      interpolateScalarsBeforeMapping: false,
      useLookupTableScalarRange: true,
      lookupTable,
      scalarVisibility: false,
    })
  const actor = vtkActor.newInstance();
    actor.rotateX(-90);
    actor.getProperty().setOpacity(opacity);
    actor.setMapper(mapper);
    mapper.setInputData(source);
  actor.getProperty().setColor(this.state.colorList[colorNum].colorvalue1 / 255, this.state.colorList[colorNum].colorvalue2 / 255, this.state.colorList[colorNum].colorvalue3 / 255)
    actor.getProperty().setDiffuse(0.25)
    actor.getProperty().setAmbient(0.5)
    actor.getProperty().setSpecular(0.125)
    return actor;
  }
Now, i don't know how to do, please give me some help. thank you very much.

**Comment by dahuajiejie** [comment]
I am sorry about the code of picker, the code as follow is didn't use in the code.
const mapper = vtkMapper.newInstance()
const actor = vtkActor.newInstance()
actor.setMapper(mapper)
mapper.setInputData(this.props.actors)
console.log('add actor',actor)
now, i can't add this.props.actor or this.renderer.getAcotrs() in addpicklist. then can't get (picker.getPointIJK()). please give me some advice about this.
and i will add full code as follows: and main code is in pickerfunction of Rendering3D.js.
[vtk.zip](https://github.com/Kitware/vtk-js/files/6069950/vtk.zip)

**Comment by jourdain** [comment]
Closing because of not understanding the question. 

If you still need help with this, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9. Thank you!
