### ISSUE TITLE
Use vtkColorTransferFunction to set pixel data(1,2,3) to red, green, blue

### ISSUE THREAD

**Issue by StevenRoger** [Kitware/vtk-js#1765]
There is one volume data only include value: 0, 1, 2, 3,
when rendered in 2d mode(MPR), the color displayed as expected.
```
cfun.addRGBPoint(1, 1, 0, 0); // label '1' will be red
cfun.addRGBPoint(2, 0, 1, 0); // label '2' will be green
cfun.addRGBPoint(3, 0, 0, 1); // label '3' will be blue
```
but when i rendered in 3d mode(use applyPreset), i changed a preset:
```
{
  "name": "MY_PRESET",
  "gradientOpacity": "4 0 1 3 1",
  "specularPower": "100",
  "scalarOpacity": "8 0 0 1 1 2 1 3 1",
  "id": "vtkMRMLVolumePropertyNode27",
  "specular": "0.5",
  "shade": "1",
  "ambient": "0.3",
  "colorTransfer": "12 0 0 0 0 1 1 0 0 2 0 1 0 3 0 0 1",
  "selectable": "true",
  "diffuse": "0.9",
  "interpolation": "1",
  "effectiveRange": "1 4",
};
```
the volume all displayed red.
 Is there anything i set wrong?
 Could you give me some suggestion.

**Comment by jourdain** [comment]
Your JSON does not seems like what the `applyPreset` expect.

**Comment by StevenRoger** [comment]
I changed **colorTransfer** value 
```
"colorTransfer": "16 0 0 0 0 1 1 0 0 2 0 1 0 3 0 0 1",
```
still not work, could you point out my JSON's errors, or give me a simple example. thx.

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/LiteColorMaps.json#L2-L20

**Comment by StevenRoger** [comment]
https://github.com/OHIF/react-vtkjs-viewport/blob/9480282a0e/examples/presets.js

thanks a lot, I refered this preset JSON.

If i don't use these JSON config, How can i achive what i want by using vtkColorTransferFunction?
```
cfun.addRGBPoint(1, 1, 0, 0); // label '1' will be red
cfun.addRGBPoint(2, 0, 1, 0); // label '2' will be green
cfun.addRGBPoint(3, 0, 0, 1); // label '3' will be blue
```
Why doesn't it work?

**Comment by jourdain** [comment]
It should work but without seeing the result or what you do with your cfun it is hard to tell which part of the doesn't work you are talking about.

**Comment by jourdain** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
