### ISSUE TITLE
CellArray default value is ignored

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#1772]
The following should return 'Uint32Array' instead of 'Float32Array'.
```
const cells = vtkCellArray.newInstance({ values: [3, 0, 1, 2] });
cells.getDataType();
```

**Comment by jourdain** [comment]
Order issue [in that section](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/Core/CellArray/index.js#L81-L94)

**Comment by finetjul** [comment]
Yep, I was about to fix it, and then I saw the `empty: true`.
I no longer have enough brain cells at that time :-)
