### ISSUE TITLE
RenderWindowInteractor InteractionEvent event name

### ISSUE THREAD

**Issue by daker** [Kitware/vtk-js#1780]
Those three will be created as events :
https://github.com/Kitware/vtk-js/blob/7104f919cf1ed1e1a0c03c8f5e3199ba8b1114eb/Sources/Rendering/Core/RenderWindowInteractor/index.js#L61-L63

using : 

https://github.com/Kitware/vtk-js/blob/7104f919cf1ed1e1a0c03c8f5e3199ba8b1114eb/Sources/Rendering/Core/RenderWindowInteractor/index.js#L780

and the result will be :
`onStartInteractionEventEvent`
`onInteractionEventEvent`
`onEndInteractionEventEvent`

**Comment by jourdain** [comment]
@martinken what do you think?

**Comment by martinken** [comment]
Sure, EventEvent seems wrong so let's fix it.
