### ISSUE TITLE
Unexpected behavior with AnnotatedCubeActor and WidgetManager

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1793]
Hello,

While trying to create an interactive orientation cube by following [this example.](https://kitware.github.io/vtk-js/examples/InteractiveOrientationWidget.html), I came across a weird behavior when changing `vtkAxesActor` by `vtkAnnotatedCubeActor`, the cube is only reactive on the first click but stops working as soon as the camera is moved.
It looks like there's some funky stuff going on with the bounds as as soon as the camera is moved, there's a layer of opacity that is changed into solid
Here is the codepen that reproduces the behavior: https://codepen.io/za-d-bouslikhin/pen/XWpWmvZ

**Comment by jourdain** [comment]
Thanks for reporting the issue. I'm not sure what could be happening. 

@floryst

**Comment by zbouslikhin** [comment]
A workaround would be manually setting the bounds in `widget.setBounds()` making it smaller.

**Comment by jourdain** [comment]
Does that work?

**Comment by zbouslikhin** [comment]
It does work. 
See line 57 in this codepen: https://codepen.io/za-d-bouslikhin/pen/XWpWpKN

**Comment by jourdain** [comment]
I guess it was the z fighting between the widget and the actor.

**Comment by finetjul** [comment]
Maybe playing with `coincident topology` would fix your problem then.

**Comment by jourdain** [comment]
The issue is just related to the size of the active widget which is smaller than the actual actor. Bumping the size of the widget solve the problem.
