### ISSUE TITLE
Missing export for ResliceCursorWidget and ImageReslice

### ISSUE THREAD

**Issue by no2497** [Kitware/vtk-js#1805]
Hi, would it be possible to export the ResliceCursorWidget from the https://unpkg.com/vtk.js@17.2.0/vtk.js?
I was trying to import it using unpkg but nothing was found from https://github.com/Kitware/vtk-js/tree/master/Sources/Widgets/Widgets3D/ResliceCursorWidget. I saw that in the index.js of widgets3D nothing related to ResliceCursorWidget package is exported
My approach was something like:
const vtkResliceCursorWidget = vtk.Widgets.Widgets3D.vtkResliceCursorWidget;
but, as I said, nothing was found.
Also the SlabMode from https://github.com/Kitware/vtk-js/tree/master/Sources/Imaging/Core/ImageReslice seems to be missing as well from the unpkg.
Am I doing something wrong or is it true?
Thanks!!

**Comment by jourdain** [comment]
@finetjul
