### ISSUE TITLE
Set coordinates values into vtkActor2D's constructor caused crash

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#181]
When I try to create a vtkActor2D new instance, it crashed.

The constructor of the vtkActor2D set two values to a vtkCoordinate instance :
```
model.positionCoordinate2 = vtkCoordinate.newInstance();
model.positionCoordinate2.setCoordinateSystemToNormalizedViewport();
model.positionCoordinate2.setValue(0.5, 0.5);
```
But the value setter of the vtkCoordinate has to take 3 values : 
```
  macro.setGetArray(publicAPI, model, [
    'value',
  ], 3);
```
So if it takes a different number, it crashes. I think that it has to depend on the coordinateSystem property of the vtkCoordinate, hasn't it ? Or did I miss anything ?

**Comment by martinken** [comment]
Yes, I have a topic to fix it here.

https://github.com/Kitware/vtk-js/pull/183
