### ISSUE TITLE
Open CASCADE Technology

### ISSUE THREAD

**Issue by WREQI** [Kitware/vtk-js#1816]
I want to connect to occt in vtk-js, what should I do?

**Comment by jourdain** [comment]
I'm guessing that you want to use occt on a server or do they have something running is JS?

**Comment by WREQI** [comment]
My ideal way is to use occt on the server and vtk.js to display on the web side, and realize the interaction between vtk and occt

**Comment by WREQI** [comment]
@jourdain thank you for your reply

**Comment by jourdain** [comment]
I guess you will have to figure out the server part between occt and VTK/C++/Python. Once you are in a VTK format on the server side, we can talk about getting that data to vtk.js.
