### ISSUE TITLE
Documentation 404's

### ISSUE THREAD

**Issue by greglucas** [Kitware/vtk-js#1831]
**Describe the bug**

The website documentation appears to have been removed from GitHub Pages. Has it moved to another location?

I'm trying to access the examples and snippets here: https://kitware.github.io/vtk-js/

Specifically, commit https://github.com/Kitware/vtk-js/commit/c679bbaa8daed8187ca6856a36292761ba8aee70 appears to have deleted a bunch of the index.html files.

**Comment by jourdain** [comment]
Thanks we are on it. We've noticed it as well...

FYI @daker ;-)

**Comment by daker** [comment]
How is it possible, the last changes did not change anything in the build system and we didn't update .md files

**Comment by jourdain** [comment]
Might be a CI issue, @floryst is looking into it.

**Comment by daker** [comment]
@floryst @jourdain 
here is why npm can't resolve hexo deps https://github.com/Kitware/vtk-js/runs/2290652093#step:10:4145

**Comment by floryst** [comment]
Update: Commit a846586e9ae736e43c4a208d6b4513d1b56924d6 appears to be the culprit.

**Comment by floryst** [comment]
Upgrading to semantic-release v17.4.2 triggers the issue. Still not sure 100% why.

**Comment by jourdain** [comment]
I guess that was my fault not yours @daker ;-)

**Comment by floryst** [comment]
Whoops I didn't mean to close the issue. Still need to perform two more tests to verify that actually fixes things.

**Comment by greglucas** [comment]
Looks like it is back up to me, thanks for the quick fix! I'll let you close it when you've done your other tests.

Additionally, you may want to put an extra check in the action to only publish/push to the gh-pages branch if the docs exist in the CI environment. It looks like npm failed, but the doc build still showed as succeeded to the workflow for some reason and it decided to push anyways.

**Comment by floryst** [comment]
Good idea, we'll add a check to ensure that something was generated. The CD build still doesn't fix the issue, so I pushed the site manually. Need to dig into fixing the automatic build.

**Comment by ifunplus** [comment]
Still can't open the page https://kitware.github.io/vtk-js/

**Comment by floryst** [comment]
Should be fixed in https://github.com/Kitware/vtk-js/pull/1841.
