### ISSUE TITLE
VtkDistanceWidget does not work

### ISSUE THREAD

**Issue by no2497** [Kitware/vtk-js#1845]
Hi,
I'm using the 17.2.1 from the unpkg (I'm the guy from the ResliceCursorWidget missing export).
I'm trying to add a distance widget from the Interaction/Widgets package but I cannot understand this error 
```
Uncaught RangeError: Invalid number of values for array setter (center)
    at Object.n.forEach.e.<computed> [as setCenter] (vtk.js:2)
    at Object.e.setWorldPosition (vtk.js:2)
    at Object.e.setPoint1WorldPosition (vtk.js:2)
    at Object.Ex.e.setPoint1WorldPosition (vtk.js:2)
    at Object.Qx.e.moveAction (vtk.js:2)
    at Object.Qx.e.handleMouseMove (vtk.js:2)
    at Object.<anonymous> (vtk.js:2)
    at o (vtk.js:2)
    at Object.Q.e.<computed> [as invokeMouseMove] (vtk.js:2)
    at Object.Mm.Dm.forEach.e.<computed> [as mouseMoveEvent] (vtk.js:2)
    at HTMLDivElement.Mm.e.handleMouseMove (vtk.js:2)
n.forEach.e.<computed> @ vtk.js:2
e.setWorldPosition @ vtk.js:2
e.setPoint1WorldPosition @ vtk.js:2
Ex.e.setPoint1WorldPosition @ vtk.js:2
Qx.e.moveAction @ vtk.js:2
Qx.e.handleMouseMove @ vtk.js:2
(anonymous) @ vtk.js:2
o @ vtk.js:2
Q.e.<computed> @ vtk.js:2
Mm.Dm.forEach.e.<computed> @ vtk.js:2
Mm.e.handleMouseMove @ vtk.js:2
```

while my code simply does this
```
const measure = vtkDistanceWidget.newInstance();
measure.setInteractor(this.renderWindow.getInteractor());
measure.setEnabled(true);
measure.setWidgetStateToStart();

.. stuff with colors and measures to display ...

```

I'm writing here because, while searching for a solution in https://kitware.github.io/vtk-js/examples/ in the Interaction/widgets examples and I saw that the majority of them does not work.
Am I doing something wrong or what?

Thanks!!

**Comment by finetjul** [comment]
I have not looked at your issue.

Those `Interaction/Widgets` are now obsolete. Please consider using [Widgets/LineWidget](https://kitware.github.io/vtk-js/examples/LineWidget.html) instead. It should do what you want (all you have to do is set the distance as text).

**Comment by finetjul** [comment]
Regarding the issue, I couldn't reproduce the error with a quick example. I did the same than you, i.e. 
```
const measure = vtkDistanceWidget.newInstance();
measure.setInteractor(this.renderWindow.getInteractor());
measure.setEnabled(true);
measure.setWidgetStateToStart();
```)

You would need to check why "center" is not an array of length 3.

**Comment by no2497** [comment]
Hi and sorry to keep you waiting. I tried again with the old widget but it wouldn't work, it always says that this "center" array is not an array of length 3 (I've no center array so I thought it was something from the widget). Trying to update the project using the new lineWidget from Widgets3D I saw that it is not exported for the unpkg version. Could you add it please?

Thanks!!

**Comment by no2497** [comment]
Hi, this morning I downloaded the last version of vtk.js from unpkg and now the old lineWidget works again correctly. Could it br related to https://github.com/Kitware/vtk-js/issues/1832 ? Also, if you add the new lineWidget to the export anyway it could be useful in the future!

**Comment by finetjul** [comment]
Yes, that is possible that it fixed it.
`center` could have been a typed array and therefore not supported.

New line widget will soon be exported:
https://github.com/Kitware/vtk-js/pull/1854

**Comment by no2497** [comment]
Thank you very much!!!
