### ISSUE TITLE
LiteHttpDataAccessHelper error in some examples

### ISSUE THREAD

**Issue by ronzim** [Kitware/vtk-js#1857]
Some examples are broken, showing the following error:
`LiteHttpDataAccessHelper does not support compression. Need to register HttpDataAccessHelper instead.`
`Uncaught (in promise) Error: LiteHttpDataAccessHelper does not support compression. Need to register HttpDataAccessHelper instead.`

As long as I can see, the error appear in these examples:
- ImageCroppingRegionsWidget, https://kitware.github.io/vtk-js/examples/ImageCroppingRegionsWidget.html
- ImageCropFilter https://kitware.github.io/vtk-js/examples/ImageCropFilter.html
- ImageCroppingWidget https://kitware.github.io/vtk-js/examples/ImageCroppingWidget.html
- PiecewiseGaussianWidget https://kitware.github.io/vtk-js/examples/PiecewiseGaussianWidget.html
- HttpDataSetReader https://kitware.github.io/vtk-js/examples/HttpDataSetReader.html
- VolumeMapper https://kitware.github.io/vtk-js/examples/VolumeMapper.html

**Comment by jourdain** [comment]
Thanks for listing those example.

**Comment by jourdain** [comment]
[This](https://github.com/Kitware/vtk-js/commit/b392548461e6f2c2d88bf82a079e430eb01e7174) should take care of it.

Thanks again for our help.

**Comment by sumilying** [comment]
this problem is still exist ,my version is 21.1.4

**Comment by jourdain** [comment]
For which example? If it is in your code, did you do that import? 

```
import 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';
```
