### ISSUE TITLE
Volume rendering issue on NVIDIA GeForce GT 750M

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#188]
On Macbook pro, the rendering have volume duplication.

![vtk-js-volume-rendering](https://cloud.githubusercontent.com/assets/294518/24781158/b6ab71ce-1afa-11e7-80c1-5e418373946a.jpeg)

**Comment by jourdain** [comment]
[WebGL MAX parameters test.pdf](https://github.com/Kitware/vtk-js/files/904413/WebGL.MAX.parameters.test.pdf)

**Comment by martinken** [comment]
Are your drivers up to date?  With OSX I think that means are you on the latest OSX? Have you tried rebooting, wiping the disk, and reinstalling the OS ;-)

**Comment by martinken** [comment]
More seriously I'll try thinking about this some today.  Looks like an exact factor of 2, just split into 5 pieces.

**Comment by martinken** [comment]
Also can you rotate and translate it some? What happens?

**Comment by martinken** [comment]
Actually I would bet money this is a retina 2x issue

**Comment by martinken** [comment]
Let's do a hangout, I want to see how the issue behaves

**Comment by martinken** [comment]
Fixed
