### ISSUE TITLE
Crop widget handles error

### ISSUE THREAD

**Issue by ronzim** [Kitware/vtk-js#1905]
Error interacting with crop widget (Cannot read property 'displayToWorld' of undefined).
Can be seen in vtk.js example, just try to move an handle on the edge. It works correctly for corner and face handles.
See attached screenshot.

Chrome Version 90.0.4430.93

![image](https://user-images.githubusercontent.com/45311591/117828097-d2a4db00-b271-11eb-8ca3-f262d1137e13.png)

**Comment by floryst** [comment]
Thanks for the report, I can take a look at this.
