### ISSUE TITLE
Multiple inheritance problem

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#1910]
### High-level description

Widgets do not list 'vtkProp' in their class hierarchy despite 'deriving' from it.
Here is the class hierarchy of LineWidget:
```js
['vtkObject', 'vtkInteractorObserver', 'vtkAbstractWidget', 'vtkLineWidgetProp']
```

### Detailed behavior

Here is the constructor of AbstractWidget
```js
vtkProp.extend(publicAPI, model, initialValues);
vtkInteractorObserver.extend(publicAPI, model, initialValues);
```
and here is vtkInteractorObserver constructor:
```js
export function extend(publicAPI, model, initialValues = {}) {
  Object.assign(model, DEFAULT_VALUES, initialValues);

  // Object methods
  macro.obj(publicAPI, model);
```
`macro.obj()` resets `model.classHierarchy`  that was previously initialized by `vtkProp.extend`

### Expected behavior

Not sure what to expect in a linear class hierarchy when doing multiple inheritance.

Should it be:
```
['vtkObject', 'vtkProp', 'vtkObject', 'vtkInteractorObserver', 'vtkAbstractWidget', 'vtkLineWidgetProp']
```
Or I guess we can be a bit smarter:
```js
['vtkObject', 'vtkProp', 'vtkInteractorObserver', 'vtkAbstractWidget', 'vtkLineWidgetProp']
```

Or maybe it should not be a flat list ? But that might break few things...

### Steps to reproduce

Instantiate a lineWidget and look at its hierarchy:
```js
const widget = vtkLineWidget.newInstance();
const instance = widgetManager.addWidget(widget, ViewTypes.SLICE);
console.log(instance.get(['classHierarchy']))
```

### Context ###
I found a `visibility` property in my line widget `model` and could not understand why because I only looked at the model class hierarchy.

**Comment by floryst** [comment]
One suggestion is that, when adding to the hierarchy, duplicates are dropped. I believe the class hierarchy is just used to determine if the current class derives from another class. (Of course, this has issues when multiple inheritance overwrites shared member variables, but that problem existed in the first place and is orthogonal.)
