### ISSUE TITLE
Empty scene returning white canvas

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1917]
### High-level description
Hello,

After updating VTK.js to the latest version, creating an empty scene returns a blank canvas.

### Steps to reproduce
```js
    // VTK renderWindow/renderer
    this.renderer = vtkRenderer.newInstance()
    this.renderWindow = vtkRenderWindow.newInstance()
    this.renderWindow.addRenderer(this.renderer)

    // OpenGLRenderWindow
    this.openGLRenderWindow = vtkOpenGLRenderWindow.newInstance()
    this.openGLRenderWindow.setContainer(this.mount)
    this.openGLRenderWindow.setSize(width, height)
    this.renderWindow.addView(this.openGLRenderWindow)

    // Interactor
    this.interactor = vtkRenderWindowInteractor.newInstance()
    this.interactor.setInteractorStyle(vtkInteractorStyleTrackballCamera.newInstance())
    this.interactor.setView(this.openGLRenderWindow)
    this.interactor.initialize()
    this.interactor.bindEvents(this.mount)
```

```html
render() {
		return (
			<React.Fragment>
				<div
					className='vtk-canvas'
					ref={(mount) => {
						this.mount = mount
					}}
				/>
			</React.Fragment>
		)
	}
```

### Detailed behavior
![image](https://user-images.githubusercontent.com/47977073/118480800-002ad200-b713-11eb-9548-1c9a981fd7ce.png)

### Environment
- **vtk.js**: 18.1.1
- **OS**: Windows 10
- **Browser**: Chromium 83.0.4103.122 (Electron v9.4.1)

**Comment by jourdain** [comment]
Any console error or anything else?

**Comment by zbouslikhin** [comment]
@jourdain 
Nothing at all.

**Comment by jourdain** [comment]
Oh, yes... You need to import some Rendering [profile](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/OpenGL/Profiles) like shown [here](https://github.com/Kitware/vtk-js/blob/master/Examples/Applications/GeometryViewer/index.js#L7) for example.

**Comment by zbouslikhin** [comment]
It does work now, thank you!

**Comment by jourdain** [comment]
See the [changelog](https://github.com/Kitware/vtk-js/releases/tag/v18.0.0)
