### ISSUE TITLE
SphereMapper doesn't update on polydata.modified

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1921]
### High-level description
Hello,

As right now, I have Polydata surface mesh structure that I constantly modify and update the shape of the actor.
Feeding data to a simple VTK mapper using `setInputData` and updating the Polydata automatically updates the actor.
However, feeding data to sphereMapper using `setInputData` and updating the Polydata does not update the actor. 
### Steps to reproduce
```js
// After modifying the PolyData
currentPolyData.modified() 

const pointActor = vtkActor.newInstance()
const pointMapper = vtkMapper.newInstance()

const meshActor = vtkActor.newInstance()
const meshMapper = vtkSphereMapper.newInstance();

pointMapper.setInputData(currentPolyData) // Is updated
meshMapper.setInputData(currentPolyData) // is not updated

renderWindow.render()
```
### Expected behavior
Sphere mapper to updated as well.

### Environment
- **vtk.js**: 16.13.1
- **OS**: Windows 10
- **Browser**: Chromium 83.0.4103.122 (Electron v9.4.1)

**Comment by zbouslikhin** [comment]
Looks like it's working as expected using vtk.js: 18.1.1

**Comment by zbouslikhin** [comment]
#1923 might be related.

**Comment by jourdain** [comment]
Let's close it if you see it fix on your end. Especially if it was related to the missing profile for the rendering part.

**Comment by jourdain** [comment]
Feel free to re-open if that is not the case.

**Comment by zbouslikhin** [comment]
> Looks like it's working as expected using vtk.js: 18.1.1.
> I'll leave this open until approved that this is not a bug, or was fixed.
> 
> EDIT: though it is updated, vtkSphereMapper doesn't render spheres, but a shape. #1923 might be related.

As an update to this comment, vtkSphereMapper does render spheres right now after importing the missing profile for the rendering part, but SphereMapper does not update on polydata.modified (original problem)

**Comment by finetjul** [comment]
@zbouslikhin, can you please write a [test](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/Core/SphereMapper/test), an [example](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/SphereMapper/example/index.js) or a codepen example that demonstrates the problem?
Thanks.

**Comment by zbouslikhin** [comment]
> @zbouslikhin, can you please write a [test](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/Core/SphereMapper/test), an [example](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/SphereMapper/example/index.js) or a codepen example that demonstrates the problem?
> Thanks.

Here are three JSFiddles demonstrating the problem:
- What is expected to happen: https://jsfiddle.net/guo1zafn/8/
- Doesn't work - sphereMapper: https://jsfiddle.net/n3jf98mt/92/
- Doesn't work - glyph3DMapper: https://jsfiddle.net/ndz3fokx/40/

Now that I'm thinking about with some hindsight, Updating the vertex array of a polydata linked to a sphereMapper or glyph3DMapper might not mean to hide that point, if that makes sense.

**Comment by finetjul** [comment]
Indeed, the vtkSphereMapper and vtkGlyph3DMapper do not consider the `verts` cell array at all.
Your polydata can only contain points, no need for cells.

**Comment by zbouslikhin** [comment]
Is there any other way then to hide say one specific sphere without having to create a single typed array which contains a shrink view of it with just the list of points needed to be visualized and then recompute the mapper?

Recomputing might significantly slow down the process in case of a big list of points.

**Comment by finetjul** [comment]
You may want to use a point scalar array to "scale to 0" points you want invisible.

**Comment by zbouslikhin** [comment]
Sweet, I'll give that a go. Thanks!
