### ISSUE TITLE
AverageIPScalar not working

### ISSUE THREAD

**Issue by GeorgeFuller** [Kitware/vtk-js#1924]
### High-level description
AverageIPScalar not behaving as expected.

I've been trying to use the AverageIPScalar so limit the values rendered with and average blend mode. I haven't had any luck getting this running. 

### Steps to reproduce
In the VolumeMapperBlendModes example add:

`mapper.setAverageIPScalarRange(0.0, 0.9);`

The volume is now not visible when selecting average blend mode.

### Expected behavior
The volume would average all the values between 0.0 and 0.9

**Comment by GeorgeFuller** [comment]
I took a look through this to see if i could figure out what's going on and I noticed that the setAverageIPScalarRange doesn't handle floats.
I've also noticed that the shader doesn't seem to handle single component volumes. I attempted to fix these issues here but I've either created some new ones or missed some further issues:
https://github.com/GeorgeFuller/vtk-js

**Comment by GeorgeFuller** [comment]
![averageIPScalarTest](https://user-images.githubusercontent.com/7668858/118969803-69098880-b965-11eb-95f7-c76f7fecbe61.gif)
I've attached a little gif of what happens after I've applied those changes. You can get to this by checking out https://github.com/GeorgeFuller/vtk-js/tree/average_ip_scalar_fix
and running
`npm run example -- VolumeMapperBlendModes`
then switch the averageBlendMode

**Comment by jourdain** [comment]
Can you create a PR from your branch as it will be easier to look at the diff? Thanks!
