### ISSUE TITLE
Bug in ResliceCursorWidget example caused by LiteHttpDataAccessHelper

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#1927]
### High-level description
The [reslice cursor example](https://kitware.github.io/vtk-js/examples/ResliceCursorWidget/index.html) is broken because of a reader

### Detailed behavior
The raised error when we launch the example is the following:
`Error: LiteHttpDataAccessHelper does not support compression. Need to register HttpDataAccessHelper instead.
`
### Expected behavior
A display image

**Comment by jourdain** [comment]
@laurennlam feel free to do a PR, that is an easy fix

**Comment by laurennlam** [comment]
#1937
