### ISSUE TITLE
View becomes completely black when attempting to pan in InteractorStyleUnicam example

### ISSUE THREAD

**Issue by tamaynard** [Kitware/vtk-js#1935]
### High-level description

When attempting to run the InteractorStyleUnicam demo (https://kitware.github.io/vtk-js/examples/InteractorStyleUnicam.html), if you attempt to pan by clicking on the cone rather than the background, the view becomes completely blank, including the orientation marker, if enabled.

### Steps to reproduce

1. Go to https://kitware.github.io/vtk-js/examples/InteractorStyleUnicam.html
2. Click within the boundaries of the displayed cone object
3. Without releasing the mouse button, move the mouse

### Detailed behavior

Once the view has been blanked it is impossible to recover without a page refresh. Also there doesn't appear to be any relevant info/messages in the browser's debug console that would indicate a possible source of this issue.

### Expected behavior
Clicking on an object in the scene to pan should have the same effect as clicking on the background

**Comment by finetjul** [comment]
@laurentmalka an idea of what's going on ?

**Comment by daker** [comment]
I think this was fixed, not sure why it wasn't closed by the bot @jourdain

**Comment by martinken** [comment]
Hmm yes, it should be fixed, and thought the bot would have closed it. Closing it now.
