### ISSUE TITLE
Incorrect volume mapper bounds  

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#1936]
### High-level description

Volume mapper bounds are incorrect

### Steps to reproduce

This is a bug for rendering the first and last slice.

 It is visible on any sample data (headsq.vti etc). Also, I have created a synthetic dicom data set with long stripes in each slice along the y-axis, which change position for each slice (illustration below).
In addition, if we manually change the intensity values of the first and last slice in `headsq.vti`, we can see the cut at the edges.
 

### Expected behavior

Bounds should be to the edge of the volume.

### Environment
- **vtk.js**:  17.xx, 18.xx
- **OS**:  MacOS
- **Browser**:  Chrome 90.0.4430.212

#### Code Sandbox link

https://codesandbox.io/s/volume-rendering-bounds-exp9h?file=/src/index.js

headsq.vti with the changed intensity value for the first and last slice
- As seen, the slice thickness is not consistent and the last slice is thinner (as if bounds are forcing it to get cut)
- If interpolation is nearest, the last slice is gone

#### With linear interpolation
![image](https://user-images.githubusercontent.com/7490180/119558297-3994ba80-bd6f-11eb-9f5f-c0ebc56ee546.png)

With nearest interpolation
![image](https://user-images.githubusercontent.com/7490180/119559871-38648d00-bd71-11eb-832e-6d2850865e2c.png)

This becomes more clear if we intentionally increase the slice thickness (below screenshot is from local running of demo, not in sandbox)
![image](https://user-images.githubusercontent.com/7490180/119562346-3a7c1b00-bd74-11eb-95ea-7d89cd1343f4.png)

Test dicom files can be downloaded from [my dropbox (9kb)-10 slices](https://www.dropbox.com/s/eng1kkqkl5ec49d/Archive.zip?dl=0) and can be dropped into paraview glance for volume rendering as well

Synthetic data illustration
![image](https://user-images.githubusercontent.com/7490180/119561408-1d931800-bd73-11eb-9728-74c334a59c05.png)

Paraview glance volume rendering on the left, with the slice rendering on the right

![image](https://user-images.githubusercontent.com/7490180/119563109-2be23380-bd75-11eb-8ffb-3e87b137c892.png)

**Comment by sedghi** [comment]
I have tried 3D Slicer for volume rendering and I'm getting different renderings depending on CPU, GPU or Multi-volume. 

I recorded my screen and you can see it here

The data I used can be find [here](https://www.dropbox.com/sh/5bbydxnvl6vn87h/AAC306PdHRXyeu8WCGKe9DQQa?dl=0) (same as before)

https://user-images.githubusercontent.com/7490180/119839031-da9b8680-bed1-11eb-8ab5-a8e768d8d00f.mp4

**Comment by sedghi** [comment]
Dropping the nrrd into the paraview glance + turning on the slice mappers shows some accumulated error

<img src="https://user-images.githubusercontent.com/7490180/120514237-0ec3eb00-c39b-11eb-9f53-b4f65e3c63f9.png" width="600" height="400">


Taking a look into the OpenGL volumeMapper [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js). @floryst Is there any reason `vsize` definition is not consistent in the code?

1. In [`replaceShaderValues`](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L171-L178) we have 

    ```
    const ext = model.currentInput.getExtent();
    const spc = model.currentInput.getSpacing(); 
   const vsize = new Float64Array(3);
    vec3.set(
      vsize, 
     (ext[1] - ext[0]) * spc[0],
     (ext[3] - ext[2]) * spc[1],
     (ext[5] - ext[4]) * spc[2]);
    const maxSamples =      vec3.length(vsize) / model.renderable.getSampleDistance();
    ```
2. In [`getNeedToRebuildShaders`](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L415-L426) we have:

    ```
    const ext = model.currentInput.getExtent();
    const spc = model.currentInput.getSpacing(); 
   const vsize = new Float64Array(3);
    vec3.set(
      vsize, 
     (ext[1] - ext[0]) * spc[0],
     (ext[3] - ext[2]) * spc[1],
     (ext[5] - ext[4]) * spc[2]);
    const maxSamples =  vec3.length(vsize) / model.renderable.getSampleDistance();
    ```
3. Lastly, in [`setCameraShaderParameters `](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L635-L644) we have:

    ```
    const ext = model.currentInput.getExtent();
    const spc = model.currentInput.getSpacing(); 
   const vsize = new Float64Array(3);
    vec3.set(
      vsize, 
     (ext[1] - ext[0] + 1) * spc[0],
     (ext[3] - ext[2] + 1) * spc[1],
     (ext[5] - ext[4] + 1) * spc[2]);
    ...
    ...
    vec3.set(vctoijk, 1.0, 1.0, 1.0);
    vec3.divide(vctoijk, vctoijk, vsize);
    program.setUniform3f('vVCToIJK', vctoijk[0], vctoijk[1], vctoijk[2]);
    ```

The last one makes a wrong `vVCToIJK` matrix as a result which is used in the [shader](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L977).

Removing the `+1`s from the last `vsize` definition, results in a correct rendering. 


Before: 

![chrome-capture (5)](https://user-images.githubusercontent.com/7490180/120516100-fe147480-c39c-11eb-8bd1-8cb1b263f2e3.gif)


After:
![chrome-capture (6)](https://user-images.githubusercontent.com/7490180/120516221-1dab9d00-c39d-11eb-8f15-1830e5fda2d9.gif)




Attachements:
- [test data nrrd](https://www.dropbox.com/s/ms6x34yrdnqqyvq/synthetic_dicom.nrrd?dl=0)
- [test data vti](https://www.dropbox.com/s/7alse5zftjykczs/synthetic.vti.zip?dl=0)
- [paraview glance state](https://www.dropbox.com/s/y2s4irupsl8voom/synthetic.glance?dl=0)

**Comment by agirault** [comment]
@sedghi thank you very much for the thorough bug report! That's very appreciated.

@martinken looks like the `+1` was introduced here to fix some other bug: https://github.com/Kitware/vtk-js/commit/dbd4dac3f28208da8ad4592bebc6bc087a2b942e. Is there a test or reference to the bug in question somewhere, to make sure reverting wouldn't just break something else?

Also noting that we should be careful of using the ImageMapper as the ground truth for bounds because of #1553

**Comment by sedghi** [comment]
So the vsize and the `+1` that is introduced _might_ be the problem here, 
Something that is also wrong and might be the actual bug is the location of the volume in space 

**Data**: 10 slices, each slice has a bar with value of 255 (explanation above)

If you visualize the data in 3D slicer (vtk c++) and the first and last voxel center pos (two spheres) we get:
![image](https://user-images.githubusercontent.com/7490180/121280341-26700780-c8a4-11eb-8859-3aeddf271752.png)

I understand volume rendering does not render half of the first and last voxel (8 full squares and 2 half ones), but looking at the vtk.js example I created codeSandbox [here](https://codesandbox.io/s/volume-bounds-sphere-jzqvt?file=/src/index.js) we can see that only 9 squares are showing up, but more importantly is how volume is rendered between the sphere corners which should be similar to 3D slicer view (8 full and 2 half ones)

![image](https://user-images.githubusercontent.com/7490180/121281427-deea7b00-c8a5-11eb-89b6-b5db784987be.png)

**Comment by agirault** [comment]
> vtk c++ and vtk js should be able to give a consistent rendering

What do you get in Paraview? Slicer has a layer over the `vtkImageData` to add things like orientation, and might be actually doing some work to counter the #1553 issue (also seen in paraview [here](https://gitlab.kitware.com/paraview/paraview/-/issues/18276))

**Comment by agirault** [comment]
Hi @sedghi, @swederik.

We discussed the state of your change last week: [as mentioned in the PR](https://github.com/Kitware/vtk-js/pull/1993#issuecomment-883396606), we envision more changes to do things properly and consistently with the image data, mapper, and volume mapper. The changes we plan to do involve:
- Changing the convention for bounds and origin in ImageData (still using point data, but basically treated as cell data)
  - origin will be the center of the first pixel
  - bounds will encapsulate all of the representation, to properly fit spacing (i.e.: a single pixel will have bounds, outer of the represented image)
- Update the volume mapper to adjust to this new convention (different from your fix)
- Update the image mapper to adjust to this new convention 

Given our current funding and available staffing, we've planned to have someone working on this realistically mid-October. We hope that'll work for you and that distributing your change in a `beta` release is satisfactory in the meantime. Of course, you're more welcome to contribute to some of those changes yourself if you're looking to get things in `master` in a shorter timeline.
