### ISSUE TITLE
Support for context sharing for multiple canvases

### ISSUE THREAD

**Issue by adam-urbanczyk** [Kitware/vtk-js#1940]
### Need
It would be great if vtk.js supported sharing of webgl contexts so that displaying of many objects on separate canvases in one page is possible.

### Feature
Short investigation shows that similar feature is possible and implemented in three.js or twgl using a `scissor` approach
https://threejs.org/examples/webgl_multiple_elements.html
http://twgljs.org/examples/itemlist.html

see also:

https://webglfundamentals.org/webgl/lessons/webgl-multiple-views.html

**Comment by jourdain** [comment]
I'll try to come up with an example with the current API.
The idea is to create a single GLRW and all the "views" are just renderers in it with proper viewport location.

**Comment by adam-urbanczyk** [comment]
Great, thanks a lot!

**Comment by adam-urbanczyk** [comment]
Thanks again @jourdain ! I will use this in https://github.com/CadQuery/cadquery/pull/735 .

**Comment by adam-urbanczyk** [comment]
One additional question (maybe an issue) regarding https://kitware.github.io/vtk-js/examples/ManyRenderers/index.html . It seems that the scroll wheel results both in zooming and webpage scrolling when the mouse hovers over one of the views. Is there a simple solution withing vtk.js to prevent the latter?

**Comment by jourdain** [comment]
Use another interactor style. The manipulator ones are better and you can reconfigure them at enter/leave events.
The one I used in the example is keeping a renderer as active by default hence the zooming issue.

**Comment by jourdain** [comment]
For the example I didn't wanted to add more code complexity and I was trying to focus only on the "Many renderers" aspect.
It is possible that we need to fix something in vtk.js to have the Manipulator style works with non overlapping renderers.
