### ISSUE TITLE
Voxel representation of VTI

### ISSUE THREAD

**Issue by gaston-perret** [Kitware/vtk-js#1950]
### Need

Get a voxel representation of a VTI dataset. This is achieved in Paraview with the threshold filter. Or in this next examples with vtk python and c++ libraries
https://kitware.github.io/vtk-examples/site/Python/Medical/GenerateCubesFromLabels/
https://kitware.github.io/vtk-examples/site/Cxx/Medical/GenerateCubesFromLabels/
### Feature

A filter in vtk js that generates a voxel representation of the dataset.
The result would be something like this:
![image](https://user-images.githubusercontent.com/66233297/120516107-610a0980-c3a5-11eb-9ef0-8d6143fff7a3.png)

**Comment by jourdain** [comment]
We should implement masking on vtkImageData (~threshold) and a filter to generate a vtkPolyData of the skin.
Doing those two things are not that difficult in plain JS.

**Comment by gaston-perret** [comment]
> We should implement masking on vtkImageData (~threshold) and a filter to generate a vtkPolyData of the skin.
> Doing those two things are not that difficult in plain JS.

Thank you that helped. We worked it out implementing a filter similar to threshold and then converting the vti to vtp to render the voxels. I'll close the issue.

**Comment by jourdain** [comment]
Feel free to contribute your filter to vtk.js if you feel that it could be useful for others.
