### ISSUE TITLE
Widget unpickability should be enforced on widget representation

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#1988]
If you make a widget not pickable:
`widget.setPickable(false);`
or 
`widgetInView.setPickable(false);`

It does not propagate the pickability onto its representations.
Therefore its components (think of handles) are pickable but not the widget.

Worst, setting `setPickable()` on the widget representation has no effect. It does not propagate pickability to actors. Widget representation picking is actually handled by the visibility of their actors being turned off when picking happens (see [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Representations/WidgetRepresentation/index.js#L143)).
Therefore there are 2 mechanisms to handle pickability in vtk.js: visibility in the context of picking and pickable property.

I think for a representation (Context or Handle) to be pickable it needs to be pickable AND the widget be pickable.

Therefore, I would suggest to do the following:
 - have the scenegraph be a tree instead of a list. 
 - If pickable is false on a prop, prop children should not be pickable even if their pickable value is true.

**Comment by finetjul** [comment]
https://codesandbox.io/s/spline-picking-o9kpf

**Comment by agirault** [comment]
@floryst is that also an issue between the widget "factory" (too often called "widget") and the actual widget representations?

**Comment by floryst** [comment]
Just to clarify: calling `widgetFactory.setPickable(true)` will call `viewWidget.setPickable(true)` for all widget instances (those that extend AbstractWidget), so calling `setPickable` on the factory vs the widgets themselves make no difference.

It would be preferable if setting `pickable` (or any other flag) to `false` on a vtkProp would cause children props to never be picked, regardless of the children Prop's `pickable` flag. However, I am not 100% sure if the vtk.js rendering pipeline could support that. @martinken any thoughts on that?

There are two immediate solutions to this that I can see:
- Widget.setPickable() -> WidgetRepresentations: set pickable on all reps in `model.representations`
- WidgetRepresentations -> underlying Actors: use `pickable` flag in `WidgetRepresentation.updateActorVisibility()`.

**Comment by martinken** [comment]
pickable should be inherited by any props that have subprops. Probably the easiest (yet still performant) way to do that is to

- add ParentProp ivar to Prop
- set that on any nested props
- modify getpickable() to chain up the tree returning false if any parent is false.

**Comment by finetjul** [comment]
Please note that `visibility`, `dragable`, `userMatrix` (and bounds, origin, position...) are also good candidates to combine with their parent values.

@martinken @jourdain it would be misleading if `getPickable()` does not return the `pickable` model variable set on the prop, wouldn't it?  Shouldn't we either create a new function (to "compute" the pickability by taking into account its ancestors pickability) or rename `pickable` into `internalPickable` (but that's a major change) .

For the new function name, it suggest `computePickable`, `isPickable` (@floryst for consistency, we might have to remove the convenient `isVisible` function in the widget state), `getWorldPickable` or `getFinalPickable`. Do you have some better naming suggestion ?

**Comment by agirault** [comment]
Name suggestions:
- getPickableWithParents / Ancestors
- getPickableAsNestedProp
- getPickableAsDependentProp
- getPickable(nested: Bool)

**Comment by floryst** [comment]
I like the idea of doing something like `getPickable({ withParents: true })`. This is nice if getPickable ever gets any other options. Realistically, it might not, so `getPickableWithParents()` or `getPickableAsNestedProp()` is sufficient. The latter does require less typing. :)

**Comment by finetjul** [comment]
I think it should be fast, so I prefer a new function rather than `named parameters`.

Because we already have `getNestedProps()`, I think I'll go with `getPickableAsNestedProp()` if no one objects.

**Comment by martinken** [comment]
I like set/getPickable (acts on the instance) and isPickable evaluates the tree

But I think I like even more getNestedPickable getNestedVisibility and getNestedUserMatrix have a nice feel to them as well since we already have the concept of "nested" in vtkProp.  But will +1 whatever name you settle on.

**Comment by finetjul** [comment]
I ruled out `isPickable()` because it does not work with `userMatrix` (which I have not implemented).

So I think `getNested[Pickable|Visibility|UserMatrix]()` is the best ! Thanks !

**Comment by agirault** [comment]
Only one comment: anybody using auto-completion will probably discover `getPickableAsNestedProp()` more easily than `getNestedPickable()`, though the latter does sound better.
