### ISSUE TITLE
RemoteView & vtkWebApplication doesnt draw any widgets

### ISSUE THREAD

**Issue by lambacini** [Kitware/vtk-js#1991]
### Description
when we testing vtk.js remote view, we encountered a problem . This problem about;
We couldn't add any vtkWidgets. If you try this case, you will observe it.

For example:
axes = vtk.vtkAxesActor()
widget = vtk.vtkOrientationMarkerWidget()
widget.SetCurrentRenderer(ren)
widget.SetOrientationMarker(axes)
widget.SetInteractor(iren)
widget.SetEnabled(1)

cubeActor = vtk.vtkCubeAxesActor()
cubeActor.SetBounds(volume.GetBounds())
cubeActor.SetCamera(ren.GetActiveCamera())
ren.AddActor(cubeActor)

In addition, We see normal vtkActor and volume in vtkRemoteView and output window ( renderwindow), but any vtkWidgets does not appear on the vtkRemoteView and output window( renderwindow)

### Environment
- **vtk.js**:  18.4.1
- **OS**: Windows 10
- **Browser**: Chrome

**Comment by jourdain** [comment]
This is not true, orientation widget or any other widgets that get rendered on the server side is properly rendered with the vtkRemoteView. The issue might be on your server side code.
