### ISSUE TITLE
FBX request

### ISSUE THREAD

**Issue by liuyazui** [Kitware/vtk-js#2004]

**Comment by finetjul** [comment]
There is currently nothing available in VTK.JS to import FBX files.
You can however do something similar to obj-mtl-importer.py. By converting the FBX file into a file format supported by VTK.JS
Apparently there are some [python SDKs](https://en.wikipedia.org/wiki/FBX#Limitations) to read such FBX files.

**Comment by liuyazui** [comment]
ok thanks
