### ISSUE TITLE
ImageCroppingWidget interaction broken when origin is not [0,0,0]

### ISSUE THREAD

**Issue by ronzim** [Kitware/vtk-js#2008]
When dragging an handle, it seems that only the X movement of the mouse has an effect, while dragging in the Y direction has no effect. This behaviour changes with different images. I've found that setting image origin to [0,0,0] fix the issue.

### Steps to reproduce
A simple way to reproduce the issue is using the ImageCroppingWidget example on vtk.js examples page. Just force image origin to be not [0,0,0] (ie image.setSpacing(200,200,200) )and interact with handles on the cube widget faces.

### Environment
- **vtk.js**: 18.7.2
- **Browser**: Chrome

**Comment by finetjul** [comment]
Bug should be located in Widgets/Widgets3D/ImageCroppingWidget/behavior.js, in the [publicAPI.handleEvent()](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js#L43) function.

**Comment by ronzim** [comment]
Thanks @finetjul, I hope to give a look at this next week.
