### ISSUE TITLE
Lines connection: bug?

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2011]
### High-level description
Hello,

I have 6 points in total where each 3 points represent a triangle. My goal is to connect each point in a triangle with a line without having any line connecting the two triangles together.
After defining the array `let edgesw = [10, 0, 1, 2, 0, -1, 3, 4, 5, 3]` (assuming that -1 doesn't exist and therefore doesn't connect anything to anything) that will be passed to  `setLine(edgesw)`, visually in the wireframe mode, there's no line connected to point 0 and point 3. However, after switching to surface mode, they are connected.
Now, I'm not sure whether I'm doing right or wrong nor if it is even possible to ignore one line in therefore, I'm not so sure if this is a bug or not.

Ignore the brown lines/points. Please consider only the white points/lines.
![image](https://user-images.githubusercontent.com/47977073/126809888-14e5e608-5ece-420b-a8a1-826e3a05f365.png)
![image](https://user-images.githubusercontent.com/47977073/126809917-e00de4a4-2604-49ee-a71e-2f2019451d45.png)
![image](https://user-images.githubusercontent.com/47977073/126809940-0374d609-1c33-4663-be4b-55e792d06983.png)

### Steps to reproduce
```js
let tmp = [1135.7, 6.9, 87, 2, 0, 1]
let edgesw = [10, 0, 1, 2, 0, -1, 3, 4, 5, 3]
dataset = vtkPolyData.newInstance();
dataset.getPoints().setData(tmp , 3);
dataset.getLines().setData(edgesw, 1);
dataset.getPolys().setData(edgesw, 1);
```

### Expected behavior
No line between point 0 and 3

### Environment
- **vtk.js**: 18.1.1
- **OS**: Windows 10
- **Browser**:  Chromium 83.0.4103.122 (Electron v9.4.1)

**Comment by zbouslikhin** [comment]
This did achieve it.
```js
let edgesw = [4, 0, 1, 2, 0, 3, 4, 5, 3]
```

**Comment by finetjul** [comment]
Shouldn't it be instead:
```
dataset = vtkPolyData.newInstance();
dataset.getPoints().setData([x1, y1, z1, x2, y2, z2, ...]], 3);
dataset.getLines().setData([4, 0, 1, 2, 0,            4, 3, 4, 5, 3], 1);
dataset.getPolys().setData([3, 0, 1, 2,          3, 3, 4, 5], 1);
```
