### ISSUE TITLE
Your documentation is terrible

### ISSUE THREAD

**Issue by lkxlonely** [Kitware/vtk-js#2012]
### Need

Use of vtk.Filters.Cornerstone.vtkImageDataToCornerstoneImage
### Feature

There is no documentation, and other API descriptions are not clear, and there is no source code example.

**Comment by finetjul** [comment]
I agree with you that VTK.js documenation could be improved (contribution is welcomed ;-) ).
We could for example, create a "filtering usage" in our [doc](http://kitware.github.io/vtk-js/docs/index.html). 
I would argue that in this precise case, it seems to be more Cornerstone documentation that is missing.

By the way, have you considered [vtk.js/ohif tutorial](http://kitware.github.io/vtk-js/docs/tutorial.html) ?

**Comment by lkxlonely** [comment]
> I agree with you that VTK.js documenation could be improved (contribution is welcomed ;-) ).
> We could for example, create a "filtering usage" in our [doc](http://kitware.github.io/vtk-js/docs/index.html).
> I would argue that in this precise case, it seems to be more Cornerstone documentation that is missing.
> 
> By the way, have you considered [vtk.js/ohif tutorial](http://kitware.github.io/vtk-js/docs/tutorial.html) ?

The link you provided is not accessible.
I need to see to decide.

**Comment by finetjul** [comment]
I can access the link.
Go on http://kitware.github.io/vtk-js/docs/ and search for tutorial.

**Comment by lkxlonely** [comment]
> I can access the link.
> Go on http://kitware.github.io/vtk-js/docs/ and search for tutorial.

![image](https://user-images.githubusercontent.com/36163926/126957614-173a937d-423a-4feb-98fc-4a6631a20014.png)

**Comment by finetjul** [comment]
![image](https://user-images.githubusercontent.com/219044/126959128-6aee4700-9868-495e-992e-43c741f0bcdd.png)

Anyway, here are the important links:
[ [Slides](https://docs.google.com/presentation/d/1NCJxpfx_qUGJI_2DhbECzaOg0k-Z6b65QlUptCofN-A/edit#slide=id.p) | [Video](https://vimeo.com/375520781) ] Introduction to VTK.js and OHIF
[ [Slides](https://docs.google.com/presentation/d/17TCS6EhFi6SWFIrcAJ-DFdFzFFL-WD9BBTv-owmMdDU/edit?usp=sharing) | https://vimeo.com/375521036 ] Developing with VTK.js
[ [Slides](https://docs.google.com/presentation/d/1Sr1OGxMSw0oCt46koKQbmwSIE11Kqq8MGtyW3W0ASpk/edit?usp=gmail_thread) | [Video](https://vimeo.com/375521810) ] VTK.js Architecture and Tooling
[ [Slides](https://docs.google.com/presentation/d/1Iwg-u01HGVf1CgC6NbcBD3gm3uHN9WhjU59FSz55TN8/edit?ts=5d9c9ce4#slide=id.g59aa99cda4_0_131) | [Video](https://vimeo.com/375521206) ] OHIF + VTK.js Integration
