### ISSUE TITLE
Customize automated layout of ScalarBarActor

### ISSUE THREAD

**Issue by NGimbal** [Kitware/vtk-js#2020]
### Need

Customize automated layout of ScalarBarActor

The automated layout function works well but I'm running into this situation:

<img src="https://user-images.githubusercontent.com/34066664/127878548-e3a6cd7d-f0a3-4f20-b278-ca2f76753105.png" width="98" height="350" />

### Feature

Automated ScalarBarActor layout function is here:
https://github.com/Kitware/vtk-js/blob/b617e02a7d09c5044f559b28e0bb4c67dad3b639/Sources/Rendering/Core/ScalarBarActor/index.js#L52

I would like to pass a custom function that would be called instead of this default layout function.

```javascript
const scalarBarActor = vtkScalarBarActor.newInstance({
  automated: true,
  autoCompute: () => {
    // layout the legend here
    ...
  }
```

An alternative proposal would be to parameterize parts of this automated layout function, but allowing a user to override the function entirely would be an extremely flexible approach.

I would be willing to submit a PR to add this small improvement.

**Comment by jourdain** [comment]
That seems reasonable to me. Feel free to submit a PR with those changes.

Thanks for your suggestion!
