### ISSUE TITLE
Hardware Selector tolerance?

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#2023]
### Need

I'm looking for a way to increase the tolerance of the hardware selector so that it's easier to select small actors/geometries.

### Feature

Something similar to the existing PointPicker#setTolerance method would be awesome.

**Comment by jourdain** [comment]
Hardware selector is really based on rendering pixels. So if your object became smaller than a pixel, it will be hard to make it selectable. 

If on the other hand you are trying to fake a fat pointer, you can do that by just extending the area you perform selection on.

**Comment by FezVrasta** [comment]
Thanks, yes in my case the element is at least a pixel, I just want a fat pointer. So is it okay to basically call the hardware selector multiple times on as many points as my pointer should be large?

This is something that would be very useful for the picking behavior of react-vtk-js View component.

How do I know of how many "units" should I move the picker in order to cover all the pixels and not do useless calls?

**Comment by jourdain** [comment]
No, the hardware selector use an area (box: x1, y1, x2, y2) for its selection and therefore, you should just make sure you are not providing x1=x2 and y1=y2.

I guess for react-vtk-js we should have a pointerSize attribute which will affect that picking area. You can see the usage of that [method](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L479)

**Comment by FezVrasta** [comment]
Ah ok thanks! I'll prepare a PR if you don't mind.
