### ISSUE TITLE
Resetting an array property

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#2026]
`model` array properties can be initialized to `undefined` (by not specifying the property in `DEFAULT_VALUES`), `null`, an empty array `[]` or a valid `[0, 0, 0]` array.

However, once the property is changed (e.g. `setMyProp([1, 2, 3])`, it is no longer possible to reset the property to its initial `undefined`/`null`/`[]` value. 

Wouldn't it make sense to support `undefined`/`null`/`[]` in `macro.setArray` ?
It would be helpful to better deal with uninitialized properties see. 

_See discussion with @floryst in https://github.com/Kitware/vtk-js/pull/2021#discussion_r681933915_

**Comment by jourdain** [comment]
are you looking for a add-on method `resetMyProp()` method? Or you just want to call `setMyProp(null)` to perform a model.myProp = null?

**Comment by finetjul** [comment]
Either way works for me. I was more thinking of `setMyProp(null)` though.

**Comment by jourdain** [comment]
Then it should just be added inside macro and documented (ts comment of something).

At least that is an easy fix that will became available everywhere once macro is updated...

**Comment by floryst** [comment]
I think this is a reasonable idea. We will need to add a check to allow null/undefined/empty array when calling setArray.

**Comment by finetjul** [comment]
@jourdain @floryst Please consider this [commit](https://github.com/Kitware/vtk-js/pull/2021/commits/761aafca96aac7c5585061b63dc4331547da3b16)
Note that: 
 - `size` (in `setArray(..., size, ...)`) is still optional, i.e. no array size is enforced
 - an array attribute, if defined (not `undefined` nor `null`) at initialization is now enforced to be of the expected size (if a size specified) when `setGetArray()` is called.

**Comment by jourdain** [comment]
Glancing through the code for the macro+test it seems reasonable.
