### ISSUE TITLE
MPR has an API for the previous page and the next page of the scroll wheel event on the mobile terminal

### ISSUE THREAD

**Issue by itsRaul** [Kitware/vtk-js#2028]

**Comment by itsRaul** [comment]
I am using vtkjs to develop MPR, and the PC browser uses the mouse wheel to scroll the previous page and the next page, but it cannot be used on the mobile terminal. Is there any related API?

**Comment by finetjul** [comment]
What vtk.js class are you using when you say "MPR" ?
vtkRenderWindowInteractor has support for finger gestures, so I believe it should be feasible to support double finger for scrolling. Feel free to contribute a PR.

**Comment by itsRaul** [comment]
![image](https://user-images.githubusercontent.com/32694558/128132233-c27e14aa-938d-4116-a097-391f5e6a1bfe.png)
GenericRenderWindow rendering can support The scroll wheel scrolls up and down, but does not support mobile browsers to scroll up and down with fingers

**Comment by itsRaul** [comment]
> What vtk.js class are you using when you say "MPR" ?
> vtkRenderWindowInteractor has support for finger gestures, so I believe it should be feasible to support double finger for scrolling. Feel free to contribute a PR.

**Comment by itsRaul** [comment]
> What vtk.js class are you using when you say "MPR" ?
> vtkRenderWindowInteractor has support for finger gestures, so I believe it should be feasible to support double finger for scrolling. Feel free to contribute a PR.
![image](https://user-images.githubusercontent.com/32694558/128133372-0f32410b-10c9-4135-b21a-7bc00f249bc2.png)
GenericRenderWindow rendering can support The scroll wheel scrolls up and down, but does not support mobile browsers to scroll up and down with fingers
