### ISSUE TITLE
[regression] worldToDisplay returns doubled coordinates

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#2029]
### High-level description

Starting from @kitware/vtk.ks@19.0.4 the `worldToDisplay` method returns wrong values (they are double their supposed value).

With 19.0.3 everything is okay.

### Steps to reproduce

```js
const viewCtx = useContext(Contexts.ViewContext);
const renderer = viewCtx?.renderer;
const view = renderer?.getRenderWindow()?.getViews()[0];

console.log(view?.worldToDisplay(point[0], point[1], point[2], renderer));
```

`openglRenderWindow.worldToDisplay(point[0], point[1], point[2], renderer)` has the same issue.

### Detailed behavior

The values are correct if I divide them by 2, I think it may relate to `getPixelWorldHeightAtCoord` changes made in 19.0.4

### Expected behavior

The returned values should be correct.

### Environment
- **vtk.js**: 19.0.4
- **OS**: macOS
- **Browser**: Chrome 91

**Comment by daker** [comment]
@finetjul

**Comment by FezVrasta** [comment]
I think this is dependent by the host screen resolution, on a low dpi machine everything works as intended, but on my 5K hidpi iMac it doesn't

**Comment by jourdain** [comment]
I was going to say it must be related to the pixelRatio. But in truth the returned coordinates are relative to the resolution of the canvas itself, not the browser display coordinates.

**Comment by FezVrasta** [comment]
So is this expected? Is there any method to convert them to browser coordinates?

**Comment by jourdain** [comment]
Not right now, but we could add one on the view object since it has its DOM container and the knowledge of the width/height of the canvas, so we could easily rescale to the browser "units" even when things get stretch with improper ratio.

Feel free to add a PR on that which would add a `worldToBrowserCoordinate` (or something that make more sense) method to `openglRenderWindow` and the webgpu one. Maybe have a generic one that is static on vtkRenderWindow which takes all the args which get called from the opengl and webgpu class definition.

**Comment by finetjul** [comment]
I got a quick fix (a revert) but there is still x2 ratio that I haven't had a chance to look at. (`2` happened to be the value of my `window.devicePixelRatio`, this is why I first thought I had to multiply it with)

I wonder if [those lines](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L221-L223) are faulty.
I would be good to unit test `getPixelWorldHeightAtCoord()`... I probably won't have time to further investigate today though.

**Comment by jourdain** [comment]
I don't think this is related to widgets. Widgets needs to have a path forward on that topic but the usage described here is with `react-vtk-js` picking information. And the fact that worldToDisplay does not provide what users tend to think it should be. See [that bug](https://github.com/Kitware/vtk-js/issues/1246) on that topic too.

**Comment by finetjul** [comment]
@FezVrasta are you in parallel projection by any chance ? does it work in perspective projection ?

**Comment by FezVrasta** [comment]
I'm in parallel projection, I'll see if I can test it without it but I can't make any promise.

**Comment by finetjul** [comment]
@jourdain I agree, `worldToDisplay` is not related to widgets. It seems however that it is somehow related.

With my new [test](https://github.com/Kitware/vtk-js/pull/2030/commits/2945fcd21247d048937b2bcaa8fff0aa1973d420), we can see that there is a missing x2 ratio in parallel projection. For the `testScaleInPixelsWithParallelProjection` test, the sphere handle should take the entire height (300px) of the view but it takes only half (150px). This is not sensitive to `window.devicePixelRatio`

@martinken @floryst can you doube check [those lines](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L221-L223) ? are you sure there is not an x2 missing for the parallel projection ?

**Comment by jourdain** [comment]
Ok, but anyhow we should have a method that convert Display/Canvas coordinate to Browser based on how stretched that canvas is vs the space used in the browser outside of devicePixelRatio even if the devicePixelRatio is the main reason of that stretch.

**Comment by finetjul** [comment]
@FezVrasta can you check if #2030 fixes your issue ?
