### ISSUE TITLE
Is there any connection between 2D multi-planar reconstruction and computer graphics card?

### ISSUE THREAD

**Issue by itsRaul** [Kitware/vtk-js#2033]
### High-level description
Hello, Use vtkjs to develop two-dimensional multi-planar reconstruction. There are image blurring and stuck in individual computer equipment. Is the final effect of vtkjs related to the computer's graphics card?

### Environment
- **vtk.js**: 11.1.3 
- **OS**:  Windows 10
- **Browser**:  Chrome  92.0.4515.131

**Comment by finetjul** [comment]
It depends of the VTK.js class you are using, can you please describe what are all the VTK.js classes you are using in your code ?

**Comment by itsRaul** [comment]
> It depends of the VTK.js class you are using, can you please describe what are all the VTK.js classes you are using in your code ?

MatrixBuilder

**Comment by itsRaul** [comment]
> It depends of the VTK.js class you are using, can you please describe what are all the VTK.js classes you are using in your code ?

- vtk.js/Sources/Common/Core/MatrixBuilder
- vtk.js/Sources/Rendering/Core/Volume
- vtk.js/Sources/Rendering/Core/VolumeMapper
- vtk.js/Sources/Rendering/Misc/GenericRenderWindow

**Comment by finetjul** [comment]
vtk.js/Sources/Rendering/Core/VolumeMapper is relying on GPU.

For the same setup, do you have different output rendering ? Can you share screenshots ?

**Comment by itsRaul** [comment]
> vtk.js/Sources/Rendering/Core/VolumeMapper is relying on GPU.
> 
> For the same setup, do you have different output rendering ? Can you share screenshots ?

**Comment by itsRaul** [comment]
> vtk.js/Sources/Rendering/Core/VolumeMapper is relying on GPU.
> 
> For the same setup, do you have different output rendering ? Can you share screenshots ?

![1628494306368](https://user-images.githubusercontent.com/32694558/128673283-599f7453-30d5-4ff9-83f8-0f449cd1d396.png)
![16284942776448](https://user-images.githubusercontent.com/32694558/128673290-108ecd32-a34e-4cee-9fb5-15a7e315a84f.png)

**Comment by finetjul** [comment]
It looks like the issue is more due to the "resolution". Do you have different values for `window.devicePixelRatio` in each case ?

**Comment by itsRaul** [comment]
> It looks like the issue is more due to the "resolution". Do you have different values for `window.devicePixelRatio` in each case ?
> 
> (btw, please do not "Close" the issue if it is not resolved.)

I have found the answer. Chrome browser settings use the hardware acceleration mode setting, and the computer equipment appears fuzzy only because this setting is turned off

**Comment by itsRaul** [comment]
Thank you very much for letting me find a solution to the GPU. Open Chrome to use the hardware acceleration mode setting, some computers still have the problem of image lines. Turn off Chrome to use the hardware acceleration mode setting, the image lines, blur, and will definitely appear. Is there any API for optimizing hardware acceleration?
