### ISSUE TITLE
SetScaleFactor in SphereMapper

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2036]
### Need
I'm Currently using `vtkSphereMapper` by setting a point scalar array (`setScaleArray()`). 

However, once that's set, one can no longer interact with how big are or small is the scale therefore, there is no way to change the equivalent of `setScaleFactor()` function available in `vtkGlyph3DMapper`.

It would be nice to have the possibility to easily set a scaleFactor.

### Feature
```
const actor = vtkActor.newInstance()
const mapper = vtkSphereMapper.newInstance()
.
.
.
mapper.setScaleArray('scale')
// Can be eventually available in the vtkSphereMapper class
mapper.setScaleFactor(30)
```

**Comment by finetjul** [comment]
Have you tried to play with `radius` instead ?

**Comment by zbouslikhin** [comment]
I did try. 

After `setScaleArray`, change the radius doesn't have any impact on the spheres.
However without `setScaleArray`, changing the radius works as expected.

**Comment by finetjul** [comment]
I see...

It is not on our roadmap to further improve such mapper. Feel free to submit a pull request though. Alternatively, if you have some funding, we can still add such feature for you.
