### ISSUE TITLE
vtkClosedPolyLineToSurfaceFilter throws error every time module: filters type: bug

### ISSUE THREAD

**Issue by Nikhil216** [Kitware/vtk-js#2044]
Recently got to use the vtkClosedPolyLineToSurfaceFilter. My code essentially looks like this.

```js
    const actor2 = vtkActor.newInstance();
    const mapper2 = vtkMapper.newInstance();
    const plane = vtkPlane.newInstance({origin:[0, 0, 0.7366], normal: [0, 0, 1]});
    const cutter = vtkCutter.newInstance();
    const surf = vtkClosedPolyLineToSurfaceFilter.newInstance();
    cutter.setCutFunction(plane);
    // tankSource is vtkAppendPolyData, with PolyData from three STL files
    cutter.setInputConnection(tankSource.getOutputPort());
    surf.setInputConnection(cutter.getOutputPort());
    mapper2.setInputConnection(surf.getOutputPort());
    actor2.setMapper(mapper2);
```
It would throw this error everytime.

![polylinefilter bug](https://user-images.githubusercontent.com/61278405/129699345-96fc1b18-c0c2-48ed-805b-a08ac8cec7b4.png)

Upon looking into the index.js file for ClosedPolyLineToSurfaceFilter, I noticed this line which appeared in the stack trace.

https://github.com/Kitware/vtk-js/blob/7254994f0e13bc16b35b59308aa58a3a4a0a3b3f/Sources/Filters/General/ClosedPolyLineToSurfaceFilter/index.js#L129

![stack trace for the bug](https://user-images.githubusercontent.com/61278405/129699306-ccbbe5e7-fa34-43f0-872c-792c4866a354.png)

Shouldn't this line be after the check for ```if (!input)```.
```js
  publicAPI.requestData = (inData, outData) => {
    // implement requestData
    const input = inData[0];
    const output = vtkPolyData.newInstance();
    output.shallowCopy(input);

    if (!input) {
      vtkErrorMacro('Invalid or missing input');
      return;
    }
```

**Comment by jourdain** [comment]
Yes I would think so too.

**Comment by Nikhil216** [comment]
Also this filter didn't work on a STL file. I used this filter with ```vtkCutter``` but it couldn't close the poly line so the render scene would lag out with this error in the console.

![segment Aggregator error](https://user-images.githubusercontent.com/61278405/129779682-2a0ea0b3-1346-43c4-b32f-dee1d1e56dbe.png)

getting console.log of the class SegmentAgregator props would look like this

![bugged-CPL2SF](https://user-images.githubusercontent.com/61278405/129779906-53dc9b54-4706-4ba5-be8f-5d0ced96d947.png)
Here the objects logged are 1) lineSegment, 2) this.segments 3) this.segmentMapping

The ```this.segmentMapping``` stores all the head and tail values of the segment in ```this.segments``` like ```{ pointIdx: segmentIdx }```. The sign on ```segmentIdx``` depends whether it is the head or tail. But in the console.log you can see the segmentMapping be ```{0: undefined, 1: 1, 2: 1}``` instead of ```{0: undefined, 1: 1, 2:  -1}```

So I changed these lines
https://github.com/Kitware/vtk-js/blob/7254994f0e13bc16b35b59308aa58a3a4a0a3b3f/Sources/Filters/General/ClosedPolyLineToSurfaceFilter/index.js#L75
https://github.com/Kitware/vtk-js/blob/7254994f0e13bc16b35b59308aa58a3a4a0a3b3f/Sources/Filters/General/ClosedPolyLineToSurfaceFilter/index.js#L97
to
```js
this.segmentMapping[last] = mappingFirst;
```
```js
this.segmentMapping[first] = mappingLast;
```
by removing the minus signs (fliping the sign here would mean changing a head to a tail which is not what we want)

Now it renders the cut plane correctly
![test-CPL2SF](https://user-images.githubusercontent.com/61278405/129782129-19ae97b9-e32e-454e-8cb5-bf35301d34c7.png)

**Comment by finetjul** [comment]
Would you mind creating a pull request with your 2 fixes ?
