### ISSUE TITLE
VTK file support

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/vtk-js#205]
Will there be support for other vtk files such as `.vtu`, `.vtp` or `.vtm`?

**Comment by jourdain** [comment]
Eventually but not in the short term. We did not spend any time on the parsing of such a files.
So far we relied on converting the data to allow easy ingestion in JavaScript while keeping the structure and concept of those data structures.

**Comment by doczoidberg** [comment]
there is a [python export script](https://raw.githubusercontent.com/Kitware/vtk-js/master/Utilities/ParaView/export-scene-macro.py). is it possible to write time steps with it and manipulate e.g. color data on exported data or does it only export 'static data'?

**Comment by jourdain** [comment]
This script only manage static scene but we've integrated a viewer in [ArcticViewer](https://github.com/Kitware/arctic-viewer/blob/master/scripts/examples/paraview/samples/VTKGeometry-can.py) which allow to capture time and various data fields.

**Comment by jourdain** [comment]
Forget to link the [viewer](https://github.com/Kitware/arctic-viewer/blob/master/lib/types/VTKGeometry.js)

**Comment by martinken** [comment]
@jourdain should this be closed now?

**Comment by jourdain** [comment]
We currently support vtp / vti
