### ISSUE TITLE
Integrate new data for test

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#207]
I'm writting a test for createCubeFromRaw and I need to use 6 image data to create a skybox. For my own test, I put the files into Data folder and it worked well but I saw that this folder is on the .gitignore and I can't push it into vtkjs.
I tried to move it into my test folder but without success. Files are not found.

- OK : `const path = ``${__BASE_PATH__}/Data/skybox/mountains/``;`
- Not OK :  `const path = ``${__BASE_PATH__}/Sources/Rendering/OpenGL/Texture/test/skybox/mountains/px.vti``;` 

Where can I put the files in order to push it into vtkjs ?

**Comment by jourdain** [comment]
You need to put your test data in the `/Data` directory. You will just need to add your file with the `-f` argument for git.

Moreover, the path used for your test should be `${__BASE_PATH__}/data/...` not `.../Data/...`

**Comment by laurennlam** [comment]
@jourdain Thanks for the precision.
I just test with `.../data/...` and it doesn't work. But it works well with `.../Data/...`
My collegue, @luciemac had the same problem when she created her test for shaderReplacement. Do you have any idea why it doesn't work with us ?

**Comment by jourdain** [comment]
Hum, that's because I was thinking of `examples` not test. I think I did not created a proxy for the tests. So stick with `.../Data/...` for now. ;-)

**Comment by laurennlam** [comment]
Ok ! Thank you @jourdain !
