### ISSUE TITLE
Rendering of multiple volumes not sorted correctly

### ISSUE THREAD

**Issue by silentbat** [Kitware/vtk-js#2086]
When rendering two volumes, they are not sorted correctly, as described in #473 , the volume inserted last overdraws the first regardless of viewing angle.

My idea currently is: Either culling/sorting doesn't work at all with multiple volumes currently or maybe the issue in this case is that both volumes are inserted in the same space (origins are equal) and only the voxel data sets them apart?

Code:
```js
const renderWindow = vtkFullScreenRenderWindow.newInstance({ rootContainer: container, });
const httpReader = vtkHttpDataSetReader.newInstance();
const mapper = vtkVolumeMapper.newInstance();
const actor = vtkVolume.newInstance();

httpReader.setUrl(url1)
    .then(() => httpReader.loadData())
    .then(() => {
        mapper.setInputConnection(httpReader.getOutputPort());
        actor.setMapper(mapper);
        renderWindow.getRenderer().addVolume(actor);
        renderWindow.getRenderer().resetCamera();
        renderWindow.getRenderWindow().render();
    });

const mapper2 = vtkVolumeMapper.newInstance();
const actor2 = vtkVolume.newInstance();

const httpReader2 = vtkHttpDataSetReader.newInstance();
httpReader2.setUrl(url2)
    .then(() => httpReader2.loadData())
    .then(() => {
        mapper2.setInputConnection(httpReader2.getOutputPort());
        actor2.setMapper(mapper2);
        renderWindow.getRenderer().addVolume(actor2);
        renderWindow.getRenderer().resetCamera();
        renderWindow.getRenderWindow().render();
    });
```

correct:
![image](https://user-images.githubusercontent.com/34458627/135820993-cbf4ce3a-4407-446e-bd22-83e33f9d3d3c.png)

incorrect:
![image](https://user-images.githubusercontent.com/34458627/135821085-d733a046-230b-4f70-9eea-6ad260f9aeea.png)

expected behaviour would be correct perspective rendering of the cube being in front rendering after / on top of the cube being in the back.

### Environment
- **vtk.js**: 19.5.1
- **OS**: Windows 10
- **Browser**: Chrome 94.0.4606.61

**Comment by jourdain** [comment]
I think the idea was to have it implemented in WebGPU. Any comment, status @martinken ?

**Comment by martinken** [comment]
The webgpu support is still limited and experimental, but intermixed volume rendering is supported and working. I have tested it out and it seems to work well on chrome canary on windows at least. You just set them all up as usual and the WebGPU backend just handles it automatically. They can have different tfuns, etc. Note shading and multicomponent volumes are not supported right now, just haven't gotten to it. 

Also I'll probably tweak the intermixing of MIP and composite a bit. Right now it blends MIP/Average/etc on top of composite but I may try to do something more complex in the future. Depth based pixel by pixel mixing of MIP and composite looked horrible (I had it coded that way originally) as the depth of a MIP is a mess. I thought it might look cool, nope, just doesn't make sense. But the MIP on top of composite looks pretty good and works.

**Comment by silentbat** [comment]
Thank you guys for the fast answer!
So there is no way currently to get this working without chrome canary right?

What I am trying to do is have cubes with different spacial resolution that's why I am not rendering one big cube...

I could get it to render the cubes shown in the screenshots correctly in canary as you guys suggested 👍
Hopefully composite rendering between adjacent cubes will work as well :)

**Comment by silentbat** [comment]
Hey again, back with new knowledge:

I took a 256^3 uint16 Volume as vti input (through vtkHttpDataSetReader as in the original code), but split it up in 64 subvolumes, each rendered seperately (so one can choose which ones to render).
This way we have 64 actors/mappers all waiting to load data (vtkHttpDataSetReader.loadData).

Loading is then activated by some interaction, when more than ~3 Volumes load, I get the following error and a white screen:

```
The number of sampled textures exceeds the maximum per-stage limit.
 - While calling CreateBindGroupLayout([BindGroupLayoutDescriptor]).
```

This is the case in Chrome Canary 96.0.4662.1, on normal Chrome  94.0.4606.71 there is no such problem, but as stated initially the rendering order is of course still wrong.

loading initially works (boxes marked green are expected to load next):

![image](https://user-images.githubusercontent.com/34458627/136225707-20ab2829-6a12-4ce3-9c51-a6e885b182c3.png)

**Comment by silentbat** [comment]
Sorry for taking so long - of course you are right, this should be a different issue!
Thank you for explaning the problems regarding the new problem 👍

**Comment by martinken** [comment]
I think on the webgpu front the sorting of many volumes should work now.
