### ISSUE TITLE
Document 'vtkScalarBarActor'

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2087]
### Need
I am currently trying to implement a color bar using the 'vtkScalarBarActor' class. However, I could not find any documentation on how to use anywhere.

### Feature
- A small code pen with ground basics,
- Documentation on how to use it.

**Comment by zbouslikhin** [comment]
After digging deeper, I ended up on an [example](https://kitware.github.io/vtk-js/examples/GeometryViewer.html), which uses scalarBarActor.
Furthermore, is it possible to change the position/orientation of the bar + the size of the title?

**Comment by martinken** [comment]
setAutoLayout allows you to override the default autolayout function with your own function.  So it takes a function. 

setAutomated determines if autolayout is used or not. It defaults to true.

By providing your own function you can control all of the settings/computation.

By default if whatever is providing coloring can have a NaN color then it gets displayed.

You could add an option in the class to suppress the NaN color pretty easily though.

**Comment by zbouslikhin** [comment]
@martinken Many thanks for the explanation.

I tried to pass an autolayout function in the same fashion it's done [in here](https://github.com/Kitware/vtk-js/blob/b617e02a7d09c5044f559b28e0bb4c67dad3b639/Sources/Rendering/Core/ScalarBarActor/index.js#L52), but no success.
How would it look like to change for example the box size?

**Comment by martinken** [comment]
Maybe post what you tried in a sandbox and I'll try taking a look at it.

**Comment by daker** [comment]
@zbouslikhin i have submitted a typescript definition file but without an example, feel free to ropen this one
