### ISSUE TITLE
glTF support

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/vtk-js#210]
Not sure if it makes sense for vtk.js but please consider the use of glTF:

https://en.wikipedia.org/wiki/GlTF
https://www.khronos.org/gltf
https://github.com/KhronosGroup/glTF

it should help to load and process 3d data faster

**Comment by jourdain** [comment]
https://github.com/google/draco could have better benefits. But the data model we would be looking at, would only be vtkPolyData / vtkImageData and maybe vtkUnstructuredGrid.

**Comment by haehn** [comment]
Hi @jourdain do you have plans yet to support glTF / Draco in VTK.js? There is a lot of momentum and it could be very useful.

**Comment by jourdain** [comment]
I think glTF will happen sooner than Draco but I hope both should happen within the next year.

**Comment by daker** [comment]
@jourdain i am giving the gltf loader a shot, i am facing an issue where loading a colored cube gives me this result, any idea?

https://filebin.net/m9z7aii9nkytvgf5/screen-capture.webm?t=d6qksflt

**Comment by finetjul** [comment]
Sorry, I won't help here concerning GLTF (besides mentionning that faces/cells do not seem to be made of the right point ids, could it be an issue when packing the arrays?), I'm just mentionning that draco is now supported in vtk.js
