### ISSUE TITLE
Lighted Volume Rendering test fails

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#2101]
### High-level description

`Rendering/OpenGL/VolumeMapper/test/testLighting` test fails with pixelmatch threshold of 0.

### Steps to reproduce

1. set testUtils.js pixelmatch threshold to 0
2. run npm test

### Detailed behavior
![image](https://user-images.githubusercontent.com/1812167/136421733-305aab31-9726-499b-a42c-1c9db303f3e7.png)

### Environment
- **vtk.js**: v19.7.2

**Comment by floryst** [comment]
@jadh4v , with @martinken as backup if needed

**Comment by jadh4v** [comment]
There was a change in lighting computations in the volume rendering shader. The code was changed from using pre-computed gradients, to computing gradients on-the-fly. The generated test image changes after this commit on May 28 2019:
https://github.com/jadh4v/vtk-js/commits/874ac0e0dd41bfa670b69c15cddbdedda343f64b

### Test image comparison before commit:
<img width="1720" alt="lightingtest_before_commit" src="https://user-images.githubusercontent.com/22624785/139942054-d9cda06b-b6f9-4fab-bc5f-388326cfe6fc.png">

### Test image comparison after commit:
<img width="1720" alt="lightingtest_after_commit" src="https://user-images.githubusercontent.com/22624785/139942106-b191d8ab-4d66-4435-9a53-0f47d0dc36a7.png">

**Comment by martinken** [comment]
So which is correct ? :-)  I looked at the code changes and I cannot see an issue with either of them. They are different approaches though as the old code normalized the gradients first, then interpolates them. The new code trilinearlly samples to compute the values then computes a normalized gradient from the result. As such I'm pretty sure the new code is more correct as the normalization step in the precomputation makes small gradients next to big gradient have equal impact which is not correct and is correctly handled in the current approach. So long story short I think the new image is correct unless someone sees something I'm missing.

**Comment by jadh4v** [comment]
The new approach should be more accurate in estimating the local gradients, though it skips taking equal steps in both directions (which introduces a slight offset in the positive axis direction). As you pointed out, "first normalization then interpolation" in the previous approach: the magnitude of normals will often be less than one which adds an extra darkening effect to the shading (I am guessing).

**Comment by jadh4v** [comment]
[here](https://github.com/Kitware/vtk-js/blob/44bbf1afd4eee009695f8ceff80debfed7fc6d3d/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L295): `  result.x = getTextureValue(pos + vec3(tstep.x, 0.0, 0.0)).a - scalar;`
Since we are doing `currentPosition + step.x` would it be better to have a step size smaller than half of voxel spacing? I am thinking `1/5` of spacing, or it could be half of `sampleDistanceIS`. Currently it appears to be 1 voxel spacing, which is quite large. Ideally we don't want to step outside the current cell, though we cannot avoid that for samples closer to the boundary of the cell.

**Comment by martinken** [comment]
Using 1/2 or 1/5 is fine I think. Just make the matching adjustment where we divide by spacing to keep it all consistent.

**Comment by martinken** [comment]
I lied. The spacing has to be at least one voxel I think because we support nearest neighbor sampling in volume rendering. Anything smaller than one voxel differences will result in no normals.

**Comment by jadh4v** [comment]
We could do a test for `#ifdef vtkTriliearOn` to decide what step size to use.

**Comment by martinken** [comment]
Sure that would be fine

**Comment by jadh4v** [comment]
@floryst @martinken Seems like jitter is causing the test to fail even when I changed the baseline. With a threshold of zero, I get an error of around 5% (changes every execution). Currently there isn't any mechanism to turn off jitter.

**Comment by floryst** [comment]
I'll look into this lighting test while I work on the image testing infra.
