### ISSUE TITLE
Selectively running tests

### ISSUE THREAD

**Issue by ebrahimebrahim** [Kitware/vtk-js#2110]
### Need

When a developer is working on addressing the failure of a test, they want some convenient way to run that specific test. Running all tests repeatedly takes too long.

### Feature

It should be possible to run a particular test (maybe also a particular set of tests) by specifying it in the command line.

Currently we run tests with the command
```
npm run test
```
which runs karma.

We can disable tests by commenting out lines in `Sources/tests.js`.
This process should be made more convenient, perhaps by allowing a command like

```
npm run test <name of a specific test>
```

Difficulty: karma does not have test-selection as a built in feature. It offloads that responsibility to the "testing framework" that uses it.

**Comment by floryst** [comment]
Here is an alternative: identify the specific test, and switch to using `test.only`. This will run only that test. This might be better since you typically only focus on a single failing test at a time.

```diff
-test('test description here', (t) => ...
-test.only('test description here', (t) => ...
```

**Comment by ebrahimebrahim** [comment]
More convenient than commenting out a bunch of lines. Also nice that you don't have to touch `Sources/tests.js` while iterating on a specific test.

**Comment by floryst** [comment]
I've added docs on using `test.only`, so I'm considering this solved. The specific docs can be found here: https://kitware.github.io/vtk-js/docs/develop_test.html#Running-a-single-test-for-debugging
