### ISSUE TITLE
Allow arbitrary number of clipping planes in PolyDataMapper

### ISSUE THREAD

**Issue by ebrahimebrahim** [Kitware/vtk-js#2134]
Currently only up to 6 clipping planes can be added to [PolyDataMapper](https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/OpenGL/PolyDataMapper). This is because the number has to be [hard-coded](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/PolyDataMapper/index.js#L878) into the fragment shader.

We can make that number arbitrary by rebuilding the shader every time it changes. For example, the volume mapper's clipping plane loop count [is set based on the number of clipping planes](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L316).

This issue should be assigned to me.

**Comment by daker** [comment]
@ebrahimebrahim it should be released, right?

**Comment by ebrahimebrahim** [comment]
> @ebrahimebrahim it should be released, right?

That's right, closing, thank you
