### ISSUE TITLE
vtkForwardPass not exposed in public API

### ISSUE THREAD

**Issue by casra-developers** [Kitware/vtk-js#2139]
### High-level description
In the current version of vtk.js the render pass vtkForwardPass is no longer available. Looking through the source-code it is still present but it is never imported in: ./Sources/Rendering/OpenGL/index.js

### Steps to reproduce
This issue can be triggered when trying to instantiate a new vtkForwardPass (e.g. for a rendering pipeline):
```
const forwardPass = vtk.Rendering.OpenGL.vtkForwardPass.newInstance();
```

### Detailed behavior
Since the vtkForwardPass is not exposed, an error is raised:
```
ERROR TypeError: Cannot read properties of undefined (reading 'newInstance')
```

### Expected behavior
A vtkForwardPass should be generated which can then be used for setting up a custom render-pipeline.

### Environment
- **vtk.js**: 20.2.0
- **OS**: Windows 10
- **Browser**: Chrome 94.0.4606.81

**Comment by casra-developers** [comment]
An update from my side: I have been doing experiments on my own to see if there are workarounds for this problem (besides just building the module for myself and replacing vtk.js). Using the @kirware/vtk.js module requires to add the line:
```javascript
import '@kitware/vtk.js//IO/Core/DataAccessHelper/HttpDataAccessHelper';
```
To enable loading gz-compressed volume data. But when doing it like this, nothing happens (just index.json gets retrieved as can be seen when looking into the network traffic). Using vtk.js/Sources also does not work and additionally it does not even compile since there seems to be an issue with the return types in Rendering/OpenGL/RenderWindow/index.d.ts. Re-writing the backend to decompress the volume before serving it also did not yield any positive results.

The test projects are all ASP.NET Core 3.1 with Angular (8 and 12) and the only way I had any success so far was with using the pre-built version when I rebuilt it myself with the vtkForwardPass set public. I also invested time in trying out other render pass objects which where exposed (e.g. Rendering/ScreenGraph/RenderPass) but they did not work either.

So I am not sure if the test projects with Angular are interfering here, but since our main projects are based on it, I really do not have any choice in choosing an alternative which might work better together with vtk.js.

**Comment by jourdain** [comment]
What is the issue when using the ESM build?
- TS definition prevent you from using it? Or it is just a warning and you can pass that?
- No rendering? Did you load the profile?
- Something else?

**Comment by casra-developers** [comment]
It is actually the TS which does prevent me from using it (in vtk.js/Rendering/OpenGL/RenderWindow/index.d.ts)

```typescript
displayToLocalDisplay(x : any, y : any, z : any): VtkOpenGLRenderWindow0;
```
The type "VtkOpenGLRenderWindow0" is not recognized. However, when replacing it with "any" it works as far as I do not get any errors. After that I am stuck with the "vtkHttpDataSetReader" not fetching the payload (or not rendering it). What do you mean with "Did you load the profile?". The only thing I can say with certainty is that the prebuilt version works as intended.
I'll gladly provide any information I can if I get directions on where to extract those. With that said, I already spent way more time on this than I should so I cannot promise that I can react quickly.

For us, the best case would still be to make the vtkForwardPass public in the prebuilt version.

**Comment by jourdain** [comment]
The prebuilt version load the all the rendering profiles. When using ESM, you can choose what you want to load to enable tree shaking so you don't need to have the SurfaceLIC (+300KB) if you are not planning to use it. 
 
The same way as the `HttpDataAccessHelper`, you need to import the rendering part.

```javascript
// Load the rendering pieces we want to use (for both WebGL and WebGPU)
import '@kitware/vtk.js/Rendering/Profiles/All';
// import '@kitware/vtk.js/Rendering/OpenGL/Profiles/Geometry'; // < just for geometry for webgl
```

**Comment by casra-developers** [comment]
Awesome! This works, thank you very much :)
Sorry since we always used the pre-built version in our projects none of us knew about the profiles (should have read the docs more carefully). This actually provides a way to work with vtkForwardPass without having to rebuild the package ourselves. The question now remains as you stated @jourdain, whether you want to add something to the public API which can be used instead of the vtkForwardPass in order for the vtkConvolution2DPass to work with the pre-built version as well.

**Comment by jourdain** [comment]
Great, the ESM build is indeed the way to go. The UMD pre-built version should only be used for conveniency and quick tests.

**Comment by casra-developers** [comment]
So in that case and especially since in the ESM version the vtkForwardPass is already available, it could be made public I assume.

**Comment by floryst** [comment]
The UMD build provides a more explicit boundary of what is considered public API vs private API. The manner by which vtk.js is consumed in ES module projects site-steps this boundary, and acts as an escape hatch for private class access. 

If it makes sense, we can have vtkForwardPass made available. However, it is not clear to me from the existing discussion that this is the case.

**Comment by jourdain** [comment]
Until we have a "generic" access to it, we should expose it in our UMD bundle.
