### ISSUE TITLE
vtkjs not showing anything anymore (with vue)

### ISSUE THREAD

**Issue by nattyluke** [Kitware/vtk-js#2151]
## Vtk.js not showing anything anymore (with vue)
Hello,
I use vtkjs at my company, we started a project one year ago, it worked well. Now I dont see anything anymore and I dont know what to do anymore.

### Steps to reproduce
I created  a new vue2 testproject with vue console ( vue create vtk-test ) and installed vue, and of course vtkjs.

 My mounted method looks like this (of course I load all used vtk modules)
```js

  mounted() {        
    const fullScreenRenderWindow = vtkFullScreenRenderWindow.newInstance({
            // rootContainer: this.$refs.render as HTMLElement,
            background: [0, 0, 0], // set to black
    });
    // fullScreenRenderWindow.set
    const renderWindow = fullScreenRenderWindow.getRenderWindow();
    const renderer = fullScreenRenderWindow.getRenderer();

    const coneSource = vtkConeSource.newInstance({ height: 1.0 });

    const mapper = vtkMapper.newInstance();
    mapper.setInputConnection(coneSource.getOutputPort());

    const actor = vtkActor.newInstance();
    actor.setMapper(mapper);

    renderer.addActor(actor);
    renderer.resetCamera();
    renderWindow.render();
  },
```
I tried to create an easy example from https://kitware.github.io/vtk-js/docs/vtk_vue.html and
https://kitware.github.io/vtk-js/examples/SimpleCone.html

### Detailed behavior
Nothing is shown.I just see a white 100% width and height canvas (which should be black) and no cone showing up too.
No errors too. 

### Expected behavior
I should see a cone. 

### Environment
- **vtk.js**:20

**Comment by jourdain** [comment]
You need to load a rendering profile. See [BREAKING_CHANGES](https://github.com/Kitware/vtk-js/blob/master/BREAKING_CHANGES.md#from-17x-to-18) for reference.

**Comment by nattyluke** [comment]
omg thank you its working again...
