### ISSUE TITLE
The shape widget has some bugs

### ISSUE THREAD

**Issue by Zhengyangzuishuai** [Kitware/vtk-js#2170]
I try to implement the function of drawing a circle, but in the process of implementation, I found some problems.
1. When I draw multiple circles in the view, the handles only appear in the last circle
![image](https://user-images.githubusercontent.com/43663302/142567654-a61093af-4706-4897-8ec5-5c7299691789.png)

2. When I move the mouse between different views, the movehandle cannot be moved to other views. During debugging, I found that it cannot trigger the getInteractor().onMouseMove() of different views like the distance widget. In addition, movehandle will disappear when the mouse is scrolled.

**Comment by finetjul** [comment]
For 1), you might want to look at the [Shape Widget example](https://kitware.github.io/vtk-js/examples/ShapeWidget.html).
The circle widget does not loose its handle.
The ellipse widget does loose its handle but it is for [demo purpose](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/ShapeWidget/example/index.js#L343-L348).

For 2) can you please share a screencast that shows the problem
