### ISSUE TITLE
MouseBoxSelectorManipulator frame gets rendered to wrong position

### ISSUE THREAD

**Issue by ahojukka5** [Kitware/vtk-js#2177]
### High-level description

It looks that MouseBoxSelectorManipulator "red rectangle" is calculated wrong if surrounding container is having margins.

### Steps to reproduce

Here's the code to reproduce this problem. If margin is set to 0 px, everything works as expected.

```html
<!DOCTYPE html>
<html>

<body>
  <div id="container" style="margin: 100px; width: 500px; height: 500px"></div>

  <script type="module">
    import "https://cdn.skypack.dev/@kitware/vtk.js";

    const { vtkFullScreenRenderWindow } = vtk.Rendering.Misc;
    const { vtkXMLPolyDataReader } = vtk.IO.XML;
    const { vtkActor, vtkMapper } = vtk.Rendering.Core;
    const { vtkInteractorStyleManipulator } = vtk.Interaction.Style;
    const { Manipulators } = vtk.Interaction;

    const container = document.getElementById("container")

    // ----------------------------------------------------------------------------
    // Standard rendering code setup
    // ----------------------------------------------------------------------------

    const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({ container });
    const renderWindow = fullScreenRenderer.getRenderWindow();

    // ----------------------------------------------------------------------------
    // Example code
    // ----------------------------------------------------------------------------

    const boxSelector = Manipulators.vtkMouseBoxSelectorManipulator.newInstance({
      button: 1,
    });
    boxSelector.onBoxSelectChange(({ selection }) => {
      console.log('Apply selection:', selection.join(', '));
    });
    // boxSelector.onBoxSelectInput(console.log);

    const iStyle = vtkInteractorStyleManipulator.newInstance();
    iStyle.addMouseManipulator(boxSelector);
    renderWindow.getInteractor().setInteractorStyle(iStyle);
  </script>

</body>

</html>
```

**Comment by jourdain** [comment]
That is a good point, but if you create an extra container with the padding you needs, you should be all-set as long as the vtk one does not have margin or padding?

**Comment by ahojukka5** [comment]
Unfortunately it looks that it's not solving the problem. So this is also failing:

``´html
<!DOCTYPE html>
<html>

<body>
  <div id="wrap" style="margin: 100px">
    <div id="container" style="width: 500px; height: 500px; margin: 0px; padding: 0px">
    </div>
  </div>

  <script type="module">
    import "https://cdn.skypack.dev/@kitware/vtk.js";

    const { vtkFullScreenRenderWindow } = vtk.Rendering.Misc;
    const { vtkXMLPolyDataReader } = vtk.IO.XML;
    const { vtkActor, vtkMapper } = vtk.Rendering.Core;
    const { vtkInteractorStyleManipulator } = vtk.Interaction.Style;
    const { Manipulators } = vtk.Interaction;

    const container = document.getElementById("container")

    // ----------------------------------------------------------------------------
    // Standard rendering code setup
    // ----------------------------------------------------------------------------

    const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({ container });
    const renderWindow = fullScreenRenderer.getRenderWindow();

    // ----------------------------------------------------------------------------
    // Example code
    // ----------------------------------------------------------------------------

    const boxSelector = Manipulators.vtkMouseBoxSelectorManipulator.newInstance({
      button: 1,
    });
    boxSelector.onBoxSelectChange(({ selection }) => {
      console.log('Apply selection:', selection.join(', '));
    });
    // boxSelector.onBoxSelectInput(console.log);

    const iStyle = vtkInteractorStyleManipulator.newInstance();
    iStyle.addMouseManipulator(boxSelector);
    renderWindow.getInteractor().setInteractorStyle(iStyle);
  </script>

</body>

</html>
```

**Comment by jourdain** [comment]
I think the issue is that the container was not set with a `position: relative;` which was the assumption when those computation are done.
