### ISSUE TITLE
LiteHttpDataAccessHelper 

### ISSUE THREAD

**Issue by sumilying** [Kitware/vtk-js#2185]
when use the  HttpDataSetReader to load file ,this erreor happened

### Expected behavior
 LiteHttpDataAccessHelper does not support compression. Need to register HttpDataAccessHelper instead.
Uncaught (in promise) Error: LiteHttpDataAccessHelper does not support compression. Need to register HttpDataAccessHelper instead.

### Environment
- **vtk.js**: 
- **OS**: 
- **Browser**:

**Comment by jourdain** [comment]
To enable zip compression you need to explicitly import the following line. 
Otherwise you get a light weight version which allow a much smaller bundle.

```
import 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';
```

**Comment by sumilying** [comment]
maybe can do this to ensure types support,or choose the one you need :
    import 'vtk.js/Sources/IO/Core/DataAccessHelper/HtmlDataAccessHelper';
    import 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';
    import 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';

**Comment by sumilying** [comment]
> To enable zip compression you need to explicitly import the following line. Otherwise you get a light weight version which allow a much smaller bundle.
> 
> ```
> import 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';
> ```

thanks so much.

**Comment by jourdain** [comment]
> maybe can do this to ensure types support,or choose the one you need : import 'vtk.js/Sources/IO/Core/DataAccessHelper/HtmlDataAccessHelper'; import 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper'; import 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';

I'm not sure to get what you are trying to say here. But if you need them, then yes.
