### ISSUE TITLE
PaintWidget handle is rendering behind the imageLayer when both use the same renderer.

### ISSUE THREAD

**Issue by Guzzler** [Kitware/vtk-js#2188]
### High-level description
PaintWidget handle appears behind the current selected slice even though the origin matches.

### Detailed behavior
As seen in the image below, the preview is being cut off as soon as it overlaps the image and seemingly goes behind it.
![paintWidgetbehind-ss](https://user-images.githubusercontent.com/12707741/144980188-47a99878-90ac-4a12-bc23-b4053c35355a.png)
### Expected behavior
The paintWidget handle and preview is expected to be above the current slice. For some reason, when the renderer is common it goes behind the image viewport.

### Extra information
This is using an MPR view and closely follows the workflow setup in react-vtkjs-viewport.

Have been fighting this for a while now and would appreciate if any insight could be provided on how to proceed with this issue and the right way to fix it.

### Environment
- **vtk.js**: 21.2.0
- **OS**:  Ubuntu
- **Browser**: Firefox/ Chrome 89.0.4389.128

**Comment by finetjul** [comment]
Have you tried playing with coincident topology parameters ?

**Comment by Guzzler** [comment]
Tried playing around with them as suggested but not really sure what specific values to put. Didn't seem to change at all when i changed them up and down.

**Comment by finetjul** [comment]
You may want to try with different volumes / orientations then... 
Make sure the plane manipulators are correctly updated...
