### ISSUE TITLE
VTK Image Mapper compute closest IJK Axis fails for this case

### ISSUE THREAD

**Issue by annehaley** [Kitware/vtk-js#2191]
### High-level description
ImageMapper x-y-z slicing has corner cases bugs. @floryst @agirault 

### Steps to reproduce
Create an image, set the direction matrix to the array pasted below, and try to slice along x, y, and z.

### Detailed behavior
![image](https://user-images.githubusercontent.com/44912689/145292856-4e6e2583-b424-4a3b-8189-cc7a7c9b8ad2.png)
The below direction matrix results in the above screenshot (ignore the crosshairs). The views should be rendering z, x, y, but are rendering two of the same slice (rotated differently) and nothing.

```
[ 0.5986634492874146, 0.22716301679611206, -0.7681139707565308, 0.5627936124801636, 0.5630670785903931, 0.6051601767539978, 0.569969654083252, -0.7945769429206848, 0.20924176275730133 ]
```

### Expected behavior
I should see three different slices (z, x, y).

### Environment
- **vtk.js**: 14.16.5 (but master should have the same issue)

**Comment by annehaley** [comment]
I am working with @floryst and @dzenanz on using this function in MIQA: https://github.com/OpenImaging/miqa/pull/236/files#:~:text=let%20newOrientation%20%3D%20%5B%5D%3B-,if%20(this.closestIJKAxis%20%3D%3D%3D%200)%20%7B,%7D,-newOrientation%20%3D%20newOrientation.map

**Comment by dzenanz** [comment]
The idea is that [`normalizedAxis` function](https://github.com/OpenImaging/miqa/blob/6185887dc82feca9702a917c5396da12af978061/client/src/components/VtkViewer.vue#L222-L270)'s logic might be adapted for vtk.js' `VolumeMapper.getClosestIJKAxis()`.

**Comment by dzenanz** [comment]
The original logic comes from [itk::SpatialOrientationAdapter](https://github.com/InsightSoftwareConsortium/ITK/blob/8801247049712d50528e4651a0d000892b7eb22a/Modules/Core/Common/src/itkSpatialOrientationAdapter.cxx#L32-L111).

**Comment by Julesdevops** [comment]
should be fixed by https://github.com/Kitware/vtk-js/commit/81504a4bb7f367bd82d5b6d15108673d36a75f6c

**Comment by floryst** [comment]
Closing as per the comment above. If this is still an issue for anyone, please submit a new issue.
