### ISSUE TITLE
VtkMath definition error

### ISSUE THREAD

**Issue by aShuaizzz** [Kitware/vtk-js#2192]
### High-level description

The matrix parameters defined are inconsistent with the actual matrix parameters used in vtkMath
### Steps to reproduce

      const mP = [
        [dP[0], 0, 0],
        [dP[1], 0, 0],
        [dP[2], 0, 0],
      ];
      const mQ = [
        [dQ[0], dQ[1], dQ[2]],
        [0, 0, 0],
        [0, 0, 0],
      ];

      const H1 = [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
      ];
      vtkMath.multiplyMatrix(mP, mQ, 3, 1, 1, 3, H1);

### Detailed behavior

![1639033540(1)](https://user-images.githubusercontent.com/45392896/145349872-8806fe0f-9548-4fea-ad4f-2c013dc8aaf4.png)
![image](https://user-images.githubusercontent.com/45392896/145349946-206d45dc-3cdd-4bc3-92c9-459a2e0869ff.png)
![image](https://user-images.githubusercontent.com/45392896/145350008-a096280c-07d0-418d-acbe-0c2da4fc95c3.png)

### Environment
- **vtk.js**: 21.2.0
- **OS**: 
- **Browser**:

**Comment by aShuaizzz** [comment]
both MAT3 and MAT4 in GL-matrix are one-dimensional arrays, but the Matrix operations in vtkMath are two-dimensional arrays, so you need to distinguish them when writing the definition file

**Comment by daker** [comment]
This can be easily fixed if you want to propose a PR https://github.com/Kitware/vtk-js/blob/master/Sources/Common/Core/Math/index.d.ts#L413-L421

**Comment by daker** [comment]
@aShuaizzz i would recommand creating a new type `Matrix3x3` & `Matrix2x2` and replace the gl-matrix types with the new one

```typescript
declare type Matrix2x2 = [Vector2, Vector2];
declare type Matrix3x3 = [Vector3, Vector3, Vector3];
```

**Comment by aShuaizzz** [comment]
@daker That's great,sometimes I need to use m* N matrices when using methods such as solveLeastSquares and would like to include those methods in the definition as well.
![企业微信截图_16391001066819](https://user-images.githubusercontent.com/45392896/145502381-50859c8c-2d11-4e70-912c-9231320d3a2e.png)
