### ISSUE TITLE
vtkSTLReader Reading binary STL file throws error.

### ISSUE THREAD

**Issue by Nikhil216** [Kitware/vtk-js#2197]
I am using `@kitware/vtk.js` in a react app. Till now I was reading text STL files. Now I am trying read binary STL files by using the following method.
```js
reader.loadData({ binary: true })
```
There is this line I want to point out, in `vtkSTLReader` method `parseAsArrayBuffer`
https://github.com/Kitware/vtk-js/blob/f3d323eb081c8ba64a34ea02c6a8bf7e55bad0fa/Sources/IO/Geometry/STLReader/index.js#L187

As expected this throws up the error.
```
ReferenceError

global is not defined

Call Stack
  Object.publicAPI.parseAsArrayBuffer
    vendor.288136d581a3c46df577.hot-update.js:207:5
  publicAPI.parse
    vendor.288136d581a3c46df577.hot-update.js:171:17
```
Can we please comment this line or change `global` to `window` ?

**Comment by jourdain** [comment]
This line should be removed. Can you submit a PR removing it?

Thanks,

Seb
