### ISSUE TITLE
error

### ISSUE THREAD

**Issue by heningwei** [Kitware/vtk-js#2199]
Use VTK.js in Vue, error 'Uncaught ReferenceError: _toConsumableArray$1 is not defined'，How to solve it please？

**Comment by daker** [comment]
@heningwei Please make sure you are using the latest version or at least v21.2.1

**Comment by heningwei** [comment]
Solved the problem with the latest version, thank you.

**Comment by daker** [comment]
@heningwei can you close the bug?
