### ISSUE TITLE
HttpDataSetReader: can't load data from basic example

### ISSUE THREAD

**Issue by MaxPal** [Kitware/vtk-js#220]
I use the the basic example in : intro_vtk_as_es6_dependency.html
The cone displays perfectly.

Then I replaced the index.js by the example from HttpDataSetReader in:
https://kitware.github.io/vtk-js/examples/HttpDataSetReader.html

I just replace the file path : (`${__BASE_PATH__}/data/cow.vtp`) by a path accessible to the webpack-dex-server in "dist" directory.

```
reader.setUrl(`data/cow2/cow.vtp/index.json`).then(() => {
  reader.loadData().then(() => {
    renderer.resetCamera();
    renderWindow.render();
  });
});
```

The file is found but an error is thrown:

```
MyWebApp.js:30017 Uncaught (in promise) TypeError: GEOMETRY_ARRAYS[dataset.vtkClass] is not a function
    at processDataSet (MyWebApp.js:30017)
    at MyWebApp.js:30093
    at <anonymous>
```

In the debuger of Chrome I found that 'dataset' has no attribute vtkClass. What I understand is that it should resolve to "vtkPolyData" this is why GEOMETRY_ARRAYS[dataset.vtkClass] is undefined and ... not a function.

The error is generated in 
"xxxx\Sources\nodeExamples\vtkjst3\node_modules\vtk.js\Sources\IO\Core\HttpDataSetReader\index.js"  at line 72 for vtk.js version 2.18.6

I tried a similar example with the same data last november and it works well.
Perhaps I am missing something very obvious. 
I am very new in development with javascript and client/server applications.

Environment:
------------------
node v7.9.0
npm v3.10.9

"vtk.js": "^2.18.6"
kw-web-suite": "^2.2.1"

Any help will be appreciated.
Thanks

**Comment by jourdain** [comment]
Do you know what `dataset` contains?

Try adding a debug line:

```console.log(JSON.stringify(dataset, null, 2));```

Moreover, you can also try to provide for the URL just `data/cow2/cow.vtp`.

We did change some code since last time you used it to enable options and reading data from zip file. But what you are doing should still work.

**Comment by MaxPal** [comment]
Thanks for the help,

I finally found the problem looking at the log from 
  `console.log(JSON.stringify(dataset, null, 2)) ` 

In fact the structure has changed a lot in the dumped files. 
I used my generated data from last november !

I regenerate the data with the new  convert-cli.js:
`>node convert-cli.js -e -m --paraview . -i ..\..\ex1\data\cow.vtp -o cow3`

and it works well ...

Sorry to bother you,
Regards,
