### ISSUE TITLE
Render DICOM series as VtkVolume

### ISSUE THREAD

**Issue by stounej** [Kitware/vtk-js#2245]
Hey,

I'm working on a React project, I have a number of DICOM files and I want to fusion them into a single vtkVolume that I can render with vtk.js and display it with axis (sagittal, coronal, axial)

I didn't find any documentation out there, all I know is I have to convert the DICOM files into a vti file (is it the only available choice ?  does it allow the 3-axis display? how we can I do it?)

 I will be gratefull for you help!

**Comment by finetjul** [comment]
You can handle your DICOM images client-side with ITK.wasm https://github.com/InsightSoftwareConsortium/itk-wasm
Otherwise, you can convert your DICOM images into .vti or .vtkjs server-side with python thanks to https://github.com/KitwareMedical/dicom-exporter/

**Comment by daker** [comment]
vtk.js doesn't have a way to parse DICOM slices, you can parse them with [dicomParser ](https://github.com/cornerstonejs/dicomParser) or itk wasm, create the voxel data with the slices pixel images. You might also check [paraview-medical](https://github.com/KitwareMedical/paraview-medical) and [itk-dicom](https://github.com/KitwareMedical/paraview-medical/tree/master/src/io/itk-dicom) used there .

**Comment by stounej** [comment]
@finetjul Thank you for your precious answer, but converting dicom images into .vti in the server-side and then send the vti file to the client-side seems to me that will take more time and ressources doesn't it? so the it is better to handle them in the client-side I guess

**Comment by stounej** [comment]
@daker Thank you for your precious answer, can dicomParser  parse 3D volumes from dicom slices? Thank you for the other solutions,.

**Comment by daker** [comment]
@stounej dicomParser or other libs will just parse the file and provide JS object, a quick search on GH will give you some hints, for ex: https://github.com/MaxwellMarcus/seg-renderer/blob/master/src/DICOMSeriesRenderer.js#L106-L139

**Comment by finetjul** [comment]
> @finetjul Thank you for your precious answer, but converting dicom images into .vti in the server-side and then send the vti file to the client-side seems to me that will take more time and ressources doesn't it? so the it is better to handle them in the client-side I guess

Correct if your DICOM files are originally on the client and not on the server. That information was not mentioned.

**Comment by stounej** [comment]
@daker Thank you so much

**Comment by stounej** [comment]
@finetjul Sorry I didn't mention it my DICOM files are in the server-side, so is it better to convert them to a VTI file and send this file to the client-side, or direclty reading those DICOM files from the server with itk-wasm in the client-side (sorry for this question I'm really stuck)

**Comment by finetjul** [comment]
If DICOM files are server-side, I guess both work, it would be faster to do as much processing server-side, so I would convert to vtkjs (or vti) server-side.

**Comment by stounej** [comment]
@finetjul Thank you so much, last question, with the solution of converting DICOM files to .vtkjs (or vti) in the server-side, can I display the 3-axis of the volume (sagital axial coronal) In addition to the 3D volume ? Like shown in the imabe below:

![image](https://user-images.githubusercontent.com/51821761/151358872-1e268f9d-c2e1-401f-8491-73e2727c4e1e.png)

**Comment by stounej** [comment]
Thank you

**Comment by thewtex** [comment]
> DICOM files from the server with itk-wasm in the client-side (sorry for this question I'm really stuck)

Note that itk-wasm also works server-side in Node.
