### ISSUE TITLE
xmlbuilder2 is bundled even if not necessary

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#2272]
### High-level description
When we import vtk.js the resulting app bundle includes `xmlbuilder2` (600kB) even though we are not using any `Sources/IO/XML` functionalities.

### Steps to reproduce
I'm not sure which specific import provokes this, the Kitware team has access to our repository so feel free to take a look at the imports.

### Current behavior
Right now the final app bundle includes unnecessary dependencies (`xmlbuilder2`)

### Environment
- **vtk.js**: @kitware/vtk.js@22.5.1
- **OS**: macOS
- **Browser**: Brave

**Comment by jourdain** [comment]
If it was use for [that](https://github.com/Kitware/vtk-js/blob/master/Utilities/XMLConverter/xml2json-cli.js) it should be a dev dependency. But not sure.

**Comment by jourdain** [comment]
@floryst you've updated the dep but, I'm not sure who put it in first. ;-)

**Comment by FezVrasta** [comment]
That's a different dependency, I'm referring to xmlbuilder2, which is used extensively across the XML modules

**Comment by FezVrasta** [comment]
marking it as external doesn't implicitly means it won't get bundled in the final app

**Comment by floryst** [comment]
This issue stems from react-vtk-js, and is not applicable to vtk.js.
