### ISSUE TITLE
*.d.ts should use relative imports in esm mode

### ISSUE THREAD

**Issue by yasushi-saito** [Kitware/vtk-js#2279]
With `npm build:esm`, the import statements in *.d.ts are rewritten to use absolute imports. For example, `Rendering/Misc/SynchronizableRenderWindow.d.ts` will have an import statement like:

```
import { vtkRenderWindow, IRenderWindowInitialValues } from '@kitware/vtk.js/Rendering/Core/RenderWindow';
```

But Typescript has a quirk where it essentially ignores transitive absolute imports (https://github.com/microsoft/TypeScript/issues/36971). So the fact that `SynchronizableRenderWindow` is a subtype of `RenderWindow` is lost. As a result, a simple code such as 

```
import vtkSynchronizableRenderWindow from '@kitware/vtk.js/Rendering/Misc/SynchronizableRenderWindow';
import vtkOpenGLRenderWindow from '@kitware/vtk.js/Rendering/OpenGL/RenderWindow';
const w = vtkSynchronizableRenderWindow.newInstance();
const g = vtkOpenGLRenderWindow.newInstance();
w.addView(g);
```

fails with 

```
TS2339: Property 'addView' does not exist on type 'vtkSynchronizableRenderWindowInstance'.
```

This problem can be fixed by changing the *.d.ts files to use relative imports. E.g.,

```
import { vtkRenderWindow, IRenderWindowInitialValues } from '../Core/RenderWindow';

```

**Comment by daker** [comment]
Thanks for the report, this is an import issue, i have submitted a fix

![image](https://user-images.githubusercontent.com/878518/154055068-06a8eece-52f5-4ab5-bdc7-616177c5c1cb.png)

**Comment by daker** [comment]
This reminds me to add some checks to prevent those issues in the future.

**Comment by yasushi-saito** [comment]
Yes, SynchronizableRenderWindow import got to be fixed (my fault,sorry), but this issue is independent of that. 

In fact, the current (wrong) statement import statement doesn't cause any typescript error. That's how I found the problem in the first place :)

**Comment by yasushi-saito** [comment]
As another example:

```
import vtkConeSource from '@kitware/vtk.js/Filters/Sources/ConeSource';
import vtkMapper from '@kitware/vtk.js/Rendering/Core/Mapper';
const coneSource = vtkConeSource.newInstance();
const mapper = vtkMapper.newInstance();
mapper.setInputConnection(coneSource.getOutputPort());
```

```
      TS2339: Property 'setInputConnection' does not exist on type 'vtkMapper'.
```

**Comment by daker** [comment]
> As another example:
> 
> ```
> import vtkConeSource from '@kitware/vtk.js/Filters/Sources/ConeSource';
> import vtkMapper from '@kitware/vtk.js/Rendering/Core/Mapper';
> const coneSource = vtkConeSource.newInstance();
> const mapper = vtkMapper.newInstance();
> mapper.setInputConnection(coneSource.getOutputPort());
> ```
> 
> ```
>       TS2339: Property 'setInputConnection' does not exist on type 'vtkMapper'.
> ```

Are you sure about this? i am not able to reproduce it [[demo](https://codesandbox.io/s/gifted-merkle-87e87m?file=/src/index.ts)], can you create a simple codesandbox to demonstrate the issue?

**Comment by yasushi-saito** [comment]
Hmm. I can't reproduce it myself. Perhaps the bad import in SynchronizableRenderWindow really caused ts to disable rest of typechecking? Sorry for the confusion.

**Comment by yasushi-saito** [comment]
Upon further investigation, use of a local symlink in `package.json` causes this problem. I created an example in https://github.com/yasushi-saito/vtkjstest. Here, `package.json` contains an entry

```
  "dependencies": {
    "@babel/runtime": "^7.16.7",
    "@kitware/vtk.js": "../vtk-js/dist/esm"
  }
```

(it assumes that vtk-js is installed and built in ../vtk-js). If you run `npm install; npm run build`, it fails with the aforementioned error. If you change the last line to, say, "@kitware/vtk.js": "^22.2.3", the code compiles.
