### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/vtk-js#228]
Using the current master, I'm seeing 14 failures when running tests on my local machine.  Is anyone else seeing this?

I have attached the test summary output in case it helps, renamed so it could be uploaded here.

[tests-md.txt](https://github.com/Kitware/vtk-js/files/980026/tests-md.txt)

**Comment by martinken** [comment]
Yeh, the images all got a pixel smaller. I have a topic to fix it, but it requires a ton of new images as they are all now a tad larger.  They all pass on my system but we may need to update a few for other systems.

**Comment by scottwittenburg** [comment]
Tested with the latest master just now, and all those tests are passing again.  Thanks!
