### ISSUE TITLE
Mobile version cannot pick points to ajust planes

### ISSUE THREAD

**Issue by ramaobalta** [Kitware/vtk-js#2285]
### High-level description
Testing ResliceCursorWidget example at https://kitware.github.io/vtk-js/examples/ResliceCursorWidget.html on my mobile, I could not angulate the planes using the points. This feature works fine on the PC Navigator unless you change to debug mode and set mobile mode.

### Steps to reproduce
Open https://kitware.github.io/vtk-js/examples/ResliceCursorWidget.html on the phone
try to pick a point, it looks very small, but this is not the problem, I changed the size on my code, same behavior.
Drag the points. It will only apply window level, the planes will not change.

### Detailed behavior
![image](https://user-images.githubusercontent.com/100292669/155335491-afa15695-92b8-4e5e-ad27-89f365825374.png)

### Expected behavior
The plane should move on the views

### Environment
We tried this example in several phones, Motorola, Samsung, Iphones near January 20, 2022
Chrome, Samsung navigator, default android navigator
And also tried with Chrome for windows - debug mode

**Comment by finetjul** [comment]
The widget does not implement `handleTouchMove`, hance mobile events (no left/right mouse button pressed) are not supported. It shouldn't be too difficult to support if you want to give it a shot.

**Comment by ramaobalta** [comment]
I tried to debug the events and noticed that the touch events are implemented and transfered to mousedown/mouse move events. Is it to possible that it could be using something differente? Maybe a picker?

**Comment by floryst** [comment]
Relevant: https://github.com/Kitware/vtk-js/pull/2348
