### ISSUE TITLE
AbstractWidgetFactory widgetState onModified execution ordering

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#2305]
### High-level description

The offending lines of code: https://github.com/Kitware/vtk-js/blob/master/Sources%2FWidgets%2FCore%2FAbstractWidgetFactory%2Findex.js#L177-L181

This breaks tests, likely because `model.widgetState` is checked after a widget test runs and resources are cleaned up. The workaround would be to set a guard on `model.widgetState`, but I think we can do better than that.

We can require that the AbstractWidgetFactory constructor take in a non-null widgetState. This will change where we define widget behavior and widget state, but I think that'll be for the better. Right now, it's defined in the derived class's constructor, [as seen here (ImageCroppingWidget as an example)](https://github.com/Kitware/vtk-js/blob/master/Sources%2FWidgets%2FWidgets3D%2FImageCroppingWidget%2Findex.js#L102-L103). A proposed approach would be to instead move it [here, and pass it into the initialValues for AbstractWidgetFactory](https://github.com/Kitware/vtk-js/blob/master/Sources%2FWidgets%2FWidgets3D%2FImageCroppingWidget%2Findex.js#L157). This way, we don't have an initialization ordering workaround, and we preserve the notion that the AbstractWidgetFactory requires a widget state on init. @jourdain 

### Steps to reproduce
See the #2298 comments. Running tests causes the issue.

### Detailed behavior
See the #2298 comments, and my description above.

### Expected behavior
Tests do not fail in this manner.

### Environment
- **vtk.js**: 22.5.10
- **OS**: Windows 10
- **Browser**: Chrome 98

**Comment by jourdain** [comment]
Fine with me... Thanks for keep pushing the widgets infrastructure forward...
