### ISSUE TITLE
Type definitions are not properly resolved when using `npm link`

### ISSUE THREAD

**Issue by Georift** [Kitware/vtk-js#2311]
### High-level description

When working on the typescript definitions using `npm link` some types are unable to be resolved. Perhaps I'm doing something wrong? Or this is an unsupported was of developing types. @daker would you share how you've been developing the types?

### Steps to reproduce

```
# in vtk.js repo
npm run dev:esm

cd dist/esm/ # so we get the @kitware/vtk.js package rather than the vtk.js
npm link

# in the linked project dir
npm link @kitware/vtk.js
``` 

```typescript
import vtkOrientationMarkerWidget from "@kitware/vtk.js/Interaction/Widgets/OrientationMarkerWidget"

// type error! .onModified does not exist on vtkOrientationMarkerWidget despite it extending vtkObject
vtkOrientationMarkerWidget.newInstance().onModified()
```

This is happening because `vtkObject` cannot be resolved, if we look at the defintion we can see:
```typescript
import { vtkObject } from '@kitware/vtk.js/interfaces';
```
Which I guess doesn't work in an `npm link` environment?

However if the import was:
```typescript
import { vtkObject } from './../../interfaces';
```
Everything types correctly.

My solution for now has been to override the absolute import code in `rollup.config.js`:
https://github.com/Kitware/vtk-js/blob/ea51f4538773febf4cbc36e103b1ba677ff682f1/rollup.config.js#L184,L194

With quick hack to leave it as relative and "mostly" get it hooked up again:
```typescript
return absolutifyImports(content.toString(), (relImport) => {
  if (relImport.startsWith('../')) {
    return './' + relImport.slice(3);
  }
  return relImport;
});
```

### Environment
- **vtk.js**: master branch
- **OS**: Debian
- **Browser**: N/A

**Comment by daker** [comment]
@Georift thanks for digging into the issue, i can confirm the problem.

@floryst i propose to add a env var something like NO_ABSOLUTIFY_IMPORT which will be set for the dev:esm and use it the rollup transform step.

@yasushi-saito i think this is issue that you were bringing in https://github.com/Kitware/vtk-js/issues/2279#issuecomment-1040355919 ?

**Comment by Georift** [comment]
> @Georift thanks for digging into the issue, i can confirm the problem.
> 
> @floryst i propose to add a env var something like NO_ABSOLUTIFY_IMPORT which will be set for the dev:esm and use it the rollup transform step.
> 
> @yasushi-saito i think this is issue that you were bringing in https://github.com/Kitware/vtk-js/issues/2279#issuecomment-1040355919 ?

Oh yeah for sure, your comment @yasushi-saito, expressed the problem far better than I have.

One thing I would add is the roll-up code I showed may not cover all cases, I did notice it broke when there was no top level `../`. I suspect it might have something to do with the Sources stripping?

Would you be open to me raising a PR implementing your proposal?

**Comment by floryst** [comment]
> @floryst i propose to add a env var something like NO_ABSOLUTIFY_IMPORT which will be set for the dev:esm and use it the rollup transform step.

This seems fine by me. I actually am not 100% sure we need that anyways. It should be better to just make all paths relative. That way, it will work for `npm link`, and regular package installs shouldn't be affected at all. 


> One thing I would add is the roll-up code I showed may not cover all cases, I did notice it broke when there was no top level `../`. I suspect it might have something to do with the Sources stripping?

Do you mean that, from the repo root, `..` hits `/`? It would seem odd that a path strays outside of the repo root, but maybe there's some path-related bug somewhere.
