### ISSUE TITLE
Bugs in TypeScript type definitions.

### ISSUE THREAD

**Issue by subdavis** [Kitware/vtk-js#2317]
### High-level description

2 bugs in typescript type definitions.

### Steps to reproduce

Try to use vtkFullScreenRenderWindow from a typescript project.

### Detailed behavior

* `rootContainer` is not defined on IFullScreenRenderWindowInitialValues
* Param to `setRendertimemultiplier` needs a non-any type.

```
~$ yarn type
yarn run v1.22.15
$ vue-tsc -p tsconfig.check.json --noEmit
src/components/MeshViewer.vue:30:72 - error TS2345: Argument of type '{ rootContainer: HTMLElement; }' is not assignable to parameter of type 'IFullScreenRenderWindowInitialValues'.
  Object literal may only specify known properties, and 'rootContainer' does not exist in type 'IFullScreenRenderWindowInitialValues'.

30     const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({ rootContainer });
                                                                          ~~~~~~~~~~~~~

node_modules/@kitware/vtk.js/Rendering/Core/Prop.d.ts:235:29 - error TS7006: Parameter 'renderTimeMultiplier' implicitly has an 'any' type.

235     setRendertimemultiplier(renderTimeMultiplier): boolean;
                                ~~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

Type checking should pass (without having to disable library type checks).

### Environment
- **vtk.js**: 23.0.1
- **OS**: n/a
- **Browser**: n/a

**Comment by daker** [comment]
Thanks for the report! i don't see any setter for `rootContainer` 
https://github.com/Kitware/vtk-js/blob/0c8a0740a72a3e57fc265920a339b92fa665290d/Sources/Rendering/Misc/FullScreenRenderWindow/index.js#L207-L215

For the second issue it's valid, if you can propose quick PR otherwise i will look at it tonight.

**Comment by daker** [comment]
@jourdain is this vtk vue example correct?

**Comment by jourdain** [comment]
It is indeed correct but technically we should not use the FullScreenRenderWindow for such React/Vue integration. 
Sorry @floryst for not catching that sooner.

For reference all the examples are using it to skip the 20 lines needed for setting the render window and focus only on the code that the example is showing off. [This example](https://kitware.github.io/vtk-js/examples/SimpleCone.html) is the only one which kept the rendering part the way it should be. 

Examples on how to integrate a vtk render window in React or Vue can be found in [react-vtk-js](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js) and [vue-vtk-js](https://github.com/Kitware/vue-vtk-js/blob/master/src/core/VtkView/script.js). But those again might be too advanced for a simple integration example...

**Comment by Zeng95** [comment]
```js
Argument of type '{ rootContainer: HTMLDivElement | null; }' is not assignable to parameter of type 'IFullScreenRenderWindowInitialValues'.
  Object literal may only specify known properties, but 'rootContainer' does not exist in type 'IFullScreenRenderWindowInitialValues'. Did you mean to write 'container'?
```

I'm still getting the error, and I have to use `// @ts-ignore` to make it disappear.

**Comment by daker** [comment]
@Zeng95 can you report a bug? i can look at it ASAP.

**Comment by Zeng95** [comment]
> @Zeng95 can you report a bug? i can look at it ASAP.

Sure
