### ISSUE TITLE
Change zSlice of vtkImageMapper

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#232]
I try to move zSlice of a vtkImageMapper but without success.
Here's the code I use : 
```
mapper.setInputData(data);
mapper.setUseCustomExtents(true);
const extent = data.getExtent();
mapper.setCustomDisplayExtent(extent[0], extent[1], extent[2], extent[3]);
mapper.setZSlice(50);
```
Instead of display a slice, the camera zoom on the first slice of the volume.
Did I miss anything to make it works well ?
For info : Used data is "${__BASE_PATH__}/data/volume/LIDC2.vti"
Here is the slice 0
![image](https://cloud.githubusercontent.com/assets/11785751/25900797/ed09ff7e-3594-11e7-941e-ce9f603f9dcd.png)

And here the slice 50 I tried to change but it makes just a zoom
![image](https://cloud.githubusercontent.com/assets/11785751/25900817/03abcdfc-3595-11e7-9e87-333eaabd31fe.png)

**Comment by martinken** [comment]
Give this a shot

https://github.com/Kitware/vtk-js/pull/234

Also you might want to look at the changes I make to the example. The interactor style image can now be set to control slices as well.

**Comment by laurennlam** [comment]
@martinken It looks good, thanks a lot !
As I understand, the slice can only be changed on Z axis, is it right ?

**Comment by martinken** [comment]
YOu could add some functionality to the slice mapper to support something like

//@{
  /**
   * Set the orientation of the slices to display.  The default
   * orientation is 2, which is Z.
   */
  vtkSetClampMacro(Orientation, int, 0, 2);
  vtkGetMacro(Orientation, int);
  void SetOrientationToX() { this->SetOrientation(0); }
  void SetOrientationToY() { this->SetOrientation(1); }
  void SetOrientationToZ() { this->SetOrientation(2); }
  //@}

You would need to reorder the data before sending it to OpenGL. My gut would be to make a copy of the data and reorder it everytime the data updates. Then in the mapper you just use that data. The second alternative is to reorder the data for each slice as it is sent to OpenGL but given that people scroll through slices a lot I would suspect that would get slow. The third alternative is to add a cache to the opengl slice mapper and reorder and cache as requested. Making it a tad slow for the first scroll through as it reorders but fast after that. I would go with option 1 or 3. I would put the orientation option in the Core class and the actual reorder code in the OpenGL class. Update the setslicefromfocalPoint to handle the orientation setting as well.
