### ISSUE TITLE
mobile multi touch problem

### ISSUE THREAD

**Issue by zweideux** [Kitware/vtk-js#2329]
https://kitware.github.io/vtk-js/examples/InteractorStyleTrackballCamera.html

In this example, when I perform multitouch actions (pan, pinch, Etc.), I cannot run the function of the element on the vtk view canvas.
If I touch two time or more, then the function is performed.

 
![image](https://user-images.githubusercontent.com/7368678/159668601-8aaa4ffd-1d35-4159-a150-9b0f3b0f256e.png)

**Comment by floryst** [comment]
I'm guessing #2347 might be related.

**Comment by floryst** [comment]
This is fixed in #2431.
