### ISSUE TITLE
when using vtkResliceCursorWidget with old video card，ShaderCache report error

### ISSUE THREAD

**Issue by cnszpeak** [Kitware/vtk-js#2344]
### High-level description

in vtk-js-master\Sources\Rendering\OpenGL\ShaderCache\index.js，report ：array index for gl_FragData must be zero when GL_EXT_draw_buffers is disabled
### Steps to reproduce

1.Video Card:Intel(R) HD Graphics
2.Edge 99.0.1150.55 ,64 bits
3.report errors in console window:
vtk.js:2 
        
       Error compiling shader '#version 100

#extension GL_OES_standard_derivatives : enable

#extension GL_EXT_frag_depth : enable
#extension GL_EXT_shader_texture_lod : enable
#define textureCubeLod textureCubeLodEXT
#define texture2DLod texture2DLodEXT
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp int;
#else
precision mediump float;
precision mediump int;
#endif

/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkPolyDataFS.glsl

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// Template for the polydata mappers fragment shader

uniform int PrimitiveIDOffset;

// VC position of this fragment
varying vec4 vertexVCVSOutput;

// optional color passed in from the vertex shader, vertexColor
uniform float ambient;
uniform float diffuse;
uniform float specular;
uniform float opacityUniform; // the fragment opacity
uniform vec3 ambientColorUniform;
uniform vec3 diffuseColorUniform;
uniform vec3 specularColorUniform;
uniform float specularPowerUniform;

// optional surface normal declaration
varying vec3 normalVCVSOutput;

// extra lighting parameters
//VTK::Light::Dec

// Texture coordinates
//VTK::TCoord::Dec

// picking support
uniform vec3 mapperIndex;
uniform int picking;

// Depth Peeling Support
//VTK::DepthPeeling::Dec

// clipping plane vars
//VTK::Clip::Dec

// the output of this shader
//VTK::Output::Dec

// Apple Bug
//VTK::PrimID::Dec

// handle coincident offsets
uniform float cfactor;
uniform float coffset;

//VTK::ZBuffer::Dec

void main()
{
  // VC position of this fragment. This should not branch/return/discard.
  vec4 vertexVC = vertexVCVSOutput;

  // Place any calls that require uniform flow (e.g. dFdx) here.
  float cscale = length(vec2(dFdx(gl_FragCoord.z),dFdy(gl_FragCoord.z)));
//VTK::UniformFlow::Impl

  // Set gl_FragDepth here (gl_FragCoord.z by default)
  gl_FragDepthEXT = gl_FragCoord.z + cfactor*cscale + 0.000016*coffset;

  // Early depth peeling abort:
  //VTK::DepthPeeling::PreColor

  // Apple Bug
  //VTK::PrimID::Impl

  //VTK::Clip::Impl

  vec3 ambientColor;
  vec3 diffuseColor;
  float opacity;
  vec3 specularColor;
  float specularPower;
  ambientColor = ambientColorUniform;
  diffuseColor = diffuseColorUniform;
  opacity = opacityUniform;
  specularColor = specularColorUniform;
  specularPower = specularPowerUniform;

  // Generate the normal if we are not passed in one
  vec3 normalVCVSOutput = normalize(normalVCVSOutput);
  if (gl_FrontFacing == false) { normalVCVSOutput = -normalVCVSOutput; }

  //VTK::TCoord::Impl

    float df = max(0.0, normalVCVSOutput.z);
  float sf = pow(df, specularPower);
  vec3 diffuseL = df * diffuseColor;
  vec3 specularL = sf * specularColor;
  gl_FragData[0] = vec4(ambientColor * ambient + diffuseL * diffuse + specularL * specular, opacity);
  //VTK::Light::Impl

  if (gl_FragData[0].a <= 0.0)
    {
    discard;
    }

  //VTK::DepthPeeling::Impl

    gl_FragData[0] = picking != 0 ? vec4(mapperIndex,1.0) : gl_FragData[0];

  // handle coincident offsets
  //VTK::Coincident::Impl

  //VTK::ZBuffer::Impl

  
      float weight = gl_FragData[0].a * pow(max(1.1 - gl_FragCoord.z, 0.0), 2.0);
      gl_FragData[0] = vec4(gl_FragData[0].rgb*weight, gl_FragData[0].a);
      gl_FragData[1].r = weight;
    
}
': ERROR: 0:141: '[]' : array index for gl_FragData must be zero when GL_EXT_draw_buffers is disabled

### Environment
- **vtk.js**: 
- **OS**: 
- **Browser**:

**Comment by floryst** [comment]
Marking this as closed, since #2346 looks like it addresses the issue. If the issue still persists, do re-open this with any new info.
