### ISSUE TITLE
activeListenerCount in RenderWindowInteractor doesn't decrement with multi-touch gestures

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/vtk-js#2347]
I believe this is the issue, please let me know if I missed anything or if more information is required.
### High-level description
Multi-touch Mobile RenderWindowInteractor doesn't properly decrement `activeListenerCount` when dealing with multi-touch interactions.

### Steps to reproduce
The basic result is we have a HTML button above the render and after using multi-touch gestures on mobile.  The button has to be hit N times the number of multi touch gestures done + 1 to activate properly.
A way to test it:
- Load up data and monitor the `activeListenerCount` so you can watch it decrement and increment
- As you do multi-touch gestures (panning with two fingers or pinch to zoom) you can watch the `activeListenerCount` increment but each time the two fingers are removed it will only decrement 1 value instead of 2.

### Detailed behavior
- Within the touchEnd handler it will decrement the `activeListenerCount` using a function `interactionRegistration(false)`; -https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js#L691
- With the case of removing two fingers from a gesture it does a call initially where `event.touches.length === 1 && event.changedTouches.length === 1`.  So it executes this [conditional block](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js#L714-L725) which doesn't decrement the `activeListenerCount` using `interactionRegistration(false)`.  Now when the final finger is released it will decrement only once.  So that means that each time you do a multi-touch gesture you are adding 1 to the `activeListenerCount` which never gets reset.
- 
### Expected behavior
I think that `activeListenerCount` should go to 0 when all fingers are removed and that it doesn't `preventDefault` for buttons that are overlayed on the render area when tapping after removing all fingers.

### Environment
- **vtk.js**: 23.0.1
- **OS**: Android 
- **Browser**:Chrome (100.0.4896.58)

**Comment by ScottShingler** [comment]
Just noticed this on our project today. This is easily reproducible on the [cone live example](https://kitware.github.io/vtk-js/examples/Cone.html) as shown in this video:

https://user-images.githubusercontent.com/10943423/161600116-88ab4f7d-24c8-4642-a464-0a10b9f43051.mp4

### Environment

* **vtk.js:** Not sure if the live vtk.js examples always use the latest version, but the latest version was `24.2.1` at the time. For our project, we're using 22.6.1
* **OS:** Windows 8.1
* **Browser:** Chrome 100.0.4896.60
* **Device:** Microsoft Surface Pro 3 i7

**Comment by floryst** [comment]
FYI the linked PR should resolve this issue.
