### ISSUE TITLE
Can use class refactoring in the future?

### ISSUE THREAD

**Issue by zhangzhi93** [Kitware/vtk-js#2363]
I hope to use class refactoring, the current inheritance relationship is more difficult to understand. 
  The API description in the official documentation is not complete. Some methods do not know what to do, what values can be set for some fields, and the range of settings is not specified.Hope the documentation can be better.

**Comment by jourdain** [comment]
Classes don't provide the level of isolation required in VTK. If we let the objects open, the first thing a user will do, will be to modify the underlaying structure without the system knowing which will lead to invalid result and behavior. 

We hope with time to be able to provide typescript definition to help with the "documentation" part.
