### ISSUE TITLE
Click/release button out of render window

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#237]
- click into the viewer and maintain the click
- move the cursor outside of the viewer 
- release the mouse button 
- go back to the viewer
It applies a rotation as if the cursor hadn't been released.

I think when the cursor is out of the viewer (renderwindow), it should considers that the mouse button have been release, is it right ? Then, if the mouse goes back into the render window, user has to click again to make a rotation.

**Comment by laurennlam** [comment]
Does anyone has a clue to fix this ? @jourdain @martinken  ?

**Comment by jbeezley** [comment]
You can bind the events to the `document` object instead of the render window, but you have to be careful to avoid memory leaks.  The usual method is to bind the `mousemove` and `mouseup` handlers to the  `document` object  on `mousedown` and unbind them inside the `mouseup` handler.

**Comment by laurennlam** [comment]
@jbeezley Thanks for your suggestions. I'll take a look on this !

**Comment by laurennlam** [comment]
Here is the way I found to fix my issue. I update the file Sources/Rendering/Core/RenderWindowInteractor :
```
publicAPI.bindEvents = (canvas) => {
...
canvas.addEventListener('mouseout', publicAPI.handleMouseOut);
...
}
```
```
publicAPI.unbindEvents= (canvas) => {
...
canvas.removeEventListener('mouseout', publicAPI.handleMouseOut);
...
}
```
```
publicAPI.handleMouseOut = (event) => {
    event.stopPropagation();
    event.preventDefault();

    switch (event.which) {
      case 1:
        publicAPI.leftButtonReleaseEvent();
        break;
      case 2:
        publicAPI.middleButtonReleaseEvent();
        break;
      case 3:
        publicAPI.rightButtonReleaseEvent();
        break;
      default:
        break;
    }
  };
```
With this method, I don't have to bind document event.
Thanks !
