### ISSUE TITLE
ImageCroppingWidget can't interact properly

### ISSUE THREAD

**Issue by HuWei501** [Kitware/vtk-js#2374]
I found some problems with the examples on the official website(https://kitware.github.io/vtk-js/examples/ImageCroppingWidget.html)

I can't drag my selected point correctly in ImageCroppingWidget

https://user-images.githubusercontent.com/19411208/164004193-9a62d0e8-e85d-4344-bd79-82ded04db3a2.mp4

.

**Comment by floryst** [comment]
Thanks, that's an odd regression. We will look into it.
