### ISSUE TITLE
InteractiveOrientationWidget example is broken

### ISSUE THREAD

**Issue by Julesdevops** [Kitware/vtk-js#2377]
### High-level description
The InteractiveOrientationWidget example is broken.
Seems like its since: https://github.com/Kitware/vtk-js/commit/e1557c40b1271fef2181a254df647544eb564b4f#

### Steps to reproduce
Run the example, you should see a cone in the view.

### Detailed behavior
we cant see the cone from the conesource
### Expected behavior
We should see a cone

### Environment
- **vtk.js**: master
- **OS**: Archlinux
- **Browser**:Firefox

**Comment by jourdain** [comment]
https://kitware.github.io/vtk-js/examples/InteractiveOrientationWidget.html

**Comment by Julesdevops** [comment]
Looks like as soon as you have some translucent actors, you can't see the actors that are totally opaque.
In the example the widget cube's faces are translucent: https://github.com/Kitware/vtk-js/blob/557973d4889cd6bdd39e78904bd3bf551ae8e2fa/Sources/Widgets/Representations/ConvexFaceContextRepresentation/index.js#L125
If you call `actor.getProperty().setOpacity(0.9);` on the cone actor in the example, the cone appears.
Same if you pass a default opacity value to 1 for the cube faces...

**Comment by martinken** [comment]
Nested renderer issue most likely as opposed to just simple mixed geometry. I'll look into it.

**Comment by Julesdevops** [comment]
I'm closing this off since the problem has been resolved in v24.5.3
Thanks for the rapid fix, Ken
