### ISSUE TITLE
Add direction to `XMLImageDataReader`

### ISSUE THREAD

**Issue by ramonemiliani93** [Kitware/vtk-js#2380]
### Need
When overlaying images that have different origin, if the direction is not included, visualization will not be correct. 

### Feature

Include the direction on the XML reader (probably on the writer too). If reading an XML file generated from a VTK C++ writer then the following should be enough to read:
```js
const direction = imageDataElem
      .getAttribute('Direction')
      .split(' ')
      .map((t) => Number(t));
```

**Comment by finetjul** [comment]
Can you please create a PR to add such feature?

**Comment by ramonemiliani93** [comment]
Hey @finetjul I just pushed some changes 👌 I am not very familiar with JS so if anything is off let me know and I can update it.
