### ISSUE TITLE
RenderWindow example?

### ISSUE THREAD

**Issue by zachmullen** [Kitware/vtk-js#239]
In looking through the docs, all the examples I could find use the `FullScreenRenderWindow`. I'm trying to render to a specific element in the DOM, but couldn't easily find such an example. Does one exist? If not, how do I do that?

**Comment by martinken** [comment]
Here is an example from before Seb converted them.  I think it should work.

https://github.com/Kitware/vtk-js/blob/27abf6817e8edc621f00fbd441b551bde6d3e060/Examples/WebGL/Cone/index.js

But yes +1 we need to have at least one example that does not use the full screen helper.

**Comment by jourdain** [comment]
Well you can also look at the content of the code of the `FullScreenRenderWindow`.

But I guess you are right, we should have a plain fully descriptive RenderWindow/Renderer/Interactor example. It just that's always the same boilerplate that I made that full screen guy so we won't have to clutter example with side and `uninteresting` code. ;-)

**Comment by laurennlam** [comment]
@zachmullen Here is an example I often use for my project : 

```
this.renderWindow = vtkRenderWindow.newInstance();
this.renderer = vtkRenderer.newInstance();
this.renderWindow.addRenderer(this.renderer);
this.openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
const container = document.getElementById(divName);
this.openglRenderWindow.setContainer(container);
this.renderWindow.addView(this.openglRenderWindow);

const dimsContainer = container.getBoundingClientRect();
this.openglRenderWindow.setSize(dimsContainer.width, dimsContainer.height);

this.interactor = vtkRenderWindowInteractor.newInstance();
this.interactor.setView(this.openglRenderWindow);
this.interactor.initialize();
this.interactor.bindEvents(container);
```

`<div id="3DVisualization" style="height: 800px; width: 800px;"></div>`

Hope it helps.

**Comment by martinken** [comment]
We now have a minimal example in Examples\WebGL\SimpleCone
