### ISSUE TITLE
Incorrectly typed vtkRenderer.visibleActorCount

### ISSUE THREAD

**Issue by emil-peters** [Kitware/vtk-js#2390]
### High-level description
In the `index.d.ts` of the `vtkRenderer` the function `visibleActorCount` is incorrectly typed.
The type given is void, while the result of this function is a number as seen in the implementation:
```js
  publicAPI.visibleActorCount = () =>
    model.props.filter((prop) => prop.getVisibility()).length;
```

### Expected behavior
I would expect the type be:
```js
  /**
  * Get the number of visible actors.
  */
  visibleActorCount(): number;
```

### Environment
- **vtk.js**: 24.0.0
- **OS**: iOS 12.3.1

**Comment by emil-peters** [comment]
ps. If there is a small tutorial on how to update this, and create a PR For this, I'm willing to fix this issue

**Comment by daker** [comment]
Thank you for the report, if you want to fix this, it's easy you can fork the repo, create a branch in your fork, fix the [index.d.ts](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Renderer/index.d.ts#L559-L562), stage it then commit and push, once done propose it as PR.

https://github.com/Kitware/vtk-js/blob/master/CONTRIBUTING.md#workflow
