### ISSUE TITLE
No type declarations for ITKHelper

### ISSUE THREAD

**Issue by AlmightyYakob** [Kitware/vtk-js#2397]
### High-level description
There's no TypeScript type declaration (`.d.ts`) files for [ITKHelper](https://github.com/Kitware/vtk-js/tree/master/Sources/Common/DataModel/ITKHelper).

### Steps to reproduce
```typescript
import vtkITKHelper from '@kitware/vtk.js/Common/DataModel/ITKHelper';
```

TypeScript will complain about missing declarations

**Comment by daker** [comment]
@AlmightyYakob we don't have all the definitions yet, can you check the PR?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob we don't have all the definitions yet, can you check the PR?

Forgot to reply, it looked good to me.
