### ISSUE TITLE
TS enums in declaration files

### ISSUE THREAD

**Issue by Julesdevops** [Kitware/vtk-js#2400]
### High-level description
Hi and thanks in advance for the help! :)
Errors when trying to import VTK.js enum into a typescript codebase.
Also I don't understand why we have enums (which compiles down to actual JS code) in declaration files which are not compiled?

### Steps to reproduce
In a typescript codebase/application, use 
`import { Corners } from "@kitware/vtk.js/Interaction/Widgets/OrientationMarkerWidget"`
You should get a compile-time error from tsc, which can't find the enum.
For `vtk-js/Sources/Interaction/Widgets/OrientationMarkerWidget::setViewportCorner` for instance the parameter is typed as the `Corners` enum, but since I can't use it, I cannot satisfy the ts compiler. (If I pass "BOTTOM_LEFT" string the type checking fail.)

### Detailed behavior
Failed build because of type-checking.

### Expected behavior
Typescript consumers of VTK.js should be able to natively satisfy the type checking

### Environment
- **vtk.js**: v19.4.0
- **OS**: archlinux
- **Browser**: not relevant

edit: typos

**Comment by daker** [comment]
I might have made some mistakes on this, i will check it ASAP

**Comment by daker** [comment]
@Julesdevops i have tried to fix the the Constants.d.ts issues in the PR

The mentioned import was produced by the export enum in index.d.ts which is wrong, the import should something like the following:

```js
import Constants from '@kitware/vtk.js/Interaction/Widgets/OrientationMarkerWidget/Constants';
const { Corners } = Constants;
// or
import vtkOrientationMarkerWidget from '@kitware/vtk.js/Interaction/Widgets/OrientationMarkerWidget';
vtkOrientationMarkerWidget.Corners
```

**Comment by Julesdevops** [comment]
awesome thanks
