### ISSUE TITLE
Consider new docs section for high-level concepts

### ISSUE THREAD

**Issue by zachmullen** [Kitware/vtk-js#241]
This would be very helpful for those who are not already familiar with VTK. It could go in the "Overview" section and would explain things like what are mappers, actors, renderers, render windows, interactors, etc. Explaining these things could help open up vtk.js to a wider audience.

**Comment by jourdain** [comment]
The following example setup each part following the VTK pattern.

https://kitware.github.io/vtk-js/examples/SimpleCone.html

Then most of that logical split is explained inside the [VTK book](https://www.vtk.org/vtk-textbook/)

**Comment by jourdain** [comment]
[Link to the Book PDF](https://www.kitware.com/products/books/VTKTextbook.pdf)
