### ISSUE TITLE
vtkLookupTable.setAboveRangeColor method parameter is mistyped as "Ranged"

### ISSUE THREAD

**Issue by nicolascedilnik** [Kitware/vtk-js#2413]
**vtk.js**: 24.10.0

In LookupTable.d.ts we have:

```
	/**
	 * 
	 * @param aboveRangeColor 
	 */
	setAboveRangeColor(aboveRangeColor: Range): boolean;
```

But in fact, this method accepts an `RGBAColor` (which makes more sense). It's also the case for `setBelowRangeColor`.

This is annoying because the typescript compiler won't accept it this way. Just modifying the file in `./node_modules` solves the issue.

**Comment by jourdain** [comment]
Submitting PR to update TS definitions is the way to go for quickly improving those TS mismatch.

**Comment by truenicoco** [comment]
(switched to personal GH account, but it's the same person)

I thought these were auto-generated somehow, but apparently I was wrong.
