### ISSUE TITLE
LineWidget Example Broken

### ISSUE THREAD

**Issue by seattlewayne** [Kitware/vtk-js#2416]
### High-level description
LineWidget Example throws error when attempting to add widget.

### Steps to reproduce

- Run the [LineWidget example](https://kitware.github.io/vtk-js/examples/LineWidget.html)
- Click on "Add Widget"

### Detailed behavior
Attempting to add the widget sends the following error to the console:
```
LineWidget.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'isVisible')
    at Object.e.updateActorVisibility (LineWidget.js:1:646605)
    at Object.UO.e.updateHandleVisibility (LineWidget.js:1:667871)
    at aA (LineWidget.js:1:674833)
    at HTMLButtonElement.<anonymous> (LineWidget.js:1:678231)
```
The widget is not displayed.

### Expected behavior
It should insert a LineWidget and not generate the error.

### Environment
- **vtk.js**: v24.10.0
- **OS**: not relevant
- **Browser**: not relevant

**Comment by finetjul** [comment]
Regression from #2381
