### ISSUE TITLE
Box widget example is broken

### ISSUE THREAD

**Issue by Julesdevops** [Kitware/vtk-js#2428]
The Widgets>Box example is broken: https://kitware.github.io/vtk-js/examples/Box.html
I can look into it someday

**Comment by floryst** [comment]
Looks like that wasn't updated when the moveToProtected commit occurred. `model.renderer.getActiveCamera()` should be `model._renderer.getActiveCamera()`.

**Comment by Julesdevops** [comment]
would it make sense to make a "real" available widget out of it? currently if I understood well it's only example code

**Comment by Julesdevops** [comment]
My branch: https://github.com/Julesdevops/vtk-js/tree/fix-box-widget
The example shows up but it seems to be broken (no handles visibility...), will look into it

**Comment by floryst** [comment]
I don't know if it has any real use as of yet. It probably can stay an example. IIRC @jourdain made that example.

**Comment by jourdain** [comment]
I don't remember why I made it. Probably to build the initial features. If not relevant anymore, we should remove it...

**Comment by Julesdevops** [comment]
Actually we may need it soon in one project, so I have an interest in making this a fist-class citizen

**Comment by Julesdevops** [comment]
fixed as part of https://github.com/Kitware/vtk-js/commit/189d708d14bc35abfa59cf61098ab7634f20ae33
Keeping this open for making this widget available for client code
