### ISSUE TITLE
pako is bundled twice

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#2429]
### High-level description
pako is bundled twice when @kitware/vtk.js is imported in a project, one is a top-level dependency (pako@2.0.3) and the other is a dependency of jszip (pako@1.0.11).

### Steps to reproduce

https://bundle.js.org/?q=@kitware/vtk.js,@kitware/vtk.js/Common/Core/Math,@kitware/vtk.js/Common/DataModel/Plane,@kitware/vtk.js/Common/Core/Math,@kitware/vtk.js/Common/DataModel/ImageData,@kitware/vtk.js/Common/DataModel/ITKHelper,@kitware/vtk.js/Common/Core/Math,@kitware/vtk.js/Common/Core/Math,@kitware/vtk.js/Interaction/Manipulators/MouseCameraTrackballRotateManipulator,@kitware/vtk.js/Interaction/Manipulators/MouseCameraTrackballZoomToMouseManipulator,@kitware/vtk.js/Interaction/Manipulators,@kitware/vtk.js/Rendering/Core/Property2D/Constants,@kitware/vtk.js/Rendering/Core/Coordinate/Constants&treeshake=[*],[{+angleBetweenVectors+}],[{+default+as+z+}],[{+multiply3x3_vect3+}],[{+default+as+x+}],[{+default+as+y+}],[{++signedAngleBetweenVectors,cross,min,norm,}],[{+add,multiplyScalar,normalize,subtract,clampValue,dot+}],[{+default+as+m+}],[{+default+as+mm+}],[{+default+as+Manipulators+}],[{++DisplayLocation+}],[{+Coordinate+}]&config={"analysis":true}

### Current behavior

<img width="949" alt="CleanShot 2022-05-20 at 4 12 41@2x" src="https://user-images.githubusercontent.com/5382443/169546931-b1fc0f61-41e6-4db3-b311-dfaa4516a217.png">

### Environment
- **vtk.js**: 
- **OS**: 
- **Browser**:

**Comment by FezVrasta** [comment]
This could be an opportunity to switch from pako and jszip to [`fflate`](https://github.com/101arrowz/fflate), it's much more lightweight and should also be faster.

**Comment by floryst** [comment]
I'll check out `fflate`. There appears to be no current signal in the jszip repo to bump pako, which means we are stuck with the two versions in the build output. If fflate can handle high-level zip routines and low-level deflate routines, then that will be a good candidate.

**Comment by FezVrasta** [comment]
A short-term solution could be to downgrade to the same version used by jszip? Unless you need something from the new versions.

**Comment by floryst** [comment]
I was initially considering switching to pako v1 as an intermediate solution, but I will have to verify that downgrading won't introduce errors on reading compressed datasets. It may be easier to just switch to fflate, especially since I want to see if fflate fixes #2099.

**Comment by FezVrasta** [comment]
Looking at the treemap I also wonder if it's okay to see so many XML-related dependencies given the inputs I specified in the bundlejs configuration?

```js
// Click Build for the Bundled, Minified & Compressed package size
export * from "@kitware/vtk.js";
export { angleBetweenVectors } from "@kitware/vtk.js/Common/Core/Math";
export { default as z } from "@kitware/vtk.js/Common/DataModel/Plane";
export { multiply3x3_vect3 } from "@kitware/vtk.js/Common/Core/Math";
export { default as x } from "@kitware/vtk.js/Common/DataModel/ImageData";
export { default as y } from "@kitware/vtk.js/Common/DataModel/ITKHelper";
export {  signedAngleBetweenVectors, cross, min, norm, } from "@kitware/vtk.js/Common/Core/Math";
export { add, multiplyScalar, normalize, subtract, clampValue, dot } from "@kitware/vtk.js/Common/Core/Math";
export { default as m } from "@kitware/vtk.js/Interaction/Manipulators/MouseCameraTrackballRotateManipulator";
export { default as mm } from "@kitware/vtk.js/Interaction/Manipulators/MouseCameraTrackballZoomToMouseManipulator";
export { default as Manipulators } from "@kitware/vtk.js/Interaction/Manipulators";
export {  DisplayLocation } from "@kitware/vtk.js/Rendering/Core/Property2D/Constants";
export { Coordinate } from "@kitware/vtk.js/Rendering/Core/Coordinate/Constants";
```

**Comment by floryst** [comment]
Yeah, I was wondering that too. I would have to figure out what is pulling in the XML readers. At a first glance, there shouldn't be any need for the IO module at all.

**Comment by FezVrasta** [comment]
Ah nevermind, the XML issue is because I'm importing `* from "kitware/vtk.js"`, I must have forgotten to remove it from there.

**Comment by floryst** [comment]
Oh yep, I forgot the top-level export includes all of the symbols. Good catch.
