### ISSUE TITLE
Is vtk.js supporting glTF file?

### ISSUE THREAD

**Issue by xuhenry** [Kitware/vtk-js#2441]
### Need

Is vtk.js supporting glTF file?

**Comment by floryst** [comment]
Duplicate of https://github.com/Kitware/vtk-js/issues/210. AFAIK we have draco support in vtk.js, but I don't think we have gltf at the moment.

@daker do you have any info on the gltf loader you mentioned in the aforementioned issue?

**Comment by daker** [comment]
a draft PR to be reworked in #2479

**Comment by daker** [comment]
An initial support for GLTF has been added, PBR requires WebGPU to work

https://kitware.github.io/vtk-js/examples/GLTFImporter/index.html?model=FlightHelmet&viewAPI=WebGPU

@floryst we can close the issue.
