### ISSUE TITLE
WebXR VR Examples are broken

### ISSUE THREAD

**Issue by tbirdso** [Kitware/vtk-js#2442]
### High-level description

The [VR](https://kitware.github.io/vtk-js/examples/VR.html) and [SkyboxViewer](https://kitware.github.io/vtk-js/examples/SkyboxViewer.html) examples appear to be nonfunctional. In both examples the stereoscopic camera views react improperly to headset movements and each eye even appears to drift independently while the headset is at rest.

### Steps to reproduce

1. Use a compatible HMD browser or following the developer notes in [vtk.js WebXR documentation](https://kitware.github.io/vtk-js/docs/develop_webxr.html) to install the Mozilla WebXR emulator in a compatible desktop browser
2. Navigate to the example
3. Launch in VR

### Detailed behavior

- Dual views drift independently
- Camera movement in each eye does not reflect headset movement
- Camera sometimes moves more rapidly when headset is in motion
- Camera sometimes drifts while headset is at rest

### Expected behavior

Stereoscopic views move together in response to headset movements

### Environment
- **vtk.js**:  `master`
- **OS**:  Windows 10, Oculus HMD (Android)
- **Browser**:  Chrome 101.0.4951.67, Oculus Browser

### Other Notes

Tested with both the Mozilla WebXR emulator and Meta Quest 2 HMD.

I have not made any recent changes in vtk.js so I am having to start from scratch on this investigation. Initial suspicion is that something changed in how we are handling camera parameters or 3D styles since the last time I touched these files.

WebXR AR applications are still fully functional.

**Comment by tbirdso** [comment]
cc @floryst

**Comment by tbirdso** [comment]
Verified that last stable commit is b5b1c22bca53547dfb4a124c29a1315ba74650ad, breaks in c84b5a08f3c4ea20f2e226761f13a705ca04b7f8

**Comment by tbirdso** [comment]
For the record, it looks like the error occurs when `computeLightTransform` from [https://github.com/Kitware/vtk-js/pull/2415](https://github.com/Kitware/vtk-js/pull/2415) is called, but I don't see any issues in that method itself. Something strange is going on in terms of how that block interacts with how we are setting the position in VR. Will continue to investigate.

**Comment by tbirdso** [comment]
Current hypothesis is that #2415 exposed some issues in VR rendering that already existed, such as where [vtkCamera.computeViewParametersFromPhysicalMatrix](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Camera/index.js#L466) does not explicitly set the view matrix that [computeCameraLightTransform](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Camera/index.js#L359) expects to find. Adjusting this results in correct behavior where the camera rotates with the HMD, though the camera position appears fixed at the origin.

**Comment by JiayiXuu** [comment]
> For the record, it looks like the error occurs when `computeLightTransform` from #2415 is called, but I don't see any issues in that method itself. Something strange is going on in terms of how that block interacts with how we are setting the position in VR. Will continue to investigate.

In short - to fix the issue, maybe try removing all the calls to `ComputeCameraLightTransform()` in `Core/Camera`. If this doesn't fix it, try removing the calls to `ComputeCameraLightTransform()` in `Core/Renderer`.

Long story: 
`ComputeCameraLightTransform()` only effects cameraLightMatrix, which supposedly calculate the transform matrix between camera and light in view space. The one thing I am sure about is that the current implementation of `ComputeCameraLightTransform()` is wrong, which is mentioned in [#2415](https://github.com/Kitware/vtk-js/pull/2415). We decided to come back the issue later because cameraLightMatrix is used only in one place, `updateLightsGeometryToFollowCamera()` in Core/Renderer. We thought it won't effect other code - apparently it does.

I can think of one thing that might break VR scene, `getViewMatrix()` is called in `ComputeCameraLightTransform()` and that might update view matrix at the wrong time.

**Comment by tbirdso** [comment]
Thanks for the background @JiayiXuu! I agree that the issue probably lies with the view matrix being updated unexpectedly. Removing the single `ComputeCameraLightTransform` call at [https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Camera/index.js#L75](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Camera/index.js#L75) seems to fix the issue. There may be a more long-term solution involving how the view matrix is set/updated in `computeViewParametersFromPhysicalMatrix` and `computeViewParametersFromViewMatrix`.

**Comment by JiayiXuu** [comment]
Created [#2447](https://github.com/Kitware/vtk-js/pull/2447) to fix the issue.
