### ISSUE TITLE
Improvements to reslicecursorwidget

### ISSUE THREAD

**Issue by Zhengyangzuishuai** [Kitware/vtk-js#2461]
I tried to use vtkcylindersource to replace vtkspheresource as the rotation point, so as to expand the area that can be rotated, but after continuous attempts, the following happens.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/43663302/172468921-d0727821-6d01-420a-a0e8-96e670ab3ed6.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/43663302/172468988-3c691b8d-f314-4f04-aa06-75f736d2b168.png">
It seems that the rotation of the cylindersource or spheresource is about their center, is there a solution that will allow me to rotate around the endpoint of the cylindersource instead of the endpoint

**Comment by Zhengyangzuishuai** [comment]
like this
<img width="695" alt="image" src="https://user-images.githubusercontent.com/43663302/172469697-bc6f97fd-6748-4032-9198-124d0ddc7b46.png">

**Comment by Zhengyangzuishuai** [comment]
![Uploading image.png…]()
In the end, I succeeded by changing the setcenter of the original spheresource to the setusermatrix of the cylindersource.

**Comment by Zhengyangzuishuai** [comment]
> yes, it seems to be related to the order of matrices multiplications.
> 
> By curiosity, why do you want to use a cylinder source ?

In fact, in terms of user experience, the accessible area of spheresource is too small, and I don't really need the function of translateaxis, so recently I have been trying to improve the crosshairs from our user experience.

**Comment by finetjul** [comment]
You might want simply to change the picking "radius" at [that line](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js#L264).

**Comment by Zhengyangzuishuai** [comment]
> You might want simply to change the picking "radius" at [that line](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js#L264).

Yes, I know this, but in the end from the ui aspect and from the perspective of looking at the picture, I chose to re-use the cylinder source instead of using the setsphereradius to expand the area of the four points, thank you for your help
