### ISSUE TITLE
ImageSlice not implemented 

### ISSUE THREAD

**Issue by ho9science** [Kitware/vtk-js#2488]
### High-level description

Hello, i’m beginer vtk.js using 24.18.7

I tried to convert a 2D image to 3D as in your [MultiSliceImageMapper example](https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html)
I found bug
and posted on discourse and got a [answer](https://discourse.vtk.org/t/how-to-add-vtkimageslice-for-addactor/8778/2?u=henry.min)

please consider this issue.

### Steps to reproduce

```
const renderer = fullScreenRenderWindow.getRenderer();
const imageActorI = vtkImageSlice.newInstance();
renderer.addActor(imageActorI);
```

### Detailed behavior

TypeScript error message:
TS2345: Argument of type 'vtkImageSlice' is not assignable to parameter of type 'vtkActor'.

imageSlice/index.d.ts
```
export interface vtkImageSlice extends vtkProp3D {
	/**
	 * 
	 */
	getActors(): any;
...
}
```
but ImageSlice/index.js
```
  publicAPI.getActors = () => publicAPI;
```

### Expected behavior

```
  publicAPI.getActors = () => {
     ...
  };
```

### Environment
- **vtk.js**: 24.18.7 
- **OS**: Windows 10
- **Browser**: Chrome 102.0.5005.115

**Comment by daker** [comment]
@ho9science could you check if it's issue is fixed?

**Comment by ho9science** [comment]
@daker It's works. thank you!!
