### ISSUE TITLE
MouseRangeManipulator swipe issue in touchscreen devices

### ISSUE THREAD

**Issue by zhangzhi93** [Kitware/vtk-js#2489]
### High-level description
when I use the MouseRangeManipulator to change the window width/window level in a touch screen device, after the sliding ends, the sliding again, the value is not continuously changed, the initial value will be reset. I don’t have this problem with a mouse on a pc. 

### Steps to reproduce
[MouseRangeManipulator Official example](https://kitware.github.io/vtk-js/examples/MouseRangeManipulator.html)，Open in touch screen device, or use pad simulator in chrome, swipe to modify window level/window width, each swipe will reset the value

### Environment
- **@kitware/vtk.js**: 24.19.0
- **OS**: windows 11
- **Browser**: Chrome  102.0.5005.115

**Comment by floryst** [comment]
This is fixed in #2516, which should be released soon.
