### ISSUE TITLE
Slow response on rendered STL model interactions

### ISSUE THREAD

**Issue by SimoneMazzola** [Kitware/vtk-js#2494]
### High-level description
I'm experiencing extremely slow responses on rendered STL model user interactions.
I have a React component rendering a variable number of STL models (_the performance issue is even happening when rendering only 1 STL model_).

### Steps to reproduce
<details>
  <summary>Below you can find the source code of the react component:</summary>
  
  ```
  import { Modal } from "react-bootstrap";
  import React, { useRef, useEffect } from 'react';
  import '@kitware/vtk.js/Rendering/Profiles/Geometry';
  
  import vtkActor from '@kitware/vtk.js/Rendering/Core/Actor';
  import vtkMapper from '@kitware/vtk.js/Rendering/Core/Mapper';
  import vtkOpenGLRenderWindow from '@kitware/vtk.js/Rendering/OpenGL/RenderWindow';
  import vtkRenderWindow from '@kitware/vtk.js/Rendering/Core/RenderWindow';
  import vtkRenderWindowInteractor from '@kitware/vtk.js/Rendering/Core/RenderWindowInteractor';
  import vtkRenderer from '@kitware/vtk.js/Rendering/Core/Renderer';
  import vtkProperty from '@kitware/vtk.js/Rendering/Core/Property';
  import vtkInteractorStyleTrackballCamera from '@kitware/vtk.js/Interaction/Style/InteractorStyleTrackballCamera';
  import vtkSTLReader from '@kitware/vtk.js/IO/Geometry/STLReader';
  import { convertToRGB, getColorInfo } from "../../utils/Common";
  
  
  export default function CaseModal({ setShowCaseModal, stlFile, layerinfo }) {
      const vtkContainerRef = useRef(null);
      const context = useRef(null);
  
      useEffect(() => {
          async function renderAll() {
              if (!context.current) {
                  const files = Object.fromEntries(Object.entries(stlFile).filter(([key, value]) => {return key.match(/Model\/./g)}).map(([key, value]) => {return [key.replace('Model/', ''), value]}))
                  const mappers = []
                  const actors = []
  
                  layerinfo.forEach(layer => {
                      const { color_hex, opacity_percentage } = getColorInfo(layer.material_color)
                      const color_rgb = convertToRGB(color_hex)
                      const reader = vtkSTLReader.newInstance();
                      const mapper = vtkMapper.newInstance({ scalarVisibility: false });
                      const actor = vtkActor.newInstance();
                      const property = vtkProperty.newInstance();
                      property.setOpacity(opacity_percentage/100)
                      property.setColor(color_rgb[0]/255, color_rgb[1]/255, color_rgb[2]/255)
                      mapper.setInputConnection(reader.getOutputPort());
                      actor.setProperty(property)
                      actor.setMapper(mapper);
                      reader.parseAsArrayBuffer(files[layer.file_name].buffer)
                      mappers.push(mapper)
                      actors.push(actor)
                  });
  
                  const renderWindow = vtkRenderWindow.newInstance();
                  const renderer = vtkRenderer.newInstance({ background: [0.2, 0.3, 0.4] });
                  renderWindow.addRenderer(renderer);
  
  
                  actors.forEach(actor => {
                      renderer.addActor(actor);
                  })
                  renderer.resetCamera();
  
                  const openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
                  renderWindow.addView(openglRenderWindow);
                  const container = vtkContainerRef.current;
                  openglRenderWindow.setContainer(container);
                  const { width, height } = container.getBoundingClientRect();
                  openglRenderWindow.setSize(width, height);
                  const interactor = vtkRenderWindowInteractor.newInstance();
                  interactor.setView(openglRenderWindow);
                  interactor.initialize();
                  interactor.bindEvents(container);
                  interactor.setInteractorStyle(vtkInteractorStyleTrackballCamera.newInstance());
                  renderWindow.render();
  
                  context.current = {
                      renderer,
                      actors,
                      mappers,
                  };
              }
              return () => {
                  if (context.current) {
                      const { renderer, actors, mappers } = context.current;
                      actors.forEach(actor => {
                          actor.delete()
                      });
                      mappers.forEach(mapper => {
                          mapper.delete()
                      });
                      renderer.delete();
                      context.current = null;
                  }
              };
          }
          renderAll()
      }, [context, vtkContainerRef, layerinfo, stlFile]);
  
      return (
          <Modal fullscreen={true} show={true} onHide={() => setShowCaseModal(false)}>
              <Modal.Header closeButton>
                  <Modal.Title className="primary-600">Case viewer</Modal.Title>
              </Modal.Header>
              <Modal.Body id="case-modal">
                  <div className="h-100">
                      <div className="h-100" ref={vtkContainerRef} />
                  </div>
              </Modal.Body>
          </Modal>
      );
  }
  ```
</details>

### Current behavior
It seems like a GPU related issue, since it's only happening using chrome in combination with iMac.
The problem is not happening using other browsers on the same iMac or using the same chrome version on other devices (even other apple computers, like macbook).
We got many of this iMac and it's happening on all of them when using chrome.

https://user-images.githubusercontent.com/26705905/176415437-d2c70cf9-8beb-465c-b420-9579139e8278.mp4

### Environment
- vtk node module: @kitware/vtk.js: 24.18.2
- browser: Version 103.0.5060.53 (Official Build) (x86_64)
- OS: macOS Monterey version 12.4
- device: iMac (Retina 4K, 21.5-inch, 2017)
  - GPU: Radeon Pro 555 2 GB
  - Processor: 3,6 GHz Quad-Core Intel Core i7
  - Memory: 8 GB 2400 MHz DDR4

**Comment by daker** [comment]
Do you have the same issue with the [STLReader example](https://kitware.github.io/vtk-js/examples/STLReader/index.html)? Maybe try opening the performance tab and launch a record, once done share the json(using the arrow button) or screenshot the call stack.
![image](https://user-images.githubusercontent.com/878518/176422233-36377822-2269-46d6-a6f3-96fcba516cef.png)

**Comment by SimoneMazzola** [comment]
Ok, now the performance profile report download worked. [Here's the full JSON](https://drive.google.com/file/d/1U7pThbictVNEBmGN32LxW4kQrHq3cNzi/view?usp=sharing) (had to host it separately, because it's too long for a github comment)

The issue is also happening with [this STL](https://cdn.thingiverse.com/assets/9f/d1/01/07/76/articulated_axolotl_2.stl), I downloaded randomly from thingiverse.

**Comment by SimoneMazzola** [comment]
Thank you @floryst!
Hope to hear from you soon.

**Comment by floryst** [comment]
Checkout the branch at #2484, and run the following to get a local build of the STLReader. Let me know if those changes fix your issue on your platform configuration.

```
npm install
npm run example -- STLReader
# visit http://localhost:999/ for a local build of the STLReader example
```

**Comment by floryst** [comment]
Your latest profile contains mostly off-thread processing that devtools cannot seem to identify, which makes me wonder if Chrome or the GPU is doing something inefficient.

Do other online 3D STL viewers have the same issue? e.g. https://3dviewer.net/. I'm trying to gauge if this is a GPU + platform bug, or a bug specific to vtk.js.

**Comment by SimoneMazzola** [comment]
Same performance issue on [https://3dviewer.net/](https://3dviewer.net/), even with smaller STL (around 5MB) that were working smoothly on [STLReader example](https://kitware.github.io/vtk-js/examples/STLReader/index.html).

**Comment by floryst** [comment]
Looks like it's a Chrome issue. If you visit `chrome://gpu` and copy the report here, we may be able to see what is wrong. I don't think it could be software rendering, but that page will tell you if you are using hardware acceleration or not. If the GPU is not being blacklisted, I would recommend posting a Chrome bug report.

**Comment by SimoneMazzola** [comment]
Here's the report, hope it helps:
[gpu report.pdf](https://github.com/Kitware/vtk-js/files/9019879/gpu.report.pdf)

**Comment by daker** [comment]
@SimoneMazzola can you do this test and see if it does solve the issue ? go to about:flags in Chrome, "Choose ANGLE graphics backend", and choose "Metal", restart the browser then do the test again

**Comment by SimoneMazzola** [comment]
I confirm that setting "Choose ANGLE graphics backend" on "Metal" the issue is not happening anymore.

**Comment by floryst** [comment]
Closing this as resolved with the previous comment.
