### ISSUE TITLE
Potential typo in Utilities/ParaView/export-scene-macro.py

### ISSUE THREAD

**Issue by dasmy** [Kitware/vtk-js#2499]
I assume, this file is deprecated. However, while trying to learn from the code, I came across the line https://github.com/Kitware/vtk-js/blob/6ae17f80c8496191d5439eaf746eac772a40450b/Utilities/ParaView/export-scene-macro.py#L244 .

Shouldn't it be `cd.GetNumberOfArrays()` instead of `pd.GetNumberOfArrays()`?

**Comment by patrickoleary** [comment]
Shouldn't it be cd.GetNumberOfArrays() instead of pd.GetNumberOfArrays()?

**Comment by dasmy** [comment]
> Shouldn't it be cd.GetNumberOfArrays() instead of pd.GetNumberOfArrays()?
> […](#)

Opps, fixed my typo. Thanks :-)

**Comment by finetjul** [comment]
Hi dasmy, I think you are right. can you please make PR ?

**Comment by dasmy** [comment]
Hi @finetjul,
As I needed some more fixes / additions to the macro (see https://discourse.paraview.org/t/trouble-exporting-scene-to-vtkjs/9829/10 for the full story), I did several additional modifications, see https://github.com/dasmy/export-scene-macro .

Does it make sense to discuss them and create a composite PR or should I for now only address the change mentioned above?

**Comment by DavidBerger98** [comment]
Hi @dasmy,

Thank you for opening this issue and suggested changes.

You can create one PR with your changes from the discussion and the fixed typo. Linking the discourse thread and this issue in the PR should be enough.

I am pinging @jourdain in case he wants to add anything to the discussion.

Best,

David

**Comment by jourdain** [comment]
I'm good pushing that macro forward. In general. It is a "deprecated path" now that we have a more mainstream C++ one. But it is definitely an easier path for the community to contribute and extend it to better fit their needs.
