### ISSUE TITLE
Is vtk.js support VTK C++ WASM export polydata?

### ISSUE THREAD

**Issue by supriome** [Kitware/vtk-js#2501]
I use VTK C++ Emscripten to compile some function to use in front-end, here is my code 

```
// fetch a vtk file
const res = await fetch('/result-2.vtk');
const fileData = await res.text();

// Create a virtual file
Module.FS.createDataFile("/", 'result.vtk', fileData, true, true);

// define vtkUnstructuredGridReader reader
const reader = new Module.vtkUnstructuredGridReader();
reader.SetFileName('result.vtk');
reader.Update();
Module.FS.unlink("/result.vtk");

// Create a filter to convert vtkUnstructuredGrid file to vtkPolyData
const geometryFilter = new Module.vtkGeometryFilter();
geometryFilter.SetInputConnection(reader.GetOutputPort());
geometryFilter.Update();

// get vtkPolyData
const polydata = geometryFilter.GetOutput();
```

First fetch a vtk unstructruedgrid file from server, then use wasm filesystem to create a virtual file which will read by vtkUnstructuredGridReader, then use vtkGeometryFilter to convert file to vtkPolyData.

I want this polydata used by vtk.js. And use vtk.js mapper/Actor/Renderer to render this polydata. But i failed.

```
// Use vtk.js fullscreen render window to render the clipped actor
const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance();

const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();

const mapper = vtkMapper.newInstance();
mapper.setInputData(polydata);
// mapper.setInputConnection(reader.GetOutput());
// mapper.setInputConnection(polydata);

const actor = vtkActor.newInstance();
actor.setMapper(mapper);

renderer.addActor(actor);
    
renderer.resetCamera();
renderWindow.render();
```

Here is the error screenshot. `Uncaught (in promise) TypeError: input.getBounds is not a function`

<img width="885" alt="image" src="https://user-images.githubusercontent.com/19944032/177121740-5b6bd0e1-0241-4914-857a-9e8bb6e9c817.png">

I guess error maybe occur because vtk C++ polydata is base on `VtkDataObject`, but vtk.js `polydataMapper` is javascript rewrite.

**Comment by supriome** [comment]
#976

**Comment by jourdain** [comment]
You need to convert your C++ polydata into vtk.js/polydata which should be somewhat straight forward as it should just be dealing with typed arrays binding.

**Comment by supriome** [comment]
@jourdain Do you mean to bind the function methods in [vtk.js/polydata](https://kitware.github.io/vtk-js/api/Common_DataModel_PolyData.html) to the public functions in [VTK C++/Polydata](https://vtk.org/doc/nightly/html/classvtkPolyData.html) one by one?

![image](https://user-images.githubusercontent.com/19944032/177294044-74692d09-5900-494f-a34a-b02e6ed0e773.png)

Just like this? Javascript side `buildCells` to C++ side `BuildCells`?

**Comment by supriome** [comment]
[itk-wasm](https://github.com/InsightSoftwareConsortium/itk-wasm) is the combination of itk and webassembly, is there some way to read C++ polydata directly?

**Comment by supriome** [comment]
I also have an issue maybe related to you on gitlab [VTK C++ Emscripten Binding Config](https://gitlab.kitware.com/vtk/vtk/-/issues/18592#note_1211920)

**Comment by jourdain** [comment]
I mean you should not do what you are suggesting. Mapping methods could work but would be tricky and might require too much work while not necessary working. It should be easier to rebuild your JS polydata as long as you can get a wasm pointer to the data array and map it to a typed array. Itk-wam is most likely doing something like that.

**Comment by supriome** [comment]
Hi @jourdain ,

I finally implemented the conversion of unstructured grids to polydata through C++ wasm. Here is my code.

```
// fetch an unstructured grid vtk file
const res = await fetch('/result.vtk');
const fileData = await res.text();

// Create a virtual file
Module.FS.createDataFile("/", 'result.vtk', fileData, true, true);

// define vtkUnstructuredGridReader reader
const reader = new Module.vtkUnstructuredGridReader();
reader.SetFileName('result.vtk');
reader.Update();
Module.FS.unlink("/result.vtk");

// Create a filter to convert vtkUnstructuredGrid file to vtkPolyData
const geometryFilter = new Module.vtkGeometryFilter();
geometryFilter.SetInputConnection(reader.GetOutputPort());
geometryFilter.Update();

// get vtkPolyData
const polydata = geometryFilter.GetOutput();

// use vtkXMLPolyDataWriter to write a vtp file.
const writer = new Module.vtkXMLPolyDataWriter();

// output an string rather than a file
writer.SetWriteToOutputString(true);

writer.SetInputData(polydata);
writer.Write()

// then get vtp data by getoutputstring
const str = writer.GetOutputString();

// Then this str could load by vtk.js polydata reader
const vtpReader = vtkXMLPolyDataReader.newInstance();

const binary = new TextEncoder().encode(str);
vtpReader.parseAsArrayBuffer(binary);

const source = vtpReader.getOutputData(0);

// finally a normal vtk.js render process
const mapper = vtkMapper.newInstance();
const actor = vtkActor.newInstance();

actor.setMapper(mapper);
mapper.setInputData(source);
renderer.addActor(actor);
```

**Comment by Ricco8** [comment]
> Hi [@jourdain](https://github.com/jourdain) ,
> 
> I finally implemented the conversion of unstructured grids to polydata through C++ wasm.

Hello, I am facing the same problem. How did you solve it?
