### ISSUE TITLE
Cell Picking no longer working on vtk.js 25.X

### ISSUE THREAD

**Issue by WesleyTheGeolien** [Kitware/vtk-js#2508]
### High-level description
After updating from vtk.js@24.3.1 (I think later versions of 24.X still works) to vtk.js@25.1.3 Cell picking for quads are no longer working.

This looks to be due to #2394 and in particular due to `createCellMap` in `Sources/Rendering/Core/CellPicker/index.js`. The new implementation create a cell mapping which only specifies Lines, PolyLines or Triangles, however in `Sources/Common/DataModels/Constants` there are a number of other possible cell types

### Steps to reproduce
Create a Poly Data object composed of vtkQuads.

### Expected behavior
Expected to be able to pick as before

### Environment
- **vtk.js**: 25.1.3
- **OS**: MacOS 12.4
- **Browser**: Firefox developper 103.0b2 (64-bit)

**Comment by finetjul** [comment]
You can triangulate your mesh before doing picking.

But the best would be to port [vtkQuad](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Common/DataModel/vtkQuad.h) into VTK.js. You can see how it was done for vtkTriangle.

Fancy contributing vtkQuad ?

**Comment by finetjul** [comment]
Closed by #2515
