### ISSUE TITLE
OBJ Reader appends "index.obj" to URLs

### ISSUE THREAD

**Issue by zachmullen** [Kitware/vtk-js#252]
My OBJ file lives at a URL that does not end in ".obj", and this is causing the reader to append "index.obj" to the end of the URL. This was unexpected behavior to me, is there a way to instruct the reader not to add this to the URL?

**Comment by jourdain** [comment]
Yes by using { fullpath: true } as option in the setUrl.

See https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Misc/OBJReader/index.js#L182-L183

**Comment by zachmullen** [comment]
Great, thanks!

**Comment by jourdain** [comment]
BTW if you are doing some generic girder plugin, you might want to use [StandaloneSceneLoader](https://kitware.github.io/vtk-js/examples/StandaloneSceneLoader.html) as it is use [here](https://kitware.github.io/vtk-js/examples/StandaloneSceneLoader/index.html?fileURL=https://data.kitware.com/api/v1/file/5878eb978d777f05f44b1427/download) with girder and is also meant to load OBJ file.

**Comment by zachmullen** [comment]
Thanks for the tip, I actually have a minimal setup working now with the following:


        const renderWindow = vtkRenderWindow.newInstance();
        const renderer = vtkRenderer.newInstance();
        renderWindow.addRenderer(renderer);

        const reader = vtkObjReader.newInstance();
        const mapper = vtkMapper.newInstance();
        mapper.setInputConnection(reader.getOutputPort());
        const actor = vtkActor.newInstance();
        actor.setMapper(mapper);
        renderer.addActor(actor);

        const container = this.$('.g-surface-viewer-container')[0];
        const glwindow = vtkOpenGLRenderWindow.newInstance();
        glwindow.setContainer(container);
        renderWindow.addView(glwindow);

        const interactor = vtkRenderWindowInteractor.newInstance();
        interactor.setView(glwindow);

        reader.setUrl(this.model.downloadUrl(), {fullpath: true}).then(() => {
            renderer.resetCamera();
            renderWindow.render();

            interactor.initialize();
            interactor.bindEvents(container);
        });

<img width="579" alt="screen shot 2017-05-23 at 2 11 34 pm" src="https://cloud.githubusercontent.com/assets/555959/26369137/c618af8c-3fc1-11e7-8b05-e91e6c22ae61.png">

**Comment by jourdain** [comment]
Awesome! Thanks for sharing...
