### ISSUE TITLE
TestVolumeTypes Example shader compile error with 2+ components

### ISSUE THREAD

**Issue by PaulHax** [Kitware/vtk-js#2520]
### High-level description
TestVolumeTypes example has shader compile error with 2+ components.

### Steps to reproduce
Go here:
https://kitware.github.io/vtk-js/examples/TestVolumeTypes.html

Increase components to 2.

### Detailed behavior
The error:
```
': ERROR: 0:1084: 'normalLight' : undeclared identifier
ERROR: 0:1084: 'applyLightingDirectional' : no matching overloaded function found
ERROR: 0:1084: '=' : dimension mismatch
ERROR: 0:1084: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'
```

Does not happen if Lighting unchecked.

### Environment
- **OS**: Ubuntu 22.04
- **Browser**: Chrome 103

**Comment by floryst** [comment]
FYI @JiayiXuu, this looks like a lighting issue. Not sure from what, yet.

@PaulHax, can you bisect to the commit to figure out where things went wrong?

**Comment by PaulHax** [comment]
I think this is where the trouble starts: 4155c207cca4e4ae554cdc9efa39b125ff39a886

**Comment by JiayiXuu** [comment]
Thanks for spotting that! Will push fix by tomorrow.
