### ISSUE TITLE
WebXR not running 'Failed to create XR session!'

### ISSUE THREAD

**Issue by moi1882** [Kitware/vtk-js#2558]
Hi all,
Let me know if you are experiencing the same.
Laurent

### High-level description
The XR sessions cannot launch on 2 different computers on firefox and chrome. They were running few weeks ago.

### Steps to reproduce
Home made code as well as VTK.js VR/AR examples are affected:
https://kitware.github.io/vtk-js/docs/develop_webxr.html

### Detailed behavior
The scene launches, but the console throws an error message: 
Uncaught (in promise) Error: Failed to create XR session!

### Expected behavior
rendering VR/AR content using the WebXR extension

### Environment
- **vtk.js**: most recent one
- **OS**: Windows 10
- **Browser**: Chrome and firefox

**Comment by floryst** [comment]
Thanks for the report. I know where this is coming from.
