### ISSUE TITLE
TubeFilter over allocating output points

### ISSUE THREAD

**Issue by WesleyTheGeolien** [Kitware/vtk-js#2559]
### High-level description
It appears that in certain cases (haven't pin pointed the exact cases) that the vtkTubeFilter overallocates output points array. This leaves trailing 0's at the end of the array, consequently causing problems on the `getBounds()` call

### Steps to reproduce
As stated before I am not entirely sure on what inputs  / where the difference comes between the two calculations (I havent looked in too much detail either though ... ) but I can provide points and lines that cause this issue if needed.

### Detailed behavior
There appears to be a difference between the calculation of newNumPts: line: https://github.com/Kitware/vtk-js/blob/24de4f815199a6ae1cab05a06b5e1593877d771a/Sources/Filters/General/TubeFilter/index.js#L634 and the filling of the array in generatePoints. I propose to change the calculations in the forLoop to simply setting the offset and incrementing it (the same that is done in generatePoints (I'd be happy to put together the PR for this)

### Expected behavior
Not to have trailing 0s at the end of the Array that havent been allocated

### Environment
- "@kitware/vtk.js": "^25.7.2",
- **OS**: MacOSX 12.5
- **Browser**: Firefox dev 104

**Comment by WesleyTheGeolien** [comment]
Hmm so some further quick testing and looking at the different codes, it looks like `npts` is updated in the wrong place, eg. after calculating the number of points and not before: https://github.com/Kitware/vtk-js/blob/24de4f815199a6ae1cab05a06b5e1593877d771a/Sources/Filters/General/TubeFilter/index.js#L645

**Comment by finetjul** [comment]
I do not know if that helps, but you can also call `.subarray()` to remove trailing 0s.

**Comment by WesleyTheGeolien** [comment]
@finetjul potentially though the last point could be 0,0,0 by design in which case this would be removed creating an erroneous array
