### ISSUE TITLE
Setting a model variable as object always trigger modified()

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#2575]
### High-level description
If `macro.set(publicAPI, model, ['foo']);` and `foo` is an `Object` (e.g. `{a: 1, b: 2}`, then calling `setFoo({a: 1, b:2})` will always trigger `modified()`.

### Steps to reproduce
```
extend(...){
  macro.set(publicAPI, model, ['foo']);
}
...
myobj.setFoo({a: 1, b: 2});
myobj.getMTime(); // =>1234
myobj.setFoo({a: 1, b: 2});
myobj.getMTime(); // =>1235
```

See [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js#L239) for a performance hit that modifies a WidgetRepresentation each time the mouse is moved which will always `requestData()` on the widget representation

### Detailed behavior
This is because `macro.setter()` does a shallow equal comparison `if (model[field] !== value) {` instead of a deep equal.

### Expected behavior
I can see 2 options:
 - Add deep equal check if `value` is an object in `macro.setter()`
 - Create `macro.setObject(publicAPI, model, ['foo']);` convenient setter similar to `macro.setArray()`

### Environment
- **vtk.js**:  master

**Comment by floryst** [comment]
I think we can add a flag to the setter for performing a deep equals check. `macro.setObject` doesn't make much sense to me over `macro.set/macro.setGet`, since nothing about the generated API is different (unlike for arrays).

**Comment by floryst** [comment]
These flags should be off by default, to preserve the current behavior (unless the current behavior is deemed "buggy").

For the getter, do you suppose a deep copy makes more sense, or a shallow copy? If the purpose of the copy is to prevent inadvertent editing of the underlying object, then a deep copy may make more sense. Only issue would be potential perf issues, and that we should also ignore copying of frozen objects.
