### ISSUE TITLE
Performance regression in ImageCroppingWidgetExample

### ISSUE THREAD

**Issue by PaulHax** [Kitware/vtk-js#2618]
### High-level description
Clicking and rotating ImageCroppingWidgetExample is slower after https://github.com/Kitware/vtk-js/commit/b85167c177e3ddd292c1a8ed6e7967b3a2084c49 

In one comparison, mouse orbit task update takes ~5ms on master.  With commit right before https://github.com/Kitware/vtk-js/commit/b85167c177e3ddd292c1a8ed6e7967b3a2084c49  mouse orbit task takes ~1ms.

### Steps to reproduce
Run ImageCroppingWidgetExample on branch master, record performance via devtools, rotate camera with mouse.  Compare task time with 93e74fcd9edb4d35f8301fa2620df89affcb6b43 <- good one right before trouble commit.

### Detailed behavior

WidgetManager.updateDisplayScaleParams called many times every frame.

### Environment
- **vtk.js**: 25.12.0

**Comment by finetjul** [comment]
Would you say it is slow because of the "deepEqual()" comparison that is performed many times ?

I'm not sure why `updateDisplayScaleParams()` is called many times. It should be called only when camera or renderWindow is modified.

**Comment by PaulHax** [comment]
The `deepEqual` calls take majority of time in `updateDisplayScaleParams`.  Camera and renderWindow/Framebuffer are modified more than once each frame when rotating with mouse. https://github.com/Kitware/vtk-js/blob/5495580f6790846d8180cb802cb007022d860ef9/Sources/Rendering/OpenGL/RenderWindow/index.js#L1317-L1321

**Comment by finetjul** [comment]
Good catch, `activeFramebuffer` should not call `modified`, maybe create a new event instead for those who want to observe `activeFramebufferChanged` event.

**Comment by PaulHax** [comment]
The performance regression is gone with addition of `fast-deep-equal` in 085ad94cabb8fd958ee5501aaa28b75bdb2adb25.
