### ISSUE TITLE
Can't use @kitware/vtk.js with Next.js

### ISSUE THREAD

**Issue by Zeng95** [Kitware/vtk-js#2626]
### High-level description

Next.js is unable to parse the library and throwing an error.

### Steps to reproduce

1. Open the link [vtk-nextjs-codesandbox](https://codesandbox.io/p/sandbox/vtk-nextjs-9i5szf)
2. There's an error showing on https://9i5szf-3000.preview.csb.app/

### Detailed behavior

![image](https://user-images.githubusercontent.com/12603244/200997933-ec4f4a30-1ee6-4317-a09d-4c0eae1624dc.png)
```js
SyntaxError: Cannot use import statement outside a module
```

### Expected behavior

Next.js should be able to import the library without an error.

### Environment
- **vtk.js**:  25.13.0
- **OS**:  macOS Monterey 12.6 (21G115)
- **Browser**:  Chrome 108.0.5326.0 (Developer Build) (arm64)

**Comment by YeonHoJeong** [comment]
Transfiles are required when loading "vtk.js" from "next.js".
[show next.config.js & pacakge.json ](https://codesandbox.io/p/sandbox/vtk-nextjs-forked-lfd05s?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A39%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A4%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000olpge36cd7kfk%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522url%2522%253A%2522lfd05s-3001.preview.csb.app%2522%252C%2522key%2522%253A%2522claatfqq902ku3b6lb8ufccb0%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522claat771c003dl1ge4rf39pdl%2522%252C%2522key%2522%253A%2522claat76oc019i3b6lg3wrk3cf%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522claat386300er3b6lojjsnbd5%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

However, solving this will probably lead to other errors.

If you look at the [RenderWindow code in Vtk.js](https://kitware.github.io/vtk-js/api/Rendering_Core_RenderWindow.html), there is a part that checks what the GPU API is through Navigator.

In next.js, global objects (Navigator, window, ...etc) is not accessible An error will appear.

in my opinion If you want to rend a Volume Image, etc. on the Server Side like SSR, you should look for examples such as Remote Render.

**Comment by Zeng95** [comment]
> 

Good point. It looks like it has something to do with SSR

I solved the issue by using **Dynamic Import** [With no SSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr)

**Comment by Zeng95** [comment]
> Transfiles are required when loading "vtk.js" from "next.js". [show next.config.js & pacakge.json ](https://codesandbox.io/p/sandbox/vtk-nextjs-forked-lfd05s?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A39%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A4%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000olpge36cd7kfk%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522url%2522%253A%2522lfd05s-3001.preview.csb.app%2522%252C%2522key%2522%253A%2522claatfqq902ku3b6lb8ufccb0%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522claat771c003dl1ge4rf39pdl%2522%252C%2522key%2522%253A%2522claat76oc019i3b6lg3wrk3cf%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522claat386300er3b6lojjsnbd5%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)
> 
> However, solving this will probably lead to other errors.
> 
> If you look at the [RenderWindow code in Vtk.js](https://kitware.github.io/vtk-js/api/Rendering_Core_RenderWindow.html), there is a part that checks what the GPU API is through Navigator.
> 
> In next.js, global objects (Navigator, window, ...etc) is not accessible An error will appear. (Alternatively, "vtk.js" must be available when it reaches the client side.)
> 
> in my opinion If you want to rend a Volume Image, etc. on the Server Side like SSR, you should look for examples such as Remote Render.

Good point. It looks like it has something to do with SSR.

I solved the issue by using Dynamic Import [With no SSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr).

**Comment by daker** [comment]
@Zeng95 can you close the issue if you have managed to solve it?
