### ISSUE TITLE
There is a bug in class LandmarkTransform?

### ISSUE THREAD

**Issue by huge818** [Kitware/vtk-js#2632]
### Environment
- **vtk.js**:    25.13.1
- **OS**: windows
- **Browser**:  chrome 102

http://kitware.github.io/vtk-js/api/Common_Transform_LandmarkTransform.html

const transform = LandmarkTransform.New();
transform.setMode(Mode.RIGID_BODY);
transform.setSourceLandmark(…); // vtkPoints
transform.setTargetLandmark(…); // vtkPoints
transform.update();
const transformMatrix = transform.getMatrix();

my found the veision is 25.13.1 , the other version i did not test.

This line  "transform.update();"  run error.

there is a varibale  need initialization。  It is recommended to fix this bug

thanks

**Comment by finetjul** [comment]
Would you mind pasting the error log ?
Alternatively, feel free to submit a fix :-)

**Comment by huge818** [comment]
the bug in  "version": "27.1.2"

error log :
index.js:191 Uncaught TypeError: Cannot set properties of undefined (setting '0')
    at e.update (index.js:191:14)
    at vtk.html:79:13

notice:; the error in :

vtk.js\Sources\Common\Transform\LandmarkTransform\index.js

line 168 and line 169, varibale rs rt is Array, but  not initialization

        let ds;
        let dt;

it is must be 
        let ds =[];
        let dt = [];

Please repair it as soon as possible， thanks very much!
