### ISSUE TITLE
TypeError: Failed to construct ‘XRWebGLLayer’ HoloLens 2

### ISSUE THREAD

**Issue by will-3ds** [Kitware/vtk-js#2650]
### High-level description
We are experiencing issue with vtk.js examples on a HoloLens 2

### Steps to reproduce
Access any vtk.js AR example via HoloLens 2 Edge browser

### Detailed behavior
When starting an AR session from any vtk.js example directly from the HoloLens 2, we got this error:
`Uncaught (in promise) TypeError: Failed to construct ‘XRWebGLLayer’: The provided value is not of type ‘(WebGL2RenderingContext or WebGLRenderingContext)’`

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/118812869/205026648-b4d85347-3d52-4cc6-afcf-4ed43ff18f16.png)

It should be noted that AR examples with three.js and babylon.js are both working fine.

### Expected behavior
AR session should launch without issue

### Environment
- **vtk.js**: Version used on vtk.js AR example page
- **OS**: Windows Holographic OS
- **Browser**: Edge 107.0

**Comment by floryst** [comment]
FYI @tbirdso

**Comment by floryst** [comment]
#2653 should fix your issue.
