### ISSUE TITLE
Radon Transformation Scaling Issue

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#2658]
### High-level description
The Radon Transform blend mode does not work if the texture data is Float32Array.

![image](https://user-images.githubusercontent.com/7490180/206624816-8a28323a-f438-41f7-9414-3bc946c3281c.png)
 

### Steps to reproduce
In the [`VolumeMapperBlendMode` example](https://github.com/Kitware/vtk-js/blob/master/Examples/Volume/VolumeMapperBlendModes/index.js#L45), comment out the line that forces the scalar texture be HalfFloat (setPreferSizeOverAccuracy makes the scalar texture half float)

### Detailed behavior
It seems like the code written for radon transform has some wrong assumption for the scaling. 

The [code in the shader](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L1468) for the Radon transform uses some scaling which would fail if the data type is Float32Array. 

I tried changing the 

`gl_FragData[0] = texture2D(ctexture, vec2(normalizedRayIntensity * cscale0 + cshift0, 0.5));` 

to 

`gl_FragData[0] = texture2D(ctexture, vec2(normalizedRayIntensity, 0.5));` 

and it works. So there is something going on with the color texture scale and offset.

### Expected behavior
The Radon transform should work regardless of data type

**Comment by finetjul** [comment]
I did not follow the HalfFloat issue/discussion.

What are those `cscale0`/`cshift0` uniforms for ?

Does removing them from the radon blend functions not break the case where data type is integer ? 
What about the `oscale0`/`oshift0` uniforms ?

**Comment by sedghi** [comment]
@finetjul I updated the description. As I understand, cscale0/cshift0 are the color texture scale and offset which maps the sampled texture value to the ctable (color texture table).

I think we can focus on the Float32Array for now, and see the problem there, and later deal with the Int16 case. 

Based on my investigations the scale and offset for HalfFloat is 0, 1 while for the Float32Array is 0 and the volumeMax ([here](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/Texture/index.js#L1269-L1270))

**Comment by finetjul** [comment]
> I think we can focus on the Float32Array for now, and see the problem there, and later deal with the Int16 case.

I'm confused, the Radon transform is currently working fine for the Int16 case. I just do not want to make it stop working by adding Float32 support.
Did I misunderstood something ?

**Comment by sedghi** [comment]
Where are you seeing the Radon transform working for the Int16 case? It is failing for Int16 (which I'm adding support [here](https://github.com/Kitware/vtk-js/pull/2058) you can see the Radon is wrong in the description of that PR, but I it is not merged, so I created this issue for the already existing Float32). 

Does vtk.js has support for Int16 other than what I'm adding in that PR?
