### ISSUE TITLE
HardwareSelector "Error linking shader fragment..."

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2659]
### High-level description
I have a bunch of spheres produced by `vtkSphereMapper`. I'm trying to use `hardwareSelector` to pick single spheres. An error is returned in the console `Error linking shader FRAGMENT varying vertexIDVSOutput does not match any VERTEX varying`

### Steps to reproduce
See [this codesandbox](https://codesandbox.io/s/vtk-react-mst-f1xyml?file=/src/scene/SceneManager.tsx:2954-2969)

### Detailed behavior
![image](https://user-images.githubusercontent.com/47977073/207601860-c1b8a85e-104a-4f02-a25b-ac33be03fa58.png)

### Environment
- **vtk.js**: 25.15.0
- **OS**: Mac Ventura 13.0
- **Browser**: Safari Version 16.1 (18614.2.9.1.12)

**Comment by finetjul** [comment]
Indeed, the hardware selector is currently ONLY supporting `vtkPolyDataMapper`.

**Comment by jourdain** [comment]
@finetjul the GlyphMapper is working fine with the Hardware selector as well.

**Comment by zbouslikhin** [comment]
Hello @jourdain,

I gave it a shot once again, but it still returns the same error: `Error linking shader FRAGMENT varying vertexIDVSOutput does not match any VERTEX varying`

Link to the sandbox [here](https://codesandbox.io/s/spheremapper-hardwareselector-f1xyml)

**Comment by zbouslikhin** [comment]
@jourdain @finetjul is there any update for this one? Same error is returned when using `vtkImplicitPlaneWidget`

**Comment by jourdain** [comment]
Like previously mentioned the hardware picking is not working with that mapper. Such feature needs to be added.
If its a priority for you, feel free to [reach out to Kitware](https://www.kitware.com/contact/) for implementing such capability.
