### ISSUE TITLE
Add BigInt64 and BigUint64Array  support

### ISSUE THREAD

**Issue by banesullivan** [Kitware/vtk-js#2693]
### Need

`BigInt64Array` is now supported in JS. Can this be added to VTK.js? 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array

Having issues converting `int64` (`VTK_LONG_LONG`) from VTK to VTK.js

https://github.com/Kitware/trame-vtk/issues/21

### Feature

Add support for `BigInt64Array` and `BigUint64Array`

**Comment by jourdain** [comment]
I'm pretty sure they are already supported. We just rely on the native JS type and add the time those didn't existed.
