### ISSUE TITLE
ImplicitPlaneWidget: documented, but missing set/get <component>Visible

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2702]
### Detailed behavior
There are some functions in the `implicitPlaneWidget` that are documented, but are not implemented.
See [doc](https://kitware.github.io/vtk-js/api/Widgets_Widgets3D_ImplicitPlaneWidget.html)

### Environment
- **vtk.js**: 26.2.0
- **OS**: Windows 10
- **Browser**: Chrome Version 109.0.5414.119 (Official Build) (64-bit)

**Comment by zbouslikhin** [comment]
Perhaps this is not a bug. The object returned after placing the widget `widgetManager.addWidget(clipPlane)` contains those functions. 
I'll leave this issue open until confirmation.

**Comment by jourdain** [comment]
Visibility is indeed specific to the view it is on. And the current infrastructure let you share a widget across views and therefore should allow you to show/hide each of its representation across the various views it has been added to.
