### ISSUE TITLE
Renderer background alpha value

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2705]
### High-level description
renderer = vtkRenderer.newInstance()
renderer.setBackground(0, 0, 0, 0)

The last parameter sets the alpha value. This seems to be nowhere documented. It also returns a typescript error.

### Environment
vtk.js: 26.2.0
OS: Windows 10
Browser: Chrome Version 109.0.5414.119 (Official Build) (64-bit)

**Comment by jourdain** [comment]
The TypeScript definition is indeed missing it.

**Comment by Julesdevops** [comment]
https://github.com/Kitware/vtk-js/commit/2da9e2bdd4aa40f9be30a7e5826a9a33eaf9fee6 should fix that

**Comment by floryst** [comment]
Closing this since it's now fixed.
