### ISSUE TITLE
Online VolumeMapper examples crash

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#2717]
### High-level description
The online examples for volume mapper crashes. The browser (chrome and edge) turns blank and then turns back to original state but inspect shows errors for reading `isAttributeUsed` 

### Steps to reproduce
Open any volume mapper example such as https://kitware.github.io/vtk-js/examples/VolumeClipPlane.html

### Detailed behavior
Tab crashes

![image](https://user-images.githubusercontent.com/7490180/219671272-70d78fb1-68ad-4afe-80f0-0482f1f7461c.png)![image](https://user-images.githubusercontent.com/7490180/219671213-c2f3c26d-dc59-4b82-9bf4-fb21be1c549b.png)

### Expected behavior
shows like before

### Environment
MacBook Pro (13-inch, 2020)
Intel Iris Plus Graphics 1536 MB

- **OS**:  macOSMonterey 12.6
- **Browser**:  Chrome and Edge latest

**Comment by floryst** [comment]
I'm suspecting this is due to the norm16 extension. We've been investigating similar issues where the `EXT_texture_norm16` extension is supposedly supported, but doesn't actually work. Firefox and Opera should be the only browsers that aren't affected.

**Comment by sedghi** [comment]
That is so weird. I thought it is stable for `texImage3D` (it was working for me before!)
However we found a bug for `texSubImage3D` which we reported and they apparently have a fix soon

https://bugs.chromium.org/p/chromium/issues/detail?id=1408247
https://bugs.webkit.org/show_bug.cgi?id=252039

**Comment by sedghi** [comment]
hmmmmm quite interesting, I didn't know that. Ok then that makes sense now

**Comment by sedghi** [comment]
is it known that texStorage3D and texSubImage3D is faster? since I don't think you use the streaming feature of subImage3D to progressively load

**Comment by sankhesh** [comment]
@sedghi Could you please try #2718?

> is it known that texStorage3D and texSubImage3D is faster? 

The premise of `texStorage` is that the texture buffer is allocated in memory right away which means there are no additional checks/resizes when drawing the texture; thereby, making it a little more efficient.
