### ISSUE TITLE
Cannot run examples with the current version of Webpack

### ISSUE THREAD

**Issue by auxiliary** [Kitware/vtk-js#272]
When I run an example, I get the following error: 
`Error: Cannot find module '../config/webpack.loaders.js'`

It seems like there's a compatibility issue with the current version of Webpack.

**Comment by jourdain** [comment]
1. Delete your `node_modules` directory as well as `Documentation/build-tmp`.
2. run `npm install`
3. You should be all set. If not let me know what you did and how you get that error.

Thanks,

Seb

**Comment by jourdain** [comment]
Oups are you talking about 'npm run example -- NAME`?

**Comment by auxiliary** [comment]
Yes

**Comment by jourdain** [comment]
Ok thanks, I will try to fix it soon.

**Comment by auxiliary** [comment]
Thank you. A semi-related question: So I managed to run an example from an older revision (3239d37). What version of Paraview should the data converter macro work with? I've tried 5.2 and 5.3 and it tells me `AttributeError: 'vtkCommonDataModelPython.vtkImageData' object has no attribute 'GetPoints'`

Could it be because I'm trying to convert a NetCDF volume?

**Comment by jourdain** [comment]
I'm guessing that you are using the ParaView macro which was meant to be used for geometry extract not volume hence the issue.

To get the volume you should use `vtkDataConverter` that should be available in your command line environment if you run `npm install vtk.js -g` or `npm link` within your local repo of vtk.js.

Then hopefully the help within `vtkDataConverter` should be enough to get you started. And you will have to do something similar to that [example](https://kitware.github.io/vtk-js/examples/VolumeMapper.html) to look at your data.

**Comment by auxiliary** [comment]
Is there a specific requirement or file format that vtkDataConverter works with. All my NetCDFs result in `NetCDF: Invalid dimension ID or name`. I also tried converting them to a .vtk in Paraview, then using vtkDataConverter. That went fine, but when the viewer opens up it crashes with the JS error `TypeError: Cannot read property 'getDataType' of null` in `VolumeMapper.js:23452`.

**Comment by jourdain** [comment]
The volume mapper example assume that the data you are looking is active, while the vtkDataConverter does not set any active array. You may want to either programmatically set the array active or edit the json file like here: https://github.com/Kitware/vtk-js/blob/master/Data/volume/headsq.vti/index.json#L32

**Comment by auxiliary** [comment]
Thanks. That did the trick.

**Comment by jourdain** [comment]
Issue is fixed inside master
