### ISSUE TITLE
Is there a way to calculate the radius of the SphereWidget on the screen

### ISSUE THREAD

**Issue by Zhengyangzuishuai** [Kitware/vtk-js#2724]
I'm trying to use svg to outline a SphereWidget on the screen
<img width="480" alt="image" src="https://user-images.githubusercontent.com/43663302/220830320-f0212688-29bc-4796-bd15-443f29b5aa3d.png">

**Comment by finetjul** [comment]
From the widget state you can get access to the center 3D point and a 3D point on the circle, hence you can compute the radius.

**Comment by Zhengyangzuishuai** [comment]
> 

Yes, but the radius calculated by the coordinates of the borderhandle projected in the pixel space when reslice is not correct

**Comment by Zhengyangzuishuai** [comment]
> From the widget state you can get access to the center 3D point and a 3D point on the circle, hence you can compute the radius.
Yes, but the radius calculated by the coordinates of the borderhandle projected in the pixel space when reslice is not correct

**Comment by finetjul** [comment]
if you want to map world coordinates with pixel coordinates, you might want to rely on the `displayCallback`.
You can see an example [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/ImageCroppingWidget/example/index.js#L68).

Alternatively, [this example](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/PolyLineWidget/example/index.js) does also manipulate SVG elements.

**Comment by Zhengyangzuishuai** [comment]
> if you want to map world coordinates with pixel coordinates, you might want to rely on the `displayCallback`. You can see an example [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/ImageCroppingWidget/example/index.js#L68).
> 
> Alternatively, [this example](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/PolyLineWidget/example/index.js) does also manipulate SVG elements.

Yes, I tried to use worldPointsToPixelSpace, and successfully obtained the coordinates on the screen after the transformation, but the problem is that the projection of the borderHandle point after the reslice will change, and finally the radius of my svg circle will also change dynamically. So is there a way to directly calculate the radius or size of the actor on the screen

**Comment by finetjul** [comment]
Please consider the [ShapeWidget](https://kitware.github.io/vtk-js/examples/ShapeWidget.html) example with the circle widget to get the radius.
