### ISSUE TITLE
how to set the line color of LineWidget ? it seems not work

### ISSUE THREAD

**Issue by jinjilynn** [Kitware/vtk-js#2725]

**Comment by jinjilynn** [comment]
```javascript
currentWidget.getWidgetState().getMoveHandle().setColor(color);
```
i set the color like this

**Comment by finetjul** [comment]
A `color` mixin is a scalar that gets mapped through a color transfer function.
There is a new `color3` mixin (i.e. `setColor3()`) that lets you set the r,g,b color components.

**Comment by jinjilynn** [comment]
> A `color` mixin is a scalar that gets mapped through a color transfer function. There is a new `color3` mixin (i.e. `setColor3()`) that lets you set the r,g,b color components.

i know the value is a scalar value, so i set the value from 0 to 1, the handle1 & handle2 is ok, but the moveHandle is bad

```javascript
currentWidget.getWidgetState().getMoveHandle().setColor(0.1); // 0.1 map to a red-like color
```

**Comment by finetjul** [comment]
Gotcha, then you need to disable "activeColor" to the line widget: `currentWidget.setUseActiveColor(false)`, the `moveHandle` color will then be considered instead of being overrident by the `activeColor`

**Comment by finetjul** [comment]
Closing, feel free to reopen if that does not fix your question
