### ISSUE TITLE
VTK.js dependencies

### ISSUE THREAD

**Issue by finetjul** [Kitware/vtk-js#2727]
### High-level description
I tried a vanilla webpack project with "vtk.js" as dependency following the [old approach](https://kitware.github.io/vtk-js/docs/old_intro_vtk_es6.html).

It still works, however I had to do (not documented): 
  `npm install autoprefixer @babel/preset-env`

### Steps to reproduce

[webpack-vtk.js.zip](https://github.com/Kitware/vtk-js/files/10832409/webpack-vtk.js.zip)

### Expected behavior
I guess there are 2 options to fix this issue:
 - add "autoprefixer" and "@babel/preset-env" as vtk.js dependencies
 - update the [old approach documentation](https://kitware.github.io/vtk-js/docs/old_intro_vtk_es6.html)

I would favor the first option but I'm not so sure.

### Environment
- **vtk.js**: v26
- **OS**: Windows 11
- **Browser**: Chrome latest

**Comment by floryst** [comment]
We should add `autoprefixer` and `@babel/preset-env` as peer dependencies, and note that in the docs. No need to add it to the dependencies array.
