### ISSUE TITLE
Unable to extract data from vtkActor to pass over http for save purpose.

### ISSUE THREAD

**Issue by anandadake** [Kitware/vtk-js#2732]
### High-level description
Created a actor from stl file and transformed it, now we want to save updated actor (stl file) at backend via http

### Steps to reproduce

  * code snippets - Angular 13
    ```
    ngAfterViewInit(): void {
      this.http.get(`cube.stl`, {responseType: "blob"}).subscribe((resp: any) => {
        let response__: any = new Response(resp).arrayBuffer().then((response) => {
          this.reader = vtk.IO.Geometry.vtkSTLReader.newInstance();
          this.actor = vtk.Rendering.Core.vtkActor.newInstance();
          this.mapper = vtk.Rendering.Core.vtkMapper.newInstance({ scalarVisibility: false });
          this.actor.setMapper(this.mapper);
          this.mapper.setInputConnection(this.reader.getOutputPort());
          this.reader.parse(response);
          this.actor.getProperty().setOpacity(this.DEFAULT_OPACITY);
          this.renderer.addActor(this.actor);
          this.render();
        })
      });
    }

    scale(event:any){

         this.actor.setScale(event.scale_x, event.scale_y, event.scale_z);
          this.render();
    }
    
    save(event:any){
          //how to pass vtkActor string/arrayBuffer data over http to server??
    }

    ```

### Expected behavior
Want to save vtkActor into stl file through Http at server side
How could i get plain stl data from actor ?

**Comment by jourdain** [comment]
Actors don't hold data. The transform you applied on the actor is just for rendering and does not affect data.
What you need to do is apply that transform onto the point coordinates on a filter to produce another mesh and use that mesh as input to a STL writer.

**Comment by anandadake** [comment]
I Tried this 

'''
    const writer = vtk.IO.Geometry.vtkSTLWriter.newInstance();
    writer.setInputData(this.reader.getOutputData());
    const fileContents = writer.getOutputData();
    const blob = new Blob([fileContents], { type: 'application/octet-steam' });
    this.apiService.post('/api/receive',blob).subscribe(()=>{});
'''
But It saved the original file data without modification of position and scale

**Comment by jourdain** [comment]
Indeed you are writing what you read. This is expected. 

```
const ds = reader.getOutput()
 
vtkMatrixBuilder
      .buildFromRadian()
      . scale(sx, sy, sz)
      .apply(ds.getPoints().getData());

const writer = vtk.IO.Geometry.vtkSTLWriter.newInstance();
writer.setInputData(ds);
```

**Comment by floryst** [comment]
Actor position and scale is used for drawing your STL data in the scene. It doesn't transform your points. You need to use a vtk filter to do that.

**Comment by anandadake** [comment]
> vtk filter
Could you please give me an example.
Thanks in advance.

**Comment by jourdain** [comment]
Already did... Do you need more?

**Comment by anandadake** [comment]
> Already did... Do you need more?

I'm getting bellow error...

ERROR TypeError: Cannot read properties of undefined (reading 'buildFromRadian')

**Comment by anandadake** [comment]
Ohh Sorry Guys..
I was using wrong path of vtkMatrixBuilder
its actually 
vtk.Common.Core.vtkMatrixBuilder.buildFromRadian()

thank you so much...
