### ISSUE TITLE
vtkResliceCursorWidget

### ISSUE THREAD

**Issue by Javi-r** [Kitware/vtk-js#2733]
1. The views are reversed when you rotate the planes as you can see in this video: 

https://user-images.githubusercontent.com/33517533/222127396-f45b7c9b-ff16-4b20-9fe2-0bf1ab92f415.mp4

2. The following methods do not work
```
const widget = vtkResliceCursorWidget.newInstance();
const state = widget.getWidgetState();
state.setOpacity(0.6);
state.setSphereRadius(8);
state.setShowCenter(false);
state.setLineThickness(2);
```

### Environment
- **vtk.js**:  26.x.x
- **OS**: Ubuntu 10, iOS 13.6
- **Browser**: Chrome 108.0.5359.62

**Comment by finetjul** [comment]
1. Should be fixed in the PR: https://github.com/Kitware/vtk-js/pull/2730
2. Indeed, those methods should be replaced by playing with handle mixins:
e.g.
```
state.getCenterHandle().setVisible(true / false); // was before setShowCenter(true/false)
state.getCenterHandle().setScale1(10); // was before setSphereRadius(10);
...
```

**Comment by Javi-r** [comment]
What is now the alternative for setOpacity and setLineThickness ?
And how do you change the diameter of the other spheres ?
state.getCenterHandle().setScale1  only changes the radius of the central sphere  state.setSphereRadius changed the radius of all spheres.

**Comment by Javi-r** [comment]
Any alternative for state.setOpacity ? this does not work

**Comment by finetjul** [comment]
Indeed, there is no alternative for `state.setOpacity`.

@floryst WDYT if we add an `opacity` mixin ?

**Comment by Javi-r** [comment]
I have upgraded to version 26.8.0 and the view still flips when rotating the planes as seen in the video

**Comment by finetjul** [comment]
The PR #2730 has not yet been merged into master.
