### ISSUE TITLE
Can Widgets add onModifiedEnd event handler or export a leftButtonPress handle just receive a callback

### ISSUE THREAD

**Issue by supriome** [Kitware/vtk-js#2735]
I'm using ImplicitPlaneWidget, I want to listen event of left button release. I notice implict plane behavior has this event listener.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/19944032/222689022-6251e293-fd78-462a-a8a8-50a2af393716.png">
 
But when i use widget, I can only have an option of listen onModified event, it trigger every time when i drag the actor. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/19944032/222689408-b736bf1e-e458-45e0-b2fa-5503a3ca2bfe.png">

So, is it possible that add a function like `widget.getWidgetState().onModifiedEnd(callback)`

**Comment by bruyeret** [comment]
You can register a callback on "end interaction event" thanks to this line in ImplicitPlanWidget:
```
publicAPI.invokeEndInteractionEvent();
```

To register a callback, use:
```
/**
   * Registers a callback to be invoked when an end interaction event occurs.
   * 
   * @param {EventHandler} cb The callback to be called. 
   * @param {Number?} [priority] The callback to be called
   */
  onEndInteractionEvent(cb: EventHandler, priority?: number): Readonly<vtkSubscription>;
```

**Comment by bruyeret** [comment]
Is this the function you were looking for?

**Comment by finetjul** [comment]
To do so, you need to do something like:

```
const instancedWidgetInView = widgetManager.addWidget(widget);
instancedWidgetInView.onEndInteractionEvent(...)
```

**Comment by supriome** [comment]
@finetjul @bruyeret 
Thanks you both,  I've try your code `instancedWidgetInView.onEndInteractionEvent(...)` and it works, it helps me a lot.
