### ISSUE TITLE
Issue with rendering PolyData with RGBA lookup table

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#2739]
### High-level description
To start, not sure if it is a bug or limitation.
But, I'm not able to render a polyData with RGBA look up table with any opacity that is not 255. 

### Steps to reproduce
I have created a sandbox here

https://codesandbox.io/s/polydata-translucent-p16eji?file=/src/index.js:3281-3320

Line 101 has the logic for the `vtkLookupTable` that I'm using 

```js
const numberOfColors = 1;
  const table = vtkDataArray.newInstance({
    numberOfComponents: 4,
    size: 4 * numberOfColors,
    dataType: "Uint8Array"
  });
  table.setTuple(0, [255, 0, 0, 255]);
```

which results in correct image which is 

![image](https://user-images.githubusercontent.com/7490180/223555730-ea5e465e-6bef-45d2-9702-78c5ecb700a3.png)

but even changing the 255 opacity in RGBA to 254 results in

![image](https://user-images.githubusercontent.com/7490180/223555849-a6d7a099-f33b-4b4f-b2af-22f0b04f9580.png)

is this a bug or limitation? 

### Detailed behavior
My end goal is actually completely different thing. To to be able to change the opacity of each scalar in the `appendPolyData` via `vtkLookUpTable` to be able to set the opacity to 0 and hide each polyData separately (code sandbox [here](https://codesandbox.io/s/append-poly-data-transfer-function-25tmux?file=/src/index.js))

![image](https://user-images.githubusercontent.com/7490180/223558474-1d2cc13d-cc8d-400b-8723-12bd3bc1a5bf.png)

but when I set the red to be opacity of 0 (line 101), it gets disappeared but the blue becomes incorrect in depth

![image](https://user-images.githubusercontent.com/7490180/223558638-79ac3333-154e-42d0-93b5-e757216c5592.png)

related discussion on discourse 
- https://discourse.vtk.org/t/optimizing-traverseopaquezbufferpass-for-rendering-many-polydata-actors/10761

### Expected behavior
They stay at the correct depth 

### Environment
- **vtk.js**: 26.8.0
- **OS**: MacOS
- **Browser**: Latest Chrome

**Comment by finetjul** [comment]
I'm not sure to understand all the problems.

Screenshot #2 is expected. When a polydata is not opaque, that means it will not write into the depth buffer. So when the volume is rendered AFTER, it will overwrite the translucent polydata fragments.
I can think of 2 options:
 - render the translucent polydata in the opaque render pass by calling 'setForceOpaque(true)' on its actor
 - render the translucent polydata in the overlay pass, hence AFTER the volume. To do so you need to use vtkActor2d instead of vtkActor.

Hth,
Julien.
P.s. for information, shall you not use a lookup table but directly store rgba values in your polydata point data scalar array, please note that I fixed a bug in a not-yet-merged PR (#2730)

**Comment by sedghi** [comment]
Thanks @finetjul for your response. So it is not a bug.
The first option works like a charm (`setForceOpaque(true)`) I guess I will use that. 

One last question, which I'm pretty sure is my limited knowledge but related to this thread if anyone looks in future. It seems like I can't map scalar to color one to one in this [example](https://codesandbox.io/s/append-poly-data-transfer-function-25tmux?file=/src/index.js:3257-3595) 

My scalars are 0 and 1 (for my two polyData) which is set below (index gets incremented)

```js
const scalars = vtkDataArray.newInstance({
  size,
  numberOfComponents: 1
});
for (let i = 0; i < size; ++i) {
  scalars.setTuple(i, [index]);
}
polyData.getPointData().setScalars(scalars);
```

and then I map them in the lookUp table with 

```js
const numberOfColors = 3;
const table = vtkDataArray.newInstance({
  numberOfComponents: 4,
  size: 4 * numberOfColors,
  dataType: "Uint8Array"
});
table.setTuple(0, [255, 0, 0, 255]);
table.setTuple(1, [0, 255, 0, 255]);
table.setTuple(2, [0, 0, 255, 255]);
lut.setTable(table);
```

my 0 scalar is correctly set to be Red `[255, 0, 0, 255]` BUT my second scalar (1) is being set to the last one which is 2 and Blue (`[0, 0, 255, 255]`). 
Any idea what am I doing wrong? 
I want 0-> RED and 1 -> Green? one to one mapping

**Comment by finetjul** [comment]
you may have to play with the `range` of your LUT.

**Comment by sedghi** [comment]
I ended up setting the scalars directly with RGBA which worked great. Thanks
