### ISSUE TITLE
Scrolling through slices with InteractorStyleImage

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#275]
This is similar to issue 232, but I'm running into an issue scrolling through the slices with InteractorStyleImage.  Using this [example](https://kitware.github.io/vtk-js/examples/ImageMapper.html) as a guide but loading the ‘LIDC2.vti’ example volume, I can get various slices to show up on loading with ```mapper.setZSclice()```, but am then unable to scroll through. Here's a bit of my setup code:
```
    const mapper = vtkImageMapper.newInstance();
    const actor = vtkImageSlice.newInstance();
    actor.setMapper(mapper);

    const iStyle = vtkInteractorStyleImage.newInstance();
    iStyle.setInteractionMode('IMAGE_SLICING');
    renderWindow.getInteractor().setInteractorStyle(iStyle);
````
I'm on a mac, and as I understand it, 'ctl+drag' should allow me to scroll through the slices in the volume, but ctl+drag doesn't seem to do anything, while command+drag fires a window/level event. If I switch InteractionMode to 'IMAGE3D' and press shit+drag I get the expected rotation event, so I'm unsure if its an issue with my setup or something within the code itself.  It seems to appear across all browsers as well.

**Comment by llangholz89** [comment]
Just as I thought, it was something with my set up.  Including ```mapper.setSliceAtFocalPoint(true)``` produced the expected behavior.  However, what is the best way to avoid the zooming effect while scrolling through?

**Comment by laurennlam** [comment]
@llangholz89 Some changes have been added. See #341

**Comment by llangholz89** [comment]
Yep, I've seen those, thanks for the update ;)

I don't know if you all are waiting for me to close this issue or if you're keeping it open for some other reason, but all seems to be working on my end and I can close this if needed!

Thanks

**Comment by laurennlam** [comment]
I think you can close :)
