### ISSUE TITLE
vtkLineWidget setText not work

### ISSUE THREAD

**Issue by Javi-r** [Kitware/vtk-js#2752]
widgetState.getText().setText() not work in vtk.js V26.9.0
widgetState.getPositionOnLine().setPosOnLine() I don't know if it still works
### Environment
- **vtk.js**:  26.9.0
- **OS**: Xbuntu 22.04
- **Browser**: chrome 108.0.5359.62

**Comment by bruyeret** [comment]
Take a look at [this example](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Widgets3D/LineWidget/example/index.js), it still works
The live example is [here](https://kitware.github.io/vtk-js/examples/LineWidget.html) and can also be run using `npm run example LineWidget`
Whenever you have a question on the API of vtk.js, you can check out the doc, the examples or the code of the class

**Comment by finetjul** [comment]
You are going to have to look at what snabbdom can offer. @floryst

**Comment by floryst** [comment]
If you are using the SVGHelper.js file, you can use [`makeListenableSVGNode`](https://github.com/Kitware/vtk-js/blob/master/Examples/Widgets/Utilities/SVGHelpers.js#L200). You can find more info in the [snabbdom eventlisteners module](https://www.npmjs.com/package/snabbdom#the-eventlisteners-module)

**Comment by finetjul** [comment]
So I guess you can look at the LabelWidget example code
