### ISSUE TITLE
getBoundsForSlice first argument is optional

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#2758]
`getBoundsForSlice` is typed with `slice` as required but it actually is optional.

**Comment by daker** [comment]
For which class?

**Comment by FezVrasta** [comment]
Sorry, this one https://github.com/Kitware/vtk-js/blob/00a46c083f4a637eb9433ea06bfc3b63ba262189/Sources/Rendering/Core/ImageSlice/index.d.ts#L38

**Comment by daker** [comment]
The first argument is not optional as you can see in the JS code
https://github.com/Kitware/vtk-js/blob/00a46c083f4a637eb9433ea06bfc3b63ba262189/Sources/Rendering/Core/ImageSlice/index.js#L114

**Comment by FezVrasta** [comment]
Internally it calls `getBoundsForSlice` that allows `slice` to be omitted.

**Comment by daker** [comment]
Maybe the usage internally on the JS part can be optional, i'll let others comment on the the issue
@finetjul 
@jourdain
