### ISSUE TITLE
How to use mprAnd3DVolumeViewport in viewers-v3-stable 

### ISSUE THREAD

**Issue by lang18276916053** [Kitware/vtk-js#2788]
### Need

I found this line of code in the path, but I don't know how to work, 'extensions/cornerstone/src/getHangingProtocolModule.ts'
`function getHangingProtocolModule() {
  return [
    {
      name: 'mpr',
      protocol: mpr,
    },
    {
      name: mprAnd3DVolumeViewport.id,
      protocol: mprAnd3DVolumeViewport,
    },
  ];
}`

**Comment by daker** [comment]
Hello, i think you have reported the issue against the wrong project, you need to do it in https://github.com/OHIF/Viewers, here is how you can use it : 
https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095722.1&hangingProtocolId=mprAnd3DVolumeViewport

**Comment by daker** [comment]
@lang18276916053 can you close the issue ?

**Comment by lang18276916053** [comment]
@daker Can you configure this mode to the toolbar,like MPR mode ？
