### ISSUE TITLE
VTK file converter in javascript

### ISSUE THREAD

**Issue by juanprietob** [Kitware/vtk-js#280]
The data converter is written in python. Is there a data converter for vtk files that is available in the browser?

**Comment by doczoidberg** [comment]
no. see also: https://github.com/Kitware/vtk-js/issues/205

**Comment by jourdain** [comment]
No, but the plan will be to use Emscripten to convert some C++ reader of VTK into JavaScript so we could load various binary files in pure JavaScript.

Although, we don't have any timing/schedule for that.

**Comment by jourdain** [comment]
We have native JavaScript reader for vtp and vti. Other more complex format will be handle via compiling VTK/C++ into WebAssembly or similar.
