### ISSUE TITLE
[Bug] ObjectManager array creation is broken

### ISSUE THREAD

**Issue by Antti-Palola** [Kitware/vtk-js#2815]
### Bug description

Two datasets of same dataType with same hash override each other.

### Steps to reproduce

Load a VTP of a single sphere that has cellData for volume and surface id.

### Detailed Behavior

When ObjectManager runs `createDataSetUpdate` the `state.arrays` is keyed by hash and type but with one surface and one volume both having data containing ones for both fields, their hashes are the same. The former cellData array is overridden by the latter.

### Expected Behavior

All arrays are processed.

### Environment

- vtk.js version: 27.4.1
- Browsers:
- OS:

**Comment by jourdain** [comment]
One of the idea is to not send the same array twice especially if the raw content is the same. Do we still preserve that property?

**Comment by Antti-Palola** [comment]
I would not be preserved if it's a different array.

I guess this could fixed in a way that all names that match the original hash+type are recorded. So we would add some map of `arrayNameToHash` that would be passed around the updater/arrayHandler to store the correct final arrays.

**Comment by Antti-Palola** [comment]
No problem, done!
