### ISSUE TITLE
[Bug] computeBarSize function doesn't exist on ScalarBarActor

### ISSUE THREAD

**Issue by ClappeB** [Kitware/vtk-js#2822]
### Bug description

I was trying to use `[ScalarBarActor.]computeBarSize()` function but the function doesn't exist even if the documentation and typescript say otherwise.

### Steps to reproduce

Add this code to whatever example you want:

import ScalarBarActor from '@kitware/vtk.js/Rendering/Core/ScalarBarActor';

const bars = ScalarBarActor.newInstance();
bars.computeBarSize({ tickHeight: 1, tickWidth: 1 }); // This line crashes as computeBarSize doesn't exist

### Detailed Behavior

The script stops at the line containing "computeBarSize" function as the function doesn't exist in runtime object (despite existing in typescript and documentation objects).

### Expected Behavior

The script shouldn't crash as the function is expected to exist on the runtime object.

### Environment

- vtk.js version: 27.4.1
- Browsers: Google Chrome
- OS: Microsoft Windows

**Comment by daker** [comment]
i think this is related to the fact that they are arrow functions

**Comment by ClappeB** [comment]
What do you suggest then?
Should I be able to access it and I just misunderstood something in the API or is it not accessible and should be fixed (or something else)?

For your information, here is the list of functions (JSON format) that is attached to the object that comes out of `ScalarBarActor.newInstance()`:
`["addEstimatedRenderTime","addPosition","addTexture","computeMatrix","delete","get","getActors","getActors2D","getAllocatedRenderTime","getAutoLayout","getAutomated","getAxisLabel","getAxisTextStyle","getAxisTitlePixelOffset","getBackfaceProperty","getBarPosition","getBarPositionByReference","getBarSize","getBarSizeByReference","getBounds","getBoxPosition","getBoxPositionByReference","getBoxSize","getBoxSizeByReference","getCenter","getClassName","getCoordinateSystem","getDragable","getDrawAboveRangeSwatch","getDrawBelowRangeSwatch","getDrawNanAnnotation","getEstimatedRenderTime","getForceOpaque","getForceTranslucent","getGenerateTicks","getIsIdentity","getIsOpaque","getLength","getMTime","getMapper","getMatrix","getNestedDragable","getNestedPickable","getNestedProps","getNestedVisibility","getOrientation","getOrientationByReference","getOrientationWXYZ","getOrigin","getOriginByReference","getParentProp","getPickable","getPosition","getPositionByReference","getProperty","getRedrawMTime","getReferenceByName","getRenderTimeMultiplier","getScalarsToColors","getScale","getScaleByReference","getState","getSupportsSelection","getTextures","getTickLabelPixelOffset","getTickTextStyle","getUseBounds","getUserMatrix","getVisibility","getVolumes","getXRange","getYRange","getZRange","hasKey","hasTexture","hasTranslucentPolygonalGeometry","isA","isDeleted","makeProperty","modified","onModified","pick","processSelectorPixelBuffers","removeAllTextures","removeTexture","resetAutoLayoutToDefault","resetGenerateTicksToDefault","restoreEstimatedRenderTime","rotateWXYZ","rotateX","rotateY","rotateZ","set","setAllocatedRenderTime","setAutoLayout","setAutomated","setAxisLabel","setAxisTextStyle","setAxisTitlePixelOffset","setBackfaceProperty","setBarPosition","setBarPositionFrom","setBarSize","setBarSizeFrom","setBoxPosition","setBoxPositionFrom","setBoxSize","setBoxSizeFrom","setCoordinateSystem","setCoordinateSystemToDisplay","setCoordinateSystemToWorld","setDragable","setDrawAboveRangeSwatch","setDrawBelowRangeSwatch","setDrawNanAnnotation","setEstimatedRenderTime","setForceOpaque","setForceTranslucent","setGenerateTicks","setMapper","setOrientation","setOrigin","setOriginFrom","setParentProp","setPickable","setPosition","setPositionFrom","setProperty","setRenderTimeMultiplier","setScalarsToColors","setScale","setScaleFrom","setTickLabelPixelOffset","setTickTextStyle","setUseBounds","setUserMatrix","setVisibility","shallowCopy","toJSON"]`

**Comment by floryst** [comment]
This is indeed a bug with the typescript definitions. `computeBarSize` is available on the ScalarBarActor helper, *not* the vtkScalarBarActor itself.

Try using `getBarSize()` instead. I presume you are only looking to get the bar size.
