### ISSUE TITLE
Is there a `ZipMultiDataSetReader` example?

### ISSUE THREAD

**Issue by supriome** [Kitware/vtk-js#2829]
### Bug description

I've noticed that there don't have a `ZipMultiDataSetReader` example in source code, and I also don't know what a multi DataSet is, is there a file example for me to download.

I use `Paraview` to load a `glTF` file, and then I export this model to a `vtm` multiBlock data. It produce a vtm entry file, and a folder include all the separate part file, so if i  can  use `ZipMultiDataSetReader` to load those files?

<img width="810" alt="image" src="https://github.com/Kitware/vtk-js/assets/19944032/a5d40ae5-72ce-442a-92a3-e14daf13d0b7">

### Steps to reproduce

 nothing here

### Detailed Behavior

 nothing here

### Expected Behavior

 nothing here

### Environment

 nothing here

**Comment by jourdain** [comment]
`ZipMultiDataSetReader` is an unfinished class which intended to capture many dataset in 1 file. It was not meant to handle multiblocks.
