### ISSUE TITLE
[Bug] Volume Shader compile error with GradientOpacity and clippingPlane 

### ISSUE THREAD

**Issue by PaulHax** [Kitware/vtk-js#2830]
### Bug description

Getting shader compile error in vtkVolumeFS.glsl
```
ROR: 0:402: 'IStoVC' : no matching overloaded function found
ERROR: 0:402: '=' : dimension mismatch
ERROR: 0:402: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'
```

### Steps to reproduce

Add these lines to `VolumeMapperBlendModes` example:

```
import vtkPlane from '@kitware/vtk.js/Common/DataModel/Plane';
actor.getProperty().setUseGradientOpacity(0, true);
const clipPlane1 = vtkPlane.newInstance();
mapper.addClippingPlane(clipPlane1);
```

### Detailed Behavior

Trouble is somewhere around here:
https://github.com/Kitware/vtk-js/blob/2dd7e3fadb7806f7e7c5b9658691dd6a6bd5a816/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L367-L377

### Expected Behavior

No shader compile error.

### Environment

- vtk.js version: v28.0.0
- Browsers: Chrome
- OS: Linux

**Comment by thewtex** [comment]
@sankhesh related to your recent changes? https://github.com/Kitware/vtk-js/commit/fc928f02e2f1f8f563b0f51c54086ad2685df49d https://github.com/Kitware/vtk-js/commit/fee91ebf21425ddd7aeb265220e0a4a4520ecafe
