### ISSUE TITLE
[Bug] - Unable to zoom when holding shift when scrolling with MouseWheel

### ISSUE THREAD

**Issue by david-cord** [Kitware/vtk-js#2834]
### Bug description

Zoom interactor does not work with `scrollEnabled: true` and `shift: true` when rolling a mousewheel.  All other variants work in terms of modifier keys.  Specifically shift + a mouse wheel interaction.  Effects both zoom and zoomToMouse.

### Steps to reproduce

https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html

<img width="652" alt="image" src="https://github.com/Kitware/vtk-js/assets/97387061/c48947a9-1982-4752-91b8-844a2949b4f5">

Go to the above demo, set the right most scroll column to as seen in the screenshot.  You'll see when shift + mousewheel scroll is applied, nothing happens.  It correctly zooms for the other modifier key combinations ctrl + mousewheel and alt + mousewheel.

**Please note this works when 2-finger scrolling with say a touchpad (macbook).  It will not work when rolling a mousewheel.  All other modifier keys with mousewheel work: `ctrl` `alt` etc.**

### Expected Behavior

Zoom occurs

### Environment

Whatever is latest deployed on https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html

**Comment by floryst** [comment]
@finetjul this might be related to the adjustments to the spin values.

**Comment by finetjul** [comment]
I tried to reproduce but I do not have the bug.
I'm on Windows 11, using Chrome 113. I tried both with a left+right+mid+scroll USB mouse but also with my laptop trackpad.

**Comment by david-cord** [comment]
Hi there, thanks for the follow up.  The only difference that springs to mind is that I'm on a Mac.

I've doubled confirmed, testing on both Chrome and Brave, and both using usb mouse and bluetooth.  In all cases, specifically just the shift key plus mousewheel zoom doesn't do anything, all other variants work. (different modifier keys - or none at all, plus touch pad scroll gestures)

I'm trying to get hold of a windows machine to see if it works on that.  I shall post a follow up comment when I can confirm.  

I should add, I'm on a pretty standard setup and don't have any other issues with scrolling with the mousewheel.

**Comment by david-cord** [comment]
ok, confirmed it's not an issue on Windows, so it seems to be Mac + the specific scenario I've described.  How odd....

**Comment by finetjul** [comment]
Did you try the example in [full screen mode](https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator/index.html) ?

**Comment by david-cord** [comment]
I have, the same issue.   I've recorded a demo with keycastr in the screen so you can see my keyboard events.


https://github.com/Kitware/vtk-js/assets/97387061/a39e03a2-e473-44f6-82df-211736595e6f

**Comment by finetjul** [comment]
Apparently a shift+scroll on mac does "horizontal scrolling":

https://github.com/Kitware/vtk-js/blob/e654ff27fe444bb75ef712023586023a043e85e9/Sources/Rendering/Core/RenderWindowInteractor/index.js#L657

https://github.com/Kitware/vtk-js/blob/e654ff27fe444bb75ef712023586023a043e85e9/Sources/macros.js#L1685

Most of the interactors in VTK.js only handles "vertical scrolling" (spinY). Maybe we should harmonize `spinX` and `spinY` into a third `spin` value (`=max(spinX, spinY)`). And for interactors that only support "vertical scrolling" it should consider `spin` instead of `spinY`. 

@floryst WDYT ?
