### ISSUE TITLE
[Bug] Problem with plane source

### ISSUE THREAD

**Issue by BishopWolf** [Kitware/vtk-js#2837]
### Bug description

vtkPlaneSource is not accepting input data

### Steps to reproduce

let planeSource = vtkPlaneSource.newInstance();
planeSource.setInputData(some vtkArray);

the data inside planeSource is not changed

### Detailed Behavior

The problem lies in this line

https://github.com/Kitware/vtk-js/blob/d3b62b568c3d9d5f1faf26df053921893733ba9f/Sources/Filters/Sources/PlaneSource/index.js#LL26C32-L26C32

you are assigning the output to the dataset, it should be the input.

### Expected Behavior

vtkPlaneSource accepts input data

### Environment

- vtk.js version: 28.2
- Browsers: Any
- OS:Any

**Comment by finetjul** [comment]
A PlaneSource is supposed to generate a plane polydata, hence it writes to the "outputData" of the filter.
Being a source filter, it should ignore any input data.
