### ISSUE TITLE
Can ParaView Web load unstructured grids for cropping and slicing processing？

### ISSUE THREAD

**Issue by missWangLP** [Kitware/vtk-js#2843]
### Feature Request

I need to load an unstructured grid .vtk file, how do I slice and crop it? 
ParaView Web

### Motivation and Detailed Description

I need to load an unstructured grid .vtk file, how do I slice and crop it? 
ParaView Web

**Comment by jourdain** [comment]
Yes as you get the full power of VTK/ParaView on the server side.

**Comment by missWangLP** [comment]
I have a vtk file, and there will be errors when cutting and slicing it. I'm not sure if it's due to the file format

**Comment by jourdain** [comment]
Did you try to open your file with ParaView? That will at least validate what you might be thinking.

**Comment by missWangLP** [comment]
Yes, I just opened the file using Paraview web, and the cropping and slicing tools reported an error. I will try Python again tomorrow. Can you help me test that file?

**Comment by jourdain** [comment]
Sure, I will open it with ParaView like I told you to.

**Comment by missWangLP** [comment]
Thank you, vtkPlane can be used normally now

**Comment by jourdain** [comment]
Cool so everything is working as expected...
