### ISSUE TITLE
[Bug] I cannot obtain the correct actor by picker

### ISSUE THREAD

**Issue by llayearnn** [Kitware/vtk-js#2844]
### Bug description

   I have a hexahedron model. Its six faces are returned to the frontend through API requests, and the frontend generates six actors by iterating through them. Each face carries information. Now, I use a picker（onRightButtonPress） to select one of the faces, but the actor I obtain is not the one that was actually clicked by the mouse. 
 My colleague uses vtk for Java (9.2.2), and he can obtain the correct face by using vtkPropPicker
 

### Steps to reproduce

// Pick on mouse right click
renderWindow.getInteractor().onRightButtonPress((callData) => {
  if (renderer !== callData.pokedRenderer) {
    return;
  }

  const pos = callData.position;
  const point = [pos.x, pos.y, 0.0];
  console.log(`Pick at: ${point}`);
  picker.pick(point, renderer);

  if (picker.getActors().length > 0) {
      console.log(picker.getActors()[0]) // obtained incorrect actor 
    }
}
)

### Expected Behavior

hope to obtain the correct actor by clicking with the mouse

### Environment

- vtk.js version:27.4.1
- Browsers:Windows 10
- OS:Chrome 102.0.5005.63

**Comment by floryst** [comment]
Are you using vtkCellPicker or vtkPointPicker?

**Comment by llayearnn** [comment]
> Are you using vtkCellPicker or vtkPointPicker?

yes,I tried both of them, but they didn’t work, so I resorted to using vtkPropPicker😰😰😰

**Comment by llayearnn** [comment]
> Are you using vtkCellPicker or vtkPointPicker?

https://github.com/llayearnn/vtk-demo

**Comment by moneyfirst-yh** [comment]
did you fixed it? i have the same problem

**Comment by llayearnn** [comment]
> did you fixed it? i have the same problem

not yet，This is their bug, and they haven't fixed it yet.

**Comment by finetjul** [comment]
Many things have changed in the pickers in the last 12 months. Especially in the HardwareSelector.

> This is their bug, and they haven't fixed it yet.

I don't it is the best approach to open-source projects. As a user of the library, you are also part of the VTK.js community. If you want the issue to be fixed, time must be spent somehow. Two options: 1) whether you have time to investigate yourself, or 2) you can finance someone to investigate for you...

**Comment by llayearnn** [comment]
> Many things have changed in the pickers in the last 12 months. Especially in the HardwareSelector.
> 
> > This is their bug, and they haven't fixed it yet.
> 
> I don't it is the best approach to open-source projects. As a user of the library, you are also part of the VTK.js community. If you want the issue to be fixed, time must be spent somehow. Two options: 1) whether you have time to investigate yourself, or 2) you can finance someone to investigate for you...

All right，I apologize for the way I expressed myself.

**Comment by moneyfirst-yh** [comment]
i fixed it useing HardwareSelector!

**Comment by floryst** [comment]
This should actually be fixed by now in the latest version of vtk.js. Your vtk-demo repo works as expected with the latest version: vtkPicker and vtkCellPicker hides the correct faces, while vtkPointPicker hides the correct faces when clicking on vertices.
