### ISSUE TITLE
[Bug] The object of vtkOpenGLPolyDataMapper does not have the method getViewSpecificProperties.

### ISSUE THREAD

**Issue by Ranglage** [Kitware/vtk-js#2854]
### Bug description

In the vtk.js documentation, there is an example code snippet as follows:
```
const mapperSpecificProp = mapper.getViewSpecificProperties();
mapperSpecificProp['OpenGL']['ShaderReplacements'].push({
  shaderType: ...,
  originalValue: ...,
  replaceFirst: ...,
  replacementValue: ...,
  replaceAll: ...
});
```
However, when I tested the code, the debugger indicated that the mapper object does not have the getViewSpecificProperties method. Here is my test code:
```
import vtkOpenGLPolyDataMapper from '@kitware/vtk.js/Rendering/OpenGL/PolyDataMapper';
const mapper = vtkOpenGLPolyDataMapper.newInstance();
const mapperSpecificProp = mapper.getViewSpecificProperties();
mapperSpecificProp['addShaderReplacement'] =
    (_shaderType, _originalValue, _replaceFirst, _replacementValue, _replaceAll) => {
        mapperSpecificProp['OpenGL']['ShaderReplacements'].push({
            shaderType: _shaderType,
            originalValue: _originalValue,
            replaceFirst: _replaceFirst,
            replacementValue: _replacementValue,
            replaceAll: _replaceAll,
        });
    };
```

### Steps to reproduce

just follow my code

### Detailed Behavior

```
bootstrap:27  Uncaught TypeError: mapper.getViewSpecificProperties is not a function
    at ./src/vtk_bug.js (vtk_bug.js:3:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (bundle.js:15:66)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

### Expected Behavior

get a mapper.getViewSpecificProperties() object

### Environment

- vtk.js version: 28.2.5
- Browsers: edge 115.0
- OS: win11

**Comment by floryst** [comment]
`getViewSpecificProperties` resides on vtkMapper, not the OpenGL specific mapper implementation. You should use vtkMapper, as you typically won't create vtkOpenGLPolyDataMapper directly.

**Comment by Ranglage** [comment]
> `getViewSpecificProperties` resides on vtkMapper, not the OpenGL specific mapper implementation. You should use vtkMapper, as you typically won't create vtkOpenGLPolyDataMapper directly.

thank you very much!
