### ISSUE TITLE
[Bug]  vtkInteractiveOrientationWidget does not work since 28.0.0

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#2858]
### Bug description

vtkInteractiveOrientationWidget stopped working since v28.0.0 update onwards. Pressing the interactiveWidget does not trigger onOrientationChange.
The InteractiveOrientationWidget example also does not seem to work: https://kitware.github.io/vtk-js/examples/InteractiveOrientationWidget.html

### Steps to reproduce

See: https://codesandbox.io/s/playground-93onj8?file=/src/Scene/SceneManager.tsx:5303-5334

### Expected Behavior

Run onOrientationChange when clicking the widget

### Environment

- vtk.js version: 28.0.0
- Browsers: Firefox 114.0.2 
- OS: Windows 10 Pro Version 21H2

**Comment by floryst** [comment]
Thanks for the report! We'll look into this. Do you know if it worked in the latest v27 release?

**Comment by zbouslikhin** [comment]
> Thanks for the report! We'll look into this. Do you know if it worked in the latest v27 release?

Yes, it does work in the latest v27 release

**Comment by jourdain** [comment]
Could be one of
- WidgetManager: Support multiple renderers in the same render window ([4def3ed](https://github.com/Kitware/vtk-js/commit/4def3ed1a49b20ead9a2f15f70f4d941a15ea45c))
- BehaviorManager: Allow decorated RenderWindow to work as well ([1024f07](https://github.com/Kitware/vtk-js/commit/1024f0719970fdcca63b552f1c2aaa6b728768b4))

**Comment by judebourlay** [comment]
tried it and indeed it seems broken due to https://github.com/Kitware/vtk-js/commit/4def3ed1a49b20ead9a2f15f70f4d941a15ea45c

**Comment by bourdaisj** [comment]
Closing as completed  
see https://github.com/Kitware/vtk-js/pull/3082
