### ISSUE TITLE
[Bug] "no runtime supported the requested configuration" error when requesting XR session on hololens

### ISSUE THREAD

**Issue by djelouze** [Kitware/vtk-js#2861]
### Bug description

After an update of MS Edge from 109.0.1518.49 to 114.0.1823.37 (triggered automatically by the hololens when browsing Edge parameters), the `navigator.xr.requestSession()` for HmdAR failed with message:

`no runtime supported the requested configuration`

Module: Rendering/OpenGL

### Steps to reproduce

- Update MS Edge to `114.0.1823.37` on the Hololens 2
- Browse to [vtk.js AR example](https://kitware.github.io/vtk-js/examples/AR.html)c
- Trigger the AR
- Open the developer console

### Detailed Behavior

When triggering AR in the example, nothing happened. The console shows the error message

### Expected Behavior

Hololens should go into AR mode, showing a floating cone

### Environment

- vtk.js version: v26.9.15
- Browsers: MS Edge 114.0.1823.37 
- OS: Windows ARM (Hololens2)

**Comment by tbirdso** [comment]
> Browse to [vtk.js AR example](https://kitware.github.io/vtk-js/examples/AR.html)c

Hi @djelouze , would you please try the VR example and let us know if it works for you:

https://kitware.github.io/vtk-js/examples/VR.html

As we note in the [AR example notes](https://kitware.github.io/vtk-js/examples/AR.html#Augmented-Reality-Head-Mounted-Display), the HoloLens 2 device considers itself to be a VR device and (currently) supports the `immersive-vr` and not `immersive-ar` session type. This leads to some confusing behavior where it is an AR HMD but runs our VR examples.

If the VR example works for you then I will work to update our documentation and examples to better clarify which examples support which devices.

**Comment by djelouze** [comment]
Indeed the VR example is working :) Thank you.

**Comment by tbirdso** [comment]
Hi @djelouze , I have updated our WebXR examples to improve documentation around supported devices. The webpage should update in the next hour or two. Please take a look and reopen this issue if you find that anything is unclear.

vtk.js WebXR examples: https://kitware.github.io/vtk-js/docs/develop_webxr.html
