### ISSUE TITLE
[Bug] WebXR Examples Default To Undesired Session Type

### ISSUE THREAD

**Issue by EricMoerthVis** [Kitware/vtk-js#2862]
### Bug description

It seems like the WebXR Examples on the webpage https://kitware.github.io/vtk-js/docs/develop_webxr.html are the same for AR and VR. I would like to try the Head Visualizations in VR but the button only says AR, no matter which example I open.

### Steps to reproduce

https://kitware.github.io/vtk-js/docs/develop_webxr.html go to the head visualizations in the VR section, the button only states Switch to AR instead of VR

### Expected Behavior

I would assume that the VR examples would allow me to see the head visualizations in VR.

### Environment

- vtk.js version:
- Browsers:
- OS:

**Comment by EricMoerthVis** [comment]
1) The Meta Quest Pro
2) Yes
3) The built in Browser on the Meta Quest Pro
4) Will check again

It seams like from time to time the examples can be opened but at other times they load forever and I don't see any rendering happening. I will check again for error loggs in the Browser within the goggles (if I manage to open them)

The example you stated here works on the goggles and I can go into VR Mode, but the controls then don't work any more. Before I go into VR mode I can use the controllers to move the cube and rotate it and such. But as soon as I go into the VR mode the cube just moves out of frame when I press the button on the right controller.

Maybe you could add the flagg xrSessionType for the examples on the page you have there? You already have two categories there with VR and AR but both examples lead to the same URL without the xrSessionType flag.

I will try further and keep you posted if I was able to get the medical imaging data running in VR on the Goggles.

**Comment by tbirdso** [comment]
Thank you for the details here.

> It seams like from time to time the examples can be opened but at other times they load forever and I don't see any rendering happening. I will check again for error loggs in the Browser within the goggles (if I manage to open them)

Some of the volume files are rather large and may take a moment to load. I wonder if there are memory constraints for the Meta Quest Pro built-in browser causing this behavior. Errors in the console log would indeed help us better understand this issue.

> The example you stated here works on the goggles and I can go into VR Mode, but the controls then don't work any more. Before I go into VR mode I can use the controllers to move the cube and rotate it and such. But as soon as I go into the VR mode the cube just moves out of frame when I press the button on the right controller.

Yes, while rendering is supported on multiple devices, unfortunately XR interaction support is still rather limited. For now WebXR examples only support translation in the direction of the Quest controller when the trigger is pressed. Interaction support is tracked on the vtk.js WebXR feature roadmap at https://github.com/Kitware/vtk-js/issues/2571.

> Maybe you could add the flagg xrSessionType for the examples on the page you have there? You already have two categories there with VR and AR but both examples lead to the same URL without the xrSessionType flag.

I agree, it would be clearer to add explicit links for each type. I will work on updating example pages accordingly.

**Comment by tbirdso** [comment]
Hi @EricMoerthVis , we have updated WebXR example pages for better clarity concerning XR session types. The page should update within the next hour or two. Please re-open this issue if you find that you still have trouble launching scenes in your Quest Pro headset.
