### ISSUE TITLE
The mtl corresponding to the obj file was not loaded correctly

### ISSUE THREAD

**Issue by xut-d** [Kitware/vtk-js#2863]
### Bug description

Use vtk.js to load obj model, need to load the corresponding color texture picture, but failed to load correctly, mtl file using other software can be loaded out, the following is a simple case, may I ask is there a problem with the use of code?

### Steps to reproduce

import '@kitware/vtk.js/favicon';
import '@kitware/vtk.js/Rendering/Profiles/Geometry';
import vtkActor from '@kitware/vtk.js/Rendering/Core/Actor';
import vtkLight from '@kitware/vtk.js/Rendering/Core/Light';
import vtkFullScreenRenderWindow from '@kitware/vtk.js/Rendering/Misc/FullScreenRenderWindow';
import vtkOBJReader from '@kitware/vtk.js/IO/Misc/OBJReader';
import vtkMTLReader from '@kitware/vtk.js/IO/Misc/MTLReader';
import vtkSTLReader from '@kitware/vtk.js/IO/Geometry/STLReader';
import vtkMapper from '@kitware/vtk.js/Rendering/Core/Mapper';
import vtkTexture from '@kitware/vtk.js/Rendering/Core/Texture';
import vtkPolyDataNormals from '@kitware/vtk.js/Filters/Core/PolyDataNormals';
import vtkWindowedSincPolyDataFilter from '@kitware/vtk.js/Filters/General/WindowedSincPolyDataFilter';
import vtkSTLWriter from '@kitware/vtk.js/IO/Geometry/STLWriter'
import vtkFPSMonitor from '@kitware/vtk.js/Interaction/UI/FPSMonitor';
import vtkCamera from "@kitware/vtk.js/Rendering/Core/Camera";

const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({
  background: [0.08, 0.08, 0.08],
});
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();
const mapper = vtkMapper.newInstance({ scalarVisibility: false });
const actor = vtkActor.newInstance();

const objReader = vtkOBJReader.newInstance();
objReader.setUrl('cube.obj');

const mtlReader = vtkMTLReader.newInstance();
mtlReader.setUrl('cube.mtl');

objReader.setUrl(`cube.obj`).then(() => {
  const polydata = objReader.getOutputData(0);
  const name = polydata.get('name').name;
  actor.setMapper(mapper);
  mapper.setInputData(polydata);
  if (mtlReader && name) {
    mtlReader.applyMaterialToActor(name, actor);
  }
  renderer.addActor(actor);
  renderWindow.render();
});
renderer.resetCamera();
renderWindow.render();

### Detailed Behavior

![nznAItdd49](https://github.com/Kitware/vtk-js/assets/84498316/7e8c653b-0368-481b-a458-bb330f9959ef)

### Expected Behavior

Use the website to load both obj and mtl files to see the results：https://3dviewer.net/#
The specific obj and mtl are stored in the zip package (cube.zip) are as follows：
[cube.zip]

(https://github.com/Kitware/vtk-js/files/11889470/cube.zip)

![p0UX9OtVke](https://github.com/Kitware/vtk-js/assets/84498316/025d8f97-b80e-40cd-bd10-1608796ccb23)

### Environment

- vtk.js version:   "name": "@kitware/vtk.js", "version": "28.2.6",
- Browsers:     117.0.5855.0 (正式版本) canary （64 位） (cohort: Clang-64) 
- OS:  Windows 10 专业版

**Comment by jourdain** [comment]
[That example](https://kitware.github.io/vtk-js/examples/OBJViewer.html) load that zip correctly with the proper color.

**Comment by xut-d** [comment]
My local display has no color, is it a problem with the version environment?

**Comment by xut-d** [comment]
Yes, the cube on the example on my computer has no color, it's all gray, so it doesn't feel right

**Comment by jourdain** [comment]
Which browser? And just to be sure. You dropped the zip file not the obj one?

**Comment by xut-d** [comment]
Browsers: 117.0.5855.0 (正式版本) canary （64 位） (cohort: Clang-64)
The zip file contains a cube.obj and cube.mtl, and the code loads the two files

**Comment by jourdain** [comment]
<img width="975" alt="Screenshot 2023-07-04 at 11 02 04" src="https://github.com/Kitware/vtk-js/assets/294518/890367dc-30be-4777-8e4d-eaabb1bca9fb">
 
Seems to be working for me on mac

**Comment by xut-d** [comment]
I can't find any other reason. Is the version of vtk.js I am using incorrect? I downloaded the version": "28.2.6" from your official website using npm, which version do you use?

**Comment by xut-d** [comment]
Updated the latest code, the display is good, thank you for the previous answer
