### ISSUE TITLE
The environment mipmap does not take effect

### ISSUE THREAD

**Issue by xut-d** [Kitware/vtk-js#2874]
### Bug description

Hello, I have a question. In the PBR case on the official website(https://kitware.github.io/vtk-js/examples/PBR.html), why does the use of environment map not take effect, Whether I check the Environment map button or not, the image below is always displayed and it looks like the map is not in effect? The code below the official website case clearly shows the background picture and sets the map, why can't it be displayed?
![6fc264b0-4c0f-4328-8ac4-f777f7488e83](https://github.com/Kitware/vtk-js/assets/84498316/2349898c-7d6d-4461-be76-9c13a80a5b49)

### Steps to reproduce

How can I use it to display the following effect?
![img_v2_f95d83dc-5b53-485f-a236-18f88a42268g](https://github.com/Kitware/vtk-js/assets/84498316/3b12ac7e-ebb9-416d-b502-961409c008f7)

### Expected Behavior

1. The official website case can show the effect of the mipmap, such as the second image
2.  setEnvironmentTexture() can be work in the code, can map the model

### Environment

- vtk.js version: 28.3.3
- Browsers: 117.0.5884.0 (正式版本) canary （64 位） (cohort: Clang-64) 
- OS: win10

**Comment by jourdain** [comment]
@andrewcombs

**Comment by andrewcombs** [comment]
It looks like you're loading the PBR case on the official website with a browser that doesn't support WebGPU. Right now, all PBR features are exclusive to WebGPU, which normal chrome does not support. Notice how in the second screenshot chrome displays `You are using an unsupported command-line flag: --enable-unsafe-webgpu. Stability and security will suffer.`  whereas the first screenshot does not. Because the PBR case on the official website does not have access to WebGPU, it is falling back to the WebGL backend which does not support PBR. Notice how textures are also not loaded in the first screenshot too.

**Comment by xut-d** [comment]
I use the browser version below, the computer graphics card below, so I don't know why I don't support webgpu, do you have any good suggestions?
![img_v2_a5e24cfc-fca2-43d2-9b87-462664e4686g](https://github.com/Kitware/vtk-js/assets/84498316/a6194ef1-68f4-424c-9bee-6eac60932e0c)
![img_v2_ce276e1c-c203-4e53-a68f-19aab5b4bb7g](https://github.com/Kitware/vtk-js/assets/84498316/6aa4302e-8627-408f-b67b-3e6dafcea3a3)
![img_v2_ab29a246-ef8e-4fa6-8c4f-76198fb256ag](https://github.com/Kitware/vtk-js/assets/84498316/82b516a3-17fa-4cc4-8f8e-cd135c366268)

**Comment by daker** [comment]
Since the release of Chrome 113, vtk.js have defaulted to WebGL since the WebGPU is not yet ready #2814, you need to call manually to force WebGPU:
```js
const renderwindow = vtkRenderWindow.newInstance({
    defaultViewAPI: 'WebGPU'
});
```

**Comment by jourdain** [comment]
You can force it that way https://kitware.github.io/vtk-js/examples/PBR/index.html?viewAPI=WebGPU

**Comment by jourdain** [comment]
But the background rendering is still not showing. The object get the proper reflections and so on though.


<img width="1363" alt="Screen Shot 2023-07-19 at 8 54 32 AM" src="https://github.com/Kitware/vtk-js/assets/294518/41092641-e462-47fe-9c8c-eaf2b96a4e20">

**Comment by daker** [comment]
It works for me with the background with Chrome 114.0.5735.201 (Official Build) (64-bit)
![image](https://github.com/Kitware/vtk-js/assets/878518/6ae511d9-3658-42f2-9b94-9fc9ab0b86a1)

**Comment by daker** [comment]
The result from the chrome performance tab, json file inside the zip if you want to load in Chrome devtools
![image](https://github.com/Kitware/vtk-js/assets/878518/a7b3c090-889f-4fdf-9f52-b60d3aaf312c)
[Trace-20230719T173245.zip](https://github.com/Kitware/vtk-js/files/12096764/Trace-20230719T173245.zip)

**Comment by xut-d** [comment]
Thank you very much for your professional answer, I can use it normally after adding ViewAPI = webgp
