### ISSUE TITLE
[Bug] Error in ColorTransferFunction when indexed Lookup Mode is used

### ISSUE THREAD

**Issue by katiamar63** [Kitware/vtk-js#2881]
### Bug description

In getColor() function   there is a call to getNodeValue function where returned value is passed by function argument (array). 
https://github.com/Kitware/vtk-js/blob/188c7fb379a87b97f39262659d4a66aedc2e88d3/Sources/Rendering/Core/ColorTransferFunction/index.js#L395-L398

But getNodeValue is setting 6-element array instead of object with r,g,b properties as above.
https://github.com/Kitware/vtk-js/blob/188c7fb379a87b97f39262659d4a66aedc2e88d3/Sources/Rendering/Core/ColorTransferFunction/index.js#L962-L976

So the code in getColor should be:
```
 rgb[0] = nodeVal[1];
 rgb[1] = nodeVal[2];
 rgb[2] = nodeVal[3];
```

### Steps to reproduce

Any use of `ColorTransferFunction` with `setIndexedLookup(true)`

### Expected Behavior

The getColor function should return color indiced by annotation, instead undefined values are returned.

### Environment

- vtk.js version: 17.17.x
- Browsers: any
- OS: any

**Comment by floryst** [comment]
Thanks for catching that! Would you like to submit a PR to fix this? It looks like a simple change. If not, I can get to it later.

**Comment by floryst** [comment]
This might be a feature deficiency in vtkColorTransferFunction. My first guess would be to fill the gaps in the lookup table with dummy values to see if that does the trick for you. We will look into this further.
