### ISSUE TITLE
[Maintenance] Deprecate DistanceWidget

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#2891]
### Feature Request

Deprecate the Distance widget in favor of the Line widget.

### Motivation and Detailed Description

The Line widget is more flexible than the Distance widget. Having both is unnecessary, so the Distance widget should be removed.

The proposed approach would be to remove the Distance widget in the next major release.

**Comment by Julesdevops** [comment]
https://github.com/Kitware/vtk-js/commit/31b1b930b98aebf82a83530c732be0838d80318a
