### ISSUE TITLE
WebGL-2 issue with Mac

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#291]
I've noticed an issue with the newer versions that implement webgl2.  I get the following warnings in my browser console:

In Chrome:
- [Offscreen-For-WebGL-0x7fa0b690ea00]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: invalid internalformat/format/type combination GL_R8_EXT/GL_RED_EXT/GL_FLOAT
- [Offscreen-For-WebGL-0x7fa0b690ea00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

In Firefox:
- Error: WebGL warning: texImage2D: Mismatched internalFormat and format/type: 0x8229 and 0x1903/0x1406

If I force it to use WebGL1 instead the warnings disappear and the images render correctly.  I haven't really had a chance to dig into the differences between 1 and 2 that could be causing this.  Any thoughts or help would be greatly appreciated.  Thanks! 

PS: for future reference, is it better to post these kind of topics here or through the mailing list?? Thanks!!

**Comment by martinken** [comment]
Here is probably best and thanks for the report.  To help me narrow down the issue can you tell me what you are doing when it happens? Such as Volume Rendering or rendering a Image Slice with  the image mapper? And do you know the raw type of your data such as float, unsigned char, short etc?


Thanks!

**Comment by llangholz89** [comment]
I'm using the Image Mapper to render an image slice and the data is of type short (Int16Array).  Your question prompted me to try with a different dataset, and when attempting the same pipeline with a dataset of type float, it seemed to render just fine with WebGL2.  However, interestingly that seemed to break other parts of my code, namely the slider I have to adjust the window/level properties of the image slice (probably a separate issue though...)

If it's at all helpful, here's a bit of the index.json file for the data sets
short: 
```
  ...
  "vtkClass": "vtkImageData", 
  "pointData": {
    "arrays": [
      {
        "data": {
          "numberOfComponents": 1, 
          "name": "SCALARS", 
          "vtkClass": "vtkDataArray", 
          "dataType": "Int16Array", 
          "ranges": [
            {
              "max": 1705.0, 
              "component": null, 
              "min": 0.0
            }
          ],
   ...
```
float:
```
  ...
  "vtkClass": "vtkImageData", 
  "pointData": {
    "arrays": [
      {
        "data": {
          "numberOfComponents": 1, 
          "name": "SCALARS", 
          "vtkClass": "vtkDataArray", 
          "dataType": "Float32Array", 
          "ranges": [
            {
              "max": 1.7084298133850098, 
              "component": null, 
              "min": -0.13133132457733154
            }
          ],
  ...
```

**Comment by martinken** [comment]
Can you try a one line fix and see if it works for you?  

In Sources/Rendering/OpenGL/RenderWindow/index.js line 192. The default: statement is going to the same clause as UNSIGNED_CHAR when it should be moved down to line 201 and use the same path as FLOAT.

```
diff --git a/Sources/Rendering/OpenGL/RenderWindow/index.js b/Sources/Rendering/OpenGL/RenderWindow/index.jsindex 7760b26..9a5e6c4 100644
--- a/Sources/Rendering/OpenGL/RenderWindow/index.js
+++ b/Sources/Rendering/OpenGL/RenderWindow/index.js
@@ -189,7 +189,6 @@ function vtkOpenGLRenderWindow(publicAPI, model) {
   publicAPI.getDefaultTextureInternalFormat = (vtktype, numComps, useFloat) => {
     if (model.webgl2) {
       switch (vtktype) {
-        default:
         case VtkDataTypes.UNSIGNED_CHAR:
           switch (numComps) {
             case 1: return model.context.R8;
@@ -199,6 +198,7 @@ function vtkOpenGLRenderWindow(publicAPI, model) {
             default:
               return model.context.RGBA8;
           }
+        default:
         case VtkDataTypes.FLOAT:
           switch (numComps) {
             case 1: return model.context.R16F;
```

**Comment by llangholz89** [comment]
Yep, that seemed to fix the issue! It renders correctly and the console warnings are gone.  Thanks for the help!

**Comment by martinken** [comment]
Should be fixed in https://github.com/Kitware/vtk-js/pull/293
