### ISSUE TITLE
[Bug] Wrong data range when array contains NaN values

### ISSUE THREAD

**Issue by FedericoNegri** [Kitware/vtk-js#2920]
### Bug description

Trying to visualize this VTP file containing a data array on a mesh: [array_with_nans.zip](https://github.com/Kitware/vtk-js/files/12646702/array_with_nans.zip)

The array "contact pressure;32" contains a lot of NaN values (as expected) and can be visualized correctly in Paraview (note the range [0, 1.6E+9])
![image](https://github.com/Kitware/vtk-js/assets/11756875/9d4a2d7c-857e-40ff-be72-420cd8807123)

With vtkjs, when I query the range with `data.getRange()` I get [NaN, NaN].

### Steps to reproduce

You could for instance open the file attached above in Glance and notice these errors
![image](https://github.com/Kitware/vtk-js/assets/11756875/343a7613-71d3-4252-8881-54cd71752c2d)

### Detailed Behavior

I noticed this doesn't happen for arrays with NaN values in general. I think it only happens for those with NaN as first value (like in my case), maybe because of the min/max initialization in `fastComputeRange`?
https://github.com/Kitware/vtk-js/blob/9af4da13a961ce671a40343ec77376e61a55d67c/Sources/Common/Core/DataArray/index.js#L24

### Expected Behavior

The returned range should be [0, 1626058368]. 

### Environment

- vtk.js version: 28.6.0
- Browsers: Edge
- OS: Windows

**Comment by finetjul** [comment]
Thanks for your detailed report.

Can you please [contribute a PullRequest](https://github.com/Kitware/vtk-js/blob/master/CONTRIBUTING.md) to fix the error ?

**Comment by FedericoNegri** [comment]
@finetjul there you go https://github.com/Kitware/vtk-js/pull/2921
