### ISSUE TITLE
rotation doesn't work correctly with 3D vtk Image volume [Bug] 

### ISSUE THREAD

**Issue by gzt036** [Kitware/vtk-js#2949]
### Bug description

3D vtk image data can be read and rendered properly as long as no rotation is done on the object. Once rotated, a simple operation like actor.rotateZ(30) will render incorrectly. 

### Steps to reproduce

an example codesandbox is here

https://codesandbox.io/s/jgzzhh?file=/src/index.js

if you uncomment the line 
//const {renderer, renderWindow} = createFullScreenRenderWindow(containerRef);
and comment out line
const { renderer, renderWindow } = createGenericRenderWindow(containerRef);

you will see correct render behaviour. But this only works with codesanbox. On win11 vscode neither line works. 

### Expected Behavior

image object should be rendered correctly after rotation

wrong behaviour
![image](https://github.com/Kitware/vtk-js/assets/52687412/6a770220-7f80-4b03-8060-8d31f93a53a9)
correct behaviour
![image](https://github.com/Kitware/vtk-js/assets/52687412/0c3b43b7-7ed7-4062-8946-c3f5102141a4)

### Environment

- vtk.js version: "@kitware/vtk.js": "^29.0.0, earlier versions upto one year earlier probably the same.
- Browsers:  chrome, edge
- OS: win11

**Comment by gzt036** [comment]
any plan to fix it?

**Comment by bruyeret** [comment]
This issue looks a lot like #2922 
I think that they are the same bug

**Comment by gzt036** [comment]
just a hint, it does appear to work with createFullScreenRenderWindow() on codesandbox setting, although on my local machine with vscode nothing works. 

since it works in certain cases, maybe the fix does not require too much coding involved.

**Comment by gzt036** [comment]
Dear vtk.js team, I would consider this a critical bug as 3D volume rendering is what makes vtk.js superior to other libraries like three.js.  Rotating an actor in 3D scene is a basic operation,  not being able to do so severely restricts its potential applications, e.g., arranging two volume together in a scene in a reasonable way. 

Also, since the rotation functions works in some specific cases, fixing it does not appear to write lots of new code, though a detailed knowledge of vtk.js and debugging work are required.  Hope this can be fixed ASAP, thanks.
