### ISSUE TITLE
Rendering issue on Safari/Chrome with iOS +10

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#295]
I tried to render a scene on an apple device with iOS 10.
It crashes if the scene contains more than 300 000 pts.
When the scene contains approximately 50 000 pts, it works most of the time.

Does anyone have already had this problem ?

**Comment by laurennlam** [comment]
I think we found the problem. The iPhone device have a very limited RAM. If we try to load a bench of data with a global weight superior to 80-85Mo, it crashes. It's easy to test by adding a vtkSphereSource into a renderer and changing phi and theta. You can compare the weight by doing the same thing in paraview.

I hope it's clear. Thanks for your help...

**Comment by martinken** [comment]
I hear you, but 300K points seems really small.  When I looked at this issue earlier when you posted, I noticed some people saying safari only allows up to 10 MB per webgl context. But the reports were not clear and 10 Meg seems absurdly small.

**Comment by laurennlam** [comment]
@martinken it's my first project in vtkjs, maybe i'm not doing well some things, I don't know. I'll be surprised when we figured out the problem. But yes, maybe it wasn't clear or not enough accurate. I forgot to mentionned that the data weight 30Mo (normals, tcoords,...). We found that we also loaded a skybox with 6 images weighed 7Mo  and some little mesh. So maybe it began to be heavy for a phone device.
But you can reproduce it by creating a sphere in a simple renderwindow with thetaResolution = 2000 and phiResolution = 976 and then, launch it into an iOS device. If you increase one of these resolution, it crash.

Sorry for the inconvenience.
