### ISSUE TITLE
[Bug] VTKJS is so slow on MAC

### ISSUE THREAD

**Issue by zuoPang** [Kitware/vtk-js#2962]
### Bug description

When VTKJS renders a large grid, it is stuck on a specific MAC, and Threejs can be rendered smoothly. (1) Under the mac, Firefox and Safair can be rendered smoothly; (2) Chrome can also be rendered smoothly when the user-anonle = metal is opened.

### Steps to reproduce

Load a large grid model casually and rotate the model in the scene. The performance is very stuck

### Expected Behavior

Metal can be automatically used in the Mac environment

### Environment

- vtk.js version:25.15.1
- Browsers:Chrome 119.0.6045.159
- OS:Mac Book Pro (2018), Sonoma 14.1.1

**Comment by sysuyl** [comment]
Similar problem on my mac(MacbookPro 2016) + Chrome.

Test link,
threejs example demo: https://threejs.org/editor/
vtkjs example demo:  https://kitware.github.io/vtk-js/examples/STLReader/index.html

Test mesh,
about 300,000 faces

**Comment by jourdain** [comment]
Can someone provide a sample stl file?

**Comment by zuoPang** [comment]
[model.zip](https://github.com/Kitware/vtk-js/files/13577867/model.zip)
Loading these two models at the same time will cause lag when rotating in the scene.

**Comment by sysuyl** [comment]
hello, here is a test file.
[nefertiti.zip](https://github.com/Kitware/vtk-js/files/13578128/nefertiti.zip)

**Comment by zuoPang** [comment]
[model.zip](https://github.com/Kitware/vtk-js/files/13578177/model.zip)

https://github.com/Kitware/vtk-js/assets/151905221/da710ff7-9354-411c-9aec-b707e575308e

After loading the model, it cannot rotate normally and is very stuck.

**Comment by zuoPang** [comment]
> hello, here is a test file. @jourdain [nefertiti.zip](https://github.com/Kitware/vtk-js/files/13578128/nefertiti.zip)

After loading this model, it is still very stuck.

**Comment by zuoPang** [comment]
> @zuoPang @sysuyl can you do this test and see if it does solve the issue ? go to about:flags in Chrome, "Choose ANGLE graphics backend", and choose "Metal", restart the browser then do the test again
> 
> Chrome bug: [crbug.com/1245448](https://crbug.com/1245448)

This is OK, thank you, but I hope to find a way that you don't need to set the chrome setting manually. There is no good way to find a good way so far

**Comment by daker** [comment]
it's a Chrome bug on MAC with AMD GPU and i don't think there is something to do unless Chrome changes the backend by default

**Comment by sysuyl** [comment]
> Just tried both models on Mac M1 with Safari and Chrome and everything was fine. Could you try [Glance](https://kitware.github.io/glance/app/) and see which GPU get used in your setup. You may have to force your GPU to be used. <img alt="Screenshot 2023-12-06 at 09 46 44" width="1333" src="https://private-user-images.githubusercontent.com/294518/288482985-8a26196b-be4b-4240-9b7e-5c06ae764d60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTk1NjIsIm5iZiI6MTcwMTk5OTI2MiwicGF0aCI6Ii8yOTQ1MTgvMjg4NDgyOTg1LThhMjYxOTZiLWJlNGItNDI0MC05YjdlLTVjMDZhZTc2NGQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQwMTM0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDQ5ZGZkZjU1YjZmOTRkNjhiMjUyMzk5YTdjM2Y5MzBjNDI0N2VkNTI3MDY3NTk5NzhjMTgxYmIwZTQ1MTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-e2Qk5o7IVFXcg79KFuVGL90MrfguDp1kfszE4ABGOs">

@jourdain hello, here is my mac shows,
![image](https://github.com/Kitware/vtk-js/assets/1774010/45dd592a-382f-4e6f-a367-d3e3fc1257eb)

**Comment by sysuyl** [comment]
I also want to know why Threejs can render smoothly.

**Comment by jourdain** [comment]
Threejs makes a different assumption than vtk.js. VTK is aimed at scientific visualization (support big mesh, off-center, interpolate before mapping, etc.), which generates more complex GL, which can be slower with some drivers/GPU.

**Comment by sysuyl** [comment]
Thanks @jourdain . I have indeed found that the rendering of more complex applications based on Threejs on my Mac is also quite sluggish.
