### ISSUE TITLE
[Bug] Incorrect behaviour Cfun and Ofun for ImageMapper after v27.4.2

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#2964]
### Bug description

This seems to be a long lasting bug that was never hit, until this PR that set back the `DEFAULT_VIEW_API` to `WebGL` inside `Sources/Rendering/Core/RenderWindow/index.js` in [this PR](https://github.com/Kitware/vtk-js/pull/2814). It appears that there are a mix of these issues 

**Cfun Issues (No Ofun)**
-  Scaling Issues (?): When I increase the values significantly (0, 100, 200), at least something is displayed. However, webGPU can accurately display the red and green even for lower values (0, 1, 2).
-  Color Accuracy (?): The green appears darker in the webGL version compared to the webGPU version.

**Ofun Issues (with Cfun)**
-  When we add the ofun, the webGL version completely malfunctions.
-  I believe there might be a bug in the webGPU version since I don't see any changes from the ofun having an effect on the rendering. However, this could be due to the limited support of webGPU, which is understandable.### Steps to reproduce

try this example and play with the `DEFAULT_VIEW_API` in `Sources/Rendering/Core/RenderWindow/index.js` to `WebGL` or `WebGPU`

```js
import 'vtk.js/Sources/favicon';
import 'vtk.js/Sources/Rendering/Profiles/Volume';

import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkImageMapper from 'vtk.js/Sources/Rendering/Core/ImageMapper';
import vtkImageSlice from 'vtk.js/Sources/Rendering/Core/ImageSlice';
import vtkImageData from 'vtk.js/Sources/Common/DataModel/ImageData';
import vtkDataArray from 'vtk.js/Sources/Common/Core/DataArray';
import vtkColorTransferFunction from 'vtk.js/Sources/Rendering/Core/ColorTransferFunction';
import vtkPiecewiseFunction from 'vtk.js/Sources/Common/DataModel/PiecewiseFunction';

const BACKGROUND = 0;
const LOW_VALUE = 100;
const HIGH_VALUE = 200;

const fullScreenRenderWindow = vtkFullScreenRenderWindow.newInstance({
  background: [0, 0, 1],
});
const renderWindow = fullScreenRenderWindow.getRenderWindow();
const renderer = fullScreenRenderWindow.getRenderer();

const imageData = vtkImageData.newInstance();
const dims = [100, 100, 1];
imageData.setSpacing(1, 1, 1);
imageData.setOrigin(0.1, 0.1, 0.1);
imageData.setDirection(1, 0, 0, 0, 1, 0, 0, 0, 1);
imageData.setExtent(0, dims[0] - 1, 0, dims[1] - 1, 0, dims[2] - 1);

imageData.computeTransforms();

const values = new Float32Array(dims[0] * dims[1] * dims[2]);

let i = 0;
for (let y = 0; y < dims[1]; y++) {
  for (let x = 0; x < dims[0]; x++, i++) {
    if ((x < 30 && y < 30) || (x > 70 && y > 70)) {
      values[i] = BACKGROUND;
    } else if (x > 40 && x < 60 && y > 40 && y < 70) {
      values[i] = LOW_VALUE;
    } else {
      values[i] = HIGH_VALUE;
    }
  }
}

const dataArray = vtkDataArray.newInstance({
  numberOfComponents: 1,
  values,
});
imageData.getPointData().setScalars(dataArray);
imageData.modified();

const cfun = vtkColorTransferFunction.newInstance();
const ofun = vtkPiecewiseFunction.newInstance();

cfun.addRGBPoint(LOW_VALUE, 1, 0, 0);
cfun.addRGBPoint(HIGH_VALUE, 0, 1, 0);
ofun.addPoint(BACKGROUND, 0);
ofun.addPoint(LOW_VALUE, 0.5);
ofun.addPoint(HIGH_VALUE, 0.5);
ofun.setClamping(false);

const actor = vtkImageSlice.newInstance();
const mapper = vtkImageMapper.newInstance();

actor.getProperty().setRGBTransferFunction(0, cfun);
actor.getProperty().setScalarOpacity(0, ofun);
actor.getProperty().setInterpolationTypeToNearest();

mapper.setInputData(imageData);
actor.setMapper(mapper);
actor.getProperty().setInterpolationTypeToNearest();

renderer.addActor(actor);
renderer.resetCamera();
renderer.resetCameraClippingRange();
renderWindow.render();

global.fullScreen = fullScreenRenderWindow;

````

Set the DEFAULT_VIEW_API back to webGPU and see the correct colors, but current default is 'WebGL'

Correct: [code sand box with vtk.js 27.4.1](https://codesandbox.io/p/sandbox/append-poly-data-transfer-function-forked-ggkqmw?file=%2Fsrc%2Findex.js%3A19%2C48&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpwv3dsj00063b6hv2bm75vc%2522%252C%2522sizes%2522%253A%255B79.5748987854251%252C20.425101214574894%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpwv3dsj00023b6h5uj1gc09%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpwv3dsj00033b6h1hgfx8av%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpwv3dsj00053b6hsn9jsqi3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.34473245588827%252C51.65526754411173%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpwv3dsj00023b6h5uj1gc09%2522%253A%257B%2522id%2522%253A%2522clpwv3dsj00023b6h5uj1gc09%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpx47vhk00023b6gmepgqqt7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A48%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpx47vhk00023b6gmepgqqt7%2522%257D%252C%2522clpwv3dsj00053b6hsn9jsqi3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpwv3dsj00043b6h1bdgl3xx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpwv3dsj00053b6hsn9jsqi3%2522%252C%2522activeTabId%2522%253A%2522clpwv3dsj00043b6h1bdgl3xx%2522%257D%252C%2522clpwv3dsj00033b6h1hgfx8av%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpwv3dsj00033b6h1hgfx8av%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![image](https://github.com/Kitware/vtk-js/assets/7490180/c9ef5336-c51d-475d-b774-8713cc0a9755)

![image](https://github.com/Kitware/vtk-js/assets/7490180/1e2d4e6c-99d7-4807-8870-5cee63b4be67)

![image](https://github.com/Kitware/vtk-js/assets/7490180/cac63e77-c196-4c4d-aa93-e53634d38a2a)

![image](https://github.com/Kitware/vtk-js/assets/7490180/c545494a-6f1b-4596-a3e5-aea14d909d8f)

### Detailed Behavior

Seems like since the default was 'WebGPU' for the file in `Sources/Rendering/Core/RenderWindow/index.js`, this bug was not hit for WebGL until that change in https://github.com/Kitware/vtk-js/pull/2814. I really don't know where to look for it, since it seems like a long lasting bug

### Expected Behavior

Should have colors match the webGPU. However, I believe there is another bug in WebGPU where the ofun does not really have any effect (which might be by design and experimental webGPU?)

### Environment

- vtk.js version: most recent, but really after 27.4.2
- Browsers: Chrome
- OS: MacOS

**Comment by sedghi** [comment]
Seems like it is about 

`Sources/Rendering/WebGPU/RenderWindow/index.js`

vs

`Sources/Rendering/OpenGL/RenderWindow/index.js`

**Comment by sedghi** [comment]
Ok seems like we need to add the points for all indices

```js
for (let j = 3; j < 255; j++) {
  cfun.addRGBPoint(j, 0, 1, 0);
}
```

But it is not necessary for the VolumeMapper, hmmmmmm

**Comment by finetjul** [comment]
I'm confused, what's wrong with [this](https://codesandbox.io/p/sandbox/incorrect-cfun-imagemapper-forked-qsq7nd) example ? It seems that the rendering is what you expect from the code. No ?

**Comment by sedghi** [comment]
That is probably fine (it has issues i can explain) but make the LOW and High to 1 and 2 and you see the actual more important issue

**Comment by finetjul** [comment]
This is because you are using a vtkImageMapper. 
By default, `vtkImageProperty` ignores the image and lookuptable scalar range and solely relies on `vtkImageProperty` Window/Level. 
You need to call `setUseLookupTableScalarRange(true);`

**Comment by sedghi** [comment]
I see, thanks.

- Is there a specific reason why the color look-up table implementation or behavior differs between image and volume mappers?
- And also is there any specific reason the 'WebGPU' does not require that to set `setUseLookupTableScalarRange(true);`? 
- Also seems like `WebGPU` does not implement the ofun, I guess this is known limitation?

**Comment by finetjul** [comment]
> Is there a specific reason why the color look-up table implementation or behavior differs between image and volume mappers

I believe it is because Window/Level does not make sense as-is in Volume mappers (due to the opacity subtility)

> And also is there any specific reason the 'WebGPU' does not require that to set `setUseLookupTableScalarRange(true);`?

I can't think of a specific reason. Must be an omission.

> Also seems like WebGPU does not implement the ofun, I guess this is known limitation?

It depends known to whom. I think it is also missing and should be therefore be added.

**Comment by sedghi** [comment]
Alright thanks, I guess I will close this then
