### ISSUE TITLE
[Bug] Likely memory leak when using vtkHttpDataSetReader

### ISSUE THREAD

**Issue by dominik-werner-casra** [Kitware/vtk-js#2978]
### Bug description

When using vtk.js in a SPA where the displayed CT image data is changed without refreshing the page, the browser's memory usage continuously increases until parts of the page stop working.
As a workaround we have removed the usage of ```vtkHttpDataSetReader.setUrl()``` from our code and replaced it with our own implementation which omits the problem. However, our own method is not as feature rich as ```vtkHttpDataSetReader```.

### Steps to reproduce

To reproduce this problem, we have created a very simple nodejs application with two different pages:
- **http://localhost:8080/example_with_issue.html**: This uses the ```vtkHttpDataSetReader.setUrl()``` method and causes the memory to be filled while the sequence runs.
- **http://localhost:8080/example_with_workaround**: This uses the custom method to load data and allows the browser to dispose old data.

To run the examples extract the zip archive and in the folder run:
```bash
node server.js
```

The server uses samples from **kitware.github.io** that are served in a way that the client cannot cache them in order to simulate many different CT images.
[vtk_memory_leak_demo.zip](https://github.com/Kitware/vtk-js/files/13842815/vtk_memory_leak_demo.zip)

### Detailed Behavior

When using vtk.js in a SPA where the displayed CT image data is changed without refreshing the page, the browser's memory usage continuously increases until parts of the page stop working, usually with an error similar to this:
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint16Array (<anonymous>)
    at r (<anonymous>:2:1727148)
    at Vk.e.create3DFromRaw (<anonymous>:2:1740847)
    at Vk.e.create3DFilterableFromRaw (<anonymous>:2:1741812)
    at Nz.e.buildBufferObjects (<anonymous>:2:2117370)
    at Nz.e.updateBufferObjects (<anonymous>:2:2115011)
    at Nz.e.renderPieceStart (<anonymous>:2:2112251)
    at Nz.e.renderPiece (<anonymous>:2:2114756)
    at Nz.e.volumePass (<anonymous>:2:2093181)
```
As a workaround we have removed the usage of ```vtkHttpDataSetReader.setUrl()``` from our code and replaced it with our own implementation which omits the problem:
```javascript
const NEW_ARRAY = {
    'Uint8Array': arr => arr,
    'Uint16Array': arr => new Uint16Array(arr.buffer, arr.byteOffset, arr.byteLength / Uint16Array.BYTES_PER_ELEMENT),
    'Int16Array': arr => new Int16Array(arr.buffer, arr.byteOffset, arr.byteLength / Int16Array.BYTES_PER_ELEMENT)
}

/**
 * Custom method for loading CT data for vtk.js viewport
 * @param {*} url Url of the CT data
 * @returns Promise
 */
function loadDataCustom(url) {
    return new Promise(resolve => {
        const indexUrl = [url, 'index.json'].join('/');
        fetch(indexUrl).then(response => {
            // fetch the metadata of the CT volume
            response.text().then(json => {
                const manifest = JSON.parse(json);
                const dataset = vtk(manifest);
                const payloadUrl = [url, 'data', `${manifest.pointData.arrays[0].data.ref.id}.gz`].join('/');
                
                // fetch the array data
                fetch(payloadUrl).then(response => {
                    response.blob().then(data => {
                        data.arrayBuffer().then(buffer => {
                            // decompress data and map it to proper array type
                            const arrayData = manifest.pointData.arrays[0].data;
                            const decompressed = fflate.decompressSync(new Uint8Array(buffer));
                            const array = NEW_ARRAY[arrayData.dataType](decompressed);
                            array.values = array;

                            // build vtk array object
                            const metaArray = {
                                array: {
                                    ...arrayData,
                                    buffer: array.buffer,
                                    size: array.length,
                                    values: array.values
                                },
                                enabled: true,
                                location: 'pointData',
                                name: 'ImageFile',
                                registration: 'setScalars'
                            };
                            delete metaArray.array.ref;

                            const newArray = vtk.Common.Core.vtkDataArray.newInstance(metaArray.array);

                            dataset['getPointData']()[metaArray.registration](newArray);
                            delete metaArray.registration;

                            dataset.modified();

                            resolve(dataset);
                        });
                    });
                })
            });
        });
    });
}
```
A comparison running both implementations in the Chrome browser (Version 120.0.6099.200 (Official Build) (64-bit)) on Windows 10 x64 for 1'000 image changes yields the following results:
| Implementation | Memory used by browser |
|--|--|
| vtkHttpDataSetReader.setUrl() (vtk.js) | ~ 5'060 MB |
| loadDataCustom() (ours) | ~ 419 MB |

However, our own method is not as feature rich as ```vtkHttpDataSetReader```. Through debugging and inspection of the source code it seems that the problem may originate from the global variable ```const cachedArrays = {};``` in **Sources/IO/Core/HttpDataSetReader/index.js** where data is never removed.

### Expected Behavior

In the case vtk.js is used in the context of a SPA, old data that is no longer displayed needs to be disposed to limit memory consumption.

### Environment

- vtk.js version: 29.3.2
- Browsers: Chrome (Version 120.0.6099.200 (Official Build) (64-bit))
- OS: Windows 10 x64

**Comment by finetjul** [comment]
Thanks for the report.
Can you try to see how to clear the `cachedArrays` global variable and make a PR  ?

**Comment by dominik-werner-casra** [comment]
I am a bit hesitant since I don't know what the consequences are when doing this. Since the vtk.js implementation is very stateful I see the risk of potentially breaking the promise chain if ```cachedArrays``` is cleared. This is why we chose the stateless approach with our workaround.
Would you be willing to give me some hints how the whole thing is supposed to work? ```cachedArrays``` keeps track of unfinished requests as well as far as I can tell.

**Comment by dominik-werner-casra** [comment]
After looking again at the code I think I have an idea. The problem is actually here:

Sources/IO/Core/HttpDataSetReader/index.js
```javascript
// Cache the promise while fetching
cachedArrays[arrayId] = model.dataAccessHelper
  .fetchArray(publicAPI, model.baseURL, array, options)
  .then((newArray) => {
    // Replace the promise with the array in cache once downloaded
    cachedArrays[arrayId] = newArray;
    return newArray;
 });
```
I guess we could introduce a size limit for the cache that can be configured and would be something reasonable by default (e.g. 2048 MB). Then once the limit is reached, we can dispose the oldest entries. Of course we also need to keep track which entries have been accessed when.
I will create a branch and try to implement this, after that I will create a PR.

**Comment by dominik-werner-casra** [comment]
@finetjul I have created the PR #2979. It fixes the issue and adds a few convenient features. Would be nice if you could guide me through the process.

**Comment by floryst** [comment]
Closing, as this should be resolved now.
