### ISSUE TITLE
[Feature] How to remove CT bed/shadows in a CT image

### ISSUE THREAD

**Issue by StevenRoger** [Kitware/vtk-js#2984]
### Feature Request

![image](https://github.com/Kitware/vtk-js/assets/15900201/d3d5eb71-7844-447c-ab1d-1e1c84794af0)

How to remove the bed in a 3D view, similar to the display in 3D Slicer?

### Motivation and Detailed Description

Remove CT bed/shadows in a CT image

**Comment by finetjul** [comment]
Removing the CT bed is an image processing algorithm.

In Slicer it is performed by [this code](https://github.com/PerkLab/SlicerSandbox/blob/master/RemoveCtTable/RemoveCtTable.py#L251-L353).

You can do image processing in a web browser using [itk.wasm](https://wasm.itk.org/en/latest/). ITK.wasm integrates with VTK.js.

**Comment by StevenRoger** [comment]
thx
