### ISSUE TITLE
how does the cow.vtp is generated

### ISSUE THREAD

**Issue by fanhenghui** [Kitware/vtk-js#3]
I have get the vtk volume render data by the vtk software,but i donnot konw how to use the vtk.js library to show it in the web broswer,and how the .gz data is generate is generated

**Comment by jourdain** [comment]
Volume rendering is not yet supported by the vtk.js library.
VTK.js is still in development and hasn't been released yet.
The cow was generated using ParaView with the Python script from the repository.

If you have ParaView on your system and node.js, you can run the following:

```sh
$ npm install -g kitware/vtk-js
$ vtkDataConverter 

  Usage: vtkDataConverter [options]

  Options:

    -h, --help                output usage information
    -V, --version             output the version number
    -i, --input [file.vtk]    Input data file to convert
    -o, --output [directory]  Destination directory
    
    -m, --merge               Merge dataset
    -e, --extract-surface     Extract surface
    
    --paraview [path]         Provide the ParaView root path to use
    --sample-data [path]      Convert sample data from ParaViewData
```
