### ISSUE TITLE
Translucent Rendering with ImageSlice and ImageMapper

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#304]
I'm attempting to adjust the opacity of image slices using the ImageSlice/ImageMapper classes.  Looking at the source for the ImageSlice actor I see that the default returns for .getIsOpaque() is true and .hasTranslucentPolygonalGeometry() is false.  There's also some comments about always rendering during opaque pass and eventually rendering images in layers.  I guess my question is what does the implementation for that approach entail, and, if it is rather complicated/involved are there any short term approaches to get around this behavior? 

Ideally, I'd like to display images with translucent NaN values and/or overlay images on top of one another.  Thanks for the help, I appreciate the support!

**Comment by AndreFrelicot** [comment]
I'm having the same problem :

model.actor.getProperty().setOpacity(0.5); //does nothing

Any update on that ?

thank you

**Comment by jourdain** [comment]
@martinken

**Comment by martinken** [comment]
I don't think it is implemented yet. Not a big change, just not done yet.

**Comment by alfredomp** [comment]
@martinken could you give us a hint on where to make this change? @katiamar63 and I would like to contribute to this functionality.

We are right now checking this file https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/ImageSlice/index.js

**Comment by lujx123** [comment]
How to superimpose coordinates in SWC files on images displayed by vtk.js

**Comment by jourdain** [comment]
Do you mean a Adobe Flash file?

**Comment by lujx123** [comment]
> 你的意思是Adobe Flash文件？
No, it is some 3d coordinates. The 3d coordinates of the file need to be displayed on the image displayed by vtk.js, which is similar to displaying some coordinates of points and lines on the image.

Do you have detailed contact information?I ask you a lot of questions.

**Comment by lujx123** [comment]
> Do you mean a Adobe Flash file?

No, it is some 3d coordinates. The 3d coordinates of the file need to be displayed on the image displayed by vtk.js, which is similar to displaying some coordinates of points and lines on the image.

Do you have detailed contact information?I ask you a lot of questions.

**Comment by jourdain** [comment]
https://www.kitware.com/what-we-offer/#support

**Comment by lujx123** [comment]
> https://www.kitware.com/what-we-offer/#support

I don't quite understand what you mean, can you provide corresponding services, or do you have ready-made software to fulfill this requirement?

**Comment by jourdain** [comment]
Kitware is a consulting company that produce OpenSource software. If you have a lot of questions and/or need help with your development we can help you via support contracts.
