### ISSUE TITLE
[Bug] Memory leak in WidgetState

### ISSUE THREAD

**Issue by Antti-Palola** [Kitware/vtk-js#3062]
### Bug description

Instantiating for example a plane widget and properly removing the widget and its manager with delete leaks memory.

### Steps to reproduce

* Instantiate a widget
* Delete widget
* Widget state leaks memory

### Detailed Behavior

Loaded widgets three times, notice the groups of 3 distinct size, which are all different different states when loading the same view three times.

![Screenshot 2024-04-22 at 09 54 02](https://github.com/Kitware/vtk-js/assets/100124171/fe2a12c7-b3fe-4203-ab5e-528c82e5557d)

Cause would seem to be https://github.com/Kitware/vtk-js/blob/21534d1515f234c5034f9ec1c1e423575379a14d/Sources/Widgets/Core/WidgetState/index.js#L57 that pushes a callback in `unbindState`

### Expected Behavior

No memory leaks

### Environment

- vtk.js version: main of 22.4.2024 ([21534d1](https://github.com/Kitware/vtk-js/commit/21534d1515f234c5034f9ec1c1e423575379a14d))
- Browsers: Chrome
- OS: Mac OS 14.3.

**Comment by Antti-Palola** [comment]
Could someone take a look at this? Shouldn't the unbind state remove the callback rather than add it?

**Comment by floryst** [comment]
I'll take a look at this.

**Comment by floryst** [comment]
This appears to be a leak only in vtkLineWidget. The logic you linked shouldn't leak, since it unsubscribes from all nested states, removes the nested state, then re-subscribes to the remaining nested states. In effect, removing the associated subscription with the removed nested state.
