### ISSUE TITLE
[Feature] Unfreezing New Instances 

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#3108]
### Feature Request

Currently, the `publicAPI` gets frozen in the macro using `Object.freeze`.

```js
function newInstance(
  mixins,
  initialValues,
  publicAPI = {},
  model = {},
  skipWidgetState = false
) {
  if (!skipWidgetState) {
    vtkWidgetState.extend(publicAPI, model, initialValues);
  }

  for (let i = 0; i < mixins.length; i++) {
    const mixin = MIXINS[mixins[i]];
    if (mixin) {
      mixin.extend(publicAPI, model, initialValues);
    } else {
      vtkErrorMacro('Invalid mixin name:', mixins[i]);
    }
  }
  macro.safeArrays(model);

  return Object.freeze(publicAPI);
}
```

It is often desirable to assign metadata to an instance, such as IDs or references. However, this is currently not possible because the instance is frozen.

### Motivation and Detailed Description

Would you be willing to remove this constraint? Alternatively, could you suggest a way for me to achieve this  without creating a `myImageData`?

**Comment by jourdain** [comment]
You can add those directly on the model by calling `myVtkInstance.set("myId", anything)` and `myVtkInstance.get("myId").myId`

**Comment by jourdain** [comment]
Another option would be to add some kind of mixin into the newInstance arg...

**Comment by sedghi** [comment]
Thanks a lot @jourdain

**Comment by sedghi** [comment]
@jourdain 

Your suggested approach doesn't seem to work at the moment.

I've created a CodeSandbox to demonstrate this issue.

https://codesandbox.io/p/sandbox/blending-my897d

what i have done is 

```js
imageData.set("stuff", [1, 2, 3]);
console.log("stuff", imageData.get("stuff"));
```

and here is the log

![CleanShot 2024-08-06 at 12 06 47@2x](https://github.com/user-attachments/assets/4d89a77a-4e1b-4b5e-9acc-6c32b28db1cf)

**Comment by jourdain** [comment]
Sorry I guess my API memory was a bit rusty...

```js
imageData.set({ dataType, id });
const userData = imageData.get("id", "dataType");
console.log(userData.id, userData.dataType)
```

**Comment by sedghi** [comment]
Worked great thanks!

**Comment by sedghi** [comment]
@jourdain I tried to override a method in imageData, and it throws an error, i know this is not usually done, but in my case i need to show a warning for using a method

I tried this 

imageData.getScalars = () => {
  console.warn ('')
}

any comment how i can work around this?

**Comment by jourdain** [comment]
Inheritance is the only way, but you can easily inline that.
