### ISSUE TITLE
Abnormal image display[Bug] 

### ISSUE THREAD

**Issue by HuWei501** [Kitware/vtk-js#3112]
### Bug description

When opening a PET file, black pixel blocks appear. I find that the CT values ​​of these pixels are very high. How can I solve this abnormal display?
![1723018786532](https://github.com/user-attachments/assets/56937b7d-2ae6-4c4e-a833-3411c75b3240)

### Steps to reproduce

Open the file at https://kitware.github.io/glance/app/
[pet.nii.gz](https://github.com/user-attachments/files/16520561/pet.nii.gz)

### Expected Behavior

![image](https://github.com/user-attachments/assets/724da248-02cb-4ec5-ad95-aecadea2786f)
In ITK-SNAP, you can see that the image does not have similar black pixels.

### Environment

- vtk.js version: 28.12.4
- Browsers: chrome 127.0.6533.89
- OS:

**Comment by floryst** [comment]
That might be a colormap issue in Glance. For medical images, I would recommend you try using [VolView](https://volview-dev.kitware.app/) instead. (Just a note: VolView presently doesn't support `.nii.gz` files, only uncompressed `.nii` files.)

**Comment by HuWei501** [comment]
Yes. This issue has been fixed in version 29.5.1
