### ISSUE TITLE
[Bug] Unable to user RemoteView to connect to pvserver in paraview 5.13 following the example

### ISSUE THREAD

**Issue by AlbertoPa** [Kitware/vtk-js#3120]
### Bug description

The approach described in the RemoteView example ( https://kitware.github.io/vtk-js/examples/RemoteView.html ) to connect to a pvserver instance does not work with paraview 5.13 since wslink is missing.

Installing vtk[web] with pip leads to another error showing missing dependencies. Specifically, the module paraview.modules.vtkRemotingClientServerStream is not found.

### Steps to reproduce

Configure vtk.js and start a pvserver with the script provided using pvpython from paraview 5.13.
Create a python environment and install vtk[web] using pip.

### Detailed Behavior

After following the above steps, the following is shown:

```
ParaView is using venv: .venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alber\Documents\MyRemoteDataVisualizer\pvserver.py", line 5, in <module>
    from paraview.web import pv_wslink
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'
```

### Expected Behavior

A remote pvserver instance is started and ready to connect to the remote view in vtk.js.

### Environment

- vtk.js version: 3.1.2
- Browsers: Edge
- OS: Windows 11

**Comment by jourdain** [comment]
It looks like your venv have a vtk in it which conflict with the one that is part of ParaView.

**Comment by AlbertoPa** [comment]
Thanks @jourdain, as usual you saved the day (and I need to become more familiar with environments 😅).
I installed vtk[web] because the first error I received when I did not have wslink suggested doing that, and I did not think about a conflict.

Closing, since your answer resolved the issue.
