### ISSUE TITLE
[Feature] Support for HDR images

### ISSUE THREAD

**Issue by daker** [Kitware/vtk-js#3145]
### Motivation

Support for the Radiance HDR (RGBE) image format for environment maps

### Detailed Description

Add a new vtkHDRReader

```js
const reader = vtkHDRReader.newInstance();
reader.parse(fileReader.result);
const imageData = reader.getOutputData();
```

**Comment by finetjul** [comment]
You can read it with ITK.wasm, VTK.js makes it easy to read itkImages.

**Comment by daker** [comment]
I did make one using JS, is it worth to propose it as PR ?

**Comment by finetjul** [comment]
wow, cool.
Yes, if it makes sense to have it in VTK.js to not require a third-party dependency.
