### ISSUE TITLE
[Feature] Support for TGA images

### ISSUE THREAD

**Issue by daker** [Kitware/vtk-js#3155]
### Motivation

Support for the [Truevision Targa](https://fr.wikipedia.org/wiki/Truevision_Targa) (TGA) for textures.

### Detailed Description

Add a new vtkTGAReader

```js
const reader = vtkTGAReader.newInstance();
reader.parse(fileReader.result);
const imageData = reader.getOutputData();
```

**Comment by finetjul** [comment]
Being curious here, is this still a standard format ? What software still produce/consume file format ?

**Comment by daker** [comment]
well it still used specially in game development, software like GIMP, Photoshop, Blender, Maya, 3ds Max, Nuke still support TGA format.
