### ISSUE TITLE
[Bug] vtkAngleWidget sometimes does not display

### ISSUE THREAD

**Issue by jwrepo** [Kitware/vtk-js#3178]
### Bug description

![GIF 2024-11-22 16-47-04](https://github.com/user-attachments/assets/a366f4c8-b876-434b-a81a-1ca3f3db71e9)

### Steps to reproduce

open this url https://kitware.github.io/vtk-js/examples/AngleWidget.html

### Expected Behavior

Normal display

### Environment

- vtk.js version: https://kitware.github.io/vtk-js/examples/AngleWidget.html
- Browsers: Edge
- OS: Win11

**Comment by finetjul** [comment]
This is because the camera must be reset: `renderer.resetCamera();`

Because the camera does not need to be reset in 2D views, it is not something the widget should do automatically. It should be done by the application, not the widget.
