### ISSUE TITLE
[VTU] Using VTK.JS to open .vtu or .vtk files

### ISSUE THREAD

**Issue by Front-end-tao2** [Kitware/vtk-js#3180]
### Motivation

Greetings to the esteemed author. I am failing to open VTU files or VTK files using VTK.JS, is this feature still not available? In other words, I want to visualise VTU files in WEB, not in desktop application.

### Detailed Description

 Also, I would like to ask if there is any other way to achieve what I need. Thank you very much for reading and recovering. Thanks!

**Comment by finetjul** [comment]
Already answered by those 2 issues:

- https://github.com/Kitware/vtk-js/issues/3066
- https://github.com/Kitware/vtk-js/issues/976

**Comment by Front-end-tao2** [comment]
Thank you very much for the author's reply and for your contribution to the visualisation direction, but based on your reply I still haven't come up with a suitable solution as I'm not familiar with C++. I would like to further ask you one other question and hope to get your reply. Thanks.  
What I need to do in my assignment is to visualise an ODB file (a result generated by the simulation software ABAQUS) onto a web page, so far my thought process has been to convert it to VTU and then visualise it onto a web page, but that doesn't seem to work. I contacted a company whose technicians achieved this, but I don't know their exact details. I have listed his explanation below:
“The front-end uses three.js, the back-end uses the entityFramework framework to query the data from the data into the list, and the list is converted to json via Newtonsoft.”  
It seems they use some method of conversion to json
I've shown their realisations below as well:
![image](https://github.com/user-attachments/assets/9f1982a8-879e-4201-8bff-395842000b45)

Does the author have any advice for me? How can I achieve this goal?  Thank you very much for your reply! Thanks! Best wishes to the development team.

**Comment by finetjul** [comment]
You can post-process the VTU file server-side to extract the surface of the volumetric mesh (i.e. create a VTP) and to visualize the surface in VTK.js.

**Comment by finetjul** [comment]
This is correct.

**Comment by Front-end-tao2** [comment]
I appreciate your reply, thank you!

**Comment by floryst** [comment]
Yes, VTK C++ [supports visualizing VTU files](https://examples.vtk.org/site/Cxx/IO/ReadUnstructuredGrid/).
