### ISSUE TITLE
[Bug] vtkXMLPolyDataWriter lose PolyData FieldData

### ISSUE THREAD

**Issue by wumanman1024** [Kitware/vtk-js#3186]
### Bug description

1.  create a polydata
2. create a  dataArray
3. create a fieldData
4. append dataArray to fieldData
5. polyData set fieldData
6. vtkXMLPolyDataWriter wite the polyData
7. look demo.vtp file, XML lose  <FieldData></FieldData>

### Steps to reproduce

`import vtk from 'vtk.js/Sources/vtk';
import vtkDataArray from 'vtk.js/Sources/Common/Core/DataArray';
import vtkPolyData from 'vtk.js/Sources/Common/DataModel/PolyData';
import vtkXMLPolyDataWriter from 'vtk.js/Sources/IO/XML/XMLPolyDataWriter';

// 创建一个简单的 polyData
const polyData = vtkPolyData.newInstance();
polyData.setPoints(new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]));

// 创建 fieldData
const fieldArray = vtkDataArray.newInstance({
 name: 'ExampleFieldData',
 values: new Float32Array([10]),
});
const fieldData = vtk.Common.Core.vtkFieldData.newInstance();
fieldData.addArray(fieldArray);

// 给 polyData 设置 fieldData
polyData.setFieldData(fieldData);

// 使用 vtkXMLPolyDataWriter 导出 polyData 为 VTP 格式
const writer = vtkXMLPolyDataWriter.newInstance();
writer.setInputData(polyData);
writer.setFormat('binary'); // 或使用 ASCII 格式

// 注意：该代码示例可能需要根据你的具体环境进行适当的调整`

### Expected Behavior

i hope vtp file include fieldData

### Environment

  "name": "@kitware/vtk.js",
  "version": "32.7.2",

**Comment by finetjul** [comment]
Yes, apparently the [Field data are omitted](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/XML/XMLPolyDataWriter/index.js#L29-L88). 
Would you mind to create a PR?

**Comment by wumanman1024** [comment]
Could you please update the npm package as soon as possible? My project is somewhat urgent.
