### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#339]
I have a class which instanciate a vtk.js view (renderer, render window, openglRenderWindow) from a div name. I need to recreate several times this class like this :
```
this.instance = new myClass('divName');
this.instance = new myClass('divName');
...
this.instance = new myClass('divName');
```
I've a memory issue by doing this, so I tried to set `this.instance` to null before recreate the class :
```
this.instance = new myClass('divName');
this.instance = null;
this.instance = new myClass('divName');
```
But I always had memory issues. The size of the memory heap continue to increase.
Then I tried to add a method into the class which set to null all attributes and then set this.instance to null :
```
uninitialize() {
this.renderer = null;
this.renderWindow = null;
this.openglRenderWindow = null;
...
}
```
```
this.instance = new myClass('divName');
this.instance.uninitialize();
this.instance = null;
this.instance = new myClass('divName');
```

But I still use too many memory.
I tried to check the memory with chrome and as I understand, the overuse of memory seems to come from vtk.js object which are not deleted by the garbage collector.
So the question is, is there a way to completely delete an object which contains renderer, renderwindow, openglRenderwindow,... ?

**Comment by jourdain** [comment]
vtkObject instance have a `delete()` method which empty the model.
But I think the issue is related to the fact you might bind something to the DOM and forget to unbind it. 

BTW, you can look at the test code since we clean the memory between each test. That way you could see what needs to be done.
Before we did that, after 10 WebGL tests, the browser would crash.

**Comment by laurennlam** [comment]
@jourdain Thanks for these precisions. I never think about unbinding something to DOM...
I'll test what you've suggest and come back here to confirm that it works better. Thanks !

**Comment by laurennlam** [comment]
@jourdain I don't have any memory issue anymore. I use the delete() method to vtkObject and unbinds event from the container.
Thanks again for your reactivity !
