### ISSUE TITLE
publicAPI.handlePinch Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by thewtex** [Kitware/vtk-js#361]
```
Uncaught TypeError: Cannot read property 'x' of undefined
    at Object.publicAPI.handlePinch (http://localhost:8000/itkVtkImageViewer.js:22263:37)
    at Object.<anonymous> (http://localhost:8000/itkVtkImageViewer.js:36238:44)
    at http://localhost:8000/itkVtkImageViewer.js:852:35
    at Array.forEach (<anonymous>)
    at Object.publicAPI.(anonymous function) [as invokePinch] (http://localhost:8000/itkVtkImageViewer.js:851:15)
    at Object.publicAPI.(anonymous function) [as pinchEvent] (http://localhost:8000/itkVtkImageViewer.js:38084:38)
    at HTMLDivElement.publicAPI.handleWheel (http://localhost:8000/itkVtkImageViewer.js:37945:15)
```

on Linux Desktop / Chromium browser 61.0.

The debugger points to

```
  publicAPI.handlePinch = function () {
    var pos = model.interactor.getEventPosition(model.interactor.getPointerIndex());
    publicAPI.findPokedRenderer(pos.x, pos.y);
    if (model.currentRenderer === null) {
      return;
    }
```

After updating [itk-vtk-image-viewer](https://github.com/Kitware/itk-vtk-image-viewer) to vtk-js 5.1.1.

Mouse scroll-based zoom no longer works.

CC: @jourdain @laurennlam

**Comment by laurennlam** [comment]
Which vtk.js file is concerned by this error ? Do you have a small example of using itk-vtk-image-viewer, so I can test it.

**Comment by thewtex** [comment]
@laurennlam The error is [occuring here](https://github.com/Kitware/vtk-js/blob/3be862163130eaae04d49c4334a6dfaedab58b5b/Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js#L111-L134). I am testing [this branch](https://github.com/thewtex/itk-vtk-image-viewer/tree/vtk-bump) and a [debug deploy is available here](http://59df5d03a700c4173311a99b.chambermaid-guests-83431.netlify.com/).

**Comment by laurennlam** [comment]
@thewtex Which data did you use on the debug deploy ?

**Comment by thewtex** [comment]
@laurennlam [This data](https://data.kitware.com/#item/59df612e8d777f31ac641e37) can be used, for example.

**Comment by laurennlam** [comment]
I used the data and the link you sent to test and I have no errors when zooming/dezooming on the data

**Comment by thewtex** [comment]
Are you using a system without a touchscreen?

**Comment by laurennlam** [comment]
Yes. On the computer.

**Comment by thewtex** [comment]
After some more experiments, I noticed that this is a bug in the Chrome Dev Tools when emulating a mobile device on a desktop system without a touch screen.
