### ISSUE TITLE
ParallelProjection bug

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#377]
Hi All,

I have some troubles to use the `setParallelProjection` on the vtkCamera. I can't call the `resetCamera()` if the parallelProjection is set to true. All objects on the scene disappear if the parallelProjection is set and then I call `resetCamera()`. Do you have any ideas on where it comes from ( @jourdain ) ? Or how to solve this ? Thanks in advance.

**Comment by martinken** [comment]
Are you on master?

**Comment by martinken** [comment]
Or at least have pulled recently

**Comment by laurennlam** [comment]
I work on a project with vtk.js 5.1.6. I'll test with 5.1.8.

**Comment by laurennlam** [comment]
looks better ! Thanks :)
