### ISSUE TITLE
Capture mouse event when several render window

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#384]
I have three render windows in three different div :
```
<div id="root">
			<div id="container1">Z</div>
			<div id="container2">Y</div>
			<div id="container3">X</div>
</div>
```
The first container takes the whole `root `height and the half `root `width. The two others take half of `root `width and half of `root `height.

I implemented a custom interactor style that catches mouse position. The problem is, the mouse position is relative to the `root` and I'd like it to be relative to the container (the render window where the cursor is).

How can I do it ? I would get the render window position and then, subtract it to the mouse position, but I didn't find something like that.

Does anyone have any idea ?

**Comment by jourdain** [comment]
Did you validate the layout and the true position of your contrainerX?

How do you get the mouse coordinate? Are you using offsetX, offsetY?

**Comment by jourdain** [comment]
That for touch, but it would be true to for any mouse event.

https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js#L230

**Comment by laurennlam** [comment]
My bad, I forgot to use the bounding container attributes as in your example. Here is the right code I use to capture mouse position : 
```
function getMousePosition() {
	const eventPosition = model.interactor.getEventPosition(model.interactor.getPointerIndex());
	const boundingContainer = model.container.getBoundingClientRect();
	const position = {
		x: eventPosition.x - boundingContainer.left,
		y: eventPosition.y + boundingContainer.top
	};
	return position;
}
```
