### ISSUE TITLE
Example ZipHttpReader

### ISSUE THREAD

**Issue by Hansonnnn** [Kitware/vtk-js#396]
why it turns to express "main.js:2 Uncaught ReferenceError: exports is not defined" when I use ZipHttpReader's javascript file (I open the file by ".ts" and complied it by "tsc").Thank for your answer later~~

**Comment by jourdain** [comment]
I think we need more information regarding your build process and configuration as vtk.js needs to be transpile as it is written in ES6 or ES2015. The code is not TypedScript, so I'm not sure to follow what you did.

**Comment by Hansonnnn** [comment]
okay.maybe I misunderstand it. Thank for your help. let's me try again.

**Comment by jourdain** [comment]
This guide will walk you through building a project from an example. You can swap that example and use the ZipHttpReader if you'd like.

https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

**Comment by Hansonnnn** [comment]
thank for your help~ I have solve it .
