### ISSUE TITLE
How to run web

### ISSUE THREAD

**Issue by yundian** [Kitware/vtk-js#4]
I read the docs and execute $ npm install kw-web-suite --save-dev.But what should I do later?

**Comment by yundian** [comment]
How to get on the web？

**Comment by jourdain** [comment]
What do you mean? VTK.js is library which will require you to write some code before getting anything working into the web. 

How do you plan to write your Web application while leveraging vtk.js?
What are the technologies you want to use to build and develop your application?

If you plan to use npm with webpack, you can see some sample applications here: 
https://kitware.github.io/vtk-js/examples/ConeSource.html
