### ISSUE TITLE
(almost) all links in CONTRIBUTING.md are dead

### ISSUE THREAD

**Issue by TristanWright** [Kitware/vtk-js#40]
Points a lot to `Documentation/dev/git` which doesn't exist anymore? @jourdain

**Comment by aronhelser** [comment]
That's the path inside ParaView - likely a copy-paste mistake.

**Comment by TristanWright** [comment]
so should it point to the vtk gitlab docs? 

https://gitlab.kitware.com/vtk/vtk/blob/master/Documentation/dev/git/develop.md

**Comment by jourdain** [comment]
I have no idea sorry...
