### ISSUE TITLE
insure -> ensure

### ISSUE THREAD

**Issue by TristanWright** [Kitware/vtk-js#41]
a few instances of this one is a method name, definitely supposed to be ensure right? 

https://github.com/Kitware/vtk-js/search?utf8=%E2%9C%93&q=insure

**Comment by aronhelser** [comment]
Yes, true, according to AP, but they can also be 'interchangeable'.
'ensure' makes more sense to me.
https://www.google.com/#q=insure+vs+ensure

**Comment by TristanWright** [comment]
Wow I've never seen it [interchanged](https://en.wiktionary.org/wiki/insure) (definition 3). I think 'ensure' makes more sense too, will be changing it ...

**Comment by TristanWright** [comment]
closed with fe36884
