### ISSUE TITLE
Interactively setting window/level results in all black image

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#426]
Setting the window/level via mouse drag on an image results in a black image.

Steps to reproduce: Run `npm run example ImageMapper` and interactively set the window/level by dragging the mouse.

**Comment by martinken** [comment]
Probably the recent changes to support color transfer functions on images. I'll try taking a look next week.

**Comment by martinken** [comment]
Fixed in https://github.com/Kitware/vtk-js/pull/429
