### ISSUE TITLE
vtkRenderer: actors in separate layers intersect each other

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#465]
This occurs in the OrientationMarkerWidget and its corresponding example. The orientation cube shown below is in the highest valued layer, presumably the foreground layer. The cone is in the lowest valued layer, presumably the background layer.

The expected behavior is that the orientation cube is always in front of the cone due to being on the foreground layer. The observed behavior is that while the cube is mostly in front, the cone can still intersect and obscure parts of the cube, as shown in the image below.

![image](https://user-images.githubusercontent.com/1812167/34129428-157624ca-e412-11e7-8866-e54e97d31771.png)

**Comment by martinken** [comment]
Yes, I know exactly what the issue is, and I'll try coming up with a fix in the next few days.

**Comment by martinken** [comment]
Any chance one of you could give this a try on your case?

https://github.com/Kitware/vtk-js/pull/479

 @jourdain @floryst

**Comment by floryst** [comment]
Yes, this fixes the above layer issue.

**Comment by martinken** [comment]
Awesome! Thanks for checking!
