### ISSUE TITLE
vtk.js not working anymore on Chrome/macOS

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#472]
```
Uncaught TypeError: Cannot read property 'blendFuncSeparate' of null
    at Object.e.initialize (Cone.js:1)
    at e.buildPass (Cone.js:1)
    at Object.e.apply (Cone.js:1)
    at Object.e.traverse (Cone.js:1)
    at Object.e.traverse (Cone.js:1)
    at Object.e.traverseAllPasses (Cone.js:1)
    at Object.e.forceRender (Cone.js:1)
    at Object.e.render (Cone.js:1)
    at Object.e.initialize (Cone.js:1)
    at i (Cone.js:1)
```

**Comment by jourdain** [comment]
The context does not get created...

**Comment by martinken** [comment]
Seems google fixed the issue in Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by dmarquez83** [comment]
Cannot read property 'blendFuncSeparate' of null.

I have the version Versión 65.0.3325.146 (Build oficial) (64 bits) and my problem persists I would like to know how you solved it

**Comment by jourdain** [comment]
Did it work?

**Comment by dmarquez83** [comment]
if it worked, killing rl chrome

**Comment by jourdain** [comment]
Yes, did killing Chrome solved the issue?

**Comment by mix3d** [comment]
I don't mean to dig up an old thread, but our Sentry logs are reporting this same issue for much newer versions of Chrome: 

v89.0.4389
Windows 10

**Comment by jourdain** [comment]
@mix3d which version of vtk.js? I'm wondering if this start showing up due to our work in progress on WebGPU?

**Comment by mix3d** [comment]
I'm excited to hear you've already started on WebGPU (will hopefully fix our volume size bottleneck, better 16-bit texture pipelines, etc), we're still on `"vtk.js": "^12.1.2"`

**Comment by mix3d** [comment]
I recognize v12 is very old now. I will spend some time in the next few weeks to update to pre-webGPU v16 or v15 and see what that does.

**Comment by jourdain** [comment]
I don't remember if we did much improvement on volume/slice rendering between 12-16. I don't think you will see much differences.
