### ISSUE TITLE
Rendering of multiple volumes are not intermixed or sorted correctly

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#473]
When one of the two volume `visibility` property is disable, the reset camera works as expected but the supposedly invisible volume still manage to show up when within the near/far camera clip plane...

To reproduce:
- Load 2 volumes.
- Turn the visibility of one of the volume off
- rotate the view until you manage to still see the volume that should not be visible.

**Comment by jourdain** [comment]
<img width="1299" alt="screen shot 2018-01-02 at 3 25 47 pm" src="https://user-images.githubusercontent.com/294518/34502596-689376f6-efd1-11e7-87d2-1902e3a29368.png">

Also some blending front/back issue....

<img width="1299" alt="screen shot 2018-01-02 at 3 29 46 pm" src="https://user-images.githubusercontent.com/294518/34502682-d959408c-efd1-11e7-96ed-c84f50f404ca.png">

<img width="1299" alt="screen shot 2018-01-02 at 3 30 00 pm" src="https://user-images.githubusercontent.com/294518/34502686-dddbac30-efd1-11e7-95bf-91ceef92899f.png">

**Comment by martinken** [comment]
Multi volume rendering is not implemented. It can be, but it isn't right now. It involves some non-trivial changes to handle nicely (supporting multiple intermixed volumes) Probably a few days to implement.

**Comment by martinken** [comment]
The visibility issue is a bug and should be fixed by https://github.com/Kitware/vtk-js/pull/478

**Comment by martinken** [comment]
@jourdain is the two volume visibility issue still an issue? My look at the code says it is fine. If the only issue is proper multivolume merging then I will leave as a feature request

**Comment by jourdain** [comment]
Yes the order of the volumes remain the same as they were inserted.
Meaning the blending between them is not correct. But maybe that is expected in our current implementation?

**Comment by jourdain** [comment]
Sorry I was talking about something else in my previous comment. 

The visibility toggle works fine.
