### ISSUE TITLE
ImageMapper / ImageSlice

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#474]
It seems that sometime changing the slice position may result in an invalid texture which seems to happen very easily if the normal slice is the X axis.

<img width="1299" alt="screen shot 2018-01-02 at 3 19 40 pm" src="https://user-images.githubusercontent.com/294518/34502397-7f1f3cbc-efd0-11e7-99b5-394533751be4.png">
 
<img width="1299" alt="screen shot 2018-01-02 at 3 20 13 pm" src="https://user-images.githubusercontent.com/294518/34502402-86041ebc-efd0-11e7-878b-640f7c08b0bf.png">

**Comment by martinken** [comment]
Do you see this on 

https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html

because I'm not seeing it

**Comment by jourdain** [comment]
That example is working fine for me...

**Comment by martinken** [comment]
Should be fixed in https://github.com/Kitware/vtk-js/pull/480
