### ISSUE TITLE
NaN Color not respected in Image's color transfer function

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#489]
I'd like to apply a particular color and opacity to NaN values within an image dataset.  However, setting the NaN color on the image's color transfer function doesn't seem to produce the expected result, nor does using the default NaN color for a particular color map.

**Comment by daker** [comment]
@llangholz89 
Can you please try again, otherwise close the bug.

**Comment by floryst** [comment]
Closing due to age, but if this is still an issue please re-open with more info on the expected result.
