### ISSUE TITLE
Volumetric rendering of ImageData with non-orthogonal axes

### ISSUE THREAD

**Issue by mkhorton** [Kitware/vtk-js#499]
Is this currently possible? We're looking at vtk.js to render a large quantity of volumetric data files of crystallographic data, but the volumes do not always have orthogonal axes, but come with a 3x3 matrix specifying the axes/co-ordinate system of the volume.

Many thanks for any help you can offer.

**Comment by martinken** [comment]
I think it  should work. It should be easy to test as vtk.js includes a sample dataset that has a direction (still orthogonal) but it would be easy to change that to be non orthogonal and I think it should work.

See https://github.com/Kitware/vtk-js/blob/master/Data/volume/headsq.vti/index.json and look near the bottom for the direction section.

**Comment by mkhorton** [comment]
Thanks -- I tried running the example using the headsq.vti via npm run example (this was the VolumeContour example, not a volumetric render, but I'm guessing it's the same) and changing the direction value, but it didn't seem to change anything in the resulting visualization.

Is there any documentation for `direction` somewhere? -- it looks like vtkImageData might not support including a transform. vtkStructuredGrid might, but I don't know how/if that works with vtk.js

**Comment by martinken** [comment]
That example (computing an iosofurface) probably does not use the direction which is a bug in the isosurface filter. The volume rendering does use it though. Try the volume mapper example.

**Comment by mkhorton** [comment]
Ah I'd missed that example in the repo, I was looking in the main Examples folder.

I can confirm the transformation is applied, but it seems to result in some graphical glitches. I've attached a static screenshot but it's difficult to describe what's going on. I'll try it again with some of our own data to see if I can get a better understanding of what's happening.

<img width="1317" src="https://user-images.githubusercontent.com/2976580/34890450-d315e844-f786-11e7-8d9a-275940201d71.png">

Screenshot is taken with:

```
  "direction": [
      0.866, 0.5, 1,
      -0.5, 0.866, 0,
      0, 0, 1
  ],
```

**Comment by agirault** [comment]
Hi @mkhorton,

We did some recent improvements to the ImageMapper to support flips and permutations in the direction matrix when slicing along X, Y, Z, which means it will slice correctly when either I, J or K are aligned with your slicing axis.

We'll look at supporting non-orthogonal axis soon.

**Comment by mkhorton** [comment]
Excellent, thanks for the update @agirault :)

We have an application ready and waiting for it if you make it, so very much looking forward to seeing it. Does adding interpolation mean that render quality could be improved too?

**Comment by floryst** [comment]
This should be fixed.
