### ISSUE TITLE
Resize openglRenderWindow

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#508]
I use element-resize-detector npm package to catch window resize event. When the window is been resized, here is the code I launch : 
```
const containerDimensions = this.container.getBoundingClientRect();
this.openglRenderWindow.setSize(containerDimensions.width, containerDimensions.height);
this.renderer.resetCamera();
this.renderer.resetCameraClippingRange();
this.interactor.render();
this.renderWindow.render();
```
The problem is that the openglRenderWindow has the good size, but 3D elements are deformed until I click on the renderWindow.
Does anyone have any idea how to solve this problem ?

**Comment by jourdain** [comment]
I do remember that issue a while back, but that was fix. Which version of vtk.js are you using?

**Comment by laurennlam** [comment]
I use a very old version. I didn't check that...
So I'll try with the last version of vtk.js and let you know if it's fix. Thanks @jourdain.
