### ISSUE TITLE
Integrating VTK-JS with Python pipeline

### ISSUE THREAD

**Issue by rlizzo** [Kitware/vtk-js#517]
Hello all,

I am hoping someone could provide some direction on how to begin integrating a pre-existing Python VTK application with VTK-JS? Essentially, I have a [large application](https://github.com/vmtk/vmtk) which uses VTK and ITK to process data and render the images and polydata (along with capturing user input) with the standard VTK OpenGL render windows. 

For a variety of reasons (performance wise and for integration into ipython/Jupiter notebooks) I would like to move all rendering and interaction to VTK-JS, while still controlling application flow and logic with the python/C++ layer. 

I'm wondering if there are any example applications which i use a similar model, or if there is any documentation hidden away which could explain how to send/receive data and initialize a VTK-JS app?

Thanks,
Rick

**Comment by jourdain** [comment]
Look at that project as it is exactly doing that but just using ITK on the server side.

https://github.com/KitwareMedical/vtkVolViewVessels

**Comment by rlizzo** [comment]
Thanks perfect! Thank you so much @jourdain!

**Comment by thewtex** [comment]
CC: @aylward
