### ISSUE TITLE
can I load local .vtp file

### ISSUE THREAD

**Issue by tomhaitao** [Kitware/vtk-js#530]

**Comment by jourdain** [comment]
Yes, you can look at the example / application here which does exactly that: https://kitware.github.io/vtk-js/examples/GeometryViewer.html

**Comment by doczoidberg** [comment]
nice to see development on the file formats.
no time steps are supported yet? Would it be difficult to implement?

**Comment by jourdain** [comment]
That can be managed at the application level.

**Comment by doczoidberg** [comment]
can you give a code hint?

**Comment by jourdain** [comment]
https://github.com/Kitware/arctic-viewer/blob/master/lib/types/VTKGeometry.js

load the data structure that the following script generate

https://github.com/Kitware/arctic-viewer/blob/master/scripts/examples/paraview/samples/VTKGeometry-can.py

And the inside time handling is done here

https://github.com/Kitware/paraviewweb/blob/master/src/Rendering/Geometry/VTKGeometryBuilder/index.js
