### ISSUE TITLE
External controls and properties access - best approches

### ISSUE THREAD

**Issue by AndreFrelicot** [Kitware/vtk-js#536]
Hello,

I need to externalise the controls (dot not use the controlPanel/addController system). The vtkjs architecture is getting clearer in my mind (functional inheritance, props, representation, events...). 

But how can you manage widget ?  I need to delete the instances I created when I want, so I have an array of Widgets but when I delete an instance the elements are not removed from the rendering and I get a bunch of events error when interacting. Should I dig into the widget instance and detach/delete all the need elements manually ??

Like this:

```
this._lineWidgetList.forEach(element => {
          console.log("Try delete %o", element);
          
          console.log("element.getWidgetRep()");
          console.log(element.getWidgetRep());

          element.getWidgetRep().getActors().forEach(actor => {
            console.log("Try deleting actor");
              element.getWidgetRep().getRenderer().removeActor(actor)
              actor.delete();
          });

          element.setInteractor(null);
          element.setWidgetRep(null); 

```
But if still gives me events errors. Is there a clean way to achieve this ?
thank you

vtk.js version : 5.13.3

André

```
Uncaught TypeError: Cannot read property 'getOpacity' of undefined
    at index.js:242
    at Array.forEach (<anonymous>)
    at Object.publicAPI.pick (index.js:239)
    at Object.publicAPI.pick (index.js:139)
    at Object.publicAPI.computeInteractionState (index.js:92)
    at Object.publicAPI.moveAction (index.js:207)
    at Object.publicAPI.handleMouseMove (index.js:93)
    at Object.<anonymous> (index.js:66)
    at _loop (macro.js:745)
    at Object.invoke [as invokeMouseMove] (macro.js:739)

```

**Comment by jourdain** [comment]
`setEnable(false)` and `element.setInteractor(null)` should be good, but I'm not super familiar with the Widget API so I might be missing something else.

@martinken @laurennlam  ?

**Comment by AndreFrelicot** [comment]
Thank you it's good.

then I remove the widget from the list and delete it :
`this._lineWidgetList = this._lineWidgetList.filter(item => item !== element)`

Now I'll find the best way to serialise the actors/widgets  :)

**Comment by jourdain** [comment]
```
const str = JSON.stringify(actor.getState());
const newActor = vtk(JSON.parse(str));
```
