### ISSUE TITLE
Transfer function widget spans colors only over the window viewed

### ISSUE THREAD

**Issue by thewtex** [Kitware/vtk-js#554]
The transfer function editor currently always spreads colors across the entire range of the input data even when only a small window is selected with non-zero opacity. This limits contrast in hue or intensity. By using the entire range of colors for the values spanned by the minimum and maximum of the Gaussians used, visualization will be greatly enhanced. This also corresponds to the standard behavior when selecting a window/level for viewing a 2D image.

![current](https://user-images.githubusercontent.com/25432/35701957-b1ad172e-0765-11e8-83b9-d489042cf6fc.png)

![desired](https://user-images.githubusercontent.com/25432/35701966-bdd22c74-0765-11e8-98bf-47db4e58d1e9.png)

CC: @jourdain @martinken

**Comment by jourdain** [comment]
I can enable a mode where the lut range get updated based on the opacity window...

**Comment by thewtex** [comment]
Awesome, thank you, @jourdain !
