### ISSUE TITLE
Passing multiple vtp files via URL?

### ISSUE THREAD

**Issue by ibrahimshibani** [Kitware/vtk-js#590]
I apologize as this is not exactly an issue with the software but I was wondering if there is a way to pass multiple ".vtp" files to one of the viewers such as : 
[https://kitware.github.io/vtk-js/examples/GeometryViewer/GeometryViewer.html?fileURL=https://data.kitware.com/api/v1/item/59e12d848d777f31ac645553/download](url)
via the "?fileURL" query. Thank you.

**Comment by jourdain** [comment]
We can certainly edit the example to support such use case using ?fileURL=[url1,url2,url3...]

**Comment by ibrahimshibani** [comment]
Thank you for the swift response. It would be a small but useful addition I think.
