### ISSUE TITLE
Load local Binary Structured points VTK

### ISSUE THREAD

**Issue by YoneMoreno** [Kitware/vtk-js#604]
**Hello and thank you for reading this question.**

I have one doubt because of I have installed vtkjs correctly and set up the example project as: https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

I would like to load a local VTK file not a URL one, and I have been using as a reference: https://kitware.github.io/vtk-js/examples/PolyDataReader.html

However how could we load a local file?

I have tried:
`import 'vtk.js/Sources/favicon';

import vtkActor from 'vtk.js/Sources/Rendering/Core/Actor';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkMapper from 'vtk.js/Sources/Rendering/Core/Mapper';
import vtkPolyDataReader from 'vtk.js/Sources/IO/Legacy/PolyDataReader';

const fileName = 'sphere.vtk'; // 'uh60.vtk'; // 'luggaBody.vtk';

// ----------------------------------------------------------------------------
// Standard rendering code setup
// ----------------------------------------------------------------------------

const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance();
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();

const resetCamera = renderer.resetCamera;
const render = renderWindow.render;

// ----------------------------------------------------------------------------
// Example code
// ----------------------------------------------------------------------------

const reader = vtkPolyDataReader.newInstance();
reader.setUrl(`/dist/dist/bunny.vtk`).then(() => {
    const polydata = reader.getOutputData(0);
    const mapper = vtkMapper.newInstance();
    const actor = vtkActor.newInstance();

    actor.setMapper(mapper);
    mapper.setInputData(polydata);

    renderer.addActor(actor);

    resetCamera();
    render();
});

// -----------------------------------------------------------
// Make some variables global so that you can inspect and
// modify objects in your browser's developer console:
// -----------------------------------------------------------

global.reader = reader;
global.fullScreenRenderer = fullScreenRenderer;`

And the output we got is:

**GET http://localhost:8080/dist/dist/bunny.vtk 404 (Not Found)**

![imagen](https://user-images.githubusercontent.com/22214901/36493637-f93f8992-1727-11e8-920e-8ba00ca61691.png)

In addition the architecture is:

![imagen](https://user-images.githubusercontent.com/22214901/36493610-e9066d66-1727-11e8-8910-ad30a8776733.png)

**Also as the title suggests: Is it possible to load binary VTK structured points data?**

**Thank you for your help!**

**Comment by jourdain** [comment]
You will need to use a FileReader and an `<input type="file" />`.

Many example do exactly that. Like the [GeometryViewer](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) which can load any vtp file.

**Comment by jourdain** [comment]
BTW you need to fix your project tree. It is very confusing to have several nested `/dist/` and `/src/` in 'dist/`.

I bet you have trouble understanding what's going on. I would feel the same...

**Comment by YoneMoreno** [comment]
Thank you for your help jourdain!

I have tried to understand first and then to apply the example given. I have created the div and the input type file static in the index.html:

`<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="myContainer"></div>
<input type="file" id="fileInput">
<script type="text/javascript" src="MyWebApp.js"></script>
</body>
</html>`



Then in the index.js I have added:

`
import HttpDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';

const fileInput = document.getElementById("fileInput");

function handleFile(e) {
    console.log(e);
    preventDefaults(e);
    const dataTransfer = e.dataTransfer;
    const files = e.target.files || dataTransfer.files;
    if (files.length > 0) {
        load(myContainer, {files});
    }
}

fileInput.addEventListener('change', handleFile);

function preventDefaults(e) {
    e.preventDefault();
    e.stopPropagation();
}

function load(container, options) {
    autoInit = false;
    emptyContainer(container);

    if (options.files) {
        createViewer(container);
        let count = options.files.length;
        while (count--) {
            loadFile(options.files[count]);
        }
        updateCamera(renderer.getActiveCamera());
    } else if (options.fileURL) {
        const urls = [].concat(options.fileURL);
        const progressContainer = document.createElement('div');
        progressContainer.setAttribute('class', style.progress);
        container.appendChild(progressContainer);

        const progressCallback = (progressEvent) => {
            const percent = Math.floor(
                100 * progressEvent.loaded / progressEvent.total / (urls.length + 1)
            );
            progressContainer.innerHTML = `Loading ${percent}%`;
        };

        createViewer(container);
        const nbURLs = urls.length;
        let nbLoadedData = 0;

        /* eslint-disable no-loop-func */
        while (urls.length) {
            const url = urls.pop();
            const name = Array.isArray(userParams.name)
                ? userParams.name[urls.length]
                : `Data ${urls.length + 1}`;
            HttpDataAccessHelper.fetchBinary(url, {
                progressCallback,
            }).then((binary) => {
                nbLoadedData++;
                if (nbLoadedData === nbURLs) {
                    container.removeChild(progressContainer);
                }
                createPipeline(name, binary);
                updateCamera(renderer.getActiveCamera());
            });
        }
    }
}
`

As result after building and starting the web server it outputs:

`Uncaught ReferenceError: autoInit is not defined
    at load (MyWebApp.js:22313)
    at HTMLInputElement.handleFile (MyWebApp.js:22301)`

So then the screen is:

![imagen](https://user-images.githubusercontent.com/22214901/36496284-b2dccb2e-172f-11e8-919b-ca7ca4830b1f.png)



I see that autoInit does not look like it is imported nor defined before being used in the examples. I tried to deep in with the IDE and I see that it is only being referenced in the other examples like TubeViewers. 

![imagen](https://user-images.githubusercontent.com/22214901/36496418-1cc30dc8-1730-11e8-9124-99764aed9084.png)


Thank you for you help jouradin ;=)

**Any suggestion?**

**Comment by jourdain** [comment]
Yes... Debug your code, the error message is fairly explicit. 
You need to figure out on your own otherwise you won't learn.

Good luck!

**Comment by jourdain** [comment]
If you can't figure it out. Just delete that line. You missed its usage and declaration in the example you copy/pasted from.

You don't want it in your use case.

**Comment by lujx123** [comment]
hello
I have a question
VTK. Js display 3Dtiff image, in VTK,js format does not exist
Vtk.js has support for identifying coordinate points on images
Thank you in advance

**Comment by jourdain** [comment]
yes

**Comment by lujx123** [comment]
> yes

I don't quite follow you

**Comment by jourdain** [comment]
Same
