### ISSUE TITLE
Consuming vtk as a library

### ISSUE THREAD

**Issue by vidartf** [Kitware/vtk-js#608]
I'm working on a project where I want to use vtk.js as a library. I want to bundle my project using webpack (i.e. include the relevant parts of vtk.js in that bundle). Based on what was said [here](https://github.com/Kitware/vtk-js/blob/master/Documentation/content/docs/develop_build.md#title-building-vtkjs), I figured vtk.js was an ES6 library, so I've just been importing the relevant bits using lines like `import vtk from 'vtk.js/Sources/vtk';`. However, I recently had some problems, as some of the test tooling I'm using does not support some of the ES7 features introduced here: https://github.com/Kitware/vtk-js/commit/27ad20500482e718371f477ff1ce22f9debf87d2

How should I consume vtk.js to avoid such problems?

**Comment by jourdain** [comment]
[Here](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) is the documentation on how to integrate vtk.js into a project using webpack and its loaders.

In vtk.js for the testing part we use the same loaders as our build ones. Is there any reason you can't do it with your test infrastructure? Do you use babel, or just modern enough runtime to not need transpilling?

**Comment by vidartf** [comment]
Thanks for the quick reply! That link seems like a good resource.

> Do you use babel, or just modern enough runtime to not need transpilling?

I'm using typescript, and I'm having an issue with [karma-typescript](https://github.com/monounity/karma-typescript/issues/255). With those resources, I'll have a go at seeing if I can make it work (I'll post the solution if I find one).

**Comment by vidartf** [comment]
I had to add a transformer from ES6 to ES5, and the ES7 issue was resolved in the previously linked issues. For reference, the needed config option was:
```js
bundlerOptions: {
  transforms: [
    require("karma-typescript-es6-transform")({ presets: [["env"]] }),
  ],
}
```

**Comment by doczoidberg** [comment]
just want to add that it's not possible to use vtk.js with [angular cli](https://github.com/angular/angular-cli). This is more an issue of angular cli but maybe also a more generic use of vtk.js with other frameworks than webpack is possible

**Comment by jourdain** [comment]
What about using the pre-built UMD version of vtk.js?

**Comment by doczoidberg** [comment]
what?

**Comment by jourdain** [comment]
Also here is a standalone example using vtk.js 

https://codepen.io/jourdain/pen/RQZWYa

**Comment by jourdain** [comment]
You can import vtk.js that way into your HTML `https://unpkg.com/vtk.js@6.3.4`.

**Comment by doczoidberg** [comment]
yes that is possible and I do it right now, but of course it isn't as comfortable for development because no code completion etc.
