### ISSUE TITLE
handleWheel on Render Window Interactor doesn't seem to process single wheel events

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#614]
I'm playing with an application and am attempting to change an image's slice index on a mouse scroll event by using the mouse range manipulator class.  I've noticed that the render window interactor does not seem to propagate the mouse wheel event if only one event is fired, but instead requires multiple scroll/wheel events to trigger the action.  I attempted the same thing on this [example](https://kitware.github.io/vtk-js/examples/MouseRangeManipulator.html) and saw the same outcome.  

I didn't spend too much time digging into the event architecture, but I did manage to find a quick fix that seemed to work alright.  I added a line that calls ```publicAPI.mouseWheelEvent(callData)``` on line 423 in the render window interactor class and it seems to have worked for my use case.  Again, being unfamiliar with the event architecture I'm not sure this is the proper way to get around it, but it seems to work for me:
```
 publicAPI.handleWheel = (event) => {
    event.stopPropagation();
    event.preventDefault();

    let wheelDelta = 0;
    // let mode = '';
    if (event.wheelDeltaX === undefined) {
      // mode = 'detail';
      wheelDelta = -event.detail * 2;
    } else {
      // mode = 'wheelDeltaY';
      wheelDelta = event.wheelDeltaY;
    }
    const callData = {
      wheelDelta: Math.max(0.01, (wheelDelta + 1000.0) / 1000.0),
    };

    if (model.wheelTimeoutID === 0) {
      publicAPI.startMouseWheelEvent(callData);
      publicAPI.mouseWheelEvent(callData);          // ADDED CODE
    } else {
      publicAPI.mouseWheelEvent(callData);
      clearTimeout(model.wheelTimeoutID);
    }
...
```

If it is the intended function to not execute these mouse wheel events unless multiple are fired, is there a way to get around this? 

Thanks for the help,
-Logan

**Comment by agirault** [comment]
Hi @llangholz89,

I remember we added start and stop events for mouse wheel, and we probably did not think of handling the mouse event when it happened initially. The fix you offer seems to rectify this, and I think it makes sense!

Could you contribute that change in a pull request?

**Comment by llangholz89** [comment]
@agirault 
Thanks for the reply, that's good to know!  Yes I can go ahead a submit that change, I'll try to get to it by the end of the day.

Cheers,
Logan
