### ISSUE TITLE
trouble when using vtkGenericRenderWindow instead of vtkFullScreenRenderWindow

### ISSUE THREAD

**Issue by Trophime** [Kitware/vtk-js#619]
Hi, 
I'm trying to rebuild a js using vtk-js to mimic SceneExplorer.
I'm running into a pb when using vtkGenericRenderWindow instead of fullscreen render.

I've tracked down the problem to:
```
 const genericRenderWindow = vtkGenericRenderWindow.newInstance( {container: renderWindowContainer,} )
genericRenderWindow.setContainer(renderWindowContainer);
```
where renderWindowContainer is:
```
        const renderWindowContainer = document.createElement('div');
        renderWindowContainer.style.position = 'absolute';//'relative';
        renderWindowContainer.style.width = '100%';//'500px';
        renderWindowContainer.style.height = '100%';//'700px';
        rootContainer.appendChild(renderWindowContainer);
```

How could I make sure renderWindowContainer is properly defined?
What are the best practice to debug that kind of script?

(PS: I'm a real beginner as for js)

Best
C

**Comment by jourdain** [comment]
The debugger of your browser should help you inspect the DOM and see the current position/size/layout of the various node of your DOM.

Then you might be missing a call to resize() once that container is actually valid (in term of size).
