### ISSUE TITLE
API informing webgl1 vs webgl2

### ISSUE THREAD

**Issue by agirault** [Kitware/vtk-js#625]
Using webgl1 will result in much lower performance than when using webgl2. Some browsers on some OS will default to webgl1 without warning or informing the user. Adding an API capable of exposing that information would be valuable so that we could display warnings on the application level.

**Comment by agirault** [comment]
https://caniuse.com/#feat=webgl2

**Comment by zachmullen** [comment]
It would be wonderful if there was a full-featured cross-platform introspection API that could retrieve support flags for all sorts of GL capabilities, and maybe even things like memory sizes if the browser exposes that.

**Comment by agirault** [comment]
Done by @jourdain at https://github.com/Kitware/vtk-js/pull/644/commits/fdd66bbab55eb0c421f4233982ee31f9328deb22
