### ISSUE TITLE
Integrating maps / vector tiles with vtk.js

### ISSUE THREAD

**Issue by danmindru** [Kitware/vtk-js#645]
Hi there,

First of all thank you for this beautifully made library. It’s refreshing to see such a high-standard JavaScript code base. The docs, tooling and what I’ve seen from the source align with my own views on JS.
My hat off to you and all other contributors.

In a little while, I will be looking into how to integrate maps with vtk.js. My ideas range from syncing the interactions on a vtk.js view with a map view that sits behind it (thinking mapbox gl js) to extending the renderer so it can decode vector tile pbf(s) and draw them within vtk.js (they are usually rendered via WebGL anyway).

Not sure where to start, but have you given it some thought? Or perhaps have some pointers for researching the subject?

Thank you for the help 🙏

**Comment by jourdain** [comment]
Hi Dan,

Thanks for your great comment. As far as I know [GeoJS](https://github.com/OpenGeoscience/geojs) is going to have some option to blend both world. @sankhesh may have additional information on that.

**Comment by aashish24** [comment]
@danmindru we have a mapping library GeoJS built for this purpose which also use WebGL and currently we are adding VTK.JS backend so that you can draw data objects rendered by VTK on top of the map. @sankhesh is the best contact person if you want to try it out.  thanks @jourdain

**Comment by danmindru** [comment]
Sounds good @jourdain / @aashish24! Thanks a lot for the info, I’ll need to have a closer look at GeoJS then.
At a glance, it seems like it only supports rendering in 2D via GeoJSON (if https://github.com/OpenGeoscience/geojs/issues/492 is a good hint).
If that’s the case, I should probably see what it takes to get 3D working in it. It was just a quick look, so please correct me if I’m wrong.

What I want to research is how to render the vtp object as a 3D surface together with a base map.
I’ve attached some rough examples to clarify my end goal.

![963267cf-246c-4bee-ad75-309a30ca1cf4](https://user-images.githubusercontent.com/1515742/37424603-287bc80c-27c1-11e8-99fb-95ee28fe3b9a.jpeg)
![3e0505f1-fb58-4fa6-91dd-9df4ee8e3059](https://user-images.githubusercontent.com/1515742/37424604-289e4116-27c1-11e8-83b8-3aec9fe3dc8a.jpeg)
![479c06b4-58b0-49f1-a7b0-506e277ad2d3](https://user-images.githubusercontent.com/1515742/37424605-28bdcce8-27c1-11e8-8748-dc9bf3383612.jpeg)

I’m aware the surface can’t exactly be drawn with vector tiles / geojson, because support for point elevation is sparse, but a good enough visualization could be achieved with elevation per polygon (3D extrusions).
Hope I made my intentions clear(er).
Thanks again for the help & suggestions :)

**Comment by jourdain** [comment]
Are you talking about something similar to https://kitware.github.io/vtk-js/examples/ElevationReader.html with a textured apply to that vtp?

**Comment by danmindru** [comment]
That’s pretty close to what I have in mind, yes. It looks fantastic by the way, wonder how I missed that example. I’ll try to fiddle with a maps api and see if I can generate the texture and dem CSV on the fly.

This together with labels is a good enough start for me. Thanks!
