### ISSUE TITLE
What is __BASE_PATH__?

### ISSUE THREAD

**Issue by fornewgold** [Kitware/vtk-js#652]
I am not familiar with NPM. When I tried the STLReader example (https://kitware.github.io/vtk-js/examples/STLReader.html), I noticed the reader can load a STL file by code like this:

reader.setUrl(`${__BASE_PATH__}/data/stl/segmentation.stl`, { binary: true }).then(update);

What is the correct way to load a STL file in the sample folder as index.js (project_name/src/index.js)? I am not sure what is ${__BASE_PATH__}. I tried src/filename.stl and filename.stl, it did not work.

**Comment by jourdain** [comment]
The `setUrl()` method expects a URL to download the file from. In other words `http://hostname/path/to/the/stl/file/to/download.stl`. In our case we use `__BASE_PATH__` to dynamically inject the base path where the file will be serve from. Typically on our github.io site, this will translate to `https://kitware.github.io/vtk-js/data/stl/segmentation.stl`.

But if you have your hand on your data via another mean, you can use `parseAsArrayBuffer(binaryContent)`.

HTH,

Seb

**Comment by fornewgold** [comment]
Thanks for fast reply. I followed the tutorial and used localhost:8080 to test the STLReader examples. I have several STL files located in the source folder. What should I do if I want to visualize them like the method used in the STL example:

reader.setUrl(`${__BASE_PATH__}/data/stl/segmentation.stl`, { binary: true }).then(update);

**Comment by jourdain** [comment]
I think your web server is serving the content of the `./dist` directory. So you could put your data there.
