### ISSUE TITLE
style.mcss ERROR

### ISSUE THREAD

**Issue by fornewgold** [Kitware/vtk-js#656]
I am testing the the examples of DepthTest and SphereAndLabels. I got errors that the loader failed to parse file of style.mcss. See the picture for more details. How to fix it and run these two examples? Why OpenGL is needed for these two examples?

![screenshot from 2018-03-20 00 04 30](https://user-images.githubusercontent.com/31722022/37635607-f230ce58-2bd2-11e8-9a86-29ad966f42ba.png)

**Comment by jourdain** [comment]
This is the rule you are missing:
https://github.com/Kitware/vtk-js/blob/master/Utilities/config/rules-vtk.js#L17-L35

For the OpenGL vs WebGL, we just kept the naming of our VTK/C++ library.

**Comment by fornewgold** [comment]
Thanks for quick reply. I am not sure how to use the rule exactly. Detailed instruction will be appreciated. I tried to put the code in webpack.config.js, then npm failed to start.

**Comment by jourdain** [comment]
Try to learn more about Webpack first using their resources.
