### ISSUE TITLE
How to move objects with mouse?

### ISSUE THREAD

**Issue by fornewgold** [Kitware/vtk-js#657]
I am trying to implement a function that an object(cone or point or sphere) can be created and moved on a line/plane or the surface of a bigger object using mice. Is it possible and how to achieve it?

**Comment by jourdain** [comment]
It is possible to do it, but it won't be easy to explain it here. You will have to do some actor picking and then once picked, you want to reflect the mouse movement to a position change of that given object position.

**Comment by agirault** [comment]
Something similar is done with the handle widget. You could give a look at this to see how it's done (look for translate):
https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Widgets/SphereHandleRepresentation/index.js

**Comment by JensMunkHansen** [comment]
You can use the vtkHandleWidget together with vtkContrainedPointHandleRepresentation and it does exactly what you are asking for
