### ISSUE TITLE
Show scale bar with volume

### ISSUE THREAD

**Issue by linsheng** [Kitware/vtk-js#660]
Hi,

I'm using vtk.js to render volume contour for a dataset and it works great. Then I'm trying to show a scale bar to with the volume. I checked all examples but didn't find one. Is it possible to add a scale bar using vtk.js? How can I do it?

Thanks,
Lin

**Comment by jourdain** [comment]
Hi Lin,

we don't have any implementation inside the 3D view but you can create your own with HTML and a canvas as overlay.

The code below give you some hints on how to do that:
https://github.com/Kitware/pv-web-viewer/blob/master/Sources/properties/LookupTableProperty/index.js#L20-L28

HTH,

Seb

**Comment by linsheng** [comment]
Thanks, that's very helpful.
