### ISSUE TITLE
Export vtk.js scene

### ISSUE THREAD

**Issue by aminechir** [Kitware/vtk-js#663]
Hi,

Let me explain the problem.
In vtk.js I oppen a render window to allow the user moving and translating an actor with the mouse. 

I would like to get the state of this scene and export it to use in an other c++ program. What I did is that I get the active camera and get all current parameters such focal point,  viewUp, ... and I export them.

The problem is that in my c++ executable, when I try to reproduce the scene, the actor and the camera are not well placed.

Do you know what exact informations I have to pass from vtkjs to c++ to reconstruct exactly the scene ? I wonder that just the camera state was sufficient but it looks not. 

Ps: I don't have to export the actor because I already have an instance of this actor into a .vtu file which I can read in the c++. My problem is only the position of this actor and the camera. 

Thanks you

**Comment by jourdain** [comment]
I would think camera position/focalPoint/viewUp should be enough.

**Comment by martinken** [comment]
There are a lot of properties, but generally what Seb said plus the clipping range and view angle. If you want it to be exactly the same then there are a ton of properties that ***could*** go into it. But most are rarely used but window size and viewport would be two more.

**Comment by aminechir** [comment]
Ok thank you . So you mean that just the position of the camera has to be exported?

When we use mouse interaction in the render window, we are moving the actor or the camera?
 I we also move the actor , I also have to export some properties about the moved actor, what do you think

**Comment by martinken** [comment]
Usually it is the camera that is moving. If you move the actor then yes, you need to also export the position, scale, orientation of the actor

**Comment by aminechir** [comment]
Ok thank you for this reactivity. I will try and get back here if I encountered some problems

**Comment by jourdain** [comment]
I'll close the issue for now.
