### ISSUE TITLE
Listen widget raised events

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#666]
I have a custom interactor style (priority = 0.4) and I'd like to be able to observe a vtkLineWidget when the `publicAPI.invokeStartInteractionEvent()` or `publicAPI.invokeEndInteractionEvent()` are raised. How can I do that ?
As I set alow priority to the interactor style than line widget, I can't handle mouse event (for example) when a handleWidget is moved. And that's ok, but I want to get back the new position of the HandleWidget.

**Comment by jourdain** [comment]
@agirault

**Comment by agirault** [comment]
are you talking about invokeStartInteractionEvent and invokeEndInteractionEvent triggered by your interactor style or by the line widget?

**Comment by laurennlam** [comment]
By the line widget.

**Comment by agirault** [comment]
They're defined in [InteractorObserver](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/InteractorObserver/index.js#L147-L149) with the [event](https://github.com/Kitware/vtk-js/blob/master/Sources/macro.js#L763) macro, so you can use [`lineWidget.onStartInteractionEvent/onEndInteractionEvent`](https://github.com/Kitware/vtk-js/blob/master/Sources/macro.js#L813) to catch those.

**Comment by laurennlam** [comment]
I tried this but not in the right way... Thanks a lot !
