### ISSUE TITLE
How to iterate all picked cells?

### ISSUE THREAD

**Issue by fornewgold** [Kitware/vtk-js#667]
I am trying to implement a function that iterates all picked cells and put a text label on each of them. I referred the example of CellPicker to pick points with a sphere representation like this:

```
// Press shift+click to pick
const picker = vtkCellPicker.newInstance();
picker.setPickFromList(1);
picker.initializePickList();

const iStyle = vtkPickerInteractorStyle.newInstance();
iStyle.setContainer(fullScreenRenderer.getContainer());
renderWindow.getInteractor().setInteractorStyle(iStyle);
renderWindow.getInteractor().setPicker(picker);
```

The problem is how to iterate and label the elements in the picker. In the example of SpheresAndLabels, the psMapper was setup and connected with coneSource like this:

```
const psMapper = vtkPixelSpaceCallbackMapper.newInstance();
psMapper.setInputConnection(coneSource.getOutputPort());
psMapper.setCallback((coordsList) => {
  if (textCtx && dims) {
    textCtx.clearRect(0, 0, dims.width, dims.height);
    coordsList.forEach((xy, idx) => {
      textCtx.font = '12px serif';
      textCtx.textAlign = 'center';
      textCtx.textBaseline = 'middle';
      textCtx.fillText(`p ${idx}`, xy[0], dims.height - xy[1]);
    });
  }
});
```

Is it possible to connect the psMapper with the picker? I tried but it did not work. I noticed the coordsList was not defined in the example. Is it a variable in the source class? I checked the CellPicker class but did not found any helpful information. Any document introduce the data structure of picked contents and relevant APIs?

Any help or suggestion would be very much appreciated!

**Comment by jourdain** [comment]
Hum your question is definitely relevant. But the answer is not trivial. I would think it is possible with some data conversion layer in-between which create a polydata based on the selection. Then use that polydata with the vtkPixelSpaceCallbackMapper for rendering those labels.

HTH

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9
