### ISSUE TITLE
How to load a .vtk file in vtk.js

### ISSUE THREAD

**Issue by nicolasmaurotorres** [Kitware/vtk-js#668]
Hi, im doing my thesis and i need to render files locally and remotelly

Im trying to do the local rendering to visualize a .vtk file from my pc to the browser with vtk.js using this examples
https://kitware.github.io/vtk-js/examples/STLReader.html using the handleFile of the example and the rendering part of this one https://kitware.github.io/vtk-js/examples/PolyDataReader.html but is not working

This is the file im using to render (125MB) https://drive.google.com/file/d/1IbcaAZcK7ysc5noGb5cuo6unvq7Q0zbq/view

I already did the remote render and works like a charm, i used this tutorial https://kitware.github.io/paraviewweb/docs/multi_user_setup.html

what im doing wrong?

thanks in advance!

**Comment by nicolasmaurotorres** [comment]
**Update** 
i tryed this code

this.reader.setUrl("/src/js/imagen_procesada.vtk").then(() => {
               const polydata = _this.reader.getOutputData(0);
               const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance();
                const renderer = fullScreenRenderer.getRenderer();
                const renderWindow = fullScreenRenderer.getRenderWindow();
                _this.actor.setMapper(_this.mapper);
                _this.mapper.setInputData(polydata);
                renderer.addActor(_this.actor);
               resetCamera();
               render();
});
and the console of chrome throws 
"Dataset of type UNSTRUCTURED_GRID not supported"

**Comment by jourdain** [comment]
You will need to extract the surface of your unstructured grid in order to render it into vtk.js.
The preferred format for it would be `vtp`.

**Comment by anastasia-r** [comment]
Hi, I am getting the same error 
"Dataset of type UNSTRUCTURED_GRID not supported"

however the file I am using doesn't have an unstructured grid. Is there any other reason for this?
