### ISSUE TITLE
Problem of using ImageCroppingRegionsWidget with pre-built vtk.js

### ISSUE THREAD

**Issue by linsheng** [Kitware/vtk-js#670]
Hi, I have a web project and I want to use vtk.js to render some 3D data. I'm not familiar with node.js so I just use pre-build vtk.js from https://unpkg.com/vtk.js@6.3.4. It works great for volume rendering and slice rendering. But when I tried ImageCroppingRegionsWidget, the browser console shows an error `Cannot read property 'newInstance' of undefined`. The code is:
```
var vtkImageCroppingRegionsWidget = vtk.Interaction.Widgets.vtkImageCroppingRegionsWidget.newInstance();
```

I take a look at the source code and find that ImageCroppingRegionsWidget is not exported from Widgets package. So I want to know is it possible to use ImageCroppingRegionsWidget in pre-build vtk.js? If possible, how should I do it?

Thanks,
Lin

**Comment by jourdain** [comment]
Let me expose it... Should be available in next release ;-)

**Comment by jourdain** [comment]
FYI @floryst

**Comment by jourdain** [comment]
`vtk.js@6.4.6` will have the missing widget properly exposed. Thanks for reporting the issue.
