### ISSUE TITLE
Dicom Image Volume Rendering

### ISSUE THREAD

**Issue by leyuan** [Kitware/vtk-js#678]
Hi，

We are trying to get volume rendering work with DICOM vti image written from vtk writer in Python. Following the structure, we are running into troubles trying to get`index.json` file correctly generated. So few questions here and appreciate if someone can help!

- How does `index.json` generated for `vti` data
- Is using `vtkHttpDataSetReader` the correct choice of reading the data? Or it should be `XMLReader`
- Is there a better way of reading Dicom images(a folder of .dcm files) instead of using `vti` file

Thanks!

**Comment by thewtex** [comment]
Yes, as @jourdain mentioned, we can load the DICOM images directly via [itk.js](https://insightsoftwareconsortium.github.io/itk-js/).

To load a multi-frame DICOM file (the entire volume is in one file), use [itk/readImageFile](https://insightsoftwareconsortium.github.io/itk-js/api/browser.html). To load a DICOM file series, use [itk/readImageDICOMFileSeries](https://insightsoftwareconsortium.github.io/itk-js/api/browser.html#readImageDICOMFileSeries-fileList-gt-itk-Image). Both of these are enabled in [this reference application](https://kitware.github.io/itk-vtk-image-viewer/).

**Comment by leyuan** [comment]
Okay thanks!

**Comment by truongleit** [comment]
Hi @thewtex, can you tell me what the rendering algorithm of your application (itk-vtk-image-viewer) is? Is that marching cube? Cause I am doing project called "Visualization of DICOM images on web application" and I have finished implementation for Ray casting and Texture-based rendering, so maybe your VTK.js and ITK.js could be the last part of my work. Thanks!

**Comment by rjsgml5698** [comment]
I want to render dicom files using itk.js. So, I want to use itk / dicomImageDICOMFileSeries. 

However, I am a beginner who is not familiar with itk.js. 

Is there a simple example I can refer to?

**Comment by thewtex** [comment]
@rjsgml5698 these code snippets may be helpful:

https://github.com/InsightSoftwareConsortium/itk-js/blob/680878359d89fa0e0e7b609cec494500762ec6af/test/Browser/DICOMSeriesTest.js#L22-L26

https://github.com/Kitware/itk-vtk-viewer/blob/58ed5f09e904557ee949f5d6e4f65be395a428e9/src/processFiles.js#L32-L42

**Comment by rjsgml5698** [comment]
Thank you for your help!! I will try it!

**Comment by engrussman** [comment]
@thewtex I want to render the DICOM images but unable to use the following. would be grateful if you can give an independent example for beginners, please?  

https://github.com/InsightSoftwareConsortium/itk-js/blob/680878359d89fa0e0e7b609cec494500762ec6af/test/Browser/DICOMSeriesTest.js#L22-L26

**Comment by thewtex** [comment]
@engrussman here's an example:

  https://glitch.com/~itk-read-dicom

**Comment by engrussman** [comment]
@thewtex Many thanks for your prompt response. The example is working fine for one or two slices when I select more than that, it gets stuck on "Loading... " status. Can you please rectify the issue, please.

**Comment by thewtex** [comment]
@engrussman please share the data so the issue can be reproduced.

**Comment by engrussman** [comment]
> @engrussman please share the data so the issue can be reproduced.

@thewtex Sorry that was my bad. There was some issue with the dataset, after fixing that issue, now it is reading all the dicom files.  Thanks for your support. Is there any example which also performs rendering of DICOM file using VTK.js?

**Comment by thewtex** [comment]
@engrussman good to hear :-)

A few applications with DICOM support using itk.js / vtk.js:

https://kitware.github.io/itk-vtk-viewer/
https://kitware.github.io/itk-vtk-viewer/app/

https://kitware.github.io/paraview-glance/index.html
https://kitware.github.io/paraview-glance/app/

**Comment by wcb2fwt** [comment]
@thewtex Hello, when the number of DCM files exceeds 800, there will be an error, I want to know why? thank you~
![image](https://user-images.githubusercontent.com/22394710/134601966-dbb0391c-d01c-4ba1-b086-fae883ca99fd.png)

**Comment by wcb2fwt** [comment]
@thewtex When I delete the remaining 650 DCM files, it can be displayed normally. I need your help, thank you very much 
![image](https://user-images.githubusercontent.com/22394710/134602220-21753f88-7cc3-4b35-a27f-f062e709ed39.png)
