### ISSUE TITLE
Multi-model translucent.

### ISSUE THREAD

**Issue by qian-jiang** [Kitware/vtk-js#680]
I am a web front-end developer, I met a difficult development by the project, I use three js to load multiple STL model, the model of transparency, alpha effects, according to the load in sequence, after the first load model will affect loading model transparent display, I try to use blend attribute, this does not solve the problem. I'm going to use vtk.js to see if vtk.js supports multi-model transparent loading.
thankyou.

**Comment by jourdain** [comment]
You can certainly load several models with vtk.js and make them transparent. But the current implementation does not provide depth peeling which will create some rendering artifacts. 

This will eventually be supported in the future, but we don't have a specific timeframe for it. Although, if that feature is important for your company, you can contract us to implement it so you could have it in a timely manner.

@martinken feel free to provide any additional information.

**Comment by qian-jiang** [comment]
Does the current version of vtk.js support Depth sorting?
Thank you

**Comment by jourdain** [comment]
I don't think it does.

**Comment by martinken** [comment]
Not currently.

**Comment by xmliu0915** [comment]
I have the same problem, 
Does vtk.js support depth peeling now?

**Comment by GuillaumeFavelier** [comment]
Why the issue is closed if the feature asked is not supported yet?

**Comment by alexshi0000** [comment]
Why is this feature in the documentation for vtk-js? Is it supported as of now?

**Comment by jourdain** [comment]
Still not supported

**Comment by siebediels** [comment]
Is there any time frame on when this might be supported in the future?
Thanks in advance!

**Comment by jourdain** [comment]
I think the focus now is WebGPU and @martinken can provide more info but it might be available with that backend right away? If you need it for WebGL, you may have to reach out to us with funding to make it a priority.

**Comment by martinken** [comment]
It will be implemented for WebGPU, just haven't gotten to that yet.

**Comment by martinken** [comment]
It is now implemented in WebGPU
