### ISSUE TITLE
OpenGL Render VolumeMapper Image Dimension

### ISSUE THREAD

**Issue by leyuan** [Kitware/vtk-js#681]
Hey I found in this line

https://github.com/Kitware/vtk-js/blame/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L1193

It calls `image.getDimensions()`, but this method does not seem to exist.
Both this and `model.currentInput.getDimensions()` report this error,  but the other methods work properly.

![image](https://user-images.githubusercontent.com/1417993/38286439-9d297700-3782-11e8-90d4-700bf4088abc.png)

I have a feeling that I may be made wrong assumptions here...

A part of my code is like this
```
/** Render And Interactor */

const openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
renderWindow.addView(openglRenderWindow);
openglRenderWindow.setContainer(container);
// renderWindow.addController(controlPanel);

const interactor = vtkRenderWindowInteractor.newInstance();
interactor.setView(openglRenderWindow);
interactor.initialize();
interactor.bindEvents(container);

renderWindow.addView(openglRenderWindow);
openglRenderWindow.setSize(1600, 900);

renderWindow.render();

global.marchingCube = marchingCube;
```

I am using multiple viewport on openglRenderWindow, please let me know if you need more information, appreciate your help!

**Comment by jourdain** [comment]
I'm pretty sure it is related to the way you create your pipeline (which is not shown here).

The method in question is not supposed to exist on a vtkPolyData but only on a vtkImageData. And if you use the marchingCube filter, that will convert your vtkImageData to a vtkPolyData which can not be volume rendered.

[See method definition](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/ImageData/index.js#L73)
