### ISSUE TITLE
Default event action preventing

### ISSUE THREAD

**Issue by luciemac** [Kitware/vtk-js#686]
Using _vtk.js_ in a _React_ project, `onClick` action does not work.

It appears that the `RenderWindowInteractor `stops events' propagation.
Besides defining a class that inherits from `RenderWindowInteractor` and avoids events propagation, do you have an other solution ?

**Comment by jourdain** [comment]
Are you saying that by not doing

https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js#L198

You can not get the click event?

**Comment by luciemac** [comment]
@agirault I [tried ](https://jsfiddle.net/luciemac/kdha77p2/12/)what you suggested without success.
`onClick` is made on a parent component not within the container of the vtk canvas.

On the given example, we have 2 divs. If you click on div `two`, the event is catched and not propagated to div `one` even if the z-index is lower than div `one`.
The expected behaviour, in our case, would be to trigger `one()` and `two()` actions.

**Comment by luciemac** [comment]
@jourdain
Actually, if you comment https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js#L198 it solves the problem.

**Comment by luciemac** [comment]
Why is it necessary for `vtkjs` to stop events propagation?

**Comment by luciemac** [comment]
In our side it would be fine but I don't know if it would impact some `vtkjs` interactions mecanisms..

**Comment by jourdain** [comment]
From what I see, it should be fine.

**Comment by floryst** [comment]
Instead of using `onClick`, try using `onClickCapture`. That will get the click on the capture phase of event propagation, since vtkjs invokes preventDefault on the bubble phase (which is listened to with `onClick`).

here's a modified example of your jsfiddle: https://jsfiddle.net/k1jLk0uw/

**Comment by floryst** [comment]
Fixed in #694. Closing.
