### ISSUE TITLE
NIFTI reader issue

### ISSUE THREAD

**Issue by katiamar63** [Kitware/vtk-js#707]
I tried to use ITK Readers in VTK to read  NIFTI images but I could not display them properly (I checked a few examples and none of them was displayed properly). So I tried to read these NIFTI with **ParaView Glance** and the result was the same as bad. So I checked these NIFTI in other viewers (ITK-Snap, 3D Slicer) and they were displayed properly. 

Moreover, I converted  this NIFTI file:  [https://nifti.nimh.nih.gov/nifti-1/data/avg152T1_LR_nifti.nii.gz](url)  to a few other formats using 3D slicer and then displayed results in ParaView:

1. mnc - NOT DISPLAYING PROPERLY
2. nrrd - OK
3. vtk - NOT DISPLAYING PROPERLY
4. mgz - OK

The most stunning for me is that when I try to read  original NIFTI file it is not working, but after conversion to nrrd or mgz, it is displayed properly. I compared the meta-data in headers  and values in data tables (get by getOutputData(), getPointData().getScalars().getData(), getExtent(), getRange() and  so on) among all the above formats using Inspector Debugger. It seems that headers are identical, for all the cases,  but the raw data tables are different  in case of mnc, nifti and vtk (the remaining ones are identical and displayed properly).
The images displayed improperly looked as they were shrinked onto one direction (projected on a single plane)

**Comment by jourdain** [comment]
I believe that's an issue to report on the itk.js side. 

@thewtex I let you take over...

**Comment by thewtex** [comment]
@katiamar63 please create an issue on the [itk-js repository](https://github.com/InsightSoftwareConsortium/itk-js) and include the test images that are failing. Thanks.
