### ISSUE TITLE
Canvas and toDataURL()

### ISSUE THREAD

**Issue by Raccoon5031** [Kitware/vtk-js#708]
I have not found the information so I'll ask here.

When I render something in 3D, I would like to create an image, a real .png, from the current state of the canvas.

Normally I would do something like this

```
var canvas = document.querySelector('canvas');
var img = canvas.toDataURL();
```

But it is not working, the result is blank. Is there any other way to proceed? Or is it just not possible?

Three.js [implemented something](http://learningthreejs.com/blog/2011/09/03/screenshot-in-javascript/) allowing to do this. So I guess that something similar should be possible

**Comment by jourdain** [comment]
The method to call is defined here: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindow/index.js#L92
