### ISSUE TITLE
Picker demos are not working

### ISSUE THREAD

**Issue by katiamar63** [Kitware/vtk-js#709]
PointPicker and CellPicker examples are not working on your demo pages.  I attach screenshots from FF v.59.0.2 and Chrome 65.0.x
![pointpicker2](https://user-images.githubusercontent.com/3754848/39054748-6eaf539e-4480-11e8-927d-8e75a6d4668e.PNG)
![pointpicker](https://user-images.githubusercontent.com/3754848/39054755-73249768-4480-11e8-88ff-5f84a65ed956.PNG)

**Comment by jourdain** [comment]
Thanks for reporting the issue @katiamar63.

@agirault are you aware of any change that could have cause the issue?
