### ISSUE TITLE
How to embed vtk.js in html without fullscreen?

### ISSUE THREAD

**Issue by jackyko1991** [Kitware/vtk-js#712]
I have tried the example codes in vtk.js, and found that all codes are using vtkFullScreenRenderWindow to generate renderer and renderWindow. This will make the app run in fullscreen mode. 

But in some documentations like [this](https://kitware.github.io/vtk-js/examples/PDBReader.html#Live-example), it seems is possible to embed the renderWindow in html, but I can't find any tutorial on that.

I want to write a medical image viewer using vtk.js, it is necessary for me to have 4 viewers in same html page. Any help?

**Comment by jourdain** [comment]
https://kitware.github.io/vtk-js/examples/SimpleCone.html

**Comment by agirault** [comment]
Also @jackyko1991, you can set a container on a `vtkFullScreenRenderWindow` to limit it to the bounds of your div container.
