### ISSUE TITLE
Volume cropping planes

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#713]
Add support for volume cropping like in [VTK VolumeMapper](https://github.com/Kitware/VTK/blob/master/Rendering/Volume/vtkVolumeMapper.h#L147)

**Comment by thewtex** [comment]
@floryst #done?

**Comment by floryst** [comment]
We have an image cropping filter now. It's not the same interface as the linked one in my first post, but for the purposes of cropping volumes, we have something at least.
