### ISSUE TITLE
Problem with Lookup table and opacity in ImageSlice

### ISSUE THREAD

**Issue by katiamar63** [Kitware/vtk-js#714]
I need to overlay a label image (e.g. segmentation) on top of another image (MRI raw image) in order to visualize the labels (lesions). When I try to use image slices for both of the images, I have the scene where one image is covering the other one (as in the picture below). When I try to use opacity and lookup table (rgb transfer function) I have the error as in the second screenshot.
Is it possible to have cells in image slicing mode completely transparent?  

The other thing is that whether I use colorWindow and colorLevel or not, if I change the opacity, it does not make any difference. So seems to me that opacity is not working at all.

What would you suggest in order to have this overlay made? Are there any examples? I have already checked ParaView code and sliceRepresentationProxy but I have not found any solution for my case.

![imageslice](https://user-images.githubusercontent.com/3754848/39215447-d8df8e24-47e5-11e8-97a6-3e2be8e2e862.PNG)
![rgbtransferproblem](https://user-images.githubusercontent.com/3754848/39215459-e328a320-47e5-11e8-814f-b8a33388f927.PNG)

**Comment by jourdain** [comment]
I believe the slice mapper does not support/implement transparency. This feature can certainly be added but I let @martinken comment out to provide more details.

**Comment by katiamar63** [comment]
I would appreciate  any tips or suggestions how to make this overlaying in vtk, eg.  if it is possible to mix 'regular' Image Actors with Image Slices then it would be great.

**Comment by alfredomp** [comment]
@jourdain when you say "convert your image into a transparent one", do you mean adding a fourth scalar component to the image? (I guess this fourth component will be used for "transparency' when rendering)

**Comment by jourdain** [comment]
Yes RGBA but I don't know what is your current image format if it is 3d/2d or something else.

**Comment by alfredomp** [comment]
It's a 3D image, we read it using the vtkItkImageReader. Are they any examples or code to get inspired for this transparency filter? I am trying to access the voxels inside the vtkImageData but can't find a way to get them.

**Comment by katiamar63** [comment]
so we have  actually pretty much the same problem as  described in https://github.com/Kitware/vtk-js/issues/304

**Comment by jourdain** [comment]
I wrote a start here https://github.com/Kitware/vtk-js/pull/720

**Comment by jourdain** [comment]
The example below provide a full path to do a transparent slice using the existing infrastructure.

https://kitware.github.io/vtk-js/examples/ScalarToRGBA.html

**Comment by katiamar63** [comment]
Great thanks for that example and filter.  We're using it but we haven't figured out how to change the slice orientation for the filter. We keep trying with 'orientation' property, but either we do not set it properly, or we should use other property. It seems that it is configured to be aligned with the axial direction, how can we use it for saggital or coronal?

**Comment by jourdain** [comment]
I've wrote it while watching TV on my spare time, so I couldn't get all the feature in place. I just did a quick and incomplete way to validate it was possible. If you want, you can extend the code to handle orientation (which I didn't). Or you can request some support from [Kitware](https://www.kitware.com/what-we-offer/) to implement the bit and pieces missing that you want to use.

**Comment by katiamar63** [comment]
Aaa, ok I got it. Thanks for quick response.  I will try to extend it, 
thanks again for help.

**Comment by jourdain** [comment]
To do it in a good manner you will have the create a new TypedArray reordered along the axis you want to slice. That way the code for slicing could remain the same using the slice() method which only create a view on the data.

**Comment by katiamar63** [comment]
Thanks for the tip,

**Comment by alfredomp** [comment]
@alvarosan thank you for the implementation of the opacity in the image slice. Although it certainly solves the issue #304 it is not a solution for our problem. As explained by @katiamar63 we would like to overlay a label map on top of an original image (using image slice for both images) where we see only the labels on top of the original image. Using the opacity implementation, the voxels of the label map, including the background voxels, are displayed on top of the original image. The ideal solution would be to only have the non-background voxels on top of the original image. 

@jourdain do you have a suggestion to make this happen inside the **image slice**? Maybe the RGBTransferFunction can be expanded to handle an alpha channel (RGBA).

The solution you created in #720 works but we have 2 main issues, we have to manually aligned the images to be able to have the overlay displayed on top of the original image, and we don't have the reformatting filter to display the images in sagittal and coronal planes. In other words, if it is implemented inside the image slice it will a much simpler solution for us and for future users of VTK.js
