### ISSUE TITLE
ElevationReader

### ISSUE THREAD

**Issue by srobayo222** [Kitware/vtk-js#717]
Hello everyone

For my class i need to know what is the function of the ElevatioReader and what means the XSpacing, ySpacin and the zScaling.

Thanks!

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Misc/ElevationReader/api.md

**Comment by jourdain** [comment]
Formatted version is available here too
https://kitware.github.io/vtk-js/api/IO_Misc_ElevationReader.html
