### ISSUE TITLE
Babel warning

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#734]
I get this message while compiling with webpack:
```
[BABEL] Note: The code generator has deoptimised the styling of "XXX/node_modules/vtk.js/dist/vtk.js" as it exceeds the max of "500KB".
```
After googling, It seems to be related to the ```compact``` option of babel. 

What do you think of this message?

**Comment by jourdain** [comment]
If you do `import vtk from 'vtk.js';` you get a vtk object similar to [script usage](https://kitware.github.io/vtk-js/docs/intro_vtk_as_external_script.html). For which you can use as-is without any specific rules. The rules are needed if you import the files from `vtk.js/Sources/.../*` but not with that prebuilt version which contain the full set of vtk.js.

In that case the `dist/vtk.js` file as already been transpiled using babel. Therefore trying to reprocess it with the js/babel rule does not make sense. Hence the warning telling you that processing a ~minified~ version of JavaScript is probably not what you were intending to do.
