### ISSUE TITLE
Point/Cell Picking

### ISSUE THREAD

**Issue by aminechir** [Kitware/vtk-js#735]
I  have already check the existing api regarding the picking and I am wondering if we could interactively pick point or cells as the same way we can do with Paraview ?

This feature already exists or it's planned for later versions ?

**Comment by jourdain** [comment]
I'm not sure to see what you mean by `interactively pick point or cells as the same way we can do with Paraview`?

One thing that we are missing is the hardware selector for cell.

**Comment by aminechir** [comment]
Ok thanks for answer.
