### ISSUE TITLE
VTK to JSON and from JSON

### ISSUE THREAD

**Issue by Neuroforge** [Kitware/vtk-js#736]
Hello,

Is it possible to export a VTK model in Python to JSON and load it in VTK-js?

This is a VTK to JSON converter.....

http://voxelent.com/tutorial-how-to-json/

Kind regards,

Daniel

**Comment by jourdain** [comment]
We don't have a reader for it but looking at the JSON file it seems fairly easy and quick to write such reader.

**Comment by Neuroforge** [comment]
Thank you for a swift response.

Ok. For now, would there be a way for me to host the file and serve it to vtkjs? It is a vtkCommonDataModelPython.vtkPolyData "surface".

Which class in vtkjs would fetch this? 

I require to fetch vtp and vti files.

**Comment by jourdain** [comment]
We have 2 standalone applications that you can use to load and visualize vtp/vti even from URL parameters.

https://kitware.github.io/vtk-js/examples/GeometryViewer.html
https://kitware.github.io/vtk-js/examples/VolumeViewer.html

Do you mean, you need to load both vtp and vti so you can see them together? 
- Volume rendering + geometry or
- Volume Slice + geometry 

For that you could [ParaView Glance](https://kitware.github.io/pv-web-viewer/).

**Comment by Neuroforge** [comment]
That's perfect. Thank you.

A json reader may be preferable at a later stage otherwise server implementations will require storage of static files.

Kind regards,

Daniel
