### ISSUE TITLE
Get intensity value at 3d point in Volume

### ISSUE THREAD

**Issue by Neuroforge** [Kitware/vtk-js#738]
Hello,

When you have loaded some data. What is the best way to access a value from the dataset?

Regards,

Daniel

**Comment by jourdain** [comment]
On a slice mapper you can do cell or point picking, but on a 3D volume, I'm not sure what you mean.

**Comment by Neuroforge** [comment]
In the Slicer Viewer, I have moved the slices to a particular point.

I would like to know the intensity at the 3d point at which all slices intersect.  Is there an example?

**Comment by jourdain** [comment]
We don't have examples but there are several ways to do it.

**Comment by agirault** [comment]
This is done in the itk-vtk-image-viewer (@thewtex)

**Comment by thewtex** [comment]
[itk-vtk-image-viewer](https://kitware.github.io/itk-vtk-image-viewer/) demonstrates cell picking and now uses the improve functionality, h/t @agirault @jourdain .

**Comment by Neuroforge** [comment]
So i think this look like what i am after...

Initialise the picker using the ImageSlice actors.

```
> const picker = vtkCellPicker.newInstance();
> picker.setPickFromList(1);
> picker.initializePickList();
> picker.addPickList(imageActorI);
> picker.addPickList(imageActorJ);
> picker.addPickList(imageActorK);
```

Then set the cell point position to be picked and try to return that value.

```
> function getPickedPoint()
> {
>       var I = document.querySelector('.sliceIVal').value;
>       var J = document.querySelector('.sliceJVal').value;
>       var K = document.querySelector('.sliceKVal').value;
> 
>       const point = [I, J, K];
>       console.log(`Pick at: ${point}`);
>       annotationPicker.pick(point, ren);
> 
>       const ijk = annotationPicker.getCellIJK();
> }
```

This returns [0, 0, 0] which doesn't seem right.

I would like to calculate a single intensity at the point of intersection for slices I, J and K.

**Comment by sedghi** [comment]
@jourdain In case of a 3D volume rendering of MIP, what is the best way to get the volume rendering intensity?. Is it possible to extract a `vtkImageData` from the renderer?

**Comment by jourdain** [comment]
I'm not sure about the question. If you created the data, you should have your hand on the `vtkImageData` (i.e. reader.getOutputData()). But you can also from the renderer, get the Volumes, and from it the mapper and them the inputData which should be your rendered vtkImageData.

**Comment by sedghi** [comment]
@jourdain Thanks for your prompt response; that answers my question about the rendering. 
Regarding the point picking from the 3D MIP, how can I get the location of the brightest voxel since we are clicking in a 3D volume?
I have found this [link](http://vtk.1045678.n5.nabble.com/picking-a-voxel-in-a-MIP-volume-td1231107.html) from the old forum, which suggests using `vtkProbeFilter` and traveling over a line to get the brightest point? Is there a better way to do this? (I don't think there is a `vtkProbeFilter` in vtk-js)

**Comment by jourdain** [comment]
I'm not the best person for that @martinken maybe? or someone from medical?

**Comment by martinken** [comment]
You would have to compute the line going through the selected pixel and then intersect that with the original volume data (probing it) to get the max (or min) as desired. Not sure how to do that in vtkjs right now other than manually coding that all up into a function.

**Comment by sedghi** [comment]
@martinken Thanks for your response, I have actually gone that pass to manually implement this functionality and it works as expected in the perspective projection, however, in the parallel projection the line that I draw from the voxel to the camera position seems to be off and not in the desired direction. I really appreciate if you have any comment this issue.

**Comment by floryst** [comment]
Is this still an issue, or did you solve your problem @sedghi?

**Comment by agirault** [comment]
Closing this issue. If you still need help, please ask your question on our discussion forum: https://discourse.vtk.org/c/web/9

**Comment by sedghi** [comment]
@floryst It's been solved, thanks
