### ISSUE TITLE
TypeError on script load

### ISSUE THREAD

**Issue by Raccoon5031** [Kitware/vtk-js#742]
Hi, 

When I try to use vtk-js with a simple javascript file ([from unpkg](https://unpkg.com/vtk.js)), I have a `TypeError: t.currentInput is undefined` error in the console.

Despite that, everything works well.

This error is coming from the second if in this code.

```
e.renderPiece = function (n, r) {
    if (e.invokeEvent(x), t.renderable.getStatic() || t.renderable.update(), t.currentInput = t.renderable.getInputData(), e.invokeEvent(I), null !== t.currentInput) {
      if (t.currentInput.getPoints && t.currentInput.getPoints().getNumberOfValues()) {
```

`t.currentInput` seems to be `undefined` but somewhow is passing through the first condition

**Comment by jourdain** [comment]
Could you describe the pipeline you are trying to run?

**Comment by Raccoon5031** [comment]
I'm using more or less the same [example as importing STLs](https://kitware.github.io/vtk-js/examples/STLReader.html) (I'm not using the ES6).

It does the following

- Create a `vtkFullScreenRenderWindow`
- Define for each STL the properties: path, color, opacity
- Foreach STL
  - Create mapper, actor, reader
  - Set properties on actor
  - `actor.setMapper(mapper);`
  - `mapper.setInputConnection(reader.getOutputPort());`
  - `fullScreenRenderer.getRenderer().addActor(actor);`

- Render

I'm also using a controller to interact with the STLs.

I can include my code if needed. Just let me know.

But I repeat everything is working. I just have this error in the console everytime.

**Comment by jourdain** [comment]
Any idea what could be happening @martinken  ?

**Comment by martinken** [comment]
I believe the original code is below, maybe we need a better test of currentInput? Ala if (!model.currentInput) instead of if (model.currentInput !== null)
```
model.currentInput = model.renderable.getInputData();
    publicAPI.invokeEvent(EndEvent);

    if (model.currentInput === null) {
      vtkErrorMacro('No input!');
      return;
    }

    // if there are no points then we are done
    if (
      !model.currentInput.getPoints ||
      !model.currentInput.getPoints().getNumberOfValues()
    ) {
      return;
    }
```

**Comment by jourdain** [comment]
Could you try with 6.6.1 just to make sure that solve the error you were seeing.

**Comment by jourdain** [comment]
Thanks!

My guess is that the data is not there yet (downloading) for some initial render(s). Or one of your data does not load at all.
