### ISSUE TITLE
Cannot Run Any VTK file

### ISSUE THREAD

**Issue by daalegend** [Kitware/vtk-js#748]
I created two files, one with javascript sample code with vtk.js and the other with HTML code that, all it does, runs the script. It's giving me a compilation error at the very first line when I ran it. My initial thought was that I needed to relocate where the javascript file is looking at to find the vtk.js framework because they're not in the same directory. But it still was giving me the 800A03EA compilation error at the first line whenever I ran it (I'm using Sublime if that matters at all). I'm not able to run any vtk file, but I can run javascript files just fine. The first line was originally 

import 'vtk.js/Sources/favicon';
--

 How do I go about fixing this?
```
import * from '../../../node_modules/vtk.js/Sources/favicon';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkActor from 'vtk.js/Sources/Rendering/Core/Actor';
import vtkElevationReader from 'vtk.js/Sources/IO/Misc/ElevationReader';
import vtkMapper from 'vtk.js/Sources/Rendering/Core/Mapper';
import vtkTexture from 'vtk.js/Sources/Rendering/Core/Texture';

// ----------------------------------------------------------------------------
// Standard rendering code setup
// ----------------------------------------------------------------------------

const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({
  background: [0, 0, 0],
});
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();

// ----------------------------------------------------------------------------
// Example code
// ----------------------------------------------------------------------------

const reader = vtkElevationReader.newInstance({
  xSpacing: 0.01568,
  ySpacing: 0.01568,
  zScaling: 0.06666,
});
const mapper = vtkMapper.newInstance();
const actor = vtkActor.newInstance();

mapper.setInputConnection(reader.getOutputPort());
actor.setMapper(mapper);

renderer.addActor(actor);
renderer.resetCamera();
renderWindow.render();

// Download and apply Texture
const img = new Image();
img.onload = function textureLoaded() {
  const texture = vtkTexture.newInstance();
  texture.setInterpolate(true);
  texture.setImage(img);
  actor.addTexture(texture);
  renderWindow.render();
};
img.src = `${__BASE_PATH__}/data/elevation/dem.jpg`;

// Download elevation and render when ready
reader.setUrl(`${__BASE_PATH__}/data/elevation/dem.csv`).then(() => {
  renderer.resetCamera();
  renderWindow.render();
});

// -----------------------------------------------------------
// Make some variables global so that you can inspect and
// modify objects in your browser's developer console:
// -----------------------------------------------------------

global.reader = reader;
global.mapper = mapper;
global.actor = actor;
global.renderer = renderer;
global.renderWindow = renderWindow;
```

**Comment by jourdain** [comment]
I'm not sure to understand the purpose or the meaning of that line.

```
import * from '../../../node_modules/vtk.js/Sources/favicon';
```

I would remove it or replace it by

```
import  'vtk.js/Sources/favicon';
```

**Comment by daalegend** [comment]
Right, that's what the line originally was. But that's where the problem started. My original thought then, like I said, was perhaps it didn't know where exactly the vtk file was because they weren't in the same directory. So I tried to find the file by writing a statement that would look explicitly where I defined it. But it was still having problems with compilation. That's where I am right now,

**Comment by jourdain** [comment]
Did you run `npm install vtk.js` so `import 'vtk.js/....';` could be resolved.

It is kind of difficult to help when no context is provided. As for sure that file is perfectly fine since those example files are actually compiled and deployed on the web site, so if they work in your browser, that means you miss something from the environment setup which should be described [here](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html), unless we forgot to update something when the build process changed.
