### ISSUE TITLE
How to get a slice from vtkImageData and render it to canvas (vtkExtractVOI  ?)

### ISSUE THREAD

**Issue by AndreFrelicot** [Kitware/vtk-js#749]
I would like to get the pixels from a slice in order to render it to a canvas, do you have a tip on how I can accomplish this ? vtkExtractVOI does not seems to be implemented.

thank you

André

**Comment by jourdain** [comment]
Could [this](https://github.com/Kitware/vtk-js/issues/738) works? 

Otherwise, it might be easy to just add vtkExtractVOI. Feel free to do a PR with it.

**Comment by floryst** [comment]
If you want to slice vtkImageData along the IJK axis, then you can get the pixel data and slice it yourself. Slicing logic is [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/ImageMapper/index.js#L834).

If the above doesn't answer your question, please ask again on our discourse: https://discourse.vtk.org/c/web/9
