### ISSUE TITLE
Potential bug in vtkScalarsToColor ?

### ISSUE THREAD

**Issue by aminechir** [Kitware/vtk-js#776]
In the class vtkScalarToColor, the function mapVectorsToMagnitude is responsible for computing the magnitude of the given vector when we want to generate the color mapping with a multi component data.

In the component "for loop", when you sum the terms, the values of the input vector are not squared for computing the norm. 

Did you assume that this functions take as an input already squared values ?

**Comment by jourdain** [comment]
Good catch!
