### ISSUE TITLE
Trying to build an app with react that uses this library.

### ISSUE THREAD

**Issue by malinged** [Kitware/vtk-js#780]
How does the renderer manipulate the dom, and is there a detailed reference for this js library similar to the C++ and Python vtk libraries?

**Comment by jourdain** [comment]
The renderWindow needs to be given a DOM element. Then after that it create a Canvas to leverage WebGL.

The documentation is available here: https://kitware.github.io/vtk-js/
You should look for examples to learn more on how to use it.

But I'm not sure to understand the question. You can find a React example using vtk.js here:
https://github.com/Kitware/paraviewweb/blob/master/src/React/Renderers/VtkGeometryRenderer/index.js
But the class described above aims to have a remote ParaView server on which it want to keep the 2 render window in synch. So most likely not what you are looking for, but at least it show how to manage the life cycle methods of React.

**Comment by malinged** [comment]
Thanks this seems like it will be all I need I appreciate the quick response.
