### ISSUE TITLE
Rendering rectilinear grids in vtk files with vtk.js not working.

### ISSUE THREAD

**Issue by malinged** [Kitware/vtk-js#793]
Im trying to render out data inside a rectilinear grid that is inside a vtk file following these 2 examples separately .
https://kitware.github.io/vtk-js/examples/VolumeMapper.html
https://kitware.github.io/vtk-js/examples/PolyDataReader.html

 

The renderer works but then the screen is black and nothing works or shows up at all. 

I'm using react and that seems to be handling vtk.js just fine.

**Comment by jourdain** [comment]
Ok, not sure to understand the question, but vtkRectilinearGrid is not directly supported as a renderable format. Some processing will need to happen in order to extract its vtkPolyData representation.
