### ISSUE TITLE
Images with negative orientation components render incorrectly

### ISSUE THREAD

**Issue by floryst** [Kitware/vtk-js#807]
To reproduce: load any image with negative orientation components

![negative-orientation](https://user-images.githubusercontent.com/1812167/42962771-5b39b526-8b60-11e8-9454-495e3a9f46ec.gif)

A sample image is provided (not the same as the above animation). Be sure to first unzip it.

[Acute_FLAIR (1).nii.zip](https://github.com/Kitware/vtk-js/files/2211233/Acute_FLAIR.1.nii.zip)

**Comment by martinken** [comment]
This has been fixed.
