### ISSUE TITLE
vtp reader on Safari

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#811]
Appended+zlib is failing for `202-t-edges-appended-zlib.vtp`, `lidar-appended-zlib.vtp`, `single-pin-appended-zlib.vtp`  from https://github.com/Kitware/vtk-js-datasets/tree/master/data/vtp

**Comment by floryst** [comment]
Is this still an issue? @jourdain

**Comment by jourdain** [comment]
it is fixed
