### ISSUE TITLE
Save everything then load it after

### ISSUE THREAD

**Issue by ghost** [Kitware/vtk-js#812]
Hi,

I would like to know if there is a _fast_ way to save the state of everyhting (actors properties, camera properties, ...) on a file, then load it after. For instance, if two people want to share their own configuration to the other one. I tried to use set/get on renderer and renderWindows, but i rise this error : `viewport.getViewportByReference is not a function`.

Thank you.

**Comment by jourdain** [comment]
You could serialize the full pipeline below an actor by doing something like that:

```
// Saving
const stateToSave = {
  actors: renderer.getActors().map((a) => a.getState()),
  camera: renderer.getActiveCamera().getState(),
};

// String to write
const str = JSON.stringify(stateToSave);
```

```
// Loading
const stateToLoad = JSON.parse(str);
renderer.setActiveCamera(vtk(stateToLoad.camera));
stateToLoad.actors.forEach((actor) => {
  renderer.addActor(vtk(actor));
});
```

Otherwise if you use [ParaViewGlance](https://blog.kitware.com/kitware-releases-paraview-glance-an-advanced-in-browser-data-viewer/) we have a state handling managed natively so you can easily share a tuned visualization.

**Comment by jourdain** [comment]
Just something to be aware is that `getState()` does not support reference cycle.

**Comment by SchLagOs** [comment]
Thank you for your answer. I found a slightly different solution for loading because i needed to keep the current actors but changing their current state according to a previous one.

Have a nice day.
