### ISSUE TITLE
How to retrieve the boundary

### ISSUE THREAD

**Issue by ngunhaSO** [Kitware/vtk-js#814]
How to retrieve the boundary of an stl file? I can't seem to find the equivalent of the following classes vtkFeatureEdges, vtkStripper in vtk-js

Thank you

**Comment by jourdain** [comment]
To get the bounds, you just need to call `getBounds()` on the dataset. Regarding the filters, we don't currently have processing filters in vtk.js. A way to go can be to use WebAssembly by compiling there C++ counter part.

**Comment by ngunhaSO** [comment]
The getBounds() only return the min and max values of 3 coordinates, right? I was looking for how to get the polydata of the bounday edge of an stl file

**Comment by jourdain** [comment]
I see, you wanted to extract the feature lines. As I previously mentioned we don't have much filters on the JS side.
