### ISSUE TITLE
no.input error when using vtk.js in react 

### ISSUE THREAD

**Issue by malinged** [Kitware/vtk-js#816]
Im just trying to run the polydatareader example with my data in a react project. I am getting an error on load and on button press stating that there is no input. 

here is the code I am using: 

```
import React from 'react';
import vtkActor from 'vtk.js/Sources/Rendering/Core/Actor';
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkMapper from 'vtk.js/Sources/Rendering/Core/Mapper';
import vtkPolyDataReader from 'vtk.js/Sources/IO/Legacy/PolyDataReader';

export default class VtkGeometryRenderer extends React.Component {
  constructor (){
    super();
  }
  shouldComponentUpdate(){
    return false;
  }
  componentDidMount(){
//vtk.js try
const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance();
const renderer = fullScreenRenderer.getRenderer();
const renderWindow = fullScreenRenderer.getRenderWindow();

const resetCamera = renderer.resetCamera;
const render = renderWindow.render;


const reader = vtkPolyDataReader.newInstance();
reader.setUrl(`./Assets/cube_ascii.vtp`).then(() => {
  const polydata = reader.getOutputData(0);
  const mapper = vtkMapper.newInstance();
  const actor = vtkActor.newInstance();

  actor.setMapper(mapper);
  mapper.setInputData(polydata);

  renderer.addActor(actor);

  resetCamera();
  render();
});

global.reader = reader;
global.fullScreenRenderer = fullScreenRenderer;

  }
  render() {

    return (
          <div
              ref={(c) => {
              this.rootContainer = c;
            }}
          />
        );
};
```

and here is the error message and screen im getting on load: 
![image](https://user-images.githubusercontent.com/35342569/43478758-9e5f1448-94b3-11e8-9654-f1b990784f46.png)

**Comment by jourdain** [comment]
Did you try to see if you can get the vtp file with that url `http://localhost:3000/Assets/cube_ascii.vtp`

**Comment by malinged** [comment]
I loaded the file in the geometry viewer and it looks just like its supposed to. The file does show up at that url, I tried to run the example that you sent me to but it also spat out a lot of errors and crashed. 

here are the errors it put out, I didnt even try to rener the file, I was just trying to get the basic exact code that I saw to work. 
![image](https://user-images.githubusercontent.com/35342569/43485772-f66d4624-94c6-11e8-83c7-f633e86582d0.png)

**Comment by jourdain** [comment]
Well did you properly bind the container that was provided by React instead of doing a plain copy/paste?

Moreover, you need to make sure the div you bind to has a size... If the size is 0x0 it is possible that the canvas that get created does not like that to render something in it...

**Comment by jourdain** [comment]
For the URL did you look at the network tab to validate that the file was getting fetched?

**Comment by jourdain** [comment]
Did you also try to replace `./Assets/cube_ascii.vtp` by `http://localhost:3000/Assets/cube_ascii.vtp`

**Comment by malinged** [comment]
I can confirm the file was being fetched, and I have replaced it in the file. Still running in to the same issues. I did try to bind to the react component but i still got the same errors returned I dont think that is the issue. 


![image](https://user-images.githubusercontent.com/35342569/43486566-0685c872-94c9-11e8-930e-413cefba213d.png)

**Comment by jourdain** [comment]
I'm not saying react is producing that error, I'm just saying that your react component is not valid.
But like I said, you are not there yet... The main issue right now is that the data does not load.

But looking closer at your code, the issue is related to your import.
`vtk.js/Sources/IO/Legacy/PolyDataReader` is meant for vtk files not vtp.
You need to use the XML version which is available here: https://github.com/Kitware/vtk-js/tree/master/Sources/IO/XML/XMLPolyDataReader
