### ISSUE TITLE
Rotate center changed when re-bind keys

### ISSUE THREAD

**Issue by SchLagOs** [Kitware/vtk-js#818]
Hi,

I get an _issue_ with the **InteractorStyleManipulator** example (https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html). Indeed, when applied to vtp files, the rotation center is not the same but the focal point remains the same. This means that, even when i reset the camera view, the 3D models will turn around a point different from the general centroid.
Any idea on how to change this rotation and/or fix this _issue_ ?

**Comment by jourdain** [comment]
You need to manually set the center of rotation. It is on purpose not the focal point.
See what we do when we reset the camera to reset that center of rotation here:
https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/ViewProxy/index.js#L233

**Comment by SchLagOs** [comment]
It works very well ! Thank you so much !

Have a nice day.
