### ISSUE TITLE
ArrayBuffer already contains string

### ISSUE THREAD

**Issue by aagrosch** [Kitware/vtk-js#821]
Hi,

When trying to use `vtkXMLPolyDataReader.setUrl('./someFile')` or `vtkXMLImageDataReader.setUrl('./someFile')`, I get the error message:

```Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'```

The error originates from the BinaryHelper:
https://github.com/Kitware/vtk-js/blob/97d0be62f661f290a452d520cbd3daf0025918f3/Sources/IO/Core/BinaryHelper/index.js#L24-L25

Changing line 25 to `const str = arrayBuffer;` seems to solve the issue for me. Am I using the `setUrl` function wrong?

**Comment by jourdain** [comment]
Can you specify which browser you were running the code on?
Also what was the encoding of the vtp file?

1. ascii
2. binary
3. binary + zlib
4. appended
5. appended + zlib

**Comment by aagrosch** [comment]
I've tested it in both Chrome and Firefox. I only get the error message in Chrome, but looking at the Debugger in Firefox, it seems to fail at the same line of code.

For both vtp and vti files, I've tried
1. ascii
2. binary
3. binary + zlib

with and without the option `{ binary: true }`.

**Comment by jourdain** [comment]
Your change work for 1/2/3 as they are all just ascii. Only the appended will embed binary inside the XML. The option argument is not used in that reader. Although if the user know that's actually a valid XML (not 4/5), maybe we can shortcut the binary extract/processing...

@floryst should that [line](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/XML/XMLReader/index.js#L323) be replaced by a binary fetch unless the option tell us to fetch ascii?

**Comment by floryst** [comment]
Yeah we should use a binary fetch there. I'll make a PR.
