### ISSUE TITLE
VTK as Script tag overwrites native objects

### ISSUE THREAD

**Issue by swederik** [Kitware/vtk-js#826]
Hello,

It seems that when I import VTK using a script tag, it overwrites the browser's native 'Proxy' class with the contents of the [VTK.Proxy object](https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/index.js#L4).

Here is a codepen to demonstrate the issue:

https://codepen.io/swederik/pen/djqGXg?editors=1111

Please let me know if you need any more information.

Thanks,

Erik

**Comment by jourdain** [comment]
Wow, this is bad... Thanks for reporting the issue, I'll see what I can do...
