### ISSUE TITLE
XMLReader fails to read binary+zlib compressed image data

### ISSUE THREAD

**Issue by ckolb** [Kitware/vtk-js#829]
I am getting this error in processDataArray:
Uncaught (in promise) RangeError: Invalid typed array length: 12437

This is the header as it was read by the XMLReader:
(20) [4, 16, 32768, 0, 12437, 14192, 16673, 16968, 17821, 18420, 19889, 20968, 20587, 21113, 20650, 20044, 18927, 16130, 16216, 13540]

**Comment by floryst** [comment]
Which line is this occurring on? Also, is this a publicly available dataset?

**Comment by ckolb** [comment]
const compressedBlock = new Uint8Array(uint8.buffer, offset, blockSize);
line 160 in XMLReader/index.js

I can reproduce the error with this dataset: https://kitware.github.io/vtk-js-datasets/data/vti/LIDC2.vti
using the vtkXMLImageDataReader

**Comment by jourdain** [comment]
Which browser? Safari?

**Comment by ckolb** [comment]
Chromium 68

**Comment by jourdain** [comment]
Which OS?

**Comment by ckolb** [comment]
ArchLinux
i just tried to read the datasets in this example:
https://kitware.github.io/vtk-js/examples/VolumeViewer.html
This works!
As far as I can tell, I'm not doing anything differently in my code.

**Comment by jourdain** [comment]
Hum, ok... Can you share your code, maybe we can spot something?

**Comment by ckolb** [comment]
import vtkFullScreenRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
import vtkHttpDataSetReader from 'vtk.js/Sources/IO/Core/HttpDataSetReader';
import vtkImageMapper from 'vtk.js/Sources/Rendering/Core/ImageMapper';
import vtkImageSlice from 'vtk.js/Sources/Rendering/Core/ImageSlice';
import vtkRenderer from 'vtk.js/Sources/Rendering/Core/Renderer';
import vtkXMLImageDataReader from 'vtk.js/Sources/IO/XML/XMLImageDataReader';
import HttpDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';

const fullScreenRenderWindow = vtkFullScreenRenderWindow.newInstance({
  background: [0, 0, 0],
});
const renderer = fullScreenRenderWindow.getRenderer();

const renderWindow = fullScreenRenderWindow.getRenderWindow();
const imageMapper = vtkImageMapper.newInstance();
const imageActor = vtkImageSlice.newInstance();

renderer.getActiveCamera().setParallelProjection(true);

renderer.resetCamera();
renderWindow.render();

export function updateImage()
{
  HttpDataAccessHelper.fetchBinary("image/161").then((binary) => {
    const reader = vtkXMLImageDataReader.newInstance();
    reader.parseAsArrayBuffer(binary); // this fails

    imageMapper.setInputConnection(reader.getOutputPort());
    imageMapper.setSlicingMode(SlicingMode.K);
    imageActor.setMapper(imageMapper);
    renderer.addActor(imageActor);

    imageActor.setMapper(imageMapper);
    renderer.resetCamera();
    renderer.getActiveCamera().setParallelScale((height-1)*0.5);
    renderWindow.render();
  });

}

**Comment by ckolb** [comment]
i logged the output of 
function extractAppendedData(buffer)
in XMLReader and it seems to be correct. so I think that the error is not in  HttpDataAccessHelper

**Comment by floryst** [comment]
Instead of using HttpDataAccessHelper directly, maybe it'll be worthwhile to try using `setUrl()`:

```
const reader = vtkXMLImageReader.newInstance();
reader.setUrl("image/161").then(() => {
  imageMapper.setInputConnection(reader.getOutputPort());
  ...
})
```

I don't know how different that'll be from your approach, but worth a shot.

**Comment by jourdain** [comment]
Did you try to use `reader.setURL().then(...` instead of fetching it for it?

Internally that reader is doing the same thing as you are doing but it will be easier to read.

Also when you did your test with the volume viewer, did you load it as a file or as a remote url?

**Comment by jourdain** [comment]
Are you behind a proxy that could alter the file you download?

**Comment by ckolb** [comment]
in the volumeviewer example, i tested both.
in my code, "image/161" is a rest call that sends a local file

**Comment by jourdain** [comment]
Did you try the VolumeViewer locally for fetching your rest endpoint instead? Just to be sure that it is not your local server?

**Comment by ckolb** [comment]
I think I found the issue, however I really cannot imagine why this isn't a problem in the VolumeViewer example:

the base64-js package does not support concatenated Base64 strings:
https://github.com/beatgammit/base64-js/issues/42

I think the padding characters (==) are used in the compressed vti files to separate the header from the blocks?
Anyway, after this line:
const uint8 = toByteArray(dataArrayElem.firstChild.nodeValue.trim());  in XMLReader/index.js
the uint8 array is trimmed after 76 bytes, where the first '=' characters occur.

**Comment by jourdain** [comment]
Thanks for your investigation and actually figuring out what was going on...
This make me think we should embed such functionality inside vtk.js so issue like you ran into won't happen again...
