### ISSUE TITLE
Cutter and Cell Arrays

### ISSUE THREAD

**Issue by daalegend** [Kitware/vtk-js#832]
This may seem like a naive question, but I'm having trouble understanding how exactly to pick points on a 3D shape. Let's say I want to cut it in half. How exactly can I reference those points from the 1st half of the shape to display and cut the 2nd half of the shape? In other words, what exactly can I do to section off the shapes? I know cutter is a start, but it's using the line base that I'm a little confused about.

**Comment by jourdain** [comment]
I'm not sure of the question? Are you asking regarding the algorithm logic or the vtk structure to encode cells? In both case, you should be able to find plenty of resources explaining both.

**Comment by daalegend** [comment]
Could you please link me to the resources? I'm very excited to follow your recommendations! You're the only guy that could help.

**Comment by jourdain** [comment]
https://www.vtk.org/vtk-textbook/

**Comment by jourdain** [comment]
If you understand what this [class/algo](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/Core/Cutter/index.js) is doing, then you will know exactly what needs to be done for the case of a clip.

**Comment by daalegend** [comment]
Thanks for the algorithm! However, is it also possible to link the page numbers in the book which talk about this?
I'm currently a student working on a project for a research institute for a rather unorthodox internship. I'm pretty much on my own with trying to implement this software without any help from IT professionals and I'm not getting paid for it. Please forgive me for my naivety as I'm trying to work around this.
Thank you so much for the advice! I really value it!
