### ISSUE TITLE
ERROR in OpenGL/glsl/

### ISSUE THREAD

**Issue by bionick87** [Kitware/vtk-js#836]
Hi,

I was curious to try this interesting vtk js lib.
I am not expert of it, and i tried to install on my mac pro following perfectly this nice example:
 
https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

However, I got this error, maybe can you help me to resolve it.

i installed npm  vtk in this way:

$ npm install vtk.js --save
$ npm install kw-web-suite --save-dev

Thanks.

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkVolumeVS.glsl 18:10
Module parse failed: Unexpected token (18:10)
You may need an appropriate loader to handle this file type.
| =========================================================================*/
| 
> attribute vec4 vertexDC;
| 
| varying vec3 vertexVCVSOutput;
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/VolumeMapper/index.js 20:0-80 83:21-32
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkPolyDataVS.glsl 18:10
Module parse failed: Unexpected token (18:10)
You may need an appropriate loader to handle this file type.
| =========================================================================*/
| 
> attribute vec4 vertexMC;
| 
| // frag position in VC
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js 18:0-84 91:21-34
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkSphereMapperVS.glsl 19:10
Module parse failed: Unexpected token (19:10)
You may need an appropriate loader to handle this file type.
| // this shader implements imposters in OpenGL for Spheres
| 
> attribute vec4 vertexMC;
| attribute vec2 offsetMC;
| 
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/SphereMapper/index.js 12:0-92 29:21-38
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkStickMapperVS.glsl 19:10
Module parse failed: Unexpected token (19:10)
You may need an appropriate loader to handle this file type.
| // this shader implements imposters in OpenGL for Sticks
| 
> attribute vec4 vertexMC;
| attribute vec3 orientMC;
| attribute vec4 offsetMC;
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/StickMapper/index.js 7:0-90 27:21-37
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkPolyDataFS.glsl 19:8
Module parse failed: Unexpected token (19:8)
You may need an appropriate loader to handle this file type.
| // Template for the polydata mappers fragment shader
| 
> uniform int PrimitiveIDOffset;
| 
| // VC position of this fragment
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js 19:0-84 92:23-36
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkVolumeFS2.glsl 22:8
Module parse failed: Unexpected token (22:8)
You may need an appropriate loader to handle this file type.
| //VTK::Output::Dec
| 
> varying vec3 vertexVCVSOutput;
| 
| // camera values
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/VolumeMapper/index.js 22:0-82 85:25-37
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl 22:8
Module parse failed: Unexpected token (22:8)
You may need an appropriate loader to handle this file type.
| //VTK::Output::Dec
| 
> varying vec3 vertexVCVSOutput;
| 
| // camera values
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/VolumeMapper/index.js 21:0-80 87:25-36
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/ViewNodeFactory/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/OpenGL/RenderWindow/index.js
 @ ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
 @ ./src/index.js

ERROR in ./src/controller.html 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
| 
> <table>
|   <tr>
|     <td>
 @ ./src/index.js 11:0-45 58:33-45

**Comment by jourdain** [comment]
Like the error says, you are missing rules.

In the section `Webpack config` you might have skipped a couple of important things like:

```
var vtkRules = require('vtk.js/Utilities/config/dependency.js').webpack.v2.rules;
[...]
rules: [
        { test: entry, loader: "expose-loader?MyWebApp" },
        { test: /\.html$/, loader: 'html-loader' },
    ].concat(vtkRules),
[...]
```

**Comment by bionick87** [comment]
Hi thanks for the replay, 

The error was related to the wrong position of webpack.config.js . Indeed in the example in not clear where is the correct position of this file ( i.e inside src or outside)

However, after npm start in the browser http://localhost:8080 the system not display the vtk app but just a series of strings:

/******/ (function(modules) { // webpackBootstrap /******/ // The module cache /******/ var installedModules = {}; /******/ /******/ // The require function /******/ function __webpack_require__(moduleId) { /******/ /******/ // Check if module is in cache /******/ if(installedModules[moduleId]) { /******/ return installedModules[moduleId].exports; /******/ } /******/ // Create a new module (and put it into the cache) /******/ var module = installedModules[moduleId] = { /******/ i: moduleId, /******/ l: false, /******/ exports: {} /******/ }; /******/ /******/ // Execute the module function /******/ modules[moduleId].call(module.exports, module, module.exports, __webpack_require__); 

Then, my questions are fully linked to the example that vtk.js ( that is very important for people as me that don't know nothing about vtk and npm interaction, but still want to learn it)

https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html

a) In index.js there is the vtk code example and indeed in  webpack.config.js  contains the 
 var entry = path.join(__dirname, './src/index.js'); 
But still not fully clear way there is MyWebApp.js ( i.e is never cite in the example) 
So, is index that has the vtk code or  MyWebApp.js ?

module.exports = {
  entry,
  output: {
    path: outputPath,
    filename: 'MyWebApp.js',
  },

c) Always in webpack.config.js i don't fully understand this rules:

 rules: [
        { test: entry, loader: "expose-loader?MyWebApp" },
        { test: /\.html$/, loader: 'html-loader' },
    ].concat(vtkRules),

What dose mean -- expose-loader?--  and way link  a MyWebApp that is in js and not html?

d) Way dist/index.html is never used in webpack.config.js , that should be a door for opening the vtk MyWebApp ( or ndex.js -- very confuse for me here).

**Comment by jourdain** [comment]
a) You should read more about code bundler like Webpack. Basically the compiled/bundle result endup in `./dist/MyWebApp.js` next to the `dist/index.html` that reference it.

b) The loader rules expose to the global `window.MyWebApp` namespace what ever you export in your entry file. (Same here reading Webpack documentation would help you understand modern web development.)

c) The dist directory contains the products that can them be served by a web server like apache. So when the index.html reference a script like `<script type="text/javascript" src="MyWebApp.js"></script>` then, that means the browser will try to load a file `MyWebApp.js` in  that same directory.

**Comment by jourdain** [comment]
I've prefixed all the path with `./` in the doc to hopefully make it more obvious where the file are going.

**Comment by bionick87** [comment]
Hi,

Thanks for making path root on example more clear, I suggest to explain also the rule of dir dist that is strategic for a better understanding.
Now the example, works! Maybe in future i will have some other questions. 
Thanks.

**Comment by bionick87** [comment]
Hi,

Thanks for making path roots on this example more clear, I suggest to explain also the role of dir dist that is strategic for a better understanding.
Now the example, works! Maybe in future i will have some other questions. 
Thanks.

**Comment by jourdain** [comment]
Feel free to contribute some add-on to [the documentation](https://github.com/Kitware/vtk-js/blob/master/Documentation/content/docs/intro_vtk_as_es6_dependency.md) since you know more were beginner are more likely to struggle.

**Comment by floryst** [comment]
Closing due to age, but I'll be documenting this.
