### ISSUE TITLE
how can I use vtk.js in potree

### ISSUE THREAD

**Issue by tomhaitao** [Kitware/vtk-js#839]

**Comment by jourdain** [comment]
I don't know.

**Comment by tomhaitao** [comment]
Can vtk.js be used with three.js

**Comment by jourdain** [comment]
Not sure either although it depends what you mean.

**Comment by floryst** [comment]
Closing due to age, but vtk.js and three.js cannot be intermixed due to each wanting individual control of the webgl context.
