### ISSUE TITLE
model.rGBTransferFunction.getMTime is not a function

### ISSUE THREAD

**Issue by tomhaitao** [Kitware/vtk-js#842]
const actor = vtkImageSlice.newInstance();
const lookupTable = vtkColorTransferFunction.newInstance();
const preset = vtkColorMaps.getPresetByName('erdc_rainbow_bright');
lookupTable.applyColorMap(preset);
lookupTable.setMappingRange(...dataRange);
lookupTable.updateRange();
actor.getProperty().setRGBTransferFunction(0, lookupTable);

I use this code but vtkImageProperty class line 60 is error:
         model.rGBTransferFunction.getMTime is not a function

**Comment by tomhaitao** [comment]
import vtkColorTransferFunction from 'vtk.js/Sources/Rendering/Core/ColorTransferFunction';

**Comment by tomhaitao** [comment]
How to set color for vtkImageSlice?

**Comment by jourdain** [comment]
@martinken

**Comment by martinken** [comment]
actor.getProperty().setRGBTransferFunction(0, lookupTable);

should be

actor.getProperty().setRGBTransferFunction(lookupTable);

I'll add a fix so that it doesn't try calling getMTime on 0, the current test is !== null
