### ISSUE TITLE
camera.setParallelProjection(true) issue

### ISSUE THREAD

**Issue by tanxu1120** [Kitware/vtk-js#843]
I just need to set camera.setParallelProjection(true), the volume will not be displayed.
Please help me find out what the problem is.
Thanks!!!

**Comment by jourdain** [comment]
Did you try to reset the camera when in parallel projection?

**Comment by tanxu1120** [comment]
@jourdain Yes, I did that.However, it still cannot be displayed.

**Comment by mix3d** [comment]
following up on this, we're trying to use parallel projection and it's still not working.

I've tried the above methods, played with clipping points and parallelScale, but nothing seems to work.

in one case, I managed to get some things to render, but moving the camera (in a method needed for our MPR approach, moving the focal plane and camera distance together through the volume, with a small clipping plane) results in VERY strange cropping.

Looked through the code, and there doesn't seem to be any unit tests for the camera at all, so I'm not totally surprised.

How can we help debug this?

**Comment by mix3d** [comment]
example of strange cropping issue:
![perspective progress](https://user-images.githubusercontent.com/1474137/67121542-9813b300-f1a0-11e9-8428-bf8d1ae8395b.gif)

The rendered volume slice stays the same dimensions/scale, but moving the camera closer/farther into the volume crops unusually. If I change the camera angle to one not defaulted to a cartesian coord, the clipping becomes even stranger.

**Comment by mix3d** [comment]
Update: I made a small codepen trying to reproduce the problem. Seems to work in this very small case, so I'm going to keep adding to it until it breaks. 

One thing I've notices is that if you don't `resetCamera()`and the camera is significantly moved from the default view when switching to parallelProjection, the cone does not render (or renders off screen)

The above examples are using volumes that are `256 x 256 x ~100-500` in world dimensions, which may also be playing a part in the weirdness if most examples are in much smaller scale units.

**Comment by mix3d** [comment]
My "hack" solution for this is to use a camera viewAngle of 1 degree. This approximates a parallel view well enough, but doesn't solve the core problem.

**Comment by mix3d** [comment]
@jourdain @martinken any thoughts / is this on your radar? Perhaps a bug label at least?

**Comment by martinken** [comment]
I'll try takjng a quick look. Should be a very small fix once I locate the issue.

**Comment by JamesAPetts** [comment]
Hey @martinken ,

I've found the issue, I'll get a PR up soon!

**Comment by martinken** [comment]
Awesome @JamesAPetts ! Tag me on the PR if you want and I'll do a review.

**Comment by JamesAPetts** [comment]
https://github.com/Kitware/vtk-js/pull/1230

**Comment by martinken** [comment]
Fixed by @JamesAPetts  in https://github.com/Kitware/vtk-js/pull/1230
