### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by Gao-XiaoShi** [Kitware/vtk-js#847]
I found a bug in the file : vtk-js/Sources/Imaging/Core/ImageReslice/index.js ,the line is 66,
(origin[2] + 0.5 * (inWholeExt[4] + inWholeExt[5]) * inSpacing[0],)  <--the index of inSpacing must be 2 not 0?because this is the Z axes

**Comment by jourdain** [comment]
@finetjul

**Comment by finetjul** [comment]
Good catch, thanks !
