### ISSUE TITLE
Issue with tubeFilter

### ISSUE THREAD

**Issue by ghost** [Kitware/vtk-js#848]
Hi,

I get an issue when i try to tubeFilter some vtp files.

![issue_tubing](https://user-images.githubusercontent.com/40494123/44451792-0092ee80-a5f5-11e8-9ceb-8931d3577b5c.png)

As you can see, some tubes are not drawn. I guess it's because the lines are not "smooth enough" (the derivate is not continuous enough), but maybe you already got this issue in the past.

Have a good day.

**Comment by jourdain** [comment]
@sankhesh

**Comment by sankhesh** [comment]
@SchLagOs The tube filter does not add any curvature/bend or smart smoothing at the intersection of two tubes. Try removing intermediate points from the input polylines based on a curvature threshold.

**Comment by SchLagOs** [comment]
@sankhesh thank you for your answer. However, due to process which must be very accurate, i can't remove points from the input polylines. Is there an other way to solve this ?

**Comment by sankhesh** [comment]
@SchLagOs The better (and right) way to solve it would be to add capabilities to the tube filter. Ideally, you want a tubular end to each tube based on the parameters computed for the next or prior tube.

**Comment by sankhesh** [comment]
Another possible solution, and this one wouldn't require modifications to the tube filter, is to pass the input polylines through a connectivity filter and reduce each loop to be a single cell (line) with the same number of points.

**Comment by jourdain** [comment]
Closing as it could be handled by pre-processing user data to match vtkTubeFilter expectation
