### ISSUE TITLE
AxesActor is missing

### ISSUE THREAD

**Issue by ericdebleumortier** [Kitware/vtk-js#852]
I updated my vtk.js to the latest version (`7.6.1`). 

But the `AxesActor` is missing under `vtk.Rendering.Core`.
Is it normal?

(As company restriction I can't use ES6 right now, so I grabed the js file under `node_modules\vtk.js\dist\vtk.js`)

**Comment by jourdain** [comment]
Just a mistake... Thanks for letting us know... Should be updated/fixed in the next release (probably tomorrow)

**Comment by ericdebleumortier** [comment]
This is working, thanks!
