### ISSUE TITLE
left handed image data direction matrix

### ISSUE THREAD

**Issue by pieper** [Kitware/vtk-js#858]
The[ ImageData code](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/ImageData/index.js#L249-L255) says the direction matrix needs to be orthonormal, but does it also need to be right handed?

I ran into this because the VolumeMapper rendering is not right when a left handed direction matrix.

This can be reproduced by running the example like this
```bash
npm run example -- VolumeMapper
```

And then pasting this in the browser developer console:

```javascript
source.getOutputData().getDirection()[8] *= -1
```

And when you rotate around you get images like this:

![image](https://user-images.githubusercontent.com/126077/44820481-05403f80-abbf-11e8-862d-80f71f56b2c8.png)

I get the same kind of issue when loading my own data with left handed direction matrices.

This is an issue because sometimes medical image acquisitions are naturally left handed.  For example a person could be put in a CT scanner either foot-first of head-first.  While the patient space (e.g. [LPS or RAS](https://www.slicer.org/wiki/Coordinate_systems)) is right handed, the direction matrix may not be if you leave the slices in the order they were acquired.  As I recall, ITK reshuffles the slices in memory in this case so that the direction matrix is right handed, but I would prefer to avoid that if possible.

It's not clear if this is a bug in the VolumeMapper or if vtkjs is meant to require right handed direction matrices (in which case it should be documented).

Related to: https://github.com/Kitware/vtk-js/issues/499

**Comment by pieper** [comment]
It's a little harder to test, but it looks to me that regular VTK has similar behavior.

**Comment by aylward** [comment]
Attached are two files that demonstrate this behavior.  In one file (head-failSwap.mha) the Y and Z axis are swapped in the direction matrix.  In the other file (head-failInv.mha) the Z axis has a negative orientation in the direction matrix.   Both result in odd rendering behavior.

I've placed both files in this zip file:
   [head-fail.zip](https://github.com/Kitware/vtk-js/files/2337883/head-fail.zip)

**Comment by martinken** [comment]
I think I am looking into this issue right now :-) At least it seems similar and involves an inverted axis.  I'll let you know what I find.

**Comment by martinken** [comment]
The issue I am looking into was emailed from Stephen on June 15th, just behind a bit.

**Comment by martinken** [comment]
Found the issue, ImageData was using a quaternion for the direction, which cannot handle inversions so the transforms to/from index to world were not correct.  Should be fixed in

https://github.com/Kitware/vtk-js/pull/870

I do worry that something somewhere else might break (tests all passed) Just because I know I tend to think everything is in a right handed coordinate system once loaded from a file. With vtk.js we are allowing left handed data objects so...

**Comment by martinken** [comment]
Looks to be fixed. Thanks!

**Comment by pieper** [comment]
Works for me - thanks! 👍
