### ISSUE TITLE
Live example OrientationMarkerWidget BUG

### ISSUE THREAD

**Issue by tanxu1120** [Kitware/vtk-js#866]
Live example OrientationMarkerWidget  : if you replace the data source with a volume browser crash.

**Comment by jourdain** [comment]
You will need to provide more specifics regarding the issue (GPU, vtk.js version, browser, OS...) as we have working examples of what you describe with Glance (see picture below). Although it is true that a while back this was an issue, but it was fix.

![volumerenderingwithorientationwidget](https://user-images.githubusercontent.com/294518/45163213-1388ef80-b1ad-11e8-804a-6bd435c6c20c.jpeg)

**Comment by jourdain** [comment]
See issue #728

**Comment by tanxu1120** [comment]
GPU : NVIDIA GeForce GT 730M
vtk.js version : 7.6.0
browser : Google Chrome 68.0.3440.106
OS : win7 64bit service pack 1

**Comment by jourdain** [comment]
@martinken I guess you will have to test on Windows...

I've tried on Mac with Safari to run vtk.js as WebGL 1 and noticed an issue with the textures on the cube.

![vtk-js](https://user-images.githubusercontent.com/294518/45196677-9b591300-b21a-11e8-82de-4d8688361d2a.jpeg)

**Comment by tanxu1120** [comment]
I have not tested with paraview-glance, I am using my own code written in vtk.js, then I can download a paraview-glance test

**Comment by tanxu1120** [comment]
Paraview-glance is fine, let me see my code again.
