### ISSUE TITLE
STL import not inline with other soft (e.g. meshlab / 3d slicer )

### ISSUE THREAD

**Issue by yh3ds** [Kitware/vtk-js#867]
Hello,
if I load the two STL attached to this message in meshlab (for example but it is not the only software behaving like that), they are overlapping in the renderer.

But if I load them with vtk.js (and Glance), they are not overlapping (see screen capture). 

I don't get why ? 
Am I missing somethong ? 

Thanks a lot
[test_X_Y_Z_exportforVTKJS.zip](https://github.com/Kitware/vtk-js/files/2365511/test_X_Y_Z_exportforVTKJS.zip)

![problemimportexport](https://user-images.githubusercontent.com/43130636/45282129-5cf17b80-b4da-11e8-9bd3-ef1b11a06d9f.jpg)

**Comment by jourdain** [comment]
The current version of stl reader in vtkjs does not read any transform.

**Comment by jourdain** [comment]
Thanks for looking into it.
