### ISSUE TITLE
Set progressCallback on HttpDataSetReader

### ISSUE THREAD

**Issue by linsheng** [Kitware/vtk-js#871]
Hi,

I want to get the data loading progress when load a remote file. HttpDataSetReader has a setProgressCallback method but the callback function is not called after I set progressCallback. I found an example on vtk.js website but it uses HttpDataAccessHelper. Can I use progressCallback directly with HttpDataSetReader?

This is the code I used to test.

```
const progressCallback = (progressEvent) => {
    ...
}

const reader = vtk.IO.Core.vtkHttpDataSetReader.newInstance();
reader.setProgressCallback(progressCallback);
reader.setUrl('remote_file_url').then(...);
```

Thanks.

**Comment by linsheng** [comment]
Thanks @jourdain, but it didn't work. The callback function is still not called.

**Comment by linsheng** [comment]
Thanks. I'll check on my side too.

**Comment by floryst** [comment]
If this is still an issue, please re-open.
