### ISSUE TITLE
How to load a XYZ file in VTK-JS?

### ISSUE THREAD

**Issue by muthugit** [Kitware/vtk-js#872]
Hi,
I've rendered my custom XYZ file in TCL-TK. But don't know how to load and render the XYZ file in VTK-JS. Need to know the appropriate reader.

**Comment by jourdain** [comment]
Mostly the same way except that we don't have a XYZ reader, so you will have to implement it.
There should be plenty of example out there that help you on `how to render something in a web page` and also in some way `how to load data`.

**Comment by muthugit** [comment]
Thanks @jourdain
