### ISSUE TITLE
The line of the lineWidget is not always drawn

### ISSUE THREAD

**Issue by marcel1986** [Kitware/vtk-js#873]
When adding the lineWidget to the ikt-vtk-image-viewer and running it then only the SphereRepresentations are drawn when looking at the top view.  When switching to any other view then the line becomes visible. This can also be seen on the examples page of vtk.js when trying out the LineWidget example on the main page of LineWidget. Tried it both on firefox and chrome.
![linewidget_example_page](https://user-images.githubusercontent.com/1233510/45438935-cfb84d80-b6b8-11e8-9a64-31d6b6858044.PNG)

**Comment by thewtex** [comment]
@marcel1986 `renderWindow.render()` may be required to draw the line.

See, e.g.:

https://github.com/thewtex/itk-jupyter-widgets/commit/8ab2da5efeaaf5630e1c1434f5688ca9faaf987e

which is adding a line widget to `itk-vtk-viewer` to generate line profiles:

https://github.com/thewtex/itk-jupyter-widgets/commits/line_profile

**Comment by mix3d** [comment]
can confirm, lineWidget does not draw the line
https://kitware.github.io/vtk-js/examples/LineWidget.html

**Comment by floryst** [comment]
Line widget has been updated since, and the line now renders. If this is still an issue, please re-open.
