### ISSUE TITLE
PlaneSource setOrigin issue

### ISSUE THREAD

**Issue by alesgenova** [Kitware/vtk-js#882]
Hi!

I need to draw parallel planes in vtkjs, and my approach is the following:
The two planes share the same `point1` and `point2` and only differ from their origin.
According to the documentation, this should be easily achievable by using the `setOrigin` method on one of the two planes.

> Origin (set/get)
> Float array of size 3 representing the origin of the plane, lower-left corner.

However I run into an unexpected behavior, where the plane gets distorted after setting the origin.

You can easily reproduce this problem even in the official [PlaneSource example](https://kitware.github.io/vtk-js/examples/PlaneSource.html). Setting the origin to anything but `[0, 0, 0]` will yield a distorted plane.

**Comment by jourdain** [comment]
What you are describing is the expected behavior as a plane is defined by those 3 points.

```
(point 1) -----------+
|                    |
|                    |
|                    |
|                    |
(origin) ------- (point 2)
```

**Comment by alesgenova** [comment]
Yep, after playing around a little longer I realized that the points themselves needed to be translated by the origin.
Thank you!
