### ISSUE TITLE
Loading STLs dynamically

### ISSUE THREAD

**Issue by ericdebleumortier** [Kitware/vtk-js#886]
In a project I'm forced to add/remove STLs at different time (button pressing) in the same renderer.

I based my code on the example [here](https://kitware.github.io/vtk-js/examples/STLReader.html).

But I face a problem where the STLs are not fully loaded before updating the renderer.

The `reader.setUrl( my_file.stl, { binary: true }).then(update);` does seems to work properly because in the console I'm always getting **"No input"** messages.

The error is coming from there

```
model.currentInput = model.renderable.getInputData();
    publicAPI.invokeEvent(EndEvent);

    if (model.currentInput === null) {
      vtkErrorMacro('No input!');
      return;
    }
```

Any idea on what's wrong ? Or maybe I did'nt catch the correct way of loading multiple STLs ...

**Comment by jourdain** [comment]
Assuming `my_file.stl` is a correct string that match the url where the file can be downloaded, on thing you should do is to add the actor only once the data is loaded.

Did you check the network tab, to make sure the file was properly downloaded? 

Maybe you can share more code on your end to make sure the pipeline get properly connected?

**Comment by jourdain** [comment]
It works, but you need one reader/mapper/actor per data you want to show.

```
var fullScreenRenderer = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance( { 
  rootContainer: document.getElementById("renderer_1"),
  containerStyle: {
    height: '50%',
    width: '50%',
    overflow: 'hidden',
  }
} );

var fullScreenRenderer2 = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance( { 
  rootContainer: document.getElementById("renderer_2"),
  containerStyle: {
    height: '50%',
    width: '50%',
    overflow: 'hidden',
  }
} );


//Set default options to renderer
fullScreenRenderer.getRenderer().getActiveCamera().setParallelProjection(true);
fullScreenRenderer.getRenderer().setLayer(1);
fullScreenRenderer2.getRenderer().getActiveCamera().setParallelProjection(true);
fullScreenRenderer2.getRenderer().setLayer(1);


//Declare all files with parameters such as opacity, color...
var files = [
  { url: "./stl/Tibia.stl", opacity: "0.8" , caption:"Tibia" },
  { url: "./stl/Talus.stl", opacity: "0.8" , caption:"Talus" },
]; 

function processFile(file) {
    var mapper = vtk.Rendering.Core.vtkMapper.newInstance({ scalarVisibility: false });
    var actor = vtk.Rendering.Core.vtkActor.newInstance();
    var reader = vtk.IO.Geometry.vtkSTLReader.newInstance();

    actor.getProperty().setOpacity( file.opacity );
    actor.setMapper(mapper);    
    mapper.setInputConnection(reader.getOutputPort());

    function addActor() {
        fullScreenRenderer.getRenderer().addActor(actor);
        fullScreenRenderer.getRenderer().resetCamera();
        fullScreenRenderer.getRenderWindow().render();
        
        fullScreenRenderer2.getRenderer().addActor(actor);
        fullScreenRenderer2.getRenderer().resetCamera();
        fullScreenRenderer2.getRenderWindow().render();
    }

    reader.setUrl( file.url, { binary: true }).then(addActor);
}

for (var i = files.length - 1; i >= 0; i--) 
{
    processFile(files[i]);
}
```

**Comment by ericdebleumortier** [comment]
Thanks, it works well indeed.
Is it possible to pass arguments to a promise?

Because here the `addActor()` function is declared many time.
Is it possible to extract this function somewhere else and in the` processFile` just use something like this

`reader.setUrl( file.url, { binary: true }).then(addActor( actor ));` ?

**Comment by jourdain** [comment]
I'm glad that's working.
