### ISSUE TITLE
InteractorStyle / Zoom

### ISSUE THREAD

**Issue by aminechir** [Kitware/vtk-js#888]
When we zoom with the InteractorStyleTrackballCamera, we can set the motionFactor which allows us to control the sentitivity of the rotation. But we cannot control the level of the zoom because in the function 

```
publicAPI.handleMouseWheel = (callData) => {
    const dyf = 1 - callData.spinY / 10; // divide by 10 to lower the zoom factor
    publicAPI.dollyByFactor(callData.pokedRenderer, dyf);
  };
```
The factor to lower the zoom is hard coded in the function. It is planned in later version to use a setter/getter to control this value ?

Thanks a lot.

**Comment by jourdain** [comment]
Feel free to provide a PR for that.
