### ISSUE TITLE
Timing issue with new viewProxy's setOrientation() 

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#894]
I've been working on updating some code to accommodate newer vtk.js releases and have run into an issue with the `setOrientation` method of the `vtkViewProxy`.  For background, I'm working within a React framework and currently trying to update to vtk version 7.11.1.  Before, I had set up the proper view orientation in the constructor of my component, then set container, added representations, subscriptions, etc. in the `componentDidMount` method and it worked just fine.  Now, using relatively the same setup, I'm seeing an initial camera/view orientation that is somewhere in between the default and the values I input.  After investigating a bit, I'm seeing that the [callback](https://github.com/Kitware/vtk-js/blob/06fd17eb4301216dbff326bac70b154aed353c0f/Sources/Proxy/Core/ViewProxy/index.js#L431-L449) within the returned Promise doesn't complete until after the `componentDidMount` and even `componentDidUpdate` methods are called.  I inserted some console logs and set a break point to demonstrate here (there are 2 Viewport3D components): 
![image](https://user-images.githubusercontent.com/16705837/46324920-2f689100-c5b3-11e8-9951-e2b0bb1e1844.png)

I guess I have a couple questions about this:  Is this indeed an issue with unexpected/undesired timing of events? If so, how can we modify that initial setup to ensure everything is properly setup before adding any representations and rendering.  If not, what is the optimal workflow/pipeline for setting up the view, then adding representations, subscriptions, etc. and rendering? 

Thanks for the help,
-Logan

**Comment by floryst** [comment]
The logic you linked is to animate the view orientation changes. Since that callback is on an interval timer, the only way to invoke a callback after the animation finishes is through the Promise:

```
view.updateOrientation(...).then(() => {
  // orientation is now done transitioning
});
```

The same goes with `view.resetOrientation`, since that just returns the `updateOrientation` promise. Try doing your representations/etc. setup in the promise `then(...)`.

**Comment by llangholz89** [comment]
I've given that a try as well, however in keeping my logic within my `componentDidMount` mostly the same but moving the reps setup to the `then(...)` callback I still get some inconsistent results.  I'm wondering if the initial `publicAPI.resetOrientation()` call [here](https://github.com/Kitware/vtk-js/blob/06fd17eb4301216dbff326bac70b154aed353c0f/Sources/Proxy/Core/ViewProxy/index.js#L493) might be causing issues in my case.  I've added additional console log statements [here](https://github.com/Kitware/vtk-js/blob/06fd17eb4301216dbff326bac70b154aed353c0f/Sources/Proxy/Core/ViewProxy/index.js#L433) and adjusted that initial reset mentioned above to: `publicAPI.resetOrientation().then(() => console.log('done resetting in initialization'))` and get the following output: 
```
initialized in constructor                        Viewport3D.jsx?c510:31
starting didMount                                 Viewport3D.jsx?c510:62
animating orientation update: vtkViewProxy        index.js?ef81:433 
animating orientation update: vtkViewProxy        index.js?ef81:433 
done resetting in initialization                  index.js?ef81:494 
done resetting in `DidMount`, setup reps here     Viewport3D.jsx?c510:67 
```
Would tinkering with the camera position twice like that cause an issues? Also, does the reset on initialization really need to be asynchronous? For a general workflow like this, my instinct would be that any initialization of my `viewProxy` instance would be complete by the time I reach the `componentDidMount` phase of my component, assuming it's initialized in the constructor.

**Comment by llangholz89** [comment]
For a reference, the inconsistent results I'm getting are shown here.  I'm transitioning to: `axis= 1; orientation= 1; viewUp= [0, 0, -1]` (first picture), but wind up somewhere else (second picture).  I do get correct orientation most of the time when working with image data, but there's an initial "flash" that I'd like to get around if possible.
![screen shot 2018-10-02 at 9 28 06 am](https://user-images.githubusercontent.com/16705837/46359562-bc98fd80-c626-11e8-9ed0-58b5305e65d2.png)
![screen shot 2018-10-02 at 9 20 09 am](https://user-images.githubusercontent.com/16705837/46359583-c6226580-c626-11e8-90c4-1d782e38a122.png)

**Comment by jourdain** [comment]
I would agree that for an`animateSteps = 0`, we should not request animation. 
The reason why we call the resetOrientation at constructor time is to properly apply the orientation provided at construction time (or the one defined in default if nothing is provided).

Feel free to provide a PR with a code that directly apply the orientation.

```
publicAPI.updateOrientation = (
    axisIndex,
    orientation,
    viewUp,
    animateSteps = 0
  ) => {
   [...]

   if (animationStack.length === 1) {
       // update camera
       model.camera.set(animationStack.pop());
       model.renderer.resetCameraClippingRange();
       if (model.interactor.getLightFollowCamera()) {
            model.renderer.updateLightsGeometryToFollowCamera();
       }
       return Promise.resolve();
   }

   return new Promise((resolve, reject) => {
   [...]
}
```

**Comment by jourdain** [comment]
In essence that will do the same as the suggested code. Except that the updateOrientation should also properly handle direct apply instead of a delayed one. So the code I suggest should still exist regardless of what is called in the constructor. But in general I would rather call an existing method.

**Comment by llangholz89** [comment]
Right, I was thinking in addition to the logic you provided but just replacing that line I had indicated.  I suppose it doesn't matter.  You can't supply a callback to that Promise return anyway with it being within the initialization.  I'll put a PR together with just those changes. Thanks again!
