### ISSUE TITLE
Shader customization using GeometryRepresentationProxy

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#900]
I would like to use the ProxyManager and its GeometryRepresentationProxy in my app with shader customization. From what I understood, the geometry proxy will create a vtkMapper from which I can use the viewSpecificProperties attribute to replace the shaders. This should be the generic way to modify the sharders, am I right?

If I add a vtkPolyData as an input data of the proxy, is there a way to use the vtkPolyDataMapper API to customize the shaders? Should I write my own RepresentationProxy?

**Comment by jourdain** [comment]
What might be missing is the getter for the various pieces that compose the RepresentationProxy. But you still have access to the method `getReferenceByName('mapper')` to get your hand on the mapper.

**Comment by BotellaA** [comment]
Yes, there is a getter but it will get this generic vtkMapper (https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Representations/GeometryRepresentationProxy/index.js#L31) and not for example a vtkPolyDataMapper. So all the great API you did on this class is 'it usable with proxies?

**Comment by jourdain** [comment]
@martinken how to you get the OpenGL implementation from its generic vtkMapper?

**Comment by martinken** [comment]
Arguably a mapper could have multiple reps OpenGL, vulkan, pdf etc.  So you start at the top for the API you want and call getViewNodeFor(mapper)

ala

let openglMapper = openGLRenderWindow.getViewNodeFor(mygenericmapper);

**Comment by BotellaA** [comment]
Thanks a lot @jourdain @martinken for your help and your reactivity!!

**Comment by BotellaA** [comment]
Hello @martinken, I am only trying your proposition now.. one year later... :disappointed: 
It does not seem to work as you were expected:
```
function createSource(proxyManager, dataset) {
  const source = proxyManager.createProxy('Sources', 'TrivialProducer');
  source.setInputData(dataset);
  source.activate();
  proxyManager.getViews().forEach(v => {
    const rep = proxyManager.getRepresentation(source, v);
    const mapper = rep.getMapper();
    const window = v.getOpenglRenderWindow();
    const OpenglMapper = window.getViewNodeFor(mapper);
    console.log('OpenglMapper', OpenglMapper);
  });
  return source;
}
```
I get `OpenglMapper undefined`. There is a `vtkOpenGLPolyDataMapper` in the children of the `window` but I do not know how to validate it is the one corresponding to my `source`.

**Comment by jourdain** [comment]
Looking at the code, it seems that it should work.

**Comment by BotellaA** [comment]
It might not be rendered yet. Is there an event of something to hook on first render?

**Comment by jourdain** [comment]
I don't think so, but you can trigger a render inside you initialization.

**Comment by BotellaA** [comment]
I modified my function like this:
```
function createSource(proxyManager, dataset) {
  const source = proxyManager.createProxy('Sources', 'TrivialProducer');
  source.setInputData(dataset);
  source.activate();
  proxyManager.getViews().forEach(v => {
    const rep = proxyManager.getRepresentation(source, v);
    v.renderLater();
    setTimeout(() => {
      const mapper = rep.getMapper();
      const window = v.getOpenglRenderWindow();
      const OpenglMapper = window.getViewNodeFor(mapper);
      console.log('OpenglMapper', OpenglMapper);
    }, 1000);
  });
  return source;
}
```
Now I have two `vtkOpenGLPolyDataMapper` in the children of the `window`, so your assumption seems right. However, I still get an `undefined`.

**Comment by jourdain** [comment]
This should work at that point, I'm not sure how the lookup is not properly happening. You may need to debug a bit more why the glMapper.renderable does not match your generic mapper.

**Comment by BotellaA** [comment]
Yes it works. I missed my test...
