### ISSUE TITLE
Rotation (elevation) of camera by -90 degrees seems to have singularity issues

### ISSUE THREAD

**Issue by DominionSoftware** [Kitware/vtk-js#902]
first resetCamera() is called with a volume added to scene.

volume renders ok.

camera starting position [159.375 159.375 1098.180634218645,1].
camera focal point [159.375 159.375 116.99979400634766,1];
camera matrix [1 0 0 159.375
                         0 1 0 -159.375
                         0  0 1 -1098.1806640625;
                          0 0 0 1]

// want a different view of the volume.
camera.elevation(-90);

camera matrix is  [0 0 0 -0; 
                         0 0 0 -0; 
                         0 -1 0 -821.805908203125; 
                         0 0 0 1];
// above looks strange
// resulting position seems to be rotated 180.0 (or -180)

// instead use -89.99

// vtk camera matrix when camera.elevation(-89.999)
 [ 1 0 -0 -159.375
   0 0.000017456506611779332 1 -117.00257873535156
  0 -1 0.000017456506611779332 -821.807861328125
  0 0 0 1]

 // rotates camera into expected position, view of volume is as expected.

**Comment by jourdain** [comment]
I believe the issue is related to a non incremental update where the viewUp is not valid and end-up being recomputed.

What happen if you call 
```
camera.elevation(-45);
camera.elevation(-45);
```

**Comment by DominionSoftware** [comment]
Yes that works.

**Comment by jourdain** [comment]
That behavior is expected.

**Comment by DominionSoftware** [comment]
Really? That seems odd. C++ vtk doesn't have that issue. I'm sure I'm not the only one who will get tripped up on it.

**Comment by jourdain** [comment]
I guess such corner case could be handled internally to the camera class. @martinken what do you think?

**Comment by DominionSoftware** [comment]
It’s extremely common in medical imaging to rotate the camera about the focal point by multiples of 90 degrees to position a volume so that the anterior of the patient faces the viewer.

Rick Frank
Sent from Mobile
617-838-2031

On Oct 4, 2018, at 5:16 PM, Sebastien Jourdain <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess such corner case could be handled internally to the camera class. @martinken<https://github.com/martinken> what do you think?

**Comment by martinken** [comment]
Should be fixed IMO, fix is easy, just use the same alg from the method in C++. Whip up a MR and I can review.

**Comment by DominionSoftware** [comment]
Unfortunately I’m moving off my current js project and can’t assist. I recommend quaternions.

Rick Frank
Sent from Mobile
617-838-2031

On Oct 5, 2018, at 10:12 AM, Ken Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be fixed IMO, fix is easy, just use the same alg from the method in C++. Whip up a MR and I can review.

**Comment by zbouslikhin** [comment]
Hi,

Any update on this one (or trick) to avoid such behavior when rotating using elevation()?

**Comment by martinken** [comment]
Seb suggested breaking the 90 degree rotation into two 45 degreee ones, that seems to work while waiting for someone to patch the issue

**Comment by zbouslikhin** [comment]
Another temporary solution that worked in my case is to use `orthogonalizeViewUp()` after every `azimuth()` or `elevation()`. Hope this helps anyone.
