### ISSUE TITLE
How to display multiple line segments with one actor

### ISSUE THREAD

**Issue by HuWei501** [Kitware/vtk-js#914]
My current approach is implemented with multiple actors.
But I found that too many actors can cause performance problems.
So I want to merge multiple actors.What should I do？

**Comment by jourdain** [comment]
Just create the proper vtkPolyData with each line being a cell in your cell list for the line type.

**Comment by HuWei501** [comment]
![image](https://user-images.githubusercontent.com/19411208/47197617-eaf23900-d399-11e8-97ac-b58e37070983.png)
Cannot display images after actor merges.I don't know where I am doing wrong.
Can you help me figure out where to go wrong? Thank you.

**Comment by HuWei501** [comment]
`// test
const arrTest = [
  [100, 100, -396],
  [200, 100, -396],
  [200, 200, -396],
  [100, 200, -396],
];
const pointsTest = vtkPoints.newInstance();
pointsTest.setNumberOfPoints(4);
pointsTest.setPoint(0, ...arrTest[0]);
pointsTest.setPoint(1, ...arrTest[1]);
pointsTest.setPoint(2, ...arrTest[2]);
pointsTest.setPoint(3, ...arrTest[3]);

const polyData = vtkPolyData.newInstance();

const line1 = vtkLineSource.newInstance();
line1.set({ point1: arrTest[0] });
line1.set({ point2: arrTest[1] });

const line2 = vtkLineSource.newInstance();
line2.set({ point1: arrTest[1] });
line2.set({ point2: arrTest[2] });

const lines = vtkCellArray.newInstance();

lines.setData([line1, line2]);
polyData.setLines(lines);
polyData.setPoints(pointsTest);

const actorTest = vtkActor.newInstance();
const mapper = vtkMapper.newInstance();
mapper.setInputData(polyData);
actorTest.setMapper(mapper);
renderer.addActor(actorTest);`

**Comment by jourdain** [comment]
```
lines.setData(Uint16Array.from([
2, 0, 1,
2, 1, 2
]));
```

vtkLineSource is an algorithm that produce a polydata. The vtkCellArray does not expect an array of algorithm as its data. vtkDataArray/vtkPoints/vtkCellArray are only a wrapper to a specific typed array.
Therefore setData would only expect a typed array.

Also you could set the points that way:

```
pointsTest.setData(Float32Array.from(
100, 100, -396,
200, 100, -396,
200, 200, -396,
100, 200, -396
), 3);
```

**Comment by jourdain** [comment]
As a side note, you could also do something like:

```
lines.setData(Uint16Array.from([
5, 0, 1, 2, 3, 0
]));
```

**Comment by jourdain** [comment]
```
(number of points) (point index0) (point index1) ... (point indexN)
(number of points) (point index0) (point index1) ... (point indexN)
(number of points) (point index0) (point index1) ... (point indexN)
```

**Comment by HuWei501** [comment]
![image](https://user-images.githubusercontent.com/19411208/47976054-9534c500-e0eb-11e8-8387-0790c9f9c4a6.png)
This is the outline obtained by cutter cutting obj.
But some places are not continuous, is there any good solution?

**Comment by wjswlr02** [comment]
you should connect last element to first element
