### ISSUE TITLE
vtkImageSlice & vtkImageMapper slice offset problem

### ISSUE THREAD

**Issue by AndreFrelicot** [Kitware/vtk-js#916]
Hello,

I've two viewers pointing to the same data, the left viewer is showing K slices correctly but on the right I've only 3 slices with data (others are black) and there is some kind of shifting. Also when I rotate the right viewer I see clipping, I've tried changing the clipping range without success.

do you have an idea what I'm doing wrong ?

```
const data = representation.getInputDataSet();
const imageActorK = vtkImageSlice.newInstance();
model.renderer.addActor(imageActorK);
const imageMapperK = vtkImageMapper.newInstance();
imageMapperK.setInputData(data);
imageActorK.setMapper(imageMapperK);
```

![image](https://user-images.githubusercontent.com/2123744/46871620-36ed2d00-ce32-11e8-8dc5-3934af258a1d.png)

![image](https://user-images.githubusercontent.com/2123744/46871630-3a80b400-ce32-11e8-9e39-13e3b3961285.png)

**Comment by floryst** [comment]
The shifting looks like a possible bug with the slicing. What are the dimensions/spacing/origin/direction of your image, and is it a single-component or multi-component image? If you want, you can try reverting commit 88226aa4658b12ed7c03e06e78f31771f295c28e to see if that is the issue.

As for the clipping, maybe make sure your clipping ranges aren't being overwritten after interaction? I'm not too sure on this one just yet.

**Comment by AndreFrelicot** [comment]
Thank you for the reply, actually it was a stupid error in my side : setting the slice in float (Z) and not the index.
sorry !

André
