### ISSUE TITLE
Rendering is not automatically updated when async work completes

### ISSUE THREAD

**Issue by brianhelba** [Kitware/vtk-js#921]
See the example at: https://kitware.github.io/vtk-js/examples/VolumeViewer/VolumeViewer.html?fileURL=https://data.kitware.com/api/v1/item/59e12e988d777f31ac6455c5/download

The rendering updates only once the first mouse interaction occurs.

**Comment by brianhelba** [comment]
@thewtex I brought this up with @jourdain , and he directed it to you. Should something be added to every volume rendering implementation, or should this be occurring automatically?

**Comment by thewtex** [comment]
I believe we address this in the `itk-vtk-viewer` here:

https://github.com/Kitware/itk-vtk-viewer/blob/bf7a46b207bc98419547c4a1bfce4b33dcac1d6c/src/createViewer.js#L153-L155
```
proxyManager.renderAllViews();

setTimeout(view.resetCamera, 1);
```

CC: @martinken

**Comment by floryst** [comment]
This appears to be fixed. If not, please re-open with more detail.
