### ISSUE TITLE
HandleWidget example not displaying anything

### ISSUE THREAD

**Issue by thewtex** [Kitware/vtk-js#925]
Looking at:

https://kitware.github.io/vtk-js/examples/HandleWidget.html

Currently blank:

![image](https://user-images.githubusercontent.com/25432/47435719-2c585f00-d773-11e8-8b83-2f339abd552d.png)

CC: @floryst @jourdain

**Comment by thewtex** [comment]
Or the Label Widget example:

![image](https://user-images.githubusercontent.com/25432/47435877-66296580-d773-11e8-94fc-a094ff839903.png)

**Comment by jourdain** [comment]
@laurennlam

**Comment by jourdain** [comment]
For information those are old style widgets taken from VTK/C++. The new widget infrastructure is available in `Sources/Widgets/**` which use hardware picker to find handles.

**Comment by laurennlam** [comment]
@luciemac , Thanks for watching this bug.

**Comment by thewtex** [comment]
Seems to be fixed by #937 , thanks @luciemac !
