### ISSUE TITLE
Examples not running in Internet Explorer & poor performance

### ISSUE THREAD

**Issue by timothyblue** [Kitware/vtk-js#927]
[Demo](https://kitware.github.io/vtk-js/examples/PDBReader.html)

When I manage to get vtk.js to work in Internet Explorer is it very slow. Is there some way to mitigate this?

**Comment by jourdain** [comment]
Is the issue specific to that demo?

Can you report the rendering spec within that browser?

To do that:

1. [Open ParaView Glance](https://kitware.github.io/paraview-glance/app/)
2. Click on the molecule or another image that correspond to the dataset you want to load/test
3. Click on the __Global__ tab in the left drawer
4. Look at the __Rendering__ section which should give you fps and so on when interacting
5. On the right side of the __Rendering__ title you have a (?) icon, which should provide you with additional information regarding your GPU and which WebGL is used for rendering?

BTW, which version of IE?

Thanks!

**Comment by timothyblue** [comment]
Many of the examples do not work. Some are syntax errors, some are mixed content (https and http) like the SpheresAndLabels demo.

The ParaView link you sent works wonderful in Chrome, but does not load at all in IE.

I get the following errors:
```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
app
HTML1300: Navigation occurred.
app
SCRIPT1002: Syntax error
vendors.js (1,1697)
SCRIPT5009: 'Glance' is undefined
app (39,7)
```
I am using IE11 Version: 11.726.16299.0 with no emulation mode selected.

**Comment by jourdain** [comment]
I see, that's most likely because we didn't build the examples with a browser target that include IE11.

May I ask why using IE11 instead of Edge, Chrome or Firefox?

**Comment by timothyblue** [comment]
IE11 is a customer requirement. Our customers are large corporations which often outsource their IT departments. We do not have the ability to dictate which browsers are installed on these machines and they tend to be locked down to the point where the user cannot install a new browser themselves.

**Comment by jourdain** [comment]
Thanks I'll see to update the build to support IE.

**Comment by dannyrb** [comment]
Was this resolved here?: https://github.com/Kitware/vtk-js/issues/930

Are there outstanding IE issues or a known lack of support for some features/functionality?

**Comment by jourdain** [comment]
If someone with IE11 could verify that, it would be great.

**Comment by floryst** [comment]
If IE11 still has issues, feel free to re-open. However, note that we currently have no interest in supporting IE11 or predecessors, as even Microsoft is phasing out support for the browser in their products.
