### ISSUE TITLE
OrientationMarkerWidget does not work in Edge

### ISSUE THREAD

**Issue by timothyblue** [Kitware/vtk-js#929]
This example demonstrates this defect [OrientationMarkerWidget Demo](https://kitware.github.io/vtk-js/examples/OrientationMarkerWidget.html)

**Comment by floryst** [comment]
Closing due to age, but if this is still an issue please re-open. Note that if this is Edge on the EdgeHTML engine, then we currently do not have interest in supporting those specific issues.
