### ISSUE TITLE
Handles for vmin / vmax changes in PiecewiseGaussianWidget

### ISSUE THREAD

**Issue by thewtex** [Kitware/vtk-js#932]
@jourdain I do not have the funding or time to implement this myself at the moment, but I want to get your thoughts and feedback:

It would be very nice to have handles on the left and right side of the PiecewiseGaussianWidget to adjust the min / max of the histogram and associated color transfer function.

These handles would:

- Look like something that can be grabbed
- Be located on the left and right edges of the histogram box
- Highlight on mouseover, and display the current min or max value
- Could be dragged left or right, which would update the min or max on release

What do you think?

**Comment by jourdain** [comment]
I'm guessing that relate to your usage when the window range was control by opacity above 0. In that case, you would like to have dedicated control to either grow or shrink that range that will only adjust the range of the color map?

I think that should be fine especially if it is a behavior mode that you can enable/disable like we have with the dynamic range one.

Do you foresee a usage where the goal is to grow that range outside the actual data range?

**Comment by thewtex** [comment]
> I'm guessing that relate to your usage when the window range was control by opacity above 0. In that case, you would like to have dedicated control to either grow or shrink that range that will only adjust the range of the color map?

There are many times, especially with float data, that the intensities of interest are concentrated in a small range. The min / max intensities can be far from this range, and you just see a tight little blip in the histogram. So it would nice to adjust the color range but also see the histogram in this range when adjusted.

> I think that should be fine especially if it is a behavior mode that you can enable/disable like we have with the dynamic range one.

Cool :cool: 

> Do you foresee a usage where the goal is to grow that range outside the actual data range?

Good point -- another desired behavior is that the UI would pin the lower and upper bound to the min / max of the data when expanding the range.

**Comment by jourdain** [comment]
I see, I start having some idea, but when ever you are ready on that end, we should talk face to face so we could run various scenario and see if we properly address them.

**Comment by thewtex** [comment]
Addressed in https://github.com/Kitware/vtk-js/pull/1183
