### ISSUE TITLE
I cannot load polydata

### ISSUE THREAD

**Issue by samleeeg** [Kitware/vtk-js#934]
I've tried many times, but I couldn't load polydata.
I also tested with uploaded file(https://data.kitware.com/api/v1/file/59de9de58d777f31ac641dc6/download)
but it didn't work.
Please check mistakes.
I'm using Django.
I checked vtkPolyDataReader, vtkXMLPolyDataReader.
I checked file download with Chrome Developer Tools network tab.

```{% load staticfiles %}
<!DOCTYPE html>
<html>
<body>
<script type="text/javascript" src="https://unpkg.com/vtk.js"></script>
<script type="text/javascript">  
  var fullScreenRenderer = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance();  
  var actor = vtk.Rendering.Core.vtkActor.newInstance();
  var mapper = vtk.Rendering.Core.vtkMapper.newInstance();
  //var reader = vtk.IO.Legacy.vtkPolyDataReader.newInstance();  
  var reader = vtk.IO.XML.vtkXMLPolyDataReader.newInstance();
	
  reader.setUrl('https://data.kitware.com/api/v1/file/59de9de58d777f31ac641dc6/download');
  //reader.setUrl('http://127.0.0.1:8000/static/img/test2.vtk');
  var polydata = reader.getOutputData(0);  
  
  actor.setMapper(mapper);  
  mapper.setInputData(polydata);
  
  var renderer = fullScreenRenderer.getRenderer();
  renderer.addActor(actor);
  renderer.resetCamera();
  var renderWindow = fullScreenRenderer.getRenderWindow();
  renderWindow.render(); 
  
</script>
</body>
</html>

**Comment by jourdain** [comment]
The file you try to load is not the legacy format but the XML one.
Therefore, the reader that you should use is `vtk.IO.XML.vtkXMLPolyDataReader`.

**Comment by samleeeg** [comment]
As the code above, I used vtk.IO.XML.vtkXMLPolyDataReader for XML one and vtk.IO.Legacy.vtkPolyDataReader for legacy one. But it didn't work. No input message is all I have received. Please help me.
