### ISSUE TITLE
Can I add a scalar bar?

### ISSUE THREAD

**Issue by samleeeg** [Kitware/vtk-js#944]
I found some information of lookuptable, but I couldn't find any information about scalar bar.
Can I add a scalar bar?

**Comment by jourdain** [comment]
There is no scalar bar that goes in the 3D view, but it is fairly easy to create one in plain HTML by asking the LookupTable to create an image for you. 

Some example on how to do something like that can be found [here](https://github.com/Kitware/paraview-glance/blob/v1.1.14/Sources/properties/LookupTableProperty/index.js).

**Comment by samleeeg** [comment]
Thank you for your advice.
