### ISSUE TITLE
Use wtk.js vtkXMLPolyDataReader class to load data from XML string

### ISSUE THREAD

**Issue by pbaras** [Kitware/vtk-js#945]
Hello,
I try to use the vtkXMLPolyDataReader in a javascript, but i don't want to use a file, i receive a XML in a string : 
`<?xml version="1.0"?><VTKFile type="PolyData" version="0.1" byte_order="LittleEndian" header_type="UInt32" compressor="vtkZLibDataCompressor"><PolyData><Piece NumberOfPoints="38496" NumberOfVerts="0" NumberOfLines="0" NumberOfStrips="0" NumberOfPolys="53488">...`
 

How I can load this data in the vtkXMLPolyDataReader .
I try vtkXMLPolyDataReader.loadData(xml_string); but it does not seem to work.
Many thanks for your help.

Patrick

**Comment by jourdain** [comment]
We expect binary argument as often the XML is not a fully XML content and binary elements can be part of it. But we could have a custom/dedicated method for pure string/XML file.

**Comment by jourdain** [comment]
Oh, BTW, the method to use is not loadData (That's for when you provide a URL) but `parseAsArrayBuffer()` instead.

**Comment by floryst** [comment]
If this is still an issue, please re-open.

**Comment by ZbindenJoel** [comment]
@floryst Can we reopen this issue?

I am facing the same problem now. 
I am getting the contents of a `.vtp` file as a string from another element in my web-app and would like to read that string using the XMLPolyDataReader. Reading directly from file is unfortunately not an option.

Unfortunately, using the `parseAsArrayBuffer(XMLFileString)` function suggested by @jourdain above returns an error saying `TypeError: TextDecoder.decode: Argument 1 could not be converted to any of: ArrayBufferView, ArrayBuffer.`.

For examples, here is one of the files I would like to load: 
[sample_mesh.zip](https://github.com/Kitware/vtk-js/files/8999189/sample_mesh.zip)

**Comment by daker** [comment]
@ZbindenJoel parseAsArrayBuffer needs an `ArrayBuffer` to work not a string
