### ISSUE TITLE
The outline obtained by cutter cutting obj is not continuous in some places

### ISSUE THREAD

**Issue by HuWei501** [Kitware/vtk-js#950]
The outline obtained by cutter cutting obj is not continuous in some places. Is there any way?
![image](https://user-images.githubusercontent.com/19411208/48321764-1e557a00-e65f-11e8-8823-002491bf4d86.png)

**Comment by floryst** [comment]
Either this is a bug with vtkCutter, or your polydata is incomplete. In any case, providing a reproducible test case for this issue is the best way to resolve this at the moment.
