### ISSUE TITLE
Disabling key binds

### ISSUE THREAD

**Issue by cjh1** [Kitware/vtk-js#951]
vtk.js is listening to all key events in the browser window. For example if I type 'w' the rendering switches to wireframe. This is somewhat problematic in an environment such as JupyterLab as typing in a cell will change the viz. See image below:
![both](https://user-images.githubusercontent.com/1031053/48501698-c90a9b80-e80b-11e8-91e3-2c1763d495d2.png)

Is there away to disable these key binding?

**Comment by cjh1** [comment]
@jourdain Thanks, figured there must be away, can you point me to an example of its use?

**Comment by jourdain** [comment]
https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html

And you can also see what we are doing inside the view proxy here:

https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/ViewProxy/index.js#L46-L51
