### ISSUE TITLE
selectColorArray is missing from Mapper index.js source code in vtk.js? 

### ISSUE THREAD

**Issue by astenta** [Kitware/vtk-js#953]
I am trying to use selectColorArray in vtk.js, but it does not seem to exist in the Mapper index.js source code? I was able to use the function properly in python VTK, but it does not exist in the javascript version even though the user manual states that it should be there? 

Here is a link to the manual, showing that it should be an available function, but it is not in the source code at the bottom of the page?
https://kitware.github.io/vtk-js/api/Rendering_Core_Mapper.html#selectColorArray-arrayName-component-1

**Comment by astenta** [comment]
Thank you for your response. We will attempt this and let you know if it works.

**Comment by dspring2** [comment]
Using the setColorByArrayName doesn't seem to work quite as expected. I created a CodePen (https://codepen.io/dspring86/pen/dQKxYB) that tries to illustrate the issue. In a first step, we're trying to create a tube with a simple color contour over the surface, where the color changes from red to green over the length of the tube and the tube can have a varying radius. 

Everything we've tried seems to result in a tube that is fully red, or some weird graphic artifacts. Any chance someone might have some insight into what we're doing incorrect?

**Comment by jourdain** [comment]
Your color is a vector that has the same magnitude so the color would remain the same unless you explicitly say that you want to use the RGB from the data itself and not use a LookupTable to convert a vector into a color. 
But the issue might not just be that.

**Comment by jourdain** [comment]
This would work

```
// Load script from https://unpkg.com/vtk.js then...
// Render a tapered cylinder with a color contour on its surface,
// ranging from red at one end to greeen at the other end
const numPoints = 2;
const points = vtk.Common.Core.vtkPoints.newInstance();
var polyData = vtk.Common.DataModel.vtkPolyData.newInstance();

// Create a color array containing red and green
const colorArray = vtk.Common.Core.vtkDataArray.newInstance({
  name: "Colors",
  numberOfComponents: 3,
  values: Uint8Array.from([0, 255, 0, 255, 0, 0]),
});

// Create the tapered cylinder data
var pointData = new Float32Array(3 * numPoints);
var radiusData = new Float32Array(numPoints);
var verts = new Uint32Array(2 * numPoints);
var lines = new Uint32Array(numPoints + 1);

// Cylinder axes from (0,0,0) to (12,0,0)
pointData = [0.0, 0.0, 0.0, 12.0, 0.0, 0.0];

// Taper cylinder radius from 1 to 3
radiusData = [1.0, 3.0];

verts = [1, 1, 1, 0];
lines = [2, 0, 1];

const radius = vtk.Common.Core.vtkDataArray.newInstance({
  name: "Radius",
  values: radiusData
});

// Create the polyData and assign it the data used for the cylinder
points.setData(pointData);
points.setNumberOfPoints(numPoints);
polyData.setPoints(points);
polyData.getVerts().setData(verts);
polyData.getLines().setData(lines);

// Add the radius and colorArray arrays to the pointData
polyData.getPointData().addArray(radius);
polyData.getPointData().addArray(colorArray);

// Create a tubeFilter for the cylinder
const tubeFilter = vtk.Filters.General.vtkTubeFilter.newInstance({ varyRadius: 3 });
tubeFilter.setCapping(true);
tubeFilter.setNumberOfSides(3);
tubeFilter.setInputData(polyData);
tubeFilter.setInputArrayToProcess(0, "Radius", "PointData", "Scalars");

// Create the mapper, and assign it to setColorByArrayName
const tubeMapper = vtk.Rendering.Core.vtkMapper.newInstance();
tubeMapper.setInputConnection(tubeFilter.getOutputPort());
tubeMapper.setColorByArrayName('Colors');
// tubeMapper.setInputData(polyData);
tubeMapper.setScalarModeToUsePointFieldData();
tubeMapper.setColorModeToDirectScalars();
tubeMapper.set({
  scalarVisibility: true,
  interpolateScalarsBeforeMapping: false,
});

// Assign the mapper to an actor
const tubeActor = vtk.Rendering.Core.vtkActor.newInstance();
tubeActor.setMapper(tubeMapper);

// Create the renderer and display the colored tube
var fullScreenRenderer = vtk.Rendering.Misc.vtkFullScreenRenderWindow.newInstance();

var renderer = fullScreenRenderer.getRenderer();
renderer.addActor(tubeActor);
renderer.resetCamera();

var renderWindow = fullScreenRenderer.getRenderWindow();
renderWindow.render();
```

but the tube filter might be doing something wrong when mapping the vector RGB over. @sankhesh

**Comment by dspring2** [comment]
Thank you for the response. However, with the method you list above, I see some odd artifacts in the render. It doesn't look like the tube anymore.
![image](https://user-images.githubusercontent.com/13966398/49033141-61920b80-f17c-11e8-9beb-dff0ae92a207.png)

**Comment by jourdain** [comment]
Yes that's why 

> but the tube filter might be doing something wrong when mapping the vector RGB over.

As if you uncomment `tubeMapper.setInputData(polyData);` you will get the expected behavior.

**Comment by dspring2** [comment]
I see, so even when I uncomment that line, the contour looks correct, from red to green, but it is only over a line, not over the tube. 

![image](https://user-images.githubusercontent.com/13966398/49033444-3956dc80-f17d-11e8-901c-8dbe476b594f.png)

So something may be wrong with the tube filter, like you mentioned

**Comment by jourdain** [comment]
Yes uncommenting that line is just by-passing the tube filter. But you can try with a scalar value, that will probably work.

But did you notice the correct way of setting the data arrays and how to apply a direct RGB mapping if you have one? 

In fact, I'm surprised that using JS array is working for the rest of the fields...

**Comment by dspring2** [comment]
Yes, that makes things more clear, than you! Once any issue with the tube filter is discovered, we should be able to accomplish what we need.

**Comment by jourdain** [comment]
Try with a scalar value...

**Comment by sankhesh** [comment]
Yep, seems like a bug in the tube filter. 

Looking at https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/General/TubeFilter/index.js#L354, it seems like the point data is indeed passed correctly to the output (or that's the intent anyway) from the input. 

Someone will have to take a deeper look. I am happy to, but don't have cycles at the moment.

**Comment by dspring2** [comment]
It's not 100% clear to me if I've done this right, but if I have, it still displays the artifacts when I use the lookupTable approach (https://codepen.io/dspring86/pen/jQpyPO)

![image](https://user-images.githubusercontent.com/13966398/49042218-7f1f9f00-f195-11e8-8938-322b1abd2d5f.png)

**Comment by jourdain** [comment]
There is definitely an issue with the passArray used inside the tubeFilter. I was hoping the issue to be limited with vectors. 

I don't have any cycle to look into it. Anyone would like to fix it?

@vibraphone @floryst

**Comment by dspring2** [comment]
I opened a PR that should fix the problem https://github.com/Kitware/vtk-js/pull/959

**Comment by jourdain** [comment]
Thanks but this is not a correct fix, although some stuff that you did are good and should go in. I'll comment more on your PR.

**Comment by dspring2** [comment]
Okay, thank you!

**Comment by dspring2** [comment]
Okay, I modified the approach I was taking and created a new PR https://github.com/Kitware/vtk-js/pull/960

I suspect it still needs some modification to be more in line with how you might have solved it, but please let me know what changes I could make, or if I'm still off with the approach.

**Comment by jourdain** [comment]
If this is still an issue, please re-open.
