### ISSUE TITLE
after setviewmatrix ,my model don't rotate by droping mouse

### ISSUE THREAD

**Issue by yuhangli1991** [Kitware/vtk-js#954]
render.getActiveCamera().setViewMatrix(viewshot);

**Comment by jourdain** [comment]
The camera is controlled by (viewUp, position, focalPoint). When you provide the viewMatrix, that take precedence to anything. That's why the camera is not going to move anymore...

**Comment by yuhangli1991** [comment]
thanks. i use viewUp, position  and focalPoint to controller camera.,it works!
