### ISSUE TITLE
Export for TubeFilter

### ISSUE THREAD

**Issue by dspring2** [Kitware/vtk-js#956]
Would it be possible to export vtkTubeFilter in: 

https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/General/index.js

I'm trying to create a newInstance of a vtkTubeFilter in CodePen, but am unable to access it using https://unpkg.com/vtk.js

Alternatively, if someone can direct me on how to access vtkTubeFilter in any other way, in CodePen. I'm trying to access it using: 

const tubeFilter = vtk.Filters.General.vtkTubeFilter.newInstance();

which does not work.

**Comment by jourdain** [comment]
Yes that is missing. If you can, please provide a PR with the add of the proper import in that index file.
Thanks for reporting the issue...

**Comment by jourdain** [comment]
FYI @sankhesh

**Comment by dspring2** [comment]
Okay, PR made: https://github.com/Kitware/vtk-js/pull/957

**Comment by jourdain** [comment]
Fixed in 8.2.1
