### ISSUE TITLE
Touch start / Mouse down events

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#962]
I have a custom interactor style which inherited from vtkInteractorStyleTrackballCamera. In this class, I have overwritten the HandleLeftButtonPress method.
The problem comes when we use an android tablet because the touching interactions always call TouchStart and MouseDown events. Theses two events calls the method leftButtonPressEvent which calls my custom HandleLeftButtonPressEvent.
So, when I touch once a mesh, then the custom HandleLeftButtonPress event is called twice instead of once.
Do you have any idea on how I can avoid it ?

Thanks.

**Comment by jourdain** [comment]
Either you guard the press so it can not be called twice or you detect the browser and do something different regarding the event binding/listeners...

**Comment by laurennlam** [comment]
Yes I was thinking to detect the device. It seems to be better because I have to keep the mouse down when the webpage is used on a computer.
Thanks.
