### ISSUE TITLE
Adding Modifier keys to scroll interaction

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#963]
I'd like to have different events triggered on the mouse wheel depending on the presence of any modifying key.  For example (in 2d), set the slice with just the mouse wheel, but perhaps zoom with _shift_ + mouse wheel.  I'm looking at the code for `vtkInteractorStyleManipulator`, and that doesn't seem to be possible with the current way that the manipulator instance is [found](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Style/InteractorStyleManipulator/index.js#L430-L441) (it just takes the first one that is scroll enabled).  

I realize that the modifier keys would need to be added to the call data from the `vtkRenderWindowInteractor`, but before I go and attempt to modify any code elsewhere I wanted to see if there was a good reason as to why identifying the manipulator during scroll events was different than during others.  Are there any potentially hidden issues with implementing something along the lines of: 
```
    let manipulator = null;
    let count = model.mouseManipulators.length;
    while (count--) {
      const manip = model.mouseManipulators[count];
      if (
        manip.isScrollEnabled() &&
        manip.getShift() === callData.shiftKey &&
        manip.getControl() === callData.controlKey &&
        manip.getAlt() === callData.altKey
      ) {
        manipulator = manip;
      }
    }
    ...
```

Or should it be approached in a different way?  Happy to help implement any changes where I can.

Thanks,
-Logan

**Comment by jourdain** [comment]
Are we sure that a scroll event in JS have those modifier available on all browsers? One issue we have with scroll is that we don't always have a mouse position. I'm wondering if it is also true with the modifier.

Otherwise, I kind of agree of the extra-check regarding the modifier assuming they are always present in the event that we get from the browser.

**Comment by llangholz89** [comment]
Good point.  I did a quick test with the browsers on my computer and Chrome, Firefox, and Safari all seem to give the shift, control, and alt modifiers.  I'd have to do a bit more research on the others.  

For now, I'll assume that they will be present and can put together a pr with those edits.

**Comment by jourdain** [comment]
Sounds good, thanks for doing that!
