### ISSUE TITLE
Create a polyline

### ISSUE THREAD

**Issue by johannesring** [Kitware/vtk-js#975]
I would like to create a polyline in vtk.js. In Python I would do it as in [this](https://www.vtk.org/Wiki/VTK/Examples/Python/GeometricObjects/Display/PolyLine) example. How can I do the same in vtk.js?

**Comment by jourdain** [comment]
```
polygon = vtkPolydata.newInstance();
polygon.getPoints().setData(Float32Array.from([
  0, -1, 0,
  c, -0.5, 0,
  c, 0.5, 0,
  0, 1, 0,
  -c, 0.5, 0,
   -c, -0.5, 0,
]), 3);

polygon.getLines().setData(Uint16Array.from([
 7, 0, 1, 2, 3, 4, 5, 0
]), 3);
```

**Comment by johannesring** [comment]
Great, thanks a lot! Unfortunately, it looks like it doesn't work to set the line width. I tried with `actor.getProperty().setLineWidth(5)`, but that didn't change the line width.

**Comment by jourdain** [comment]
Yes line width is not supported in WebGL. And tricks to support it haven't been implemented yet.
We know how to do it, but we don't have the funds to do it right now.

**Comment by johannesring** [comment]
Ok, thanks! Would you say it requires a lot of work to implement these tricks?

**Comment by jourdain** [comment]
I think @martinken said it should be a couple days. But I can't be sure. Hopefully he'll comment. Are you thinking of having a support contract with us to enable such feature sooner?

**Comment by johannesring** [comment]
Well, I was thinking about helping out with this, but I have now found a satisfactory solution to my problem by using a vtkTubeFilter to create a tube along the line and use radius to change the width.

Thanks for your help. I also have a different problem, but I will open a new issue for that.
