### ISSUE TITLE
latest npm version (8.3.2) via unpkg is broken

### ISSUE THREAD

**Issue by pieper** [Kitware/vtk-js#984]
Using the suggested script url, https://unpkg.com/vtk.js, results in an error from unpkg `Cannot find "/index.js" in vtk.js@8.3.2`.

But specifying the previous version https://unpkg.com/vtk.js@8.3.1 works as expected.

**Comment by mix3d** [comment]
Is this still an issue, now that it's up to v8.13.0?

**Comment by jourdain** [comment]
Seems to be working now...
