### ISSUE TITLE
Is there a  unstructured grid reader?

### ISSUE THREAD

**Issue by cathty** [Kitware/vtk-js#986]
Is there a  unstructured grid reader?
thanks

**Comment by jourdain** [comment]
Not right now. But even if a reader could be done fairly quickly, the extract surface filter will need to be implemented in order to render that unstructured grid which is more complex to implement than the reader.

**Comment by cathty** [comment]
Jourdain,
thanks your reply. if there is a  unstructured grid, can it transfer unstructured grid to polydata ?so it can save a lot of work.

**Comment by agirault** [comment]
As @jourdain said converting from unstructured grid to polydata (surface mesh, which is necessary for rendering) is the most complex part to be implemented. You can follow up on unstructured grid support at #976
