### ISSUE TITLE
Remove a color from labelMap

### ISSUE THREAD

**Issue by ericdebleumortier** [Kitware/vtk-js#988]
Hello,

I'm using [this example](https://kitware.github.io/vtk-js/examples/PaintWidget.html) with the paintFilter and the labelMap. I managed to add multiple labelMaps with different colors.

Basically I have this

```
labelMap.cfun.addRGBPoint(0, 0, 0, 0); // label "0" will be the eraser
labelMap.cfun.addRGBPoint(1, 0, 0, 1); // label "1" will be blue
labelMap.cfun.addRGBPoint(2, 0, 1, 0); // label "2" will be green
labelMap.cfun.addRGBPoint(3, 1, 0, 0); // label "2" will be red
```

And I switch between labels when I want to draw in a different color.

Now I want to erase every point picked for a given label. Is it possible?
I found out that I can use `labelMap.cfun.removePoint( id );` 

But it doesn't seems to work as expected (maybe I use the wrong way to create the colors?).
If a draw a point in `blue `and then do `removePoint(1)`, this point is become `green`. Then `removePoint(2)` and it's `red` and then `removePoint(3)` but it still "dark/black".

If I use the label 0, the "eraser", over an existing point, then it disapear completly as expected.
Can you help me to understand the behaviour of label/painting?

Thanks!

**Comment by floryst** [comment]
If you want to erase every pixel point that has a given label, you should loop through your image and set the desired pixels to 0. 

The `cfun.removePoint` method removes a point from your color transfer function, which only affects the rendering of your labelmap. It doesn't change values in your labelmap. When you removed your blue point from cfun, the colormap has to interpolate to pick a color for the label value 1, which will be between "eraser" and "green".

Hope that helps clarify what you are experiencing.

**Comment by ericdebleumortier** [comment]
Hi, 

Thanks for you explanation, that's much clearer ;-)
